### ISSUE TITLE
[feature request]support for notification-center for android and ios

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#1007]
## What?
We have notification center as a react component for web. Can we have a similar component/library for android and ios?

## Why?
A clear and concise description of why this feature is important or you need it as a user...
This feature will help users to use In App notification feature in most of the mobile devices

**Comment by oba2311** [comment]
@jainpawan21  is that something you would like to work on?

**Comment by jainpawan21** [comment]
I have limited knowledge of native android and ios. Previously I have worked with react-native. 
Let me explore, how to create libraries for ios and android

**Comment by Myzel394** [comment]
I'm facing issues integrating Novu into React Native (Expo to be precise) - is there a workaround to just access the APIs?

**Comment by jainpawan21** [comment]
Check out this https://docs.novu.co/api/overview/

**Comment by Myzel394** [comment]
@jainpawan21 I mean these APIs: https://docs.novu.co/notification-center/react/react-components

It seems as if they depend on `NovuProvider`, which depends on `document`, which is not available on React Native

**Comment by scopsy** [comment]
@Myzel394 quite late to the party, but we recently published a react native dedicated package https://docs.novu.co/inbox/react-native/quickstart
