### ISSUE TITLE
Unread notification count is not updating real time in notification-center

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#1008]
**Describe the bug**
In the main branch, this notification count is not updating in real-time. I have 3 unread notifications, still it is showing 1. If I refresh this page then it will show 3 

**To Reproduce**

1. Run the project in local
2. Create one notification and workflow with in-app as one of the step
3. Trigger the notification to yourself using subscriberId as your userid
4. Click on bell icon on the header 
5. See after every trigger new notification will come, but unread count will not change

**Expected behavior**
Unread count should change in real time

**Screenshots**
![image](https://user-images.githubusercontent.com/39362422/183985757-aa388a25-3943-4f6a-b2e1-3f185b8821c5.png)

**Details (please complete the following information):**
 - OS: Mac
 - Node Version: v16.14.0

**Comment by scopsy** [comment]
Hi @jainpawan21 could you please verify `apps/ws` is running correctly on your local machine? And also what browser are you using?

**Comment by jainpawan21** [comment]
@scopsy, Yes apps/ws is running. I am using chrome browser.

**Comment by oba2311** [comment]
@jainpawan21 are you currently working on this one?

**Comment by jainpawan21** [comment]
Yes, I am working

**Comment by lawweiliang** [comment]
@scopsy, 

Since @jainpawan21 is working on this task. 
Maybe you can directly assign this task to him.
Other contributor like me can ignore this issue and  focus on other. 😃

**Comment by scopsy** [comment]
@jainpawan21 is that something we can close? I couldn't reproduce this on multiple scenarios. Are you still experiencing this?

**Comment by jainpawan21** [comment]
yes we can close this.
