### ISSUE TITLE
[NV-780] - DingTalk Support

### ISSUE THREAD

**Issue by yvan-wyf** [novuhq/novu#1016]
## What?
Describe what is your feature/change request

DingTalk Support ：https://www.dingtalk.com/

## Why?
very popular in China

## How?
ChatOps

**Comment by oba2311** [comment]
@yvan-wyf will you be interested in tackling this?

**Comment by kymppi** [comment]
I can try this today/tomorrow. Never used DingTalk so i might not be able to do it, but will try.
