### ISSUE TITLE
[NV-782] - WhatsApp Provider

### ISSUE THREAD

**Issue by escobar5** [novuhq/novu#1019]
## What?
It would be nice to have a provider to send WhatsApp notifications

## Why?
WhatsApp is being currently used in many use cases to notify users about deliveries, app updates, etc.

## How?
Integrating WhatsApp for Business API. The difficult part, I think, may be the WhatsApp enterprise onboarding, after that, integrating the API is simpler. Another option would be Twillio Messaging for WhatsApp.

**Comment by oba2311** [comment]
@escobar5 interested in working on this?

**Comment by escobar5** [comment]
> @escobar5 interested in working on this?

yes, let me check the code first

**Comment by Smartmind12** [comment]
@scopsy & maintainers can i work on this issue for Hacktoberfest 2022?

**Comment by escobar5** [comment]
@oba2311 I'm now creating the WhatsApp Provider using WhatsApp Business API, I have a question though, there's an `IChatOptions` interface, I first thought as WhatsApp is a chat application I may use this, but it doesn't have a `to` property, maybe `ISmsOptions` may be a better option, it does have the `to` property and also `attachments`. What do you think?

**Comment by scopsy** [comment]
I think that `IChatOptions` is the way to go, tho I think we should extend to also work with the `to` field for a phone number. We would need to do a conditional in the send-chat-message.usecase, so depending on provider we either use the to field or the webhook URL. 

What do you think about this approach @escobar5 ?

**Comment by escobar5** [comment]
Yes, sounds good, @scopsy can you assign this to me, so I continue working on it?

**Comment by scopsy** [comment]
@escobar5 do you still want to take a look at this?

**Comment by inglesuniversal** [comment]
Really hope this feature is implemented as planned

**Comment by vipulsharma144** [comment]
@escobar5 are you working on this?

**Comment by escobar5** [comment]
> @escobar5 are you working on this?

Hi, no, not working on it, I was awaiting for confirmation from maintainers, but now I have no availability unfortunately

**Comment by antoniodinovi** [comment]
I did a simple implementation using the whatsapp business api here #3575 , is still in draft and can be improved. Any opinion on that ?

**Comment by bitpickle** [comment]
I was wondering if it would be possible to use a webhook provider (email, for example) to tap into an api integrated with VenomBot.

The api will handle all the whatsapp part, novu just needs to deliver the message via webhook.

I'll test it and bring you news.
