### ISSUE TITLE
Upgrade Novu Issue Templates to use Github Issue Forms

### ISSUE THREAD

**Issue by Rutam21** [novuhq/novu#1022]
## Introduction
GitHub has already rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This allows to create interactive issue templates and validate them.

Novu currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). The task is to create GitHub issue forms for this repository. The issue form needs to be designed to accommodate all the fields in the current issue template.

## Tasks Summary
 - Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 - Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 - Push changes to the fork and test issue forms
 - Submit pull request

**Comment by Rutam21** [comment]
@scopsy Please check this issue and assign it to me so that I can work on it. Thanks.

**Comment by scopsy** [comment]
This is so cool! Let's do it 🚀
