### ISSUE TITLE
[Bug]: Password visibility toggle buttons inside `PasswordInput` are not accessible by keyboard.

### ISSUE THREAD

**Issue by sachinsom93** [novuhq/novu#1027]
**Describe the bug**
Password visibility buttons present in Sign Up and Login In pages are not accessible by keyboard. User can't focus on them using `tab` or `shift + tab` keys.

**To Reproduce**
1. Setup project locally.
2. Run `npm run start:web` and go to `http://localhost:4200/auth/signup` on your browser.
3. Try to input fields using keyboard (`tab` or `shift + tab`).
4. When focus comes to password field, the focus directly goes to `SignUp` button without coming to `toggle password visibility button (the eye icon)` that makes it keyboard inaccessible.

**Expected behavior**
After coming inside password field, user should directed to `toggle password visibility button (the eye icon)`  after tapping `tab` key from keyboard.

**Screenshots**
https://user-images.githubusercontent.com/64790109/184601027-25ddec1a-02a9-420d-b2ce-e93437c35e50.mp4

**Details (please complete the following information):**
 - OS: [Windows]
 - Node Version [16.0.0]

**Additional context**
Not sure, if the visibility button is intentionally made inaccessible by keyboard or not. Would love to raise PR if it's not intentional.

**Comment by oba2311** [comment]
@scopsy let's assign to @sachinsom93 ?
