### ISSUE TITLE
Add a CODE_OF_CONDUCT file for this repository

### ISSUE THREAD

**Issue by Rutam21** [novuhq/novu#1037]
## Description
Novu is a growing open source project that will be collaborating with a huge Contributor base in the times to come. So, this repository needs to have a standard CODE_OF_CONDUCT file that would drive and govern the interaction of each of the individual contributors participating here.

## Solution
The Github [CODE_OF_CONDUCT](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) Guide can be followed and a suitable template may be chosen as the Code_of_Conduct file for this repository.

**Comment by Rutam21** [comment]
@scopsy Please assign this issue to me and I can submit a PR soon.

**Comment by scopsy** [comment]
@Rutam21 we already have a conduct here: https://docs.novu.co/community/code-conduct Maybe we can create a file in the github repo and from the file to point to our site in docs?

**Comment by Rutam21** [comment]
@scopsy We can rather create a file and use the same content here. Generally, all the repos have the content in the repository file itself.

**Comment by scopsy** [comment]
Got ya, so let's copy it's contents than.
