### ISSUE TITLE
Add Kannel SMS provider

### ISSUE THREAD

**Issue by ComBarnea** [novuhq/novu#1050]
## What?
To add [kannel](https://kannel.org/) as a new SMS provider, similar the the NodeMailer Email provider, an underlying protocol provider.

## Why?
So kannel users, and people who want to use SMS gateway could do that with Novu, while simply hosting kannel on their network.

## How?
First thing, the assumption is a kannel server is already up and running. Looking into [kannel userguide](https://kannel.org/download/1.4.5/userguide-1.4.5/userguide.html), section Table 7-17. SMS Push (send-sms) CGI Variables we can see how send SMS using this game. See below basic 

| Property  | Description |
| ------------- | ------------- |
| username  | configured to use kannel interface  |
| password  | configured to use kannel interface  |
| from  | shortcode  |
| to  | cellphone number  |
| smsc  | an id of the connection,  usually given for each mobile operator  |
| text  | text of the SMS, URL encoded  |
| priority  | Sets the Priority value (range 0-3 is allowed). (Defaults to 0, which is the lowest priority). |
| meta-data - optional  | For SMPP  |
| dlr-mask  | Request for delivery reports with the state of the sent message  |
| dlr-url  | Request for delivery reports with the state of the sent message wehbook url  |

Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

## Usage
Example for Kannel SMS provider registration needs to be finalized.
```ts
await notifire.registerProvider(
  new KannelSmsProvider({
    username: process.env.KANNEL_USERNAME,
    password: process.env.KANNEL_PASSWORD,
    host: process.env.KANNEL_HOST,
    port: process.env.KANNEL_PORT,
    dlr-mask: process.env.KANNEL_DLR_MASK, // most likely mask 31 so Novu can get all reports
    dlr-url: process.env.KANNEL_DLR_URL,
  })
);
```

## More Information
In order for Kannel integration to work there is one major change from other "simple" SMS provider, that is the smsc variable. In most cases this is being handled by SMS provider, in Kannel this needs to be passed, and in case the mobile operator was not found/found not found on mobile operator, a response using dlr-mask,  another mobile operator should be tried.

This could be resolved as a variable in the `trigger` function, and an iterative process up until the message was received on the phone or the mobile operator. Can see mapping [here](https://gist.github.com/grantpullen/3d550f31c454e80fda8fc0d5b9105fd0).

**Comment by has9800** [comment]
Hey, I want to give this a try, can someone assign it to me? Thanks

**Comment by scopsy** [comment]
Hi @has9800 sure thing, assigning you right now 🙏

**Comment by scopsy** [comment]
Hi @has9800 did you had a chance to look at this? Let me know if I can un-assign you perhaps someone else can help with this. 🙏

**Comment by abhisheksunil2201** [comment]
@scopsy Can you assign this to me if it is not being worked on?
