### ISSUE TITLE
🚀 Feature:  Change 'support documentation' location on the web

### ISSUE THREAD

**Issue by djabarovgeorge** [novuhq/novu#1068]
### 🔖 Feature description

The following section should be at the bottom of the page.

![Uploading image.png…]()

### 🎤 Why is this feature needed ?

At the user will switch between the pages this section won't be moving intuitively.

### ✌️ How do you aim to achieve this?

At the moment this section lives under AppShell -> SideNav. 
Maybe this section can go on the outer footer component.

### 🔄️ Additional Information

At the moment this component is available on the 'release/0.7.0' branch 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by Rutam21** [comment]
@djabarovgeorge The image seems to be broken. Can you please re-upload it? Also, you can assign this to me. I would like to give it a try.

**Comment by djabarovgeorge** [comment]
Hey @Rutam21,
You are right looks like it is broken, thanks for raising it up! :)

Let me try to update it again

![image](https://user-images.githubusercontent.com/39195835/185567811-bdf2ea3f-08e2-4b9c-95fc-17adebeeff22.png)

**Comment by djabarovgeorge** [comment]
@Rutam21 
I Assigned you, let us know if you need any further assistance.

**Comment by abhinavsaurav** [comment]
@djabarovgeorge  Can you assign this to me ? 

I was looking into it and have successfully figured out the changes that need to be done for this. Also, does the "support documentation" section just to the bottom like the image you shared or needs to be added in a footer like below (as mentioned above)?
 
![image](https://user-images.githubusercontent.com/25846741/185755906-3504d475-e925-4c8b-98b6-84c96af016fb.png)

**Comment by oba2311** [comment]
@scopsy I thought we had in ming the top right corner no?
https://linear.app/novu/issue/NV-769/add-link-to-docs-from-the-web-dashboard

**Comment by djabarovgeorge** [comment]
Hey @Rutam21 
Have you managed to handle this issue? or would you like @abhinavsaurav to handle it?

**Comment by djabarovgeorge** [comment]
Hey @oba2311 
At the moment the location of this component is not consistent in comparison to the page.

For example : 

![image](https://user-images.githubusercontent.com/39195835/185935534-1a60035d-634c-4c51-9ea3-cea9ddbd6bad.png)

![image](https://user-images.githubusercontent.com/39195835/185935782-5d371bbf-b08a-4cf5-8949-ced22ec5d7a7.png)


Do you think we should keep it like this?

**Comment by oba2311** [comment]
@djabarovgeorge can we close it ?

**Comment by djabarovgeorge** [comment]
Hey @oba2311 was the issue resolved?

**Comment by scopsy** [comment]
We decided right now to just fix the location to be fixed at the bottom instead of floating in the middle of the screen. @Rutam21 do you think you will be able to do it?

**Comment by MohammedBajuaifer** [comment]
Hey @scopsy, If @Rutam21 isn't available to work on it, I can work on it

**Comment by scopsy** [comment]
Closed this as part of the multiple organizations support issue. Thank you everyone for the support and help!
