### ISSUE TITLE
Multiple accounts 

### ISSUE THREAD

**Issue by jwilridge** [novuhq/novu#1085]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by oba2311** [comment]
@jwilridge  would be great if you could please follow our guidelines for how to submit a ticket, as without necessary details it's hard for us to move forward.
