### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by varghesejose2020** [novuhq/novu#1092]
`https://novu.co/contributors/` Internal Server Error 500

![image](https://user-images.githubusercontent.com/71702982/185755467-b6748755-2a4c-409b-9b06-37876a736f5c.png)

**Comment by scopsy** [comment]
Thanks for submitting, taking a look right now. Will update here

**Comment by scopsy** [comment]
Was resolved, looking for a better way to handle this for the future with a more stable DB deployment. Closing for now.
