### ISSUE TITLE
API inconsistency for the subscriber endpoint

### ISSUE THREAD

**Issue by JustinBack** [novuhq/novu#1098]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Querying the GET subscribers endpoint should get the following keys

![B754F67E-BD8E-49C1-BBA5-DD1AD0790AE6](https://user-images.githubusercontent.com/40178814/185797810-15550ef0-dfe8-41a2-8229-adbb8ce30a01.jpeg)

however if firstName, lastName, email, phone, etc. are **not** set, they are removed from the response, the proper behavior should be to null those properties, rather than deleting them.

![02E832F9-B172-49A5-8E73-B4410A895B0D](https://user-images.githubusercontent.com/40178814/185797885-aa3a6008-11b3-4a87-9e84-fb0bfa50841c.jpeg)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by scopsy** [comment]
Thanks for reporting @JustinBack ! Merged at #1100

**Comment by JustinBack** [comment]
Great! Thank you 👍🏻
