### ISSUE TITLE
[NV-825] disappearing Points in the list

### ISSUE THREAD

**Issue by varghesejose2020** [novuhq/novu#1114]
`https://docs.novu.co/api/`  The points will disappear  if we hover the mousepointer on the points
![image](https://user-images.githubusercontent.com/71702982/186222948-7a25949d-1423-41ff-9a32-59bbdfc24449.png)

**Comment by scopsy** [comment]
Thanks for reporting! @varghesejose2020

**Comment by Prajnaprabhu3** [comment]
This is the issue with the light theme. This is because when you hover on the list items the color is set to white or a light color.

**Comment by scopsy** [comment]
Sure @KumarDhananjaya just assigned 🙌

**Comment by MohammedBajuaifer** [comment]
Hi @scopsy, Is this issue still open?

**Comment by davidsoderberg** [comment]
@MohammedBajuaifer some one is already working on this as well...

**Comment by andrewgolovanov** [comment]
Hi guys!
I think I already [made a correction](https://github.com/novuhq/api-docs/commit/a98b237cd27aaa28c17e33272f63ecdca5a3b782) for this :sweat_smile:
Unfortunately I didn't know that there was an open issue on this problem and as soon as I noticed the problem I decided to fix it quickly :grimacing: 

Example: https://docs.novu.co/api/
