### ISSUE TITLE
🚀 Feature: Disable additional sign ups for self-hosted

### ISSUE THREAD

**Issue by ACPixel** [novuhq/novu#1128]
### 🔖 Feature description

The ability to disallow new sign ups/registrations for a self-hosted instance.

### 🎤 Why is this feature needed ?

To add additional security when using for a single org

### ✌️ How do you aim to achieve this?

Likely via an environment variable

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by jainpawan21** [comment]
Hi @ACPixel, Can you please explain about this feature?

**Comment by ACPixel** [comment]
Not really sure what else there is to explain but basically just adding a way to disable new account registrations from being allowed. If I'm self hosting, I don't want someone to find the dashboard URL and make an account on my servers. 

Ideally I set Novu up, make the primary account, then change an environment variable like "allowSignups" and reboot the servers, then the dashboard stops showing a "create account" button and the API disables the sign up routes.

**Comment by jainpawan21** [comment]
Thanks @ACPixel for detailed explanation
