### ISSUE TITLE
[NV-1248] 🚀 Feature: Use the Provider's template.

### ISSUE THREAD

**Issue by xioxin** [novuhq/novu#1138]
### 🔖 Feature description

Provides a new type of integration that serves to combine the template id and Variable and forward it to the SMS provider.

### 🎤 Why is this feature needed ?

In China SMS templates must be reviewed by the provider.
The provider's interface is to pass the SMS template id and variables, not the full text content.

### ✌️ How do you aim to achieve this?

Add a forward type integration.
Add an action in Workflow Editor, select Integration in the action and fill in the template id from the vendor.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

My native language is not English, so there may be errors in the description.

<sub>[NV-1248](https://linear.app/novu/issue/NV-1248/🚀-feature-use-the-providers-template)</sub>

**Comment by scopsy** [comment]
Thank you for reporting this @xioxin! What providers support this behavior of passing a template id? Do we have those integrations in Novu or it is for new providers targeting china?

**Comment by xioxin** [comment]
new providers targeting china.


SMS provider related api documentation (Chinese, may need translation software help)
https://help.aliyun.com/document_detail/419273.htm
https://www.mysubmail.com/documents/OOVyh

**Comment by scopsy** [comment]
Thank you for this information @xioxin this is very helpful!

**Comment by scopsy** [comment]
Can be handled with provider overrides with Echo https://docs.novu.co/echo/quickstart
