### ISSUE TITLE
🐛 Bug Report: Can't update workflow editor in cloud

### ISSUE THREAD

**Issue by revskill10** [novuhq/novu#1144]
### 📜 Description

After creating template, i couldn't update the workflow editor after editing.

### 👟 Reproduction steps

1. Got web.novu.co and login
2. Create new template
3. Go to workflow editor and make some changes, then click on Update
4. Nothing happens.

### 👍 Expected behavior

The change should be saved.

### 👎 Actual Behavior with Screenshots

Nothing changes.

### 💻 Operating system

MacOS

### 🤖 Node Version

16.15.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by matigumma** [comment]
confirm same behavior
