### ISSUE TITLE
🚀 Feature: use notification actions with iframe embed

### ISSUE THREAD

**Issue by sioex** [novuhq/novu#1148]
### 🔖 Feature description

Be able to set methods on the notification buttons by using the Vue iframe

### 🎤 Why is this feature needed ?

It is needed for better UX

### ✌️ How do you aim to achieve this?

Add Vue components or adjustment to add methods to the buttons

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
We need to allow to add a handler for action click just as we do with the react component here: https://docs.novu.co/notification-center/react-components#notification-actions
