### ISSUE TITLE
Documentation not updated to show usage of email arrays in trigger event

### ISSUE THREAD

**Issue by SajMohammed** [novuhq/novu#1152]
I am submitting an issue to update the Novu documentation with usage of email parameter in trigger event as an array of emails as well

Currently, it is ambiguous in its usage as it shows only one email per trigger event

**Comment by mrajen27** [comment]
Team, I will work on this documentation.

**Comment by scopsy** [comment]
Thank you @mrajen27 🙏 assigning you
