### ISSUE TITLE
Linking License and Contribution Guidelines Internally in ReadMe 

### ISSUE THREAD

**Issue by krupalitrivedi** [novuhq/novu#1160]
Please consider linking the docs of License and Contributing Guidelines in ReadMe for people to have easy access to these files. 
Something like attached screenshot.

![Screenshot_20220830-234725.jpg](https://user-images.githubusercontent.com/99717469/187513571-982ff7f3-be86-4474-9c63-8702a9b2a42e.jpg)

**Comment by Tfanios** [comment]
Hey, could i work on this issue?

**Comment by scopsy** [comment]
Hi @krupalitrivedi thanks for opening the issue! GitHub already has a dedicated place for the license and contributors on the information panel. Could you elaborate on why we need to duplicate this information to the readme aswell? 

![CleanShot 2022-08-31 at 13 39 18](https://user-images.githubusercontent.com/8872447/187660270-be982b6d-e662-4db8-ac31-1cc797d8ec90.png)

**Comment by krupalitrivedi** [comment]
> Hi @krupalitrivedi thanks for opening the issue! GitHub already has a dedicated place for the license and contributors on the information panel. Could you elaborate on why we need to duplicate this information to the readme aswell?
> 
> ![CleanShot 2022-08-31 at 13 39 18](https://user-images.githubusercontent.com/8872447/187660270-be982b6d-e662-4db8-ac31-1cc797d8ec90.png)

Usually, it is for accessibility. I do realize that the license and Code of Conduct are present on the information panel but when someone is reading about the project, 'ReadMe' file, the information panel is already scrolled up. And even though - not necessary, it provides easy access to License and Contributing Guidelines if added in ReadMe towards the end as the reader now knows about the project and if they wish to contribute, they simply have to click to navigate. Now, this is my belief, not necessary that everyone has to do that same - thus raised an issue suggesting the same :)

**Comment by AmanNegi** [comment]
Hey there, can I work on this issue

**Comment by jainpawan21** [comment]
@AmanNegi this is still not ready to work

**Comment by AmanNegi** [comment]
@jainpawan21 Is something else also needed? Didn't quite get you.

**Comment by abhaytaras7** [comment]
> @AmanNegi this is still not ready to work

guess it is

**Comment by AmanNegi** [comment]
So can you please merge this pull request?

**Comment by scopsy** [comment]
@krupalitrivedi this defiently makes sense, thank you for raising it up and @AmanNegi for the contribution <3

**Comment by AmanNegi** [comment]
Thanks a lot @scopsy ✌
