### ISSUE TITLE
🐛 Bug Report: api url incorrect in API reference

### ISSUE THREAD

**Issue by guy-wal** [novuhq/novu#1169]
### 📜 Description

The [api docs](https://docs.novu.co/api/) point to an incorrect url: https://api.novu.app/v1

### 👟 Reproduction steps

make a request to https://api.novu.app/v1 and get `ENOTFOUND`

### 👍 Expected behavior

should refer to https://api.novu.co/v1

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/95572228/187699163-9f9b4e54-3945-41fd-bc1d-1ef2f142e013.png)

![image](https://user-images.githubusercontent.com/95572228/187699248-ea447c4a-e7b4-4144-8436-6edbdc5d817a.png)

### 💻 Operating system

MacOS

### 🤖 Node Version

16.13.1

### 📃 Provide any additional context for the Bug.

[discord discussion](https://discord.com/channels/895029566685462578/895029567125872653/1014535577737113752)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
Closed by @kymppi 🚀
