### ISSUE TITLE
🐛 Bug Report: Different positions to the notification center

### ISSUE THREAD

**Issue by SajMohammed** [novuhq/novu#1174]
### 📜 Description

Alignment issue with Notification Center while trying to place it in a side navbar. The notification center component overlaps the sidebar. It should be positioned on the left of the bell and not only beneath it.

### 👟 Reproduction steps

1. Place the notification center on a side navbar 
2. You should see the notification center overflows the sidebar 

### 👍 Expected behavior

It shouldn’t be overlapping the side navbar, also should be able to customise the popover positions as per user requirement

### 👎 Actual Behavior with Screenshots

Currently, the screenshot is overlapping the sidebar not able to target the component to offset to required position 

### 💻 Operating system

MacOS

### 🤖 Node Version

v16.13.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
This was added by @BiswaViraj 🚀
