### ISSUE TITLE
Really sad if these package is only applicable for Javascript Project. 

### ISSUE THREAD

**Issue by lawweiliang** [novuhq/novu#1176]
I found out that this package currently is just applicable only for javascript. It would be sad in that case.  

I suggested turning the bottom layer into API layer. Then, create SDKs on top of these APIs for different languages. 😃

**Comment by davidsoderberg** [comment]
Hi @lawweiliang, we have just started creating SDKs for some languages 😄 
Do you miss a specific language? Do you like to contribute on any language SDK?

I would love to help you getting started with Novu and creation of an SDK 🤩

**Comment by Wyfy0107** [comment]
This's a good idea. I can help with go sdk if possible :)

**Comment by scopsy** [comment]
Hi @Wyfy0107, the Go SDK Source is available [here](https://github.com/novuhq/go-novu), it supports the most basic API requests right now. Would appreciate the help of extending it to more methods 🚀

**Comment by lawweiliang** [comment]
@davidsoderberg 
Just a little suggestion over here yeah. 

The bottom layer(API layer) should go as fast as possible(Using Rust instead of other languages).

Then, SDK layer. 
SDK layer(Go for Python, Java, Go, Javascript, PHP). 
Why? Because these languages cover most of the applications in the market.

For my part. Currently, I am working on my side project more toward Rust. Maybe I could help out with that.

**Comment by lawweiliang** [comment]
> Hi @Wyfy0107, the Go SDK Source is available [here](https://github.com/novuhq/go-novu), it supports the most basic API requests right now. Would appreciate the help of extending it to more methods 🚀

Thanks, brother. Good sharing.

**Comment by lawweiliang** [comment]
Close this issue.

**Comment by jjmpsp** [comment]
I found a PHP implementation too but haven't got around to testing it yet: https://github.com/JRB-IT/NovuPHP
