### ISSUE TITLE
🐛 Bug Report:  People invited directly assign as an admin? 

### ISSUE THREAD

**Issue by lawweiliang** [novuhq/novu#1187]
### 📜 Description

![image](https://user-images.githubusercontent.com/34936929/188151916-4f274db8-6987-4ae9-b1c8-d0ec87763678.png)

First problem
I am literally getting shocked by this. I think it would be better to assign them as a `normal member` first and allow the admin to modify it over the backend. Any clue on this?

Second problem
When I first invite a user, I don't even know I can modify the role by clicking the "admin". Hmm, maybe we could do something over the UiUx section later. 

### 👟 Reproduction steps

1. Send an invitation to email A.
2. View the role over "Team member section".

### 👍 Expected behavior

Solution 1
1. Invitee should be assigned with the lowest role first.
2. Then, the admin could modify it over the backend. 

### 👎 Actual Behavior with Screenshots

---

### 💻 Operating system

Windows

### 🤖 Node Version

v.16.14.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
Hi @lawweiliang, as of know our permission system is not very evolved when it comes to defining boundaries correctly. This is why the admin account is used by default when a person gets invited. this is also why this featured doesn't have "High" discoverability level.

We are looking to redefine this in the next couple of months. In the meanwhile could you share your usecases with inviting multiple users and what would expect each role to represent?

**Comment by lawweiliang** [comment]
@scopsy , based on current feature. I don't see a need for different roles.

**Comment by ainouzgali** [comment]
Hi @lawweiliang, you are right, based on our current management of roles there is no real need for the different types of roles. But it is planned for the near future. 

If you would like to share, it will be helpful for us to hear what you think each role should be allowed to do. For example, would you expect only admins to be allowed to promote changes to production? Should all members be allowed to invite new users to the organization? etc.

**Comment by lawweiliang** [comment]
Hi @ainouzgali, instead of thinking which role can do which action. I would rather pass this task to the client itself. 

For eg, they can create role based on their own preference. 
Role A can do action a, b ,c. 
Role B can do action t, y.
Then, assign the task to it's member accordingly.

**Comment by oba2311** [comment]
@ainouzgali @scopsy how about we fix it in the meantime for the normal member, and revisit this when redefine roles?

**Comment by scopsy** [comment]
@oba2311 for now let's leave it like this. Because I'm afraid, it will create more confusion for the invited person. To make it default, we will need to add a role input near the email so it will be more clear for the person who invites him. So will close this for now.

**Comment by oba2311** [comment]
So giving admin permissions for the person invited?
Sounds quite outside of what user would expect

**Comment by oba2311** [comment]
@scopsy

**Comment by scopsy** [comment]
"Member" role may lead to strange behaviour until we define all scopes of what a "member" means. Right now the definition of Member rights was put as a placeholder. Until now the default invite was "Admin", this functionality will just leave it as-is until we will finalize the scope and test the behaviour of a "member" role I suggest leaving it like this, otherwise, we will get a lot of support issues regarding people not being able to do what they thought it should be possible to do :)

To solve this from the root we need to do a redesign of role and permission and also integrate this to the UI because right now it's only available on the Back-End. To be honest I don't think it's a priority at this point, since people don't really asked about it yet.

**Comment by oba2311** [comment]
Yes sounds good, I hadn't realize that a new invitee gets member, I thought this issue was because new invitee got admin permissions...
