### ISSUE TITLE
🚀 Feature: A demo site for posting and receiving notifications

### ISSUE THREAD

**Issue by kymppi** [novuhq/novu#1196]
### 🔖 Feature description

A Demo site that uses all the features of novu

### 🎤 Why is this feature needed ?

This is very crucial to let people test novu without adding it to their project straight away.

### ✌️ How do you aim to achieve this?

By writing code :D

### 🔄️ Additional Information

I'm willing to work on this

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
@kymppi I think that is a great idea! We will be working on something soon with @andrewgolovanov. I will update on the outputs of it, and we might be able todo some migrations of it to different front end frameworks aswell!

**Comment by jainpawan21** [comment]
@scopsy 
Any update on this?

**Comment by scopsy** [comment]
Tracking the work here: https://github.com/novuhq/notification-center-demo So will close this for now 🙏
