### ISSUE TITLE
🐛 Bug Report: new team member got different organization

### ISSUE THREAD

**Issue by guy-wal** [novuhq/novu#1198]
### 📜 Description

added a teammate to our novu organization through the UI. He received the email and clicked to join but was sent to a brand new team (not members, templates, etc...). then tried removing him and re-inviting and he got this error
![image](https://user-images.githubusercontent.com/95572228/188308778-a830c34c-f717-4496-903a-cd617f334be9.png)

### 👟 Reproduction steps

see description

### 👍 Expected behavior

should invite new member to expected organization

### 👎 Actual Behavior with Screenshots

see description

### 💻 Operating system

MacOS

### 🤖 Node Version

16

### 📃 Provide any additional context for the Bug.

[discord thread](https://discord.com/channels/895029566685462578/895029567125872653/1014968204076007495)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
What happens is that existing Novu users are prompted to create a new account and this fails. Instead of adding them directly to an organization in case they are already Novu users in the system based on their EMail.

**Comment by ainouzgali** [comment]
I am closing this as fixed. @guy-wal Let me know if there are any additional problems. Thank you so much for reporting this!
