### ISSUE TITLE
🐛 Bug Report: shortcut Ctrl + K for opening search not working as expected, when CapsLock is on in docs

### ISSUE THREAD

**Issue by Nabhag8848** [novuhq/novu#1215]
### 📜 Description

When trying to use shortcut **`Ctrl + K`** for opening search field with **`CapsLock ON`** it's not working as expected. Instead of opening the search bar, its opening chrome search URL field.

![opening chrome search field](https://user-images.githubusercontent.com/65061890/188551308-164143bd-192d-47be-8dbc-3079b3af437a.png)

### 👟 Reproduction steps

1. Go to [novu docs]( https://docs.novu.co/)
2. Try opening a search field using `Ctrl + K` while CapsLock is `ON`

### 👍 Expected behavior

Shortcut should instead open `Search` field of novu docs instead of chrome search `URL` field.
 
![Screenshot from 2022-09-06 10-41-09](https://user-images.githubusercontent.com/65061890/188552162-f11321b3-e4bc-40db-9f55-270dc1275708.png)

### 👎 Actual Behavior with Screenshots

see description

### 💻 Operating system

Linux

### 🤖 Node Version

v14.19.3

##  Chrome Version
 `v105.0.5195.52`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by MohammedBajuaifer** [comment]
I can work on it

**Comment by BiswaViraj** [comment]
@MohammedBajuaifer Assigned you 🙂

**Comment by MohammedBajuaifer** [comment]
If anyone can guide me, where can i find the the search component?

**Comment by scopsy** [comment]
Hi @MohammedBajuaifer this components is generated by algolia, and you can find the associated code in the 'docs' folder on the root of the monorepo.

**Comment by scopsy** [comment]
Did you had a chance to take a look at this @MohammedBajuaifer ?

**Comment by scopsy** [comment]
Just tried this and wasn't able to reproduce this with or without capslock. Maybe you had another language selected?
