### ISSUE TITLE
[NV-1247] 🚀 Feature: Add websocket event for new notifications

### ISSUE THREAD

**Issue by SpencerMiller23** [novuhq/novu#1220]
### 🔖 Feature description

This feature would resolve some issues that you might encounter when implementing some custom functionality on the frontend. In addition to the existing `unseen_count_changed` event, I propose to add another event such as `notification_received` which would contain all the relevant data for a new notification as follows:

```
{
    _id: "_id",
    _templateId: "_templateId",
    _environmentId: "_environmentId",
    _messageTemplateId: "_messageTemplateId",
    _organizationId: "_organizationId",
    _notificationId: "_notificationId",
    _subscriberId: "_subscriberId",
    subscriber: subscriber,
    template: template,
    templateIdentifier: "templateIdentifier",
    createdAt: "createdAt",
    content: "content",
    transactionId: "transactionId",
    channel: "channel",
    seen: true,
    email: "email",
    phone: "phone",
    directWebhookUrl: "directWebhookUrl",
    providerId: "providerId",
    deviceTokens: ["deviceTokens"],
    title: "title",
    lastSeenDate: "lastSeenDate",
    cta: cta,
    _feedId: "_feedId",
    status: "status",
    errorId: "errorId",
    errorText: "errorText",
    payload: payload,
    overrides: overrides,
    subject: "subject"
}
```

### 🎤 Why is this feature needed ?

While there are already nice solutions for displaying events in a UI such as the useNotifications hook and the Novu API, adding this event would give developers more flexibility when building their UIs. For example, you could reduce the load on the client by fetching events using the API, and then simply listen for new events by websocket and update the UI when appropriate.

### ✌️ How do you aim to achieve this?

By creating a new event that users can subscribe to and execute relevant logic when such an event is emitted.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1247](https://linear.app/novu/issue/NV-1247/🚀-feature-add-websocket-event-for-new-notifications)</sub>

**Comment by scopsy** [comment]
@SpencerMiller23 let me know if you want me to assign you to this one :)

**Comment by SpencerMiller23** [comment]
@scopsy I will look into it when I have some spare time but feel free to assign to someone else in the meantime

**Comment by Nabhag8848** [comment]
Hey, @scopsy can you assign it to me, would love to work on it. 😊

**Comment by scopsy** [comment]
Sure @Nabhag8848 thank you!

**Comment by oba2311** [comment]
Hi @Nabhag8848 , need any inputs from the team?

**Comment by SpencerMiller23** [comment]
Any updates with regards to this feature?

**Comment by scopsy** [comment]
Unfortunately not, @SpencerMiller23. Returned the help wanted label on the issues since @Nabhag8848 un-assigned him self.
