### ISSUE TITLE
🐛 Bug Report: API call with curl to notification-groups endpoint responds error 500

### ISSUE THREAD

**Issue by theeleb** [novuhq/novu#1234]
### 📜 Description

When I make the call to retrieve the groups from the API with Curl (following the documentation), the response is a 500 error

Call: 

`curl -X GET \
 -H "Authorization: ApiKey YOUR_API_KEY" \
https://api.novu.co/v1/notification-groups`

Response: 

`{"statusCode":500,"message":"Internal server error"}%`

In the same way, I make a call to:

`curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: ApiKey YOUR_API_KEY" \
  -d '{
    "name": "Novu",
    "payload": {
      "test": "test"
    },
    "to": "to",
    "transactionId": "transactionId"
  }' \
https://api.novu.co/v1/events/trigger`

With this result: 

`{"data":{"acknowledged":true,"status":"template_not_found"}}%  `

### 👟 Reproduction steps

Make this call 

`curl -X GET \
 -H "Authorization: ApiKey YOUR_API_KEY" \
https://api.novu.co/v1/notification-groups`

### 👍 Expected behavior

This response should not be a "500 - Internal Server Error"

### 👎 Actual Behavior with Screenshots

![Captura de pantalla 2022-09-07 a las 12 09 10](https://user-images.githubusercontent.com/2861833/188852820-10691b2b-baa3-4303-a448-20b4b02e56d7.png)

### 💻 Operating system

MacOS

### 🤖 Node Version

v18.0.0

### 📃 Provide any additional context for the Bug.

Im testing in development environment 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by theeleb** [comment]
![Captura de pantalla 2022-09-08 a las 12 15 15](https://user-images.githubusercontent.com/2861833/189097348-793358b9-e682-4a67-91d5-494060e9b72a.png)

I tested the call in the same way as on the Novu Website. A bearer token is sent in the call. By making the call with the token and not with the API-KEY as the documentation says. Works as expected. But, i think i missing something

<img width="1006" alt="Captura de pantalla 2022-09-08 a las 12 21 13" src="https://user-images.githubusercontent.com/2861833/189098506-548a8103-32de-4f5e-8ea2-e7c630f63aae.png">

**Comment by theeleb** [comment]
In the same way: 

1 - I tried post https://api.novu.co/v1/notification-templates with this body: 

`{
      "name": "new-request",
      "notificationGroupId": "62fe05b7cd5afb6ad3c08b08",
      "tags": ["chat", "decathlon"],
      "description": "New  request  ",
      "steps": [],
      "active": true,
      "draft": true,
      "critical": true,
      "preferenceSettings": {"email":false,"sms":false,"in_app":true,"chat":false,"push":false}
}`

If i make the call without bearer i get: 

`{
    "statusCode": 403,
    "message": "Forbidden resource",
    "error": "Forbidden"
}`

When i send the bearer works, maybe some information included in the bearer is used internally to get the data. 

There are a few endpoints with this behaviour.

**Comment by ainouzgali** [comment]
Hi @theeleb thank you for reporting and for being so detailed. Was super helpful. You are right, I am working on a solution now. Will probably be merged to main tomorrow and included in our next release.

**Comment by ainouzgali** [comment]
Merged @theeleb :)
