### ISSUE TITLE
🚀 Feature: 

### ISSUE THREAD

**Issue by MarkusTarn** [novuhq/novu#1239]
### 🔖 Feature description

Section in dashboard to see API errors, or at least queue.

### 🎤 Why is this feature needed ?

Currently when emails are not sent out, then this is not displayed anywhere on the dashboard.
Would be nice if you could see it straight from dashboard with error messages also.

### ✌️ How do you aim to achieve this?

Dashboard showing also emails not sent out

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
Hi @MarkusTarn seen that you closed this issue, but just wanted to say we are working right now on a debuggining and analytics dashboard to show all the step results in more detailed way 🙏
