### ISSUE TITLE
[NV-1246] 🐛 Bug Report: Can't find a way to edit custom attributes on the email template button

### ISSUE THREAD

**Issue by MarkusTarn** [novuhq/novu#1240]
### 📜 Description

Can't find a way to edit custom attributes on the email template button.

### 👟 Reproduction steps

1. Open Dashboard
2. Edit any template
3. Try to find a way to edit button attributes

### 👍 Expected behavior

I should be able to see a way to edit button attributes

### 👎 Actual Behavior with Screenshots

I could not find a way to edit button attributes

### 💻 Operating system

MacOS

### 🤖 Node Version

14

### 📃 Provide any additional context for the Bug.

I use Novu Sendgrid integration to send out emails.

Email-Verification template uses button to direct users to platform.

Sendgrid Click Tracking is essentially crawling the site to add tracking and verifying email as soon as user is reading it.

I don't want to disable Click Tracking, I would just like to add `clicktracking=off` to the <a> element.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1246](https://linear.app/novu/issue/NV-1246/🐛-bug-report-cant-find-a-way-to-edit-custom-attributes-on-the-email)</sub>

**Comment by oba2311** [comment]
This seems to me like webhooks are needed for this - @ainouzgali  @scopsy correct?

**Comment by scopsy** [comment]
@oba2311 not really, there is no connection the webhook. 

I think that what @MarkusTarn means here, is that under our "visual" email editor on the button it generates, there is no way to add custom HTML attributes like `clicktracking=off` as it's only available on the HTML editor at the moment

**Comment by oba2311** [comment]
Sounds like the functionality exist through the HTML editor tho, wouldn't that suffice for the time being?

**Comment by scopsy** [comment]
It is a workaround, but then the user will miss the prebuilt design. Maybe we can add some button to import the visual editor HTML to the custom HTML block? @MarkusTarn wdyt?

**Comment by MarkusTarn** [comment]
Would be more than enough for me 🙏

**Comment by oba2311** [comment]
@scopsy I believe we have this workaround alreayd in prod so we can close - @MarkusTarn @scopsy anything I might have missed?
