### ISSUE TITLE
🚀 Feature: Misc/Other class for providers

### ISSUE THREAD

**Issue by shanehughes1990** [novuhq/novu#1246]
### 🔖 Feature description

A misc class for providers would be nice to have

### 🎤 Why is this feature needed ?

We have a custom provider in mind that would not fit in the sms/chat/email categories, we have intention to make a mysql provider (for a legacy IVR system), that would use the notification bus to write a row into a sql database for the IVR to pick up (a telephony notification in the end).

### ✌️ How do you aim to achieve this?

just another provider class we can hook into to create our custom provider.

### 🔄️ Additional Information

I reached out via discord and had asked if upstream would take a PR for an additional class. Was told to just put it here on the feature board.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Hi @shanehughes1990! So if I understand correctly, you would just want to create an HTTP call instead of using a provider class? So we can have an `HTTP Request`  provider on almost all channels, and it will just create a call to the HTTP endpoint of your choosing?

**Comment by shanehughes1990** [comment]
Well ideally we want to remove our http api that talks to the sql db in Lue of a provider MySQL with what table and content to write in it, then our legacy ivr reads the db and does what it does.

**Comment by scopsy** [comment]
This functionality can now be achieved with a `custom` step in Echo: https://docs.novu.co/echo/quickstart
