### ISSUE TITLE
[NV-1245] 🚀 Feature: Validate email provider emails sent

### ISSUE THREAD

**Issue by shanehughes1990** [novuhq/novu#1247]
### 🔖 Feature description

Validate email bounce back and update the event status in novu ui to errored

### 🎤 Why is this feature needed ?

We use the mailgun provider and was testing what happens when we sent to a known bad email address, and as far as novu displaying that email was successful, and technically it was mailgun successfully triggered the email, but it bounced back in another event saying email was invalid.

Would be nice to see novu validate bounce back and update the event in novu itself to errored, we could then notify the person who triggered that email that it failed. and the mailgun error telling them of the bounce back.

### ✌️ How do you aim to achieve this?

1.Novu client sends an email workflow trigger
2. Mailgun successfully sends the email (in mailgun you see the event as successful)
4. A couple seconds later you get another event in mailgun with an error of bounce back due to invalid email
5. Novu sees this new error from mailgun and updates the novu event to errored that was triggered by novu client.
6. Do whatever you want with that updated status (in our case we would update the client who triggered the event)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1245](https://linear.app/novu/issue/NV-1245/🚀-feature-validate-email-provider-emails-sent)</sub>

**Comment by oba2311** [comment]
@shanehughes1990 thanks for this idea! This is part of the webhooks effort we are planning for next month. 
If that is valuable to you, you are more than welcome to help us by creating the necessary webhooks when we work on this in 3-4 weeks.

@ainouzgali  FYI :)

**Comment by scopsy** [comment]
We have recently launched the delivery provider webhook support https://docs.novu.co/platform/webhooks that touches this exact issue. Closing this issue as resolved.
