### ISSUE TITLE
🐛 Bug Report: Readme Typing Error

### ISSUE THREAD

**Issue by thevinitgupta** [novuhq/novu#1252]
### 📜 Description

I think there is a typing error in the `readme.md` file. 
The highlighted textin *yellow* shows the error : 

![bug](https://user-images.githubusercontent.com/65801700/189698731-3b5cc8bd-058b-4016-aabd-91ce6d591946.PNG)
 
Since I am beginner I would like to fix this

### 👟 Reproduction steps

Go to the *WHY* part of `readme` to see this error.

### 👍 Expected behavior

I think it should be 
`around the globe`

### 👎 Actual Behavior with Screenshots

The text is `around the code`

### 💻 Operating system

Windows

### 🤖 Node Version

v16.14.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by oba2311** [comment]
@BiswaViraj  WDYT?

**Comment by scopsy** [comment]
@oba2311 the meaning should be around the **code**, and not around the `globe` here. I agree it might be a bit strange so maybe we can rephprase it entirely. But the I don't think it should be `globe` in any case :)

**Comment by scopsy** [comment]
Will be closing for now, but thanks a lot for the suggestion. Really appreciate this 🙏
