### ISSUE TITLE
🐛 Bug Report: GET to notification-groups endpoint using ApiKey causes 500 error

### ISSUE THREAD

**Issue by KyleKreutzer** [novuhq/novu#1259]
### 📜 Description

Sending a GET to the notification-groups endpoint using the API key results in a 500 error. However, accessing this endpoint using the bearer token seems to work fine. Hitting the cloud service.

### 👟 Reproduction steps

Run this command with your own apiKey.

```
curl --location --request GET 'https://api.novu.co/v1/notification-groups' \
--header 'Authorization: ApiKey {Key}' \
--header 'Accept: application/json'
```

### 👍 Expected behavior

Return notification groups.

### 👎 Actual Behavior with Screenshots

Returned:
```
{
    "statusCode": 500,
    "message": "Internal server error"
}
```

### 💻 Operating system

MacOS

### 🤖 Node Version

Cloud Service

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by BiswaViraj** [comment]
I think this endpoint is behind the auth wall, so you'll need to provide the `Authorization` header with the JWT bearer token, not the API key.
@scopsy, @davidsoderberg We might need to update the API doc for this instance, maybe remove the `@ExternalApiAccessible()` from the route.

**Comment by scopsy** [comment]
@BiswaViraj This should work with the api key aswell like the other endpoints :(

**Comment by oba2311** [comment]
I think that @ainouzgali  is on this one.

**Comment by ainouzgali** [comment]
@KyleKreutzer, should be ok now. It is in main and will be in the next release :)
