### ISSUE TITLE
🐛 Bug Report: UI- Hover effect on cards in Workflow Editor

### ISSUE THREAD

**Issue by DanishOnGit** [novuhq/novu#1263]
### 📜 Description

If you hover on the Step card itself, then no change in background color of the card.
But, if you hover on the 3 dots inside the card, then the background color of card changes.
Also, the error tooltip comes over the Delete confirmation modal.

### 👟 Reproduction steps

Add any Step to the workflow, for example: Email.
Just hover on the Step card with 3 dots. Change of background color will happen only if you hover on the 3 dots inside it.
For the error tooltip issue: Just hover on 3 dots and click on Delete step

### 👍 Expected behavior

The background color of card should change upon hovering anywhere on the card.
Error tooltip should be behind the Delete Step modal

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/65118743/190917924-5e979198-f34d-461b-bc8d-a88852ae972c.png)
![image](https://user-images.githubusercontent.com/65118743/191250279-1f8054b0-333f-467a-b13c-fe26ad49e6a1.png)

### 💻 Operating system

Windows

### 🤖 Node Version

v14.17.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
Great @DanishOnGit ! I am assigning you.

**Comment by ainouzgali** [comment]
Merged! Thank you @DanishOnGit

**Comment by DanishOnGit** [comment]
Thanks a lot @ainouzgali !!
