### ISSUE TITLE
🐛 Bug Report: Wrong API call for updating user data 

### ISSUE THREAD

**Issue by JakovGlavac** [novuhq/novu#1269]
### 📜 Description

When using js library
```js
 await novu.subscribers.update("userid", {
            email: "email"
        });
```
I got an error 
```
   data: {
      statusCode: 404,
      message: 'Cannot PUT /v1/123/subscribers',
      error: 'Not Found'
    }
```

And if you check your [API docs](https://docs.novu.co/api/update-subscriber/) url for updating the subscriber data is actually  https://api.novu.co/v1/subscribers/:userId. I think someone just inverted it.

### 👟 Reproduction steps

Use Node libery

### 👍 Expected behavior

It should request https://api.novu.co/v1/subscribers/:userId not https://api.novu.co/v1/:userId/subscribers

### 👎 Actual Behavior with Screenshots

There is no need for Screenshots :)

### 💻 Operating system

Windows

### 🤖 Node Version

12

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
Thank you @JakovGlavac !
