### ISSUE TITLE
🐛 Bug Report: Typescript theme

### ISSUE THREAD

**Issue by JakovGlavac** [novuhq/novu#1275]
### 📜 Description

When customizing the `PopoverNotificationCenter` 
When
```js
theme={{
  dark: {
    notificationItem: {
      unseen: {
        background: "#2c3646"
      },
      seen: {
        background: "#1a202c"
      }
    }
  }
}}
```

![image](https://user-images.githubusercontent.com/34971091/191319673-959b00b2-3ef2-4261-a65a-aeab45b63758.png)
I get an error that styling button is not optional and I think it should be.

### 👟 Reproduction steps

It's self explanatory :) 

### 👍 Expected behavior

In this file https://github.com/novuhq/novu/blob/0aee8ca5cbf51a930305cf424166b9825851914a/packages/notification-center/src/store/novu-theme.context.ts#L64
I think `buttons `should be optional like `seen `and `unseen `properties 

### 👎 Actual Behavior with Screenshots

I don't think this is necessary 

### 💻 Operating system

Windows

### 🤖 Node Version

12

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
Thank you!
