### ISSUE TITLE
[NV-178] - Add new provider Matrix (matrix.org)

### ISSUE THREAD

**Issue by samip5** [novuhq/novu#128]
No support for Matrix notifications

Solution I'd like:
Support for it.

Additional Context:
matrix.org

**Comment by jotabraga** [comment]
Hi @scopsy  I would like to work on this task

**Comment by scopsy** [comment]
@jotabraga thank you! Assigned you to this. Reach out if you need any help 🙏

**Comment by pearceman** [comment]
Hey, @jotabraga How are things? Have you got an update on the issue? Can we help with something?

**Comment by scopsy** [comment]
Hey, @jotabraga removed you from the assignee for time being maybe someone else can jump and help with one. If that's ok on your ned 🙏

**Comment by Nike682631** [comment]
@scopsy  Is this issue available to work on?

**Comment by scopsy** [comment]
Sure think @Nike682631 assigning you right now 🚀

**Comment by Ln11211** [comment]
Hey there, As much as I can understand, are we trying to support Matrix notifications? Am I right? and how does one start doing this?, can you please elaborate a little about the task at hand? :)

**Comment by kymppi** [comment]
Any progress on this? I'm willing to do it

**Comment by iampearceman** [comment]
@kymppi How it's going with this?

**Comment by kymppi** [comment]
I havent been able to work on this lately. If i remember correctly there was some refactoring someone had to do before adding this

**Comment by kymppi** [comment]
I currently don't have time to work on this, so I'll unassign myself :)

**Comment by Cliftonz** [comment]
@07tAnYa Assigned

**Comment by 07tAnYa** [comment]
ok thank you sir, started working on it

**Comment by momerjaved** [comment]
Hi, 

I would like to contribute , is this issue open to work on ? Thanks.

**Comment by Cliftonz** [comment]
@momerjaved your welcome to work on it

**Comment by momerjaved** [comment]
Thanks. If I have to add the new provider matrix.org should I choose its type as Chat or do we need to add multiple providers for matrix.org ?

**Comment by samip5** [comment]
> Thanks. If I have to add the new provider matrix.org should I choose its type as Chat or do we need to add multiple providers for matrix.org ?

Please DO NOT hardcode matrix.org, as the homeserver can be any due to the federated nature of the network.

**Comment by momerjaved** [comment]
Hi @samip5 
Please note that I am not hard coding the provider name, I am following this guide to create a new provider.

https://docs.novu.co/community/add-a-new-provider?utm_campaign=github-contrib

cheers,
Omer

**Comment by samip5** [comment]
> Hi @samip5 Please note that I am not hard coding the provider name, I am following this guide to create a new provider.
> 
> https://docs.novu.co/community/add-a-new-provider?utm_campaign=github-contrib
> 
> cheers, Omer

I wasn't talking about the provider name per se. I was talking about the API endpoint.
