### ISSUE TITLE
⭐ Want to contribute? Start here!

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#1280]
# Welcome to the Novu! 

Hacktoberfest is here, and there are many ways you can contribute to Novu. Here we will write some suggestions, and feel free to submit your ideas.

## Find where to contribute
The easiest way to start is to **Find an existing issue**: visit the [issues page](https://github.com/novuhq/novu/issues) and search for any issue with a `help wanted` or a `good first issue` label.

In some cases, there is no issue available that you find accessible for you. In that case, here are some other things you can contribute with: 
- **Help with documentation** - Head over to our [documentation page](https://docs.novu.co/) and see if something is: Unclear, has typos, missing context, or has missing information. Just make a fix and create a PR for it.
- **Help with API References** - We auto-generate our API references based on Swagger Decorators. Some of our endpoints would help to get more content or information. The API Reference is available [here](https://docs.novu.co/api/overview/). 
- **Help with writing tests** - We write our tests with mocha and cypress (some provider packages use jest). You can help with creating more test cases for existing tests or find missing component tests and write new ones! 
- **Help with reviewing pull requests** - You can visit some open pull requests and help review the code there and leave your comments to help improve our code!

## Start contributing
After finding an issue, and in case the issue already exists, you can ask to be assigned just in case we won't have multiple people working on the same thing. If this is something you found without an issue, feel free to submit a PR directly. 

Fork the Novu repository and clone it to your local computer. After ensuring you have installed the environment dependencies (Redis, MongoDB, and pnpm@7.5.0). Read more detailed information on [Running Novu Locally](https://docs.novu.co/community/run-locally/).

## Get Help
You can always comment on issues to get help from community members, you are all welcome to join our [Discord Server](https://discord.gg/novu).

**Comment by kVarunkk** [comment]
Hi @scopsy, I had one doubt. Will I be eligible to get swags as I've contributed to the documentation and not the issues?

**Comment by scopsy** [comment]
Yes @kVarunkk this will count aswell!

**Comment by kVarunkk** [comment]
Thanks!

**Comment by scopsy** [comment]
@bishal7679 it happens automatically after merged PR's. It takes some time tho :)

**Comment by extinctsion** [comment]
@scopsy can u assign me this issue? :)
