### ISSUE TITLE
Chat Integration with Mattermost🚀 Feature: 

### ISSUE THREAD

**Issue by surajprabhuaissel** [novuhq/novu#1286]
### 🔖 Feature description

Mattermost is an Open Source Slack alternative that also allows managed as well as  Self hosting. 
It is used by a lot of teams and would be an excellent point for notifications similar to Slack, MS Teams or Discord.  
Mattermost supports REST API 

https://mattermost.com/platform-overview/

https://api.mattermost.com/

### 🎤 Why is this feature needed ?

While email notifications are good. Notification to other channels like slack or Mattermost is very important. Self hosted Mattermost is used by our organization and is done by many other organizations too. This will be very helpful to send notifications to Mattermost in addition to email and SMS.

### ✌️ How do you aim to achieve this?

In the integration store add option to integrate the Mattermost sever. By providing the mattermost server URL, API User, Team and the channel to post to the integration can be created. Then similar to Slack, a user can add and Chat in the Novu Workflow Editor and send notifications to the Mattermost Server's Channel.

### 🔄️ Additional Information

Our organization is using a self hosted mattermost server. I can create a new team, make it available for testing.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by ComBarnea** [comment]
@AisselTechnologiesPvtLtd following our chat I am assigning this one to you. You can find how to add a new provider [here](https://docs.novu.co/community/create-provider). Also you can checkout the [slack provider](https://github.com/novuhq/novu/tree/main/providers/slack) as a very close example.

**Comment by surajprabhuaissel** [comment]
> @AisselTechnologiesPvtLtd following our chat I am assigning this one to you. You can find how to add a new provider [here](https://docs.novu.co/community/create-provider). Also you can checkout the [slack provider](https://github.com/novuhq/novu/tree/main/providers/slack) as a very close example.

Thanks Tomer. I will go through the documentation. Since I am not an expert in coding, I hope I get help from the community to get this take care of.

**Comment by oba2311** [comment]
@surajprabhuaissel  let us know is help is needed!

**Comment by ryshoooo** [comment]
I can volunteer myself for this issue as well. We're using mattermost internally and I'd love to have the integration from Novu to mattermost, and going through the steps in the documentation, it looks pretty simple to achieve.

**Comment by jainpawan21** [comment]
Hi @ryshoooo 
Assigned this to you!
We highly appreciate your interest in contribution.
Let me know if you need any help 😃
