### ISSUE TITLE
🐛 Bug Report: No way to reset / destroy the `widget_user_auth_token` in the iFrame embed.

### ISSUE THREAD

**Issue by ahmed-classtra** [novuhq/novu#1289]
### 📜 Description

I have a Vue app that embeds the iFrame option for displaying the notification center. When I log out the existing user and log in as a new user, the notifications don't get updated. 

The `widget_user_auth_token` is not reset and remains the same. Only after a hard refresh on the page does the notification list update. 

### 👟 Reproduction steps

1. Embed the iFrame in your app.
2. Log in & check the notification center (also see `widget_user_auth_token`).
3. Log out of the current user.
4. log in as a new user.
5. Check the notification center (and `widget_user_auth_token`).

### 👍 Expected behavior

Step 5 should result in different notifications (and `widget_user_auth_token`) from step 2.

### 👎 Actual Behavior with Screenshots

Both the notifications and `widget_user_auth_token` for steps 2 and for remaining the same. 

### 💻 Operating system

MacOS

### 🤖 Node Version

16.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by oba2311** [comment]
@scopsy I think that we had several Vue issues.... correct?

**Comment by scopsy** [comment]
@oba2311 i'm not 100% sure it's relevant for Vue, but with the actual IFrame behaviour until we add an official wrapper for vue. 

@ahmed-classtra I think that the solution here is to allow a method to remove the notification center session for it. We can add it to the existing embed and react components.

**Comment by ahmed-classtra** [comment]
Thanks. It's definitely not a Vue issue. The iframe isn't clearing the storage. The best way around it for now is wrapping the React component in your own custom iframe. At least for now.

**Comment by gefgu** [comment]
I would like to work on this issue :)

**Comment by jainpawan21** [comment]
Hi @gefgu! How is it going with this issue?
Do you need any help?

**Comment by gefgu** [comment]
@jainpawan21 Actually I got a job opportunity some days after being assigned, and I'm not able to work on this issue anymore. Thanks for the opportunity :)

**Comment by jainpawan21** [comment]
> @jainpawan21 Actually I got a job opportunity some days after being assigned, and I'm not able to work on this issue anymore. Thanks for the opportunity :)

Congratulations Gustavo for new Job 🎉🎉

**Comment by jainpawan21** [comment]
@ahmed-classtra 
As we have official VUE Notification Centre now, can you please check it again?

**Comment by ahmed-classtra** [comment]
That's pretty awesome @jainpawan21 ! Will check it out for sure.
