### ISSUE TITLE
🚀 Feature: Change Admin features access

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1294]
### 🔖 Feature description

Would be great if the access to admin features (`@Roles(MemberRoleEnum.ADMIN)` decorator) used a special token instead, like Supabase and its SERVICE_ROLE key.

### 🎤 Why is this feature needed ?

When interacting with the API programmatically, some endpoints are only available for Admin users. However, it requires them to be logged in, which may not be possible for instance when using social providers or the user might not want to put its credentials in the app, even using env variables.

### ✌️ How do you aim to achieve this?

I'd like another Api key for each environment that only admins can access and that have admin privileges in the api. In a way, that looks like Supabase ANON key (that can be public) and SERVICE_ROLE key (which can bypass RLS).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by Cliftonz** [comment]
I agree with OP, there are admin tasks that should be able to be done by api.
For example, giving an AD group access to an entity with the api.

**Comment by oba2311** [comment]
@Cliftonz  / @florian-lefebvre  interested in taking this issue?

**Comment by florian-lefebvre** [comment]
I'm not interested, I'm already busy with other issues

**Comment by Cliftonz** [comment]
I am still working on the helm deploy.

**Comment by Sukriti-m** [comment]
Hi @oba2311 
I'd like to work on this issue. Please assign it to me.

**Comment by florian-lefebvre** [comment]
Currently, the api keys is stored in an array in the database per environment, which doesn't really make sense in my opinion. It might be better to have 2 properties instead like `apiKey` and `adminKey`. Wdyt?
cc @scopsy

**Comment by Cliftonz** [comment]
That would be a decent interim solution, however, I think the better option would be to create an RBAC policy controller that can apply to both users and api-tokens agnostically. The "admin" token would just have all the policies attached to it.

However, I know this is a much bigger project then defined here.

**Comment by Cliftonz** [comment]
I am going to say yes. I was going to recommend [cerbos](https://cerbos.dev/) for this. However, I think we need to do some planning before we move forward.

**Comment by scopsy** [comment]
Yes, @florian-lefebvre we won't be handling this for now until we resolve it internally in broader support since it's not a small issue to handle. @Cliftonz I've already thought of using Cerbos as we are good friends with the founders there, been on a demo with them. Will chat on this a bit later over Discord.
