### ISSUE TITLE
🐛 Bug Report: Integration store FCM is not at par with the docs

### ISSUE THREAD

**Issue by saby22** [novuhq/novu#1303]
### 📜 Description

Steps mentioned in the docs to integrate FCM with Novu.

> To enable the FCM integration, you need to get your service account key from the Firebase dashboard. You can acquire the account key JSON by selecting your project, clicking the gear icon in top of the sidebar, going to service account tab and download the JSON. After that, manually get the values from the JSON to the right fields. You can use a tool like [JSON Formatter](https://jsonformatter.curiousconcept.com/) to get the values more easily.

However, the form to add FCM as an integration only contains one field by the name of service account. What are we supposed to paste over there? The whole JSON file or something else?

### 👟 Reproduction steps

1. Navigate to the Integration Store in admin panel
2. Try to connect FCM , which is mentioned under Push

### 👍 Expected behavior

Should contain multiple form fields.

### 👎 Actual Behavior with Screenshots

![Screenshot 2022-09-27 170442](https://user-images.githubusercontent.com/67909471/192514851-d8be7c11-65dd-40ef-8e4b-ed9182dcf8d6.png)
Contains only one field by the name of service account.

### 💻 Operating system

Windows

### 🤖 Node Version

16.17.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by BiswaViraj** [comment]
Hello @saby22, thank you for raising this issue.
You'll need to paste the entire `service account` JSON in that field.
I'll look into the docs and update them later with the proper steps.
Let me know if you need any more help.

**Comment by saby22** [comment]
Got it. 
It works. Thanks for the clarification @BiswaViraj

**Comment by scopsy** [comment]
@saby22 @BiswaViraj maybe worth adding this in the field description? @saby22 do you want to create a PR for that?

**Comment by saby22** [comment]
@scopsy cool, I can take that up. Reopening just to track this one.

**Comment by oba2311** [comment]
@saby22  good luck!
