### ISSUE TITLE
"Contribution Guidelines" in README.md file links to the wrong repo.

### ISSUE THREAD

**Issue by mohanthilak** [novuhq/novu#1313]
The "Contribution Guidelines" link in the README.md file does not link to the novuhq/novu's repository's CONTRIBUTING.md file. It is pointing to a forked repository. I have updated the readme.md file. If the change is required I can make a pull request.

**Comment by oba2311** [comment]
Seems like the link leads to https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md

**Comment by mohanthilak** [comment]
Hey, @oba2311 under the links section in the README.md file the "Contribution Guidelines" link is leading to: https://github.com/AmanNegi/novu/blob/main/CONTRIBUTING.md. But yes, it should lead to https://github.com/AmanNegi/novu/blob/main/CONTRIBUTING.md.

**Comment by scopsy** [comment]
@mohanthilak assigned this to you ❤️

**Comment by mohanthilak** [comment]
Thank You @scopsy! I have made the pull request.
