### ISSUE TITLE
🚀 Feature: Complete `@novu/node` API

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1315]
### 🔖 Feature description

Many of the features of the API available at https://docs.novu.co/api/overview/ can be only accessed using a "custom" fetch (I mean not the `@novu/node` package).

### 🎤 Why is this feature needed ?

Port all the missing features to the @novu/node package.

### ✌️ How do you aim to achieve this?

This would make interacting with the API programmatically much easier.

### 🔄️ Additional Information

- [x] #1317
- [x] #1318
- [x] #1319
- [x] #1320
- [x] #1321
- [x] #1322 
- [x] #1323 
- [x] #1324

**Comment by scopsy** [comment]
This is a great point @florian-lefebvre! I think it would be best to create multiple issues for the different module just so we can split the work since there is quite a lot of it. Do you mind creating this issue for the submodules we have?

**Comment by florian-lefebvre** [comment]
Sure!

**Comment by florian-lefebvre** [comment]
Hey @scopsy it's done! I think it would to follow something like this for each module:
- Add missing endpoints in the API
- Implement them in `@novu/node`
- Document usage with & without using the client
- Use the client in the web app instead of the custom api folder

Wdyt?

**Comment by scopsy** [comment]
Perfect @florian-lefebvre! You are just amazing! This will help also a lot of folks during hactoberfest aswell 🚀

**Comment by manchicken** [comment]
Is this issue up-to-date?

**Comment by florian-lefebvre** [comment]
Yes, it's tracking other issues. So if those are not closed, checklist elements are still marked as undone. I don't know if that answers your question.

For instance, some PRs have be made to update the actual code (and merged) but the related docs haven't been updated yet so they are not closed yet.

**Comment by florian-lefebvre** [comment]
Finally!

**Comment by scopsy** [comment]
@florian-lefebvre boom! 🎉
