### ISSUE TITLE
🚀 Feature: Arm64 Support

### ISSUE THREAD

**Issue by fdelucchijr** [novuhq/novu#1316]
### 🔖 Feature description

Arm64/aarch64 support for docker images.

### 🎤 Why is this feature needed ?

Cloud is moving to Arm64 compute (probably cost related), many projects are already preparing for this new arch. 
An example of this is the Oracle Cloud Offer in Amphere A1 VM’s.

### ✌️ How do you aim to achieve this?

I’ve already downloaded the repo thinking about making a PR with all the changes, but as for now I see some problems (as for now only one, but if I see more with add it with an edit):

1.  API, web, widget and embed depends in nikolaik/python-nodejs with as for now is only amd64. There’s already [nikolaik/python-nodejs#38](https://github.com/nikolaik/docker-python-nodejs/issues/38) but with no timeline or notice.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by oba2311** [comment]
@fdelucchijr  good luck!

**Comment by scopsy** [comment]
Hi @fdelucchijr did you had a chance to take a look? Let me know if I can un-assign perhaps someone else would love to try this 🙏

**Comment by fdelucchijr** [comment]
@scopsy Sorry, I didn’t have enough time to change the build pipelines myself. As It would took me a lot of time to change it and debug for the whole monorepo (also, y don’t know much of the needs in the project for the Python and other non-node.js dependencies). My first option was to wait until https://github.com/nikolaik/docker-python-nodejs/issues/38 was finally resolved to recheck all the builds (as I remember that image was the only non ARM compatible), or in case I get a long vacation get edit the pipelines with a more specific Dockerfile for Node&Python.

If other person wanna take this issue more directly or with more time just assign him it.

**Comment by DaleWebb** [comment]
I've put in a PR for this here: https://github.com/novuhq/novu/pull/3309

**Comment by AliaksandrRyzhou** [comment]
Closed by [PR 5139](https://github.com/novuhq/novu/pull/5139)
