### ISSUE TITLE
`@novu/node`: complete the events module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1317]
Trigger, Broadcast, Cancel

- [x] #1357
- [x] https://github.com/novuhq/api-docs/pull/17

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by florian-lefebvre** [comment]
@scopsy Assign it to me, I'm working on it

**Comment by scopsy** [comment]
Just assigned you @florian-lefebvre 🚀
