### ISSUE TITLE
`@novu/node`: complete the subscribers module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1318]
- [x] #1538
- [x] https://github.com/novuhq/api-docs/pull/19

Moreover, it would be great if naming across API and client was consistent (e.g. "Update subscriber credentials" & "subscribers.setCredendials")

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by nilesh-maurya** [comment]
@scopsy assign this to me
