### ISSUE TITLE
`@novu/node`: complete the integrations module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1319]
- [ ] Get all
- [ ] Get one (no endpoint or not documented)
- [ ] Create
- [ ] Get active
- [ ] Update
- [ ] Delete
- [ ] Completed docs

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by developer-diganta** [comment]
Hello! @scopsy @florian-lefebvre I would like to work on it. But can you please guide me on how to proceed. Like do we have to update this [https://docs.novu.co/api/get-integrations/](https://docs.novu.co/api/get-integrations/) with the routes mentioned in the issue?

**Comment by florian-lefebvre** [comment]
Yes you'll need to add code snippets at https://github.com/novuhq/api-docs/tree/main/content/code-examples. You can have a look at the current content to see what you must do, but I'd recommend getting the client PR merged first before writing documentation

**Comment by jainpawan21** [comment]
Hi @developer-diganta, 
Do you need any help in this issue?

**Comment by dishantzaveri** [comment]
Hi as the previous assignee is inactive, can I take up this issue?

**Comment by jainpawan21** [comment]
@developer-diganta Are you still working on this?
@dishantzaveri lets wait for his reply.

**Comment by developer-diganta** [comment]
Sorry! I got a bit busy! If @dishantzaveri wants it he can go for it!

**Comment by jainpawan21** [comment]
@dishantzaveri Assigned to you!

**Comment by florian-lefebvre** [comment]
Hey @dishantzaveri do you need help?

**Comment by florian-lefebvre** [comment]
@dishantzaveri if you can't work on this please le me know

**Comment by dishantzaveri** [comment]
Yes I can't, I tried a lot

**Comment by florian-lefebvre** [comment]
No problem 👍 please @iampearceman unassign him

**Comment by codingmickey** [comment]
I can complete this, should I pick it up?

**Comment by dishantzaveri** [comment]
I don't think so.

**Comment by florian-lefebvre** [comment]
Not sure to have understood... @dishantzaveri you're unassigned right? Does anything prevent @codingmickey from working on it?

**Comment by jainpawan21** [comment]
> > I can complete this, should I pick it up?
> 
> pls mind our own business @codingmickey

Hi @dishantzaveri,
We highly appreciate you expressed interest previously in contribution.
However we do not promote this type of behaviour.

**Comment by jainpawan21** [comment]
> I can complete this, should I pick it up?

Yes sure @codingmickey 
I am assigning this to you.
Let me know if you need any help
