### ISSUE TITLE
`@novu/node`: complete the notification templates module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1320]
- [x] Get all
- [x] Get one
- [x] Create
- [x] Update
- [x] Delete
- [x] Update status
- [x] https://github.com/novuhq/api-docs/pull/18

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by codingmickey** [comment]
I want to try out this issue but can't figure out how to start any tips available. (currently trying to run novu locally)

**Comment by scopsy** [comment]
Hi @codingmickey, assigning you here. Our @novu/node package is a node wrapper on top of the novu API. you can find the SDK code here: https://github.com/novuhq/novu/tree/main/packages/node/src

The help needed here is to at the notification templates section on the API ref https://docs.novu.co/api/overview/ and add this functionality to the node SDK.

**Comment by scopsy** [comment]
You can also take a look at the example here: https://github.com/novuhq/novu/pull/1357

**Comment by codingmickey** [comment]
I can try this out, but not too confident as it's my first contribution. How about it?

**Comment by nilesh-maurya** [comment]
You can also check existing `subscriber` module which already has most of the APIs completed.
[SDK code](https://github.com/novuhq/novu/tree/main/packages/node/src/lib/subscribers)
[API Reference overview](https://docs.novu.co/api/get-subscribers/)

**Comment by aparna2071** [comment]
Hi @florian-lefebvre I want to work on this issue, if it is unassigned, can you please assign it to me?

**Comment by florian-lefebvre** [comment]
I'll let @scopsy do it and judge who must be assigned

**Comment by codingmickey** [comment]
I've already started working on this and figuring stuff out

**Comment by jainpawan21** [comment]
> I can try this out, but not too confident as it's my first contribution. How about it?

Ping us in discord, if you need any help in this.

**Comment by codingmickey** [comment]
I've done with the implementation but for testing I am unable to access the Create notifications-templates

###
```
Authorization: ApiKey APIKEY_FROM_SETTINGS
```

### Here is the body which I am sending
```
{
  "name": "test",
  "notificationGroupId": "NOTIFICATION_GROUP_ID",
  "steps": [],
  "description": "",
  "active": true
}
```
### This is the response I am receiving
![image](https://user-images.githubusercontent.com/42518907/195181295-132a4436-b685-4ffb-a6d7-c82b31e6223f.png)

**Comment by florian-lefebvre** [comment]
Not sure but based on tests on a project, you need to provide more fields:
- https://github.com/op-ent/api/blob/main/app/Services/Notification/setup-novu.ts#L86
- https://github.com/op-ent/api/blob/main/config/notifications.ts#L45-L75

I think the following properties are required :
- name
- notificationGroupId
- steps (maybe having it empty can cause issues)
- critical
- tags (empty is fine)
- active
- draft
- preference settings?

@scopsy I don't know who knows about it but it would be great which parameters are really required

**Comment by codingmickey** [comment]
I think this route requires admin options that have authorization of a `Bearer` token.. the API docs aren't updated with these changes

> I've done with the implementation but for testing I am unable to access the Create notifications-templates
> 
> ### Headers
> ```
> Authorization: ApiKey APIKEY_FROM_SETTINGS
> ```
> 
> ### Here is the body which I am sending
> ```
> {
>   "name": "test",
>   "notificationGroupId": "NOTIFICATION_GROUP_ID",
>   "steps": [],
>   "description": "",
>   "active": true
> }
> ```
> 
> ### This is the response I am receiving
> ![image](https://user-images.githubusercontent.com/42518907/195181295-132a4436-b685-4ffb-a6d7-c82b31e6223f.png)

**Comment by florian-lefebvre** [comment]
ah yes I see...still we should wait for dima's answer because I don't know how we shouldn't handle this. This is important because it occurs at different places in the API

**Comment by scopsy** [comment]
That's very strange since the API Key should be created using an Admin role for the logged in user. 

Could you try regenerating the API Key from the settings screen? 

Also, a small question, did you invite other users to the system or remove the previously created admin account?

**Comment by codingmickey** [comment]
> Could you try regenerating the API Key from the settings screen?

It's the same key, I don't see an option to regenerate the API Key



> Also, a small question, did you invite other users to the system or remove the previously created admin account? @codingmickey

nope I didn't do any of these

**Comment by scopsy** [comment]
Are you running novu locally on your machine or in the cloud version?

**Comment by codingmickey** [comment]
API or web? for both am using the hosted URLs/Site

**Comment by florian-lefebvre** [comment]
@scopsy this is directly linked to https://github.com/novuhq/novu/issues/1294

@jainpawan21 confirmed this issue occured on discord (have to use the Bearer personal token instead): https://discord.com/channels/895029566685462578/1022577958982004838/1023222880588288100

**Comment by florian-lefebvre** [comment]
Then @codingmickey you need to update the api docs at https://github.com/novuhq/api-docs/tree/main/content/code-examples

**Comment by codingmickey** [comment]
Sure will do that in a day or two having exams currently

**Comment by florian-lefebvre** [comment]
No problem, good luck!

**Comment by florian-lefebvre** [comment]
I've left a review 👍
