### ISSUE TITLE
`@novu/node`: complete the notification groups module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1321]
- [x] #1741 (Get all, create)
- [x] Get one (no endpoint)
- [x] Update (no endpoint)
- [x] Delete (no endpoint)
- [x] https://github.com/novuhq/api-docs/pull/32

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by deepak-sreekumar** [comment]
@scopsy I'd like to take a stab at it. Can you please assign this to me?

**Comment by jainpawan21** [comment]
Hi @deepak-sreekumar,
I hope you are working on this issue.
If you need any help, Let us know in our discord!

**Comment by deepak-sreekumar** [comment]
Thanks, @jainpawan21. I was caught up with some things and did not get a chance to work on this till now. Raised PR. PTAL when you get a chance. 

I will check the requirements for the missing endpoints and come back with questions if any.

**Comment by deepak-sreekumar** [comment]
@scopsy @florian-lefebvre Quick check on the missing endpoints. What should be the parameter on which  `Delete`, `Update`, `Get one` be supported? Is it `_id` since `name` is not a unique parameter?

Also what is the standard response for `DELETE` calls? Should it be the deleted object or an acknowledgment such as 
```
{
      acknowledged: true,
      status: 'deleted',
}
```
I see both being used in different APIs. Please let me know your thoughts. Thanks!

**Comment by scopsy** [comment]
Oh sorry, missed the notification :|

The parameter should be "_id" of the group. We can specify the following pattern as a response:
```
{
      acknowledged: true,
      status: 'deleted',
}
```

**Comment by deepak-sreekumar** [comment]
@scopsy  @florian-lefebvre  Raised PR:https://github.com/novuhq/novu/pull/1921 for the missing endpoints in notification groups. Please take a look and let me know. Thanks!

**Comment by peoray** [comment]
Is this issue still valid?

**Comment by florian-lefebvre** [comment]
I think so however somebody else needs to tackle it since @deepak-sreekumar doesn't seem available

**Comment by peoray** [comment]
Sure @florian-lefebvre will send a PR today

**Comment by peoray** [comment]
@florian-lefebvre does the repo power https://docs.novu.co/api/create-notification-group/?

**Comment by florian-lefebvre** [comment]
Yes basically it generates some api docs by default but adding files overwrites those defaults, if that makes sense

**Comment by peoray** [comment]
@florian-lefebvre No, it doesn't. I can't find the current `create` and `get` pages that exist already

**Comment by florian-lefebvre** [comment]
There is no files for the notification group yet because they're autogenerated. You can create `notification-group/get.md` and `notification-group/create.md` and take example on https://github.com/novuhq/api-docs/blob/main/content/code-examples/notification-templates/create.md

**Comment by peoray** [comment]
@florian-lefebvre okay, thanks
