### ISSUE TITLE
`@novu/node`: complete the changes module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1322]
- [x] Get
- [x] Get count
- [x] Apply one
- [x] Apply many
- [x] https://github.com/novuhq/api-docs/pull/15

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by L-390** [comment]
Can you assign this issue to me? I would like to give it a try

**Comment by florian-lefebvre** [comment]
cc @scopsy

**Comment by florian-lefebvre** [comment]
Has the doc been updated @jainpawan21? If not please let this issue open

**Comment by florian-lefebvre** [comment]
https://github.com/novuhq/api-docs/tree/main/content/code-examples

**Comment by L-390** [comment]
I just stpotted this in the code:
```typescript
applyAll() {
    throw new Error('Method not implemented.');
  }
```

implement that method, or does the endpoint not exist yet?

**Comment by florian-lefebvre** [comment]
I have no idea. @scopsy?
