### ISSUE TITLE
`@novu/node`: complete the environments module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1323]
- [x] #1928
- [x] #1370
- [x] https://github.com/novuhq/api-docs/pull/22

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by Wyfy0107** [comment]
I can work on this. I'll add the 2 missing endpoints fist and complete the doc

**Comment by florian-lefebvre** [comment]
Code examples are located at https://github.com/novuhq/api-docs/tree/main/content/code-examples

**Comment by scopsy** [comment]
@Wyfy0107 should I assign you ?

**Comment by Wyfy0107** [comment]
Btw where can I write the docs ?

**Comment by florian-lefebvre** [comment]
At https://github.com/novuhq/api-docs/tree/main/content/code-examples but I'd recommend waiting for now, there is an ongoing discussion on discord about errors in the project. If an issue is opened I'll post the link here

**Comment by jainpawan21** [comment]
@Wyfy0107 
Let us know if you need help in this.

**Comment by florian-lefebvre** [comment]
As promised: https://github.com/novuhq/api-docs/issues/13

**Comment by florian-lefebvre** [comment]
@Wyfy0107 do you need help?

**Comment by Wyfy0107** [comment]
> @Wyfy0107 do you need help?

Haven't had the time to work on this, but probably I can do it this weenkends.

**Comment by Wyfy0107** [comment]
Do we have any example doc yet and what's the format should be like, because it looks quite simple here: https://github.com/novuhq/api-docs/tree/main/content/pages/api-reference

**Comment by florian-lefebvre** [comment]
You can look at https://github.com/novuhq/api-docs/tree/main/content/code-examples/subscribers

**Comment by Wyfy0107** [comment]
> You can look at https://github.com/novuhq/api-docs/tree/main/content/code-examples/subscribers

This look like documentation for node client lib, but the current node client does not have environment module yet, does it make sense to add the doc now ? Should I add support for environment module first to the node client and then add the doc ?

**Comment by florian-lefebvre** [comment]
Yes you must add it to the node client before taking care of the docs 👍

**Comment by Wyfy0107** [comment]
> @Wyfy0107 ping me when you've contributed to the docs and I'll review

Sure, I'll work on the doc soon

**Comment by Wyfy0107** [comment]
I opened a PR, please check: https://github.com/novuhq/api-docs/pull/22
