### ISSUE TITLE
`@novu/node`: complete the feed module

### ISSUE THREAD

**Issue by florian-lefebvre** [novuhq/novu#1324]
- [ ] Create
- [ ] Get
- [ ] Delete
- [ ] Update (no endpoint or not documented)
- [ ] Completed docs

Feel free to tell me if there's more I'm missing and I'll update the list.

**Comment by aggmoulik** [comment]
Hey @florian-lefebvre I can work on this issue.

**Comment by florian-lefebvre** [comment]
cc @scopsy

**Comment by scopsy** [comment]
Added you @aggmoulik 🙏

**Comment by VoidCupboard** [comment]
Is @aggmoulik working on this? If he isn't able to do it (I has been over a week), I would be glad to work on this issue :)

**Comment by aggmoulik** [comment]
@VoidCupboard Yes, I will fix this today.

**Comment by florian-lefebvre** [comment]
@aggmoulik please, if you don't have time to work on this that's not a problem! Just tell us so that we can assign someone else

**Comment by viveknshah** [comment]
Happy to pick this up if you are caught up @aggmoulik 
Happy to help out @florian-lefebvre since  its been about 3 weeks of inactivity here.

**Comment by florian-lefebvre** [comment]
cc @jainpawan21 please assign @viveknshah instead
