### ISSUE TITLE
i18n - Odia Support

### ISSUE THREAD

**Issue by Rutam21** [novuhq/novu#1327]
## Why?
Recently we introduced an easy way to add translations for the @novu/notification-center component interface. So you can either specify a translation object or pass a premade translation. Read more about it on the [docs](https://docs.novu.co/notification-center/react-components#customize-the-ui-language).

## How?
- Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.
- Add your translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts
- Add the language code to I18NLanguage type at lang.ts file.
- Submit a PR 🙂

**Comment by Rutam21** [comment]
@ainouzgali @scopsy Please assign this issue to me as I am a native Odia Speaker.

**Comment by davidsoderberg** [comment]
Hi @Rutam21 I did see that you already have two issues assigned to you please complete those first 😄

**Comment by Rutam21** [comment]
@davidsoderberg I have already raised PR for the error response status. And this and the other one are translation issues only which I will complete today itself. Rest assured, I am not overburdened 😅

**Comment by davidsoderberg** [comment]
Okay @Rutam21 it is now assigned to you 😄
