### ISSUE TITLE
🚀 Feature: Africastalking SMS Provider

### ISSUE THREAD

**Issue by alphaolomi** [novuhq/novu#1330]
### 🔖 Feature description

SMS Provider for Novu

### 🎤 Why is this feature needed ?

From AT landing page, "Powering Communications Solutions Across Africa"
As one of the leading SMS provider in Africa, Using Novu for African focused application will be easier than ever

### ✌️ How do you aim to achieve this?

building an AT SMS Provider for Novu

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ComBarnea** [comment]
Hey @alphaolomi, as you request I am assigning this to you :)

**Comment by p-fernandez** [comment]
Assigning to you @peoray
