### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Josnapkb** [novuhq/novu#1334]
### 📜 Description

Messaging 

### 👟 Reproduction steps

@asgeirf @

### 👍 Expected behavior

👍 good

### 👎 Actual Behavior with Screenshots

Working

### 💻 Operating system

Something else

### 🤖 Node Version

iOS 15+

### 📃 Provide any additional context for the Bug.

Stucks

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
@Josnapkb not sure what this issue is about, but closing this for now.
