### ISSUE TITLE
I18n(FR) 

### ISSUE THREAD

**Issue by thomasbnt** [novuhq/novu#1356]
Recently Novu has introduced an easy way to add translations for the `@novu/notification-center` component interface. So I would like to add support for the French language.

Please assign this issue to me.

**Comment by ainouzgali** [comment]
Hi @thomasbnt! Thank you for wanting to contribute to novu! 
But it seems there is already support for [French language ](https://github.com/novuhq/novu/blob/main/packages/notification-center/src/i18n/languages/fr.ts) :)
You can see all supported languages [here](https://docs.novu.co/notification-center/react-components#customize-the-ui-language)

**Comment by scopsy** [comment]
@thomasbnt @ainouzgali closing this issue for now. @thomasbnt let me know if we missed something here and we should re open :)

**Comment by thomasbnt** [comment]
> Hi @thomasbnt! Thank you for wanting to contribute to novu! 
> But it seems there is already support for [French language ](https://github.com/novuhq/novu/blob/main/packages/notification-center/src/i18n/languages/fr.ts) :)
> You can see all supported languages [here](https://docs.novu.co/notification-center/react-components#customize-the-ui-language)

Oooh sadly 😐
