### ISSUE TITLE
Test APNS provider functionality - iOS

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#1366]
As you might have seen, we finished the work on APNS integration. We are looking for someone with iOS experience to test end to end the integration.

The idea is to run simple test for functionality - 
create notifications through web + API and make sure those are received as expected.

**Comment by ffex** [comment]
Hey there! I'm interested to this issue, maybe I need a little help. It is interesting project I'm pretty confident that I could help.

Can give me more information about test this functionality? there is documentation yet about APNS? Thanks
