### ISSUE TITLE
__Originally posted by @Josnapkb in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3329__

### ISSUE THREAD

**Issue by Josnapkb** [novuhq/novu#1383]
__Originally posted by @Josnapkb in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3329__

__Originally posted by @Josnapkb in https://github.com/novuhq/novu/issues/1336__

**Comment by Predeactor** [comment]
?
![Screenshot_20221003-064759_GitHub.png](https://user-images.githubusercontent.com/61093863/193503521-d5c229a5-0835-4885-a4ab-c3bfdec3db1c.png)

**Comment by scopsy** [comment]
Hi @Josnapkb, what is this issue about?
