### ISSUE TITLE
🐛 Bug Report: Add to the documentation how to use the "subscriber" variable.

### ISSUE THREAD

**Issue by nevo-david** [novuhq/novu#1386]
### 📜 Description

There is a way to access the "subscriber" variable, but it's not in the documentation.

### 👟 Reproduction steps

I tried to look for it here
https://docs.novu.co/platform/templates

And couldn't find it, got a message from Gali and George on the discord server.

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 💻 Operating system

MacOS

### 🤖 Node Version

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by vish-han** [comment]
Hey I would love to take-up this issue , please assign me

**Comment by Susmita-Dey** [comment]
@nevo-david Kindly assign it to me.

**Comment by ainouzgali** [comment]
Hi @vish-han I'm assigning you :) Let us know if you need anything. 
@Susmita-Dey thank you! I've assigned you to the issue you opened💪🏻

**Comment by jainpawan21** [comment]
Hi @vish-han 
How is it going with issue implementation.
Let us know if you need any help

**Comment by jainpawan21** [comment]
Hi @Susmita-Dey, 
We highly appreciate your interest in contribution.
I assigned you API keys issue.
We encourage for one issue per contributor at a time.
Thanks 🙏🏻

**Comment by nevo-david** [comment]
Hi @jainpawan21, there is a variable available in every field called "subscriber" it contains the name, email, etc... of the person the notification will be sent to. Still, this variable appears outside the documentation.

**Comment by scopsy** [comment]
We have added a new variables pane and autocomplete in the UI. Also seen that an FAQ was added under https://docs.novu.co/platform/subscribers 

so closing this issue for now 🙏
