### ISSUE TITLE
🚀 Docs: Improve line in `Introduction.md` file

### ISSUE THREAD

**Issue by Susmita-Dey** [novuhq/novu#1390]
### 🔖 Feature description

I want to change this line. 

![image](https://user-images.githubusercontent.com/79099734/193554473-5a3a4665-2b40-45d4-b061-8eaac41d172d.png)

### 🎤 Why is this feature needed ?

The line doesn't seems good.

### ✌️ How do you aim to achieve this?

I'll change this to:

```
As developers, we tend to create abstractions, but following the growing number of integrations, channels of communication that are sent becomes a burden on the team and is usually implemented only on an as just-make-it-work-mode.
```

### 🔄️ Additional Information

This is under hacktoberfest contribution. Kindly assign this to me so that I can make a PR soon. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
@Susmita-Dey I assigned you :)

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey I assigned you :)

Thanks

**Comment by ainouzgali** [comment]
Thanks!
