### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [novuhq/novu#1391]
- **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  -  [ ] question about how to use this project

- **Summary**

_I will add a github action which greets user whenever someone makes a PR or Issue by posting a comment._

- **Other information**

Can I do that @nevo-david ?

**Comment by oba2311** [comment]
@iampearceman

**Comment by scopsy** [comment]
I'm not quite sure about this functionality as it will only add more noise for the notification system on github.

@MrKrishnaAgarwal can we make it only for first-time contributors? And else, what would you write there or suggest writing there?

**Comment by MrKrishnaAgarwal** [comment]
I can make it for first-time contributors also, I'll write similar to this:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/100597998/193581204-86fdde8b-0767-43d0-bf81-edbc0a91d15e.png">

**Comment by MrKrishnaAgarwal** [comment]
@scopsy

**Comment by MrKrishnaAgarwal** [comment]
**This action will check if it's the first pull request or issue to the repo and greet them.**
