### ISSUE TITLE
Docs: To make some grammatical changes in introduction.md file 

### ISSUE THREAD

**Issue by AshishSharma1203** [novuhq/novu#1400]
# Description

I want to make some changes to the following line. 

<img width="770" alt="Capture" src="https://user-images.githubusercontent.com/92261209/193584433-fcc08d2c-552e-4b98-b5f2-9b01346894c8.PNG">

# Why is this change needed?
The line doesn't seem good.

## Type of change
I will change this to:

``` 
Novu’s goal is to help developers create meaningful transactional communication between the product and its users. All with an easy-to-use API and outstanding developer experience.

```
# Additional Information
This repository is under hacktoberfest contribution. Kindly assign this to me so that I can make a Pull Request soon. 

# Have you read the Code of Conduct?

-  [x] I have read the  [Contribution guidelines for this project](https://github.com/novuhq/novu/blob/694d4999fe3df2a0472fb5a80174d27be272ec5e/CONTRIBUTING.md)

# Are you willing to submit PR?
Yes, I am willing to submit a PR.

**Comment by ainouzgali** [comment]
Go for it 🚀 Thanks

**Comment by AshishSharma1203** [comment]
> Go for it 🚀 Thanks

Thanks. Please add hacktoberfest label to it 🥺

**Comment by AshishSharma1203** [comment]
I have made the required change and had created the pull request for it. Please review it and merge it .

**Comment by AshishSharma1203** [comment]
Thanks for merging the PR. Closing the issue now .
