### ISSUE TITLE
🚀 Feature: Api authorization not clear

### ISSUE THREAD

**Issue by codingmickey** [novuhq/novu#1409]
### 🔖 Feature description

Not exactly a bug, but there should be specified that the API requests that are to be made required a header which is "Authorization": "ApiKey API_KEY_FROM_ADMIN_PANEL"
So that should be mentioned in the first section of the docs

### 🎤 Why is this feature needed ?

For people to know exactly how the authorization is being done in the API and not randomly looking through the discussions page

### ✌️ How do you aim to achieve this?

Just by adding a new section just below the API endpoint..
And hopefully to each and every API example that is being portrayed

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by codingmickey** [comment]
Yea wasted some of my time yesterday regarding it.. so should I work on this issue?

**Comment by florian-lefebvre** [comment]
Yes go for it!

**Comment by scopsy** [comment]
@codingmickey I believe best would be to add something similar to https://docs.novu.co/api/client-libraries/ as an MD page describing the the Authorization process for the API.

**Comment by florian-lefebvre** [comment]
We also have to explain how to access admin feature, using the Bearer token (personal login). Related to #1294

**Comment by codingmickey** [comment]
> @codingmickey I believe best would be to add something similar to https://docs.novu.co/api/client-libraries/ as an MD page describing the the Authorization process for the API.

yea was this thinking of doing something similar to that, but I can't find where the source of this is located, like where are the API docs defined?

**Comment by florian-lefebvre** [comment]
https://github.com/novuhq/api-docs/tree/main/content/

**Comment by codingmickey** [comment]
Thanks, aTON!! I thought I was even unable to find such a thing and would feel dumb for asking

**Comment by florian-lefebvre** [comment]
There are issues while running it so I suggest you only edit/add markdown and make a PR
