### ISSUE TITLE
🐛 Bug Report: Incomplete Heading Information

### ISSUE THREAD

**Issue by slim-codes** [novuhq/novu#1411]
### 📜 Description

There are 2 issues that I found with the page in https://novu.co/hacktoberfest

- Firstly, the links under the **How to contribute** section all point to novu.co which isn't right
- Secondly, There are placeholder texts under the subheadings (_Lorem Ipsum...._ ). I suggest replacing these texts with meaningful info that actually summarizes what each subheading represents

### 👟 Reproduction steps

1. Go to novu.co/hacktoberfest
2. Scroll down to **How to contribute** section
3. Notice the peculiarities described above

### 👍 Expected behavior

- **View Issue** links should point to actual links
- **Subheading** text should not be placeholders (Lorem Ipsum..)

### 👎 Actual Behavior with Screenshots

![Screenshot from 2022-10-03 18-18-56](https://user-images.githubusercontent.com/72257135/193666610-1d8a2e93-403e-4529-8b4e-6ce1da3cdcee.png)

### 💻 Operating system

Linux

### 🤖 Node Version

15+

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by 201B153** [comment]
Can I work on it?

**Comment by gefgu** [comment]
@slim-codes and @201B153 It seems the subheadings problem are already solved: 
![image](https://user-images.githubusercontent.com/53129852/193950326-5f0d1b44-2217-414e-84de-ad85b6dab153.png)

**Comment by 201B153** [comment]
ok i will find another issue
