### ISSUE TITLE
🐛 Bug Report: Sendgrid provider ignores credentials.senderName

### ISSUE THREAD

**Issue by sebastiaanviaene** [novuhq/novu#1417]
### 📜 Description

The sendgrid provider does not take into account the `senderName` property of the credentials, allthough it is required.
I have created a [PR](https://github.com/novuhq/novu/pull/1418) to fix the issue

### 👟 Reproduction steps

1. Configure the sendgrid provider as an email integration
2. Fill in the senderName
3. Trigger a notification with an email block in the workflow
4. The mail just shows the sender email address but not the senderName

### 👍 Expected behavior

The mail should show the senderName, I've tested it on my PR and now it actually does 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/6652818/193764101-eb0c08ba-99fc-4be7-aa69-828ba6eb708a.png">

### 👎 Actual Behavior with Screenshots

<img width="274" alt="image" src="https://user-images.githubusercontent.com/6652818/193763407-865e1fea-0f99-4c5b-b92f-49fe077948ea.png">

![image](https://user-images.githubusercontent.com/6652818/193763689-271a4bfc-24ce-4c23-be02-8289b4f3ccce.png)

### 💻 Operating system

Linux

### 🤖 Node Version

Stable (16.x)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sebastiaanviaene** [comment]
My PR can be found [here](https://github.com/novuhq/novu/pull/1418) 🤞

**Comment by scopsy** [comment]
<img width="892" alt="CleanShot 2022-10-06 at 11 28 33@2x" src="https://user-images.githubusercontent.com/8872447/194290726-9e094461-0ffe-4a8f-ac27-79d1aa426e07.png">

@oba2311 this was merged 2 days ago ☝️
