### ISSUE TITLE
🚀 Feature: i18n - Indonesian Support

### ISSUE THREAD

**Issue by rahmat-st** [novuhq/novu#1422]
### 🔖 Feature description

Adding Indonesian Language Support

### 🎤 Why is this feature needed ?

For Indonesian Peoples, Who don't understand other languages or have trouble dealing with them.

### ✌️ How do you aim to achieve this?

Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.
Add your translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts
Add the language code to I18NLanguage type at lang.ts file.
Submit a PR

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sidbelbase** [comment]
assign this task to me please?

**Comment by rahmat-st** [comment]
hey @sidbelbase, I want to wotk for it
