### ISSUE TITLE
🐛 Bug Report: Pagination issue for subscriber feed endpoint

### ISSUE THREAD

**Issue by mohamed-cherifi** [novuhq/novu#1433]
### 📜 Description

When querying the `/v1/subscribers/:subscriberId/notifications/feed` [endpoint](https://docs.novu.co/api/get-a-notification-feed-for-a-particular-subscriber/) the returned result only has the `data` object without the pagination. 

ie: 
```
{
   "data": [...]
} 
```

### 👟 Reproduction steps

Query the `/v1/subscribers/:subscriberId/notifications/feed` endpoint

### 👍 Expected behavior

return something like:
```
{
    totalCount: 0,
    data: [...],
    pageSize: 0,
    page: 0
}
```

### 👎 Actual Behavior with Screenshots

<img width="738" alt="image" src="https://user-images.githubusercontent.com/97466700/193903128-fa4235b5-8bf3-4b45-98e5-2fc2d13a95f9.png">

### 💻 Operating system

MacOS

### 🤖 Node Version

v16.10.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by jainpawan21** [comment]
@scopsy Can I work on this?
