### ISSUE TITLE
🚀 Feature: i18n - Korean Support

### ISSUE THREAD

**Issue by Susmita-Dey** [novuhq/novu#1452]
### 🔖 Feature description

Adding Korean language support.

### 🎤 Why is this feature needed ?

For Korean people who are not familiar with English.

### ✌️ How do you aim to achieve this?

- Add a new translation file here: `packages/notification-center/src/i18n/languages`. You can follow the en.ts example.
- Add your translation import to the TRANSLATIONS object at `packages/notification-center/src/i18n/lang.ts`
- Add the language code to I18NLanguage type at `lang.ts` file.
- Updating `/docs/docs/notification-center/react-components.md` for the language added.
- Submit a PR

### 🔄️ Additional Information

I haven't found any alternatives. I want to work on this issue as part of hacktoberfest

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abhilipsasahoo03** [comment]
@Susmita-Dey I think this issue has been resolved in this PR https://github.com/novuhq/novu/pull/1420

**Comment by scopsy** [comment]
Indeed, closing this one 🙏
