### ISSUE TITLE
🚀 Feature: Improve README.md file

### ISSUE THREAD

**Issue by Susmita-Dey** [novuhq/novu#1454]
### 🔖 Feature description

The link of Report bug in the `README.md` file needs to be updated.

### 🎤 Why is this feature needed ?

In my opinion, if there a bug then folks can report directly by creating a new issue to report bug

### ✌️ How do you aim to achieve this?

I want to modify the link of Report bug from <a href="https://github.com/novuhq/novu/issues">Report Bug</a> to <a href="https://github.com/novuhq/novu/issues/new?assignees=&labels=type%3A+bug&template=bug_report.yml&title=%F0%9F%90%9B+Bug+Report%3A+">Report Bug</a>

### 🔄️ Additional Information

![image](https://user-images.githubusercontent.com/79099734/194051791-8c5686a0-de65-4cec-84c6-8b6a4e5e9b24.png)

Kindly assign it to me as part of Hacktoberfest.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Just assigned, that makes a lot of sense. Thank you @Susmita-Dey!

**Comment by Susmita-Dey** [comment]
Solved using #1487
