### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by JayKaneriya11** [novuhq/novu#1496]
### 📜 Description

We deploy novu on AWS EC2 instance using docker for the testing purpose and we are very much satisfied with it. But when we are testing SMS  service using twilio, we find out that Handlebars template syntax is not working properly. We send payload in trigger SDK function and also added Handlebars variable in SMS template but still we are getting blank value in place of variable. If we set default value then it always showing default value in final message. We checked payload is going properly with request. isRequired validation is also working properly.

### 👟 Reproduction steps

1. Deploy novu on Linux using docker
2. Create message template and add SMS template with handlebars template
3. trigger event and validate message

### 👍 Expected behavior

It should be display message with handlebars variable on user's side

### 👎 Actual Behavior with Screenshots

It actually showing blank value instead of custom value given in payload.
![Screenshot 2022-10-06 at 12 21 51 PM](https://user-images.githubusercontent.com/102660585/194233908-0fbdf860-f3ab-4248-aa34-a9bb60d44a24.png)

### 💻 Operating system

Linux

### 🤖 Node Version

Same as Given in Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
This might be related to a bug we fixed, do you mind trying to pull the `latest` github tag? We will be releasing a patch release with the fix soon. For now it's only available on the managed version.

**Comment by JayKaneriya11** [comment]
It's working in latest code.
