### ISSUE TITLE
🚀 Feature:  update discussion link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [novuhq/novu#1507]
### 🔖 Feature description

updating github discussion link 

### 🎤 Why is this feature needed ?

the link should redirect to a new discussion.

### ✌️ How do you aim to achieve this?

By replacing [Github discussion](https://github.com/orgs/novuhq/discussions)  to  [Github discussion](https://github.com/orgs/novuhq/discussions/new)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Sanket2055** [comment]
i would like to work on this issue , please assign it to me !

**Comment by saimaheshtaduri** [comment]
@scopsy

**Comment by jainpawan21** [comment]
@saimaheshtaduri Do you like to work on this?

**Comment by saimaheshtaduri** [comment]
yes! please assign to me.

**Comment by jainpawan21** [comment]
Awesome, Some one from Novu team will review your PR
