### ISSUE TITLE
🚀 Feature: update feature link in contributing.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [novuhq/novu#1508]
### 🔖 Feature description

update feature submission link.

### 🎤 Why is this feature needed ?

It is better if the feature submission link directly redirects to new feature template page.

### ✌️ How do you aim to achieve this?

By replacing : 
**If a feature is missing, you can request a new one by [submitting an issue](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md#submitting-an-issue) to our GitHub Repository.**

to : 
If a feature is missing, you can request a new one [here](https://github.com/novuhq/novu/issues/new?assignees=&labels=feature&template=feature_request.yml&title=%F0%9F%9A%80+Feature%3A+) on our GitHub Repository.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by BoseSj** [comment]
Submitted a PR regarding this issue. #1533

**Comment by saimaheshtaduri** [comment]
@BoseSj you need to get an issue assigned to you first before working on it. This issue is raised by me and I'm waiting for @scopsy  to assign me this issue.

**Comment by BoseSj** [comment]
Okay. I rediscovered the issue while going through the docs. So created a PR. Then I saw your issue, and also noticed that it is > 20hrs already and still not assigned to anyone. Thought it would be good to mention it in my PR. TY😄

**Comment by saimaheshtaduri** [comment]
@scopsy
