### ISSUE TITLE
🚀 Feature: i18n Language Support [ Bangla ] 

### ISSUE THREAD

**Issue by kaustav202** [novuhq/novu#1518]
### 🔖 Feature description

Adding Bengali language support to the project.

### 🎤 Why is this feature needed ?

Will be helpful Bengali people who may not be familiar with English.

### ✌️ How do you aim to achieve this?

- Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.
- Add the translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts
- Add the language code to I18NLanguage type at lang.ts file.
- Updating /docs/docs/notification-center/react-components.md for the language added.
- Submitting PR

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kaustav202** [comment]
Can I take this up?

**Comment by davidsoderberg** [comment]
yes sure I have assigned you @kaustav202

**Comment by kaustav202** [comment]
I turns out the feature was added with #1139  but the the translation file has some inaccuracies so I'm raising a new issue
