### ISSUE TITLE
🐛 Bug Report: Issue in Italian Translation of notification center

### ISSUE THREAD

**Issue by TheZal** [novuhq/novu#1539]
### 📜 Description

The translation file is missing the `settings` keyword

### 👟 Reproduction steps

None

### 👍 Expected behavior

There should be the translation for `settings`

### 👎 Actual Behavior with Screenshots

The translation is missing

### 💻 Operating system

Windows

### 🤖 Node Version

18.10.0

### 📃 Provide any additional context for the Bug.

I would like to fix this if you assign this to me, thanks!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
Sure! I assigned you @TheZal
