### ISSUE TITLE
🐛 Bug Report: Invalid Discord Link In Contributing.md

### ISSUE THREAD

**Issue by kailashchoudhary11** [novuhq/novu#1562]
### 📜 Description

The Link has expired!

### 👟 Reproduction steps

Open Contributing.md file. Go to Need help section. Click on Discord Channel.

### 👍 Expected behavior

We should we redirected to the discord server of novuhq.

### 👎 Actual Behavior with Screenshots

Not applicable

### 💻 Operating system

Windows

### 🤖 Node Version

16.16.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
From a check i've made it looks like already been resolved 🙏 closing this for now
