### ISSUE TITLE
Update link to "Report Bug" in the README.md file

### ISSUE THREAD

**Issue by abhilipsasahoo03** [novuhq/novu#1570]
### 🔖 Feature description

The link of Report Bug in the `README.md` file needs to be updated to direct them to create a new `Report Bug` issue.

### 🎤 Why is this feature needed ?

In my opinion, if there is a bug, folks can report directly by creating a new issue through the `Report Bug` link. However, currently it directs them to list of issues.

### ✌️ How do you aim to achieve this?

I want to modify the link of Report bug from <a href="https://github.com/novuhq/novu/issues">Report Bug</a> to <a href="https://github.com/novuhq/novu/issues/new?assignees=&labels=type%3A+bug&template=bug_report.yml&title=%F0%9F%90%9B+Bug+Report%3A+">Report Bug</a>

### 🔄️ Additional Information

![image](https://user-images.githubusercontent.com/79099734/194051791-8c5686a0-de65-4cec-84c6-8b6a4e5e9b24.png)
![Screenshot_2022-10-08-19-09-19-142_com.github.android.jpg](https://user-images.githubusercontent.com/80174214/194710719-ce9ae6a2-b49e-4736-b5f2-4ba8c7e4015f.jpg)

Kindly assign it to me as part of Hacktoberfest.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

 ### 🏢 Have you read the Code of Conduct?

 - [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

 Yes I am willing to submit a PR!

**Comment by abhilipsasahoo03** [comment]
@BoseSj I'd like to work on this :)

**Comment by Chaitanya-087** [comment]
Hi! I would like to work on this issue

**Comment by abhilipsasahoo03** [comment]
> Hi! I would like to work on this issue

Hi, a PR has already been created for this issue.
