### ISSUE TITLE
🚀 Feature: Update the Link of `Discord` `Slack` `FCM` `Expo` in provider section

### ISSUE THREAD

**Issue by bishal7679** [novuhq/novu#1573]
### 🔖 Feature description

Update the Link of `Discord` `Slack` `FCM` `Expo` in provider section

### 🎤 Why is this feature needed ?

As Slack, Discord, FCM, EXPO providers are already added to the main codebase. So we should update the corresponding link in the `#provider` list

### ✌️ How do you aim to achieve this?

Linking the already added providers in README.md

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by YuriDevAT** [comment]
Hi. I would like to work on this issue.

**Comment by YuriDevAT** [comment]
Thank for letting me know @bishal7679 👍🏽
