### ISSUE TITLE
🚀 Feature:  Add i18n - SpanishLanguage Support

### ISSUE THREAD

**Issue by bhattabhi013** [novuhq/novu#1591]
### 🔖 Feature description

People in Spain speak Spanish so this feature is to help them.

### 🎤 Why is this feature needed ?

This feature is needed for people who don't know English but know Spanish.

### ✌️ How do you aim to achieve this?

-Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.
-Add your translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts
-Add the language code to the I18NLanguage type in lang.ts file.
-Updating /docs/docs/notification-center/react-components.MD for the language added.
Submit a PR

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by Smartmind12** [comment]
Hey @bhattabhi013 ! There's already a PR submitted on this language: https://github.com/novuhq/novu/pull/944
