### ISSUE TITLE
🚀 Feature: Add a dependabot to Automate dependency checks

### ISSUE THREAD

**Issue by bishal7679** [novuhq/novu#1596]
### 🔖 Feature description

Adding a dependabot to Automate dependency checks very easily.

### 🎤 Why is this feature needed ?

To automate the dependency checking it is needed!

### ✌️ How do you aim to achieve this?

Want to add a dependabot.yml to create a dependabot

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
I am closing this for now, as discussed in the suggested PR. Thank you @bishal7679 !
