### ISSUE TITLE
🐛 Bug Report: Updating Novu Handbook

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/novu#1642]
### 📜 Description

Most of the logos and wbesite links are yet to be attached in the Novu Handbook.

### 👟 Reproduction steps

Check it out at (https://handbook.novu.co/tools)

### 👍 Expected behavior

All links and logos for all company sites/ providers should be updated.

### 👎 Actual Behavior with Screenshots

![Screenshot 2022-10-11 at 9 57 49 PM](https://user-images.githubusercontent.com/91927689/195148121-6cdb151d-2dc3-4319-8a54-7e62d6d9faf9.png)

### 💻 Operating system

MacOS

### 🤖 Node Version

x

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Thanks for letting us know! Unfortunately the handbook is not available for outside edits. But passed this internally so we can try to fix this ASAP. Closing this for now here as it's not related to the Novu codebase.
