### ISSUE TITLE
🐛 Bug Report: Issue in Finnish Translation of notification center

### ISSUE THREAD

**Issue by das-amit** [novuhq/novu#1668]
### 📜 Description

The translation file is missing the settings keyword

### 👟 Reproduction steps

None

### 👍 Expected behavior

There should be the translation for _settings_

### 👎 Actual Behavior with Screenshots

The translation is missing
![Screenshot (818)](https://user-images.githubusercontent.com/91092039/195169847-ccdd46fc-21b2-4f5e-969e-4d350e0ab276.png)

### 💻 Operating system

Windows

### 🤖 Node Version

18.10.0

### 📃 Provide any additional context for the Bug.

I would like to fix this if you assign this to me, thanks!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
Awesome. Should I assign you, @das-amit ?

**Comment by das-amit** [comment]
@ainouzgali sure, I would like to contribute:)
