### ISSUE TITLE
🐛 Bug Report: Issue in Ukrainian Translation of notification center

### ISSUE THREAD

**Issue by das-amit** [novuhq/novu#1674]
### 📜 Description

The translation file is missing the _settings_ keyword
Similar bug #1668 

### 👟 Reproduction steps

None

### 👍 Expected behavior

There should be the translation for settings

### 👎 Actual Behavior with Screenshots

The translation for "settings" is missing
![Screenshot (819)](https://user-images.githubusercontent.com/91092039/195276627-63ff3a00-c542-4238-881d-a4655a394be6.png)

### 💻 Operating system

Windows

### 🤖 Node Version

18.10.0

### 📃 Provide any additional context for the Bug.

I would like to fix this if you assign this to me, thanks!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by DonnachaHeff** [comment]
Can I pick this issue up?
