### ISSUE TITLE
Documentation: Couple of issues with grammar and presentation of README.md

### ISSUE THREAD

**Issue by slim-codes** [novuhq/novu#1688]
### 🔖 Feature description

I noticed some problems with the README file. Here they are in no particular order:

### Why section

- The **Why** heading should be replaced with **Why Novu?**
- Under the **Why** section, There's a paragraph that reads "notifications are spread around the **code**. What Code, I think the author meant something else here. Maybe something like notifications are spread around the world
- Replace **between the system** with **between a system**

### Features section

- Notification should be in plural form with an (s) in "Easily manage **notification** over multiple channels"

### Embeddable notification center section

- **iframe** should be **IFrame**

### Providers section

- consider replacing **simple to use** with **convenient** under Providers section. 

### Need help section

- consider changing **with the project** to **with this project**
- **then join our Discord..** should be **join our Discord**

### Thanks to all contributors section

- **Thanks a lot!** is repeated twice here. remove the redundant **thanks a lot**

> **Note**: I noticed that some headings are in **T**itle **C**ase while some are in **S**entence Case. This is not recommended. The casing of the headings should be consistent (i.e either all headings be in Title case or Sentence case but not a mixture of both)

### 🎤 Why is this feature needed ?

These changes should be implemented to improve the integrity of the README 

### ✌️ How do you aim to achieve this?

Implement the proposed changes above

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ShivamAgarwal-code** [comment]
I want to work on this issue, please assign
