### ISSUE TITLE
🚀 Feature: Deno Support

### ISSUE THREAD

**Issue by apollo79** [novuhq/novu#1696]
### 🔖 Feature description

I would find it cool if Deno support would be added. 

### 🎤 Why is this feature needed ?

Novu is a really cool project and I think it would be welcome in the Deno ecosystem too. 

### ✌️ How do you aim to achieve this?

I don't know exactly what the best choice to achieve this would be. There is [dnt](https://github.com/denoland/dnt), but it would require a complete rewrite to Deno to support Node... Maybe a separate package for Deno as [socket.io](https://github.com/socketio/socket.io-deno) has done or [feathers](https://github.com/feathersjs/feathers/tree/dove/deno) is currently working on

### 🔄️ Additional Information

It is of course possible to use Novu through [esm.sh](https://esm.sh) or the unstable [npm specifiers](https://deno.com/blog/v1.25#experimental-npm-support), but a "native" support is in my opinion better. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by raikasdev** [comment]
Deno doesn't give good benefits for the effort, would not make any sense to do this. Also NestJS doesn't support Deno.
