### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by muditchoudhary** [novuhq/novu#1729]
### 📜 Description

On the index.md file inside the path `main/docs/docs/channels/chat/`. All three links [here, Discord, Slack] are invalid and point to a 404 page. 

![image](https://user-images.githubusercontent.com/74391865/195862923-96d1b296-cbcc-4ac7-a42c-27cd901dad24.png)

### 👟 Reproduction steps

1. Go to index.md file 
2. Click on any link.

### 👍 Expected behavior

The Links should open a page.

### 👎 Actual Behavior with Screenshots

The links are opening a 404 error page.

![image](https://user-images.githubusercontent.com/74391865/195863452-e95d0c11-0af1-4849-8ddd-f002404ec4bb.png)

### 💻 Operating system

Linux

### 🤖 Node Version

16.13.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by muditchoudhary** [comment]
Can I work on this?

**Comment by muditchoudhary** [comment]
Hey @p-fernandez I can't seem to find the platform folder inside main.

I followed this url : `https://github.com/muditchoudhary/novu/blob/main/platform/subscribers#updating-subscriber-credentials`

Is platform present in this repo?

**Comment by p-fernandez** [comment]
I think you are looking for this: https://github.com/novuhq/novu/blob/main/docs/docs/platform/subscribers.md
It is in the docs section.

**Comment by scopsy** [comment]
@muditchoudhary this link is actually working correctly when visiting the docasarurus: https://docs.novu.co/channels/chat/

This is an internal redirect used by our docs site, so I believe this issue can be closed. Let me know if I missed anything 🙏

**Comment by muditchoudhary** [comment]
@scopsy Ohh..yaa that's correct. I tried it on GitHub and misunderstood it.

Thanks!!
