### ISSUE TITLE
🐛 Bug Report: Broken Link in monorepo-structure.md

### ISSUE THREAD

**Issue by SarojWasti** [novuhq/novu#1743]
### 📜 Description

The image link to monorepo-structure.jpeg in monorep-structure.md is broken.

### 👟 Reproduction steps

Head over to https://github.com/novuhq/novu/blob/main/docs/docs/community/monorepo-structure.md
and you will see the alt text instead of image. If you click on the image source, 404 page is shown.

### 👍 Expected behavior

The link should point to the monorepo-structure.jpeg image source.

### 👎 Actual Behavior with Screenshots

![monorepo-broken](https://user-images.githubusercontent.com/69208771/196020992-361b617f-2626-405e-ae24-38b57987867f.png)

### 💻 Operating system

Windows

### 🤖 Node Version

16.17.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SarojWasti** [comment]
@davidsoderberg Please assign me if you think it should be fixed.

**Comment by scopsy** [comment]
@SarojWasti the link is actuall correct: https://docs.novu.co/community/monorepo-structure 

The preview is not working only in GitHubs md preview. 

Closing this 🙏

**Comment by SarojWasti** [comment]
Thanks for addressing this. Is it the same with #1745 ?

**Comment by scopsy** [comment]
I believe so
