### ISSUE TITLE
🐛 Bug Report: nodemailer sendername field & secure field

### ISSUE THREAD

**Issue by shtelzerartem** [novuhq/novu#1753]
### 📜 Description

1. Nodemailer has a `Sender name` field in UI, even though it's not used in 
https://github.com/novuhq/novu/blob/2ee01b8c97d77b9f3295e46720385c137a0bfd57/providers/nodemailer/src/lib/nodemailer.provider.ts
![image](https://user-images.githubusercontent.com/20266461/196166799-88318ba6-8185-4c47-a846-572b1f9755e9.png)

2. Secure field is a textfield, therefore not intuitive, user should leave this field empty if it's `false` and provide some value if `true`

### 👟 Reproduction steps

1. Go to integration Store
2. Click on Nodemailer integration

- Check https://github.com/novuhq/novu/blob/2ee01b8c97d77b9f3295e46720385c137a0bfd57/providers/nodemailer/src/lib/nodemailer.provider.ts

### 👍 Expected behavior

1. There should be no `Sender name` field in UI.
2. Secure field should be checkbox or switch 

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/20266461/196166799-88318ba6-8185-4c47-a846-572b1f9755e9.png)
![image](https://user-images.githubusercontent.com/20266461/196168245-b803ea54-f5dc-4276-95a3-2112bff9f299.png)

### 💻 Operating system

MacOS

### 🤖 Node Version

v16.14.2

### 📃 Provide any additional context for the Bug.

From my point of view it's better to rename it to custom SMTP connection and not Nodemailer :)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by shtelzerartem** [comment]
@jainpawan21 hey! Could you please assign the issue for @CursedRock17?
It looks like he has started working on this issue and actually made a great progress there!

**Comment by ainouzgali** [comment]
@CursedRock17 are you ok with being assigned?

**Comment by CursedRock17** [comment]
@ainouzgali sure I can try and take on this issue

**Comment by peoray** [comment]
@scopsy do we have a way to add checkbox or toggle to the modal. So far, I have only seen text fields

**Comment by jainpawan21** [comment]
@peoray Yes new filed type can be added
check this file
https://github.com/novuhq/novu/blob/next/apps/web/src/pages/integrations/components/IntegrationInput.tsx
