### ISSUE TITLE
🐛 Bug Report: Broken Link to provider-template

### ISSUE THREAD

**Issue by SarojWasti** [novuhq/novu#1760]
### 📜 Description

The GitHub Template link in [create-provider](https://docs.novu.co/community/create-provider) documentation is redirecting to 404 page.

### 👟 Reproduction steps

Visit https://docs.novu.co/community/create-provider#sms-provider, scroll down and click on [GitHub Template](https://github.com/novuhq/provider-template) link.

### 👍 Expected behavior

It's expected behavior might be redirecting to provider-template doc or repo which I'm also not sure about without discussing.

### 👎 Actual Behavior with Screenshots

n/a

### 💻 Operating system

Windows

### 🤖 Node Version

16.17.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SarojWasti** [comment]
@davidsoderberg Take a look and let me know if the issue is applicable. And I also don't know about the working link so it's hard to fix. :)

**Comment by scopsy** [comment]
@SarojWasti this template was actually deprecated and removed. Do you mind just deleting this link at all from the docs page?
