### ISSUE TITLE
🚀 Feature: Implement Handlebars Dateformat

### ISSUE THREAD

**Issue by wouter-toppy** [novuhq/novu#1769]
### 🔖 Feature description

It whould be nice if we can format/modify dates in the email templates generated with handlebars

https://www.npmjs.com/package/handlebars-dateformat

### 🎤 Why is this feature needed ?

- To format dates in a human format when the payload is ISO
- make expressions like `{{#equals (dateFormat payload.someDate "N") 7 }}`  to check if its sunday

### ✌️ How do you aim to achieve this?

```
Handlebars.registerHelper('dateFormat', require('handlebars-dateformat'));
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by chavda-bhavik** [comment]
@jainpawan21 @scopsy I would like to work on it, if it's relevant. 🙂

**Comment by iampearceman** [comment]
Hey @chavda-bhavik! Mind to share the status of this issue?

**Comment by chavda-bhavik** [comment]
Yes, @iampearceman we can close it. This feature is developed and merged.
