### ISSUE TITLE
[Docs] Broken link in digest.md

### ISSUE THREAD

**Issue by digambar-t7** [novuhq/novu#1776]
### 📜 Description

In the digest.md file, there is a broken link to [`Workflow photo`](https://github.com/novuhq/novu/blob/main/img/digest-flow.png).
And this link isn't working as per our expectations.It leads us to a `404` page not found error.

### 👟 Reproduction steps

1. Go to [digest.md](https://github.com/novuhq/novu/blob/main/docs/docs/platform/digest.md)
2. In the `Digest Node` section you will see `Workflow photo`
3. Now click on it

### 👍 Expected behavior

It should lead us to the actual `Workflow photo`.The one which is intended to be shown.

### 👎 Actual Behavior with Screenshots

![Screenshot from 2022-10-18 22-36-24](https://user-images.githubusercontent.com/92970968/196499908-ad08a2e3-cdcb-43c9-bf79-93217e48c55f.png)

### 💻 Operating system

Linux

### 🤖 Node Version

v16.13.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
This photo is not broken, please see https://docs.novu.co/platform/digest 

It is only not visible on GitHub's md preview. 

Closing this 🙏
