### ISSUE TITLE
🚀 Feature: custom SMTP provider

### ISSUE THREAD

**Issue by shtelzerartem** [novuhq/novu#1778]
### 🔖 Feature description

Create non-branded, "_library-agnostic_" "Custom SMTP" provider to the integrations store. 

### 🎤 Why is this feature needed ?

This can help users who are not familiar with _Nodemailer_, or _EmailJS_, or other provider  to focus on setting up integration and not deciding whether to choose one provider or another. This choice could be, and from my point of view, should be managed by Novu's core team. 

### ✌️ How do you aim to achieve this?

We can rename existing or create a new integration for "Custom SMTP" provider. 
Under the hood, it will be good to use _Nodemailer_ library as it's the most popular library for these purposes. 

### 🔄️ Additional Information

Another option is to consolidate all existing SMTP providers into one "Custom SMTP" integration, giving user an ability to choose which provider to use, for example, in select. And also we can have _Nodemailer_ selected by default with a helper text explaining these select options.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
I would even suggest renaming nodemailer title to be a custom SMTP service, instead of creating a new one. Since it will just be duplicate. 

Should I assign you if you willing to work on this @shtelzerartem ?

**Comment by shtelzerartem** [comment]
@scopsy hey, right now we have logos and not titles, should we design a logo for Custom SMTP or add an ability to pass title to the component?

**Comment by shtelzerartem** [comment]
@scopsy @davidsoderberg I decided to design the logo by myself, adding a title prop sounds too much for this little change. Here is a screenshot: 
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/20266461/197343194-056aa3c2-b66a-4fc8-9a60-3f7977328f73.png">

**Comment by iampearceman** [comment]
Hey @shtelzerartem, any updates on this issue?

**Comment by shtelzerartem** [comment]
Hey @iampearceman, was busy for some time, excuse me for this. I have just fixed, what @p-fernandez demanded to fix and resolved merge conflicts.
