### ISSUE TITLE
🚀 Feature: there is no logo-link on web.novu.co

### ISSUE THREAD

**Issue by MaximFedarau** [novuhq/novu#1781]
### 🔖 Feature description

When user click on logo on `web.novu.co` page it leads to home, i.e. `web.novu.co`, for example if user is on `web.novu.co/integrations`.

### 🎤 Why is this feature needed ?

Because all other `Novu` websites have this feature:

- <img align="center" width="185" alt="demo-1" src="https://user-images.githubusercontent.com/87207122/196545981-e200a0e9-4981-41c8-816e-114b2c45fb87.png">

- <img align="center" width="150" alt="demo-2" src="https://user-images.githubusercontent.com/87207122/196546027-080a13fa-7371-426a-91d7-ae5420b22190.png">

But `web.novu.co` does not:

- <img align="center" width="172" alt="demo-3" src="https://user-images.githubusercontent.com/87207122/196546141-c4cb39cf-7462-4ad0-9dc8-07738cc44520.png">

### ✌️ How do you aim to achieve this?

1) Go to `components/layout/components/HeaderNav.tsx`.
2) ```import { Link } from 'react-router-dom';```
3) Embed `<img/>` into `<Link/>`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MaximFedarau** [comment]
@scopsy, @davidsoderberg , please, check my suggestion. And if you are agree, assign it to me.

**Comment by scopsy** [comment]
Just assigned you ^ 🎉
