### ISSUE TITLE
🐛 Bug Report: on not exposed in embed.js

### ISSUE THREAD

**Issue by JustinBack** [novuhq/novu#1791]
### 📜 Description

Listening to `action_click` or `notification_click` events is not possible via iframe due to a missing function `on`.

### 👟 Reproduction steps

1. Include embed.js
2. Initialize Novu
3. Use the on function

### 👍 Expected behavior

It should listen to *_click events

### 👎 Actual Behavior with Screenshots

Throws an undefined function error
![DA700480-9489-41D2-BD6C-C85A6FD4D800](https://user-images.githubusercontent.com/40178814/196872677-34be13d3-592e-426c-a285-b4b0ccae3db5.jpeg)
![B33DF557-1271-47BA-B8F4-FF1C0B39943E](https://user-images.githubusercontent.com/40178814/196872683-6a24575a-3030-4c4a-aa12-81ee98de822d.jpeg)

### 💻 Operating system

MacOS

### 🤖 Node Version

Latest Docker Image

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by mani-rsg** [comment]
Hi @scopsy, I would like to work on this, you can assign this to me

**Comment by vedant-z** [comment]
@JustinBack May I take this?

**Comment by JustinBack** [comment]
> @JustinBack May I take this?

Sure, I cannot find time to work on this particular issue

**Comment by jainpawan21** [comment]
Hi @vedant-z Are you interested to work on this?

**Comment by vedant-z** [comment]
@jainpawan21 Ya sure. I just need some help on how should I approach this 😃

**Comment by scopsy** [comment]
Hi @vedant-z I think it would be best to request help over our discord regarding this. Did you had a chance to have any progress on this?

**Comment by jainpawan21** [comment]
@LetItRock, Is this issue fixed in one of your recent PR?

**Comment by scopsy** [comment]
@jainpawan21 from a test i made this is still haven't been exposed.
