### ISSUE TITLE
[NV-190] - Add input interface for Push providers

### ISSUE THREAD

**Issue by ComBarnea** [novuhq/novu#18]
* **I'm submitting a ...**\
  \[ \] bug report\
  \[x\] feature request\
  \[ \] question about the decisions made in the repository\
  \[ \] question about how to use this project
* **Summary**\
  Need to create output interface for push providers. The interface should be based on planned providers, properties are the common logic properties found on all/most.

### **Suggested example:**

```
interface IPushOptions {
    to: string | string[];
    html: string;
    from?: string;
    avatar?: string;
    redirect?: string;
}
```

**Comment by ComBarnea** [comment]
So just looked through this one, changes seem to be quite extant major outline is:
### Template Engineer
Need to add minimal attributes to allow standard push options across providers
```ts
{
  title: 'New push notification',
  body: 'Powered by AppFeel',
  custom: {
    sender: 'AppFeel',
  },
  contentAvailable: true,
  icon: '', 
  badge: '',
  image: '',
  clickAction: '', 
  locKey: '',
  titleLocKey: '',
  sound: 'ping.aiff',
  launchImage: '', 
  action: '', 
  category: '',
}
```
These are minimal changes needed for templates unless I missed something major. Most parts are expected to be string, handlebars, or a function.

### Provider
Push Providers are mostly the same as normal ones, except for one thing, each provider acts like a multi-provider with Web, IOS, Android, etc... subchannels with input for every single one of these types. Each provider needs to be aware of what subchannel has been configured.

### Trigger Engine
In order to accommodate subchannels in each push provider there are a couple of changes:

#### Change one provider to all applicable providers
<img width="556" alt="Screen Shot 2021-11-21 at 0 37 43" src="https://user-images.githubusercontent.com/8877285/142742791-8be62ee6-1b09-4f50-b7ed-520ad8e9fef8.png">
this might be a problem if both IOS and Android are triggered but first provider only solve one of them.

#### Add automatic device detection
In order to make sure triggers are easy, the main trigger API is going to be device agnostic, the template provider needs to separate ids (just as seen [here](https://github.com/appfeel/node-pushnotifications/blob/master/src/push-notifications.js)). 

#### Subchannel based input
Not like any other provider with simple API like ```emails: string[]``` needs inputs with all options for subchannels, something like:
```ts
{
  deviceIdsGCM: string[];
  deviceIdsAPN: string[];
  deviceIdsWNS: string[];
  deviceIdsADM: string[];
  deviceIdsWebPush: string[];
  deviceIdsUnk: string[];
}
```

One last thing in addition to the main trigger API with an override of the template and known variables.

@notifirehq/notifire-contributors would love to get your thoughts about this, let me know if you have any questions, or something is lacking.

**Comment by steinroe** [comment]
Congrats on the funding!

Do you plan to also support expo push? As far as I understand your concept, [Expo Push](https://docs.expo.dev/push-notifications/overview/) would not require sub- / multi-providers and can be a quick win when it comes to push support in novu.

**Comment by scopsy** [comment]
Thank you @steinroe ! We definitely plan on adding support for the expo push. We are currently making some work on underline token subscriber token management #526 as part of this ticket. Once it's finalized, we can have support for direct and push channels aswell :)

**Comment by vbylen** [comment]
👍  for Expo push integration
