### ISSUE TITLE
🐛 Bug Report: .nvmrc file contains an old node version

### ISSUE THREAD

**Issue by devXprite** [novuhq/novu#1809]
### 📜 Description

According [Novu Docs](https://docs.novu.co/community/run-locally/) minimum Required node version is `16.15.1` but in [.nvmrc](https://github.com/novuhq/novu/blob/main/.nvmrc) file its `14.18.3`

### 👟 Reproduction steps

1. Go to [Novu Docs](https://docs.novu.co/community/run-locally/) and check minimum Node.js version.

### 👍 Expected behavior

It should be `16.15.1` in .nvmrc

### 👎 Actual Behavior with Screenshots

n/a

### 💻 Operating system

Linux

### 🤖 Node Version

v16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by neelshah2409** [comment]
May I work on this issue !
