### ISSUE TITLE
Queuing of notifications

### ISSUE THREAD

**Issue by ChakshuGautam** [novuhq/novu#181]
## What and Why?
We have a bunch of notification providers that don't provide good uptime and have to tried again and again. Need a mechanism for failure management and re-trigger notifications after a backoff. Currently I wasn't able to find a queue being persisted for the following use cases
- Bulk notifications
- Scheduled notifications
- Retrying on failure

If there is something already there, if you can point me to the relevant code sections, that would be great. Thanks.

**Comment by kharbanda14** [comment]
Hi @ChakshuGautam how about bull queue package ? it uses redis for queuing messages and can cover the scheduled notifications and retrying on failure.

for more info : https://www.npmjs.com/package/bull

**Comment by DomnicAmalan** [comment]
We should create queue based on external solutions like rabbitMQ and Kafka, etc

**Comment by jainpawan21** [comment]
Is this issue still relevant @scopsy?

**Comment by scopsy** [comment]
We are using internally Bullmq overe redis with the provided functionality that was released on 0.7.0 (if i recall correctly :P) 

So we can close this for now.
