### ISSUE TITLE
Broken Link in notification-center/react-components.md

### ISSUE THREAD

**Issue by Astrodevil** [novuhq/novu#1814]
### 📜 Description

Broken Link in notification-center/react-components.md

Go to [here](https://github.com/novuhq/novu/blob/main/docs/docs/notification-center/react-components.md#subscriber-preferences)

Click on Notification Center with a cog, you will get page not found 404.

**Please let me know if this is actual problem or is working fine at your end.**

### 👟 Reproduction steps

- Editing old link/destination with [this](https://github.com/novuhq/novu/blob/main/docs/static/img/notification-list-cog.png)

### 👍 Expected behavior

![2](https://user-images.githubusercontent.com/73425223/197268658-fc2a7e46-76df-4252-ac75-1ef0f0e4e7e9.png)

### 👎 Actual Behavior with Screenshots

![3](https://user-images.githubusercontent.com/73425223/197268726-1aece307-9329-4cad-91d8-a974b91c8ce1.png)

### 💻 Operating system

Windows

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by TheLearneer** [comment]
@Astrodevil The image is working properly.
Ref: https://docs.novu.co/notification-center/react-components#subscriber-preferences

Just a note, the image is supposed to be working properly on the docs site itself.
So they might seem broken when browsing the markdown file itself

**Comment by Astrodevil** [comment]
Cool
