### ISSUE TITLE
🐛 Bug Report: Integrations Store responsive design issue

### ISSUE THREAD

**Issue by MaximFedarau** [novuhq/novu#1816]
## On small width devices & browser windows list of integrations looks weird:

https://user-images.githubusercontent.com/87207122/197292568-66a3739e-c3e7-4457-99c0-77c2059cd0b0.mov

## I created a solution, which use only `Mantine API` without changing any other props:

https://user-images.githubusercontent.com/87207122/197293109-19230744-cdf3-4494-ab61-b98f44da9122.mov

### 👟 Reproduction steps

1. Go [here](https://web.novu.co/integrations).
2. Use `Device Toolbar` or just change width of your browser window.

### 👍 Expected behavior

It should stretch normally without going outside of the window.

### 👎 Actual Behavior with Screenshots

***Only videos ⬆️***

### 💻 Operating system

MacOS

### 🤖 Node Version

18.10.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MaximFedarau** [comment]
@scopsy, @davidsoderberg, if my proposal is correct, please, assign this issue to me😅

**Comment by MaximFedarau** [comment]
@scopsy, there is a second path:

https://user-images.githubusercontent.com/87207122/197383470-e8c5a850-c8d4-4596-9a5c-c25b59c22619.mov

As you can see:
- [x] it is fully responsive - I use special formula for this.
- [x] nothing is out of bounds
- [x] padding is constant

But instead of using `<Grid/>` from `@mantine/core` I created my own custom styled component. 
So, what is the best way for Novu: to use `@mantine/core` (first option) or `styled-components` (second option)?

**Comment by MaximFedarau** [comment]
@scopsy, @p-fernandez, @davidsoderberg, so which way better?

**Comment by scopsy** [comment]
Hi, @MaximFedarau are you on our Discord? Wanted to send you a DM to ask something :) https://discord.com/invite/WCaaK8nwZ7

**Comment by MaximFedarau** [comment]
Hi, @scopsy. Joined Discord. My nickname is navajo: navajo#8621.
