### ISSUE TITLE
🚀 Feature: add report a bug section in contributing.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [novuhq/novu#1837]
### 🔖 Feature description

There is a section on how to raise feature request issue but not for reporting a bug.

### 🎤 Why is this feature needed ?

Users can easily report bugs if there is a section for it.

### ✌️ How do you aim to achieve this?

Add a section on how to report a bug just as feature request section.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by saimaheshtaduri** [comment]
@nevo-david @scopsy

**Comment by AniqJaved** [comment]
I would like to work on this🚀 but not sure where to start.🤔
