### ISSUE TITLE
🚀 Feature: add link to the logo

### ISSUE THREAD

**Issue by Abubakrce19** [novuhq/novu#1848]
### 🔖 Feature description

![image](https://user-images.githubusercontent.com/104122959/197832549-ee27b505-0e07-4bf4-8c1e-1b7742493999.png)

### 🎤 Why is this feature needed ?

,

### ✌️ How do you aim to achieve this?

,

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by msboffl** [comment]
Can you please assign this to me, I will work

**Comment by Abubakrce19** [comment]
I am already waiting 
So they assign me

**Comment by AbubakrChan** [comment]
@davidsoderberg 
Thank you for assigning 
I will soon start working.

**Comment by davidsoderberg** [comment]
@AbubakrChan I assigned @Abubakrce19...?

**Comment by AbubakrChan** [comment]
> @AbubakrChan I assigned @Abubakrce19...?

Oh nevermind

**Comment by Abubakrce19** [comment]
Pr created #1858 
Please have a look
Thank you
