### ISSUE TITLE
Hyperlinking Hacktoberfest image.

### ISSUE THREAD

**Issue by Abubakrce19** [novuhq/novu#1872]
![image](https://user-images.githubusercontent.com/104122959/198327247-93e0262e-ea1e-4816-8759-b5611751e8de.png)
Hyperlinking Hacktoberfest image in readmemd file so the user can go to official hacktoberfest website with a single click.
Thank you

- **Summary**

- **Other information** (_e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc._)

**Comment by MarkusEicher** [comment]
Hi maintainers. I would like to get assigned to this and work on it. Thanks in advance and have a good day.

**Comment by Abubakrce19** [comment]
I created this issue and I am already waiting to get assigned.

**Comment by MarkusEicher** [comment]
Sorry. Didn't realize that. I'm out then. Hope you get it assigned soon. Good luck.

**Comment by p-fernandez** [comment]
Thank you for your contribution @Abubakrce19. But unfortunately the link was on purpose to Novu's website instead of directly to Hacktoberfest website so this is not an issue.
