### ISSUE TITLE
🐛 Bug Report: Senders name missing in AWS SES

### ISSUE THREAD

**Issue by pontusab** [novuhq/novu#1887]
### 📜 Description

When using SES `Sender name` is missing in the email.name

### 👟 Reproduction steps

Add SES, Add Sender name, trigger email.and 

### 👍 Expected behavior

The sender's name should be visible in the Email.

### 👎 Actual Behavior with Screenshots

<img width="290" alt="Screenshot 2022-10-28 at 11 54 51" src="https://user-images.githubusercontent.com/655158/198559903-2818f1d1-c0c7-43e9-bb1e-dd2c96b73c09.png">

### 💻 Operating system

Linux

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by p-fernandez** [comment]
@pontusab if you'd like to work on it I can assign it to you.

**Comment by pontusab** [comment]
Please do 👍

**Comment by scopsy** [comment]
Hi @pontusab do you still want to take a look at this or should I un-assign you, perhaps someone else can help with this 🙏

**Comment by jainpawan21** [comment]
@pontusab Removed your assignment. May be anyone else can look into this.
Please let us know if you still want to work on this.

**Comment by p-fernandez** [comment]
Closing in favour of https://github.com/novuhq/novu/issues/2225
