### ISSUE TITLE
[NV-1241] Couple of web link at Terms of Use Page are not clickable

### ISSUE THREAD

**Issue by PrakashGatiyala** [novuhq/novu#1892]
- **I'm submitting a...**
   - [ ] bug report
   - [X] feature request
   - [ ] question about the decisions made in the repository
   - [ ] question about how to use this project

- **Summary**
![image](https://user-images.githubusercontent.com/34413515/198581245-63bed3db-5a6b-41c6-b121-dd61f91e8512.png)

Highlighted web links are not clickable at https://novu.co/terms/ Page. 
I want to make them clickable. 

Hi @jainpawan21 I'd like to work on this. Could you please assign me this issue? :)

- **Other information** (_e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc._)

<sub>[NV-1241](https://linear.app/novu/issue/NV-1241/couple-of-web-link-at-terms-of-use-page-are-not-clickable)</sub>

**Comment by PrakashGatiyala** [comment]
Hi @p-fernandez I am not able to find code of https://novu.co/terms/ page in this repo. Could you please guide me?

**Comment by p-fernandez** [comment]
I am sorry but only core maintainers have access to the content of the Website. I will unassign the issue.

**Comment by peoray** [comment]
guess this has been resolved :)
