### ISSUE TITLE
🐛 Bug Report: Correct grammar and flow in code_of_conduct.md file

### ISSUE THREAD

**Issue by Vanshiii203** [novuhq/novu#1897]
### 📜 Description

I would like to Correct grammar and flow in code_of_conduct.md file

### 👟 Reproduction steps

NA

### 👍 Expected behavior

There are many fixes that are needed.

### 👎 Actual Behavior with Screenshots

NA

### 💻 Operating system

Windows

### 🤖 Node Version

node-v16.18.0-x64

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by ryuusama09** [comment]
Is this issue still up for grabs ?
