### ISSUE TITLE
Change issues and discussions to be links instead of plain text in CONTRIBUTING.md

### ISSUE THREAD

**Issue by washbin** [novuhq/novu#1898]
While reading `CONTRIBUTING.md` it may be better if the user is able to visit the issues and discussions tab by clicking the texts, i.e links. Currently both issues and discussions are plain text instead of being links to the respective tabs.

This is a pretty minor change and doesn't really fit in either bug or a feature so I opted for a blank issue.

Will you be willing to work on this issue ?
Yes, I have a PR ready just in case this is deemed to be a good enough change.

**Comment by Akshay-21** [comment]
Hey Hi, @washbin can you assign to me this issue.
actually i changed the issues and discussion link in CONTRIBUTING.md and also requested PR, kindly see this.

**Comment by washbin** [comment]
@Akshay-21  I am not a maintainer of novu, I'm just a fellow contributor like yourself. So, I can't assign the issue to anyone.

And as you can probably see, I already had an active PR #1899 mentioning this issue.
Opening a second PR for the same thing is probably against [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md), the very thing you are making an edit to.
Hope you understand :smile:

**Comment by Akshay-21** [comment]
> @Akshay-21 I am not a maintainer of novu, I'm just a fellow contributor like yourself. So, I can't assign the issue to anyone.
> 
> And as you can probably see, I already had an active PR #1899 mentioning this issue. Opening a second PR for the same thing is probably against [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md), the very thing you are making an edit to. Hope you understand 😄

@washbin yeah ok, but here i updated some new link ref. for issues and create your own. like this one and others also.

![image](https://user-images.githubusercontent.com/32409386/198822148-4143f87d-0927-4064-ac6b-5c8a56b797de.png)

**Comment by p-fernandez** [comment]
@Akshay-21 as a deference to @washbin for opening the issue I will assign it to them. But I would suggest you both to collaborate in the same PR. You both would get recognised as contributors for that. You can combine all the PRs open in that one.
https://github.com/novuhq/novu/pull/1899
https://github.com/novuhq/novu/pull/1904
https://github.com/novuhq/novu/pull/1905

**Comment by washbin** [comment]
If thats the verdict then, @Akshay-21 could you pull from the pr #1899  and publish your additional changes there.

However, @p-fernandez they seem to have worked on some changes in README.md in one of the PRs mentioned above which is not related to this issue.
If it could be counted a sepearate contribution then I guess it will be okay for them to merge both of their PRs into single one and the to the repo, whereas this could be merged as it is, since it only addresses the above mentioned issue.

**Comment by p-fernandez** [comment]
Let's do that. Anyway, for future reference, if different people collaborate in a PR they are both credited.

**Comment by washbin** [comment]
Great, then I guess it should be okay to close this issue since the original PR has been approved and the other open PR's do have a reference to here if @Akshay-21 needs more info for their side.

**Comment by Akshay-21** [comment]
Hey Hi, @p-fernandez then exactly what do i need to do?

**Comment by Akshay-21** [comment]
Okay, Thanks!
