### ISSUE TITLE
[NV-189] - Add output interface for push providers

### ISSUE THREAD

**Issue by ComBarnea** [novuhq/novu#19]
* **I'm submitting a ...**\
  \[ \] bug report\
  \[x\] feature request\
  \[ \] question about the decisions made in the repository\
  \[ \] question about how to use this project
* **Summary**\
  Need to create output interface for push providers. The interface should be based on planned providers, properties are the common logic properties found on all/most.

### **Suggested example:**

```
interface IPushResoponse {
    id: string;
    status: IMessageResoponseStatus; 
}
```

**Comment by galezra** [comment]
Hey @ComBarnea, is this issue still relevant? If yes, I don't see any email/sms response interface to be consistent with them in the code, just "ISendMessageSuccessResponse"

**Comment by ComBarnea** [comment]
Hey @galezra this issue is blocked by issue #18, and should be looked at again after this one. I think as much as we can, we should aim to get the same interface response messages for all channels, as much as we can.

**Comment by galezra** [comment]
I missed that, thanks for letting me know.
