### ISSUE TITLE
🐛 Bug Report: The link of image in monorepo-structure.md file is not correct 

### ISSUE THREAD

**Issue by Vanshiii203** [novuhq/novu#1909]
### 📜 Description

https://user-images.githubusercontent.com/94471189/198822145-fa738757-6294-4459-8f5f-dd696d3f84b3.mp4

### 👟 Reproduction steps

NA

### 👍 Expected behavior

https://docs.novu.co/assets/images/monorepo-structure-eea6a227a77765ad9baefc5b18360001.jpeg
this should be the link 

### 💻 Operating system

Windows

### 🤖 Node Version

node-v16.18.0-x64

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vrabe** [comment]
same issue: #1743
