### ISSUE TITLE
To imrove Readme.md file 

### ISSUE THREAD

**Issue by AshishSharma1203** [novuhq/novu#1918]
# Description

I want to make some changes to the following line. 

![image](https://user-images.githubusercontent.com/92261209/198865127-a64a08d0-fe6a-4940-bfec-442855b2fce0.png)

# Why is this change needed?
The line doesn't seem good , the sentence flow is not well.

## Type of change
I will change this to:

``` 
Building a notification system is complicated. At first, it seems like just sending an email, but in reality, it's just the beginning. Today, users expect a multi-channel communication experience via email, SMS, push, chat, and other channels. An ever-growing list of providers is popping up daily, and notifications are spread around the code. Novu's goal is to simplify notifications and provide developers with the tools to create meaningful communication between the system and it's user.

```
# Additional Information
This repository is under hacktoberfest contribution. Kindly assign this to me so that I can make a Pull Request soon. 

# Have you read the Code of Conduct?

-  [x] I have read the  [Contribution guidelines for this project](https://github.com/novuhq/novu/blob/694d4999fe3df2a0472fb5a80174d27be272ec5e/CONTRIBUTING.md)

# Are you willing to submit PR?
Yes, I am willing to submit a PR.

**Comment by p-fernandez** [comment]
Thanks for raising the issuee, but unfortunately I will have to close it as it is not providing any improvement and one of the two corrections suggested is a grammatical error.
