### ISSUE TITLE
No "Open in Gitpod button present"

### ISSUE THREAD

**Issue by Asmit2952** [novuhq/novu#1946]
There are .gitpod.yml and .gitpod.dockerfile available in this repository, but open in Gitpod option is not available. We can include a button like this in the Readme:
 [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#<your-repository-url>)

**Comment by davidsoderberg** [comment]
Hi @Asmit2952, that is because we have had problem with using Gitpod for Novu... Not sure it is fixed yet 🤔 @ainouzgali @djabarovgeorge do you know if it is fixed?

**Comment by djabarovgeorge** [comment]
I don't believe it was fixed yet.

**Comment by scopsy** [comment]
This was already added here: https://docs.novu.co/community/run-locally

So closing this for now. Thank you @Asmit2952 for mentioning this.
