### ISSUE TITLE
[NV-1240] 🚀 Feature: Ability to set specific Email Headers (to track campaigns)

### ISSUE THREAD

**Issue by mediana** [novuhq/novu#1949]
### 🔖 Feature description

Different email providers proposes to add custom headers when sending campaigns to better track them (by allowing to group messages). It also permits getting statistics and so on.
For instance, Mailjet documentation explains their implementation : https://dev.mailjet.com/smtp-relay/custom-headers/
Also, for SendGrid : https://docs.sendgrid.com/for-developers/sending-email/building-an-x-smtpapi-header#categories

### 🎤 Why is this feature needed ?

In my case, I could implement this to have greater segmentation over smtp relay usage.

### ✌️ How do you aim to achieve this?

Ability to set these custom header (param + value) per email notification template.
Also, ability to override these settings (or values only) by the payload of a Novu API trigger.

### 🔄️ Additional Information

Custom headers could look like this :
`X-Mailjet-Campaign: “Name of my campaign“`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1240](https://linear.app/novu/issue/NV-1240/🚀-feature-ability-to-set-specific-email-headers-to-track-campaigns)</sub>

**Comment by scopsy** [comment]
Thanks for the report @mediana 🙏 Will try to take a closer look at this later.

**Comment by oba2311** [comment]
Hi @mediana thanks for this!

We are looking at custom layouts right now so I'm wondering whether creating your own layout could solve for this?
Let's work together to understand how this can be tackled soon 👍

**Comment by mediana** [comment]
Hello @oba2311 How can I help ?

**Comment by scopsy** [comment]
I think the easiest way for now to achieve this would be with overrides object during trigger. And later perhaps add it to the template editor. @mediana wdyt about this approach

**Comment by mediana** [comment]
@scopsy This approach looks interesting indeed. I’ve checked the documentation about this. Though, I can’t find an example on how to use this, and how the object to input looks like. Do you mind providing such an example, so I can test this and give you a feedback. Maybe the doc can already be updated with this information.

**Comment by scopsy** [comment]
Closing this in favor of provider overrides: https://docs.novu.co/sdks/framework/typescript/steps/introduction#providers-overrides-object
