### ISSUE TITLE
🐛 Bug Report: Web Docker container gets existed with JavaScript heap out of memory

### ISSUE THREAD

**Issue by chavda-bhavik** [novuhq/novu#1950]
### 📜 Description

When using self-hosted version of Novu, many times docker container for `Web` gets terminated with error `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`.
![js-memory-heap log](https://user-images.githubusercontent.com/50201755/199474180-e0010d70-489d-4c0e-a939-bf18dec563f3.png)

### 👟 Reproduction steps

Deploy **Novu** on Ubuntu instance with `Ubuntu version: 22.04 LTS` and `11 GB RAM`, and start using it.

### 👍 Expected behavior

It should work smoothly.

### 👎 Actual Behavior with Screenshots

Web container gets terminated with error `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`.
![js-memory-heap log](https://user-images.githubusercontent.com/50201755/199474180-e0010d70-489d-4c0e-a939-bf18dec563f3.png)

### 💻 Operating system

Linux

### 🤖 Node Version

v16.15.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by p-fernandez** [comment]
Could you provide more logs from the container of what was being executed before running out? Thus will make it easier to investigate.
What was the running time of the container before terminating for the memory error?

**Comment by chavda-bhavik** [comment]
@p-fernandez I couldn't able to find exact timing for start and end of container but it happened two times, one was after 2 month and another was after 1 day.
And Docker logs showing the same entries of the image I attached previously.

**Comment by chavda-bhavik** [comment]
Hey, @scopsy @p-fernandez Any update on this issue? I can spare some time on it if you can provide some hints on possible ways to tackle this issue.

**Comment by scopsy** [comment]
Hi @chavda-bhavik, I would mainly suggest to think of a different static content serving options instead of the simple-http server npm package we use there. Maybe we can use NGINX? Or any other static serving solution? 

Internally we use Netlify, so we don't experience any problems with it. But previously I have used nginx for static files so maybe it will also work here. Wdyt?

**Comment by chavda-bhavik** [comment]
Didn't tried serving static content with Nginx before, But I will look into it. @scopsy can you assign this issue to me?

**Comment by scopsy** [comment]
@chavda-bhavik I think I actually noticed that it happens during the initialization of the container right? Seems like the `build` command is the one that is failing. If this is the case, you would need to provide a bit more RAM for your docker daemon that running the web component

**Comment by chavda-bhavik** [comment]
@scopsy RAM can be the reason for this issue. Actually `memory` error was happening some days after the application started. And from my observation on `apps/web/Dockerfile`, it looks like `build` will be happening during docker image creation time, instead of container initialization time, Am I right?

**Comment by scopsy** [comment]
Yes, we are doing initialization time build because we need to compile some environment variables and inject them there. We might need to revisit this in the future as it's not the best approach.

**Comment by scopsy** [comment]
A deploy was made that should help address this in the prebuilt 0.11.0 version. @chavda-bhavik please let me know if you still see this when running the 0.11.0

Closing this for now 🙏
