### ISSUE TITLE
🐛 Bug Report: Containers are not currently optimized and are >1GB

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#1958]
### 📜 Description

The issues with the current docker containers are:
- include dev dependencies
- do not use production pnpm builds 
- include python of which is not used in the system
- they do not optimize the COPY command 
- use standard out when installing modules
- does not ensure dev dependencies are removed with pruning

The current size of the containers is ~2GB on average this can slow down deployments due to the time it takes to pull the images and can cost customers with private registries extra (average $0.10/GB per month).

### Recommendations:
- Aim to go [Distroless ](https://github.com/GoogleContainerTools/distroless) in the long-term and move to node16:alpine in the short term
- do multi-stage production builds for all containers and ensure only the app files are moved
- do silent installs to minimize the use of stdout
- use prod build flags and use prune when building in the build container
- [Bundle ](https://github.com/vercel/ncc) the app into one file/binary (This will not work for the frontend)

Containers should be  <1 GB and < 0.5GB being optimal. 

### 💻 Operating system

All 

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Cliftonz** [comment]
Just for a point of documentation, to consolidate all of the copies to one layer you would do something like this with the RUN --mount=bind capability specifically with multi-stage build.
`
RUN --mount=src=/,dest=/artifacts,from=builder \
   cp /artifacts/usr/include/header_1.h /usr/include/header_1.h \
&& cp /artifacts/usr/include/header_n.h /usr/include/header_n.h
`

**Comment by scopsy** [comment]
A few months back i've introduced some of the suggestions here to the API dockerfile which helped reduce the docker size almost in two: https://github.com/novuhq/novu/pull/933

I think combined with some of the suggestions here it could be replicated to the other docker components in the system.

**Comment by p-fernandez** [comment]
Web container has been optimised in this PR: https://github.com/novuhq/novu/pull/2944

**Comment by scopsy** [comment]
Closing this for now so we can open issue for individual packages if needed.
