### ISSUE TITLE
🚀 Feature: Update to current active version of Node (18)

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#1959]
### 🔖 Feature description

This Issue is to discuss and track the progress of updating to the next LTS version of node.

### 🎤 Why is this feature needed ?

This will allow the platform to gain from underlying improvements to the ecosystem on top of being in support for 2+ years.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by gitstart** [comment]
@scopsy I would like to pick this up
