### ISSUE TITLE
[NV-1239] 🐛 Bug Report: unable to remove CTA buttons inside in-app editor

### ISSUE THREAD

**Issue by BiswaViraj** [novuhq/novu#1969]
### 📜 Description

The CTA buttons doesnt get removed upon removing them from UI and updating it,
Upon reloading the page after the update, the CTA button appears again

### 👟 Reproduction steps

1. Open in-app editor
2. add CTA buttons
3. update to save the buttons
4. remove the CTA buttons from the UI using the `x` icon
5. update it again to save the changes
6. reload or revisit the page
7. The CTA buttons appears again.

### 👍 Expected behavior

It should delete the CTA button upon removal

### 👎 Actual Behavior with Screenshots

https://user-images.githubusercontent.com/29251776/200176289-b1324626-b685-44f7-a79c-eb3d070253e3.mov

### 💻 Operating system

MacOS

### 🤖 Node Version

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1239](https://linear.app/novu/issue/NV-1239/🐛-bug-report-unable-to-remove-cta-buttons-inside-in-app-editor)</sub>

**Comment by BiswaViraj** [comment]
Also, it seems like the issue is on the API side

**Comment by scopsy** [comment]
@BiswaViraj did you managed to do something with it? Or this one is still open?

**Comment by BiswaViraj** [comment]
It is still open

**Comment by oba2311** [comment]
@BiswaViraj need help on this one from @scopsy ?

**Comment by BiswaViraj** [comment]
Fixed in https://github.com/novuhq/novu/pull/2342
