### ISSUE TITLE
[NV-1238] 🐛 Bug Report: The tooltip on activity feed is hidden

### ISSUE THREAD

**Issue by SajMohammed** [novuhq/novu#1997]
### 📜 Description

The tooltip on activity feed tab is hidden. Seems like an indexing issue

### 👟 Reproduction steps

1. Go to activity feed tab
2. hover over the bar graph
3. no details visible

### 👍 Expected behavior

It should show the tooltip and corresponding details

### 👎 Actual Behavior with Screenshots

![Screenshot 2022-11-10 115817](https://user-images.githubusercontent.com/51795573/201019528-108e8605-b585-4f1a-a092-faf8972484cc.png)

### 💻 Operating system

Windows

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1238](https://linear.app/novu/issue/NV-1238/🐛-bug-report-the-tooltip-on-activity-feed-is-hidden)</sub>

**Comment by gitstart** [comment]
@scopsy I would like to pick this up

**Comment by scopsy** [comment]
@gitstart sure! <3

**Comment by ainouzgali** [comment]
@gitstart sorry for the confusion! This seems to have been fixed in [this PR](https://github.com/novuhq/novu/pull/2705)

Thank you💙
