### ISSUE TITLE
🐛 Bug Report: manifest error in Chrome

### ISSUE THREAD

**Issue by MaximFedarau** [novuhq/novu#1998]
### 📜 Description

When I go to web.novu.co main page and I am authorized I receive an error message:
<img width="498" alt="demo" src="https://user-images.githubusercontent.com/87207122/201082514-b44d69ba-316b-4935-97a7-8f52a957f42c.png">

### 👟 Reproduction steps

1. Go to [site](https://web.novu.co).
2. Login.
3. Open console.

### 👍 Expected behavior

Icons should exist.

### 👎 Actual Behavior with Screenshots

<img width="498" alt="demo" src="https://user-images.githubusercontent.com/87207122/201082514-b44d69ba-316b-4935-97a7-8f52a957f42c.png">

### 💻 Operating system

MacOS

### 🤖 Node Version

18.11.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by p-fernandez** [comment]
Looks like `manifest.json` just needs to be updated to only have listed the favicon as it is the only one we have in the folder.

**Comment by MaximFedarau** [comment]
@p-fernandez , or we should add these 2 icons.
Which is the preferred way?

**Comment by MaximFedarau** [comment]
@p-fernandez, @davidsoderberg, please, assign it to me.
