### ISSUE TITLE
🐛 Bug Report: ButtonTypeEnum, MessageActionStatusEnum, IMessage are not exported

### ISSUE THREAD

**Issue by hckhanh** [novuhq/novu#2005]
### 📜 Description

I believe that these types need to be exported for customization in `@novu/notification-center`

### 👟 Reproduction steps

Import ButtonTypeEnum, MessageActionStatusEnum, IMessage 

### 👍 Expected behavior

It shows errors because there are no exports for these types

### 👎 Actual Behavior with Screenshots

Can import these type

### 💻 Operating system

Windows

### 🤖 Node Version

18.12.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by jinsley8** [comment]
It looks like typescript types are only in the `@novu/shared` package.

`import { IMessage, IMessageAction, ButtonTypeEnum } from '@novu/shared'`

**Comment by scopsy** [comment]
@djabarovgeorge this is the one you handled right? Let me know if I can close this.

**Comment by djabarovgeorge** [comment]
Yes @scopsy  it was resolved in https://github.com/novuhq/novu/pull/2059
