### ISSUE TITLE
[NV-1236] 🚀 Feature: Spotlight SearchBar

### ISSUE THREAD

**Issue by MaximFedarau** [novuhq/novu#2006]
### 🔖 Feature description

`Novu` now has a Spotlight feature, but there is no hint.
So I think it's very useful to create custom SearchBar which will:
1) Help with key bindings.
2) Way to interact with the websitr for users, whuch prefer to use mouse.
Example from RTK docs:
![image0](https://user-images.githubusercontent.com/87207122/201297070-52b08d55-ee63-4194-97f9-1999ebd6563d.jpg)

### 🎤 Why is this feature needed ?

It improves `UX` very much.

### ✌️ How do you aim to achieve this?

Create custom component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1236](https://linear.app/novu/issue/NV-1236/🚀-feature-spotlight-searchbar)</sub>

**Comment by scopsy** [comment]
Not sure regarding the actual implementation if it should be on the top title or not, but perhaps we can maybe add a small text annotation at the menu to indicate a `CMD + K` is available? @oba2311 maybe we can do a design for this and perhaps @MaximFedarau can help with implementation

**Comment by MaximFedarau** [comment]
@scopsy , ok, will you send a DM with design or anything else?

**Comment by MaximFedarau** [comment]
> Not sure regarding the actual implementation if it should be on the top title
Maybe it should be in the center, like on docs page?

**Comment by scopsy** [comment]
I think it will take too much attention from the user. So would prefer to have a more subtle approach there.

**Comment by oba2311** [comment]
I will take it with the designer thanks
