### ISSUE TITLE
[NV-1235] 🚀 Feature: Push (FCM) data messages

### ISSUE THREAD

**Issue by Timonzimm** [novuhq/novu#2007]
### 🔖 Feature description

Currently Novu only allows to send what Firebase calls Notification messages, with a "notification" field in the payload. It is then automatically handled by FCM SDK as explained here: https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

This is very limiting.

The feature would allow to either:
- Send **Data message** that can be handled in the service worker with `onBackgroundMessage`, or
- Allow on Novu to customize the **Notification message** template with actions, buttons, logos, etc.

### 🎤 Why is this feature needed ?

Because otherwise you're not able to use Firebase `onBackgroundMessage` function to display actions / buttons, etc.

If you do so with the **Notification** message sent by Novu, you get the notification twice, as explained in this issue: https://stackoverflow.com/questions/66697332/firebase-web-push-notifications-is-triggered-twice-when-using-onbackgroundmessag

### ✌️ How do you aim to achieve this?

Modify Novu API + web app to allow for:
- **Data messages**
- More customization of the **Notification messages** (actions, logos, etc.)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1235](https://linear.app/novu/issue/NV-1235/🚀-feature-push-fcm-data-messages)</sub>

**Comment by jimzer** [comment]
I'm also faxing this issue. It would be great to have a solution to send data only notification with FCM 👍🏽

**Comment by oba2311** [comment]
you mean you are working on it?

@scopsy I def think we should have it done soon, if not you then let's talk 😃

**Comment by Timonzimm** [comment]
@scopsy What's the ETA for this feature? Thanks! :)

**Comment by scopsy** [comment]
Hi @Timonzimm! Unfortunately not yet, but will update here once we do. 🙏

**Comment by raikasdev** [comment]
Working on it

**Comment by oba2311** [comment]
Seems like @raikas Roni is working on it - @iampearceman ?
