### ISSUE TITLE
[NV-1157] Test Sync

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2017]
Hello World

> From [SyncLinear.com](https://synclinear.com) | [NV-1157](https://linear.app/novu/issue/NV-1157/test-sync)

**Comment by djabarovgeorge** [comment]
Looks great, I think you are missing exclamation mark

**Comment by scopsy** [comment]
My comment

**Comment by scopsy** [comment]
Test

**Comment by djabarovgeorge** [comment]
Comment number four

**Comment by djabarovgeorge** [comment]
Seven
