### ISSUE TITLE
[NV-1173] Another Test

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2020]
Test 2222

> From [SyncLinear.com](https://synclinear.com) | [NV-1173](https://linear.app/novu/issue/NV-1173/another-test)

**Comment by scopsy** [comment]
Comment from here

**Comment by djabarovgeorge** [comment]
Github comment

**Comment by djabarovgeorge** [comment]
Github comment after sync

**Comment by djabarovgeorge** [comment]
Linear comment after sync

**Comment by djabarovgeorge** [comment]
#1295

**Comment by djabarovgeorge** [comment]
> Comment from here

response

**Comment by scopsy** [comment]
Tagging @djabarovgeorge what happens

**Comment by djabarovgeorge** [comment]
I am not sure where you tagged but i got a email notification from GitHub

@scopsy

**Comment by scopsy** [comment]
@djabarovgeorge tagged in Linear :)
