### ISSUE TITLE
[NV-1187] Need option to override `tls` configuration 

### ISSUE THREAD

**Issue by Ayan-Kumar-Saha** [novuhq/novu#2023]
### 🔖 Feature description

Currently, as per the support Novu has, it only takes a couple of arguments like User, Password, Host, Port, Secure, etc to create the transport. However, while using only these my Nodemailer configuration is throwing the following error

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/8451f9d8-6652-4817-a0c4-7b80067256bb/ec2f230c-7b8d-46d4-a0e6-946df7f3980f)

I believe this has to do with an additional `tls` configuration (more on this [here](https://nodemailer.com/smtp/)) that has to be provided in order to make it work (for the SMTP details I am using). The exact same code snippet for the same functionality will be,

```
nodemailer.createTransport({
        host: process.env.MAILBOX_HOST,
        port: process.env.MAILBOX_PORT,
        secure: false,
        requireTLS: true,
        auth: {
            user: process.env.SMTP_EMAIL_ID,
            pass: process.env.SMTP_PASSWORD,
        },
        tls: { ciphers: "SSLv3" },
})
```

I believe Novu doesn't support the addition `tls` override configuration, which should be added.

*More on nodejs TLSSocket options* [*here*](https://nodejs.org/api/tls.html#tls_class_tls_tlssocket)

### 🎤 Why is this feature needed ?

I am using the same SMTP mailbox details in one of my existing projects, that I want to migrate to Novu. However, currently, it is not working. Also, I believe many others will also face the same issue.

### ✌️ How do you aim to achieve this?

Novu should be able to provide additional configuration override options like -

1. `tls`
2. `ignoreTLS`
3. `requireTLS`

### 🔄️ Additional Information

*No response*

### 👀 Have you spent some time to check if this feature request has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

*No response*

> From [SyncLinear.com](https://synclinear.com)

**Comment by p-fernandez** [comment]
I created a draft PR with ongoing work for this feature so the community can contribute and develop this feature.
https://github.com/novuhq/novu/pull/2044

**Comment by p-fernandez** [comment]
@Ayan-Kumar-Saha we have put to review the PR to implement the TSL config override. Give it a look to see if handles your needs. 👍🏻
