### ISSUE TITLE
Preheader

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2032]
GOTCHA - transfer the input preheader into custom code with the corresponding variable.

Design:
https://www.figma.com/file/ibQlg50J0zXJFPww6JaGzA/Email-Editor?node-id=176%3A1625&viewport=14829%2C-3848%2C1.06

The date is just today.

**Comment by davidsoderberg** [comment]
If the preheader property is sent in payload it will override the one provided in UI
