### ISSUE TITLE
Variables Management

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2033]
Addition - with the braces, have the empty state in the payload to explain how to add vars.

We can start with "System vars" separation, and finalize the list of system vars on PRD.

Missing design for required var, and defaults.

https://www.figma.com/file/ibQlg50J0zXJFPww6JaGzA/Email-Editor?node-id=195%3A1959&viewport=16265%2C-7167%2C1.2

**Comment by ainouzgali** [comment]
Also design for json variables @oba2311
