### ISSUE TITLE
[NV-1186] 🚀 Feature: add a way to unset a subcriber's credentials

### ISSUE THREAD

**Issue by amosbastian** [novuhq/novu#2043]
### 🔖 Feature description

It would be nice if you could unset credentials for e.g. a Slack workspace

### 🎤 Why is this feature needed ?

Currently you need to do:

```
await novu.subscribers.setCredentials('subscriberId', ChatProviderIdEnum.Slack, {
  webhookUrl: undefined,
});
```

which isn't too much of a hassle, but is potentially confusing

### ✌️ How do you aim to achieve this?

Having something like `unsetCredentials`, such as

```
await novu.subscribers.unsetCredentials('subscriberId', ChatProviderIdEnum.Slack);
```

would be nice

### 🔄️ Additional Information

I'm not sure if you guys want to, or already do support subscribing to multiple Slack work spaces / Discord servers, but that could be something to keep in mind

### 👀 Have you spent some time to check if this feature request has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

*No response*

> From [SyncLinear.com](https://synclinear.com)

**Comment by p-fernandez** [comment]
[https://github.com/novuhq/novu/pull/2039](https://github.com/novuhq/novu/pull/2039)

**Comment by oba2311** [comment]
So @scopsy  this seems done in GH?

**Comment by p-fernandez** [comment]
> So @scopsy this seems done in GH?

No, this was me linking that PR in a wrong issue. Let me fix. Apologies.
