### ISSUE TITLE
[NV-1198] Create notification template is not working using API Key

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2060]
When triggering a create notification template using API Key a 

```
{"statusCode":403,"message":"Forbidden resource","error":"Forbidden"}%
```

Is thrown, making the same request with a Bearer token from the web works as expected.

### How to reproduce

```
curl -X POST \
-H "Authorization: ApiKey REPLACE_API_KEY" \
-H "Content-Type: application/json" \
-d '{
"name": "name",
"tags": ["tags"],
"description": "description",
"active": true,
"draft": true,
"critical": true
}' \
http://localhost:3000/v1/notification-templates
```

This will fail, but if we change the Authorization to use a web `Bearer` token it successfully creates it.

> From [SyncLinear.com](https://synclinear.com) | [NV-1198](https://linear.app/novu/issue/NV-1198/create-notification-template-is-not-working-using-api-key)

**Comment by p-fernandez** [comment]
@scopsy Seems we could close this open bug. What do you thinl?

**Comment by scopsy** [comment]
Yes 🙏
