### ISSUE TITLE
🐛 Bug Report: Missing documentation on default credentials

### ISSUE THREAD

**Issue by ryshoooo** [novuhq/novu#2077]
### 📜 Description

Missing documentation on the default user credentials

### 👟 Reproduction steps

There is no documentation on where I can find the default provided user when running Novu locally.

### 👍 Expected behavior

As part of the documentation, there should be either the default credentials written out or a reference to where the credentials can be found.

### 👎 Actual Behavior with Screenshots

Nothing about credentials can be found anywhere.

### 💻 Operating system

MacOS

### 🤖 Node Version

18.11.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by qtarant** [comment]
Hello. Have you found any information about default credentials?
Thanks.

**Comment by ryshoooo** [comment]
> Hello. Have you found any information about default credentials? Thanks.

No, I believe I just signed up manually and that worked fine. My assumption now is that there are no default credentials, you need to create them by signing up.
