### ISSUE TITLE
[NV-1233] 🚀 Feature:  Ability to send emails to unsubscribed users

### ISSUE THREAD

**Issue by mohsinamjad** [novuhq/novu#2078]
### 🔖 Feature description

Here is an example for this use-case, 
we want to send the emails to some users which are not registered in our app i.e "Invite users to app" email.
at this point we only have their emails, we can send the emails by using their email as a subscriberId, but in that case we'll have alot on unregistered users in subsribers list and in database which we don't want.
It also dispatch inApp notification if the template has inApp step configured which is kindof extra data which we don't need because the user doesn't exist in the application.

as novu already handles mailing and it's provider configuration, it'd be really great to have this feature so that custom maling service can be replaced with novu.

### 🎤 Why is this feature needed ?

It will allow us to send emails to the unregistered users.

### ✌️ How do you aim to achieve this?

I've not seen the code in detail but I have few options not sure if those are the best.
* a separate API for guest emails, which will just dispatch the email.
* a flag in trigger API along with preference override so we can disable the rest of channels and only enable email. the flag will be used to identify that the subscriber is not registered so we don't need to store it in DB

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1233](https://linear.app/novu/issue/NV-1233/🚀-feature-ability-to-send-emails-to-unsubscribed-users)</sub>

**Comment by oba2311** [comment]
Thanks @mohsinamjad  for the idea!

Quick Q - what prevents you from using Novu today to achieve this flow? if you manage subscribers you can run the business logic and trigger a workflow when you see fit whether the user is registered or not on your app.

WDYT? or am I missing something?
