### ISSUE TITLE
[NV-1227] 🐛 Bug Report: generate:provider places wrong version of @novu/stateless

### ISSUE THREAD

**Issue by cryptic-ai** [novuhq/novu#2079]
### 📜 Description

When running `yarn run generate:provider` per docs located at [here](https://docs.novu.co/community/create-provider), it is putting the version of `@novu/statless` at `0.4.1` instead of `0.9.0`

### 👟 Reproduction steps

Run `yarn run generate:provider`

### 👍 Expected behavior

@novu/stateless should be 0.9.0

### 👎 Actual Behavior with Screenshots

It's 0.4.1

### 💻 Operating system

Windows

### 🤖 Node Version

16\.x

### 📃 Provide any additional context for the Bug.

*No response*

### 👀 Have you spent some time to check if this bug has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

> From [SyncLinear.com](https://synclinear.com)

**Comment by oba2311** [comment]
@p-fernandez should this be a community issue?

**Comment by p-fernandez** [comment]
@oba2311 yes, it is a good Community issue. Not sure if I added the proper tag in GitHub.

**Comment by oba2311** [comment]
Yes you did 😃

@iampearceman  FYI
