### ISSUE TITLE
[NV-1226] 🐛 Bug Report: 500 Error When Supplying Invalid ID on Subscriber Delete Endpoint

### ISSUE THREAD

**Issue by james-menzies** [novuhq/novu#2081]
### 📜 Description

When providing an invalid ID to the `/subscribers/id [DELETE]` endpoint, a 500 error is returned if the ID is invalid. Valid IDs appear to work as expected.

### 👟 Reproduction steps

1. Call `https://api.novu.co/v1/subscribers/{id}` where ID is not a subscriber in the system.
2. 500 is returned.

### 👍 Expected behavior

Return some other status code (404?, 400?) with an appropriate JSON body. Perhaps `SUBSCRIBER_ID_INVALID` as a message

### 👎 Actual Behavior with Screenshots

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/c7b70437-b611-41b9-8279-98cd29348958/42012034-2389-41ca-a286-7aca8c1802d8)

### 💻 Operating system

Linux

### 🤖 Node Version

Cloud

### 📃 Provide any additional context for the Bug.

*No response*

### 👀 Have you spent some time to check if this bug has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

*No response*

> From [SyncLinear.com](https://synclinear.com)

**Comment by p-fernandez** [comment]
Thanks for reporting. Fixed here: https://github.com/novuhq/novu/pull/2090
