### ISSUE TITLE
[NV-1232] Bug Report : Can't add CC email

### ISSUE THREAD

**Issue by Riyas839** [novuhq/novu#2082]
can't add CC email when triggering CURL API

<sub>[NV-1232](https://linear.app/novu/issue/NV-1232/bug-report-cant-add-cc-email)</sub>

**Comment by oba2311** [comment]
Did you mean for this to be community?

@scopsy

**Comment by scopsy** [comment]
@oba2311 it was submitted by @Riyas839, we can take a look at it closely if we will have the capacity for it. Otherwise perhaps someone can help us with it. So will add a help wanted tag for it.

**Comment by jainpawan21** [comment]
Similar issue:-  https://github.com/novuhq/novu/issues/2314

**Comment by scopsy** [comment]
@jainpawan21 closing this issue in favor of #2314  so we can track it there
