### ISSUE TITLE
🐛 Bug Report: Docker steps for setting up the novu is incorrect

### ISSUE THREAD

**Issue by riginoommen** [novuhq/novu#2091]
### 📜 Description

User onboarding got stucks when a user follows the following doc directly
https://docs.novu.co/overview/docker-deploy/#get-the-code

### 👟 Reproduction steps

Docker compose file is missing as per the above config

### 👍 Expected behavior

it should spin up the container

### 👎 Actual Behavior with Screenshots

N/A

### 💻 Operating system

MacOS

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Thank you for the contribution @riginoommen !
