### ISSUE TITLE
🐛/❓ Bug Report / Question: What do the different NODE_ENVs do?

### ISSUE THREAD

**Issue by whodges2** [novuhq/novu#2092]
### 📜 Description

novu has different NODE_ENV such as `local | dev | prod ...etc` but it's not documented anywhere what each environment does, what it changes and when you should use one over the other.

I'm willing to submit a pr to docs if someone can explain the different envs

### 👟 Reproduction steps

n/a

### 👍 Expected behavior

n/a

### 👎 Actual Behavior with Screenshots

n/a

### 💻 Operating system

Windows

### 🤖 Node Version

16.x

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Thanks @cryptic-ai! Outlining here the different environments:
- local: Used for local development of Novu, this environment runs by default when running the cloned project
- test: Used when running e2e and spec tests of the different novu components. They work against a real DB on your local machine. This environment also exposes a few testing API's for easier mocking
- dev: Is deployed as our staging/dev environment internally. Outside users might not need to use it
- prod: is the production environment we run our service in. If you are deploying Novu selfhosted, you should set your env to this one. 


Would be amazing on adding a section for this in the docs 🔥
