### ISSUE TITLE
[NV-1231] 🐛 Bug Report: Subscriber page mongo query

### ISSUE THREAD

**Issue by mohamed-cherifi** [novuhq/novu#2099]
### 📜 Description

I noticed something weird with the new subscriber page. The mongo-db query seems to be really taxing on the DB when the subscriber count is really high.

### 👟 Reproduction steps

- Go to the subscriber page

### 👍 Expected behavior

- Not query all entries all at once? Do it per page?

### 👎 Actual Behavior with Screenshots

Whenever the subscriber page loads the Mongo-db CPU spikes.

### 💻 Operating system

MacOS

### 🤖 Node Version

16.10.0

### 📃 Provide any additional context for the Bug.

[Relevant Discord thread](https://discord.com/channels/895029566685462578/1044358402828148736)

Here's the specific query: 
```{
  "type": "command",
  "ns": "novu.subscribers",
  "command": {
    "aggregate": "subscribers",
    "pipeline": [
      {
        "$match": {
          "_environmentId": {
            "$oid": "6321c40853b9b0393a2aad1a"
          },
          "_organizationId": {
            "$oid": "6321d40853b9b0393a2qrd37"
          },
          "deleted": {
            "$ne": true
          }
        }
      },
      {
        "$group": {
          "_id": 1,
          "n": {
            "$sum": 1
          }
        }
      }
    ],
    "cursor": {},
    "lsid": {
      "id": {
        "$binary": {
          "base64": "d/O/KdfFThyKUBvSirRXgg==",
          "subType": "04"
        }
      }
    },
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": {
          "t": 1668789992,
          "i": 3
        }
      },
      "signature": {
        "hash": {
          "$binary": {
            "base64": "VVGRGY32MViHcN3qx/qV6BzR35E=",
            "subType": "00"
          }
        },
        "keyId": 7130339138124906000
      }
    },
    "$db": "novu"
  },
  "planSummary": "IXSCAN { _environmentId: 1, subscriberId: 1 }",
  "keysExamined": 31128975,
  "docsExamined": 31128975,
  "cursorExhausted": true,
  "numYields": 49837,
  "nreturned": 1,
  "queryHash": "D53F1F27",
  "planCacheKey": "CA47FC65",
  "queryExecutionEngine": "classic",
  "reslen": 254,
  "locks": {
    "FeatureCompatibilityVersion": {
      "acquireCount": {
        "r": 49839
      }
    },
    "Global": {
      "acquireCount": {
        "r": 49839
      }
    },
    "Mutex": {
      "acquireCount": {
        "r": 2
      }
    }
  },
  "readConcern": {
    "level": "local",
    "provenance": "implicitDefault"
  },
  "writeConcern": {
    "w": "majority",
    "wtimeout": 0,
    "provenance": "implicitDefault"
  },
  "storage": {
    "data": {
      "bytesRead": 226315209471,
      "timeReadingMicros": 62534574
    },
    "timeWaitingMicros": {
      "cache": 54886
    }
  },
  "remote": "X.X.X.X:XXXX",
  "protocol": "op_msg",
  "durationMillis": 976902,
  "v": "6.0.2"
}
```

Here's the effect it has on the mongo-db:
![image](https://user-images.githubusercontent.com/97466700/204057266-306c9e89-ef07-4411-8a39-49814d324897.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1231](https://linear.app/novu/issue/NV-1231/🐛-bug-report-subscriber-page-mongo-query)</sub>

**Comment by oba2311** [comment]
@scopsy how soon do we need this handled performance wise?

**Comment by p-fernandez** [comment]
@mohamed-cherifi have you tried our latest versions (v.014 onwards)? If so could you give us a bit of feedback?
We managed to fix some performance problems we had that were related to what you reported.
