### ISSUE TITLE
[NV-1254] Test workflow before workflow exist

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2108]
The button should be disabled before the WF is created, otherwise - please explain the rationale 😃

![CleanShot 2022-11-27 at 20.30.02@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/7205cac9-9e32-4944-9a28-52a0f13418f1/ec3e95b5-7482-4c32-bf77-29e7d1d3aa99)

As long as steps are not added, it should be disabled:

![CleanShot 2022-11-27 at 20.36.20@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/f77c46a7-da13-4ec7-a7c1-c08f10913537/e8f6143f-b039-4076-aa98-316c57ffa1e3)

Since as of now the user would run into "Internal Server Error"

![CleanShot 2022-11-27 at 20.34.08@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/df5d35d5-7b1e-4ba1-9a3a-492b871890e0/4a4dae83-ef22-4330-b952-99ab9779ef5d)

---

Created via [Raycast](https://www.raycast.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1254](https://linear.app/novu/issue/NV-1254/test-workflow-before-workflow-exist)</sub>

**Comment by Sko0by** [comment]
I would love to help with this
