### ISSUE TITLE
[NV-1258] Add space between pills

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2110]
Just to make those look a lil nicer in case several addresses are used.

![CleanShot 2022-11-30 at 12.46.04@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/c77e8fd7-53e9-4130-b2a2-5eedeeff6b0d/6a255fc5-8902-4d34-84d8-07cae9593c15)

---

Created via [Raycast](https://www.raycast.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1258](https://linear.app/novu/issue/NV-1258/add-space-between-pills)</sub>

**Comment by davidsoderberg** [comment]
@oba2311 image is missing I guess?

**Comment by oba2311** [comment]
\:/ 

Linear sometimes does not save the images - I'll try to redo and paste again

thanks

**Comment by Aadarsh805** [comment]
> Just to make those look a lil nicer in case several addresses are used.
> 
> ![CleanShot 2022-11-30 at 12.46.04@2x.png](https://camo.githubusercontent.com/e54df68b6a0c031979626d838748b661b0fd811478fb28fde35f79de41192b9d/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f66313366313939362d633962302d346665612d386565372d3263336661663661383332642f63373765386664372d353365392d343133302d623261322d3565656465656666366230642f36613235356663352d383930322d346433342d383464382d303763616539353933633135)
> 
> Created via [Raycast](https://www.raycast.com)
> 
> From [SyncLinear.com](https://synclinear.com) | [NV-1258](https://linear.app/novu/issue/NV-1258/add-space-between-pills)

where is this happening exactly, how can i try to regenerate in on mine
