### ISSUE TITLE
[NV-1265] 🐛 Bug Report: Email attachments are showing invalid

### ISSUE THREAD

**Issue by chavda-bhavik** [novuhq/novu#2112]
### 📜 Description

When sending emails with attachments, attachments are received as invalid in emails.

### 👟 Reproduction steps

1. Create a Notification
2. Trigger the notification with some `attachment`, I send attachment as,
```
{
  file: fs.readFileSync(path.join(__dirname, "img/facebook.png")),
  name: "facebook.png",
  mime: "image/png",
}
```
3. See the email received, the attachment will be `unprocessable (invalid)` to the system.

### 👍 Expected behavior

Attachments should be sent properly via email.

### 👎 Actual Behavior with Screenshots

How the attachment image looks in Ubuntu.
![Screenshot from 2022-11-28 11-46-55](https://user-images.githubusercontent.com/50201755/204207155-8cf585e8-3151-488c-afef-66f430ec3d89.png)

### 💻 Operating system

Linux

### 🤖 Node Version

16.15.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1265](https://linear.app/novu/issue/NV-1265/🐛-bug-report-email-attachments-are-showing-invalid)</sub>

**Comment by chavda-bhavik** [comment]
@scopsy @p-fernandez Any thoughts on this issue?

**Comment by chavda-bhavik** [comment]
@scopsy issue is occurring in text and pdf documents as well.

**Comment by Wyfy0107** [comment]
I can try to have a look

**Comment by oba2311** [comment]
Thanks @Wyfy0107 !
