### ISSUE TITLE
[NV-1266] Notification-Center bell seen/read toggle

### ISSUE THREAD

**Issue by djabarovgeorge** [novuhq/novu#2123]
At the current state notification-center bell counter uses the seen count in order to present the `bell dot` and counter on the notification center header.

![image.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/be484606-eb1e-4e3c-b333-da0e3a8e7d26/ec6e2f16-4891-4da2-ae64-7af3dde79048)

![image.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/ad64596d-71a3-415f-adfe-3b6d3017d1c9/9ff62de3-98b5-470f-a715-33e41f2393ae)

What we want is the ability for the user of the notification-center to toggle this functionality to `read`.

Once the user toggled the functionality to read the desired result should be as the following:

![image.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/9cad1d9c-3e82-4594-819e-491ab5f39428/71e1a761-4b24-4d40-ad01-0fb1935a0091)

Note: IMO in order to achieve that we need to create hook useUnreadCount same as the useUnseenCount that will store the readCount under context using the socket connection (the API part is already implemented therefore when a new notification fires the socket should get the update - the only thing that remains is to listen to unread_count_changed event), or create a general hook that will store them both.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1266](https://linear.app/novu/issue/NV-1266/notification-center-bell-seenread-toggle)</sub>

**Comment by oba2311** [comment]
I'd suggest to decide what's the default first - I believe this is config is overengineered as an option to users at this point

it is very low down the usage funnel and adds clutter to the overall system - we should understand which option makes more sense and implement it as default.

WDYT @djabarovgeorge
