### ISSUE TITLE
🚀 Feature: SAML Integration for the Login for the Novu

### ISSUE THREAD

**Issue by riginoommen** [novuhq/novu#2129]
### 🔖 Feature description

Integration of the SAML Login for the novu which enables the enterprises to adopt with the customization

### 🎤 Why is this feature needed ?

Adoption will be faster with in enterprise ecosystem like a tool like backstage.io

### ✌️ How do you aim to achieve this?

I am willing to adopt it in my work with SAML login

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
Thank you, @riginoommen for the suggestion, will be adding this to our roadmap to track it here: https://github.com/novuhq/roadmap/issues/13

Closing this issue here and will add more information there later 🙏

**Comment by riginoommen** [comment]
Thank you @scopsy
