### ISSUE TITLE
[NV-1654] 🐛 Bug Report: Styling issue with the React Notification Center Settings

### ISSUE THREAD

**Issue by psteinroe** [novuhq/novu#2139]
### 📜 Description

Hey!

The styling of the React Notification Center Settings screen is off. There are customisation options for the component, but our expectation was that there is a basic styling applied by default. Hence this issue to find out if this is expected behaviour, missing config, or a bug.

### 👟 Reproduction steps

Add the Notification Center component into a react app. We are using nextjs with tailwind.

### 👍 Expected behavior

Have a decent default styling.

### 👎 Actual Behavior with Screenshots

Especially the toggles are broken.
<img width="441" alt="image-2" src="https://user-images.githubusercontent.com/19429600/205004132-75e03c0f-0e27-4c8d-8eb4-a265f869f0fe.png">

### 💻 Operating system

Something else

### 🤖 Node Version

18

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1654](https://linear.app/novu/issue/NV-1654/🐛-bug-report-styling-issue-with-the-react-notification-center)</sub>

**Comment by jainpawan21** [comment]
Hi @psteinroe 
This is strange behaviour. 
Did you try to use notification center in non tailwind project? 
@LetItRock wdyt, can tailwind create issue in styling?

**Comment by dwome** [comment]
Hello @jainpawan21,
FYI We did not yet try in a non-tailwind project :-)

**Comment by scopsy** [comment]
Another small question @psteinroe are you using the react component provided? Seems like you have some global styles that override the notification center specific styles. Could you try inspecting the component node with "Chrome Inspect"? To see what overrides the default styles?

**Comment by psteinroe** [comment]
@scopsy it seems like the Tailwind base layer styles conflict with mantine styling... we "fixed" it for now by adding the following css. 

```
.mantine-yuke8a {
   @apply min-w-0 !important;
 }
```

The font is still not working in the subscriber preferences, but at least the checkbox is usable.

<img width="436" alt="image (1)" src="https://user-images.githubusercontent.com/19429600/207567383-d22cff86-3277-4771-9f8d-c4b656ecabb0.png">

**Comment by mosamlife** [comment]
Any update on this I have the same issue with mantine.

**Comment by scopsy** [comment]
@mosamlife unfortunately not yet :( We need to somehow namespace all mantine classes there. The long term approach for us is to actually move away from mantine to a custom implementation but it will take some time

**Comment by scopsy** [comment]
Replaced with the new Inbox component with improved styling 🙏
