### ISSUE TITLE
[NV-1285] (JS-0414) Missing key for the property

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2144]
## Description
A `key` is a special string attribute you need to include when creating lists of elements because keys help `React` identify which items have changed, added, or removed. Keys should be given to the elements to give them a stable identity.

## Occurrences
There are 15 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0414/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0414/occurrences/)

<sub>[NV-1285](https://linear.app/novu/issue/NV-1285/js-0414-missing-key-for-the-property)</sub>

**Comment by Lonecloud7** [comment]
Hey, first-time contributor here. going to get this done

**Comment by ttlgeek** [comment]
Submitted a pull request that fixes this issue :)

**Comment by scopsy** [comment]
Hi @ttlgeek please next time asked to be assigned for an issue since someone was already assigned to it.

@Lonecloud7 did you already started to work on this or should I merge the already open PR?

**Comment by Lonecloud7** [comment]
Unfortunately no, I couldn't get the app to run locally to test dependencies to solve the issue.
You can assign the task to someone else because it is above what I am capable of.

**Comment by jainpawan21** [comment]
> 

Hi @Lonecloud7,
Thanks for showing interest in contribution to Novu.
If you face any issue in local step please follow [this](https://docs.novu.co/community/run-locally) doc guide.
