### ISSUE TITLE
[NV-1287] Change the empty state copy for the URL for button

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2147]
Woud be better to write *"www.yoururl..."* instead of "Button Link" - examples always make it more clear.

![CleanShot 2022-12-01 at 13.38.52@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/32c5b9bd-5267-4e4a-99a3-3356246ec829/05871dd3-8ee9-495e-8935-b7bdc88b11ac)

---

Created via [Raycast](https://www.raycast.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1287](https://linear.app/novu/issue/NV-1287/change-the-empty-state-copy-for-the-url-for-button)</sub>

**Comment by Cxxshyy** [comment]
hi i'd like to take this issue but could you point me to the file that needs to be changed

**Comment by scopsy** [comment]
@Cxxshyy usually how I approach. this is by searching the project globally for a particular phrase, for example: "Button Link"
<img width="1400" alt="CleanShot 2022-12-11 at 18 55 30@2x" src="https://user-images.githubusercontent.com/8872447/206902124-4001456a-ab59-4590-9cf9-ebdc7182d1f0.png">

Which pointed me to this file: `apps/web/src/components/templates/email-editor/ButtonRowContent.tsx` :)

**Comment by Cxxshyy** [comment]
@scopsy ok thanks 😊

**Comment by Cxxshyy** [comment]
how do i get to- the search part ctrl f?

**Comment by Cxxshyy** [comment]
raised a pr for this issue
