### ISSUE TITLE
🚀 Feature: Azure Active Directory Authentication

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu#2153]
### 🔖 Feature description

Currently, there are two ways to login. You have the GitHub OAuth 2 provider, and then you have your standard username password configuration. 

I would like to propose an additional login method utilizing Azure Active Directory.

### 🎤 Why is this feature needed ?

Allowing users to authenticate with Azure Active Directory could aid in the adoption of Novu with Microsoft heavy companies.

### ✌️ How do you aim to achieve this?

There will need to be the addition of the following env vars
(note: AAD is the standard abbreviation for Azure Active Directory)
```
AAD_CLIENT_ID
AAD_CLIENT_SECRET
````
**Route: `/v1/auth/aad`**
Would check to see if the env vars are set. Like it does here for [GitHub](https://github.com/novuhq/novu/blob/f4d630b6de7df2772ed6a7fec8dd4be94ec6b450/apps/api/src/app/auth/auth.controller.ts#L61)

**Route: `/v1/auth/aad/callback`**
Exchange the code for a token, reach out to the Microsoft Graph and get the user details and store it in the database layer.

### 🔄️ Additional Information

https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/auth-oauth2

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Cliftonz** [comment]
This has been brought up, however, there needs to be further discussion internally before we move forward. 
I would defer to @scopsy on this.

@cryptic-ai  what is your use case for wanting this? Compliance, Security, Standard Integration, Easy of use, etc.

**Comment by Cliftonz** [comment]
Thank you!

**Comment by scopsy** [comment]
Hi @wh1337 unfortunately not at the moment, will update here once we have some news regarding that 🙏

**Comment by scopsy** [comment]
We have launched an azure auth flow on our cloud services via the SSO connector
