### ISSUE TITLE
[NV-1295] (JS-0126) Variables should not be initialized to `undefined`

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2166]
## Description
In JavaScript, a variable that is declared and not initialized to any value automatically gets the value of undefined. For example:

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0126/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0126/occurrences/)

<sub>[NV-1295](https://linear.app/novu/issue/NV-1295/js-0126-variables-should-not-be-initialized-to-undefined)</sub>

**Comment by saroj990** [comment]
@scopsy I would like to take up this issue.

**Comment by saroj990** [comment]
@scopsy so we just need to remove undefined from the 3 places where we are explicitly initialising it with `undefined`, is that the scope of this modification that we want ?

**Comment by scopsy** [comment]
Yes @saroj990 exactly 🙏

**Comment by saroj990** [comment]
@scopsy previously the deepsource link was showing 3 occurrences for `undefined` but now it does not show anything. Is there a way I can refer the places using deepsource or I have to find all the occurrences of explicit assignment of `undefined` and work on it ?

**Comment by scopsy** [comment]
@saroj990 seems like it was already resolved in another PR by someone else :( So looks like we can close this one
