### ISSUE TITLE
[NV-1302] 🚀 Feature: Upgrade to socket.io-client v4

### ISSUE THREAD

**Issue by vinhnguyen1211** [novuhq/novu#2175]
### 🔖 Feature description

Upgrade the socket.io nestjs server side & web client side to v4

### 🎤 Why is this feature needed ?

I have another socket server use v4 and it's great if I can use same library version to connect to Novu socket

### ✌️ How do you aim to achieve this?

I want this feature so I can use 1 `socket.io-client` package in Novu socket in client side without 2 individual client
```
    "socket.io-client": "^4.4.0",
    "socket.io-client-v2": "npm:socket.io-client@^2.3.1",
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1302](https://linear.app/novu/issue/NV-1302/🚀-feature-upgrade-to-socketio-client-v4)</sub>

**Comment by p-fernandez** [comment]
@vinhnguyen1211 assigned to you if you want to submit the PR. Let us know if you can't work on it to manage the issue.

**Comment by vinhnguyen1211** [comment]
hello @p-fernandez , I've submitted the PR https://github.com/novuhq/novu/pull/2223. Please review

**Comment by vinhnguyen1211** [comment]
https://github.com/novuhq/novu/pull/2223 is merged

**Comment by jainpawan21** [comment]
Thanks @vinhnguyen1211 for your contribution 🔥.
