### ISSUE TITLE
[NV-949] Add subject variables to Variables Manager

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2182]
As part of [v0.8.0](https://github.com/novuhq/novu/releases/tag/v0.8.0) release, template variable protection and default value assignation were introduced. 

This means - that every variable added to the content of a message template (e.g. {{name}}) would be recognized as a variable and immediately added to the bottom of the page with the option of giving it a default value or marking it as required. 

But this support is still missing for **variables added in the subject of an email message.** 

![Screen Shot 2022-09-29 at 13.13.05.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/986c5d7b-82c8-4c6a-bff7-3b70d46dadb7/683cf31e-ea50-44ee-9529-e8a3c3df27be)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-949](https://linear.app/novu/issue/NV-949/add-subject-variables-to-variables-manager)</sub>

**Comment by ainouzgali** [comment]
yes

**Comment by ainouzgali** [comment]
@ainouzgali  from what I understand, this is a good community issue as the mechanism already exist and so it is just to implement the same mechanism for the title.

**Comment by ainouzgali** [comment]
@oba2311 wdyt?

**Comment by ainouzgali** [comment]
Community? if so, more details needed. @ainouzgali

**Comment by NwaforAugustine321** [comment]
@oba2311 @scopsy @ainouzgali  I want to work on this issue if it is not yet done or assigned to someone.

**Comment by ainouzgali** [comment]
I'm sorry @NwaforAugustine321 . This was already implemented. Missed updating it here🤦🏻‍♀️ 
Sorry about the confusion and thank you🤩

**Comment by NwaforAugustine321** [comment]
> I'm sorry @NwaforAugustine321 . This was already implemented. Missed updating it here🤦🏻‍♀️ Sorry about the confusion and thank you🤩

Ok, @ainouzgali I'm available for any feature contribution and bug fixing.
