### ISSUE TITLE
[NV-946] Scheduled Delay step - add to trigger snippet

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2183]
With scheduled delay, a novu user can declare a path in payload of where the delayed date would be in the payload when the workflow triggers. 

I think it would be nice to add that path to the trigger snippet we show in the web UI especially as we show all other variables used in the templates. It will also help reduce misunderstandings and the need to debug. 

So, if this is defined on the web:

![Screen Shot 2022-09-28 at 9.32.10.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/a593754b-b616-4f54-b41d-6ecffb49b8a6/dcdd7c3d-4476-4337-8d6f-dc629d1f7d34)

This will be the updated trigger snippet:

![Screen Shot 2022-09-28 at 9.33.29.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/3e7846e1-dd35-45bb-bbf5-13dbccad8a60/45328f51-70ba-4f4d-9110-a32b6b9fb8db)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-946](https://linear.app/novu/issue/NV-946/scheduled-delay-step-add-to-trigger-snippet)</sub>

**Comment by gitstart-novu** [comment]
Hi @ainouzgali, we are having issues reproducing this issue. Please find the details in this [loom video](https://www.loom.com/share/9b4253e56dfb4ab0b5bfac006d1e55c5) and tell us if we are missing anything. Cc @scopsy
