### ISSUE TITLE
[NV-952] Integration Missing - a more clear navigation

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2184]
The missing integration alert in a message editor is only clickable on the arrow, which doesn't even show a pointer. 

I suggest making the whole alert clickable, and any click on it navigates to the integration page (of course, with the warning of unsaved changes, which already happens) 

![Screen Shot 2022-09-29 at 16.09.49.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/4fc32131-b2d8-4853-9bb2-17ff05ef41af/e9f18621-812b-4392-91b2-5691d526b19e)

  

Make sure it has a pointer indicating its clickable.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-952](https://linear.app/novu/issue/NV-952/integration-missing-a-more-clear-navigation)</sub>

**Comment by ainouzgali** [comment]
Great ticket!

**Comment by ainouzgali** [comment]
@oba2311  I know there was an issue about it before, I just think this might be more clear. What do you think?

**Comment by p-fernandez** [comment]
Since opening this issue the workflow editor design has been revamped.
<img width="1449" alt="Screenshot 2023-06-15 at 14 24 55" src="https://github.com/novuhq/novu/assets/18152036/87953965-961c-4658-b8a0-421d25f16249">

Closing as it doesn't apply anymore.
