### ISSUE TITLE
[NV-383] Vue component wrapper for the notification-center embed script

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2189]
## Why?

Currently, we allow to embed the notification center using 2 ways:

* A react component using @novu/notification-center [https://docs.novu.co/docs/notification-center/react-components](https://docs.novu.co/docs/notification-center/react-components)
* An **embed** script [https://docs.novu.co/docs/notification-center/iframe-embed](https://docs.novu.co/docs/notification-center/iframe-embed)

We want to create a **3rd** way using a wrapper of an vue component around the embed script. To automatically inject it and pass the relevant option to the `novu.init` command.

### API for the vue component

We need a way to pass the following information:

* applicationIdentifier
* subscriberId
* optional subscriber object (see react component API)

Questions

* How can we pass a reference to the Bell button to be triggered (Currently the embed requires: unseenBadgeSelector, and bellSelector both are CSS selector.) We want to be able to pass a ref instead of a CSS selector.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-383](https://linear.app/novu/issue/NV-383/vue-component-wrapper-for-the-notification-center-embed-script)</sub>

**Comment by chrisweirich** [comment]
Hi.

I've seen that PR nv-1316-gh-actions-for-nc-vue-angular-packages has been merged to 'next'. Will this be the integration for vue and to you already know, when 'next' will be released?

Regards
Chris

**Comment by scopsy** [comment]
Hi @chrisweirich hope that in the next 2-weeks🙏 Will update as soon as it's available

**Comment by scopsy** [comment]
🎉

**Comment by jainpawan21** [comment]
Hi @chrisweirich 
This feature is available in our recent release 0.10.0
