### ISSUE TITLE
[NV-1309] [NV-182] Add Bandwidth sms provider

### ISSUE THREAD

**Issue by iampearceman** [novuhq/novu#2191]
### **What?**

New [Bandwidth](https://github.com/Bandwidth/node-messaging) SMS Provider.

### **Why?**

To have the ability to use [Bandwidth](https://github.com/Bandwidth/node-messaging) as a provider.

### **How?**

Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### **Usage**

Example for Bandwidth SMS provider registration needs to be finalized.

```
await notifire.registerProvider(
  new Bandwidth SmsProvider({
    username: process.env. BANDWIDTH_USERNAME,
    password: process.env.BANDWIDTH_PASSWORD,
    apiKey: process.env.BANDWIDTH_API_KEY
  })
);
```

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-182](https://linear.app/novu/issue/NV-182/add-bandwidth-sms-provider)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-182](https://linear.app/novu/issue/NV-182/add-bandwidth-sms-provider)</sub>

**Comment by iampearceman** [comment]
@iampearceman could you try about what service he speaks about and create a free account there. Let me know if you are able to do it

**Comment by iampearceman** [comment]
Last update from this issue: 

### [**kishorliv **](https://github.com/kishorliv)commented [on Jan 9](https://github.com/notifirehq/notifire/issues/76#issuecomment-1008230491)

| @ComBarnea I worked on it but to get the api keys, they need organization email and phone numbers for the trial. So, I am kinda stuck here... |

@scopsy What do we do here?

**Comment by iampearceman** [comment]
[https://github.com/kishorliv](https://github.com/kishorliv) is on this issue.

**Comment by scopsy** [comment]
Duplicate issue
