### ISSUE TITLE
[NV-184] Add support for TransitSMS

### ISSUE THREAD

**Issue by iampearceman** [novuhq/novu#2192]
* **I'm submitting a feature request**
* **Summary**\
  TransitSMS is a popular SMS provider in Australia and New Zealand.\
  Documentation: [https://developer.transmitsms.com/](https://developer.transmitsms.com/)
* **Other information**\
  I'll probably look into developing this integration myself.\
  What is the best way to contribute?

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-184](https://linear.app/novu/issue/NV-184/add-support-for-transitsms)</sub>

**Comment by iampearceman** [comment]
[https://github.com/lyndonbuckley](https://github.com/lyndonbuckley) is on this issue.

**Comment by scopsy** [comment]
Duplicate entry
