### ISSUE TITLE
[NV-899] Hide pagination if page < 2

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2194]
In Subscribers and Notifications, the pagination is shown when there is one page. 

![Screen Shot 2022-09-20 at 17.13.35.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/f3778309-2de4-45a3-ad4f-0332e842b39b/73eae263-fe19-43c9-9a80-a7252b098c12)

![Screen Shot 2022-09-20 at 17.13.26.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/bd305ccf-7fa7-4939-9b03-29fdb8fdbc55/036de0d5-7bc0-4d6c-a732-5d32fa345e25)

We should either: 

* Hide when there is one page (My preference)
* Make sure it is at the bottom of the page, and not after the last record. 

We should do it for the Table component and not for each page.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-899](https://linear.app/novu/issue/NV-899/hide-pagination-if-page-2)</sub>

**Comment by Kaodily** [comment]
I can get this done

**Comment by BhuvaneshPatil** [comment]
I want to work on this issue if possible @ainouzgali @scopsy .

**Comment by BhuvaneshPatil** [comment]
Hey @ainouzgali,

![image](https://user-images.githubusercontent.com/27822551/207521333-8e813521-247b-4169-8895-87ac8dbd5caa.png)

In my pc it's showing infinite scrolling for notifications.
Am I doing something wrong here?

**Comment by ainouzgali** [comment]
Thanks @BhuvaneshPatil !
