### ISSUE TITLE
[NV-180] Add new SparkPost provider

### ISSUE THREAD

**Issue by iampearceman** [novuhq/novu#2196]
### **What?**

New [SparkPost](https://github.com/SparkPost/node-sparkpost) Email Provider

### **Why?**

To have the ability to use [SparkPost](https://github.com/SparkPost/node-sparkpost) as a provider.

### **How?**

Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### **Usage**

Example for SparkPost provider registration needs to be finalized.

```
await notifire.registerProvider(
  new SparkPostProvider({
    apiKey: process.env.SPARKPOST_API_KEY
  })
);
```

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-180](https://linear.app/novu/issue/NV-180/add-new-sparkpost-provider)</sub>

**Comment by scopsy** [comment]
Duplicate with #80
