### ISSUE TITLE
[NV-896] Upgrade Mantine version in Web

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2197]
## What

Novu was built with 4.1 version of Mantine. Mantine has kept progressing and now the official version is 5.4

## Why

In order to be able to use the latest and greatest Mantine's features we need to upgrade our codebase to the latest version.  This ticket requires the work needed to make the Web GUI work smoothly with the latest Mantine version.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-896](https://linear.app/novu/issue/NV-896/upgrade-mantine-version-in-web)</sub>

**Comment by ainouzgali** [comment]
@ainouzgali great for hacktoberfest. Adding a label to it.!

**Comment by scopsy** [comment]
Duplicate
