### ISSUE TITLE
[NV-1308] [NV-178] Add new provider Matrix (matrix.org)

### ISSUE THREAD

**Issue by iampearceman** [novuhq/novu#2201]
| Is your feature request related to a problem? Please [describe.No](http://describe.No) support for Matrix notificationsDescribe the solution you'd likeSupport for itAdditional contexthttps://matrix.org |

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-178](https://linear.app/novu/issue/NV-178/add-new-provider-matrix-matrixorg)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-178](https://linear.app/novu/issue/NV-178/add-new-provider-matrix-matrixorg)</sub>

**Comment by iampearceman** [comment]
Sent a message on GitHub issue.

**Comment by jainpawan21** [comment]
Duplicate of https://github.com/novuhq/novu/issues/128
