### ISSUE TITLE
[NV-579] [Theme] Customize empty state

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2207]
* In react component.
* In iframe embed.

add to docs

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-579](https://linear.app/novu/issue/NV-579/[theme]-customize-empty-state)</sub>

**Comment by ainouzgali** [comment]
@oba2311 A great community candidate indeed. But needs much better PRD and description.

**Comment by ainouzgali** [comment]
Community? At least for the react component. @scopsy @oba2311

**Comment by scopsy** [comment]
Duplicate
