### ISSUE TITLE
🐛 Bug Report: Unable to start the dev environment

### ISSUE THREAD

**Issue by simo97** [novuhq/novu#2211]
### 📜 Description

It bug when i follow the process to start the development in local.

### 👟 Reproduction steps

Build the development docker images with the command

`docker-compose -f ./development/docker-compose.development.yml up`

### 👍 Expected behavior

It should start the app

### 👎 Actual Behavior with Screenshots

It faill with an pnmp error.
<img width="916" alt="Screen Shot 2022-12-06 at 15 46 52" src="https://user-images.githubusercontent.com/14660547/205943369-c8fe73a8-a785-4878-8a4c-834fbdbf3e4a.png">

### 💻 Operating system

MacOS

### 🤖 Node Version

nikolaik/python-nodejs:python3.10-nodejs16-alpine

### 📃 Provide any additional context for the Bug.

I was not able to run the command until  i commented out the lines:

```
COPY ./meta .
COPY ./deps .
COPY ./pkg .
```
from the `api/Dockerfile`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
@simo97 I would suggest following the guide here: https://docs.novu.co/community/run-locally regarding running novu locally instead of using the development docker compose (it is used mainly internally right now for specific usecases)

**Comment by natnael-meresa** [comment]
I have also encountered the same issue, but in my case, it is a little different I have added a few providers and I am trying to deploy it by dockerizing it, is there any other way to dockerizing the services?
