### ISSUE TITLE
🚀 Feature: Inherit `fontFamily` when using `PopoverNotificationCenter`

### ISSUE THREAD

**Issue by ryantbrown** [novuhq/novu#2217]
### 🔖 Feature description

Remove any references to `fontFamily` from `PopoverNotificationCenter` and its `children`, allowing the component to inherit from existing styles.

### 🎤 Why is this feature needed ?

When adding `PopoverNotificationCenter` to an application, it's highly likely that inheriting the font from the global styles is desirable. Furthermore, it's currently too difficult to customize the `fontFamily`, leading to situations where the UI displays mixed fonts.

### ✌️ How do you aim to achieve this?

@scopsy mentioned that the current implementation is "mostly for the widget component implementation that lived in the iframe" and that it should be possible to move the reference "inside the iframe embed config".

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
Hi @ryantbrown,
Thanks for creating this issue
Shall I assign issue this to you?

**Comment by Cxxshyy** [comment]
i can take this issue also can you explain again please how i find the file that need to be modified when taking on an issue

**Comment by opti21** [comment]
This would be very helpful, here's an example of what's happening. The project is using nextjs tailwind, and daisyui.

![CleanShot 2023-01-03 at 14 43 39](https://user-images.githubusercontent.com/40129778/210438582-55716667-c9b8-42ba-8e93-9eac51311508.gif)

**Comment by mmmoli** [comment]
I see this too!

**Comment by scopsy** [comment]
@LetItRock not sure if I recall correctly but we had some discussion about this previously. Did you touched this area in the latest change? If not, I can issue a quick PR for this.

**Comment by mmmoli** [comment]
Any updates on this?

Novu is stubbed out of our app while this Issue is open.

**Comment by jainpawan21** [comment]
> 

@LetItRock ping

**Comment by jainpawan21** [comment]
> @LetItRock not sure if I recall correctly but we had some discussion about this previously. Did you touched this area in the latest change? If not, I can issue a quick PR for this.

@LetItRock ping!

**Comment by LetItRock** [comment]
> > @LetItRock not sure if I recall correctly but we had some discussion about this previously. Did you touched this area in the latest change? If not, I can issue a quick PR for this.
> 
> @LetItRock ping!

@jainpawan21 I remember that someone from the core team worked on this some time ago, I will ask and will get back...

**Comment by IAmRiteshKoushik** [comment]
Is this issue still looking for resolution or has it been resolved already ?

**Comment by jainpawan21** [comment]
@IAmRiteshKoushik this is fixed
