### ISSUE TITLE
[NV-1321] (JS-0422) Avoid `target='_blank'` attribute without `rel='noopener noreferrer'`

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2231]
## Description
When creating a JSX element with a tag, it is often desired to have the link open in a new tab using the `target=&#x27;_blank&#x27;` attribute. Using this attribute unaccompanied by `rel=&#x27;noreferrer&#x27;`, however, is a severe security vulnerability.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0422/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0422/occurrences/)

<sub>[NV-1321](https://linear.app/novu/issue/NV-1321/js-0422-avoid-target=-blank-attribute-without-rel=noopener-noreferrer)</sub>

**Comment by scopsy** [comment]
Low risk, but quite an easy fix

**Comment by Cxxshyy** [comment]
seems straight forward but can you point me to the file that handles this

**Comment by jainpawan21** [comment]
Hi @Cxxshyy 
This is the line you need to update
https://github.com/novuhq/novu/blob/next/apps/web/src/pages/quick-start/components/OnboardingSteps.tsx#L138-L138

**Comment by scopsy** [comment]
@Cxxshyy could you make sure you have run `npm run setup:project` from the root? You could also run `git commit -m "content" --no-verify` as a last resort:)

**Comment by Cxxshyy** [comment]
@scopsy thanks raised a pr to tackle this issue #2273
