### ISSUE TITLE
🚀 Feature: Add version proeprty to bug report template

### ISSUE THREAD

**Issue by pascal-mueller** [novuhq/novu#2232]
### 🔖 Feature description

Add a `novu version` property to the Github-Issue bug template. It would be beneficial, if it also explains how to get the `novu version` of the codebase being used.

### 🎤 Why is this feature needed ?

It's an important piece of information when trying to reproduce a bug or if someone looks for a solution.

### ✌️ How do you aim to achieve this?

I don't, you do. :D I'm too new to Novu to make a PR for anything yet.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
@scopsy I think novu version is relevant when user is using self hosted or local environment. For our managed web.novu.co, it will always be latest version?

**Comment by scopsy** [comment]
Yes @jainpawan21 cloud runs on latest :)
