### ISSUE TITLE
🐛 Bug Report: markAs endpoint in 0.9

### ISSUE THREAD

**Issue by niblasobr** [novuhq/novu#2234]
### 📜 Description

Dear all

I think in the API reference documentation there's a bug in [Mark a subscriber feed message as seen](https://docs.novu.co/api/mark-a-subscriber-feed-message-as-seen/):

The noted path is:

`/v1/subscribers/:subscriberId/messages/markAs`

I think there's missing the `messageId`?

Shouldn't it be `/v1/subscribers/:subscriberId/messages/:messageId/markAs`?

### 👟 Reproduction steps

Bug in the documentation. See above. 

### 👍 Expected behavior

Should have a `:messageId` in the path?

### 👎 Actual Behavior with Screenshots

Missing property

### 💻 Operating system

Something else

### 🤖 Node Version

- 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
Hi @niblasobr seems like there is a bug in the swagger, but it accepts the body of:
```
{ messageId: string | string[]; mark: { seen?: boolean; read?: boolean } }
```

So. the message id goes in the body and not on the param, will take a look at the swagger doc to make sure it's accurate

**Comment by jonaszeier** [comment]
https://docs.novu.co/api/update-subscriber-credentials/ seems to be wrong, too. The Object 0 in credentials shouldn't be there. Instead webhookUrl and deviceTokens should be fields of credentials. I think the Swagger doc is correct.
