### ISSUE TITLE
cannot access to discord channel

### ISSUE THREAD

**Issue by amosbah** [novuhq/novu#2241]
Hello,

I used the discord channel invite link but it reports that it is expired or invalid. Please fix the link or provide a new access link.

Thanks

**Comment by jainpawan21** [comment]
Hi @amosbah 
Please use https://discord.gg/novu link 
What link you used btw?

**Comment by p-fernandez** [comment]
Closing as not replying.
@amosbah if you happen to find again the outdated link, please provide us with the location so we can fix it.
