### ISSUE TITLE
[NV-1329] (JS-0765) Prefer that non-interactive, visible elements (such as <div>) that have click handlers use the role attribute

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2243]
## Description
Static HTML elements do not have semantic meaning. This is clear in the case of `&lt;div&gt;` and `&lt;span&gt;`. It is less so clear in the case of elements that _seem_ semantic, but that do not have a semantic mapping in the accessibility layer. For example `&lt;a&gt;`, `&lt;big&gt;`, `&lt;blockquote&gt;`, `&lt;footer&gt;`, `&lt;picture&gt;`, …

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0765/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0765/occurrences/)

<sub>[NV-1329](https://linear.app/novu/issue/NV-1329/js-0765-prefer-that-non-interactive-visible-elements-such-as-div-that)</sub>

**Comment by BhuvaneshPatil** [comment]
Anyone having difficulty reading this - 
&lt;div&gt; -> <div/>

**Comment by scopsy** [comment]
Thank you @BhuvaneshPatil!
