### ISSUE TITLE
[NV-1367] (JS-0050) Avoid use of `==` and `!=`

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2287]
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`.

## Occurrences
There are 14 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0050/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0050/occurrences/)

<sub>[NV-1367](https://linear.app/novu/issue/NV-1367/js-0050-avoid-use-of-==-and-=)</sub>

**Comment by ShashwatAgrawal20** [comment]
Hey, I am willing to have my first open source contribution it would be my pleasure if you assign me to this issue & let me fix it.

**Comment by ShashwatAgrawal20** [comment]
Hey, I have done some changes can you review them and let me know if some more changes are required
