### ISSUE TITLE
[NV-1368] (JS-0378) Found template literal expression having a non-string type

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2288]
## Description
Using only string values in placeholders is recommended as otherwise, the value may be wrongly displayed; for example, if an object value is directly included in a string, it will be shown as `[object Object]`. Using only string values can also ensure that `null` or `undefined` values are not directly …

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0378/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0378/occurrences/)

<sub>[NV-1368](https://linear.app/novu/issue/NV-1368/js-0378-found-template-literal-expression-having-a-non-string-type)</sub>

**Comment by abhinavsaurav** [comment]
Hi @scopsy Can I take a look at it?

**Comment by abhinavsaurav** [comment]
@scopsy have done the changes just want to check if the default text in case of errors should be kept as "placeholder" or should I just make it empty

**Comment by scopsy** [comment]
Not sure I understand what this refers to, mind submitting a PR and commenting there on the relevant section?
