### ISSUE TITLE
[NV-1369] (JS-T1001) Optional property in interface has an 'undefined' type

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2289]
## Description
Optional property syntax (?) implicitly adds an &#x27;undefined&#x27; type to the property. Explicitly having an &#x27;undefined&#x27; type in the union of an optional property is redundant and should be avoided to improve the readability of the code.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-T1001/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-T1001/occurrences/)

<sub>[NV-1369](https://linear.app/novu/issue/NV-1369/js-t1001-optional-property-in-interface-has-an-undefined-type)</sub>

**Comment by natnael-meresa** [comment]
@scopsy I'd like to work on this issue, it is very easy first issue

**Comment by scopsy** [comment]
Unfortunately it was resolved already by someone else :( sorry about this. He probably missed this issue
