### ISSUE TITLE
[NV-1370] (JS-0042) Found no return statements in callbacks of array methods

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2290]
## Description
`Array` has several methods for filtering, mapping, and folding. If we forget to write return statement in a callback of those, it&#x27;s probably a mistake. If you don&#x27;t want to use a `return` or don&#x27;t need the returned results, consider using `.forEach` instead.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/novuhq/novu/issue/JS-0042/occurrences/](https://deepsource.io/gh/novuhq/novu/issue/JS-0042/occurrences/)

<sub>[NV-1370](https://linear.app/novu/issue/NV-1370/js-0042-found-no-return-statements-in-callbacks-of-array-methods)</sub>

**Comment by ShashwatAgrawal20** [comment]
@scopsy I'd like to work on the issue if possible

**Comment by TheLearneer** [comment]
@scopsy it seems that the issue has been fixed?? Maybe with some other commits?
When I check the deepsource URL, the page says can't find any occurrence of this issue.

Can you please confirm 🙇

**Comment by jainpawan21** [comment]
Yes i think it is fixed
