### ISSUE TITLE
🚀 Feature: Reusable layout (template)

### ISSUE THREAD

**Issue by Swahjak** [novuhq/novu#2291]
### 🔖 Feature description

Add reusable layouts that can be used to make templating less repetitive and easier to maintain (not having to edit all templates when something, like a company phone number, changes.

### 🎤 Why is this feature needed ?

In many cases, especially for e-mail, you re-use many components in an e-mail. While having access to MJML (https://github.com/novuhq/novu/issues/1792) would help. It still leaves us with repetitive work to recreate headers and footers for each template. Postmark solves this issues by allowing users to define a 'layout' that contains a placeholder `{{{ @content }}}`, which can then be used when creating a template. The contents of the template will be replace the `{{{ @content }}}` placeholder.

https://postmarkapp.com/support/article/1077-template-syntax

### ✌️ How do you aim to achieve this?

Add a section "Layouts" in "Settings" in which one (or more) layouts can be created. Layouts can then be used when creating templates. When a layout is used, the contents of the template are placed in the layout using the `{{{ @content }}}` placeholder.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
@Swahjak we have recently launched the new layouts management feature. Please take a look here: https://docs.novu.co/platform/layouts 

Will close this one as completed :)
