### ISSUE TITLE
Duplicate assignment in code

### ISSUE THREAD

**Issue by Cxxshyy** [novuhq/novu#2301]
I'm submitting a question about the decisions made in the repository

- The code https://github.com/Cxxshyy/novu/blob/37d3fbd98a7a0f8b4a061c4f8e7542f6c6963df8/apps/api/src/app/events/usecases/send-message/test-send-email.usecase.ts#L123-L123  is a double assignment and can be reduced to one line and could potentially have some unexpected side affects. Unless there is a clear reason as to why it should be done in 2 lines rather than one I suggest it be changed.

-Link to the deepsource information 
https://deepsource.io/gh/Cxxshyy/novu/issue/JS-W1032/occurrences?listindex=0

**Comment by jainpawan21** [comment]
Hi @Cxxshyy 
Thanks for your contribution ❤️
Please use our issue template

**Comment by Cxxshyy** [comment]
@jainpawan21 which template bug or feature

**Comment by Cxxshyy** [comment]
issue #2305
