### ISSUE TITLE
[NV-2911] 🚀 Feature: option to send email attachments from UI

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2313]
### 🔖 Feature description

Novu supports sending email attachments through its sdk 
https://docs.novu.co/channels/email/#sending-email-attachments

But this is not working, if we try to send like this from UI
![image](https://user-images.githubusercontent.com/39362422/208312555-58807dde-a0e7-475d-9056-cadb49c0cd30.png)

### 🎤 Why is this feature needed ?

To send email attachments from UI

### ✌️ How do you aim to achieve this?

Maybe implementing a file upload option.

Check the [Figma designs here](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=892%3A20999&mode=design&t=HNXHg3xNaKNueEdu-1)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2911](https://linear.app/novu/issue/NV-2911/🚀-feature-option-to-send-email-attachments-from-ui)</sub>

**Comment by mahendraHegde** [comment]
@jainpawan21  for file upload do you have any design/flow in mind?
one option is to show file picker as soon as user types `attachments:[{}]` in the payload section, then we can repopulate name and mime, just to keep the design simple, what do you think?

**Comment by Vishrut19** [comment]
Is anyone working on it?

**Comment by Shurtu-gal** [comment]
Hey people is anybody currently working on this?

**Comment by nick2432** [comment]
can i work on this?

**Comment by parag477** [comment]
Hey @jainpawan21 Can you please assign this issue to me. I am willing to work on this issue.

**Comment by priyanshagra** [comment]
please assign this to me

**Comment by scopsy** [comment]
Need to close this one for now, as the designs are not finalized yet here 🙏
