### ISSUE TITLE
[NV-1527] 🚀 Feature: support of multiple email-ids in to, cc and bcc fields of email

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2314]
### 🔖 Feature description

Adding option of multiple email-ids in to, cc and bcc fields is missing

### 🎤 Why is this feature needed ?

to send same email to multiple email-ids at the same time

### ✌️ How do you aim to achieve this?

NA

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1527](https://linear.app/novu/issue/NV-1527/🚀-feature-support-of-multiple-email-ids-in-to-cc-and-bcc-fields-of)</sub>

**Comment by oba2311** [comment]
@jainpawan21 - does that refer to manually do so? because programaticaly this seems like topics when it comes to To.

**Comment by tsssdev** [comment]
I can work on this, please assign me

**Comment by aayushdura** [comment]
@jainpawan21  Can you provide a bit more info regarding this feature

**Comment by scopsy** [comment]
Why? I would add: cc and bcc, and replyTo as part of the overrides for the email channel. Wdyt?

**Comment by scopsy** [comment]
Any other things might be helpful to allow to override?

**Comment by scopsy** [comment]
If we are at it, we could also pass some other params there:

* text
* html

Was just writing a pseudo code up there :P

**Comment by scopsy** [comment]
Yes, the goal with the overrides is give the power for the developer to help with whatever edgecase our system doesn't support fully. Maybe worth looking at all the email specific (not provider specific) properties there.

**Comment by osm-vishnukyatannawar** [comment]
Hey @scopsy 

I have this usecase to support of multiple email-ids in to.

Topics do not solve my problem. 

My usecase is to send a report to multiple people who subscribed for that report.
But when I try the topic concept I see that one email is sent to reach subscriber.
So they cannot really tell who all were there on the To list. They only see their email.

For example: 

In mailgun I would do something like below. Check the to field.

```js
const messageData = {
  from: 'Excited User <me@samples.mailgun.org>',
  to: 'foo@example.com, bar@example.com',
  subject: 'Hello',
  text: 'Testing some Mailgun awesomeness!'
};
```

And would see a result like this (2 emails in the to list)

![image](https://user-images.githubusercontent.com/16570290/218726174-f4ad081a-ca1e-429a-bc3b-18c237f3018e.png)

Will this issue address this problem too? Or is there any hack which I can do to achieve this right now in novu?

**Comment by scopsy** [comment]
@davidsoderberg what do you think about adding the "to" field in the overrides aswell? We can override our "to" generated list and use the user defined one.

**Comment by davidsoderberg** [comment]
The problem with full override is that we show that we sent it to the one we generate, what we could do I guess is to merge those two into one list of adresses... @scopsy

**Comment by scopsy** [comment]
@davidsoderberg yes, we can merge this and remove duplicates. We will just need to outline this in the docs. @osm-vishnukyatannawar what do you think?

**Comment by im-perativa** [comment]
I have similar case with @osm-vishnukyatannawar but in my case i have to use BCC. I thought the "topics" concept can be applied but instead one email is sent to each subscriber and I'm afraid that will inefficiently consume "Maximum messages per day" quota from my email provider

**Comment by SerafeimOikonomou** [comment]
Hi @scopsy! As I understand, this is merged in `next` branch, which means that cc/bcc options will be available in the upcoming release, right?

**Comment by jainpawan21** [comment]
Yes you are right 👍
