### ISSUE TITLE
[NV-1528] 🐛 Bug Report: email failing with emailjs

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2315]
### 📜 Description

Email is not sent with emailjs when using gmail as service

### 👟 Reproduction steps

- Go to EmailJs
- Choose Gmail as Service
- Authorise your google account.
- After successful test verification of google account connection, copy emailjs key and add in integration store and enable it
- Add email as a step in your notification workflow.
- Click the test workflow, fill required details and click in trigger button
- It will fail in execution details.

### 👍 Expected behavior

It should send email succesfully

### 👎 Actual Behavior with Screenshots

<img width="1385" alt="Screenshot 2022-12-18 at 11 53 57 PM" src="https://user-images.githubusercontent.com/39362422/208313893-62d491dd-151b-4f46-97da-af9b8f603f18.png">

### 💻 Operating system

MacOS

### 🤖 Node Version

16.17.0

### 📃 Provide any additional context for the Bug.

It is happening in local env as well as in web.novu.co 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1528](https://linear.app/novu/issue/NV-1528/🐛-bug-report-email-failing-with-emailjs)</sub>

**Comment by rajveer43** [comment]
I would like to contribute

**Comment by jainpawan21** [comment]
Sure @rajveer43.
Go ahead.

**Comment by rajveer43** [comment]
thank you @jainpawan21

**Comment by rajveer43** [comment]
Hello @jainpawan21 I would not be able to provide time to this issue, kindly assign it to somebody else.

**Comment by jainpawan21** [comment]
The emailjs package used in the provider is actually something similar to nodemailer not the original EmailJS official SDK, and expects all the config details like host, port, ssl, tls, etc using emailjs is the same thing as using the custom SMTP server 

The official SDK is @emailjs/node , but one issue is, EmailJS have their own Templates feature and for sendEmail API call(both in SDK and REST API) it expects the TemplateID to be provided in the payload. and this makes our Workflow editor template useless

So in my opinion, we should remove emailjs from email providers

**Comment by scopsy** [comment]
@jainpawan21.novu aggree on this, will remove this
