### ISSUE TITLE
🐛 Bug Report: Double scroll bars in Admin Panel

### ISSUE THREAD

**Issue by caiopiassali** [novuhq/novu#2326]
### 📜 Description

Admin Panel layout are showing double scroll bars

### 👟 Reproduction steps

1. Go to any admin panel page
2. See at the page right the double scroll bars

### 👍 Expected behavior

It should be displayed single scroll bar?

### 👎 Actual Behavior with Screenshots

![Captura de tela de 2022-12-19 22-44-30](https://user-images.githubusercontent.com/42686072/208561750-945f95be-cc64-4b7c-a8be-079c1b2d220a.png)
![Captura de tela de 2022-12-19 22-57-20](https://user-images.githubusercontent.com/42686072/208563243-59aaf759-6632-4a8c-aef2-70ecb92b14f7.png)

### 💻 Operating system

Linux

### 🤖 Node Version

16.18.1

### 📃 Provide any additional context for the Bug.

It happens in local env, not tested in web.novu.co.

Tested in Chrome, Brave and Firefox.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
@caiopiassali Are you interested to work on this?

**Comment by caiopiassali** [comment]
@jainpawan21 Yes, i take care of it
