### ISSUE TITLE
🐛 Bug Report: Fcm push notifications it gives unexpected provider error in the activity feed

### ISSUE THREAD

**Issue by sujeet2singh** [novuhq/novu#2343]
### 📜 Description

Working on fcm push notification  it gives unexpected provider error on the activity feed section although i have fullfilled all the steps mentioned in the documents provided. Like setting the credentials and adding deviceTokens before triggering notification 
I have attached the screenshots below for related issue.

![Screenshot from 2022-12-22 18-12-17](https://user-images.githubusercontent.com/103049267/209136808-6dcd4e84-a470-468a-abb6-fd1ed36a577e.png)

### 👟 Reproduction steps

Go to activity feed after triggering push notification,
=>  it gives unexpected provider error on the activity feed section although it gives success response on triggering notification

### 👍 Expected behavior

It show a notification with the proper data in the activity feed

### 👎 Actual Behavior with Screenshots

![Screenshot from 2022-12-22 18-12-17](https://user-images.githubusercontent.com/103049267/209139366-bc288ed5-335e-451f-a55b-8cf1f153e807.png)

### 💻 Operating system

Linux

### 🤖 Node Version

v16.19.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
Hi @sujeet2singh, It looks like an error from FCM,
Can you please check again your creds?

**Comment by sujeet2singh** [comment]
> Hi @sujeet2singh, It looks like an error from FCM, Can you please check again your creds?

Thanks @jainpawan21

**Comment by im-perativa** [comment]
Hi @sujeet2singh, I have the same problem today. Would you like to share how you manage to fix it? I have already sucessfully test FCM without Novu in my app but when i tried to use Novu (with service account) it gives me unexpected provider error.
Thank you
