### ISSUE TITLE
🐛 Bug Report: APNS environment parameters issue

### ISSUE THREAD

**Issue by serafeimo** [novuhq/novu#2346]
### 📜 Description

In APNS provider there is the following check for `prod env` parameter.

```
/novu/providers/apns/src/lib/apns.provider.ts
        production: process.env.NODE_ENV === 'production'
```

However, it seems that the actual prod value is `prod`.

### 👟 Reproduction steps

Sending a push notification using APNS in production environment will probably fail. I'm having some issues with it but I don't know if it's due to that yet.

### 👍 Expected behavior

Novu's production parameter should me `prod` and not `production`.

Probably something like: `production: process.env.NODE_ENV === 'prod'`

### 👎 Actual Behavior with Screenshots

`production: process.env.NODE_ENV === 'production' `check is wrong.

### 💻 Operating system

MacOS

### 🤖 Node Version

Using docker (ghcr.io/novuhq/novu/api:0.9.0) - I think Node 16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by isurumaldeniya** [comment]
Hi, @jainpawan21 Can you assign this to me?

**Comment by jainpawan21** [comment]
Yeah sure @isurumaldeniya 
Let me know if you need any help

**Comment by isurumaldeniya** [comment]
Hi @jainpawan21 I have sent a PR please look into it. Thank you.
https://github.com/novuhq/novu/pull/2416
