### ISSUE TITLE
[NV-1530] 🚀 Feature: add Line@ messaging as chat provider

### ISSUE THREAD

**Issue by yusef-ho** [novuhq/novu#2349]
### 🔖 Feature description

Please Add [Line@ Messaging](https://developers.line.biz/en/services/messaging-api/) as Chat Provider
[Official NodeJS SDK for Line API](https://line.github.io/line-bot-sdk-nodejs/)

### 🎤 Why is this feature needed ?

In Taiwan and some countries in Asia, Line is the most used chat app

### ✌️ How do you aim to achieve this?

Add new custom chat provider and use [NodeJS SDK for Line API](https://line.github.io/line-bot-sdk-nodejs/)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1530](https://linear.app/novu/issue/NV-1530/🚀-feature-add-line-messaging-as-chat-provider)</sub>

**Comment by KaoutharAsma** [comment]
can I work on this?
