### ISSUE TITLE
[NV-1531] 🐛 Bug Report: APNS missing topic

### ISSUE THREAD

**Issue by serafeimo** [novuhq/novu#2351]
### 📜 Description

I'm trying to send a push notification using APNS provider but I'm getting an error that (I think) indicates that there's something missing from the configuration.

> {
>   "stack": "Error: 85a57fd53908d108da4c3fe1da073677c418e3bb7674f96e2cb46bcc69eb8a3c failed for reason: MissingTopic\n    at APNSPushProvider.<anonymous> (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:84:35)\n    at step (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:44:23)\n    at Object.next (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:25:53)\n    at fulfilled (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:16:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
>   "message": "85a57fd53908d108da4c3fe1da073677c418e3bb7674f96e2cb46bcc69eb8a3c failed for reason: MissingTopic"
> }

The configuration for the APNS provider in Novu requires: 

> Private Key
> Key ID
> Team ID

After searching in Google, I found out that the `topic` is actually the `bundleId`. Other apps that provide APNS testing requires that (bundleid/topic) to be set together with the rest of the parameters (private key, keyid, teamid) before setting the payload and sending the notification.

I'm not familiar with APNS, so I'm not sure if my assumption is correct but I tried placing this parameter in payload and overrides objects without any luck.

### 👟 Reproduction steps

1. Configure APNS provider
2. Send push notification using APNS

### 👍 Expected behavior

Push notification should be sent.

### 👎 Actual Behavior with Screenshots

The following error occurs:

> {
>   "stack": "Error: 85a57fd53908d108da4c3fe1da073677c418e3bb7674f96e2cb46bcc69eb8a3c failed for reason: MissingTopic\n    at APNSPushProvider.<anonymous> (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:84:35)\n    at step (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:44:23)\n    at Object.next (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:25:53)\n    at fulfilled (/usr/src/app/providers/apns/build/main/lib/apns.provider.js:16:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
>   "message": "85a57fd53908d108da4c3fe1da073677c418e3bb7674f96e2cb46bcc69eb8a3c failed for reason: MissingTopic"
> }

### 💻 Operating system

MacOS

### 🤖 Node Version

docker image

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1531](https://linear.app/novu/issue/NV-1531/🐛-bug-report-apns-missing-topic)</sub>

**Comment by scopsy** [comment]
Relevant information for the missing topic (bundleId) specification: [https://github.com/node-apn/node-apn#sending-a-notification](https://github.com/node-apn/node-apn#sending-a-notification)

**Comment by SerafeimOikonomou** [comment]
Hi @scopsy! I noticed that you closed this one. Isn't this a bug?

**Comment by scopsy** [comment]
@SerafeimOikonomou it was fixed by @davidsoderberg in https://github.com/novuhq/novu/pull/2798 just forget to add the `closes` tag :)

**Comment by SerafeimOikonomou** [comment]
Oh great, thanks a lot!

**Comment by SerafeimOikonomou** [comment]
@scopsy sorry to bother you again. Is there a release date for the next release that will contain this fix? 
Thanks!

**Comment by scopsy** [comment]
I Believe that in will be by the end of next week/beggining of the one after 🙏

**Comment by SerafeimOikonomou** [comment]
Thanks again!
