### ISSUE TITLE
[NV-1404] 🐛 Bug Report: Creating ENUM for url paths.

### ISSUE THREAD

**Issue by BhuvaneshPatil** [novuhq/novu#2366]
### 📜 Description

Creating ENUM for url path which are used as path for routing.
```
<SpotLightProvider>
                <Routes>
                  <Route path="/auth/signup" element={<SignUpPage />} />
                  <Route path="/auth/login" element={<LoginPage />} />
                  <Route path="/auth/reset/request" element={<PasswordResetPage />} />
                  <Route path="/auth/reset/:token" element={<PasswordResetPage />} />
                  <Route path="/auth/invitation/:token" element={<InvitationPage />} />
                  <Route path="/auth/application" element={<CreateOrganizationPage />} />
                  <Route
                    path="/partner-integrations/vercel/link-projects"
                    element={
                      <RequiredAuth>
                        <LinkVercelProjectPage type="create" />
                      </RequiredAuth>
                    }
                  />
                  <Route
                    path="/partner-integrations/vercel/link-projects/edit"
                    element={
                      <Require

....
```

### 👟 Reproduction steps

NA

### 👍 Expected behavior

We should have an ENUM for routes that can be used as constant, this will used at all places where we are using route,
For example - 
`navigate(<path>)`

It will improve reusability and less error-prone code.

For example, we can save ourselves from spelling mistakes, if in future if we decide to rename routes it will be easier.

### 👎 Actual Behavior with Screenshots

NA

### 🤖 Node Version

NA

### 📃 Provide any additional context for the Bug.

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1404](https://linear.app/novu/issue/NV-1404/🐛-bug-report-creating-enum-for-url-paths)</sub>

**Comment by scopsy** [comment]
I think that is a great idea @BhuvaneshPatil! Assigning you 🙏
