### ISSUE TITLE
[NV-1132] Intercom + side props overlay - side prop cannot be dismissed

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2376]
## What?

The notification toast is overlapping the intercom icon:

![CleanShot 2022-11-02 at 23.29.09@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/d069bc36-a2d1-485d-8218-aca5eaf7a80e/eb66bc21-b4ff-40b2-be77-b3648fca059f)

---

We should move the toast position to be like so:

![Frame 414.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/1e8850b2-d228-464f-8fef-d784f4caaec3/779dc496-4bd5-49ee-be0c-6db8cb72b035)

NOTICE: this is a system-wide issues that does not relate to a specific screen but rather to all screens. When testing the solution make sure to test for dark-light theme, and different kinds of toasts / props.

You probably do not need to  touch the intercom component at all, and focus on the Novu prop only.

A good starting point:

[https://github.com/novuhq/novu/blob/2d3050a13b5dfc77b0d66e34ed2eac8a25299631/apps/web/src/utils/notifications.tsx](https://github.com/novuhq/novu/blob/2d3050a13b5dfc77b0d66e34ed2eac8a25299631/apps/web/src/utils/notifications.tsx)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1132](https://linear.app/novu/issue/NV-1132/intercom-side-props-overlay-side-prop-cannot-be-dismissed)</sub>

**Comment by oba2311** [comment]
It seems it didn't sync to Github. @scopsy I am not sure why

**Comment by oba2311** [comment]
@scopsy I think that now it is good enough - anything to add?

**Comment by oba2311** [comment]
Let's go with option two,  Could you update the ticket with proper information and what to implement so we can extract it for a community ticket?

**Comment by oba2311** [comment]
So either next to it, or above it - see: I prefer option 2

[Frame 413 - Concepting (Figma)](https://www.figma.com/file/9jalQvImfHtbbExZPLW3XO/Concepting?node-id=3923%3A44672&t=cFRqDFATauD3PvMn-11)

**Comment by oba2311** [comment]
Sure, but any other suggestion? :)

**Comment by oba2311** [comment]
Please not above 🙏

**Comment by oba2311** [comment]
@oba2311 what do you think we should do with the toastr? Put it on top right or just above the intercom icon?

**Comment by oba2311** [comment]
@scopsy I added instructions - do you want to add a lil bit technical "where to start" so it can be a good first issue?

**Comment by oba2311** [comment]
Yes, but since we are staying with intercom we need to fix this - let's decide and hand it over to the community. @ainouzgali what's your suggestion on how to fix it?

**Comment by oba2311** [comment]
So it is a general problem with our messages behavior. It will look the same for any notification message. I'm not sure I agree about the shift. It might look very odd. We can discuss it and then make it for the community or backlog. @oba2311

**Comment by scopsy** [comment]
@ainouzgali was because @oba2311 didn't had his account connect on the sync tool, now should be ok :)

**Comment by Susmita-Dey** [comment]
I think fixing the position might solve this problem. I can take it up. @scopsy kindly assign it to me

**Comment by jainpawan21** [comment]
Sure @Susmita-Dey

**Comment by Susmita-Dey** [comment]
Exams are going on. Will make me a pr soon after 20th Jan

**Comment by jayavardhan3112** [comment]
Can I pick it up, seems like its been on hold for a while !

**Comment by Susmita-Dey** [comment]
Hey @oba2311 is the issue fixed?

I forgot to fix the issue. But I can do it now.

**Comment by jainpawan21** [comment]
@Susmita-Dey, No it is not fixed.
You can work on this!

**Comment by Susmita-Dey** [comment]
Okay

**Comment by ankur0904** [comment]
@jainpawan21 Can I work on this issue?

**Comment by scopsy** [comment]
Hi @ankur0904 we are closing this issue for now as we are working for a different approach to solve the problem which makes this issue not relevant soon. Will close this nonetheless.
