### ISSUE TITLE
[NV-1533] 🚀 Feature: Notification Center Bundle Size

### ISSUE THREAD

**Issue by hckhanh** [novuhq/novu#2379]
### 🔖 Feature description

The size of @novu/notification-center is really big

### 🎤 Why is this feature needed ?

According to discussion #2008, we think that the size of the novu popup chat should be reduced

### ✌️ How do you aim to achieve this?

I think we should discuss more about this.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1533](https://linear.app/novu/issue/NV-1533/🚀-feature-notification-center-bundle-size)</sub>

**Comment by lu-zen** [comment]
Half of it's size is the entire date-fns library + entire @mantine/core (〃ﾟдﾟ〃)
Can we do some tree shaking?

**Comment by phibr0** [comment]
I have looked into this a bit. I am sure there are some ways to optimize usage of mantine and some other libraries too, but the biggest of them is date-fns. 

The NotificationCenter bundles every locale of date-fns (See: <https://github.com/novuhq/novu/blob/next/packages/notification-center/src/hooks/useTranslations.ts#L3>)


I have looked into implementing code splitting via dynamic imports, but rollup seems to have really poor support for it (Only bundles relative paths, **doesn't support variables in paths**, etc.).

**Comment by scopsy** [comment]
@phibr0 yep :( Wonder what our options are other than loading the locale from a remote CDN on demand.

**Comment by phibr0** [comment]
Maybe date-fns should be a peer dependency and developers could import the desired locales manually via some sort of provider? I think most people won't need 90% of them anyway

**Comment by CaptainT33mo** [comment]
Just curious as to why don't you guys propose the use of the ECMAScript Internationalization API instead of using the locale from `date-fns`. Even on the date-fns repo many people suggested incorporating the Internationalization API directly into the date-fns locale API but it never went through due to the lack of support for that API at that time. https://github.com/date-fns/date-fns/issues/464

**Comment by scopsy** [comment]
@CaptainT33mo I think it's worth exploring, does the Internationalization API allows things like: "33 minutes ago" in different languages?

**Comment by phibr0** [comment]
It does!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

**Comment by CaptainT33mo** [comment]
@scopsy Yes it does support that out of the box using the Intl.RelativeTimeFormat object https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat & has better support as well

**Comment by zek** [comment]
I also use browser's Intl in my application. We should rely on Intl instead of loading a very big package.

**Comment by scopsy** [comment]
@zek yep! Definitely the headless lib is something we are evaluating right now to have, hopefully will be available in a few weeks from now. will update on this.

**Comment by opti21** [comment]
It'd be awesome if the useNotification hook could be a separate package. I don't even use UI that comes with it.
