### ISSUE TITLE
[NV-1534] 🐛 Bug Report:  Close Icon not visible properly

### ISSUE THREAD

**Issue by BhuvaneshPatil** [novuhq/novu#2388]
### 📜 Description

Close Icons hides behind scroll bar when adding an integration.

### 👟 Reproduction steps

1. Go to Integration Store
2. Select any provider
3. Hover on the scroll bar or try to click the close icon

### 👍 Expected behavior

Close Icon should be visible all the time.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/27822551/209968212-037f69e8-191f-4704-8800-5f564a3087c2.png)

![image](https://user-images.githubusercontent.com/27822551/209968341-0d09900e-ccc0-43b0-9e3c-19496d3e0d5d.png)

### 🤖 Node Version

NA

### 📃 Provide any additional context for the Bug.

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1534](https://linear.app/novu/issue/NV-1534/🐛-bug-report-close-icon-not-visible-properly)</sub>

**Comment by jainpawan21** [comment]
Hi @BhuvaneshPatil, is this happening in small screen size?

**Comment by Sko0by** [comment]
hey id like to help with that

**Comment by scopsy** [comment]
This will be solved as part of #2744 so assigning @Sko0by
