### ISSUE TITLE
🐛 Bug Report: WebSocket connection to 'wss://ws.novu.co/socket.io/?token=eyJhbG... failed: Invalid frame header

### ISSUE THREAD

**Issue by shahbazmeh61** [novuhq/novu#2392]
### 📜 Description

Not showing real time notification badge, which was working fine few days ago when I was working on Novu with the same version. 
Keep pushing web socket errors in console and whenever I trigger in app notification, notification badge don't appear but when i click notification icon to open notification box there are many unread notifications.

### 👟 Reproduction steps

Have not any specific reproduction way, just installed 0.9.2 version and not keep getting socket error in console

### 👍 Expected behavior

Show badge on notification icon whenever any new in app notification trigger

### 👎 Actual Behavior with Screenshots

<img width="1355" alt="Screenshot 2022-12-29 at 10 41 17 PM" src="https://user-images.githubusercontent.com/115981560/210017923-556463f9-96d0-4888-b9a3-988b64de925e.png">

### 🤖 Node Version

0.9.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by kevishie** [comment]
I'm having the same issue

**Comment by DawsonSeibold** [comment]
I am having the same issue as well.

**Comment by scopsy** [comment]
@shahbazmeh61 could you please try again? Upgrade to the latest `0.10.1` on the client side aswell.

**Comment by mmmoli** [comment]
0.10.1 fixed it for me 🙏 !

**Comment by scopsy** [comment]
And sorry for the inconvenience, thinking of setting up a backwards compatibility test right now to make sure we won't have those problems anymore 🙏

**Comment by shahbazmeh61** [comment]
@scopsy thanks for the fix, working correct now
