### ISSUE TITLE
[NV-1522] 🏛️ Rename organisation

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2402]
### 🔖 Feature description

Adding support of renaming organisation

### 🎤 Why is this feature needed ?

it is not possible to either delete or rename organisation. only option is to create new organisation

### ✌️ How do you aim to achieve this?

Implementing API first and then in Web

### 🔄️ Additional Information

*No response*

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Solution**

[Development / Workflows - Crafting updates (Figma)](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=2190%3A10883&mode=design&t=nRX8ll7wtl3h2uYs-1)

[Admin / Project profile  - Crafting updates (Figma)](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=2176%3A16990&mode=design&t=nRX8ll7wtl3h2uYs-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1522](https://linear.app/novu/issue/NV-1522/🏛️-rename-organisation)</sub>

**Comment by Abobos** [comment]
@scopsy this looks like a quick win. I can work on it However, @jainpawan21 can provide more description. Thanks

**Comment by scopsy** [comment]
Unfortuently we don't have a UI for this functionality yet 😦
But maybe you want to create an API endpoint for updating organizations?

**Comment by jainpawan21** [comment]
@Abobos 
You can add this new endpoint here
https://github.com/novuhq/novu/blob/next/apps/api/src/app/organization/organization.controller.ts

**Comment by Abobos** [comment]
@jainpawan21 , 

> @Abobos You can add this new endpoint here https://github.com/novuhq/novu/blob/next/apps/api/src/app/organization/organization.controller.ts

@jainpawan21 noted. @scopsy do we have to create a separate ticket for this?

**Comment by jainpawan21** [comment]
No, No need you can create PR and reference this issue only.

**Comment by Abobos** [comment]
@jainpawan21 @scopsy I have started working on the API endpoint [here](https://github.com/novuhq/novu/pull/2634). I am thinking since branding is part of the organization resource.. why not move the updating of branding to the same endpoint.. so to speak, we will just have one endpoint that does organization update

**Comment by jainpawan21** [comment]
> @jainpawan21 @scopsy I have started working on the API endpoint [here](https://github.com/novuhq/novu/pull/2634). I am thinking since branding is part of the organization resource.. why not move the updating of branding to the same endpoint.. so to speak, we will just have one endpoint that does organization update

@scopsy your thoughts?

**Comment by scopsy** [comment]
I would prefer to leave the branding separate at this moment, since in the future they might evolve for different directions and needs. Even if they feel quite similar right now.

**Comment by abhisheksunil2201** [comment]
@scopsy is this feature closed?

**Comment by Abobos** [comment]
@scopsy we need to implement this on the web application, I mean the admin panel.. right?

**Comment by scopsy** [comment]
Yes @Abobos but unfortuently we don't yet have a design for this part of work. We need to think how to incorporate this as a organization details page or something like this.

**Comment by Abobos** [comment]
> Yes @Abobos but unfortuently we don't yet have a design for this part of work. We need to think how to incorporate this as a organization details page or something like this.

Okay.. Let me take a look

**Comment by Abobos** [comment]
> Yes @Abobos but unfortuently we don't yet have a design for this part of work. We need to think how to incorporate this as a organization details page or something like this.

@scopsy I think we can incorporate this in the settings page. kindly see the screenshot below. Let me know what you think.

![Screenshot 2023-04-01 at 21 53 44](https://user-images.githubusercontent.com/39123908/229311477-51c2ea87-d7d2-4c92-80e5-a3c94a3266a3.png)

**Comment by scopsy** [comment]
@Abobos this could actually work for now, @nknyshov what do you think?

@Abobos do you want to submit a PR?

**Comment by Abobos** [comment]
@scopsy yes.. However, @nknyshov can give his thoughts about the design

**Comment by trueadic** [comment]
@Abobos Thanks for the proposal, this is something I wanted to fix either. But I have doubts about the place you suggesting. I think that the functionality of changing a name as well as the deletion of the organisation should be in place, right in the dropdown. Not sure that decision to keep that functionality in settings will be discoverable. What do you think?

**Comment by Abobos** [comment]
> @Abobos Thanks for the proposal, this is something I wanted to fix either. But I have doubts about the place you suggesting. I think that the functionality of changing a name as well as the deletion of the organisation should be in place, right in the dropdown. Not sure that decision to keep that functionality in settings will be discoverable. What do you think?

which dropdown are you referring to?

**Comment by Abobos** [comment]
> > @Abobos Thanks for the proposal, this is something I wanted to fix either. But I have doubts about the place you suggesting. I think that the functionality of changing a name as well as the deletion of the organisation should be in place, right in the dropdown. Not sure that decision to keep that functionality in settings will be discoverable. What do you think?
> 
> which dropdown are you referring to?

@trueadic

**Comment by nknyshov** [comment]
@Abobos Hi, I refer to the dropdown that allows you to switch between companies
<img width="1512" alt="Screenshot 2023-04-13 at 11 15 36" src="https://user-images.githubusercontent.com/117754545/231729159-f3b5cf71-a3d8-41a8-93bb-d5f3a0afbfca.png">

**Comment by Abobos** [comment]
> @Abobos Hi, I refer to the dropdown that allows you to switch between companies <img alt="Screenshot 2023-04-13 at 11 15 36" width="1512" src="https://user-images.githubusercontent.com/117754545/231729159-f3b5cf71-a3d8-41a8-93bb-d5f3a0afbfca.png">

The dropdown just shows the list of organisations to switch to.. That is an organisation switcher.. I am a bit torn on how we can accommodate for the delete/rename organization functionality there.. if you already have a design on this for me to get a visual perspective, you can share;

**Comment by nknyshov** [comment]
@Abobos Hey, sorry for the delayed reply. I lost the notification about your reply in my inbox, so I didn't see your question, sorry. I haven't prepared the design yet, I plan to work on it within the upcoming month or two. As far as I get the design, I will come back to you and we could discuss the details. Does it sound like a plan to you? Please let me know if you have any additional questions.

**Comment by florian-lefebvre** [comment]
I have a request regarding this feature, could it be possible to add the corresponding methods in the novu client package and in the api docs? See #1315

**Comment by Abobos** [comment]
@nknyshov Do you have the design now?

**Comment by Abobos** [comment]
> I have a request regarding this feature, could it be possible to add the corresponding methods in the novu client package and in the api docs? See #1315

@florian-lefebvre noted..  I can work on it. Is there a ticket to add this particular API endpoint?

**Comment by florian-lefebvre** [comment]
Sounds good to me 👍

**Comment by Abobos** [comment]
@nknyshov @trueadic

**Comment by Abobos** [comment]
> > I have a request regarding this feature, could it be possible to add the corresponding methods in the novu client package and in the api docs? See #1315
> 
> @florian-lefebvre noted.. I can work on it. Is there a ticket to add this particular API endpoint? Also, This should be under organisation module. We don't have a module for organisation yet in @novu/node package. Maybe we should create a ticket for adding the organisation module in this case.
> 
> cc: @scopsy

@scopsy

**Comment by Abobos** [comment]
@nknyshov @trueadic any update on the design.. I am leaning towards raising a PR with the design I propose.

cc: @scopsy @jainpawan21

**Comment by nknyshov** [comment]
@Abobos Hey 👋 Thanks for staying tuned, we remember about the issue and plan to roll up updates in Q4.

**Comment by Abobos** [comment]
> @Abobos Hey 👋 Thanks for staying tuned, we remember about the issue and plan to roll up updates in Q4.

Okay. I will pick another task to work on before then.

**Comment by nknyshov** [comment]
@Abobos I will let you know as soon as we finalize the design, thank you!

**Comment by Abobos** [comment]
> @Abobos I will let you know as soon as we finalize the design, thank you!

@nknyshov Is the design now finalized?

**Comment by scopsy** [comment]
Yes @Abobos but unfortuently it's going to be part of a very big project for redesigning the navigation stack. I will close this ticket at the moment.

**Comment by Abobos** [comment]
@scopsy the design is ready right?.. Where can I access this design so I can start work on it
