### ISSUE TITLE
[NV-1523] 🚀 Feature: override from email field during trigger

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2403]
### 🔖 Feature description

There is option of `from` email field in integration store only and it can not be changed anywhere except integration store.
There should be support of override default value during trigger.

### 🎤 Why is this feature needed ?

To override default `from` email value

### ✌️ How do you aim to achieve this?

NA

### 🔄️ Additional Information

https://discord.com/channels/895029566685462578/1055584533413638224

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1523](https://linear.app/novu/issue/NV-1523/🚀-feature-override-from-email-field-during-trigger)</sub>

**Comment by tsssdev** [comment]
Any one started on this? if not I can work on it, please assign me

**Comment by ainouzgali** [comment]
Sure! Reach out here or on discord if you have any questions :)

**Comment by scopsy** [comment]
Also related to #2314

**Comment by scopsy** [comment]
Closed with: https://github.com/novuhq/novu/issues/2314
