### ISSUE TITLE
🐛 Bug Report: Vue Component package.json should have vue as peerDepedency

### ISSUE THREAD

**Issue by flashspys** [novuhq/novu#2406]
### 📜 Description

https://github.com/novuhq/novu/blob/next/packages/notification-center-vue/package.json

The following package.json pins vue^3.2.45 as dependency. It should be a peer dependency.

### 👟 Reproduction steps

See above

### 👍 Expected behavior

See above

### 👎 Actual Behavior with Screenshots

See above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by LetItRock** [comment]
will be fixed in PR: https://github.com/novuhq/novu/pull/2515
