### ISSUE TITLE
🐛 Bug Report: Duplicate notification settings are created in notification center

### ISSUE THREAD

**Issue by SajMohammed** [novuhq/novu#2436]
### 📜 Description

When clicking enable or disable on the notification panel, it doesn't actually make any change. Instead, it creates replica of that notification. 
Updated novu to the latest version and the notification center seems to be really buggy. Please assist

### 👟 Reproduction steps

1. Click on the notification center settings
2. click any notification to enable or disable any channels
3. The settings replicates itself

### 👍 Expected behavior

It should not replicate the setting instead should enable or disable the channel setting for each notification

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/51795573/210951967-61df27f8-8e5d-466e-851c-b6e5f43cbf63.png)

On clicking the toggle for enabling/disabling email channel, it creates a replica of the same setting.

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
Hi @SajMohammed, a small question are you using the cloud or self-hosted version of Novu? If the self-hosted one, what version is it?  Do you have only one notification template available for the in-app? Tried to replicate this locally right now but without success.

**Comment by SajMohammed** [comment]
@scopsy This is for cloud and version 0.10.0
