### ISSUE TITLE
[NV-1442] Centralize `feed` api endpoints and clarify usage

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2437]
## Why?

Today we have a lot of different `feed` endpoints we need to centralize to make sure that it is clear which feed API a user needs to use.

The main confusion today is between:

* /subscribers/:subscriber_id/notifications/feed
* /widgets/notifications/feed
* /feeds

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1442](https://linear.app/novu/issue/NV-1442/centralize-feed-api-endpoints-and-clarify-usage)</sub>

**Comment by oba2311** [comment]
Duplicate

**Comment by scopsy** [comment]
Can we handle this in a middleware? and rely only on the subscriber endpoint?

**Comment by scopsy** [comment]
To consider rename feeds? or use solely feeds for the notification feed behaviour and avoid subscribers and widgets altogether.

**Comment by scopsy** [comment]
Deprecate old ones and keep them for a while\*

**Comment by scopsy** [comment]
Hello!

**Comment by LetItRock** [comment]
these two `/subscribers/:subscriber_id/notifications/feed` and `/widgets/notifications/feed` use the same use-case under the hood… the first one is used in the node package with a regular JWT, the second is used in the notification center component with a subscriber JWT… 

the last one return the feeds…

**Comment by LetItRock** [comment]
@Dima Grossman you mean to move `/widgets` endpoints under the `/subscribers` route and then update the endpoints to allow to work with both Authorization mechanisms?

**Comment by scopsy** [comment]
Yes Exactly
