### ISSUE TITLE
🐛 Bug Report: can't unmount PopoverNotificationCenter component

### ISSUE THREAD

**Issue by arjunbharti** [novuhq/novu#2439]
### 📜 Description

I implemented notification-center popover in react. Whenever I click on a notification, the Popover is not unmounted which means the Popover is never closed and there's no prop that can be used to close the Popover. 

### 👟 Reproduction steps

1. Click on Popover (bell icon or whatever you have there to mount the Popover)
2. Click on any notification
3. The Popover will not be closed

### 👍 Expected behavior

Ideally the Popover should be closed on any notification click. This is common user behaviour seen everywhere on the web.

### 👎 Actual Behavior with Screenshots

can't share prod, we are in stealth. Hope you understand.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by LetItRock** [comment]
hey @arjunbharti! 👋 
Yes, we do provide the `PopoverNotificationCenter` component as uncontrolled, but you don't have to use it. It's quite easy to implement your own version with the behavior you need. 
You have to use instead the `NotificationCenter` component which is a "child" of the popover (it's everything that is inside the popover body). I'm sorry to say but that component is not documented well.

Here is an example:
```
 <YourPopover isOpened={isOpened}>
   <NotificationCenter onNotificationClick={() => setIsOpened(false)} />
</YourPopover>
```

The full interface is:
```
interface INotificationCenterProps {
  onUrlChange?: (url: string) => void;
  onNotificationClick?: (notification: IMessage) => void;
  onUnseenCountChanged?: (unseenCount: number) => void;
  header?: () => JSX.Element;
  footer?: () => JSX.Element;
  emptyState?: () => JSX.Element;
  listItem?: ListItem;
  actionsResultBlock?: (templateIdentifier: string, messageAction: IMessageAction) => JSX.Element;
  colorScheme: ColorScheme;
  theme?: INovuThemeProvider;
  onActionClick?: (templateIdentifier: string, type: ButtonTypeEnum, message: IMessage) => void;
  tabs?: ITab[];
  showUserPreferences?: boolean;
  onTabClick?: (tab: ITab) => void;
}
```

**Comment by arjunbharti** [comment]
hey @LetItRock 👋 
thanks for responding, it worked for me!
