### ISSUE TITLE
[NV-1519] 🚀 Feature: Next.js + Novu Integration Example

### ISSUE THREAD

**Issue by ShaneMaglangit** [novuhq/novu#2447]
### 🔖 Feature description

Add a new project under `/examples` to demonstrate how to use Novu with the latest Next.js (v13). Perhaps, another one strictly with React.

### 🎤 Why is this feature needed ?

To start off, it's something that I believe is just something good to have.

Previously, the Vue and Angular examples only demonstrated the client-side stuffs (notification center components in particular). Next, being as awesome as it is, would allow us to demonstrate how to use the notification center package for React + demonstrate how to use the @novu/node package as well using Next's API routes.

### ✌️ How do you aim to achieve this?

So here's the plan:

- The usual frontend demo on the Notification Center for React (@novu/notification-center).
- An API endpoint `/api/hello` that triggers a notification template.
- The README for the project setup would also have this bonus step on how to set up a Notification Template for he 2nd step (another win 🥳)

### 🔄️ Additional Information

I already have something prepared, here's a screencast on how it works. It's based on the default Next.js 13 starter.

![image](https://user-images.githubusercontent.com/53674742/211199766-74a9ce5d-4114-4ff1-8c40-86459447f575.png)

![Screenshot from 2023-01-08 21-51-57](https://user-images.githubusercontent.com/53674742/211199753-c4b4a1de-b38c-4a2e-b125-fcd629ec1280.png)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1519](https://linear.app/novu/issue/NV-1519/🚀-feature-nextjs-novu-integration-example)</sub>

**Comment by jainpawan21** [comment]
Hi @ShaneMaglangit 
Thanks for your contribution 🙏🏻
@scopsy Shall we create new repo for examples or use main repo only?

**Comment by LetItRock** [comment]
@jainpawan21 @scopsy 
Yeah, we've talked about that with Dima before, but now I've changed my mind :) I see that this folder might grow in the future, so I feel like we should probably separate it. 
It would be super nice if we will have more examples there, like a custom Notification Center, Notifications List, Novu+FCM, etc., these pop up really often in questions.

**Comment by im-perativa** [comment]
+1 for Novu + NextJS + FCM
