### ISSUE TITLE
[NV-1520] 🐛 Bug Report: Alignment issue with the notification center alerts 

### ISSUE THREAD

**Issue by SajMohammed** [novuhq/novu#2449]
### 📜 Description

The alignment of the alerts in-app notification center seems to off if the text length is big

### 👟 Reproduction steps

1. Click on the notification center
2. the alert template should be big as shown in screenshot

### 👍 Expected behavior

The alignment should be proper and the alerts should not overlap the border as in screenshot. Proper justification of the message is needed

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/51795573/211284163-9e3dc39b-4987-4f56-9c21-05ba4f20d737.png)

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1520](https://linear.app/novu/issue/NV-1520/🐛-bug-report-alignment-issue-with-the-notification-center-alerts)</sub>

**Comment by Jonathan4github** [comment]
Hi @LetItRock, @SajMohammed , I will love to work on this issue but I'm having challenge replicating this issue. This is what my dashboard looks like.
![Screenshot from 2023-01-17 13-32-39](https://user-images.githubusercontent.com/31247452/212902155-128d111d-f063-45d1-9008-c343ae37c269.png)

**Comment by Jonathan4github** [comment]
Thanks
