### ISSUE TITLE
🐛 Bug Report: WebSocket connection to self-hosted version failed

### ISSUE THREAD

**Issue by katyaterletskaya** [novuhq/novu#2452]
### 📜 Description

Not showing real-time notification badge. Many unread notifications appear when opening the notification box

### 👟 Reproduction steps

1. Run the self-hosted version of API and WS (v0.10.1)
2. Integrate the widget using the bundled version of the web component and specify the link to self-hosted API and WS

### 👍 Expected behavior

Real-time updating of the badge on notification icon

### 👎 Actual Behavior with Screenshots

Not showing real-time notification badge
The following error in console

<img width="959" alt="Screenshot 2023-01-09 at 18 19 05" src="https://user-images.githubusercontent.com/58933206/211329344-1c482914-4afa-4070-b4fc-55d000aa73ae.png">

### 🤖 Node Version

v16.19.0

### 📃 Provide any additional context for the Bug.

Same issue when using embedded script

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by LetItRock** [comment]
hello @katyaterletskaya! 👋 

I've tried to connect to our cloud services with the widget web component and it works fine.

![Screenshot 2023-01-10 at 11 23 46](https://user-images.githubusercontent.com/2607232/211525823-780ffda7-0bda-48de-9fd4-52df6f393b51.png)

https://user-images.githubusercontent.com/2607232/211526004-d26b5737-f3f4-4cd6-a05d-86900472783f.mov

We've introduced the socket version changes in the release v0.10.0.
This might sound simple, but please make sure that your deployed services are > 0.10.0
