### ISSUE TITLE
[NV-1511] 🐛 Bug Report: cannot update "unseenCount" in react component

### ISSUE THREAD

**Issue by arjunbharti** [novuhq/novu#2457]
### 📜 Description

Whenever a user click on a notification, the `unseenCount` is not updated and I cannot find any prop to update the value of `unseenCount` on clicking any notification. I have to hard-refresh to get the updated values. 
There is nothing specified in the documentation too.

### 👟 Reproduction steps

1. Open the Popover NotificationCenter
2. Click on any notification

### 👍 Expected behavior

The expected behaviour should be to update the `unseenCount` after clicking any notification and if any new notification comes up then update the value of `unseenCount`.

### 👎 Actual Behavior with Screenshots

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1511](https://linear.app/novu/issue/NV-1511/🐛-bug-report-cannot-update-unseencount-in-react-component)</sub>

**Comment by arjunbharti** [comment]
hey @LetItRock 
```
<NotificationCenter
	onNotificationClick={onNotificationClick}
	onActionClick={handlerOnActionClick}
	colorScheme='light'
/>
{({ unseenCount }) => <BellSVG unseenCount={unseenCount} />}
```

I am displaying the count of unseen notifications using `unseenCount` which is coming from `useNotifications()`
Now, the problem is, the `unseenCount` will be updated after the hard-refresh only and there's no method provided in the docs and in the interface to update this `unseenCount` value if a new notification pops-in or the user clicks on an existing notification to update the count of un-seen notifications.

**Comment by BiswaViraj** [comment]
Hello @arjunbharti, 
can you please update the `notification-center` package to the latest version and verify if it works for you now?

I checked using the latest version `v.011.0`, and the unseen_count value is changing accordingly


https://user-images.githubusercontent.com/29251776/215984623-6e74ff11-ced7-4a9a-83b2-6ee8f940a601.mov

**Comment by arjunbharti** [comment]
Hey @BiswaViraj ,
I updated the package and it worked for me. Thanks!
