### ISSUE TITLE
[NV-1512] 🚀 Feature: Filter topic event based on actor

### ISSUE THREAD

**Issue by pxue** [novuhq/novu#2464]
### 🔖 Feature description

I am using topics for post comments.

User X makes a comment, other users (A, B) who've already commented before should get a notification.

I should be able to exclude User X from receiving a notification of their own comment when I trigger notification on the topic.

### 🎤 Why is this feature needed ?

This is the correct behavior for topic based notification, and I would definitely want this for the feature.

### ✌️ How do you aim to achieve this?

I'm not 100% sure if this should be the default behavior.

1. We can add `actor` to `MapTriggerRecipientsCommand`, and filter the actor from `mappedTo` by default.
2. or add an optional configuration on `TriggerEventCommand` to skip actor [in this loop](https://github.com/novuhq/novu/blob/next/apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts#L107) if defined and set to true.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1512](https://linear.app/novu/issue/NV-1512/🚀-feature-filter-topic-event-based-on-actor)</sub>

**Comment by p-fernandez** [comment]
@pxue this is something that we planned to add in the future that we couldn't in the first release of the feature due time constraints. It is also that has been requested by more users.

How I thought we would implement in the future would be in the option one you mention.
https://github.com/novuhq/novu/blob/2295e7f19d14de3c2d670e88575088e8d86dd0e9/apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.use-case.ts#L42

Through a property called maybe `skip` with an interface like this:
```
interface SkipRecipients {
  subscribers: SubscriberId[];
}
```
The reason behind of this is to allow in the future to be able to skip the notification for subscribers based on other criterias we might add in the futuro (subscriber to the topic metadata for example). Think in the schema a BJSON property with metadata for each subscriber related to the topic: https://github.com/novuhq/novu/blob/2295e7f19d14de3c2d670e88575088e8d86dd0e9/libs/dal/src/repositories/topic/topic-subscribers.schema.ts#L40

If you want to submit a PR and work on it, I am more than happy to assist you with the implementation and guide you.

**Comment by scopsy** [comment]
We should probably use actor for this, and do a $ne in the mongo query when fetching subscriber for a group. Should we allow to opt out of this behaviour?

**Comment by p-fernandez** [comment]
> We should probably use actor for this, and do a $ne in the mongo query when fetching subscriber for a group. Should we allow to opt out of this behaviour?

I think it should be driven from the payload request when triggering the event, as a first thought. That would allow flexibility.

**Comment by pxue** [comment]
> We should probably use actor for this, and do a $ne in the mongo query when fetching subscriber for a group. Should we allow to opt out of this behaviour?

Imho this is the best default behavior. In very few case do the actor of an action also wishes to receive notification on the action they just performed. flexibility causes confusion here when it's not what most implementer would expect the behavior to be.

we can use "send me a copy" style option where the user want to opt out the default behavior.
