### ISSUE TITLE
[NV-1513] 🐛 Bug Report: Notification-center adds a lot of unwanted global styles when open

### ISSUE THREAD

**Issue by lu-zen** [novuhq/novu#2469]
### 📜 Description

Some global reset styles are added into <head /> when the notification center is open. This is messing up with my app css.

### 👟 Reproduction steps

1. Add the notification-center to any react project;
2. open in and inspect head style tags

### 👍 Expected behavior

Styling to be encapsulated and not adding any global styles to the dom;

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/11050840/211691052-a784380e-ce95-4936-8d78-67d40cbb93fd.png)

### 🤖 Node Version

18

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1513](https://linear.app/novu/issue/NV-1513/🐛-bug-report-notification-center-adds-a-lot-of-unwanted-global-styles)</sub>

**Comment by jainpawan21** [comment]
@LetItRock Any thoughts?

**Comment by davidemerli** [comment]
Just found out about this too. I was specifically using tailwindcss and all styles get messed up when the popover is opened.

I quickly made a change directly into my compiled node modules and found out that changing `withNormalizeCSS` to false seems to solve the issue.
![image](https://user-images.githubusercontent.com/53702616/212575724-68c1f3ca-4b90-4a34-b0a9-b3d8f6541ee1.png)

I suppose this maps here:
https://github.com/novuhq/novu/blob/73c671246b8c8caab890244584ea6d859c723aa6/packages/notification-center/src/components/notification-center/components/AppContent.tsx#L33

Setting the whole repo up to effectively test this would take me a lot of time, and I have never touched Mantine to be able to understand how this would impact the rest of the code, so I am just reporting this here

**Comment by LetItRock** [comment]
hey @lu-zen @davidemerli @jainpawan21 👋 
Not sure what might be the problem here, but some time ago we did two migrations that might cause this, we migrated to the latest Mantine and replaced `styled-components` with the `@emotion/styled`.
I'll need to dig deeper to understand what is going on.
Thanks for pointing this out!
