### ISSUE TITLE
[NV-1515] 🐛 Bug Report: Multichannel for Push notifications doesn't work for some cases

### ISSUE THREAD

**Issue by serafeimo** [novuhq/novu#2481]
### 📜 Description

Novu allows users to have multiple providers for Push notifications active at the same time (i.e. FCM and APNS). However, this fails in specific cases. While it is supported during the first time someone will configure them, it seems that is fails for future updates.

### 👟 Reproduction steps

1. Connect to both FCM and APNS
2. Check that they are both active
3. Disable FCM
4. Check that only APNS is active
5. Enable FCM again
6. APNS gets disabled

https://user-images.githubusercontent.com/7555930/212017857-9ff0725a-c8ba-41cd-b1c4-f1b01005b031.mov

### 👍 Expected behavior

Multiple providers should be allowed.

### 👎 Actual Behavior with Screenshots

When enabling FCM, APNS gets automatically disabled.

### 🤖 Node Version

ghcr.io/novuhq/novu/api:0.9.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1515](https://linear.app/novu/issue/NV-1515/🐛-bug-report-multichannel-for-push-notifications-doesnt-work-for-some)</sub>

**Comment by serafeimo** [comment]
Hi @LetItRock, thanks for your answer!

Unfortunately, I'm not quite familiar with js and Nodejs, so I'm not able to do that at the moment.

**Comment by tsssdev** [comment]
I can work on this, can you guys assign me?

**Comment by scopsy** [comment]
@tsssdev, @ainouzgali  already started the work on this one 🙏

**Comment by ainouzgali** [comment]
oh, no. I'm sorry @tsssdev! missed your message 🙈

**Comment by tsssdev** [comment]
> oh, no. I'm sorry @tsssdev! missed your message 🙈

Sure No issues @ainouzgali
