### ISSUE TITLE
[NV-1477] 🚧 🚀 Improvement: don't return the integration credentials from the /credentials endpoint

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2484]
### 🔖 Feature description

When querying for the integrations list in the integrations page, don't returned the decrypted credentials when requested. And only return masked values

### 🎤 Why is this feature needed ?

This can help to ensure that credentials won't be accidentally exposed in logging systems and etc...

### ✌️ How do you aim to achieve this?

Add a new masked value returned by the API, and the client could only see the masked value and not the whole content of it. The user could only replace the whole string or just parts of it. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1477](https://linear.app/novu/issue/NV-1477/🚀-improvement-dont-return-the-integration-credentials-from-the)</sub>

**Comment by tsssdev** [comment]
I can work on this, please assign me

**Comment by scopsy** [comment]
@oba2311 this one requires design since we need to change the component and the flow of the update:

* User can only see the the value cannot be viewed
* we should somehow add a button to allow modify this value

So we would need to have some UI for this.

**Comment by oba2311** [comment]
Sure let's add this to our grooming backlog @nikolay .

@scopsy I have no idea what this means "User can only see the the value cannot be viewed" .

**Comment by scopsy** [comment]
We need to create a controller, that will show the user masked value (we can show last 4 digits for better UX, and if he wants to join this he needs to press a button to allow him to modify this value.

**Comment by m-salman-afzal** [comment]
Is this issue up for grabs? I'd like to take a look into it.
