### ISSUE TITLE
[NV-1508] 🐛 Bug Report: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by satnamaix** [novuhq/novu#2486]
### 📜 Description

issue with api service when build with  docker image 
followed  below steps ad facing issue with api application 
# Get the code
git clone --depth 1 https://github.com/novuhq/novu
# Go to the docker folder
cd novu/docker
# Copy the example env file
cp .env.example ./local/deployment/.env
# Start Novu
docker-compose -f ./local/deployment/docker-compose.yml up

### 👟 Reproduction steps

# Get the code
git clone --depth 1 https://github.com/novuhq/novu
# Go to the docker folder
cd novu/docker
# Copy the example env file
cp .env.example ./local/deployment/.env
# Start Novu
docker-compose -f ./local/deployment/docker-compose.yml up

api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

### 👍 Expected behavior

it should connect with redis container as per .env file 

### 👎 Actual Behavior with Screenshots

api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
api        | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
api        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1508](https://linear.app/novu/issue/NV-1508/🐛-bug-report-[ioredis]-unhandled-error-event-error-connect)</sub>

**Comment by titenkov** [comment]
I've created a fix for it - https://github.com/novuhq/novu/pull/2532. However, I'm not sure, if it's an optimal one - it solves the issue, but it might be a good improvement not to rely on `REDIS_CACHE_SERVICE_HOST`, but rather have explicit `REDIS_CACHE_SERVICE_ENABLED` env variable 🤔

**Comment by Orteko** [comment]
For reference of those trying to get v0.10.1 running, the variables to populate in that version are `REDIS_CACHE_HOST `and `REDIS_CACHE_PORT`.

**Comment by Orteko** [comment]
@titenkov in my setup, i'm seeing other issues which look like they are relating to default config which might need attention in this or another issue:

![image](https://user-images.githubusercontent.com/990906/213688008-4c92c1ca-11a5-4d08-89b8-fa13f1c69c7a.png)

Directly after a brand new setup, i'm seeing requests out to third party APIs that have not been configured.

I'm not sure if this is legitimate data - however there is what appears to be a production DSN hard-coded in `libs/embed/src/shared/resources.js`:

![image](https://user-images.githubusercontent.com/990906/213688385-7b1f5ce0-ccab-4133-8252-24c55783894a.png)

Unsure where the 2b5160da86384949be4cc66679c54e79 is coming from in my screenshot unless it's autogenerated somehow?

Happy to open up a ticket for these if required - I don't see anything obvious that relates to this.

**Comment by scopsy** [comment]
@Orteko, very strange behavior that defiently shouldn't happen. Seems like the it shouldn't be initialized. The error for sentry most likely not coming from the embed snippet. But will investigate this further now.

**Comment by scopsy** [comment]
@Orteko I think i found the problem, the previous build was adding the sentry configuration from the deployment to the docker build aswell. Submitted a PR and will create a hotfix soon. Thank you for submitting the information!

**Comment by Cliftonz** [comment]
@scopsy this has been reported again in discord.
https://discord.com/channels/895029566685462578/1066744478880235730

**Comment by scopsy** [comment]
@Cliftonz This fix is available on next branch, will be deployed as part of the next minor version this week.

**Comment by Orteko** [comment]
> @Orteko I think i found the problem, the previous build was adding the sentry configuration from the deployment to the docker build aswell. Submitted a PR and will create a hotfix soon. Thank you for submitting the information!

Awesome - thanks for looking into it.
