### ISSUE TITLE
[NV-1509] 🚀 Feature: Add locale property to Subscriber model

### ISSUE THREAD

**Issue by katyaterletskaya** [novuhq/novu#2496]
### 🔖 Feature description

Currently, there is no way to translate notification templates to suit business needs. I'm looking for any opportunity to provide this until it's implemented. And the only way I can see is to add new locale property to the subscriber model and reuse it in the templates

### 🎤 Why is this feature needed ?

This can be used as a workaround for localization until it's implemented. It also looks like a good starting point for this task

### ✌️ How do you aim to achieve this?

Adding an additional property to the subscriber model

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1509](https://linear.app/novu/issue/NV-1509/🚀-feature-add-locale-property-to-subscriber-model)</sub>

**Comment by Swahjak** [comment]
While I think this is a great feature, wouldn't you also be able to achieve this by sending a locale with every payload? Obviously requires more backend work, so not ideal. But a workaround none the less.

**Comment by scopsy** [comment]
It could be indeed achieved like you suggested as a workaround. But I think it makes sense for Novu to have a first class citizen and an infra way of managing locale.

**Comment by katyaterletskaya** [comment]
Hi @Swahjak 😊 From my point of view 'locale' is semantically related to subscriber rather than payload. Otherwise, we can store all the subscriber-related data in the payload. 
Of course, I can use this approach as a workaround, but I guess this pr is a good starting point for implementing localization 🙌
