### ISSUE TITLE
[NV-1506] 🐛 Bug Report: CLI registration hangs

### ISSUE THREAD

**Issue by digitalbanana** [novuhq/novu#2504]
### 📜 Description

when i try the command sown in the getting started section => ' npx novu init'

### 👟 Reproduction steps

1. run ` npx novu init`

### 👍 Expected behavior

not - i imagine there would be more interactive questions?

### 👎 Actual Behavior with Screenshots

cli times out after \~5s
(two invocations/attempts shown)

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/f8d254f3-e636-4f33-8e3f-3da245e64ddd/0f940e47-cbd0-41ed-8396-f57d3ef480fe)

### 🤖 Node Version

16\.13.1

### 👀 Have you spent some time to check if this bug has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1506](https://linear.app/novu/issue/NV-1506/🐛-bug-report-cli-registration-hangs)</sub>

**Comment by jainpawan21** [comment]
Can you please explain this issue a bit more?

**Comment by digitalbanana** [comment]
not sure what else to say... i am using windows, when i try to run `npx novu init` - the output is shown (see screenshot) - nothing gets generated (eg no files/apps etc)? let me know what else you need

**Comment by scopsy** [comment]
Hi @digitalbanana, could you please try running `npx novu@latest init`? 
From the screenshot I see that there are no error thrown right? In any case, you can visit https://web.novu.co directly to create an account or visit the self-hosting docs: https://docs.novu.co/overview/docker-deploy

**Comment by scopsy** [comment]
@digitalbanana and when this screen is viewable, are you able to type the application name and click on Enter for next question?

**Comment by scopsy** [comment]
Closing this one as we were not unable to replicate this behaviour from all tests in similar environment. @digitalbanana if you still encounter this after doing `npx novu@latest init` feel free to re open this issue 🙏

**Comment by melon-husk** [comment]
@scopsy I'm facing the same issue, when I run `npx novu@latest init`, it outputs this and exits before I could enter the name,
![image](https://user-images.githubusercontent.com/30780724/233811409-9cb8fd14-58e2-4638-bd27-ec31c42e409d.png)
I'm on Node v18.16.0.

**Comment by scopsy** [comment]
@melon-husk looks like something that might be related to Powershell. I'll try to get a hand at a windows machine, so I can try to replicate this locally somehow so we can debug it.

**Comment by melon-husk** [comment]
@scopsy I tried the same command on one of my ubuntu vms. same thing happened,
![image](https://user-images.githubusercontent.com/30780724/233842870-75dd520f-37a2-48db-be42-71c3df2629c6.png)
