### ISSUE TITLE
[NV-1510] 🚀 Feature: Global Refactoring

### ISSUE THREAD

**Issue by NarHakobyan** [novuhq/novu#2507]
### 🔖 Feature description

Congratulations on topics 🤩, but I think it would be better to have builder pattern under the hood of topics and other API's, and use push and pop of Mongodb instead of fully updating. If you want to add a new user to a topic, you don't have to send the rest of the data constantly. Also it will reduce load to the API.

before:
```typescript
const response = await novu.topics.addSubscribers(topicKey, {
  subscribers: ['subscriber-id-1', 'subscriber-id-2', ...],
});
``` 
after:
```typescript
const responseAdd = await novu.topics.get(topicKey).subscribers.add('subscriber-id-1');
const responseRemove = await novu.topics.get(topicKey).subscribers.remove('subscriber-id-1');
const responseList = await novu.topics.get(topicKey).subscribers.list();
``` 

### 🎤 Why is this feature needed ?

if User join's to the topic it's better to just add the user, instead of retrieve all the data and send it back with additional user.
Reduce API load.
Performance improvements.

### ✌️ How do you aim to achieve this?

using $push and $pop of the Mongodb.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1510](https://linear.app/novu/issue/NV-1510/🚀-feature-global-refactoring)</sub>

**Comment by p-fernandez** [comment]
@NarHakobyan thank you for your suggestion.
What I am struggling to understand from your proposal is this line __you don't have to send the rest of the data constantly__. What do you mean by that? What's is the API call you think we are sending the data constantly?

**Comment by NarHakobyan** [comment]
@p-fernandez Hey, let's imagine we have users under company and we want to send notification to them all, so we can create topic and add these users' subscribe it's there. So we have two scenarios when new user joins to the company or user leaves.

1. if user (subscriber-id-1) leaves the company we must retrieve all the current subscribers and send to novu without new member

```
const response = await novu.topics.addSubscribers(topicKey, {
  subscribers: ['subscriber-id-2', ..., 'subscriber-id-100'],
});
```

2. if new user (subscriber-id-101) joins to the company we must retrieve all the current subscribers and send to novu with new member

```
const response = await novu.topics.addSubscribers(topicKey, {
  subscribers: ['subscriber-id-1', ..., 'subscriber-id-100', 'subscriber-id-101'],
});
```

`What do you mean by that? What's is the API call you have spotted we are sending the data constantly?`
for example subscribe joins to the topic or firebase token added to the subscriber.
