### ISSUE TITLE
[NV-1553] 🚀 Feature: Java SDK 

### ISSUE THREAD

**Issue by katyaterletskaya** [novuhq/novu#2541]
### 🔖 Feature description

A java package for interacting with the novu api

### 🎤 Why is this feature needed ?

This package will provide convenient access to the novu API from applications written in Java

### ✌️ How do you aim to achieve this?

Write a project in Java and set up publishing artifacts to maven central

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1553](https://linear.app/novu/issue/NV-1553/🚀-feature-java-sdk)</sub>

**Comment by scopsy** [comment]
@oba2311 i'm putting this back on the backlog since we are evaluating right now an automated tool for generating SDK's. To avoid duplicate work. Will make myself a reminder to review this one in a couple of weeks. CC @Cliftonz

**Comment by SebastianStehle** [comment]
Which tool do you use? Is there something which puts out SDKs for all languages?

**Comment by scopsy** [comment]
@SebastianStehle evaluation https://www.konfigthis.com/ for this. They use https://openapi-generator.tech/ actually to make the generation itself. Not sure yet if we will use the open API generator directly or konfigthis as a middleware

**Comment by SebastianStehle** [comment]
Thanks. I had a look a while ago and the generated .NET client waws really outdated. Cannot speak for other languages.

**Comment by dsinghvi** [comment]
Hey @scopsy -- 

Hope it's okay to barge in on this thread. My team works on [Fern](https://www.buildwithfern.com/) and we can help auto-generate SDKs for REST APIs. You can start with OpenAPI, or for better results, a [Fern Definition](https://docs.buildwithfern.com/definition). 

We are currently in YCombinator and also [open source](https://github.com/fern-api/fern). 

Here's an example of a Java SDK that we've generated:
- https://github.com/ravenappdev/raven-java

Would love to chat! [Here's](https://calendly.com/deep-singhvi/30min?month=2023-02) my calendly if you're up for it.
