### ISSUE TITLE
[NV-1561] 🐛 Bug Report: Duplicate emails when using digest

### ISSUE THREAD

**Issue by guy-wal** [novuhq/novu#2569]
### 📜 Description

When more than 1 event is triggered in the same second (not exactly same timestamp) and there is a digest, sometimes I receive 2 or more emails for the same digest (events are in different order).

![image](https://user-images.githubusercontent.com/95572228/213866916-6ed7502d-f130-44fd-85fd-2ed41937d1e6.png)

### 👟 Reproduction steps

1. create template with digest
2. trigger more than 1 event to that template in less than 1 second

### 👍 Expected behavior

send only 1 notification

### 👎 Actual Behavior with Screenshots

sends more than 1 email, with different event order.

![image](https://user-images.githubusercontent.com/95572228/213867191-711202bb-a5d0-473c-9fae-ac4a383bd711.png)

![image](https://user-images.githubusercontent.com/95572228/213867197-f34a9b17-634c-4c50-964c-c3dfcaa628f1.png)

### 🤖 Node Version

v16.13.1

### 📃 Provide any additional context for the Bug.

- The digest time is 5 minutes but it happened also when tested on other times.
- When triggering the event with novu sdk we send the recipient where the email and subscriberId are both the email address.
- We trigger 1 event for each recipient separately as we though it might fix this bug but it didn't. before that we triggered once with a recipient list.
- currently running our own hosting of Novu version 0.9.0 but this also happened when we used cloud hosted novu version 0.10.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1561](https://linear.app/novu/issue/NV-1561/🐛-bug-report-duplicate-emails-when-using-digest)</sub>

**Comment by scopsy** [comment]
Seems like a race condition when processing the jobs. Thanks for the report, will take a closer look at this. 🙏

**Comment by p-fernandez** [comment]
@guy-wal 2 quick questions, regarding this point:

> We trigger 1 event for each recipient separately as we though it might fix this bug but it didn't. before that we triggered once with a recipient list.

Are you triggering the notification for more than one different subscriberId? 
Where in the workflow are you locating the Digest step? Before or after the email step?

**Comment by guy-wal** [comment]
> @guy-wal 2 quick questions, regarding this point:
> 
> > We trigger 1 event for each recipient separately as we though it might fix this bug but it didn't. before that we triggered once with a recipient list.
> 
> Are you triggering the notification for more than one different subscriberId? Where in the workflow are you locating the Digest step? Before or after the email step?

We are sending a separate trigger for each recipient. For example if we have 2 email addresses to send to, we trigger twice with the same payload and different recipient data. We send the subscriberId value the same as the email address.

the digest is before the email template in the workflow

**Comment by p-fernandez** [comment]
@guy-wal we have added some fixes for the Digest flow in our latest release (v.0.12.0; also available in `next` branch). If you can, please try any of those and keep us updated if you face the same issue again. 🙏🏻
