### ISSUE TITLE
[NV-1574] 🤔 Question: Novu and Azure CosmosDB

### ISSUE THREAD

**Issue by titenkov** [novuhq/novu#2589]
### 📜 Description

Novu is not working with MongoDB run in Azure (CosmosDB)

### 👟 Reproduction steps

Run Novu in containers and specify the external DB run in Azure

### 👍 Expected behavior

Officially, it's not mentioned as supported. However, I would like to know if I can get help here because I'm struggling to make it work with CosmosDB. As engineers, who created Novu, you might have a better context and point me in the right direction. It seems to be related to the [indexing mechanism difference between native MongoDB and CosmosDB](https://stackoverflow.com/questions/56988743/using-the-sort-cursor-method-without-the-default-indexing-policy-in-azure-cosm). Is there anything, what can be improved on the Novu side to make it run there?

### 👎 Actual Behavior with Screenshots

`novu-api-5b987878c-d6n29 novu-api [Nest] 18  - 01/23/2023, 2:15:17 PM   ERROR [ExceptionsHandler] Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 01f9e57a-68c5-404c-8ed6-875a6b25767e; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 01f9e57a-68c5-404c-8ed6-875a6b25767e; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 01f9e57a-68c5-404c-8ed6-875a6b25767e; Reason: (Message: {"Errors":["The index path corresponding to the specified order-by item is excluded."]}`

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/958581/214301011-b59ba651-13dd-4d21-bd1b-e21f84e5490f.png">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1574](https://linear.app/novu/issue/NV-1574/🤔-question-novu-and-azure-cosmosdb)</sub>

**Comment by LetItRock** [comment]
hey @titenkov! 👋 
I'm not sure about the Azure CosmosDB but some of our community members used AWS DocumentDB. 
I know these are different cloud providers and services but might be worth checking this thread: https://discord.com/channels/895029566685462578/1040037824717668423

**Comment by scopsy** [comment]
@titenkov  Officially we recommend using MongoDB since looks like CosmoDB doesn't have a full API compatibility, I'm afraid using it can introduce unforeseen bugs which will be hard for us to maintain on the long term. 

Let me if we can close those one 🙏
