### ISSUE TITLE
[NV-1586] 🐛 Bug Report: Novu user remove automatically on self hosted version 

### ISSUE THREAD

**Issue by JayKaneriya11** [novuhq/novu#2620]
### 📜 Description

We are currently using latest version of the novu v0.10.1 and testing it with our application. We deployed novu's latest using docker on our server. We created a user inside it and setup our mail and notification templates. We already had previous version of novu and its working fine but after updating to latest version we lost our user three times in two days. When we try to login on our self hosted novu with right credentials we are getting error of invalid username or password. Novu didn't able to recognise our user and we need to re create user and re configure our setup. We didn't see any errors in our docker log. 

### 👟 Reproduction steps

1. Upgrade version to latest in self hosted env
2. Create user and set up notification template
3. Didn't able to logged in and user deleted automatically and need to create that same user.

### 👍 Expected behavior

User should not be deleted automatically

### 👎 Actual Behavior with Screenshots

User deleted without any actions

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1586](https://linear.app/novu/issue/NV-1586/🐛-bug-report-novu-user-remove-automatically-on-self-hosted-version)</sub>

**Comment by scopsy** [comment]
@JayKaneriya11 the only reason this might be happening is because you are not persisting your MongoDB instance. How are you managing the database deployment? Are you deploying in on k8s or using amanged service such as mongo db atlas?

**Comment by JayKaneriya11** [comment]
@scopsy We are managing entire novu infra using docker containers. we are using this [docker compose](https://github.com/novuhq/novu/blob/next/docker/local/deployment/docker-compose.yml) file for deployment. I thought this issue is might related to this [issue](https://github.com/novuhq/novu/issues/2486)

**Comment by scopsy** [comment]
@JayKaneriya11 I don't believe this is related. The database disk should be persisted from your end between putting services down. Checkout the volumes part here: https://stackoverflow.com/questions/44888292/saving-mongodb-on-volume-using-docker-compose or here: https://betterprogramming.pub/persistent-databases-using-dockers-volumes-and-mongodb-9ac284c25b39

**Comment by LetItRock** [comment]
@scopsy @JayKaneriya11 
closing this because the DB persistence should be implemented by you and Dima pointed how to do that

**Comment by mosamlife** [comment]
@scopsy  @LetItRock  so you are saying that I need to persist my MongoDB data by my self? because we are using the same docker-compose file that novu officially provide.

**Comment by scopsy** [comment]
Hi @mosamlife so the provider docker has a persistent volume that should take of that, but without knowing your deployment, it's hard to tell why it was removed. 

For production deployment, we would suggest deploying a higher availability setup with 3 node replica set of MongoDB. (using either MongoDB atlas, or running on your own cluster)

**Comment by mosamlife** [comment]
@scopsy  Thanks for the info.! so what do you suggest right now we are using normal docker deployment setup in digital ocean server. if you have cluster or k8 cluster compose file then you can provide and I can check with my AWS server.

**Comment by scopsy** [comment]
Unfortunately, I don't have a k8 file since we are not using Kubernetes :( You can try using these community contributed files: [https://github.com/novuhq/novu/tree/next/docker/kubernetes/kustomize](https://github.com/novuhq/novu/tree/next/docker/kubernetes/kustomize) but I'm not 100% sure on how to run them.

**Comment by mosamlife** [comment]
@scopsy I also don't want to use kubernets since my team is not familiar with this. so, what do you suggest for docker production deployment?

**Comment by scopsy** [comment]
For production would suggest either kubernetes or a manged service such as AWS ECS or similar… The goal is to be able to scale the system horizontally when needed. Otherwise, you can try setting up a persistent database with Mongo Atlas, or self-hosting yourself on AWS and just run the API and other services docker images manually. Depending on your scale it might work for you, but wouldn't suggest this on the long run tho.

**Comment by mosamlife** [comment]
yes, do you have any guide for aws ecs? or just we need to use that docker-compose file with aws ecs?

**Comment by scopsy** [comment]
@mosamlife unfortunately we don't have any official guides on it, you can just follow the AWS documentation for that and use the docker images of Novu 🙏

**Comment by NelsonArguera12** [comment]
I'm having this issue myself is there anyway I can fix it?
