### ISSUE TITLE
[NV-1593] 🚀 Feature: sending daily digest at a fixed time

### ISSUE THREAD

**Issue by MerlijnElderhuis** [novuhq/novu#2628]
### 🔖 Feature description

A use case I'm interested in is sending users a daily digest email, containing the notifications of the previous day at a specific time of day.

### 🎤 Why is this feature needed ?

In my specific use case, we are creating a task system. In out system, several events would happen (colleague assigns user to a task, a task the user is subscribed to gets completed, etc.) that can trigger notifications. A daily digest like this would allow users to get an email containing an overview of things that happened the day before, so they can quickly check whether they missed anything, and see what they need to do next. 

### ✌️ How do you aim to achieve this?

As I understand it, the current digest system starts "collecting" notifications when the first notification happens, and sends the notification after a configurable amount of hours/days. 

In the use case I describe, the system would start "collecting" notifications based on an interval in a schedule (cron job would be perfect for this I think). At the next interval, the collected notifications get sent to the user (just like in the digest), and the collected notifications get reset. At which point the system will start collecting for the next interval.

Concretely, an example of some cycles would look like this:
Let's assume we have configured the interval to be daily, and the daily digest to be sent at 8:00.

- system starts collecting notifications on monday at 8:00
- on monday. notifications A and B come in at 13:00 and at 15:00
- on tuesday 8:00, the daily digest of notifications A and B is sent to the user, the system starts collecting again
- on tuesday, no notifications happen
- on wednesday 8:00, no digest is sent, since no notifications happened.  The system starts collecting again
- on wednesday, nofications C and D come in at 12:00 and 16:00
- on thursday 8:00 the daily digest of notifications C and D is sent to the user, the system starts collecting again
- ...

### 🔄️ Additional Information

From what I can gather from the docs, a fixed time delay (collect notifications for n minutes/hours, send afterwards), and fixed date (send at configured datetime x) are supported, but the use case I describe here is not supported.

I asked about this functionality on the discord in [this](https://discord.com/channels/895029566685462578/1064574173915136012) thread, @nevo-david (I hope I'm tagging the correct user here) mentioned it is not supported yet.

Ideas for later versions of this feature:
- the schedule for the digest (daily/weekly) can be configured by the user
- we can configure this feature to filter out notifications that have already been read by the user

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1593](https://linear.app/novu/issue/NV-1593/🚀-feature-sending-daily-digest-at-a-fixed-time)</sub>

**Comment by oba2311** [comment]
This was asked by several clients as well so would be good to get it done 💪

**Comment by LetItRock** [comment]
@oba2311 do we have a ticket for that already then? is this one a duplicate?

**Comment by oba2311** [comment]
@LetItRock  no, we should work as this description as the basis for the ticket.  I pinged the OP on discord so you can chat with them further if you want to.

We can sync on details - ping me.

**Comment by oba2311** [comment]
(i.e. there are details we need to figure out together)

**Comment by scopsy** [comment]
@oba2311 had reviewed this with @BiswaViraj in the morning, this is a very big task. This should be handled as part of a cycle and have the proper designs available for it as it change the template editor and requires a lot of Back end work to actually make this happen. I'm putting it back to the backlog as there is no way we will be able close this in the period of time we have left.

**Comment by p-fernandez** [comment]
Besides what @scopsy said, we need to fix earlier the buggy behaviour of digest so we can have full confidence in this feature implementation. Working on it.

**Comment by oba2311** [comment]
Thanks @scopsy  @BiswaViraj  @p-fernandez .

1 - added Pablo's issue as blocking  - let's use those Linear features when needed.

2 - I'll move this to the next cycle, under the assumption that Pablo will finish by then (this week + if needed cooldown afterwards).

**Comment by scopsy** [comment]
@MerlijnElderhuis as an update we have already started working on this functionality internally and a first version should be available in the upcoming version 🙏
