### ISSUE TITLE
[NV-1625] 🚀 Feature: Allow Subscriber to disable all Notifications from a Channel

### ISSUE THREAD

**Issue by ryshu** [novuhq/novu#2666]
### 🔖 Feature description

Possibility for a Subscriber to completely disable all Notifications from a Channel, regardless of Topic or Template.

### 🎤 Why is this feature needed ?

In our use case, we want to enable all the channels for our users because they can have access to these different channels without wanting to receive notifications on each.

For example, we define in the Template that the Notification is sent on the Discord, Slack, and MS Teams Channels. At this point, the Subscriber can activate MS Teams, Slack, or Discord and disables the others. He will then receive all his notifications through this media and not the 2 others.

### ✌️ How do you aim to achieve this?

The Subscriber will not receive any notification from the Channel if he/she disables the Channel in his/her preferences.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1625](https://linear.app/novu/issue/NV-1625/🚀-feature-allow-subscriber-to-disable-all-notifications-from-a)</sub>

**Comment by LetItRock** [comment]
@scopsy @oba2311 this one was asked many times

**Comment by oba2311** [comment]
Thanks OP for raising this issue and thanks @LetItRock .

I'll look further into the design needed here in the next couple of weeks and will schedule this for April or May's cycle. Keep an eye for this to roll out then 💪.

**Comment by jainpawan21** [comment]
Hi @ryshu 
We recently added global subscriber preference
https://docs.novu.co/subscribers/preferences#update-subscriber-global-preference

Using this, subscriber can disable particular channel at global level.
