### ISSUE TITLE
[NV-1629] 🐛 Bug Report: @novu/notification-center missing react-query dependency

### ISSUE THREAD

**Issue by lu-zen** [novuhq/novu#2673]
### 📜 Description

I'm using the react component and it throws an error, it's missing `react-query`;
```js
Error: Cannot find module 'react-query'
Require stack:
- /.../build/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at node_modules/@novu/notification-center/dist/cjs/index.js (/.../build/index.js:26:35)
```

### 👟 Reproduction steps

1. Install `@novu/notification-center` and try to use the react popover component;

### 👍 Expected behavior

It should work without asking for a peer dependency to be installed;

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/11050840/216479732-5b051b50-9bc8-4846-b8d2-a58fc36cf644.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1629](https://linear.app/novu/issue/NV-1629/🐛-bug-report-novunotification-center-missing-react-query-dependency)</sub>

**Comment by LetItRock** [comment]
hi @lu-zen! 👋 
The `notification-center` package has a regular dependency on the `@tanstack/react-query` so the imports are from that package. So you're probably using the old version `<=0.10.3` which should install `react-query`, but it seems like in your `node_modules` it couldn't find it. 
I've checked the latest version `0.11.0` and `0.10.3` and both working fine. 
Could you try to reinstall all the `node_modules` deps, by removing that folder and running the install command?

**Comment by lu-zen** [comment]
@LetItRock yep I reinstalled and it's working fine, thank!
