### ISSUE TITLE
[NV-1631] 🐛 Bug Report: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by timurchikk** [novuhq/novu#2675]
### 📜 Description

i have a mongo installed, and i tried with MONGO_URL=mongodb://mongodb/novu-db, same error
i haven't did any changes, docker-compose files and .env 's are default
.
.
.
ws         | [Nest] 537   - 02/04/2023, 11:28:41 AM   [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:27017 +30092ms
ws         | MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
ws         |     at NativeConnection.Connection.openUri (/usr/src/app/node_modules/.pnpm/mongoose@6.4.6/node_modules/mongoose/lib/connection.js:819:32)
ws         |     at /usr/src/app/node_modules/.pnpm/mongoose@6.4.6/node_modules/mongoose/lib/index.js:379:10
ws         |     at /usr/src/app/node_modules/.pnpm/mongoose@6.4.6/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
ws         |     at new Promise (<anonymous>)
ws         |     at promiseOrCallback (/usr/src/app/node_modules/.pnpm/mongoose@6.4.6/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
ws         |     at Mongoose._promiseOrCallback (/usr/src/app/node_modules/.pnpm/mongoose@6.4.6/node_modules/mongoose/lib/index.js:1224:10)
ws         |     at Mongoose.connect (/usr/src/app/node_modules/.pnpm/mongoose@6.4.6/node_modules/mongoose/lib/index.js:378:20)
ws         |     at DalService.<anonymous> (/usr/src/app/libs/dal/dist/dal.service.js:21:45)
ws         |     at Generator.next (<anonymous>)
ws         |     at /usr/src/app/libs/dal/dist/dal.service.js:8:71
ws         |     at new Promise (<anonymous>)
ws         |     at __awaiter (/usr/src/app/libs/dal/dist/dal.service.js:4:12)
ws         |     at DalService.connect (/usr/src/app/libs/dal/dist/dal.service.js:16:16)
ws         |     at /usr/src/app/apps/ws/src/shared/shared.module.ts:44:24
ws         |     at Generator.next (<anonymous>)
ws         |     at /usr/src/app/apps/ws/dist/src/shared/shared.module.js:14:71
ws         | 2023-02-04T11:28:41: PM2 log: App [main:0] exited with code [1] via signal [SIGINT]
ws         | 2023-02-04T11:28:41: PM2 log: App [main:0] starting in -fork mode-
ws         | 2023-02-04T11:28:41: PM2 log: App [main:0] online

### 👟 Reproduction steps

docker-compose -f ./local/deployment/docker-compose.yml up

### 👍 Expected behavior

i have no idea

### 👎 Actual Behavior with Screenshots

mongo is not connecting to any services

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1631](https://linear.app/novu/issue/NV-1631/🐛-bug-report-mongooseserverselectionerror-connect-econnrefused)</sub>

**Comment by scopsy** [comment]
@timurchikk is it possible that your mongoose image some reason failed to start?

**Comment by Ajaiswal2610** [comment]
i am getting the same issue !!! HELP ME

**Comment by scopsy** [comment]
@Ajaiswal2610 what are the steps you have followed until encountered this error? This will help us identify the problem

**Comment by Ajaiswal2610** [comment]
I'm trying to deploy the novu api service on google cloud run as a
container and passing a hosted mongodb url as environment variable

**Comment by timurchikk** [comment]
> 

yes, im using mac m2, thats why. i've changed mongo version in docker-compose.yml and all ok )
