### ISSUE TITLE
[NV-1636] ✨ Polishing: New template variable properties are reset when saving workflow

### ISSUE THREAD

**Issue by tomdaniel-it** [novuhq/novu#2684]
### 📜 Description

When creating a new notification template and immediately adding an In-App step, then save the step and workflow, the variable config (default value & whether required) is reset to the default values (required false and default value empty).

### 👟 Reproduction steps

1. Create new notification template
2. Open notification template
3. In workflow editor, add In-App step
4. Click to edit In-App template
5. Fill in information of template
    5.1. Url: /test
    5.2. Notification content: {{test-a}}{{test-b}}
    5.3. test-a variable -> set "is required" true
    5.4. test-b variable -> set default value "test"
6. Save by clicking Update
7. Click 'Go Back'
8. In workflow editor, click 'Update'
9. Go back into editor of In-App step template (also happens when refreshing page first)
    -> Notice how the "is required" and default value are reset

### 👍 Expected behavior

Remember the variable configuration during Updating

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1636](https://linear.app/novu/issue/NV-1636/✨-polishing-new-template-variable-properties-are-reset-when-saving)</sub>

**Comment by ainouzgali** [comment]
I'm pretty sure @LetItRock 's work [here](https://github.com/novuhq/novu/pull/2674) will fix it. Note to make sure.

**Comment by LetItRock** [comment]
@tomdaniel-it @ainouzgali 
Confirming, this gonna be fixed in the PR: #2674. Closing for now.
