### ISSUE TITLE
[NV-1640] Email provider details are viewable

### ISSUE THREAD

**Issue by Niba-nazar** [novuhq/novu#2692]
Hi,

I just want to know if it possible to to hide the email providers access key ID and secret access key? I could see those details can be taken even after the integration. Any security breaches will it result in? 

If somebody entered this panel with my login information, they could quickly obtain the access token and password from the integration store because they are both shown.
It would be much better if, after adding the information, at least the password session could not be viewed.

Anyone can quickly read the ID and secret access key by clicking on that eye symbol. 

![image](https://user-images.githubusercontent.com/114569256/217247529-e21bfa3e-4df0-49d4-8f29-b228b2ec7c85.png)

<sub>[NV-1640](https://linear.app/novu/issue/NV-1640/email-provider-details-are-viewable)</sub>

**Comment by scopsy** [comment]
Hi @Niba-nazar this is related to: https://github.com/novuhq/novu/issues/2484 
So will close this one as duplicate do we can track all progress there 🙏
