### ISSUE TITLE
[NV-1641] 🐛 Bug Report: Digest key does not allow specifying a nested payload key

### ISSUE THREAD

**Issue by spakanati** [novuhq/novu#2697]
### 📜 Description

When creating a digest, digest key doesn't work when you set the digestKey to `object.name` for example for a payload like `{ "object": {"name": "test" }}`.

Other parts of Novu do allow access to a nested payload key so this seems like it should be supported.

Also, if Novu does not find the digest key (like currently if you use a nested key), instead of falling back to simply using the subscriberId as a default, the digest will be turned off entirely.

### 👟 Reproduction steps

Create a digest and specify a nested payload key as the digest key.

### 👍 Expected behavior

It should accept a nested payload key as a digest key

### 👎 Actual Behavior with Screenshots

It allows entering "object.name" for example but the digest turns off.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1641](https://linear.app/novu/issue/NV-1641/🐛-bug-report-digest-key-does-not-allow-specifying-a-nested-payload)</sub>

**Comment by tsssdev** [comment]
Found the problem, in ShouldAddDigestJob second digest job is skipped , because are not including digest key while getting the delayedDigest object, it is returning the first digest object, fix is to include digest key in this query also.. please assign me, I can fix it.

**Comment by scopsy** [comment]
@p-fernandez FYI seems like @tsssdev is on it 🎉

**Comment by p-fernandez** [comment]
> @p-fernandez FYI seems like @tsssdev is on it 🎉

But in the fixes I am doing that use case is going to disappear.
@tsssdev do a PR but I will probably integrate it in the work I am doing here: https://github.com/novuhq/novu/pull/2719 and credit you as co-author, if that's is right for you.

**Comment by tsssdev** [comment]
> > @p-fernandez FYI seems like @tsssdev is on it 🎉
> 
> But in the fixes I am doing that use case is going to disappear. @tsssdev do a PR but I will probably integrate it in the work I am doing here: #2719 and credit you as co-author, if that's is right for you.

Sure @p-fernandez , but the issues reported here are not related to lock, we have bugs in the code, I am going to create soon, so you can review.

**Comment by p-fernandez** [comment]
> > > @p-fernandez FYI seems like @tsssdev is on it 🎉
> > 
> > 
> > But in the fixes I am doing that use case is going to disappear. @tsssdev do a PR but I will probably integrate it in the work I am doing here: #2719 and credit you as co-author, if that's is right for you.
> 
> Sure @p-fernandez , but the issues reported here are not related to lock, we have bugs in the code, I am going to create PR soon, so you can review.

I just wanted to align as we might have some conflicts due I am removing code you are fixing so I will need to move your improvements into the new code. 👍🏻
