### ISSUE TITLE
[NV-1642] 🐛 Bug Report: Digests with different values for digest key are combined together

### ISSUE THREAD

**Issue by spakanati** [novuhq/novu#2698]
### 📜 Description

With digest enabled, when triggering messages with payloads with different values for the same digest key, the digests are incorrectly merged.

### 👟 Reproduction steps

1. Create a workflow with a digest (can use 30 seconds as backoff and interval values). 
2. Set the digest key to "test"
3. Trigger multiple messages with payloads `{"test": "val1"}` and then `{"test": "val2"}` 
4. Digest will be created with the first value but then messages for the 2nd value will be combined and the activity feed will show "digest combined with existing digest"

### 👍 Expected behavior

When there is a different value for a digest key, the digests should be kept separate.

### 👎 Actual Behavior with Screenshots

Digests for different values of the same digest key are combined.

### 📃 Provide any additional context for the Bug.

There is a [PR that was supposed to fix this issue](https://github.com/novuhq/novu/pull/835) that seems to have been merged, but in our testing the issue still exists. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1642](https://linear.app/novu/issue/NV-1642/🐛-bug-report-digests-with-different-values-for-digest-key-are)</sub>

**Comment by tsssdev** [comment]
This is taken care as part of  this bug https://github.com/novuhq/novu/issues/2697

**Comment by p-fernandez** [comment]
This will be fixed inside this PR: [https://github.com/novuhq/novu/pull/2726](https://github.com/novuhq/novu/pull/2726)

**Comment by p-fernandez** [comment]
@spakanati this has been fixed thanks to @tsssdev. Should be available in our version 0.12.0 and our branch `next`. Let us know if you face the same issue again.
