### ISSUE TITLE
[NV-1647] ✨ Polishing: ProviderId not required in jobs table

### ISSUE THREAD

**Issue by tsssdev** [novuhq/novu#2722]
### 📜 Description

Right now in Jobs table we are storing providerId and that is unnecessary and not used any where else in the code. and this providerId is null for non channel steps(digest etc.) and also there is no guarantee what we stored here is same as what we use while sending message, ex: while creating job if email provider is sendgrid and while sending message if they change email integration to mailgun then in jobs table it shows sendgrid but delivered with mailgun, so it adds confusion and inconsistency, so better remove this from jobs table and also we get some performance boost as we can avoid one DB call to get provider while storing job. 
Please let me know if I missed any use case where we need the jobid?

### 📃 Provide any additional context for the Bug.

If you guys think same, please assign me, I can work on this and submit PR.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1647](https://linear.app/novu/issue/NV-1647/✨-polishing-providerid-not-required-in-jobs-table)</sub>

**Comment by scopsy** [comment]
Thank you for the input, the providerId is needed internally for future proofing of corelating webhook responses, routing mechanism between providers and for statistical purpose (logging and debugging.) Unfortunately we won't be able to remove this property from the jobs table. 

Will close this issue 🙏
