### ISSUE TITLE
[NV-1649] ✨ Polishing: Redesigning/refactoring the digest code

### ISSUE THREAD

**Issue by tsssdev** [novuhq/novu#2727]
### 📜 Description

While working on digest bug #2697  I felt the current digest code is too complex and excessive and can be simplified significantly, also performance also can be improved by refactoring and reducing the DB calls. I will create a draft PR and we can discuss in detail.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1649](https://linear.app/novu/issue/NV-1649/✨-polishing-redesigningrefactoring-the-digest-code)</sub>

**Comment by oba2311** [comment]
@tsssdev alright if you are up for it, then don't see why not. @davidsoderberg  WDYT?

**Comment by SebastianStehle** [comment]
Btw: Are you really sure that you need a distributed lock for that? I am not sure about the backoff strategy, but I assume that you only exactly one digest group per subscriberId and digest-id. So you could just work with good primary keys to ensure that you do not have duplicates.

**Comment by tsssdev** [comment]
Sure @oba2311 I will submit a draft PR so it will be easy to understand what I am trying to do.. @SebastianStehle I do not think we need distributed lock as we are grouping by subscriber id, may be in very rare cases we may get dupes for that I think adding locks makes system more complicated and slows down significantly, I think we should avoid locking where ever possible. 
Also Right now I think we do not have clarity on what is expected if we get multiple digest nodes and and multiple delay and digest nodes together in same chain, as part of this we can also come up with clear expected behavior.  Also right now we are calling relation between jobs as parent child, but I relly think it is just chain of jobs, WDYT?

**Comment by SebastianStehle** [comment]
I think the same, therefore I was asking. With the normal strategy, I think you can just do something like this

Pseudo Code:

UPSERT
   { "_id": "{tenantId}_{subscriberId}_{...}", "expiration": { $lt: ... }}
   { "$push": { "events": "newEvent" } }
  
CASE 1: No group exists or is not expired.
1. Will be just created

CASE 2: Group is expired but not processed yet.
1. If you have another element that is already expired, you get a primary key exception. 
2. Then you just remove the element from mongodb and you push the events to the next step in the workflow.
3. Then just retry with the insert.

**Comment by oba2311** [comment]
@davidsoderberg  you'll prob have the context to have this conversation with Sebastian…

**Comment by p-fernandez** [comment]
@SebastianStehle @tsssdev the distributed lock is to handle concurrency issues that led to buggy behaviour of the Digest because race conditions. The digest key has nothing to do with that in general, though when using digest key, it is used to create a specific lock for all the affected notifications of said digest key to avoid duplication and ensure the right behaviour of digest.

**Comment by tsssdev** [comment]
@p-fernandez, most of the issues reported by users I was able to reproduce with out hitting concurrently, I given delay of two to 3 mins(after first event fully processed) and still able to reproduce dupes/mixup etc problems, in the code we had serious bugs(multiple digest kes not taken care, digest key missing case not taken care etc.) and I have fixed with this PR https://github.com/novuhq/novu/pull/2726, I think the users who reported they were not hitting simultaneously... 
But in any case I have rewrote complete digestion code and fixed all the issues with out any locking just using mongodb atomic operation. , and is now much faster, eliminated all unnecessary dummy trigger jobs etc. and refactored the code to simplify logic and follow all logic one simple flow with out fragmented all over.. also as part of this I also refactored workflowqueservice code(this is not required for digest refactoring, but done it as it was complex to trace out the problems, again this also following multiple fragmented paths), also right now the existing code is written assuming we will have only single job chain and has issues when we have multiple digests and issues with delaypath jobs etc. In this new code I have take care all those existing issues, this new code is designed such a way , later if we need to support multiple chains in same template(with parallel, sequential combination) it supports easily. if we need to support scheduled digests(like every day 9 AM etc.) also become so simple now in the new code... I am about to create PR, but just got latest from master and got some conflicts(especially the test cases all mixed up), I will resolve those and test again and create PR, mostly by tomorrow morning.. 
BTW, do we have any performance/benchmark tool/script? I would like to see the performance before and after, I am assuming this new code gives huge performance boost, I will not be surprised if it **gets more thank 10X performance boost** in some cases.

**Comment by SebastianStehle** [comment]
@p-fernandez I understand why a lock is needed. But if you can bring it down to a single atomic operation you do not need a lock. Thats my point. But it seemsed that @tsssdev came to the same conclusion :)

**Comment by p-fernandez** [comment]
@SebastianStehle the single atomic operation was researched to leave it at MongoDB level, but unfortunately we couldn't find a way to implement it with the current domain logic, therefore the pessimistic lock direction.

@tsssdev happy to see what you have tried but I suggest you to always branch off from `next` (we don't even have a `master` branch) when working.

**Comment by tsssdev** [comment]
Yes, @p-fernandez I have created branch from next only(I just referred that as master), coming to mongodb atomic operation, I just used findOneAndUpdate with upsert and it worked perfectly, I tried hitting parallel requests with small script and it handled all fine. I was testing 3 to 4 days and till now no dupes.

**Comment by tsssdev** [comment]
@SebastianStehle , @p-fernandez  created the draft PR, please review and let me know if any other changes required.

**Comment by tsssdev** [comment]
@p-fernandez Did you get a chance to review this PR? I have committed two solutions for locking issue, 1. is just using findOneAndUpdate, this works fine most cases, but in rare cases(if we get request from  same subscriber/same template/samestep/samedigestkey and value  exactly at same milli/nano second to mongo DB then there is slight scope of atomic operation fails and inserts dupes, this may happen very rarely until unless someone doing DDOS type of attack, in normal traffic this never happens, even in rarely if we get dupes also, we will just send one additional message for that particular user.., say if 100 messages digested, instead ogf sending 1 message with 100 digest cont, it sends two messages one with 99 and another with 1. But if we want to be extra cautious , I have implemented one more solution with by adding additional digestRunKey(uuid5) unique key for digest queued jobs, so it takes care 100% and all this with out using any local locks or distributed locks..  

Also this PR has more than concurrency fixes,  entire digest logic is refactored and rewritten, this new code is much smaller and less error prone and if we need to add any enhancements, it is very easy in the new code, and also refactor the complex workflow queue code by separating the logic and removing dupe/multi path flows and removed circular dependencies... 

If you guys need to understand better about DAG, I have added some specs test cases, please check that, that can give complete picture of DAG, if you understand DAG then understanding remaining parts of code is easy and simple. Please let me know if you need any clarifications.
