### ISSUE TITLE
[NV-1656] ✨ Polishing: Font Sizes are inconsistent

### ISSUE THREAD

**Issue by SebastianStehle** [novuhq/novu#2743]
### 📜 Description

The font sizes are inconsistent. I have made a few screenshots:

![image](https://user-images.githubusercontent.com/1236435/218319027-c68a532f-382d-4f27-95b2-3cf7c108bb3e.png)
![image](https://user-images.githubusercontent.com/1236435/218319082-8e47bb55-f10e-4be4-b5fe-45da584adc88.png)
![image](https://user-images.githubusercontent.com/1236435/218319107-032899d3-bb6d-417c-b2f0-5b24f26ffaa3.png)

In general:

1. Table font sizes are very small.
2. Sometimes they are not consistent, why is "Created At" smaller than other columns?
3. Activity feed has several small font sizes (11.2px of the left at "Transaction id" and 12px on the right at "Message Sent")

I would define like 4-5 font sizes and use them just everywhere.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1656](https://linear.app/novu/issue/NV-1656/✨-polishing-font-sizes-are-inconsistent)</sub>

**Comment by scopsy** [comment]
Thanks for submitting this!

Regarding the Created At column, couldn't find that it is smaller than other (from your screen shots and when inspecting it (createdAt is 12px just like the other ones) Maybe I'm missing something?

**Comment by scopsy** [comment]
@nknyshov would love to get your opinion on this one :)

**Comment by SebastianStehle** [comment]
On the first screenshot the font size of CreatedAt is 12px and the rest is 14px.

![Untitled](https://user-images.githubusercontent.com/1236435/218324919-c436abb4-29d4-44bf-b219-e04ce828a88a.png)

**Comment by scopsy** [comment]
@SebastianStehle my bad, was looking on the table title, not the actual rows 🙏

**Comment by ayush4345** [comment]
Can I work on this issue ?

**Comment by scopsy** [comment]
@ayush4345 surething! 🚀

**Comment by ayush4345** [comment]
> @ayush4345 surething! 🚀

hey can you tell me the file where I can find this ??
