### ISSUE TITLE
[NV-1666] 🚀 Feature: subscriberId added to postmark webhook activity feed

### ISSUE THREAD

**Issue by vfxGer** [novuhq/novu#2751]
### 🔖 Feature description

Provide webhooks was added to Novu in a recent release (v0.10.1) and this allows for the fetching of email status via the activity feed. When an event is triggered within Novu, the caller will be returned the transaction ID, this ID can be used to access the activity feed which will detail if there were emails sent and what the status of those emails is. If an event was sent to multiple subscribers at the same time, all emails to all subscribers will be returned in the activity feed. We would need to filter out the results based on the subscriberId.  
We want to add the subscriberId to the get activity feed endpoint. 

### 🎤 Why is this feature needed ?

So that we can filter which subscribers received their email 

### ✌️ How do you aim to achieve this?

The subscriberId in the activity feed endpoint

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1666](https://linear.app/novu/issue/NV-1666/🚀-feature-subscriberid-added-to-postmark-webhook-activity-feed)</sub>

**Comment by oba2311** [comment]
Thanks.

So the ask is to add the subID to the object returned?

@scopsy / @ainouzgali  thoughts on this?

**Comment by scopsy** [comment]
@vfxGer you could pass the subscriberId to the existing `search` param, but I agree adding a dedicated subscriberId query param will be much easier to understand 🙏

**Comment by ainouzgali** [comment]
@vfxGer this has been released in v0.17.0 :)
