### ISSUE TITLE
[NV-1667] 🐛 Bug Report: Unable to set axios proxy

### ISSUE THREAD

**Issue by vfxGer** [novuhq/novu#2752]
### 📜 Description

The Novu Postmark integration used the Postmark Javascript client under the hood, which itself uses the Axios JavaScript library. Axios should have support for the http_proxy environment variable and if set, Axios would route requests through the provided proxy when making requests to the outside world. However this is not currently working.

### 👟 Reproduction steps

Try and set a http proxy for axios

### 👍 Expected behavior

NA

### 👎 Actual Behavior with Screenshots

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1667](https://linear.app/novu/issue/NV-1667/🐛-bug-report-unable-to-set-axios-proxy)</sub>

**Comment by oba2311** [comment]
@unicodeveloper  + @davidsoderberg would love your thoughts here.

**Comment by davidsoderberg** [comment]
@vfxGer should this not be a feature on postmark client first and then we could maybe support it on our provider?

**Comment by scopsy** [comment]
@davidsoderberg I aggree, unfortuently we won't be able to use environment variable due to the multi tenant nature of Novu, but if the postmark client supports it, we can add an optional field to the provider config modal.

https://github.com/ActiveCampaign/postmark.js/pull/8/files (might help with this)
