### ISSUE TITLE
[NV-1670] 🐛 Bug Report: Cannot filter steps by custom subscriber data

### ISSUE THREAD

**Issue by chauandrew** [novuhq/novu#2756]
### 📜 Description

Hi - first time contributing, so please be gracious! 

I noticed that we're not able to filter event trigger steps by custom subscriber data. In the following screenshot, if a subscriber has custom attributes `{customKey: customValue}` and the event is triggered to them, they will not receive the notification. 

![Screenshot 2023-02-13 at 4 57 36 PM](https://user-images.githubusercontent.com/37708620/218610595-1267ad2d-0dcd-4338-8bdc-e9885a02d505.png)

### 👟 Reproduction steps

1. Create a subscriber with custom attributes, eg `"data": { "customKey": "customValue" }`
2. Add a step filter to a notification template as the above screenshot
3. Trigger the notification to the subscriber

### 👍 Expected behavior

I expect the app to apply step filters to custom subscriber data. In the scenario described above, a subscriber with matching customKey/customValue pair should receive the notification. 

### 👎 Actual Behavior with Screenshots

If you add a filter for `data.customKey`, `EQUALS`, `customValue`, and there is a subscriber with `data.customKey: customValue`, that subscriber will not receive a notification from the event. 

![Screenshot 2023-02-13 at 5 06 34 PM](https://user-images.githubusercontent.com/37708620/218612330-09af5581-a727-4d69-8024-85fa1a935245.png)

It's not pictured, but the same happens if I use  `customValue` instead of `data.customValue` as the key in the step filter. 

### 📃 Provide any additional context for the Bug.

I may be missing something since I'm new to this codebase, but it looks like a one-line code change in the `processFilterEquality(variables, fieldFilter, filterProcessingDetails)` function in 
 `api/src/app/events/usecases/trigger-event/message-matcher.service.ts`.

We currently extract the field filter value from the subscriber data using `_.get(variables, [fieldFilter.on, fieldFilter.field])` where 
- `variables` contains the keys: `payload`, `subscriber`, and `webhook` 
- `fieldFilter.on` contains the string value 'subscriber' or 'payload'
- `fieldFilter.field`  contains user input to search by (in the above example, `data.customKey`). 

lodash .get() can iterate through the keys of an object with either a string (eg `"key1[0].key2.key3"`) or with an array (eg `["key1", "0", "key2", "key3]`). The current implementation uses an array, but since the user passes a string input (eg `"data.customKey"`), we call the function as `_.get( {...}, ["subscriber", "data.customKey"] )`, using a mix of array and string values to define the path. It can be fixed if we build a single string for the path (`"subscriber.data.customKey"`) or if we `.split('.')` the field and build an array for the path (`["subscriber", "data", "customKey"]`)

Locally, I replaced 
```ts
const actualValue = _.get(variables, [fieldFilter.on, fieldFilter.field]);
```
with 
```ts
const actualValue = _.get(variables, `${fieldFilter.on}.${fieldFilter.field}`);
```
and it works as expected - but I haven't tested it very thoroughly.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1670](https://linear.app/novu/issue/NV-1670/🐛-bug-report-cannot-filter-steps-by-custom-subscriber-data)</sub>

**Comment by scopsy** [comment]
@chauandrew this totally could help! Shoud I assign you?

**Comment by chauandrew** [comment]
@scopsy I can work on this, go ahead and assign me! I'm new to open source projects, so please let me know if I mishandle anything through the process. 

Thanks!
