### ISSUE TITLE
[NV-1677] Feature: Manage unused jobs of merged digests

### ISSUE THREAD

**Issue by p-fernandez** [novuhq/novu#2760]
### 📜 Description

After fixing the race conditions in: [https://linear.app/novu/issue/NV-1561/%F0%9F%90%9B-bug-report-duplicate-emails-when-using-digest](https://linear.app/novu/issue/NV-1561/%F0%9F%90%9B-bug-report-duplicate-emails-when-using-digest)

the change of logic makes to have jobs steps that are unused and we want to manage them properly and not leave them as `pending` as that could either create side effects on other features or skew the statistics.

For that we need to add logic in the trigger event flow to set those job steps that belong to merged digest jobs as digested or merged. That means to create a new StepStatusEnum entry that marks them properly (name to be agreed).

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1677](https://linear.app/novu/issue/NV-1677/feature-manage-unused-jobs-of-merged-digests)</sub>

**Comment by oba2311** [comment]
@p-fernandez  as there is no effect AFAIK on the user experience, we consider it a tech debt for now but if you think otherwise would love to discuss further.

In general we need to chat a bit on the effort for digest as there are several moving parts and we can prioritize (next cycle prob).
