### ISSUE TITLE
[NV-1681] 🐛 Bug Report: PayloadTooLargeError:

### ISSUE THREAD

**Issue by kfenev** [novuhq/novu#2768]
### 📜 Description

Got "413 Request Entity Too Large"(http) and "PayloadTooLargeError: request entity too large"(logs) from the "api" container.

### 👟 Reproduction steps

The request is "/v1/notification-templates/xxxxxx" with "Content-Length: 259340".

### 👍 Expected behavior

The request must be successfully applied.

### 👎 Actual Behavior with Screenshots

![image_2023-02-13_23-22-23](https://user-images.githubusercontent.com/125360200/218938013-f73e10d2-c375-4cd8-92f3-a3e79ff8eae7.png)

### 📃 Provide any additional context for the Bug.

How to increase max content-length to 2MB?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1681](https://linear.app/novu/issue/NV-1681/🐛-bug-report-payloadtoolargeerror)</sub>

**Comment by scopsy** [comment]
@kfenev what version of Novu are you using? @ainouzgali I think this was fixed in 0.11.0? Or is it part of this release?

**Comment by ainouzgali** [comment]
@scopsy @kfenev It is part of the upcoming release

**Comment by kfenev** [comment]
@scopsy   0.7.3

**Comment by kfenev** [comment]
ok, thanks!

**Comment by kfenev** [comment]
Hi! Was problem solved in 0.12.0 ? There are no mentions at "0.12.0 Polishing Release Updates".

**Comment by ainouzgali** [comment]
Hi @kfenev, yes, it is part of 0.12.0 . Do you still have this problem?

**Comment by kfenev** [comment]
@ainouzgali the problem is gone, thanks! But something else was changed - env REACT_APP_API_URL has no effect at all after upgrade. We need to deal with this now.

**Comment by ainouzgali** [comment]
@kfenev that seems to be related to [this fix ](https://github.com/novuhq/novu/issues/2939)
