### ISSUE TITLE
[NV-1685] Detail message in activity feed modal gets cut when error shown

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2793]
Run a test workflow and generate a provider error - in this case it is an invalid char.

Your error message will likely get cut like so:

![CleanShot 2023-02-15 at 22.33.20.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/9b561914-c702-4de0-8c76-aad313fc7e92/ef45e29c-c23e-4018-b802-4eff21ddcb35)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1685](https://linear.app/novu/issue/NV-1685/detail-message-in-activity-feed-modal-gets-cut-when-error-shown)</sub>

**Comment by ainouzgali** [comment]
It's not cut :) Scroll to the right

**Comment by oba2311** [comment]
mmm not sure how to scroll to the right there?

Anyways, would be good to solve with @nikolay as it is a bad pattern at the moment.

**Comment by aggmoulik** [comment]
@oba2311 It would be great to wrap the content instead of making it scrollable to the right. IMO, as a UX approach this should be best and I can work on it. It will be a small issue.

**Comment by ainouzgali** [comment]
@nikolay maybe you could suggest what would be best?

**Comment by oba2311** [comment]
aggmoulik wrapping is a good idea, please wait for Nikolay our designer to approve and then you can take it.

**Comment by oba2311** [comment]
Good point, not sure.

**Comment by scopsy** [comment]
@oba2311 this one for example is not ready for dev, until the designs are ready 😃

**Comment by oba2311** [comment]
Is @scopsy  it is blocked by @nikolay  to approve 😃
