### ISSUE TITLE
[NV-1675] EmptyState prop on PopoverNoificationCenter bad typing

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2795]
## Reproduction Steps

* Create a react project and use the notification center with an empty state component:

```
<PopoverNotificationCenter
    emptyState={() => <LookingGlassIcon/>}
/>
```

* When using the following syntax react send a warning message:

```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it
```

## Expected Behaviour

We need to modify the TS definition and change the signature to be:

```
<PopoverNotificationCenter
    emptyState={<LookingGlassIcon/>}
/>
```

And update the relevant documentation section where needed.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1675](https://linear.app/novu/issue/NV-1675/emptystate-prop-on-popovernoificationcenter-bad-typing)</sub>

**Comment by nikitagrossman** [comment]
id like to help

**Comment by ainouzgali** [comment]
Amazing! @nikitagrossman feel free to reach out if you need anything🚀
