### ISSUE TITLE
[NV-1669] Missing overrides details in activity feed response

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2796]
## Why?

In some cases debugging the overrides can be helpful to understand particular trigger execution.

## How?

In response of [https://docs.novu.co/api/get-activity-feed](https://docs.novu.co/api/get-activity-feed) overrides details is missing.

Response item of above endpoint.

![Screenshot 2023-02-13 at 10.27.05 PM.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/41aab37e-6304-4519-833f-4e121cb83889/c8dc8cba-79c6-4463-837a-865cd3007d1e)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1669](https://linear.app/novu/issue/NV-1669/missing-overrides-details-in-activity-feed-response)</sub>

**Comment by BiswaViraj** [comment]
![image](https://user-images.githubusercontent.com/29251776/221550930-52b54b1b-b9f2-4bf2-8afa-b305de0cc818.png)
@jainpawan21 , `overrides` is available under the `jobs` property

**Comment by jainpawan21** [comment]
Thanks Biswa, May be I missed this.
