### ISSUE TITLE
[NV-1687] ✨ Polishing: no context on what I am editing

### ISSUE THREAD

**Issue by nevo-david** [novuhq/novu#2803]
### 📜 Description

When you create a new workflow, I don't have the name of the workflow on top,
I made a mistake and added two steps, utterly different because I forgot what I was working on.

### 👟 Reproduction steps

Create a new workflow >> add a new step >> forgot what you were working on

### 👍 Expected behavior

Instead of "Workflow Editor" write the name of the workflow.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1687](https://linear.app/novu/issue/NV-1687/✨-polishing-no-context-on-what-i-am-editing)</sub>

**Comment by oba2311** [comment]
I thought we had it solved but I seem to not find an issue related to it. So let's do it.

**Comment by scopsy** [comment]
Not sure if we need any design for this from @nikolay I think this can be just easily changed to have the dynamic value.

**Comment by nevo-david** [comment]
Just change this, or add it after this:
<img width="1392" alt="Screen Shot 2023-02-26 at 18 53 12" src="https://user-images.githubusercontent.com/100117126/221408849-68ebc6b3-dd15-419e-a00c-6075bdd0a6fc.png">

**Comment by oba2311** [comment]
Yup I already talked with Nikolay about it in this case but in the future, when we have German for example, he needs to check things like that.

**Comment by jainpawan21** [comment]
Closing this issue, as this is fixed
Now we have template name in place of Workflow Editor
See `different invite link for each subscriber`

<img width="1352" alt="Screenshot 2023-04-11 at 12 46 21 PM" src="https://user-images.githubusercontent.com/39362422/231084683-fd64154a-584f-4c37-9c55-e1d0821bb098.png">
