### ISSUE TITLE
[NV-1688] ✨ Polishing: The wizard before moving to the workflow editor is confusing.

### ISSUE THREAD

**Issue by nevo-david** [novuhq/novu#2804]
### 📜 Description

 I press the “create” button multiple times; something needs to be changed there - it can’t be that the “create” and the “second tab” are both calls to action.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1688](https://linear.app/novu/issue/NV-1688/✨-polishing-the-wizard-before-moving-to-the-workflow-editor-is)</sub>

**Comment by nevo-david** [comment]
Both of them are CTA. They should both be on the top
<img width="1365" alt="Screen Shot 2023-02-16 at 20 54 20" src="https://user-images.githubusercontent.com/100117126/219383845-c2925d0b-5def-4d03-bc0a-ae318261b05e.png">

**Comment by oba2311** [comment]
OK, yes this screen will have to change. 
We'll work on it 100% with @nknyshov .

**Comment by p-fernandez** [comment]
Closing as we implemented a new flow for the Workflow editor. 😄
