### ISSUE TITLE
[NV-1689] ✨ Polishing: Edit / Create step should be a popup

### ISSUE THREAD

**Issue by nevo-david** [novuhq/novu#2805]
### 📜 Description

Better to put a popup than move to another screen to edit a step, I am losing context fast, and it’s very confusing.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1689](https://linear.app/novu/issue/NV-1689/✨-polishing-edit-create-step-should-be-a-popup)</sub>

**Comment by oba2311** [comment]
Thank you for this important issue!

This is the kind of UX changes we have our 👁️ on. @nikolay  and I will take a look here an this is something we will work on during Q2 and roll out during Q3 as it requires UX research. 

Will keep you updated!

**Comment by nevo-david** [comment]
Thank you @oba2311

**Comment by oba2311** [comment]
This issue is blocked by UX research and goes to the backlog so we can get back to it when design is done.

**Comment by ainouzgali** [comment]
Duplicate  of [this one](https://linear.app/novu/issue/NV-475/\[wip\]-let-users-configure-channels-through-the-steps-area-in-the) ?
