### ISSUE TITLE
[NV-1690] ✨ Polishing: Fix alignment of plus button

### ISSUE THREAD

**Issue by SebastianStehle** [novuhq/novu#2806]
### 📜 Description

The plus icon is not perfectly aligned:

![image](https://user-images.githubusercontent.com/1236435/219381268-aa3764de-7464-44dc-936c-a9880bb2e6df.png)

I see it all the time and drives me crazy. I would just add a background to the button ;)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1690](https://linear.app/novu/issue/NV-1690/✨-polishing-fix-alignment-of-plus-button)</sub>

**Comment by joanjeremiah** [comment]
Can you assign this task to me ?

**Comment by jainpawan21** [comment]
Hi @joanjeremiah 
We highly appreciate your interest in contribution.
However, this issue is not ready to assign.

**Comment by oba2311** [comment]
@nikolay  let's add this one the April project

**Comment by ayush4345** [comment]
Is this issue is ready to work on ?
Then, I would like to work on this

**Comment by scopsy** [comment]
Was resolved in previous releases 🙏
