### ISSUE TITLE
[NV-1691] [Roadmap] - Zappier

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2807]
<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1691](https://linear.app/novu/issue/NV-1691/zappier-integrations-roadmap)</sub>

**Comment by Shawbran** [comment]
> 
> 
> <sub>From [SyncLinear.com](https://synclinear.com) | [NV-1691](https://linear.app/novu/issue/NV-1691/zappier-integrations-roadmap)</sub>

Let move it global up like never before
