### ISSUE TITLE
[NV-1105] System Critical - Copy needs to be fixed and clear

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2843]
Copy doesn't need to change on toggle and one option we can write here is:

`When on, users will get the messages even if they opt out in user preferences` 

![CleanShot 2022-10-26 at 15.02.25@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/af757f82-d19f-4c86-9d32-fdeb60ace230/7131bfe2-a07b-41e6-a4ca-ecd809322eb7)

---

Created via [Raycast](https://www.raycast.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1105](https://linear.app/novu/issue/NV-1105/system-critical-copy-needs-to-be-fixed-and-clear)</sub>

**Comment by nikitagrossman** [comment]
i would love to help with that

**Comment by ainouzgali** [comment]
Thank you @nikitagrossman🤩

**Comment by ainouzgali** [comment]
@oba2311, if its on - if its marked critical - the template will not show in the user preferences , meaning they wouldn't be able to opt out.

I don't think this copy is clear.

**Comment by oba2311** [comment]
I agree @ainouzgali  we probably wrote the copy before deciding for the functionality.

I just checked i prod and this is what we actually have:

![CleanShot 2023-02-20 at 15.42.17.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/c23f38f9-e52c-4ffc-a709-f8c6c987fa02/b5dcb0e1-353c-4d59-a3fb-361aa53511d6)
