### ISSUE TITLE
[NV-1749] 🚀 Feature: Support more logic in the templating.

### ISSUE THREAD

**Issue by KristofDeTroch** [novuhq/novu#2874]
### 🔖 Feature description

It would be nice to have some more templating options available in titles and body fields. An example would be to pass a list of companyNames and be able to do this: 
```{{companyNames.length === 2 ? `${companyNames[0]} and ${companyNames[1]}` :  `${companyNames[0]}, ${companyNames[1]} ${companyNames[2]}`}} have joined the platform!```

### 🎤 Why is this feature needed ?

In my use case this would allow my backend to be more generic and have all the logic relating to templating and content be managed in Novu.

### ✌️ How do you aim to achieve this?

Tricky. Eval seems a straightforward solution, but possibly dangerous. Maybe add Handlebars?

### 🔄️ Additional Information

If this feature is too complex or out of scope it would also be nice if this was communicated clearly so we know to handle these kinds of strings before triggering novu. I don't know exactly all the locations where this is needed.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1749](https://linear.app/novu/issue/NV-1749/🚀-feature-support-more-logic-in-the-templating)</sub>

**Comment by ainouzgali** [comment]
@KristofDeTroch, as discussed on discord- but adding here for others who are wondering :)  You could use: 
`{{#each array}}
    {{#if @last}} and 
          {{else}} {{#unless @first}} , {{/unless}} 
    {{/if}}  {{this}} 
   {{/each}}`

So for `array: ["comp1","comp2","comp3"]`

will result in: comp1, comp2 and comp3
