### ISSUE TITLE
[NV-1750] 🚀 Feature: OpenAPI docs

### ISSUE THREAD

**Issue by vfxGer** [novuhq/novu#2875]
### 🔖 Feature description

It would really help us if the novu api was documented, preferably using the [OpenAPI](https://www.openapis.org/) spec.

### 🎤 Why is this feature needed ?

To allow use to test and use the novu api

### ✌️ How do you aim to achieve this?

There is many tools like [swagger](https://swagger.io/) that could auto generate the docs or they could be manually created.  

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1750](https://linear.app/novu/issue/NV-1750/🚀-feature-openapi-docs)</sub>

**Comment by jainpawan21** [comment]
Hi @vfxGer
Checkout this 
https://docs.novu.co/api/overview/

**Comment by vfxGer** [comment]
That's great, is there a swagger ui or a way to generate it?

**Comment by jainpawan21** [comment]
https://api.novu.co/api/

**Comment by vfxGer** [comment]
Great thanks, last question is there a way to generate https://api.novu.co/api/ from the source code?

**Comment by jainpawan21** [comment]
Yes it will be auto generated once you run the api
It will be available at /api endpoint

**Comment by vfxGer** [comment]
thanks
