### ISSUE TITLE
[NV-1759] 🐛 Bug Report: Removing a subscriber from a topic removes them from all subscribed topics

### ISSUE THREAD

**Issue by ay8s** [novuhq/novu#2902]
### 📜 Description

If a user is subscribed to a bunch of topics and we remove them from a single topic using `https://api.novu.co/v1/topics/:topicKey/subscribers/removal` then the subscriber is actually removed from all topics rather than just the defined topic.

### 👟 Reproduction steps

1. Add a subscriber to multiple topics.
2. Call `https://api.novu.co/v1/topics/:topicKey/subscribers/removal` with a single topic
3. Check the topics that are subscribed and you'll see the subscriber is no longer subscribed.

### 👍 Expected behavior

Removing should only remove the subscriber from the defined topic.

### 👎 Actual Behavior with Screenshots

Subscriber is removed from every topic they're subscribed to.

### 📃 Provide any additional context for the Bug.

Discord: https://ptb.discord.com/channels/895029566685462578/1078569121861603389

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1759](https://linear.app/novu/issue/NV-1759/🐛-bug-report-removing-a-subscriber-from-a-topic-removes-them-from-all)</sub>

**Comment by LetItRock** [comment]
@ay8s The fix was merged and will land in the next release ;) closing this issue
