### ISSUE TITLE
[NV-1768] 🐛 Bug Report: Azure redis is 6.0.14 - getting this error It is highly recommended to use a minimum Redis version of 6.2.0 Current: 6.0.14

### ISSUE THREAD

**Issue by tyipfadv** [novuhq/novu#2914]
### 📜 Description

Trying to deploy Novu in Azure and wanted to connect with Azure redis and getting the following warning

It is highly recommended to use a minimum Redis version of 6.2.0           
Current: 6.0.14

It looked like it connected but now getting the following errors

[ioredis] Unhandled error event: Error: read ECONNRESET    
at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[ioredis] Unhandled error event: 
Error: read ECONNRESET    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Error: read ECONNRESET    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {  errno: -54,  code: 'ECONNRESET',  syscall: 'read'}

### 👟 Reproduction steps

connect with Azure redis.

### 👍 Expected behavior

No error

### 👎 Actual Behavior with Screenshots

It is highly recommended to use a minimum Redis version of 6.2.0           
Current: 6.0.14

[ioredis] Unhandled error event: Error: read ECONNRESET    
at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[ioredis] Unhandled error event: 
Error: read ECONNRESET    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Error: read ECONNRESET    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {  errno: -54,  code: 'ECONNRESET',  syscall: 'read'}

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1768](https://linear.app/novu/issue/NV-1768/🐛-bug-report-azure-redis-is-6014-getting-this-error-it-is-highly)</sub>

**Comment by jainpawan21** [comment]
Hi @tyipfadv 
It looks like there is some networking issue with azure redis. azure redis is not allowing incoming connection.

**Comment by tyipfadv** [comment]
thanks and let me check the firewall rule

**Comment by tyipfadv** [comment]
btw, is there a way to disable redis?   I read somewhere and I have tried to comment out  both REDIS_CACHE_SERVICE_HOST and 
REDIS_CACHE_SERVICE_PORT.    

what will be the side effect if I disable the cache?

**Comment by oba2311** [comment]
Seems like not a Novu bug  - I'm closing and please reopen if indeed you realize it is a bug.

**Comment by tyipfadv** [comment]
thanks, it looked like there was an issue in Azure redis cache.
