### ISSUE TITLE
[NV-1780] 🐛 Bug Report: Bundled Version Stopped Working

### ISSUE THREAD

**Issue by JTravaux** [novuhq/novu#2920]
### 📜 Description

I have been using the [Web Component (Bundled Version)](https://docs.novu.co/notification-center/web-component#bundled-version-preview) and realized that something broke. It was working at one time, when I first tried it out, however it seems to have randomly broken.

### 👟 Reproduction steps

1. Create simple HTML page
2. Attach Novu Web Component script in the head tag
3. Load the page to see the error in the console

Example code:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://novu-web-component.netlify.app/index.js"></script>
  </head>
  <body>
    <notification-center-component
      style="display: inline-flex"
      application-identifier="hidden"
      subscriber-id="123"
    ></notification-center-component>
    <script>
      // here you can attach any callbacks, interact with the web component API
      let nc = document.getElementsByTagName('notification-center-component')[0];
      nc.onLoad = () => console.log('hello world!');
    </script>
  </body>
</html>
```

### 👍 Expected behavior

Notification Center should work, and I should see the component on the page.

### 👎 Actual Behavior with Screenshots

The Notification Center was never made, and gives a console error
![image](https://user-images.githubusercontent.com/30296275/221944631-948710d7-2e08-40cb-b4f7-ae7cce3a6367.png)

### 📃 Provide any additional context for the Bug.

This was working a few weeks ago when I tried it, and just randomly broke the next time I checked.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1780](https://linear.app/novu/issue/NV-1780/🐛-bug-report-bundled-version-stopped-working)</sub>

**Comment by jainpawan21** [comment]
Hi Jordan 👋
Thanks for sharing this issue here.
We are currently looking into this.

cc:- @LetItRock @BiswaViraj

**Comment by scopsy** [comment]
@BiswaViraj assigning you to this one 🙏

**Comment by scopsy** [comment]
@JTravaux could you please verify it was resolved for you?
