### ISSUE TITLE
[NV-1781] 🐛 Bug Report: 

### ISSUE THREAD

**Issue by ujwalfadv** [novuhq/novu#2921]
### 📜 Description

I wanted to check if there is a way to disable REDIS. I tried to blank out the REDIS host environment variable but it errored out saying it is required. 

### 👟 Reproduction steps

Blank out REDIS_HOST environment variable for the API

### 👍 Expected behavior

It should allow to disable REDIS

### 👎 Actual Behavior with Screenshots

It errored out saying missing required environment variables

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1781](https://linear.app/novu/issue/NV-1781/🐛-bug-report)</sub>

**Comment by jainpawan21** [comment]
Hi @ujwalfadv 
We do not recommend to disable **REDIS** related environment variables because **REDIS** is required for queue service to work.

**Comment by ujwalfadv** [comment]
Hi @jainpawan21 
Thank you for your response. 

We are trying to connect to Azure REDIS. The logs initially shows as connected but we keep seeing the following error for every second on the API after it is up. 

Error: read ECONNRESET
at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
errno: -104,
code: 'ECONNRESET',
syscall: 'read'
}
REDIS CONNECTED


We did set the REDIS_TLS to the following {"servername": "redis_host_name"}.

Is there anything that we are missing in the configuration?

**Comment by ujwalfadv** [comment]
We have build a sample nodejs application to connect to the Azure REDIS using the ioredis and it works fine without any errors. Below is the code snippet for our sample app

const Redis = require('ioredis');
const dotenv = require('dotenv')
dotenv.config({ path: './config.env'});


const redis = new Redis({
  host: process.env.REDIS_HOSTNAME,
  port: process.env.REDIS_PORT,
  password: process.env.REDIS_PASSWORD,
  tls: true
});

**Comment by scopsy** [comment]
@ujwalfadv seems to me like a connection issue, do you mind joining our discord so we can discuss it there? It doesn't seem like a code problem since we are running with redis successfully. So I guess it some miss config error. 

We can continue the chat there: https://discord.novu.co/
