### ISSUE TITLE
[NV-1793] 🐛 Bug Report: custom transactionId not working in trigger

### ISSUE THREAD

**Issue by blobinabottle** [novuhq/novu#2926]
### 📜 Description

I'm trying to pass a custom transactionId to the trigger function. But it's not working (still using a random UUID).

### 👟 Reproduction steps

What I'm doing in node js: 
```
 novu.trigger('comment', {
  to: {subscriberId, email, },
          transactionId: id,
          payload: {
         ...}
})
```

### 👍 Expected behavior

It should use the custom ID I'm passing

### 👎 Actual Behavior with Screenshots

It's using a random UUID

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1793](https://linear.app/novu/issue/NV-1793/🐛-bug-report-custom-transactionid-not-working-in-trigger)</sub>

**Comment by LetItRock** [comment]
hey @blobinabottle 👋 
It looks like the `transactionId` is not passed to the request body... anyone who would like to help here should update the request in the `packages/node/src/lib/events/events.ts:11` file...

**Comment by gitstart** [comment]
@scopsy I would like to work on this.

**Comment by scopsy** [comment]
@gitstart just assigned you 🙏

**Comment by gitstart** [comment]
Hi @scopsy I think we can close this issue now. It was been fixed by this merged [PR](https://github.com/novuhq/novu/pull/3014)
