### ISSUE TITLE
[NV-1815] 🐛 Bug Report: GitHub email change = new account

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#2964]
### 📜 Description

I know it's quite rare case but...when you register in Novu using "Sign in with GitHub" and later you change GitHub primary email, Novu creates new account and previous data is "gone".

Btw. I can reset password while using GitHub provider which is passwordless - it's expected behaviour?

### 👟 Reproduction steps

1. Sign In with GitHub on Novu
2. Change primary email on GitHub
3. Log out from Novu
4. Login with the same GitHub account
5. You end up with new Novu account :)

### 👍 Expected behavior

Most applications perform account lookup by id from provider instead just email address. So email change shouldn't affect user experience directly. The main drawback could be stale email address saved in database during registration.

### 👎 Actual Behavior with Screenshots

**X** - email address before change
**Y** - email address after change

### View from account with X mail address

![image](https://user-images.githubusercontent.com/43048524/223445981-a9bc9c03-6c2d-4af7-80c7-71c2e6d6bafd.png)

### View from account with Y email address

![image](https://user-images.githubusercontent.com/43048524/223446680-0ee482df-93ae-4fcc-9fc6-b154627f246a.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1815](https://linear.app/novu/issue/NV-1815/🐛-bug-report-github-email-change-=-new-account)</sub>

**Comment by scopsy** [comment]
I think that one of the potential things we should do is instead of using the email to identify on oauth, we can use the profiled returned by GitHub instead.

**Comment by oba2311** [comment]
@scopsy  @BiswaViraj  if you guys are busy this could get into other cycle IMO.

**Comment by scopsy** [comment]
@oba2311 added a help wanted for this issue.

**Comment by scopsy** [comment]
@peoray sure! Assigning you 🙏

**Comment by oba2311** [comment]
@unicodeveloper  could you help here? thanks

**Comment by scopsy** [comment]
@peoray I think this should be somewhere around the auth.service area, but might require some other adjustments: https://github.com/novuhq/novu/blob/89b6fccbba97d3594bef4e327a1f45d8a3a79fa4/apps/api/src/app/auth/services/auth.service.ts#L51

**Comment by gitstart** [comment]
@scopsy I would like to pick this up if it's still available.

**Comment by scopsy** [comment]
@gitstart surething!

**Comment by nbharti015** [comment]
Can I take this task ??

**Comment by scopsy** [comment]
Resolved with the new Clerk provider integration
