### ISSUE TITLE
[NV-184] - Add support for TransitSMS

### ISSUE THREAD

**Issue by lyndonbuckley** [novuhq/novu#30]
* **I'm submitting a feature request**
* **Summary**\
  TransitSMS is a popular SMS provider in Australia and New Zealand.\
  Documentation: [https://developer.transmitsms.com/](https://developer.transmitsms.com/)
* **Other information**\
  I'll probably look into developing this integration myself.\
  What is the best way to contribute?

**Comment by scopsy** [comment]
Hi Lyndon!

Sounds awesome, was not familiar with this provider. 

What you can do is to copy `twilio` provider (the only SMS we have right now) and to create a new folder for TransmitSMS implementing the `ISmsProvider`.

Attaching a short explanation on our docs https://docs.notifire.co/docs/community/create-provider (still needs to be improved).

Feel free to create a PR and I'll merge it for our next version 🚀

**Comment by scopsy** [comment]
@lyndonbuckley just noticed the the docs link I gave was out of dated prior us moving to a monorepo. You don't need to clone the template provider repository, just clone this repo and create a new provider under `providers` folder here: https://github.com/notifirehq/notifire/tree/master/providers

**Comment by ComBarnea** [comment]
Just updated the labels to be consistent with other providers, @lyndonbuckley thanks for this provider! Do you need any help?

**Comment by lyndonbuckley** [comment]
I think I should be alright. 

They don't have any pre-built node client, so i'll have to make direct calls to their APIs.
Is there a preference to reduce dependancies? Axios?

**Comment by scopsy** [comment]
@lyndonbuckley Axios should be fine :)

**Comment by pearceman** [comment]
@lyndonbuckley Hey! Any updates?

**Comment by ahmedhesham6** [comment]
I can work on the integration

**Comment by ainouzgali** [comment]
Great @ahmedhesham6 ! Ping us with any questions here or on discord :)

**Comment by florian-lefebvre** [comment]
Hey @ainouzgali, I'm going through the old issues and looks like this one is stale. You might want to add back the `help wanted` label.

**Comment by jainpawan21** [comment]
Unassigning @ahmedhesham6 due to inactivity.
Thanks @florian-lefebvre 🙏🏻

**Comment by fanatic75** [comment]
Assign this to me

**Comment by fanatic75** [comment]
Sure. I'll add it, you can assign to me.

**Comment by Mattiullah134** [comment]
@jainpawan21 if no one work on it can you assign it to me???

**Comment by jainpawan21** [comment]
@Mattiullah134 
Assigning this to you 🚀
