### ISSUE TITLE
[NV-1838] 🐛 Bug Report: tlsOptions are not mapped to NodeMailer integration

### ISSUE THREAD

**Issue by gaviriaricardo** [novuhq/novu#3010]
### 📜 Description

When a user tries to set tlsOptions for an integration via the UI such as `{ "rejectUnauthorized": false }` it seems that it is not written to the DB and is not propagated to the nodemailer integration.

It seems that the NodeMailer config for tls is always set to `undefined` here: https://github.com/novuhq/novu/blob/4727c8eda6228dea4f4f48c583c081ba292a41a2/providers/nodemailer/src/lib/nodemailer.provider.ts#L58

### 👟 Reproduction steps

1. Go to integrations
2. Select Custom SMTP 
3. Set the host, port, `secure=true` and `tlsOptions={ "rejectUnauthorized": false }`
4. Click "save"

### 👍 Expected behavior

1. When the integration is opened again, the `tlsOptions` text field should contain the value that was saved, i.e. it should not be empty
2. The `tlsOptions` should be used in the NodeMailer integration

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/113710913/224920321-401c55ec-095d-4e67-8bfd-87fe2149a4cf.png)

![image](https://user-images.githubusercontent.com/113710913/224920350-c623726a-e60d-4248-ac25-75b6e4a34c25.png)

### 📃 Provide any additional context for the Bug.

With this bug, it is not possible to test out `novu` in productive environments of intranets that have their own internal SMTP servers :( 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1838](https://linear.app/novu/issue/NV-1838/🐛-bug-report-tlsoptions-are-not-mapped-to-nodemailer-integration)</sub>

**Comment by pawanakhil** [comment]
Facing the same issue. I am willing to submit PR for it.

**Comment by p-fernandez** [comment]
Hi @akhill10. I assigned the issue to you, so not anyone else picks it up (even though I had started the works on it behind the scenes). I replied to your PR with changes we need to address.
Thank you for your will to help. 🙌🏻
