### ISSUE TITLE
[NV-1844] @novu/notification-center v0.12.0

### ISSUE THREAD

**Issue by BEN00262** [novuhq/novu#3017]
### 📜 Description

I upgraded from version v0.8.0 due to CORs issues but v0.12.0 doesn't fetch the notifications from the cloud hosted. Running https://api.novu.co/v1/widgets/notifications/feed?page=0 using postman does fetch the messages though

### 👟 Reproduction steps

upgrading to @novu/notification-center v0.12.0 in react

### 👍 Expected behavior

fetch the notifications as was in v0.8.0 

### 👎 Actual Behavior with Screenshots

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1844](https://linear.app/novu/issue/NV-1844/novunotification-center-v0120)</sub>

**Comment by oba2311** [comment]
duplicate closing
