### ISSUE TITLE
[NV-1847] 🐛 Bug Report: Update API accepts null or '' as values but email is not unset

### ISSUE THREAD

**Issue by FabianGutierrezOpengov** [novuhq/novu#3022]
### 📜 Description

When using something like 

```
channel = await this.novu.subscribers.update(id, {
        email: null,
        phone: data.phoneNumber,
      });
```

Email doesn't change, but request is also not rejected.
      

### 👟 Reproduction steps

1) create subcriber

2) update subscriber with null or empty string

### 👍 Expected behavior

Either disallow null as value, or allow me to unset emails (I highly prefer the second one, as an user could want to stop getting notifications to their email)

### 👎 Actual Behavior with Screenshots

getting the previous email

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1847](https://linear.app/novu/issue/NV-1847/🐛-bug-report-update-api-accepts-null-or-as-values-but-email-is-not)</sub>

**Comment by jayavardhan3112** [comment]
Can you assign me this issue @FabianGutierrezOpengov

**Comment by jainpawan21** [comment]
Sure @jayavardhan3112 
Assigning this to you!

**Comment by jainpawan21** [comment]
Hi @jayavardhan3112 
You need help in this?

**Comment by jayavardhan3112** [comment]
Yes, i tried hitting this API
`PUT: http://localhost:3000/v1/subscribers/:subscriberId`
`{
    "email": "",
    "phone": "2109269563"
}`

Getting the response - 

`
{
    "statusCode": 400,
    "message": [
        "email must be an email"
    ],
    "error": "Bad Request"
}
`
isnt this what we want ?

**Comment by jayavardhan3112** [comment]
@jainpawan21 Please Review.
