### ISSUE TITLE
[NV-1849] 🚀 Feature: Support for blocks in Slack messages 

### ISSUE THREAD

**Issue by joesaunderson** [novuhq/novu#3028]
### 🔖 Feature description

Slack has the concept of blocks to build messages - https://api.slack.com/block-kit.

It would be great to make use of these when sending messages to Slack - with interactive elements like buttons and lists.

### 🎤 Why is this feature needed ?

So we can send rich messages to Slack.

### ✌️ How do you aim to achieve this?

Allow pasting of blocks into the UI, that then get sent to Slack via the correct API call (and eventually rendered).

### 🔄️ Additional Information

I tried to use blocks, and they just come through as plain text.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1849](https://linear.app/novu/issue/NV-1849/🚀-feature-support-for-blocks-in-slack-messages)</sub>

**Comment by joesaunderson** [comment]
From looking at the source code, it looks like the content from the `textarea` in the UI is send directly to the `text` content in the Slack API request.

In order to send blocks, we'd need to send the raw JSON from this `textarea` as the request.

**Comment by joesaunderson** [comment]
> Thanks @joesaunderson !
> 
> 
> 
> Could you please share with us a little bit about how you could leverage blocks when using Novu? thanks! 🙌 

Yeah sure, rather then sending a plain text message - you can send interactive messages with buttons, dropdowns, actions etc. It's pretty powerful.

**Comment by ComBarnea** [comment]
@joesaunderson would you be happy to jump on a quick call and share a bit more about the underlying use cases? Just want to learn more about how you intend to use that so we can scope in the right things :) Happy to find the best time over email, or you select a slot from [here](https://calendly.com/novuhq/novu-meeting) if it's easier :)

**Comment by bartelemi** [comment]
This would be a really amazing feature to have, right now sending Slack notifications via Novu is very limited. We can only send plaintext with some minor styling and emojis.

**Comment by scopsy** [comment]
Blocks now officially supported with Echo https://docs.novu.co/echo/quickstart 🎉
