### ISSUE TITLE
[NV-1875] 🚀 Feature: Slack Notifications

### ISSUE THREAD

**Issue by brianzzzasd** [novuhq/novu#3062]
### 🔖 Feature description

Hi Novu Team!

Thank you for sharing this project to everyone. It's been very helpful.

I have a question about Slack Driver usage

<img width="902" alt="Screen Shot 2023-03-21 at 10 23 59 AM" src="https://user-images.githubusercontent.com/33320494/226504749-68c2bfc7-1610-49e6-93f7-33351c5b2766.png">

Is this format possible?

Thank you in advance!

### 🎤 Why is this feature needed ?

For fail/success slack notifications

### ✌️ How do you aim to achieve this?

I want to use this to notify from deploys and other stuff.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1875](https://linear.app/novu/issue/NV-1875/🚀-feature)</sub>

**Comment by brianzzzasd** [comment]
Hi @oba2311 !

Sorry for the confusion. I have attached an image above, it is a sample notification from envoyer to slack. Is it possible to do using your Slack Provider?
Thank you!

**Comment by oba2311** [comment]
🙏

**Comment by unicodeveloper** [comment]
@brianzzzasd I think this might involve Slack block. Right now you can send text. It's similar to #3028

**Comment by brianzzzasd** [comment]
I see, thank you for this @unicodeveloper !

**Comment by brianzzzasd** [comment]
If there is no existing PR for block-kits, can I create one? @oba2311 ?
Thanks!

**Comment by unicodeveloper** [comment]
@brianzzzasd please feel free to create one.

**Comment by Shurtu-gal** [comment]
Hey, just came across this issue. Sounds wonderful but how will editors format their message ?
We can use this [tool](https://app.slack.com/block-kit-builder) or maybe build one ourselves.
What are your thoughts @unicodeveloper ?

**Comment by scopsy** [comment]
Just found this issue recently, blocks is now officially supported using `Echo` Attaching the documentation guide here: https://docs.novu.co/echo/concepts/steps#channel-steps-interface
