### ISSUE TITLE
[NV-1903] 🚀 Feature: specify Novu version in client

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#3073]
### 🔖 Feature description

Current Novu version should be mentioned somewhere in client.

### 🎤 Why is this feature needed ?

In case of self hosting, user will be aware that this specific version is currently used

### ✌️ How do you aim to achieve this?

I will suggest to add somewhere in left bottom below side menu links.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1903](https://linear.app/novu/issue/NV-1903/🚀-feature-specify-novu-version-in-client)</sub>

**Comment by peoray** [comment]
what does this entail? can I pick this up?

**Comment by jainpawan21** [comment]
@peoray Like right now, our most current version is 0.12.0. If you run novu in local machine or you self host novu, this version should be written somewhere in client.

**Comment by peoray** [comment]
How do I get the information

**Comment by oba2311** [comment]
@jainpawan21.novu  this can be worked on, but please makse sure that you get input from @nikolay . thanks

**Comment by scopsy** [comment]
test 2

**Comment by anubhav1206** [comment]
can i work on this?

**Comment by scopsy** [comment]
Sure @anubhav1206, maybe we can add it in the dropdown of the "User" menu? at the bottom centered with smaller font perhaps? Wdyt?

**Comment by anubhav1206** [comment]
We sure can add it at the bottom but why do we need to add it in the dropdown?

**Comment by scopsy** [comment]
@anubhav1206 you mean in general or you have a better location for it? We add it to help with support to users so they can know what version they are currently running :)

**Comment by anubhav1206** [comment]
Bottom is fine

**Comment by AlexVCS** [comment]
I imagine you're still waiting on designs to go ahead and add this?

**Comment by althaf004** [comment]
> I imagine you're still waiting on designs to go ahead and add this?

Absolutely  :P

**Comment by Vivek7038** [comment]
can i get it done without the design ,just give me location where you  want it to be shown

**Comment by rockingrohit9639** [comment]
@jainpawan21 This issue is still not fixed, can I work on this one ?

**Comment by SumitMangrati** [comment]
i am willing to work on this issue, could you please elaborate a bit on what actually needs to be done

**Comment by IbraheemHaseeb7** [comment]
I think this is a sort of feature and I understand its importance. It can be implemented the way you want @althaf004 . How about we do some sort of collaboration on it together so we can get the design ready and implementation ASAP?

**Comment by mpatwa98** [comment]
I would like to work on this. Can you assign it to me?

**Comment by vineetjk** [comment]
I would like to contribute, can you assign this to me ?

**Comment by iknlaxmi** [comment]
I would like to add this feature,can you please assign this to me?

**Comment by jainpawan21** [comment]
<img width="793" alt="Screenshot 2023-12-21 at 5 33 06 PM" src="https://github.com/novuhq/novu/assets/39362422/b3911253-80e7-4824-8d83-9edcaf4bf1ef">

Adding design for this issue.
Since many contributors are interested in this issue it's more than 30 days from the last comment.

I will assign it to the first user after this comment.

**Comment by michaldziuba03** [comment]
@jainpawan21 you can assign me
