### ISSUE TITLE
[NV-1953] Encryption of PII

### ISSUE THREAD

**Issue by tmotagam** [novuhq/novu#3118]
- **I'm submitting a...**
   - [ ] bug report
   - [ ] feature request
   - [ ] question about the decisions made in the repository
   - [x] question about how to use this project

- **Summary** Hi I want to use this project in my open source project but the docs does not mention anything about the encryption of the PII is it available in the project or not. If not how can I encrypt the PII that is my question.
- Thanks.

<sub>[NV-1953](https://linear.app/novu/issue/NV-1953/encryption-of-pii)</sub>

**Comment by jainpawan21** [comment]
Hi @tomcastro 
What do you mean by PII?

**Comment by SebastianStehle** [comment]
Personal Identifiable Information (PII)

**Comment by scopsy** [comment]
Hi @tmotagam, at the moment only the provider credentials are encrypted before saving them. The subscriber information is persisted without encryption. 

On our cloud version, encryption at transit and in rest is implemented. 

We are trying to figure out other encrypted fields, but this can introduce an issue with search capabilities, so unfortunately, I don't have any estimates regarding that at the moment. 

Please let me know if that helps and the issue can be closed.

**Comment by tmotagam** [comment]
Hi @scopsy, Thanks for clearing my query. I am closing this issue.
