### ISSUE TITLE
[NV-1959] 🐛 Bug Report: The Notification Center isn't mobile responsive

### ISSUE THREAD

**Issue by tomdaniel-it** [novuhq/novu#3125]
### 📜 Description

The notification center has a fixed width and it goes out of bounds on mobile devices.
This seems like a pretty crucial design requirement to me.

### 👟 Reproduction steps

Open the notification center on a mobile device.

### 👍 Expected behavior

The notification center having the same width as the viewport, with some horizontal margin/padding.

### 👎 Actual Behavior with Screenshots

The notification center going out of bounds on the right side.

![image](https://user-images.githubusercontent.com/22665375/229358510-d92b3985-944b-4111-953c-a082d1644b81.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1959](https://linear.app/novu/issue/NV-1959/🐛-bug-report-the-notification-center-isnt-mobile-responsive)</sub>

**Comment by oba2311** [comment]
Hi @tomdaniel-it , 
At the moment we are focusing on providing API-first approach to allow folks to build the NC as they wish for different devices and platforms. 
That being said - could you elaborate on what are you trying to build? which company?

thanks

**Comment by tomdaniel-it** [comment]
@oba2311 We're building a (sort of) social network for goSolve.org, where users will receive notifications in a notification center. This site will be used by desktop and mobile users.
Since we're currently creating the MVP, we're not creating a custom NC yet and using the one provided by Novu. We've forked it and implemented our own fix to make it more responsive for mobile use, but it's a bit too hacky to create a PR for it.

**Comment by amitanshusahu** [comment]
i would like to work on it if its open, can i get assigned

**Comment by jainpawan21** [comment]
Sure @amitanshusahu. Assigning this to you!

**Comment by amitanshusahu** [comment]
hey @jainpawan21 , i am new to the project & am unable to find where to make changes to fix this, could you help me out to get started :)

**Comment by tomdaniel-it** [comment]
@amitanshusahu I believe you'll need to work in the [AppContent component](https://github.com/novuhq/novu/blob/407a77f2d33e7b534fdf869ea617c3409632b828/packages/notification-center/src/components/notification-center/components/AppContent.tsx). There is a fixed width of 420px. I'd think of something along the lines of creating a container div for the existing div, giving that a 100% width. Then the existing (child) div a width auto and max-width 420px width some x margin/padding

(Not a CSS hero though, there might be a few better solutions.)

**Comment by LetItRock** [comment]
the fix is merged and will be released in the upcoming release ;)

**Comment by gitstart** [comment]
@jainpawan21 I would like to pick this up

**Comment by LetItRock** [comment]
reopening as the merged solution unfortunately doesn't work well

**Comment by gitstart** [comment]
Hi @LetItRock, would it be possible for you to share what doesn't work well and possibly what would be desired so we can work on this again?
