### ISSUE TITLE
[NV-1962] [NV-1898] Missing scrollTo channel in quickstart -> configure provider

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#3129]
### Why? (Context)

Missing the behavior of scrolling to the fitting channel providers in the integration modal

### What?

![Screen Shot 2023-03-22 at 13.49.51.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/db846c3f-0bf3-4eeb-8661-7ac22b7bf9c0/75ff3e61-c71c-4d13-ac85-c6f17d70ef4f)

Opening for Push will open the integration modal at the top, instead of scrolling to the Push section in the modal.

[https://www.loom.com/share/30089e8a907647f19c6a0049974bfb41](https://www.loom.com/share/30089e8a907647f19c6a0049974bfb41)

### Definition of Done

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1898](https://linear.app/novu/issue/NV-1898/missing-scrollto-channel-in-quickstart-configure-provider)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1898](https://linear.app/novu/issue/NV-1898/missing-scrollto-channel-in-quickstart-configure-provider)</sub>

**Comment by gitstart** [comment]
@scopsy @ainouzgali I would like to pick this up.

**Comment by ainouzgali** [comment]
Thank you!! Assigned you @gitstart
