### ISSUE TITLE
[NV-2053] 🐛 Bug Report: Remove Brand logo

### ISSUE THREAD

**Issue by amansaini0003** [novuhq/novu#3137]
### 📜 Description

Not able to remove brand logo completely. As there is no option. we can replace it but can't remove it.

<img width="441" alt="Screenshot 2023-04-04 at 3 34 26 PM" src="https://user-images.githubusercontent.com/48579930/229758739-9cc93e96-b9ac-4500-a478-92b5758d33d6.png">
 

### 👟 Reproduction steps

1. Click on Brand navigation.
2. Add your logo in asset tab
3. After that you can only replace that logo but we can't remove it

### 👍 Expected behavior
When hovering over the brand logo image show the buttons to delete and update the logo. 
Check [the designs here](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=833%3A23889&mode=design&t=wL6gkqUIVAqvkksm-1) and [here](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=849%3A25316&mode=design&t=wL6gkqUIVAqvkksm-1).

**Definition of done**
1. The margins and paddings for the logo body is updated
2. The initial state with icon and description is updated
3. The hover state is updated 
4. The update option is added
5. The hover over Remove or Update options is implemented

### 👎 Actual Behavior with Screenshots

There is no option to remove the brand logo.
<img width="1440" alt="Screenshot 2023-04-04 at 12 14 37 PM" src="https://user-images.githubusercontent.com/48579930/229760088-28f9513d-e707-4c26-908d-df967ed07a32.png">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2053](https://linear.app/novu/issue/NV-2053/🐛-bug-report-remove-brand-logo)</sub>

**Comment by michaldziuba03** [comment]
@jainpawan21 I'm interested to fix this problem.

**Comment by jainpawan21** [comment]
Sure @michaldziuba03 
Let me know if you need any help!

**Comment by ainouzgali** [comment]
@michaldziuba03 Thank you! What do you think about showing a trash icon in top right corner on hover? Tomorrow we can get an approval from our designer

**Comment by michaldziuba03** [comment]
@ainouzgali I think it's fine. I had very similar idea.

**Comment by nknyshov** [comment]
@ainouzgali Could you please create a task in Liner and assign it to me? Once you do it, I will take it into my backlog.

**Comment by ainouzgali** [comment]
@nknyshov  [NV-2053](https://linear.app/novu/issue/NV-2053/%F0%9F%90%9B-bug-report-remove-brand-logo)

**Comment by roniskywalker** [comment]
Hello [LetItRock](https://github.com/LetItRock), I want to work in this issue. Please assign me

**Comment by snehpr966** [comment]
Interested to fix this issue

**Comment by yashnirmal** [comment]
on it

**Comment by yashnirmal** [comment]
Hey @LetItRock , while building the project, one of my build is breaking at `nx run @novu/widget:build`. Can you help me with it.
here is the full error : https://cloud.nx.app/runs/SAZON21Wgs

**Comment by vishalkhoje** [comment]
Please assign this issue to me, I am working on it. I have fully understood the issue.

**Comment by 07tAnYa** [comment]
hey! I want to work on this. Kindly assign this to me.

**Comment by victoriatrinita** [comment]
I would like to work on this issue

**Comment by michaldziuba03** [comment]
@LetItRock can you assign me back, I didn't get any design.

It should be labeled as missing design.

**Comment by nick2432** [comment]
can i work on this?

**Comment by yashnirmal** [comment]
> Hey @LetItRock , while building the project, one of my build is breaking at `nx run @novu/widget:build`. Can you help me with it. here is the full error : https://cloud.nx.app/runs/SAZON21Wgs

Anyone here who can help me with this?

**Comment by 07tAnYa** [comment]
> Hey @LetItRock , while building the project, one of my build is breaking at `nx run @novu/widget:build`. Can you help me with it. here is the full error : https://cloud.nx.app/runs/SAZON21Wgs

you can try the following steps:

1) Clear the npm/yarn cache: 
For npm:
npm cache clean --force
For yarn:
yarn cache clean

2) Delete the node_modules folder and package-lock.json (or yarn.lock) file:
This will remove any potentially problematic dependencies and their lock files. You can delete them using the following commands:
rm -rf node_modules
rm package-lock.json  # or yarn.lock if you're using Yarn

3) Install dependencies again:
For npm:
npm install
For yarn:
yarn install

4) Check your webpack configuration:
The error message indicates an issue with the webpack configuration, particularly related to the webpack-manifest-plugin. Ensure that your webpack configuration is correctly set up. You may want to review your webpack configuration files and ensure they are correctly specifying the required plugins and settings.

5) Update packages:
For npm:
npm update
For yarn:
yarn upgrade

6) If you have a specific webpack configuration file (webpack.config.js or similar), review it for any potential issues and ensure that it's compatible with the versions of webpack and related plugins you are using.

7) Check for breaking changes:
Sometimes, major version updates of packages can introduce breaking changes. Review the release notes for the packages mentioned in the error message (webpack, webpack-manifest-plugin, react-scripts, etc.) to see if there are any breaking changes that might affect your project.

8) Ensure that you have enough available memory for the build process. The --max_old_space_size flag in your command suggests that you are allocating a large amount of memory for the Node.js process. Make sure your system has enough memory available.

**Comment by yashnirmal** [comment]
> > Hey @LetItRock , while building the project, one of my build is breaking at `nx run @novu/widget:build`. Can you help me with it. here is the full error : https://cloud.nx.app/runs/SAZON21Wgs
> 
> you can try the following steps:
> 
> 1. Clear the npm/yarn cache:
>    For npm:
>    npm cache clean --force
>    For yarn:
>    yarn cache clean
> 2. Delete the node_modules folder and package-lock.json (or yarn.lock) file:
>    This will remove any potentially problematic dependencies and their lock files. You can delete them using the following commands:
>    rm -rf node_modules
>    rm package-lock.json  # or yarn.lock if you're using Yarn
> 3. Install dependencies again:
>    For npm:
>    npm install
>    For yarn:
>    yarn install
> 4. Check your webpack configuration:
>    The error message indicates an issue with the webpack configuration, particularly related to the webpack-manifest-plugin. Ensure that your webpack configuration is correctly set up. You may want to review your webpack configuration files and ensure they are correctly specifying the required plugins and settings.
> 5. Update packages:
>    For npm:
>    npm update
>    For yarn:
>    yarn upgrade
> 6. If you have a specific webpack configuration file (webpack.config.js or similar), review it for any potential issues and ensure that it's compatible with the versions of webpack and related plugins you are using.
> 7. Check for breaking changes:
>    Sometimes, major version updates of packages can introduce breaking changes. Review the release notes for the packages mentioned in the error message (webpack, webpack-manifest-plugin, react-scripts, etc.) to see if there are any breaking changes that might affect your project.
> 8. Ensure that you have enough available memory for the build process. The --max_old_space_size flag in your command suggests that you are allocating a large amount of memory for the Node.js process. Make sure your system has enough memory available.

Thanks @07tAnYa , clearing cache worked for me

**Comment by LetItRock** [comment]
> @LetItRock can you assign me back, I didn't get any design.
> 
> It should be labeled as missing design.

@michaldziuba03 I updated the description with the links to the design some time ago, but forgot to mention you :) anyway assigning this one back to you :)
