### ISSUE TITLE
[NV-2057] 🚀 Feature: Get topics of subscriber

### ISSUE THREAD

**Issue by szbartnik** [novuhq/novu#3142]
### 🔖 Feature description

Hi! In our use case it would be helpful to be able to list all subscribers added to a specific topic.

### 🎤 Why is this feature needed ?

Currently there is no way to do it. I believe there might be more people who may find it helpful to get such data efficiently.

Another reason is that it will be useful in development. Currently no UI exists where topics are visible so even when you have only 10 topics and each of them has 10 added subscribers it's not very easy to immediately make sure where a specific subscriber belongs.

### ✌️ How do you aim to achieve this?

Currently the `GET /v1/topics` endpoint has 3 optional query parameters:
- `page`
- `pageSize`
- `key` (topic key)

I was thinking about adding another optional query parameter: `subscriberId` which will narrow the results to include only topics which have a provided subscriber added.

### 🔄️ Additional Information

Workarounds:
- Listing all topics using `GET /v1/topics` endpoint & aggregate the results which is inefficient
- Implementing custom topic abstraction logic & do not use the one Novu provides

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2057](https://linear.app/novu/issue/NV-2057/🚀-feature-get-topics-of-subscriber)</sub>

**Comment by gitstart** [comment]
@davidsoderberg I would like to pick this up cc @scopsy

**Comment by kgrimsby** [comment]
Could I also add that adding a wildcard to the `key` param would help?

We have topics like this: `itemA:signalA`, `itemA:signalB` and so on. If we could query `key=itemA:*` and `subscriberId=xxx` that would be really helpfully.

**Comment by gitstart** [comment]
> Hi @gitstart Are you still interested to work on this?

Sure @jainpawan21

**Comment by shafikmevrik** [comment]
Is this feature is done?? or still pending?

**Comment by gitstart** [comment]
> Is this feature is done?? or still pending?

There is a PR up for it here

https://github.com/novuhq/novu/pull/3551

**Comment by bartelemi** [comment]
We would still love to see this implemented, but looks like the original PR by @gitstart has been closed and branch has been deleted. Is it going to be prioritized or should we look into proposing our own PR?

**Comment by scopsy** [comment]
We have released an update to the get subscriber by id endpoint to allow passing the `includeTopics=true` query param:

```
GET /v1/subscribers/:subscriberId?includeTopics=true
```

This will return a list of the subscribers topics. @bartelemi and the rest of the issue participants let me know if that helps you!
