### ISSUE TITLE
[NV-2060] 🐛 Bug Report: Incomplete i18n

### ISSUE THREAD

**Issue by david-morris** [novuhq/novu#3154]
### 📜 Description

![image](https://user-images.githubusercontent.com/5530960/230081664-875895fe-48ef-4864-9d71-e6b4181a6f56.png)
Some text ("Nothing new to see here yet") shows despite having selected `i18n="de"`.

### 👟 Reproduction steps

1. Use the React tooling as in the tutorial
2. add `i18n` parameter to the `NovuProvider`

### 👍 Expected behavior

Language should be consistent throughout Novu when i18n is explicitly chosen in the NovuProvider.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/5530960/230082184-7578d4c0-c631-493b-8214-e59bb06e7ad5.png)
The original English caption is shown.

### 📃 Provide any additional context for the Bug.

Looking at the exported types, it appears that this text is missing from your i18n system.
However, it still will be displayed on the client panel, so it should be translatable.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2060](https://linear.app/novu/issue/NV-2060/🐛-bug-report-incomplete-german-i18n)</sub>

**Comment by jainpawan21** [comment]
Hi @david-morris 
Unfortunately, this text is part of image asset. So it will not change with language change
https://github.com/novuhq/novu/blob/next/packages/notification-center/src/images/no-new-notifications.png

**Comment by david-morris** [comment]
Hi @jainpawan21 
Great work! 
So all that's needed is to crop the image and add a localized text panel in NotificationsListTab.tsx?
That would also mean that the theme could change the font and color, and screenreader users would be able to get explicit confirmation that their inbox is empty.

**Comment by jainpawan21** [comment]
Yes, I think this should work
cc:- @LetItRock

**Comment by gitstart** [comment]
@david-morris @jainpawan21 I would like to pick this up Cc @scopsy
