### ISSUE TITLE
[NV-2067] 🐛 Bug Report: Network Error after clicking Signup Button.

### ISSUE THREAD

**Issue by palashbasik** [novuhq/novu#3162]
### 📜 Description

When deploying from novu/docker/local/deployment, after clicking signup button it gives "Network Error". 
Also, when depoying from novu/docker/kubernetes/kustomize, after clicking signup button it gives "Network Error". 

### 👟 Reproduction steps

Deploying using docker-compose.
1. Clone https://github.com/novuhq/novu
2. In, novu/docker/local/deployment
3. docker-compose up -d
4. In Mozilla Firefox Browser, http://localhost:4200
5.  Click on SignUp Button.
6. Fill in the details.
7. Click Sign Up.

Deploying using kustomize.
1. Clone  https://github.com/novuhq/novu
2. In, novu/docker/kubernetes/kustomize
3. kubectl apply -f kustomization.yaml
4. In Mozilla Firefox Browser, http://localhost:4200
5.  Click on SignUp Button.
6. Fill in the details.
7. Click Sign Up.

### 👍 Expected behavior

Sign up should be successful.

### 👎 Actual Behavior with Screenshots

![novu-docker-ps](https://user-images.githubusercontent.com/105476638/230605176-511d99f7-b008-451b-8c49-0b03c5c2e11c.png)
![novu-signup-network-error](https://user-images.githubusercontent.com/105476638/230605185-4ec83089-b047-4903-850c-1ccfb5cff4e0.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2067](https://linear.app/novu/issue/NV-2067/🐛-bug-report-network-error-after-clicking-signup-button)</sub>

**Comment by jainpawan21** [comment]
Hi @palashbasik 
I see there is CORS error in network tab
Did you check, If your API is running on port 3000?

**Comment by palashbasik** [comment]
Thanks, for docker it works.

**Comment by darkterminal** [comment]
> 

How about if I use other port? When I change the `.env` file related ports:
```env
# Ports
API_PORT=5015
REDIS_PORT=6379
REDIS_CACHE_SERVICE_PORT=6379
WS_PORT=3022

# Root URL
REACT_APP_WS_URL=http://localhost:3022
# Uncomment this one when deploying Novu in the local environment
# as Web app local Dockerfile will have to load this to be used.
# Deployment version doesn't need as we inject it with API_ROOT_URL value.
REACT_APP_API_URL=http://localhost:5015
API_ROOT_URL=http://localhost:5015
DISABLE_USER_REGISTRATION=false
FRONT_BASE_URL=http://client:4200
WIDGET_EMBED_PATH=http://localhost:4701/embed.umd.min.js
WIDGET_URL=http://localhost:4500
```

It's still causing CORS.

**Comment by HanumanthaRAON** [comment]
We are also facing same issue while api service is running on 3000 port , can someone please check an
![image](https://user-images.githubusercontent.com/20111534/235901081-37550ce3-9f29-4527-8b8f-74dc85add2d3.png)
d help

**Comment by jainpawan21** [comment]
@HanumanthaRAON 
If you see in console, your self hosted novu client is making api call on localhost:3000
but it should make call on your http://<your_self_host_ip>:3000

Which version of novu you are using?
We fixed this issue in 0.13.0 release

**Comment by HanumanthaRAON** [comment]
We have installed 0.14.0 version of Novu. Even I am trying access myip:3000/v1/auth/register directly from browser getting 400 error code

![image](https://user-images.githubusercontent.com/20111534/236005125-29326721-bb05-4419-b4b8-29a0baab7f2d.png)

When Check in my server 3000 port is opened , please help me to resolve the issue

**Comment by jainpawan21** [comment]
Hi @HanumanthaRAON 
This endpoint has `POST` method
https://github.com/novuhq/novu/blob/e98836cd2fa44d829892e8300aa570aa3b12253a/apps/api/src/app/auth/auth.controller.ts#L139

**Comment by masc-be** [comment]
Like @jainpawan21 wrote, your POST request pointed to localhost. But your API-Server running on a different server. I had the same problem and i found the variable (API_ROOT) in apps/web/src/config/index.ts which holds the server address. For fix your issue edit the file.
change from:
`: window._env_.REACT_APP_API_URL || process.env.REACT_APP_API_URL || 'http://localhost:3000';`
to:
`: window._env_.REACT_APP_API_URL || process.env.REACT_APP_API_URL || 'http://<YOUR_IP>:3000';`

restart novu and check
