### ISSUE TITLE
[NV-2096] 🚀 Feature: Use environment variable for integration credentials (self-hosted)

### ISSUE THREAD

**Issue by FlxEd** [novuhq/novu#3179]
### 🔖 Feature description

I find that Novu is a very powerful tool to centralize providers !
But it makes it as well a riskier place as all the credentials involved are centralized in the Integration Store.

When I configure an integration, I would like to retrieve its credentials from Novu's environment variables:

![image](https://user-images.githubusercontent.com/42470798/231225001-7642d597-ba04-4cf6-b756-06a49e375339.png)

### 🎤 Why is this feature needed ?

It avoids displaying secrets and credentials to the Novu console users.
Only the engineer in charge of self-hosting has access to the integration credentials.

### ✌️ How do you aim to achieve this?

Parse template strings sent from the front-end dialog boxes inside the back-end and match them with Novu's environment variables.

### 🔄️ Additional Information

I tried what you can see on the screenshot with the matching variable in my .env file but could not make this work.
I also searched in the Docs and the Github issues, but could not find anything about it.

Please point out the correct way to achieve this in case I missed it.
Thank you for your amazing work !

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2096](https://linear.app/novu/issue/NV-2096/🚀-feature-use-environment-variable-for-integration-credentials-self)</sub>

**Comment by scopsy** [comment]
Unfortunately, at this moment I won't believe that we will implement something like this as we are planing to implement multiple provider implementations per channel, and for multi-tenant scenarios fetching it from the environment will create quite a lot of troubles.

I will keep monitoring this need in the future, and might rethink this a bit later. Appreciate your feedback 🙏
