### ISSUE TITLE
Add async module configuration to @notifire/nest

### ISSUE THREAD

**Issue by talShtark** [novuhq/novu#318]
## What?
Add the ability the configure the NotifireModule using factory method or class 

## Why?
In most cases, notifire providers must be configured with some secret like API Key.
These values are usually found in the environment and in Nestjs architecture, typically supplied by some configService (or other async modules).
In order to be able to pass these values in runtime to the NotifireModule, please provide some method to configure this module asynchronously.

## How?
Support a "forRootAsync" method that accepts asyncModuleConfig to create the dynamicModule.

## Additional Info
Another possibility is to use [nestjs-modules](https://www.npmjs.com/package/@golevelup/nestjs-modules) package to reduce the boilerplate necessary to create the module.

**Comment by scopsy** [comment]
Hi @talShtark thanks for adding this one, so if I understand correctly we need to modify our @notifire/nest module to support this correct? 

I'll add a need help label for it maybe some can help with it, currently busy releasing the new admin panel so probably won't be able to implement this myself in the near time.

If this is something you really need ping me, I'll try to find time :) Or feel free to open a PR if you familiar with the API.

**Comment by ninjadev101** [comment]
@scopsy I can work on this.

**Comment by davidsoderberg** [comment]
This could maybe guide someone to fix this issue: 
https://dev.to/tkssharma/creating-dynamic-modules-in-nest-js-part-2-g1j

**Comment by shahriar-shojib** [comment]
I would like to work on this
