### ISSUE TITLE
[NV-2121] 🚀 Feature: Need to login to novu using different login method like Google login (Oauth), keycloak and jumpcloud  

### ISSUE THREAD

**Issue by chethankumar4046** [novuhq/novu#3200]
### 🔖 Feature description

I have configured  keycloak and jumpcloud in our organisation, to configure login in mechanism in different application, 
keycloak and jumpcloud is helping in create and monitor users and roles so if i have ability to configure  keycloak or jumpcloud in novu will he more help full in general, Thanks  

### 🎤 Why is this feature needed ?

create new using will be centralised  

### ✌️ How do you aim to achieve this?

Need to login to novu using different login method like Google login (Oauth), keycloak and jumpcloud  

### 🔄️ Additional Information

Need to login to novu using different login method like Google login (Oauth), keycloak and jumpcloud  

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2121](https://linear.app/novu/issue/NV-2121/🚀-feature-need-to-login-to-novu-using-different-login-method-like)</sub>

**Comment by jainpawan21** [comment]
Similar to https://github.com/novuhq/novu/issues/2819
