### ISSUE TITLE
[NV-2123] 🚀 Feature: Add email sender name to overrides

### ISSUE THREAD

**Issue by p13lgst** [novuhq/novu#3202]
### 🔖 Feature description

Similar to how we can override the from email, it would be great if it's also supported to override the sender name, at the moment of triggering the notification

### 🎤 Why is this feature needed ?

So we can have a dynamic sender name without needing a template variable (which is also not yet supported: #3180). 

### ✌️ How do you aim to achieve this?

It could be added by a `senderName` property in the `IEmailOverrides`, and also using it if provided to override the sender name with the current from email override.

### 🔄️ Additional Information

None

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2123](https://linear.app/novu/issue/NV-2123/🚀-feature-add-email-sender-name-to-overrides)</sub>

**Comment by scopsy** [comment]
This was implemented as part v0.14.0 🙏 A pr already was merged so this could be used as:
```
{
  overrides: {
     email: {
        senderName: 'Name'
     }
  }
}
```
