### ISSUE TITLE
[NV-2124] 🐛 Bug Report: quick start instructions for Docker incorrect

### ISSUE THREAD

**Issue by chrisj-back2work** [novuhq/novu#3205]
### 📜 Description

Instructions for docker quick setup do not work

### 👟 Reproduction steps

Visit [](https://docs.novu.co/overview/docker-deploy)

This line references a file that doesn't exist:
`docker-compose -f ./local/deployment/docker-compose.redis-cluster.yml up`

There is a file of that name under `development` but not `deployment`

I try the same instructions substituting the directory name -- `localhost:4200` shows a login screen

Is there a default user ID and password? If yes it's not addressed in the doco

Attempting to use the Sign Up option results in : network error

(nearly the same incorrect content exists in https://github.com/novuhq/novu/tree/main/docker; it references a different file that doesn't exist)

### 👍 Expected behavior

Should reference files that exist

Should be available on localhost:4200

Should either not require login, or have a signup that works

### 👎 Actual Behavior with Screenshots

Cannot be carried out as written

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2124](https://linear.app/novu/issue/NV-2124/🐛-bug-report-quick-start-instructions-for-docker-incorrect)</sub>

**Comment by jainpawan21** [comment]
Hi @chrisj-back2work 
Can you please error you are getting in network tab?

**Comment by amirali-ashraf** [comment]
I can help with that.

If you try the method which is mentioned in the docs first it does not find the docker compose fine in the directy.

https://docs.novu.co/overview/docker-deploy/

The I tried to run the compose file by this:

```bash
$ docker-compose up -f novu/docker/local/deployment/docker-compose.yml up
```

It worked but then it was complaining about new_relic app name and licence.

Hope it helps.

**Comment by p-fernandez** [comment]
@amirali-ashraf could you share the error logs that you get for the New Relic missing app and it is license?
And another question, does that stop you from running Novu properly? Like the Docker container exits?

**Comment by KaptinLin** [comment]
it's not working when i try https://docs.novu.co/overview/docker-deploy

Attempting to use the Sign Up option results in : network error

**Comment by p-fernandez** [comment]
Closing as stale and not feedback. Please feel free to reopen if still need of help. 🙏🏻
