### ISSUE TITLE
[NV-2136] 🐛 Bug Report: Novu Provider is not working properly.

### ISSUE THREAD

**Issue by xiangdev1016** [novuhq/novu#3234]
### 📜 Description
export const Notification = () => {
  const wallet = useWallet(FANTOM);

  return wallet.connected ? (
    <NovuProvider
      subscriberId={wallet.address.toLocaleLowerCase()}
      applicationIdentifier={NOVU_APP_ID}
      initialFetchingStrategy={{ fetchNotifications: true }}
    >
      <CustomNotificationCenter />
    </NovuProvider>
  ) : (
    <></>
  );
};

This is my code snippet that retrieves a wallet address. When I change the wallet, I can obtain a different wallet address.

I am currently utilizing the wallet address as the subscribeId. It works correctly the first time. As you can see, I'm using wallet address for each subscribeId

However, when I change the wallet, the notification payload data does not update based on the new subscribeId. I have checked the onLoad function in NovuProvider and it is only called once.

Additionally, I am using the useNotification() hook function on the CustomNotificationCenter component using the @novu/notification-center library.

I have attempted to use the refetch function in useNotification, which works, but the NovuProvider is not functioning as expected.

Are there any other options to manually refetch notification payload  data based on subscribeId using useNotification or other methods?

### 👟 Reproduction steps

1. connect wallet
2. fetch notification first time
3. change wallet
At that time, it's not fetching notification payload data from novu provider

### 👍 Expected behavior

It should be clear the old subscriber's notifications, and then have to be fetch new notification payload data based on new wallet.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/94132651/232785527-d8e3e6a7-4d3b-4008-96c0-9c3f628985fd.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2136](https://linear.app/novu/issue/NV-2136/🐛-bug-report-novu-provider-is-not-working-properly)</sub>

**Comment by LetItRock** [comment]
hey @xiangdev1016! 👋 I do confirm that the issue exists. 
The session is initialized, but we don't refetch the organization info, unseen notifications, and the feed.

@xiangdev1016 do you want to contribute?

**Comment by gitstart** [comment]
@xiangdev1016 @LetItRock I would like to pick this up

**Comment by ainouzgali** [comment]
Thanks @gitstart ! Assigned you

**Comment by gitstart** [comment]
> > @xiangdev1016 @LetItRock I would like to pick this up cc @scopsy
> 
> Please let me know once you fixed this issue. Thanks @gitstart

Sure @xiangdev1016

**Comment by LetItRock** [comment]
hey @xiangdev1016 👋 @gitstart is working on it, when the code will be ready for the review you will see the PR linked to this issue ;)
