### ISSUE TITLE
[NV-2162] 📚 Docs Feedback: Unreleased methods in @novu/headless on `next` branch are present in current docs

### ISSUE THREAD

**Issue by zeferinix** [novuhq/novu#3277]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/notification-center/headless/api-reference

### Kind of issue

Broken demonstration

### Issue description

I was reading the reference for the Headless API and was experimenting on how each method would behave only to find out some methods doesn't exist in the latest release (v0.13.0) yet is present in the current docs. These are the only methods available on the said version:

![image](https://user-images.githubusercontent.com/6721822/233851146-7f093fe0-a82a-4b1f-bf78-6ab2168e9baa.png)

Particularly interested on how these other methods would behave exactly since it's ambiguous to me the difference between "**seen**" and "**read**".

![image](https://user-images.githubusercontent.com/6721822/233851237-03718796-b2b7-4b65-b303-ba1f747efca8.png)

~~On another note, what's the difference between **seen** and **read** exactly?~~ Found the [relevant docs](https://docs.novu.co/platform/step-filter#subscriber-seen--read-filters) now. Have always found this to be very contextual thus the question but I suppose if there's no 2-step, it doesn't matter which one the devs use. Unless the Novu platform does something special behind the scenes? Or are they just simply flags and up to the devs how to use/interpret it?

### Context 🔦

Was gonna try the Vue Component with Nuxt3 but just can't make it work as I'm getting various warnings and errors from multiple attempts to fix the chain of errors. Not to mention, the customizability is limited outside of React (and the Web Component) so went to explore the Headless API instead.

<sub>[NV-2162](https://linear.app/novu/issue/NV-2162/📚-docs-feedback-unreleased-methods-in-novuheadless-on-next-branch-are)</sub>

**Comment by BiswaViraj** [comment]
@zeferinix, The new version of the `headless` package will be released by tomorrow, including those new methods.
Also, please share the errors/warnings you faced while using the Vue component.
