### ISSUE TITLE
[NV-2164] Pulling docker image requires authentication

### ISSUE THREAD

**Issue by marsouin** [novuhq/novu#3279]
Hi! Same issue here with `ERROR: Head "https://ghcr.io/v2/novuhq/novu/worker/manifests/0.13.0": unauthorized`
Thanks!

_Originally posted by @marsouin in https://github.com/novuhq/novu/issues/512#issuecomment-1520534841_
            

<sub>[NV-2164](https://linear.app/novu/issue/NV-2164/pulling-docker-image-requires-authentication)</sub>

**Comment by scopsy** [comment]
Hi @marsouin we are in the middle of the new version release deployment. In a couple of hours it will be available for download. Sorry for the inconvenicnce
