### ISSUE TITLE
[NV-2166] 🚀 Feature: .NET SDK

### ISSUE THREAD

**Issue by Badabum** [novuhq/novu#3283]
### 🔖 Feature description

Hi, I didn't find .NET SDK among the available ones. Would be nice to have it.

### 🎤 Why is this feature needed ?

To simplify integration with novu for .net developers and teams using this platform.

### ✌️ How do you aim to achieve this?

Ideally, the end result would be a NuGet package published to nuget.org. Name can be `Novu.Sdk` or `Novu.Client`. 
Feature-wise not sure yet what are the most used/critical ones.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2166](https://linear.app/novu/issue/NV-2166/🚀-feature-net-sdk)</sub>

**Comment by Badabum** [comment]
If nobody started on this I can as well work on this sdk on spare time

**Comment by Badabum** [comment]
@scopsy sorry for tagging you directly, but will it be ok for you to create repo like `novu-dotnet` for .net sdk?

**Comment by Badabum** [comment]
@unicodeveloper let me know if I can help in any way with this

**Comment by unicodeveloper** [comment]
@Badabum please use https://github.com/novuhq/novu-dotnet

**Comment by unicodeveloper** [comment]
@Badabum we need help with more features, so please let me know if you will like to contribute. Feel free to take up any of the issues.
