### ISSUE TITLE
[NV-2169] 🐛 Bug Report: Header missing `screen` argument and React identity

### ISSUE THREAD

**Issue by david-morris** [novuhq/novu#3286]
### 📜 Description

There's no React-y way to tell what the current `screen` (i.e. are we looking at notifications or settings?) is from the `header`.

This is because we aren't supplied the current state as a prop, it's not in a context, and the component identity of the header isn't preserved when we `setScreen`.

### 👟 Reproduction steps

Supply a custom `header` and try to make a button that changes icons and toggles the current screen with `setScreen`.

### 👍 Expected behavior

The `header` should be given all props it needs to do its job, and its identity should be preserved between render so we can do react things like state.

### 👎 Actual Behavior with Screenshots

The `header` isn't given the `screen` prop, and its identity is not preserved when you switch the `screen`.

### 📃 Provide any additional context for the Bug.

https://github.com/novuhq/novu/blob/6e802807fbb97d3d1b41934fdefa6d87d879ce71/packages/notification-center/src/components/notification-center/components/layout/Layout.tsx#L28
- `header` should be invoked differently (i.e. as a react component with a key) to preserve its identity render-to-render
- `header` should be supplied with the current state as a prop

This bugfix might interact with #3285

Workaround:
If you make a global variable holding the current `screen` that gets reset to `ScreenEnum.NOTIFICATIONS` when you click the bell, you can have the current screen as a non-reactive value.
If you need it to be reactive, you can probably make some other workaround, but I haven't tried.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2169](https://linear.app/novu/issue/NV-2169/🐛-bug-report-header-missing-screen-argument-and-react-identity)</sub>

**Comment by LetItRock** [comment]
hi @david-morris 👋 
The `header` prop (and a few other props) is the "render prop", basically the function that returns the React Element. These functions are called on every render, and it's not safe to use react hooks in its body, because it doesn't have an "identity". Instead what you should do is you need to create your own component and return the React Element from the header render prop function, like this:
```
<NotificationCenter
  ...
  header={({ setScreen }) => <YourCustomHeader setScreen={setScreen} />}
/>
```
Then the hooks, state, etc. will work.
I do agree that we should also supply the `screen` prop.

**Comment by LetItRock** [comment]
For anyone who will be working on this ticket, please make sure that the docs are updated with an appropriate interface for the `header` render prop.

**Comment by david-morris** [comment]
hi @LetItRock ,

When I invoke my header as a render prop `header={({ setScreen }) => <Header {...{ setScreen }} />}` and add `useEffect(() => console.log("I'm mounting"), [])` to my header, I can see that my header is still mounting whenever I change between the notifications view and the settings view.

By adding a console log outside of a hook, I can see that other changes, such as receiving a new notification, cause the Layout and thus the Header to rerender, but not mount new, so in that case, the identity is stable.

I think this might have to do with the `header({ setScreen })` being called inside the `screen === ScreensEnum. ...` conditional renders rather than outside.  But I don't quite understand the rules of render props having stable identity.

Or is unstable identity just a normal property of render props?

Sorry if this is off-topic.

**Comment by LetItRock** [comment]
> hi @LetItRock ,
> 
> When I invoke my header as a render prop `header={({ setScreen }) => <Header {...{ setScreen }} />}` and add `useEffect(() => console.log("I'm mounting"), [])` to my header, I can see that my header is still mounting whenever I change between the notifications view and the settings view.
> 
> By adding a console log outside of a hook, I can see that other changes, such as receiving a new notification, cause the Layout and thus the Header to rerender, but not mount new, so in that case, the identity is stable.
> 
> I think this might have to do with the `header({ setScreen })` being called inside the `screen === ScreensEnum. ...` conditional renders rather than outside. But I don't quite understand the rules of render props having stable identity.
> 
> Or is unstable identity just a normal property of render props?
> 
> Sorry if this is off-topic.

hey @david-morris 👋 

You are totally right, I've checked the code and I did a quick test and I see that it's remounting whenever the `screen` state changes, but it shouldn't. 
It's not the render prop issue but how React sees the changes in the tree and how does recalculate it. In our case, these two conditions are causing it:
```
<div>
{screen === ScreensEnum.SETTINGS && (
     {header}
      ... 
 )}
 {screen === ScreensEnum.NOTIFICATIONS && (
     {header}
      ...
)}
</div>
```

So like when the screen is `ScreensEnum.SETTINGS` React sees it like this (super simplified):
```
<div>
{header}
{false}
</div>
```   

and when the screen is `ScreensEnum.NOTIFICATIONS` it sees that the tree has changed, so it needs to unmount the previous `header` which became `false` and mount the new `header` in place of `false`:
```
<div>
{false}
{header}
</div>
```

So the appropriate solution here should be like this:
```
<div>
{header}
{screen === ScreensEnum.SETTINGS ? (
   ...
): (
   ...
)}
</div>
```

The "identity" of the header is preserved by React between re-renders unless the header render prop function returns the same component type. 

I hope it clarifies things ;)

**Comment by LetItRock** [comment]
for anyone who will be working on this, the list of changes that have to be done:
- the `NotificationCenter` render prop `header` should supply the `screen, setScreen` args
- the types and docs should be updated accordingly
- the `Layout` component body should be changed to the solution similar to this suggestion:
```
<div>
{header}
{screen === ScreensEnum.SETTINGS ? (
   ...
): (
   ...
)}
</div>
```

**Comment by gitstart** [comment]
@david-morris @LetItRock I would like to pick this up cc @scopsy

**Comment by LetItRock** [comment]
> @david-morris @LetItRock I would like to pick this up cc @scopsy

@gitstart assigned it to you ;)
