### ISSUE TITLE
[NV-2170] 🐛 Bug Report: Broken workflow on the Changes page

### ISSUE THREAD

**Issue by phlrss** [novuhq/novu#3287]
### 📜 Description

Promoting an old change on a now-deleted template will re-create the template in prod in a non-deletable state.
If a template reaches a state where it exists only in prod and not in development, it is impossible to disable, delete, or modify.

### 👟 Reproduction steps

1. Disable a notification in Development
2. Delete a notification in Development
3. Go on the Changes page
4. Promote the "delete" change
5. Promote the "disable" change

### 👍 Expected behavior

The template should be deleted in Production and all related-pending changes to that template should be gone from the Changes list
It would also be greatly beneficial to be able to "Discard" changes and not only "Promote" them

### 👎 Actual Behavior with Screenshots

- The template no longer exists in development, but exists in production and cannot be deleted (not even through the API)
- All older pending changes that have not been promoted are still lingering in the Changes table and can be promoted
- The template which now only exists in production cannot be modified at all

![image](https://user-images.githubusercontent.com/46248889/234359945-883fa715-bcb6-4b37-be23-0ec4f9175768.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2170](https://linear.app/novu/issue/NV-2170/🐛-bug-report-broken-workflow-on-the-changes-page)</sub>

**Comment by jainpawan21** [comment]
@davidsoderberg
