### ISSUE TITLE
[NV-2171] 🚀 Feature: Accept br single line tags in Editor mode

### ISSUE THREAD

**Issue by nocodeventure** [novuhq/novu#3288]
### 🔖 Feature description

The feature request is to add a br tag inside email templates for notifications on Github. This will allow users to add line breaks in the notification emails, making them easier to read and understand. The br tag should be added in a way that it does not break any existing functionality of the email templates.

### 🎤 Why is this feature needed ?

Email notifications are an essential part of Novu's functionality, as they allow users to stay up-to-date with changes and updates to repositories. However, sometimes the notifications can be challenging to read, especially when they contain a lot of text. Adding a br tag to the email templates will make it easier for users to read and understand the notifications they receive.

### ✌️ How do you aim to achieve this?

To add a br tag inside email templates for notifications on Github, the following steps can be taken:

1. Identify the email templates that need the br tag added.
2. Modify the code of those email templates to include the br tag where necessary.
3. Test the changes thoroughly to ensure that the br tag is working as expected and does not break any other functionality.
4. Submit a pull request to the Github repository with the modified code.

### 🔄️ Additional Information

The addition of a br tag in email templates for notifications is a relatively simple feature request that will provide significant benefits to users. It is a commonly used HTML tag and should not pose any significant challenges in implementation. Testing should be thorough to ensure that it does not break any existing functionality.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2171](https://linear.app/novu/issue/NV-2171/🚀-feature-accept-br-single-line-tags)</sub>

**Comment by jainpawan21** [comment]
Hi @nocodeventure <br /> tag is working in email template editor
https://user-images.githubusercontent.com/39362422/234631948-89c3ad56-a531-4a8e-8007-40993ebf48a4.mov

**Comment by nocodeventure** [comment]
@jainpawan21 That's correct using custom code, but not in the Editor mode!

**Comment by jainpawan21** [comment]
Editor mode just supports text, you can not use html tags there

**Comment by nocodeventure** [comment]
I understand, that's the reason we added this as a ticket. For us to use the custom editor, we'll need to customize the content and design with HTML.

HTML tags would be great to have on the editor mode.

**Comment by codingmickey** [comment]
There is already a discussion going on in #3268 about the changing of the email editor and I feel this would be a small use case of it if I'm not wrong.. so if you have any inputs to give there too

**Comment by scopsy** [comment]
Defiently aggree with @codingmickey, this will be handled at the wysiwig level, as the current email custom editor lacks a lot of other functionality aswell. I will mark this ticket as a reference with #3268
