### ISSUE TITLE
[NV-2195] 🐛 Bug Report: Visual bug in Add filter button icon

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#3313]
### 📜 Description

It's small visual bug. Icon doesn't change color on theme change.

### 👟 Reproduction steps

1. Navigate to template editor
![image](https://user-images.githubusercontent.com/43048524/235541053-c65ba43d-f4f2-41a5-a525-a54d05d0f7f6.png)

2. Set theme to light
![image](https://user-images.githubusercontent.com/43048524/235541322-f446d488-48a2-4f64-ba96-83c1ba4a30f1.png)

### 👍 Expected behavior

Icon should change color to keep contrast after theme change.

### 👎 Actual Behavior with Screenshots

Look at **Add filter** button:

![dark](https://user-images.githubusercontent.com/43048524/235540031-e906efed-ab52-401d-9900-d10f52e9ff28.png)
![light](https://user-images.githubusercontent.com/43048524/235539949-3a7bdc3d-6847-4074-b614-b2d788374623.png)

As we can see - the icon doesn't change color when changing the theme.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2195](https://linear.app/novu/issue/NV-2195/🐛-bug-report-visual-bug-in-add-filter-button-icon)</sub>

**Comment by himanshu1221** [comment]
Can I work on this issue?

**Comment by scopsy** [comment]
Sure @himanshu1221, assigning you 🚀

**Comment by himanshu1221** [comment]
hey @scopsy can you guide me on how I can setup this up in gitpod

**Comment by scopsy** [comment]
Haven't used GitPod in a while now :( But you will only need to run the @novu/api and @novu/web projects to see this.

**Comment by gitstart** [comment]
@scopsy is this issue still available for pickup?

**Comment by himanshu1221** [comment]
> @scopsy is this issue still available for pickup?

I am working on it @gitstart

**Comment by gitstart** [comment]
> > @scopsy is this issue still available for pickup?
> 
> I am working on it @gitstart

Alright

**Comment by gitstart** [comment]
Are you still working on this? @himanshu1221

**Comment by gitstart** [comment]
@jainpawan21 we would like to work on this.

**Comment by harshhere905** [comment]
hey can i take the issue. I would like to work on it

**Comment by snehpr966** [comment]
Would like to fix it

**Comment by victoriatrinita** [comment]
I would like to work on this issue

**Comment by vishalkhoje** [comment]
Kindly assign this issue to my name. I am presently engaged in addressing a related matter, as it pertains not only to a filter but also involves various other issues concerning light theme icons. I am committed to rectifying all of these issues comprehensively.

**Comment by vishalkhoje** [comment]
Hello @michaldziuba03  @jainpawan21 

Link to PR: https://github.com/novuhq/novu/pull/4356

I've included screenshots and a video to provide additional context and details regarding the fix for this visual bug. Please take a look.

Thank you! 🙏🏼

**Comment by ASCE-D** [comment]
Hey Devs I would like to contribute can you please assign me this issue

**Comment by sidonweb** [comment]
Hello! I'd like to contribute to this issue. Can you assign me this?

**Comment by davidsoderberg** [comment]
Hi @harshhere905 are you ready to work on this one?

**Comment by vishalkhoje** [comment]
Hi @davidsoderberg ,
If possible can you able to consider or please check my PR: #4356 
I raised it PR yesterday.
Thank you!

**Comment by harshhere905** [comment]
yes @davidsoderberg please assign me this task

**Comment by davidsoderberg** [comment]
@harshhere905 you are now assigned to this task :)

**Comment by harshhere905** [comment]
@davidsoderberg please unassign me this task

**Comment by vishalkhoje** [comment]
Please assign me @davidsoderberg 
I have already raised the pr for this. 
Thanks

**Comment by davidsoderberg** [comment]
@snehpr966 are you ready to work on this?
