### ISSUE TITLE
[NV-2211] 🚀 Feature: Whatsapp as a new chat channel

### ISSUE THREAD

**Issue by kiranvpawar** [novuhq/novu#3327]
### 🔖 Feature description

Novu consumers should be able to send Whatsapp messages using Novu. I am looking forward to a feature where one can use platforms such as twillio to integrate with or send messages using Whatsapp.

### 🎤 Why is this feature needed ?

Many companies use whatsapp to communicate with customers. It would be a great value addition to Novu infrastructure.

### ✌️ How do you aim to achieve this?

Twillio offers APIs to send messages using Whatsapp as a channel. More info here - https://www.twilio.com/docs/whatsapp/tutorial

So we can add one more chat channel into Novu to send messages using Twillio APIs.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2211](https://linear.app/novu/issue/NV-2211/🚀-feature-whatsapp-as-a-new-chat-channel)</sub>

**Comment by scopsy** [comment]
Will keep tracking this here: #1019
