### ISSUE TITLE
[NV-2218] 🐛 Bug Report: `npx novu init` command quits before user can answer

### ISSUE THREAD

**Issue by melon-husk** [novuhq/novu#3336]
### 📜 Description

When I run `npx novu init` command in powershell terminal on windows 10, the process quits before I could answer the first question.

### 👟 Reproduction steps

1. Open Windows Terminal App(powershell)
2. Run `npx novu init`

### 👍 Expected behavior

It should wait at the first question and not quit.

### 👎 Actual Behavior with Screenshots

It just quits before I could answer the first question, I've attached the video below
https://user-images.githubusercontent.com/30780724/236293006-42491827-0ece-4d19-8976-70f5e2aacb8a.mp4

### 📃 Provide any additional context for the Bug.

I've mentioned this issue in this closed issue, 
https://github.com/novuhq/novu/issues/2504#issuecomment-1518894100

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2218](https://linear.app/novu/issue/NV-2218/🐛-bug-report)</sub>

**Comment by Cliftonz** [comment]
@melon-husk Can you run this script and upload the NovuDebug.txt file it outputs? 
This will only collect Powershell version and OS version details.
``` powershell
$ComputerInfo = Get-ComputerInfo | Select-Object OsName, OsType, OsVersion, CsSystemType,  WindowsProductName, WindowsVersion, OsHardwareAbstractionLayerVersion, OsProductType, OsArchitecture, OsLanguage
$ht2 = @{}
$ComputerInfo.psobject.properties | Foreach { $ht2[$_.Name] = $_.Value }
($PSVersionTable | Format-Table | Out-String) + ($ht2 | Format-Table | Out-String) | Out-File -FilePath ./NovuDebug.txt

```

**Comment by melon-husk** [comment]
@Cliftonz  sure, here's the file
[NovuDebug.txt](https://github.com/novuhq/novu/files/11424679/NovuDebug.txt)

**Comment by Cliftonz** [comment]
@melon-husk Thank you for the data.
I am unfortunately unable to replicated this problem on my windows computer. I am also running powershell 5.1 and running node 18.16.0 but am on Windows 11. This prompt is handled by https://www.npmjs.com/package/inquirer however it is the CLI which is governed by https://www.npmjs.com/package/commander that seems to be breaking on your side.

Have you reinstalled node and/or ran ```npm cache clean``` recently? do you run nvm for windows?

Have you considered doing the signup in the webUI at https://web.novu.co/auth/login ?

**Comment by melon-husk** [comment]
@Cliftonz I ran `npm cache clean` it prompted me to try `npm cache verify`. I did that and now the cli works ! Thanks.
![image](https://user-images.githubusercontent.com/30780724/237061567-387f4951-f932-46b4-a2ec-a6485948acbf.png)
![image](https://user-images.githubusercontent.com/30780724/237061349-d25213a5-a97b-4483-a783-d033e8d947c5.png)
