### ISSUE TITLE
[NV-2225] 🐛 Bug Report: Visual bug - dual scroll in integration configuration modal

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#3345]
### 📜 Description

When you enter integration configuration it just doesn't feel right - you can see two scrolls in modal.

### 👟 Reproduction steps

1. Go to "Integration Store"
2. Enter some random integration - I think "Custom SMTP" has the most options and that's where the bug is most visible.

![smtp](https://user-images.githubusercontent.com/43048524/236641208-bb3006a3-948c-449a-8f21-67e80187b2d9.png)

### 👍 Expected behavior

Expected behavior (I edited styles in directly dev tools - removed `y-overflow` in modal)

![expected](https://user-images.githubusercontent.com/43048524/236640886-75e2478a-6cda-438a-bb83-0a61e5c91ce9.png)

### 👎 Actual Behavior with Screenshots

It doesn't look good

![wrong](https://user-images.githubusercontent.com/43048524/236641004-0802065b-6203-441c-baff-bd93c5be0909.png)

### 📃 Provide any additional context for the Bug.

I use laptop with Full HD screen and 125% scale but I don't think it matters (I tested with 100% scale and issue is still visible).

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2225](https://linear.app/novu/issue/NV-2225/🐛-bug-report-visual-bug-dual-scroll-in-integration-store)</sub>

**Comment by gitstart** [comment]
@scopsy I would like to pick this up
