### ISSUE TITLE
[NV-2291] 🐛 Bug Report: APNs integration dialog does not allow turning Production off

### ISSUE THREAD

**Issue by shanehandley-lived** [novuhq/novu#3360]
### 📜 Description

When configuring the APNs integration, clicking the `Production` toggle sets the slider in the UI correctly, but after saving the value is not persisted.

### 👟 Reproduction steps

1. Go to the integrations store
2. Configure the push provider for APNS
3. Toggle the 'Production' value off
4. Save
5. Re-open the integration settings for APNs
6. The 'Production' value is still set to true.

### 👍 Expected behavior

The 'Production' value should be persisted as 'Off'

### 👎 Actual Behavior with Screenshots

https://user-images.githubusercontent.com/123625424/236993527-4a8c226d-d4c3-4984-b825-61da48997e25.mov

### 📃 Provide any additional context for the Bug.

Recent related issue: https://github.com/novuhq/novu/issues/2967

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2291](https://linear.app/novu/issue/NV-2291/🐛-bug-report-apns-integration-dialog-does-not-allow-turning)</sub>

**Comment by jainpawan21** [comment]
API implementation is fine. There is some bug in UI, specifically with toggle.

**Comment by gitstart** [comment]
@shanehandley-lived @jainpawan21 I would like to pick this up. Cc @scopsy

**Comment by LetItRock** [comment]
@gitstart just assigned it to you :) thanks!

**Comment by scopsy** [comment]
Amazing @gitstart let me know if I can help in anyway

**Comment by shanehandley-lived** [comment]
I think this may actually be caused by https://github.com/novuhq/novu/issues/3416 - The UI is sending a string "false" value when the value is toggle off, which is then being returned in the response and being interpreted as a boolean `true`, immediately flicking the value back to true in the UI.

**Comment by scopsy** [comment]
@shanehandley-lived yep, sounds like it might be because of it.

**Comment by scopsy** [comment]
@gitstart I believe this should help you ^. We might just need to convert the "string" boolean to a real boolean before saving the field

**Comment by michaldziuba03** [comment]
@gitstart It seems I fixed this issue by fixing #3416 where I was assigned

![image](https://github.com/novuhq/novu/assets/43048524/927b7c86-61ff-4775-a1dd-b4506f0bac26)

![image](https://github.com/novuhq/novu/assets/43048524/f076ab03-fd2e-4c55-a8f7-b00da6dcc12f)

![image](https://github.com/novuhq/novu/assets/43048524/13ee28eb-1ddb-4b79-9b9c-72f1bb76d40a)

**Comment by michaldziuba03** [comment]
@jainpawan21 I fixed this in this PR: https://github.com/novuhq/novu/pull/3430

**Comment by jainpawan21** [comment]
Thanks @michaldziuba03 🙏🏻
