### ISSUE TITLE
[NV-2294] Qwik integration

### ISSUE THREAD

**Issue by MyWay** [novuhq/novu#3367]
### 🔖 Feature description

Since they released their first stable version, I'd like to see support for Qwik framework. 

### 🎤 Why is this feature needed ?

Even though we could use an iframe, or the web component, having a native component would make it easier to adopt Novu on Qwik. 

### ✌️ How do you aim to achieve this?

A component like there is for React, Vue and Angular would be awesome. 

### 🔄️ Additional Information

Web component and iframe are availables alternatives. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2294](https://linear.app/novu/issue/NV-2294/qwik-integration)</sub>

**Comment by jainpawan21** [comment]
Hi @MyWay 
thanks for your interest in Qwik integration for notification center
Would you like us to help here in implementation?

**Comment by aggmoulik** [comment]
Hey, @jainpawan21 @MyWay I am looking into the implementation of the Novu Component with the Qwik framework.

**Comment by aggmoulik** [comment]
Hey @Cliftonz If you want to pick up, you can.
