### ISSUE TITLE
[NV-2292] 🐛 Bug Report: dual active states in UI, if template is created with api

### ISSUE THREAD

**Issue by rajat-valstro** [novuhq/novu#3386]
### 📜 Description

When I create a Novu Notification Template using the Novu Node SDK the UI shows that it is in both active and disabled state. I can't trigger notifications using this template until I toggle the active state off and back on in the UI.
![err](https://github.com/novuhq/novu/assets/130503202/4d1e7d31-df5d-4db7-a350-8a5dbaf2014b)

### 👟 Reproduction steps

1. Use the Novu Node SDK to create a notification group and then a notification template with the same name.
2. Get the triggerID for this notification template and trigger a notification to subscribers (I used 1) with this template.
3. Go to UI and see no notification in the activity and the notification template is in a dual active/disabled state.

### 👍 Expected behavior

It should create the Notification Template in active state and allow me to trigger notifications using this template.

### 👎 Actual Behavior with Screenshots

Screenshots attached in description

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2292](https://linear.app/novu/issue/NV-2292/🐛-bug-report-dual-active-states-in-ui-if-template-is-created-with-api)</sub>

**Comment by michaldziuba03** [comment]
@scopsy can you assign me? I will try to find out what happens.

I was able to reproduce this issue with this simple code
```js
require('dotenv').config();
const { randomUUID } = require('crypto');

const { Novu } = require('@novu/node');

const novu = new Novu(process.env.NOVU_API_KEY);
const subscriberId = "mysubscriberIdFromDashboard";
const name = `test${randomUUID()}`;

async function main() {
  try {
    const group = await novu.notificationGroups.create(name);

    const result = await novu.notificationTemplates.create({
      name,
      active: true,
      description: "Test Template :)",
      notificationGroupId: group.data.data.id,
      steps: [],
    });
    
    console.log(result.data.data);
    const triggerId = result.data.data.triggers[0].identifier;

    const triggerRes = await novu.trigger(triggerId, {
      to: [{subscriberId}],
      payload: { hello: "world" },
    })

    console.log(triggerRes.data);
  } catch (err) {
    console.error(err.message);
    console.log(err.data);
  }
}

main();
```

![image](https://github.com/novuhq/novu/assets/43048524/c4692576-cdf0-4fb4-bc9f-dfa990ca790e)

**Comment by michaldziuba03** [comment]
When both active and draft are `true` - bug happens

**Comment by codingmickey** [comment]
I was trying to recreate this.. but couldn't find that this was the issue

> When both active and draft are `true` - bug happens

Good work on cloning it!! 🙌🏽

**Comment by michaldziuba03** [comment]
There is also second part of issue - why triggered notification does not appear? Because you cannot trigger draft template.

![image](https://github.com/novuhq/novu/assets/43048524/09819bab-e452-4eb3-9097-aec520bd1124)

By default template is created in db as draft.

![image](https://github.com/novuhq/novu/assets/43048524/ee525623-cdfc-47e8-8c79-4001d4ad79a5)

**Comment by scopsy** [comment]
@michaldziuba03 yep, I think we can switch the default to "active" true and "draft" false on the backend. And enforce the not to allow active true and draft true modes. To be honest, we might be deprecating the "draft" down the line as it's not used anywhere at the moment. But for now this should do the trick.
