### ISSUE TITLE
[NV-2313] 🐛 Bug Report: Error Message Unprocessable Entity is not descriptive eough

### ISSUE THREAD

**Issue by banani0720** [novuhq/novu#3399]
### 📜 Description

I am using `@novu/node` to trigger notifications and I recently put a typo in my notification ID. This led to the error `Unprocessabe Entity`. While it's nice to know that I'm encountering an error that's a really unspecific error that makes it difficult to figure out what exactly is wrong. 

### 👟 Reproduction steps

1. Create a new notification in  novu dashboard
2. Create a notification trigger, but use a notification ID that doesn't exist
3. Surround notification trigger in try-catch and console log on errors

### 👍 Expected behavior

It should, include some sort of messaging indicating that the notification trigger that I have specified does not exist

### 👎 Actual Behavior with Screenshots

<img width="1346" alt="image" src="https://github.com/novuhq/novu/assets/123763710/7aff5764-4790-4313-8fcf-ba9756806cfa">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2313](https://linear.app/novu/issue/NV-2313/🐛-bug-report-error-message-unprocessable-entity-is-not-descriptive)</sub>

**Comment by scopsy** [comment]
Hi @banani0720 could you please attach the full response body? From a check I made we are sending a `message` field with the content of: `template_not_found` in this case.

**Comment by scopsy** [comment]
Closing this for now, please let me know if you still experience this on the body response 🙏
