### ISSUE TITLE
[NV-2329] 🐛 Bug Report: Issues with integration `secure` option

### ISSUE THREAD

**Issue by shanehandley-lived** [novuhq/novu#3416]
### 📜 Description

After wrestling with some APNs issues over the past week or so, I was not able to get any meaningful debugging insights from the Novu web app, but I realised that there are some potential issues with how the `secure` property is being handled between Novu <> apns.

Currently, it looks to be an optional property, so integrations created without specifying a value for this are effectively `undefined`.

This can have unfortunate consequences in the case of the `apns` package, since it will default to `production` if `NODE_ENV` is set to production (which I believe [is set](https://github.com/novuhq/novu/blob/next/apps/api/src/.env.production#L1) for Novu api) so if no value exists, production will be assumed by the apns package.

The workaround for this seemed to be ensuring that the property is set to `false`, but this didn't seem to resolve issues. I believe it's an issue with how the `credentials` data is being stored, mainly because the `secure` value is being persisted as a string ("true" || "false"). This has the effect in the `apns` package where `"false"` is actually interpreted as [true for any string value](https://github.com/node-apn/node-apn/blob/master/lib/config.js#L94)

I created a quick test in the apn package to verify that this is the case:

![Screenshot 2023-05-15 at 6 53 58 pm](https://github.com/novuhq/novu/assets/123625424/df84a80c-09d0-4617-a1f8-00d4582b379f)

### 👟 Reproduction steps

1. Create an APNs integration via the API excluding the "secure" property
2. Fetch the integraton, observing that the "secure" property is absent
3. Update the integration via an API call, setting the "secure" property to (Boolean) true
4. Observe that the "secure" property is being persisted as a string in mongoDB. 

### 👍 Expected behavior

When creating an integration, the `secure` property should be defaulted to Boolean `false` if no value is provided by teh user.

When the value is updated, the value should be persisted as a boolean value, to prevent the kind of ambiguity introduced when using the apns package, and potentially others

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-05-15 at 7 01 46 pm](https://github.com/novuhq/novu/assets/123625424/399ab334-38c4-404a-9bbd-7e5a87c662ac)

### 📃 Provide any additional context for the Bug.

I'm using the API to update notifications, but this may impact the fix for https://github.com/novuhq/novu/issues/3360

I've been unable to get e2e tests working to test a fix for this, but I feel like the `secure` property in the DTO should be `@IsBoolean` over `@IsBooleanAny` which was changed in https://github.com/novuhq/novu/commit/4e5b082b0654d6e78b322917a5d74df001e6dd2b - I don't have context on those changes however, and there was probably a reason for that change that core devs know about.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2329](https://linear.app/novu/issue/NV-2329/🐛-bug-report-issues-with-integration-secure-option)</sub>

**Comment by michaldziuba03** [comment]
@shanehandley-lived `@IsBooleanAny` exists because frontend sends for some reason boolean values as strings for credentials. When I tested these changes I seen Mongoose transforms boolean values correctly. But maybe it's not always the case.

What I will try to do is transform "true"/"false" to actual booleans before it will enter data access layer and then use `@IsBoolean` validator.

**Comment by michaldziuba03** [comment]
Ok, I checked the Integration schema for DB. For some reason "secure" is defined as string and for that reason secure is persisted as string instead a boolean. Other values I tested were persisted as boolean correctly :)

![image](https://github.com/novuhq/novu/assets/43048524/0edf83a4-2040-40c6-bd82-43ec9d3f9039)

@scopsy There is any reason for schema like this (maybe in some other provider)?

**Comment by scopsy** [comment]
@michaldziuba03 it looks like a mistake, secure should be a boolean. do we have other providers other than APNS that uses this boolean flag?

**Comment by michaldziuba03** [comment]
@scopsy nodemailer uses `secure` flag but it's boolean as well.

https://nodemailer.com/smtp/#tls-options

**Comment by michaldziuba03** [comment]
I fixed now part of `secure` data type but I wonder how to handle default values for particular provider?

@scopsy I would want to avoid making if statement for checking particual provider somewhere in API.
