### ISSUE TITLE
[NV-2341] 🐛 Bug Report: MongoDB huge amount of connections

### ISSUE THREAD

**Issue by wouter-toppy** [novuhq/novu#3425]
### 📜 Description

Ive deployed Novu to a Google Cloud Cluster with a MongoDB Deployment (using MongoDB Atlas in Google Cloud)

it is just a plain install with the API, WEB, WORKER and WS container. 

pretty instant after de deployment I receive messages from MongoDB that the connection limit is reached. (500) 

wondering why the application is using almost 500 mongoDB connections at the same time while doing basicly nothing. 

### 👟 Reproduction steps

Deploy on Google Cloud, with MongoDB (using MongoDB Atlas)

### 👍 Expected behavior

not that many database connection. (solution in [Discord](https://discord.com/channels/895029566685462578/1107967383332732989) was that connections should be configured by an ENV)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/40226924/e9c2ea68-ed79-4f8d-a1a6-b6620fbd2e44)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes

<sub>[NV-2341](https://linear.app/novu/issue/NV-2341/🐛-bug-report-mongodb-huge-amount-of-connections)</sub>

**Comment by wouter-toppy** [comment]
@jainpawan21

**Comment by wouter-toppy** [comment]
Possible on https://github.com/novuhq/novu/blob/4de93a6c168abac891ee787a751b7ac42e7de349/libs/dal/src/dal.service.ts#L9

**Comment by SebastianStehle** [comment]
The fact that you can have 500 connections does not mean that the driver should open 500 connections...
