### ISSUE TITLE
[NV-2342] 🐛 Bug Report: Details Body on Unexpected Provider Error is not shown on Push Notifications

### ISSUE THREAD

**Issue by christos-deretzis** [novuhq/novu#3431]
### 📜 Description

Whenever we trigger a push notification and something goes wrong (e.g. a wrong device token or wrong credentials for push providers), we get an Unexpected Provider Error on the execution details.As a result, we can't see the body for this specific step whenever we press the button. Instead, we get an empty body ({})

### 👟 Reproduction steps

1. Login to Novu web and Navigate to the **Activity Feed** from the Left Menu
2. Click on a failed Push Notification 
3. On the last step (**Unexpected Provider Error**) click on the button next to it (**Show Details**)
4. The details body is empty ({})

### 👍 Expected behavior

It should have a non empty body with some kind of message, explaining what went wrong 

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-05-16 at 4 22 56 PM](https://github.com/novuhq/novu/assets/124055228/5a031e13-fb5b-44fd-a63c-f15824699bfe)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2342](https://linear.app/novu/issue/NV-2342/🐛-bug-report-details-body-on-unexpected-provider-error-is-not-shown)</sub>

**Comment by jainpawan21** [comment]
Sure @gitstart Assigning this to you!

**Comment by gitstart** [comment]
Hi @christos-deretzis, I am currently facing a blocker while trying to reproduce this issue. I am having this blocker when trying to run a Push notification trigger. I have activated OneSignal and FCM separately but the error is persistent.
I will appreciate any form of help to unblock this issue. Cc @scopsy @jainpawan21

![Screenshot 2023-05-25 at 10 41 54](https://github.com/novuhq/novu/assets/1501599/698c06d6-345a-4522-bffe-0130ba7f4868)

Loom Video: https://www.loom.com/share/6f8654cc7fa544bcb6c9a49e392db4f6

**Comment by christos-deretzis** [comment]
@gitstart what you have to do it to subscribe the device token that is generated by the push provider to the subscriber id, so that the subscriber id will have a device token for a given provider. The request to achieve that is:

**Request**: `PUT {novu_api_url}/v1/subscribers/{subscriberId}/credentials`
**Authorization** : key-> Authorization, value -> "ApiKey {your_api_key}"
**Request Body** (fcm for example)

- `{
    "providerId": "fcm", 
    "credentials": {
        "deviceTokens": ["your_fcm_device_token"]
    }
}`

**Comment by jainpawan21** [comment]
Hi @gitstart 
Thanks for your interest.
I had to pick this as this was confusing bug.
