### ISSUE TITLE
🚀 Feature: Export Notification Templates interfaces/enums from SDK 

### ISSUE THREAD

**Issue by underfisk** [novuhq/novu#3442]
### 🔖 Feature description

SDK types are not being exported for consumers, example: `IMessageFilter` interface can't be imported from `@novu/node`

### 🎤 Why is this feature needed ?

I'm building a library that generates Novu resources/entities programmatically and there's the need to have type-safety but it is hard to import the types from `@novu/node` as enums such as `DigestUnitEnum`, `BuilderFieldType` etc or any other interface related to notification templates (which is my primary use case) are not available 

The workaround that I have so far is using typescript `Parameters``
```typescript
import type { Novu } from '@novu/node';

export type SdkTemplate = Parameters<
  Novu['notificationTemplates']['create']
>[0];
```

This is not ideal as for some enum fields, we're not even able to pass a literal value and i end up casting to `any`

### ✌️ How do you aim to achieve this?

If possible export the types/enums so that the SDK can import, something like

```typescript
import type { INotificationTemplateStep, INotificationTemplatePayload,  ChannelCTATypeEnum } from '@novu/node'
```

### 🔄️ Additional Information

This might apply to other resources, right now I'm only exploring templates 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by underfisk** [comment]
Bumping

**Comment by jainpawan21** [comment]
Shall I assign this to you @underfisk ?

**Comment by underfisk** [comment]
@jainpawan21 Feel free to, i can create the PR
