### ISSUE TITLE
[NV-2582] TypeError: oldMessages.map is not a function

### ISSUE THREAD

**Issue by yngfoxx** [novuhq/novu#3460]
## 📜 Description
I get this error when I mark a notification as seen with the headless service library
https://github.com/novuhq/novu/blame/e726694c4a8d2a9af17f7a24bd6f8bf7a06a2223/packages/headless/src/lib/headless.service.ts#L581
![image](https://github.com/novuhq/novu/assets/47150226/b3517bb7-16ce-4817-b04a-13da96ef479e)

## Reproduction
I use Novu's cloud service with HMAC enabled
I am trying to create a simple custom notification centre for React Native + Expo (TypeScript)
```
headlessService.markNotificationsAsSeen({
    messageId: ['message-id-0', 'message-id-1'],
    listener: ({status, isLoading}) => {
        if (isLoading) return;
        if (!isLoading && status !== 'success') return Prompt({
            status: 'error',
            content: 'An error occured while trying to mark a notification as seen.',
            closeText: ''
        });
    },
    onError: console.error
})
```
Note: I used Brave browser 

<sub>[NV-2582](https://linear.app/novu/issue/NV-2582/typeerror-oldmessagesmap-is-not-a-function)</sub>

**Comment by akashvivek** [comment]
I am interested in solving this issue.

**Comment by jainpawan21** [comment]
@BiswaViraj
