### ISSUE TITLE
[NV-2392] 🐛 Bug Report: cache invalidation issue

### ISSUE THREAD

**Issue by ceq-a-bahgat** [novuhq/novu#3520]
### 📜 Description

I'm trying novu 0.14 locally without docker, running api, worker, web, after sending the first messaage successfully to any channl, if i tried to change this content, it still sends the previouc message conten however I changed and clicked update, and made sure that the data got updated in the mesagetemplates collection, I traced it for a while and i found two keys in redis index 0 i.e: {entity:notification_template:e=641b7ed43b9278c8c2c76804:i=6467998a6df9d9462c848fa2}
{entity:notification_template:e=641b7ed43b9278c8c2c76804:t_i=test}

when I deleted them and try to triger the flow again, only then the last updated content sent successfully, and those keys in redis got created again, and If i tried again with another content the issue got appeared again, unless I went one more time and delete this keys manually from redis.

In this screenshots, I'm using email channel, send message with content "hello27" first, then updated the content to "hello28" and got updated successfully in mongo, but keeps sending the previous content which is "hello27" instead of "hello28"
![issue-1](https://github.com/novuhq/novu/assets/133760608/817cf9e8-dc83-4e5b-8d02-2d5d8df3f2ee)
![issue-2](https://github.com/novuhq/novu/assets/133760608/df5c39a1-b55c-438b-80ed-14a9294ee79d)
![issue-3](https://github.com/novuhq/novu/assets/133760608/6fdeda24-8e32-4e27-be71-7ea429d5806f)
![issue-4](https://github.com/novuhq/novu/assets/133760608/a0cf34dc-4b2c-49e7-9831-215a4672d727)

### 👟 Reproduction steps

1- Run api, worker, and web locally
2- create new workflow with active channel i.e: email
3- test the channel and send message
4- change the message content from the flow
5- test again the flow
6- you should receive the updated content but instead you received the previous one

### 👍 Expected behavior

You should receive always the updated content 

### 👎 Actual Behavior with Screenshots

You receive the previous contentno the updated one

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2392](https://linear.app/novu/issue/NV-2392/🐛-bug-report-cache-invalidation-issue)</sub>

**Comment by scopsy** [comment]
@djabarovgeorge any initial thoughts on what might happen here? Maybe it was fixed in 0.15.0 already?

**Comment by djabarovgeorge** [comment]
Hey @ceq-a-bahgat could you check if the API has the cache enabled? 
Please make sure that you have the following environments variables pointing to your Redis instance as well
REDIS_CACHE_SERVICE_HOST=localhost
REDIS_CACHE_SERVICE_PORT=6379

**Comment by scopsy** [comment]
Hi @ceq-a-bahgat did you had a chance to check George suggestion?
