### ISSUE TITLE
🐛 Bug Report: Can't embed hyperlink in Slack message 

### ISSUE THREAD

**Issue by phlrss** [novuhq/novu#3548]
### 📜 Description

According to [slack docs](https://api.slack.com/reference/surfaces/formatting#linking-urls) the way to insert a hyperlink in a Slack message is the following:
`<http://www.example.com|This message is a link>`
When i try using this, anything with `< >` gets auto-removed.

### 👟 Reproduction steps

1. Add a Chat step to a template
2. try adding a hyperlink to your Slack message like this: `<http://www.example.com|This message is a link>`
3. When you click the "Update" button the entire text with `<>` gets automatically removed

### 👍 Expected behavior

it should allow me to embed hyperlinks in my Slack message

### 👎 Actual Behavior with Screenshots

it auto-removes the hyperlink

https://github.com/novuhq/novu/assets/46248889/ccc06d2e-a78d-4cf5-a7e3-e945ece9e31f

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
This was resolved with Echo: https://docs.novu.co/echo/quickstart
