### ISSUE TITLE
[NV-2400] 🐛 Bug Report: Sign up not working for docker based deployment

### ISSUE THREAD

**Issue by vivek161985** [novuhq/novu#3554]
### 📜 Description

I am trying to follow https://docs.novu.co/overview/docker-deploy/ and as soon as i browse to http://localhost:4200/ after completing pre-requisites, it redirects to sign in page. I try to sign up but it always stucks as soon as i enter user name.

Can anyone please help me asap.

### 👟 Reproduction steps

I am trying to follow https://docs.novu.co/overview/docker-deploy/ and as soon as i browse to http://localhost:4200/ after completing pre-requisites, it redirects to sign in page. Since i don't have account, I try to sign up but page always stucks as soon as i enter user name.

Can anyone please help me asap.

### 👍 Expected behavior

It should allow me to create an account.

### 👎 Actual Behavior with Screenshots

<img width="949" alt="image" src="https://github.com/novuhq/novu/assets/44605378/c9995602-4eca-4934-b2f1-3f8e7a3c3f3b">

<img width="958" alt="image" src="https://github.com/novuhq/novu/assets/44605378/9c623ca5-7150-4cef-82ba-2877df0e9d8c">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2400](https://linear.app/novu/issue/NV-2400/🐛-bug-report-sign-up-not-working-for-docker-based-deployment)</sub>

**Comment by ComBarnea** [comment]
@jainpawan21 can you please help us here?

**Comment by jainpawan21** [comment]
@vivek161985 I see in the second screenshot you have not entered the password.

**Comment by vivek161985** [comment]
Hi @jainpawan21 : The browser is stuck as soon as i enter username. I never get chance to enter password. I have tried it in multiple laptops (both windows). In 1st laptop,  the browser is just stuck after entering user name and in 2nd laptop it throws an error stating network issue. Not sure, if i am missing anything here.

**Comment by michaldziuba03** [comment]
I tried to reproduce issue on my Windows 11 laptop but everything works for me.
```sh

git clone --depth 1 https://github.com/novuhq/novu

cd novu/docker

cp .env.example ./local/deployment/.env

docker-compose -f ./local/deployment/docker-compose.yml up
```

@vivek161985 Can you share exact Windows version, browser (with version as well if you can)?

**Comment by vivek161985** [comment]
@michaldziuba03  
The windows version is Windows 10 Enterprise. 
Browsers :  chrome (Version 114.0.5735.90) and Edge (Version 114.0.1823.37)
Screen Resolution : 1920 * 1080

**Comment by michaldziuba03** [comment]
@vivek161985 
can you test if password field works on Novu cloud version?
https://web.novu.co/auth/signup

**Comment by scopsy** [comment]
Alright, so I think I was able to reproduce. This happening only when the height if the window small and you click on the password field and the "Password Strength" tool tip opens, the screen freezes. I think that @BiswaViraj you fixed something similar on the workflow editor?

**Comment by vivek161985** [comment]
> @vivek161985 can you test if password field works on Novu cloud version? https://web.novu.co/auth/signup

@michaldziuba03 , yes cloud version is working fine for me. The issue is with self hosted one.

**Comment by vivek161985** [comment]
> Alright, so I think I was able to reproduce. This happening only when the height if the window small and you click on the password field and the "Password Strength" tool tip opens, the screen freezes. I think that @BiswaViraj you fixed something similar on the workflow editor?

@scopsy @BiswaViraj Can you please help me with the fix.

**Comment by michaldziuba03** [comment]
ok, just as @scopsy said it happens on smaller height and I was able to reproduce it as well.

![image](https://github.com/novuhq/novu/assets/43048524/8b9eaeb7-746a-4c3a-8d16-d0fb6702ac8b)

I think you use 1920x1080 screen but with 150% scale what makes window much smaller.

## Workarounds

### I suggest to zoom out with `Ctrl`+`-`
<img width="960" alt="image" src="https://github.com/novuhq/novu/assets/43048524/e7b5ad4c-0334-4bbe-b3cc-9adc53b16afd">

### Use API directly to create user
Use tools like [Postman](https://www.postman.com/) or [Insomnia](https://insomnia.rest/) to register user

![image](https://github.com/novuhq/novu/assets/43048524/75489353-4cb3-4fa9-ac9c-8dfdbc26d08c)

or just paste this`fetch` to the console and replace credentials
```js
fetch("http://localhost:3000/v1/auth/register", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "pl,en;q=0.9,pl-PL;q=0.8,en-US;q=0.7",
    "content-type": "application/json",
    "sec-ch-ua-mobile": "?0",
  },
  "referrer": "http://localhost:4200/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"firstName\":\"Firstname\",\"lastName\":\"Lastname\",\"email\":\"test@example.com\",\"password\":\"TestTest@1T\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
}).then(res => res.json());
```

**Comment by vivek161985** [comment]
> ok, just as @scopsy said it happens on smaller height and I was able to reproduce it as well.
> 
> ![image](https://user-images.githubusercontent.com/43048524/243556453-8b9eaeb7-746a-4c3a-8d16-d0fb6702ac8b.png)
> 
> @vivek161985 I think you use 1920x1080 screen but with 150% scale what makes window much smaller.
> 
> ## Workarounds
> This is client side issue for sure and needs to be fixed - until fix you can use some workarounds.
> 
> ### I suggest to zoom out with `Ctrl`+`-`
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/43048524/243558197-e7b5ad4c-0334-4bbe-b3cc-9adc53b16afd.png">
> ### Use API directly to create user
> Use tools like [Postman](https://www.postman.com/) or [Insomnia](https://insomnia.rest/) to register user
> 
> ![image](https://user-images.githubusercontent.com/43048524/243559283-75489353-4cb3-4fa9-ac9c-8dfdbc26d08c.png)
> 
> or just paste this`fetch` to the console and replace credentials
> 
> ```js
> fetch("http://localhost:3000/v1/auth/register", {
>   "headers": {
>     "accept": "application/json, text/plain, */*",
>     "accept-language": "pl,en;q=0.9,pl-PL;q=0.8,en-US;q=0.7",
>     "content-type": "application/json",
>     "sec-ch-ua-mobile": "?0",
>   },
>   "referrer": "http://localhost:4200/",
>   "referrerPolicy": "strict-origin-when-cross-origin",
>   "body": "{\"firstName\":\"Firstname\",\"lastName\":\"Lastname\",\"email\":\"test@example.com\",\"password\":\"TestTest@1T\"}",
>   "method": "POST",
>   "mode": "cors",
>   "credentials": "omit"
> }).then(res => res.json());
> ```

Thank you @michaldziuba03 This works. Thank you entire team for the help. The issue can be closed.

**Comment by vivek161985** [comment]
Issue fixed with suggestions provided by @michaldziuba03

**Comment by vivek161985** [comment]
Issue fixed with suggestions provided by @michaldziuba03
