### ISSUE TITLE
🚀 Feature: in notification-center, ability to control displayed templates in subscriber preferences

### ISSUE THREAD

**Issue by leonardbinet** [novuhq/novu#3559]
### 🔖 Feature description

Give ability to control which templates are manageable in subscriber preferences.

https://docs.novu.co/notification-center/react/react-components#subscriber-preferences

I would like to be able to hide some sections to some users.

<img width="450" alt="Screenshot 2023-06-05 at 13 54 45" src="https://github.com/novuhq/novu/assets/1590371/d6262953-e03f-4637-bc6e-f9bfa5d5ff26">

### 🎤 Why is this feature needed ?

There are multiple use cases:
- hide some new features behind a feature flag
- have different types of users: example suppose a job-board application:
   - employers will have some types of notifications
   - applicants will have other types of notifications

### ✌️ How do you aim to achieve this?

Currently, in `@novu/notification-center/dist/types/components/popover-notification-center/PopoverNotificationCenter.d.ts`, the `IPopoverNotificationCenterProps` interface contains only a boolean `showUserPreferences`.

<img width="735" alt="Screenshot 2023-06-05 at 14 13 27" src="https://github.com/novuhq/novu/assets/1590371/5a73e4db-ebef-4b3e-8412-e3e4628041bc">

A solution would be to add another attribute `userPreferenceDisplayTemplates` of shape `Record<TemplateId, boolean>` to specify which templates should be displayed or not.

### 🔄️ Additional Information

The alternative is to rewrite from scratch a custom notification center component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
This should be connected to #3850 as we will expose a custom filtering function which could be used to determine the displayed list of notifications. Will that help @leonardbinet ?

**Comment by scopsy** [comment]
This has been released under the new dashboard and novu/react components
