### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by michellekyt** [novuhq/novu#3571]
### 📜 Description

After upgrade from 0.11 to 0.15, found the email unable to send out due to tls version, hence approach to email setting and found the email settings has been changed to have extra checkbox which consist of ignore tls, required tls and secure, where secure always will auto tick (however when I check from api it actually is false). As I'm not going to use secure / tls, I have choose to select ignore tls. However it still required to put something into the tls options. 

### 👟 Reproduction steps

1. In Nodemailer Email Setting, select ignore tls, tls options is blank, hit error. 

### 👍 Expected behavior

The tls options should be hidden when ignore tls has been selected and default value should be {}. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/127278529/0b22b3d7-d3ff-4bb8-aa05-ff2c53e0d458)
![image](https://github.com/novuhq/novu/assets/127278529/0e391dff-b9f5-4b1a-b57d-c10870c2e57e)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by gitstart** [comment]
@scopsy I would like to pick this up

**Comment by p-fernandez** [comment]
@michellekyt you will have this fix available in v.0.17.0
