### ISSUE TITLE
🚀 Feature: Novu Image on Docker Hub (or similar platform)

### ISSUE THREAD

**Issue by playground-anthonya** [novuhq/novu#3576]
### 🔖 Feature description

It would be nice to have a Novu image packaged up and ready for use in other projects through docker compose or docker cli or docker swarm.

### 🎤 Why is this feature needed ?

Currently you would have to build the image yourself or create some sort of script to automate the process to keep up to date with the Github repo.

### ✌️ How do you aim to achieve this?

You can achieve this through some sort of CI/CD logic on the repository.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by harrisyn** [comment]
@playground-anthonya I think the images already exist, if you look in the docker/local/deployment/docker-compose file, you should find the referenced images.

**Comment by playground-anthonya** [comment]
@harrisyn Oh Perfect! I see them. Thanks 👍
