### ISSUE TITLE
🐛 Bug Report: Novu notification center "Mark all as read" button not doing anything

### ISSUE THREAD

**Issue by TomasHubelbauer** [novuhq/novu#3580]
### 📜 Description

Hi folks, we are using the Novu notification center and our E2E UI tests started freaking out recently. Upon investigation, it turned out they are no longer able to dismiss all unread notifications in the Novu notification center and then validate they have been cleared.

I was able to reproduce the issue by hand. I send my test account a notification and then press Mark all as read and nothing happens. When I click the Mark as read button on the individual notification, it refreshes the whole page and after the refresh there are no unread notifications anymore:

https://github.com/novuhq/novu/assets/6831144/82985878-198c-478b-bd49-df4626cb8724

I checked the Network tab in the browser developer tools and I see https://api.novu.co/v1/widgets/messages/read being hit with every click. The first time around the response is `{"data":1}` and all subsequent times the response is `{"data":0}` so I think the API works, but the Notification Center UI is not reflecting the new state.

This whole thing happens in the Novu `iframe` so I hope it is not our app code breaking this in any way, but it is not impossible I guess, so maybe it is a problem on our end? But then, what could it be to cause the `iframe` to not update its UI after the network request completes?

### 👟 Reproduction steps

I can only reproduce locally on our app. Is there any sort of a Novu Playground or any public demo of the Novu Notification Center where I could try to reproduce?

### 👍 Expected behavior

Mark all notifications as read and update the Novu Notification Center UI to match.

### 👎 Actual Behavior with Screenshots

The notifications get marked as read via the API call (as evidenced by the fact that the tab reload shows no unread notifications), but the UI is not updating. See the video above.

### 📃 Provide any additional context for the Bug.

I search for notification center issues but have not found anyone reporting this yet.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by LetItRock** [comment]
Hey @TomasHubelbauer 👋 I'm sorry that you are facing this issue, but it should be fixed in this PR: https://github.com/novuhq/novu/pull/3540. For now I would suggest you to downgrade to v0.15.0.

**Comment by TomasHubelbauer** [comment]
Awesome, thanks!

**Comment by LetItRock** [comment]
@TomasHubelbauer the fix will be released in the next patch release: https://github.com/novuhq/novu/pull/3603
