### ISSUE TITLE
[NV-2409] 🐛 Bug Report: Querying by non-existent `subscriberId` returns all messages

### ISSUE THREAD

**Issue by thenbe** [novuhq/novu#3581]
### Good example

```bash
URL="https://api.novu.co/v1/messages"
SUBSCRIBER_ID="1"
http GET ${URL} subscriberId=="${SUBSCRIBER_ID}"
```

| Header | Header |
|--------|--------|
| Expected | Subscriber 1's messages returned |
| Actual | Subscriber 1's messages returned | 

---

### Bugged example

However, when we use a non-existent subscriber ID:

```bash
URL="https://api.novu.co/v1/messages"
SUBSCRIBER_ID="NON_EXISTENT"
http GET ${URL} subscriberId=="${SUBSCRIBER_ID}"
```
| Header | Header |
|--------|--------|
| Expected | No messages returned|
| Actual | *All* messages returned | 

Related: https://github.com/novuhq/novu/blob/5ef36d0e3fca483605ad99ae26b7f04a2656ecd0/apps/api/src/app/messages/usecases/get-messages/get-messages.usecase.ts#L30

### 👟 Reproduction steps

.

### 👍 Expected behavior

.

### 👎 Actual Behavior with Screenshots

.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2409](https://linear.app/novu/issue/NV-2409/🐛-bug-report-querying-by-non-existent-subscriberid-returns-all)</sub>

**Comment by ainouzgali** [comment]
Hi @thenbe! Thanks for reporting :)
I agree, no messages should be the expected behavior.
In my opinion, should throw an error if a subscriberId is sent (command.subscriberId) to the query, but no such subscriber exists. If no subscriberId is sent to the query, should keep the current behavior. 
What do you think? @thenbe @jainpawan21

**Comment by thenbe** [comment]
@ainouzgali Agreed. A `404` seems appropriate here.

**Comment by gitstart** [comment]
@ainouzgali @thenbe I would like to pick this up

**Comment by jainpawan21** [comment]
> Hi @thenbe! Thanks for reporting :) I agree, no messages should be the expected behavior. In my opinion, should throw an error if a subscriberId is sent (command.subscriberId) to the query, but no such subscriber exists. If no subscriberId is sent to the query, should keep the current behavior. What do you think? @thenbe @jainpawan21

I agree we should throw error

**Comment by kumarUjjawal** [comment]
Is anyone working on this?

**Comment by gitstart** [comment]
> Is anyone working on this?

Yes I am

**Comment by gitstart** [comment]
But I think @jainpawan21 already pushed a fix for this
