### ISSUE TITLE
🚀 Feature: Access actor information from notification templates

### ISSUE THREAD

**Issue by richardbutler** [novuhq/novu#3583]
### 🔖 Feature description

Allow notification templates to access information provided by the actor's subscriber object.

### 🎤 Why is this feature needed ?

I want to add a simple connection request notification - "John Smith would like to connect". At present, I'm sending { firstName, lastName } as part of the payload, but this is duplicate data as this is also available via the actor (I'm sending { actor: { ... } } alongside the payload: { ... }. It doesn't appear in the default variables when creating a notification template, but it seems like an obvious thing to be able to use, as {{ actor.firstName }}, for example.

### ✌️ How do you aim to achieve this?

Currently, actor information isn't passed into the template builders, it should be a straightforward change to make this available.

### 🔄️ Additional Information

I tried various variable accessors in the template builder UI but none of them worked. On submitting a query to Discord, I was asked to create an issue for this use case.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by LetItRock** [comment]
the actor variables were implemented in [this PR](https://github.com/novuhq/novu/pull/4278) and are released in Novu Cloud ;)
