### ISSUE TITLE
🚀 Feature: Add Resend provider

### ISSUE THREAD

**Issue by raikasdev** [novuhq/novu#3587]
### 🔖 Feature description

The [Resend](https://resend.com) email API is now available for everyone. Add it as an Email provider to Novu.

### 🎤 Why is this feature needed ?

Resend has some very nice features. Also supporting more providers is good.

### ✌️ How do you aim to achieve this?

Use the [Resend Node API](https://www.npmjs.com/package/resend)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
@raikasdev I think Novu supports Resend provider or I'm missing something?

![image](https://github.com/novuhq/novu/assets/43048524/10d4455d-f5d6-4f83-bbd4-970e7619f83d)

[Source code for Resend provider](https://github.com/novuhq/novu/tree/e10d9af304234c9f186157d4a5b1404d5230780d/providers/resend)

**Comment by BiswaViraj** [comment]
Closing this issue as Resend provider was added in the release [v0.12.0](https://github.com/novuhq/novu/releases/tag/v0.12.0).
