### ISSUE TITLE
[NV-2446] 🐛 Bug Report: Workflows visual bug

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#3615]
### 📜 Description

`Category` and `Created At` columns overlap when category has longer name
 

### 👟 Reproduction steps

1. Create workflow with SDK
```js
// index.js
require('dotenv').config();
const { Novu } = require('@novu/node');
const novu = new Novu(process.env.NOVU_API_KEY);

async function main() {
    const longerName = 'qjwhwefhusefhrufhrdyufvhduvfhdudhfudhguifdhgdufghfdughdfugdfhgudsdsdsf'
    const group = await novu.notificationGroups.create(longerName);

    await novu.notificationTemplates.create({
        name: longerName,
        active: true,
        description: "Test Template :)",
        notificationGroupId: group.data.data.id,
        draft: false,
        steps: [],
    });
}

main();
```
2. Go to Workflows page

![image](https://github.com/novuhq/novu/assets/43048524/8f75c8d0-a6fb-4ac8-955d-e57afe8757a4)

### 👍 Expected behavior

Other columns don't overlap because they are limited
![image](https://github.com/novuhq/novu/assets/43048524/5177fb98-5bfd-4553-aacd-71d617c12175)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/43048524/287b7299-eaae-4997-904b-4e7b33a4f03c)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2446](https://linear.app/novu/issue/NV-2446/🐛-bug-report-workflows-visual-bug)</sub>

**Comment by scopsy** [comment]
@scopsy thank you for the report 🙏

**Comment by gitstart** [comment]
@scopsy I would like to pick this up
