### ISSUE TITLE
🐛 Bug Report: refetching broken when using feeds

### ISSUE THREAD

**Issue by david-morris** [novuhq/novu#3624]
### 📜 Description

Websockets should prompt refetching of feeds and counts when applicable.  But in version 0.16 of `@novu/notification-center` I need a refetch interval or notifications will remain stale until a reload. I think that this has to do with the fact that all my Novu usage is using feeds --- both counts and notifications are only fetched per-feed.

### 👟 Reproduction steps

1. write a notification center which never fetches all feeds
2. send a message to it (in my case from a version 0.15 local server) on a feed it reads

OR

2. delete a message from the notification center from the three-dots menu of that message

### 👍 Expected behavior

- the useFeedUnseenCount hook should trigger a react rerender with an updated value
- the list of messages should trigger a react rerender with an updated value if there's a mounted component with that hook open, e.g. PopoverNotificationCenter

### 👎 Actual Behavior with Screenshots

- immediately after sending the message from the server, the browser fetches a count of total messages (but doesn't seem to act on it...). That makes me think that at least when this happens, the websockets are still doing something.
![image](https://github.com/novuhq/novu/assets/5530960/f7f9627c-c154-40e2-b779-fa6524d74467)

- useFeedUnseenCount values don't change until reload
- PopoverNotificationCenter values don't change until reload
- on views that have multiple feeds simultaneously --- and thus multiple providers simultaneously --- I see "websocket error" in the console, even when the providers aren't nested.  I think that's new. 
![image](https://github.com/novuhq/novu/assets/5530960/efb207b7-0a70-402c-b1cc-7fd5b7b5338b)

### 📃 Provide any additional context for the Bug.

This worked fine in version 0.13 of the client.
When polling is enabled in one hook, everything else works too.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
We have replaced the feeds functionality with a more flexible inbox tabs API with @novu/react
