### ISSUE TITLE
[NV-2469] 🚀 Feature: Rename Sendinblue to Brevo

### ISSUE THREAD

**Issue by p-fernandez** [novuhq/novu#3627]
### 🔖 Feature description

Sendinblue is rebranding into Brevo.
Reference: https://www.brevo.com/blog/becoming-brevo/

New Brevo users might not know they could use Sendinblue provider in Novu.
Also depending in how they do the rebranding a migration might be needed.
We need to implement the changes needed to support this rebranding for existing and future users.

### 🎤 Why is this feature needed ?

We need to implement the changes needed to support this rebranding for existing and future users.

### ✌️ How do you aim to achieve this?

* Check if rebranding implies a migration
* Update the UI to reflect the rebranding and the potentially co-living of both brands.
* Update logos, links and documentation references.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2469](https://linear.app/novu/issue/NV-2469/🚀-feature-rename-sendinblue-to-brevo)</sub>

**Comment by gitstart** [comment]
@p-fernandez @scopsy I would like to pick this up

**Comment by ankur0904** [comment]
Can I work on this issue?
