### ISSUE TITLE
[NV-2504] 🐛 Bug Report: Typo on Workflows page of the main site

### ISSUE THREAD

**Issue by Njong392** [novuhq/novu#3663]
### 📜 Description

(Wasn't sure if I had to create this issue under some other category)

On the main site, [right here](https://web.novu.co/workflows), when I click on Create Workflow, and then hover over Password reset, the hover message says `An emai sent when the user requests a password reset`. I believe `email` there is spelt wrong.

Also, I'd love to be assigned to this issue please 😊

### 👟 Reproduction steps

1. Go to Workflows page
2. Click the Create Workflow button
3. Hover on Password Reset and read hover message

### 👍 Expected behavior

The word `emai` in the hover text should be `email`

### 👎 Actual Behavior with Screenshots

![Screenshot (89)](https://github.com/novuhq/novu/assets/81039882/0ad35887-ef05-40c9-b4b1-c4962144d298)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-2504](https://linear.app/novu/issue/NV-2504/🐛-bug-report-typo-on-workflows-page-of-the-main-site)</sub>

**Comment by Grgnavin** [comment]
Hey can someone assign this to me??

**Comment by Grgnavin** [comment]
Hey, would someone be able to assign this to me?

**Comment by ainouzgali** [comment]
Hi! @Grgnavin @Njong392  thank you! But, this text lives in an internal novu organization. They are actual workflows created in Novu. So, it must be fixed inside the org.
I will pass it on to the team. 
Thank you both!

**Comment by Njong392** [comment]
> Hi! @Grgnavin @Njong392 thank you! But, this text lives in an internal novu organization. They are actual workflows created in Novu. So, it must be fixed inside the org. I will pass it on to the team. Thank you both!

Ah, thank you @ainouzgali I was about to ask what files needed editing because I couldn't find where to work.

**Comment by scopsy** [comment]
@Njong392 thank you for you submission! I have update the content on our CMS platform (changes should be reflected soon after cache invalidation) 🙏
