### ISSUE TITLE
[NV-2500] 🐛 Bug Report: `credentials.region must be a string` error in SparkPost email integration

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#3670]
### 📜 Description

In SparkPost provider integration for email, when we try to add our credentials, and then click on connect, it throws `credentials.region must be a string` error

### 👟 Reproduction steps

1. Go to Integration Store
2. Scroll to SparkPost provider in the Email channel
3. Click on connect
4. Add all Credentials
5. Region toggle can be either EU or Non-EU
6. Click on connect button of modal
7. There is an error

### 👍 Expected behavior

It should not throw an error

### 👎 Actual Behavior with Screenshots

https://github.com/novuhq/novu/assets/39362422/13eb8979-8745-4e8c-a69f-380a1e4e13b3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2500](https://linear.app/novu/issue/NV-2500/🐛-bug-report-credentialsregion-must-be-a-string-error-in-sparkpost)</sub>

**Comment by michaldziuba03** [comment]
@jainpawan21 can you assign me?

**Comment by yashh05** [comment]
can you assign this to me ?

**Comment by jainpawan21** [comment]
@yashh05 
Thanks for your interest
We highly appreciate it.

But this issue is already assigned and the assignee has created a PR

**Comment by nbharti015** [comment]
Can you please assign this to me ??

**Comment by michaldziuba03** [comment]
@nbharti015 

I will finish my already opened PR very soon
