### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by gooddavvy** [novuhq/novu#3700]
I'm confused is Novu just a developer-based platform for chatting? Please explain further.

**Comment by michaldziuba03** [comment]
hello @gooddavvy 

Real-time notifications may be tricky to implement on your own, so  Novu provides ready to use notification center and API to trigger events. Novu is a platform that unifies way you send notifications. Many channels are supported (sms, email, in-app, push, chat) and many providers across channels (like SendGrid, Twilio, FCM and more).

![notification-center](https://github.com/novuhq/novu/assets/43048524/028c2166-3bd5-445b-a392-90e3a1f1feec)
> Notification center widget is ready to use and easy to integrate in your existing app. 
If you want - you still can build your own custom GUI using [headless library](https://docs.novu.co/notification-center/headless/headless-service/)

Another feature is workflow editor which can be used even by no-programmers. You can easily define just in dashboard steps - what will happen when you trigger specific event.

![image](https://github.com/novuhq/novu/assets/43048524/2397c67e-908e-4d91-a125-ac9c1277b1e9)

> Workflow editor - here you can define what happens after event trigger. 

My favourite feature is **digest engine** - it collects multiple events from the trigger and then combines them into single notification message (you can see something similar on twitter, when your tweet gets for example 100 likes in short amount of time, you will get only one notification (not 100) about 100 people who liked your post).

You can also **delay** notification delivery - as you can guess you can schedule **when** notification is to be delivered.

There is more things to say, but if you are interested - I recommend [documentation](https://docs.novu.co/overview/introduction).

#### Docs have whole section about how platform works:

![image](https://github.com/novuhq/novu/assets/43048524/4cde4d3b-1091-4483-9741-fe1bb9fb6195)
