### ISSUE TITLE
[NV-2553] 📚 Docs: Quickstart Guide for NestJS 

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu#3737]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/overview/quickstart/general-quickstart

### Kind of issue

Other

### Issue description

There are quickstart guides for some languages. Currently, we have PHP, Kotlin, Node.js etc

A quickstart guide is needed for NestJS

### Context 🔦

Writing a quickstart guide for NestJS. 

Here are existing quickstart guide examples to follow while making it.

- [PHP Quickstart](https://docs.novu.co/overview/quickstart/get-started-with-php)
- [Node.js Quickstart](https://docs.novu.co/overview/quickstart/get-started-with-node.js)
- [Kotlin Quickstart](https://docs.novu.co/overview/quickstart/get-started-with-kotlin) 

<sub>[NV-2553](https://linear.app/novu/issue/NV-2553/📚-docs-quickstart-guide-for-nestjs)</sub>

**Comment by unicodeveloper** [comment]
Assigning this to you @michaldziuba03

**Comment by unicodeveloper** [comment]
Please ensure to submit your PR against the `main` branch when you are ready.

**Comment by Marrwan** [comment]
@unicodeveloper Is this issue assigned already?

**Comment by michaldziuba03** [comment]
@Marrwan yes, I work on this issue. There is even PR created by me and it will be finished very soon.
