### ISSUE TITLE
🐛 Bug Report: TriggerRecipientsTypeEnum is not exported.

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#3786]
### 📜 Description

I cannot trigger notification to multiple recipients in TypeScript app with Novu Node.js SDK, because **TriggerRecipientsTypeEnum** is required but not exported.

### 👟 Reproduction steps

1. add Novu SDK for Node.js to any TypeScript project. My app is normal NestJS, just generated with CLI and default `tsconfig.json`.
2. Try to trigger enum to multiple recipients:

```ts
await this.novu.trigger('some-workflow', {
      to: [{ type: 'Topic', topicKey: key }],
      payload: {}
    });
```

> TS Error: **Type '"Topic"' is not assignable to type 'TriggerRecipientsTypeEnum.TOPIC'**

3. Cannot run app

### 👍 Expected behavior

I should be able to import `TriggerRecipientsTypeEnum` from `@novu/node`.

### 👎 Actual Behavior with Screenshots

Here is current behavior of TypeScript client with Novu Node.js SDK:

![ts](https://github.com/novuhq/novu/assets/43048524/98beb1cd-fba3-4b07-bcb4-bfb645eb74d4)

I cannot import this enum, because it is not exported.

![ts2](https://github.com/novuhq/novu/assets/43048524/7ac48366-9eb8-48b8-857d-35de449001e0)

### 📃 Provide any additional context for the Bug.

- Windows 11
- Node v18.12.1
- npm 8.19.2
- Visual Studio Code

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gitstart** [comment]
@scopsy I would like to pick this up

**Comment by michaldziuba03** [comment]
@gitstart I recently started working on PR for this issue
