### ISSUE TITLE
🐛 Bug Report: Web Portal Hangs During Brand Logo Upload

### ISSUE THREAD

**Issue by kridafans** [novuhq/novu#3806]
### 📜 Description

When attempting to upload the brand logo on the web portal, the system becomes unresponsive and hangs indefinitely. This issue occurs consistently and prevents users from successfully completing the logo upload process.

### 👟 Reproduction steps

Access the web portal.
Navigate to the Brand and logo upload section.
Select the brand logo file from the local device.
Click on the "Upload" button.

### 👍 Expected behavior

The brand logo should be successfully uploaded, and the web portal should remain responsive throughout the process.

### 👎 Actual Behavior with Screenshots

After clicking the "Upload" button, the web portal becomes unresponsive and hangs indefinitely. The logo upload process is not completed, rendering the portal unusable.

### 📃 Provide any additional context for the Bug.

This issue has been replicated on multiple devices and web browsers.
Other functionality on the web portal appears to be working correctly.
The size and format of the logo file meet the specified requirements.
No error messages or notifications are displayed when the hang occurs.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
Hi @kridafans 
Is this issue happening on web.novu.co?
I tried to reproduce this multiple times. It worked for me.
Could you please share screen recording?

**Comment by kridafans** [comment]
I am also not able to reproduce the issue now, however it happened earlier multiple times when I tried to change brand color or Brand logo on web.novu.co.
