### ISSUE TITLE
[NV-2574] Allow storing custom metadata on the workflow entity

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#3850]
### Why?

When displaying a custom UI for the user preference menu, customers would love to render those preference items with some extra information or filter our specific preferences based on this custom metadata.

### What?

* Allow customers to add and update custom metadata information (JSON Object) and pass it to the workflow
* When fetching the preference API, attach the workflow information as a joined object with identifier, and custom metadata provided there
* Other place which populate the workflow objects such as notification feed, add the custom object metadata to it. 

### Definition of Done

* Allow storing custom data using the API on the workflow
* Populate workflow custom data on the user preference API response
* (Optional) Allow viewing custom metadata on the user interface in the workflow UI

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2574](https://linear.app/novu/issue/NV-2574/allow-storing-custom-metadata-on-the-workflow-entity)</sub>

**Comment by gitstart** [comment]
@scopsy we would like to pick this up
