### ISSUE TITLE
[NV-2610] 🏗️ Provide the ability to rearrange steps in a workflow

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#3854]
**What?**

WF editor steps order

**Why?**

Currently, users won't be able to rearrange step orders, so if they make a mistake and put a step into the wrong order, they may just create a new step in the desired place of a workflow. But he needs to fill in all the metadata for that step all over again. We assume that UX where UI prompts users to do double work in case they made a mistake with a steps order might be confusing.

**How?**

Allow users to reorder steps by **drag and drop.**

**MECHANICS**

* User hover over a step
* UI display D&D hover icon near a step
* User clicks on the icon and drags it Up or Down
* When the step becomes closer than distance 8px to its neighbor, they switch places.
* The dragged step takes the place of its neighbor, the neighbor takes the place of a step that was dragged

Example

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/5c2e111d-3b18-4e49-a81e-49418b9409c0/a7ceebbc-23a1-4008-94c3-69418aaca601?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YxM2YxOTk2LWM5YjAtNGZlYS04ZWU3LTJjM2ZhZjZhODMyZC81YzJlMTExZC0zYjE4LTRlNDktYTgxZS00OTQxOGI5NDA5YzAvYTdjZWViYmMtMjNhMS00MDA4LTk0YzMtNjk0MThhYWNhNjAxIiwiaWF0IjoxNzAzMTIxMDc1LCJleHAiOjE3MDMyMDc0NzV9.gClE7c9e4wyKb6G4Ga_7wZtS_W3I5OWqS2--aFqYiVI)

[Re-order steps - Workflow create/edit (Figma)](https://www.figma.com/file/72BWZJMFf9aikgI7CPpohp/Workflow-create%2Fedit?type=design&node-id=274-53699&mode=design&t=G2ykbLhUeNYYGvOS-4)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2610](https://linear.app/novu/issue/NV-2610/🏗️-provide-the-ability-to-rearrange-steps-in-a-workflow)</sub>

**Comment by feliciien** [comment]
can I work on this?

**Comment by scopsy** [comment]
@Ashutosh-Bhadauriya please notice on the figma link with the design specification for this task 🙏 If access is missing please let me know

**Comment by Ashutosh-Bhadauriya** [comment]
@scopsy thanks for asking. Yes, I have view access to the file.

**Comment by gitstart** [comment]
@scopsy we would like to pick this up

**Comment by kunal00000** [comment]
I see this issue is unsolved, I'd like to take this up.

/attempt #3854

**Comment by Shiva1406** [comment]
@scopsy can you please assign this issue to me? I would like to take a look into this.

**Comment by devilserpent123** [comment]
is this solved?

**Comment by oleksandr-shvets** [comment]
@gtanchak Is this issue solved? Can I take it?

/attempt #3854

**Comment by oleksandr-shvets** [comment]
@scopsy Is this issue solved? (May be fixed by #4835)
Can I start work on it?
