### ISSUE TITLE
🐛 Bug Report: Release process

### ISSUE THREAD

**Issue by szbartnik** [novuhq/novu#3858]
### 📜 Description

Not sure how to approach this problem but `PaginatedResponseDto` had breaking changes recently:
https://github.com/novuhq/novu/pull/3792

`totalCount` has been removed and `hasMore` has been introduced.

The changeset is tagged as `0.17.0` which means breaking changes are technically ok. But... the breaking change is already there. We are using Novu & we had no time to migrate our code. The `totalCount` property was not deprecated & there were no communication around it anywhere (unless I missed something).

Assuming you are rolling out `0.17.0` currently but there are no release notes yet. Is it something that can be improved for future releases? My thinking is that:
- Stuff which is about to be removed should be marked as deprecated so developers have time to migrate
- If it happens that breaking changes are needed, it should be better communicated. Are there any channels you can recommend developers can follow in order to be up to date?
- Pre-release notes should be created before rolling out new version so it's more transparent for developers what they should expect

BTW. Great product! Thank you for all what you're doing!

### 👟 Reproduction steps

Call `GET /subscribers` endpoint

### 👍 Expected behavior

`PaginatedResponseDto` returns `totalCount` property

### 👎 Actual Behavior with Screenshots

`PaginatedResponseDto` returns `hasMore` property instead as there was a breaking change in:
https://github.com/novuhq/novu/commit/e50b8d0f1cc3c16f75d591579b3a10c35ed842b1#diff-66cef6a6018227a5be21522679b424272fc12135aaa5879533666db0b57a37a0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
Hi @szbartnik I'm incredibly sorry for your experience, we are working right now on a formal process internally on how to manage it better. The changes were required to help with performance optimization, but we could take a much more gradual approach with that.

I'm scheduling a call with the team around the guidelines on gradual API changes specific to cloud users who get the latest API updates (not versioned as in self-hosted).

We will make an announcement on the Release notes of the version with future deprecation + mark them on Swagger. I'm also trying to review an option to get an email subscription for upcoming changes, so we can tackle this on multiple channels.

Thank you for your feedback and submitted issue, appreciate this a lot. 

Will close for now, and will post updates regarding the process here 🙏
