### ISSUE TITLE
📚 Docs Feedback: listenNotificationReceive missed

### ISSUE THREAD

**Issue by mihail727** [novuhq/novu#3883]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/notification-center/headless/api-reference/#listennotificationreceive

### Kind of issue

Other

### Issue description

I was looking for ... and it appears that ...
The documentation declares the listen Notification Received function, but it is not in the lib, in the package @novu/headless

**Comment by ainouzgali** [comment]
Hi @mihail727 ! What version are you using? This one was added in v0.17.0

**Comment by mihail727** [comment]
I'm sorry, my mistake, it looks like the module cache has not been updated
