### ISSUE TITLE
Preview Environments for Novu PRs?

### ISSUE THREAD

**Issue by evoxmusic** [novuhq/novu#3888]
Hey Novu team 👋🏽 ,

I'm Romaric from the [Qovery](https://github.com/qovery) team (a Crane backed company as well as you :) ).

I'm a huge believer in the open-source community and absolutely love the work you and your team have put into Novu. It's projects like yours that keep the tech world spinning!

Because of my admiration for open source, I've kickstarted a *Support Open Source Program*. The idea is to offer free access to Qovery, including our cutting-edge [Preview Environment system](https://www.qovery.com/solutions/ephemeral-environments), to selected open-source projects.

But let's talk about why our Preview Environment system is such a game-changer for Novu and your community. With this system, every pull request is spun into a fully functional, isolated testing environment before it gets merged. This can supercharge your workflow in several ways:

- **Test in Real Conditions**: With an isolated environment for each pull request, contributors can thoroughly test their changes in real-life conditions before the code is merged.
- **Accelerate Feedback Loop**: It allows the community to interact with the changes early on and provide valuable feedback, leading to better and faster improvements.
- **Bug Detection**: The chance of bugs sneaking into the production code is significantly reduced, which means less time debugging and more time building cool features!
- **Collaborative Spirit**: It fosters a collaborative spirit within the community by enabling contributors to see the direct impact of their changes and encourages new contributors to participate in the project.

Preview Environments could really enhance the way you work on Novu, allowing you to speed up development, enhance code quality, and make collaboration even more fun and efficient.

I'm eager to discuss how Qovery and our Preview Environment system can support Novu. If this piques your interest, please drop me a line with a good time to chat.

Keep up the fantastic work 💪🏼

Romaric.

**Comment by scopsy** [comment]
@evoxmusic long time! :) 

Preview Environments it's definitely something we wanted to implement for a while now, unfortunately all the tools we used just didn't work for one reason or the other. Would love to chat regarding that cc. @LetItRock
