### ISSUE TITLE
🐛 Bug Report: can't reset password on self-hosted Novu and sometime lost account

### ISSUE THREAD

**Issue by huynv86** [novuhq/novu#3892]
### 📜 Description

Hi team,

I tried to self-hosted Novu but there're two problem:
- I created an account and used this account normally but later I can't login with reseaon  wrong password even I don't change password. Then I have to re-create account with same old email, Novu still create new account but reset to blank account even this account already exist
- I tried to reset password but Novu didn't send an email. I don't know how to configure email for self-hosted, could you please show me docs or instruction

Hope you reply soon, thanks

### 👟 Reproduction steps

see above

### 👍 Expected behavior

see above

### 👎 Actual Behavior with Screenshots

see above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by huynv86** [comment]
for more information:

I change 
DISABLE_USER_REGISTRATION=true
and then i run command "docker restart", account will be lost

**Comment by michaldziuba03** [comment]
hello @huynv86 

does only your account data is lost or whole database data is gone after docker restart?

If whole database then I would suspect that volume is dropped after restart for some reason.

Remember `CreatedAt` date value, then try to run `docker restart` again and check if `CreatedAt` is changed.

```sh
$ docker volume ls

local     foobar
local     xyz
local     deployment_mongodb
...

$ docker volume inspect deployment_mongodb

[
    {
        "CreatedAt": "2023-07-10T10:05:02+02:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "deployment",
            "com.docker.compose.version": "2.17.3",
            "com.docker.compose.volume": "mongodb"
        },
        "Mountpoint": "/var/lib/docker/volumes/deployment_mongodb/_data",
        "Name": "deployment_mongodb",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by huynv86** [comment]
Hello,

I run `docker volume inspect deployment_mongodb`, it always show current time
![image](https://github.com/novuhq/novu/assets/747614/76d76b87-8001-4bbb-8374-01ea8ff31457)

**Comment by huynv86** [comment]
after few hours, I lost my account again although I do nothing. Could you please help me investigate
![image](https://github.com/novuhq/novu/assets/747614/91cfd2ea-fd9e-495e-b4ee-b4b23c29f5df)

**Comment by huynv86** [comment]
I found the reason, mongodb is hacked
![image](https://github.com/novuhq/novu/assets/747614/c4d78609-99fd-473b-bd02-a42fca22719f)
