### ISSUE TITLE
[NV-2473] data field is not added in case of inline of trigger

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#3905]
We can create a new subscriber on the fly using inline of trigger

[https://docs.novu.co/platform/subscribers#2-inline-of-trigger](https://docs.novu.co/platform/subscribers#2-inline-of-trigger)

All attributes except `data` is updated/added in this case

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2473](https://linear.app/novu/issue/NV-2473/data-field-is-not-added-in-case-of-inline-of-trigger)</sub>

**Comment by jainpawan21** [comment]
@scopsy 

What is the correct flow of syncing linear issue to github

**Comment by gitstart** [comment]
@jainpawan21 we would like to work on this
