### ISSUE TITLE
[NV-2697] senderName field is missing in resend api and nodejs sdk

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#3957]
### What?

Novu allows using sender name field in email editor and via overrides. If sender name is Pawan Jain and sender from email is pawan@novu.co, in email clients shows like this `Pawan Jain <pawan@novu.co>`

### Why? (Context)

In the case of resend provider, it does not have a separate sender name field.

Ref API:- [https://resend.com/docs/api-reference/emails/send-email](https://resend.com/docs/api-reference/emails/send-email)

currently, there are two ways to handle this:- 

1. use **from** field like this in integration modal

   
![image](https://github.com/novuhq/novu/assets/39362422/9de9ac85-cd81-4248-9227-bdbe883b03b7)

2. or use overrides like this 
       `"overrides": {`
   `        "email":{`
   `            "from": "Pawan Jain Novu <pawan@novu.co>"`
   `        }`
   `    }`

Users get confused about why the sender's name is not showing up correctly.

### Definition of Done

1. Novu should automatically handle this at provider implementation
2. Update docs accordingly

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2697](https://linear.app/novu/issue/NV-2697/sendername-field-is-missing-in-resend-api-and-nodejs-sdk)</sub>

**Comment by Sangam-ghimire** [comment]
Hey @jainpawan21 @scopsy I would love to help here...seems pretty interesting

**Comment by scopsy** [comment]
@Sangam-ghimire assigned you 🙏

**Comment by Sangam-ghimire** [comment]
@scopsy  @jainpawan21 I am having trouble setting up the project locally, I have asked it in the discord channel as well.
![image](https://github.com/novuhq/novu/assets/90495874/0cd67144-cbc4-40ee-9a1b-b8d7741e4648)
I am stuck here, and the error is not getting resolved for now.

**Comment by scopsy** [comment]
@Sangam-ghimire could you try running `npm run setup:project` from project root?

**Comment by Sangam-ghimire** [comment]
> @Sangam-ghimire could you try running `npm run setup:project` from project root?

I have done that and whats next? is it optional to setup enviroment from npm start  after npm run project:setup?

**Comment by Sangam-ghimire** [comment]
> > @Sangam-ghimire could you try running `npm run setup:project` from project root?
> 
> I have done that and whats next? is it optional to setup enviroment from npm start  after npm run project:setup?

@scopsy basically I have completed successfully, npm run project:setup and while setting up the env from npm start I have faced the error shown above

**Comment by DhairyaMajmudar** [comment]
@Sangam-ghimire is you are still working in this issue. If no pls. assign me this issue

**Comment by piyushgarg-dev** [comment]
Please check PR #4237

**Comment by scopsy** [comment]
Assigned @piyushgarg-dev for this issue. 🙏
