### ISSUE TITLE
🐛 Bug Report: invalid netcore logo

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#3973]
### 📜 Description

Novu Cloud uses wrong logo for [Netcore](https://netcorecloud.com/) provider.

It uses [.NET Core](https://pl.wikipedia.org/wiki/.NET_Core) logo instead :))

![image](https://github.com/novuhq/novu/assets/43048524/c14c97ca-eeea-48ca-bb93-c6b2986ec16a)

### 👟 Reproduction steps

Just try to add `Netcore` provider on `https://web.novu.co/integrations/create`

### 👍 Expected behavior

Expected logo: 

![netcore-64x64](https://github.com/novuhq/novu/assets/43048524/0530dd9a-98f4-4283-8742-6da1a7a51bd7)

#### 32x32 SVG asset (edited by me in Figma):

![netcore](https://github.com/novuhq/novu/assets/43048524/ca66cddc-f715-477f-8c75-f7951599b6eb)

### 👎 Actual Behavior with Screenshots

Wrong actual logo:

![dotnetcore](https://github.com/novuhq/novu/assets/43048524/86fbe338-4869-43ee-93ea-a80926725c45)

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by gitstart** [comment]
@michaldziuba03 we would like to pick this up

**Comment by LetItRock** [comment]
@gitstart assigning it to you ;)
