### ISSUE TITLE
🐛 Bug Report: Error integrating @novu/notification-center-angular

### ISSUE THREAD

**Issue by lukasgreussing** [novuhq/novu#3988]
### 📜 Description

Hi, I've tried to integrate @novu/notification-center-angular into a fresh angular app, exactly how it is described in the quickstart: https://docs.novu.co/overview/quickstart/get-started-with-angular#install-novu-angular-notification-center-package

I'm getting an "Cannot read properties of null (reading 'bindingStartIndex')" error and Angular is not able to render the notification center component.

![image](https://github.com/novuhq/novu/assets/130556764/e2fb776d-71ba-43c9-84e2-cdf26efb00a7)

### 👟 Reproduction steps

1. Go through Angular Quickstart step by step with the current Angular version 16.2.0
2. Run the app

### 👍 Expected behavior

Notification center should be rendered in the Angular app without an error

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/130556764/4604925a-7b09-4817-805b-b3768b9ecdce)

### Novu version

Self hosted Novu version 0.17.1

### npm version

8.19.2

### node version

18.12.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by ArslanYM** [comment]
Can I work on this?

**Comment by scopsy** [comment]
Sure @ArslanYM 🙏

**Comment by LetItRock** [comment]
> hello @LetItRock, thanks for your reply! ok, but in the Angular quickstart requirements section it just says Angular version > 0.15.0 (I assume it's supposed to be 15.0.0). 

sorry about that, we will update it in the docs 🙏 
@jainpawan21 fyi

> Anyhow, are there plans to support Angular 16 as well? https://docs.novu.co/overview/quickstart/get-started-with-angular/#requirements

no as for now ;)

**Comment by RaminGe** [comment]
Hey there,
we are really looking forward to get novu running with Angular 16. We now have removed the angular novu package and are using the iFrame as workaround, but that is not a permanent solution.

**Comment by RaminGe** [comment]
> > Hey there, we are really looking forward to get novu running with Angular 16. We now have removed the angular novu package and are using the iFrame as workaround, but that is not a permanent solution.
> > Bye the way, the same issue as described als occurs with the webcomponent integration.
> 
> @RaminGe We have included this in our upcoming cycle. fix will be deployed around mid to end October.
> 
> Can you please share video recording / screenshot if you are able to reproduce this in web component?

Nice to hear, thanks for the update!
Regarding the web component, my bad. I just checked it again and it was just a leftover of the angular package which was throwing the error because I forgot to remove the import. Using the web component for now as a workaround.

**Comment by rifont** [comment]
The fix to support Angular 15+ in [`@novu/notification-center-angular`](https://www.npmjs.com/package/@novu/notification-center-angular) will be included in release `0.21.0` of Novu.
