### ISSUE TITLE
Wrong import in example code

### ISSUE THREAD

**Issue by zieunx** [novuhq/novu#4010]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/community/create-provider

### Kind of issue

Unclear explanations

### Issue description

The class name in `base.handler` is `BaseChatHandler`. The sample code in the document needs to be updated.

---

sample code <packages/application-generic/src/factories/mail/handlers/example-provider.handler.ts>

From
```ts
import { ChannelTypeEnum } from '@novu/shared';
import { ExampleProviderEmailProvider } from '@novu/example-provider';
import { BaseHandler } from './base.handler'; // This!!

// ...
```

To
```ts
import { ChannelTypeEnum } from '@novu/shared';
import { ExampleProviderEmailProvider } from '@novu/example-provider';
import { BaseChatHandler } from './base.handler';

// ...
```

### Context 🔦

In the process of adding a new provider, I noticed that the demo and the actual code are different.

**Comment by michaldziuba03** [comment]
hello @zieunx 

code sample is actually correct for email channel, because guide shows how to add mail provider.

**Comment by zieunx** [comment]
@michaldziuba03 Thanks!
