### ISSUE TITLE
📚 Docs Feedback: Topic key name maximum length

### ISSUE THREAD

**Issue by billyurs** [novuhq/novu#4018]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/api/topic-creation/

### Kind of issue

Missing information

### Issue description

Kindly incorporate within the document the stipulation regarding the permissible maximum length for key field in the topic creation API document. This inclusion will prove beneficial for clients as it will enable them to formulate corresponding strategies

### Context 🔦

We need to set the topic name from our client side , but we were not aware of the maximum length allowed in key field of the topic

**Comment by cannarron** [comment]
Can I work on this?

**Comment by michaldziuba03** [comment]
as far I remember there is no real length limit for key length, at least yet

I guess the limit is max size of http request :)

**Comment by billyurs** [comment]
thanks, I am closing it
