### ISSUE TITLE
[NV-2593] Feed identifier is same when feed name is same

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4026]
### What?

We have a create new feed API which has one payload `name` [https://docs.novu.co/api/create-feed/](https://docs.novu.co/api/create-feed/)

when we hit this API with same name it creates new feed with same identifier

### Why? (Context)

Since two feeds have same identifier, there will be an issue in inconsistent results items in-app messages in tab layout 

[https://docs.novu.co/notification-center/react/react-components#multiple-tab-layout](https://docs.novu.co/notification-center/react/react-components#multiple-tab-layout)

### Definition of Done

feedIdentifier should always be unique

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2593](https://linear.app/novu/issue/NV-2593/feed-identifier-is-same-when-feed-name-is-same)</sub>

**Comment by gitstart** [comment]
@jainpawan21 we would like to pick this up
