### ISSUE TITLE
[NV-2730] Add field overrides in SMS channel like we have in the Email

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4030]
## What?

We can override almost all fields in the email channel

ref:- [https://docs.novu.co/channels/email/#sending-email-overrides](https://docs.novu.co/channels/email/#sending-email-overrides)

I see we are using `from` field from credentials here, we cannot override in SMS similar to email

[https://github.com/novuhq/novu/blob/next/apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts#L265C16-L265C16](https://github.com/novuhq/novu/blob/next/apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts#L265C16-L265C16)

## Definition of done:

1. Allow all field overrides in the SMS channel similar to email
2. Add types in node sdk
3. Check if Swagger API is reflecting the change

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2730](https://linear.app/novu/issue/NV-2730/add-field-overrides-in-sms-channel-like-we-have-in-the-email)</sub>

**Comment by codingmickey** [comment]
Hi @jainpawan21 I would like to fix this one!

**Comment by mahendraHegde** [comment]
@jainpawan21  [here's my attempt](https://github.com/novuhq/novu/pull/4168), can you share your thoughts
@codingmickey  apologies for picking up without notice.
