### ISSUE TITLE
[NV-2765] 🐛 Bug Report: delay icon is not aligned with other steps icon

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4046]
### 📜 Description

While adding workflow steps, one can add new steps by clicking on plus icon. in steps Popover all steps have text and icon. Delay step icon and text seems to be un-aligned with respect to other steps 

### 👟 Reproduction steps

1. Go to workflow page
2. Create a new workflow or edit existing workflow
3. Click the plus icon
4. See the inconsistent padding or margin in delay step

### 👍 Expected behavior

It should be aligned 

### 👎 Actual Behavior with Screenshots

https://github.com/novuhq/novu/assets/39362422/7941a372-de84-468d-b992-b55e0e00a785

### Novu version

Novu SaaS

### npm version

NA

### node version

NA

### 📃 Provide any additional context for the Bug.

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2765](https://linear.app/novu/issue/NV-2765/🐛-bug-report-delay-icon-is-not-aligned-woth)</sub>

**Comment by cannarron** [comment]
Hello, may I pick this up? Thank you

**Comment by dhavall13** [comment]
Can you assign this issue ?

**Comment by gitstart** [comment]
@jainpawan21 we would like to pick this up
