### ISSUE TITLE
🚀 Feature: Add helm repo URL

### ISSUE THREAD

**Issue by cberge908** [novuhq/novu#4051]
### 🔖 Feature description

Adding a helm repo URL would ease-up the maintenance of Novu on K8s clusters. Tools like Renovate can pick up the latest updates from a helm repo and update the deployment automatically.

### 🎤 Why is this feature needed ?

See above, makes maintenance and quick start more easy.

### ✌️ How do you aim to achieve this?

- Creating a helm repository with an index.yaml
- Add a specific URL to point to this helm repository

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by cronventis** [comment]
I was actually searching for this.... Best Place to publish would also be on artifact hub

**Comment by Cliftonz** [comment]
We plan to do this within the upcoming months
