### ISSUE TITLE
🐛 Bug Report: Migration script is missing on 0.18.x branch and fails on the next

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu#4054]
### 📜 Description

Switch to the v0.18.x branch and try to run the migration, script is not there.

I then switched to the `next` branch which does have the script and it fails. See screenshots below.

### 👟 Reproduction steps

1. checkout v0.18.x branch
2. try to run migration script
3. become saddened

1.  checkout next branch
2. try and run migration script there
3. become saddened

### 👍 Expected behavior

Migration should properly run

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/11448029/bf9391a8-2634-4d76-bec3-d9c0fbe07b9b)
![image](https://github.com/novuhq/novu/assets/11448029/0064f9fa-8e2d-4618-845e-08e3e7f8df58)

### Novu version

0.17.1

### npm version

8.19.4

### node version

16.20.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
@wh1337 have you updated your .env file in the api/src folder to contain the correct mongo URL to your deployment? Also make sure you have the proper network access to it

**Comment by scopsy** [comment]
@wh1337 yes, it should be under the `src` folder with the other env specific files there 🙏
