### ISSUE TITLE
🐛 Bug Report: 0.17.1 fails to start

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu#4057]
### 📜 Description

0.17.1 fails to start no matter how I configure `IN_MEMORY_CLUSTER_MODE_ENABLED`, be that setting it to false or to true the worker doesn't seem to care which it is.

Running this against ElastiCache Redis, things worked fine on 0.14.0 so I'm not sure what changed.

#3594 - linking releated changes to this env var.

### 👟 Reproduction steps

Try to start 0.17.1 with ElasticCache Redis

### 👍 Expected behavior

Worker should run

### 👎 Actual Behavior with Screenshots

ERROR:

```
{"level":50,"time":1693409349835,"pid":18,"serviceName":"@novu/worker","serviceVersion":"0.17.1","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"There has been an error in the InMemory Cluster provider client"}
```
- Due to failing health-checks, the service restarts.

### Novu version

0.17.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
@p-fernandez any suggestion on how to debug this case? @wh1337 how are you passing the env variables for your elasticache instance? (please note that a redis cluster should only be used for the caching, and not for the queue functionality)
