### ISSUE TITLE
Activity feed not pulling in any (much) of our email activity. 

### ISSUE THREAD

**Issue by ejgennrich-joinbetter** [novuhq/novu#4080]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/platform/activity-feed

### Kind of issue

Unclear explanations

### Issue description

I am a business user of Novu, which we use to send email to customers. Our activity feed is not showing any data
<img width="1412" alt="image" src="https://github.com/novuhq/novu/assets/143820692/b7a4adf2-83a0-4d32-9101-4cdb5d1d2c08">

**Comment by scopsy** [comment]
Hi @ejgennrich-joinbetter just to clarify to help us investigate this, not seeing the environment component on the left menu, but are you on the Development environment or Production environment? (mostly that the environment will match your triggered events environment)
