### ISSUE TITLE
[NV-2822] 🐛 Bug Report: Not able to send subscriber email, first name and last name when using iFrame

### ISSUE THREAD

**Issue by baoke344** [novuhq/novu#4096]
### 📜 Description

Hi everyone, I tried to send more user data of subscriber when init like sample code on documents
`
        novu.init(
            'MY_APPLICATION_ID',
            {
                unseenBadgeSelector: '#unseen-badge',
                bellSelector: '#notification-bell',
            },
            {
                subscriberId: 'Novu_Embeded_ID_6',
                email: 'my_mail@gmail.com',
                first_name: 'Steven',
                last_name: 'Cao',
            }
        );
`

### 👟 Reproduction steps

1. Embed iFrame using doc https://docs.novu.co/notification-center/iframe-embed
2. In function call init. Sending email:, first_name: '', last_name:
3. Observe initialize request

### 👍 Expected behavior

Able to send subscriber email, firstname and last name

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/14287222/10425a30-b3e0-4cbb-bd7a-3ecf108192c9)

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2822](https://linear.app/novu/issue/NV-2822/🐛-bug-report-not-able-to-send-subscriber-email-first-name-and-last)</sub>

**Comment by gitstart** [comment]
@jainpawan21 we would like to work on this

**Comment by btme0011** [comment]
can i work on this issue?

**Comment by ainouzgali** [comment]
Hi @baoke344 , how is it going? :)  Are you still available to work on this?
If not, please let us know so we can assign someone else☺️

**Comment by jainpawan21** [comment]
> @jainpawan21 can i work on this issue?

Sure @nick2432 
Assigning this to you 🙂

**Comment by STUDIOUS-WOLF** [comment]
hi @jainpawan21  @nick2432 if the opportunity comes please assign me the issue next.
