### ISSUE TITLE
[NV-2829] 🔓 Update logout icons and text when a users click on the avatar

### ISSUE THREAD

**Issue by sumitunique777** [novuhq/novu#4111]
### 📜 Description

We can have a different icon for the logout button

### 👟 Reproduction steps

1. Click on the profile icon at the top right
2. Small Icon with sign-out button

### 👍 Expected behavior

Please implement the changes according to [this Figma designs](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=742-1491&mode=design&t=zxBADQISFjfH2Yvb-0)

### 👎 Actual Behavior with Screenshots

* 

### Novu version

0\.18.0

### npm version

*No response*

### node version

*No response*

### 📃 Provide any additional context for the Bug.

* 

### 👀 Have you spent some time to check if this bug has been raised before?

* [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2829](https://linear.app/novu/issue/NV-2829/🔓-update-logout-icons-and-text-when-a-users-click-on-the-avatar)</sub>

**Comment by gitstart** [comment]
@sumitunique777 we would like to pick this up cc @scopsy @jainpawan21

**Comment by coder-pink** [comment]
@jainpawan21  I want to work on this.

**Comment by captain-Akshay** [comment]
@jainpawan21 can you assign it to me!

**Comment by maverox** [comment]
i want to work on this issue

**Comment by Sparsh-06** [comment]
working on it!, don't worry!

**Comment by Vishrut19** [comment]
Is anyone working on it ?

**Comment by ratishjain12** [comment]
@jainpawan21 can I work on this issue ?

**Comment by narendercoder** [comment]
@jainpawan21 can I work on this issue?

**Comment by maverox** [comment]
@jainpawan21 I have opened a PR with the appropriate fix, PR #4239 !
Can you please review it

**Comment by maverox** [comment]
@scopsy  
I was actually working ahead of time on it being a first time contributor I didn't knew whether it's compulsory to be assigned to start working on something or not?

**Comment by maverox** [comment]
> @maverox assigned you on this

Please check PR #4239

**Comment by lazyMonk1010** [comment]
hey i want to work on this issue

**Comment by hazedehaze** [comment]
Can I work on this?
