### ISSUE TITLE
Add edit button on Tenant Listing

### ISSUE THREAD

**Issue by sumitunique777** [novuhq/novu#4112]
### 🔖 Feature description

We can enhance the user experience by adding an edit button to the tenant's listing page, allowing users to easily make edits.
Let me know if it is valid. I can take up this feature

### 🎤 Why is this feature needed ?

To enhance users Experience

### ✌️ How do you aim to achieve this?

-

### 🔄️ Additional Information

-

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
@nknyshov would love to hear your thoughts on the suggestion here

**Comment by nknyshov** [comment]
Hey @scopsy, I agree with @jainpawan21 here. 
The user is able to edit a tenant by clicking on its row in the list view. Adding a button would not change the interaction logic with the tenant card.

Let's imagine we will add a button in the row. A user clicks on the button, the UI opens the side panel to edit as it does currently just on the click by the tenant row.

@sumitunique777 Let me know if I got your suggestion wrong

**Comment by LetItRock** [comment]
hey @sumitunique777 👋 Thanks for the suggestion.
But, I agree with @nknyshov. Additionally, we use this pattern everywhere across the app. Closing this for now.
