### ISSUE TITLE
/v1/integrations request gives error 500

### ISSUE THREAD

**Issue by ghost** [novuhq/novu#4146]
Hi, we updated the new version to 0.18.0 (our updates are automatic). After the update, we stopped the service and started migration (https://github.com/novuhq/novu/releases/tag/v0.18.0, item "Migration for Self-hosted Novu Users"), but due to missing modules, the migration did not start. Then we returned to the version below (0.10.1). On the old version, notifications work, but when I go to the Integrations store page there is a black screen. /v1/integrations request gives error 500. Other queries work. Mongodb and redis work.
![problem](https://github.com/novuhq/novu/assets/144789607/4a8aeb54-c43e-41d6-be56-c7363fcfe8df)

**Comment by KateMin07** [comment]
In the logs
![image](https://github.com/novuhq/novu/assets/144789607/f0aebfa0-af76-4f27-9fe9-acb8dfe5b8f4)
![image](https://github.com/novuhq/novu/assets/144789607/6b1654f5-4716-4bbb-b00d-fb5e6d890f15)

**Comment by scopsy** [comment]
Was resolved 🙏
