### ISSUE TITLE
🚀 Feature: missing methods in Node SDK

### ISSUE THREAD

**Issue by sumitsaurabh927** [novuhq/novu#4164]
### 🔖 Feature description

Two methods are missing in the Node SDK:
- execution details: /v1/execution-details
- inbound parse: /v1/inbound-parse/mx/status

Please add these to the SDK

### 🎤 Why is this feature needed ?

To bring the SDK on par with the API endpoint methods available

### ✌️ How do you aim to achieve this?

Tagging @jainpawan21 to work on this issue, as requested by Prosper.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by peoray** [comment]
can I pick this up?

**Comment by sumitsaurabh927** [comment]
sure go ahead @peoray

**Comment by sumitsaurabh927** [comment]
Any update on this @peoray ?

**Comment by peoray** [comment]
@sumitsaurabh927 will send in a PR asap

**Comment by jainpawan21** [comment]
Hi @peoray 
Are you still working on this?

**Comment by peoray** [comment]
@jainpawan21 yeah, already started working on it but slacked a bit. will get a PR up
