### ISSUE TITLE
🚀 Feature: Providing as Cloud Service?

### ISSUE THREAD

**Issue by kissfrog** [novuhq/novu#4174]
### 🔖 Feature description

Like a SaaS

### 🎤 Why is this feature needed ?

Self-hosting itself is unstable, and notification server might be down before sending to notice.

### ✌️ How do you aim to achieve this?

Get a public cloud service -- free / paid

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
Hi @kissfrog, we have an available cloud offering at https://web.novu.co https://eu.web.novu.co
