### ISSUE TITLE
📚 Docs Feedback: missing response data

### ISSUE THREAD

**Issue by sumitsaurabh927** [novuhq/novu#4191]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/api-reference/subscribers/handle-providers-oauth-redirect

### Kind of issue

Missing information

### Issue description

I was looking for response data and it appears that it isn't there

**Comment by sarojregmi200** [comment]
@sumitsaurabh927 Thanks for raising the issue, I raised the issue again in the correct repo as mentioned by someone from the team.

I am not trying to be rude but I believe this issue can be close here. 
Hope you understand.
