### ISSUE TITLE
🐛 Bug Report: Switch style messed up when adding a long description 

### ISSUE THREAD

**Issue by firassziedan** [novuhq/novu#4198]
### 📜 Description

On the integrations page, within the integration popup, when a switch component is present as part of an integration option, and that switch component includes a lengthy description, there is a formatting issue where the description and the input element are not properly aligned.

### 👟 Reproduction steps

1- Edit/Create integration and that integration has a switch component and add a description to that component 
2- open integrations pages
3- open the integration dialog 

### 👍 Expected behavior

I believe it would be more visually appealing if the description were placed on a new line, separate from the input wrapper.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-09-24 at 11 07 00](https://github.com/novuhq/novu/assets/18222016/6301e61f-464c-491b-aaf9-90508d6e0ab5)

### Novu version

next

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gitstart** [comment]
@firassziedan we would like to pick this up cc @scopsy @jainpawan21

**Comment by scopsy** [comment]
@gitstart I would love to close first the open PR's and merge them before we will assign more issues 🙏

**Comment by cdxgh** [comment]
@LetItRock, @scopsy I would like to work on this issue.

**Comment by jainpawan21** [comment]
@cdxgh how is it going with this issue?

**Comment by scopsy** [comment]
@nknyshov could you please take a look at this, and perhaps provide a design alternative in case you think it will be better?

**Comment by jainpawan21** [comment]
@firassziedan 

Since we have updated integrations UI, could you please share the steps to reproduce?
I could not reproduce this

**Comment by firassziedan** [comment]
@jainpawan21 you can see it by open `Generic SMS` provider and scrolling to `Authenticate by token` field 

<img width="782" alt="Screenshot 2023-12-21 at 17 26 54" src="https://github.com/novuhq/novu/assets/18222016/6c7f11c5-e2a0-4d88-8964-f3b01434a033">
