### ISSUE TITLE
🚀 Feature: Add snippets for Python

### ISSUE THREAD

**Issue by Mitra-Electronics** [novuhq/novu#4201]
### 🔖 Feature description

You should add snippets for Python

### 🎤 Why is this feature needed ?

In my use case, it is needed as I program in Python and it becomes easier to make applications using it. 

### ✌️ How do you aim to achieve this?

I want this feature to allow me the option to copy a python snippet wherever there is the option to copy a JS snippet or a curl snippet.

### 🔄️ Additional Information

I tried to use the Python documentation, but I couldn't get my app to work as the documentation is poorly made and doesn't cover all use cases.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by ayrotideysarkar** [comment]
Can i work on this?

**Comment by Mitra-Electronics** [comment]
Yup

**Comment by davidsoderberg** [comment]
Hi @Mitra-Electronics I think this issue belongs in https://github.com/novuhq/docs/issues please add it there instead.
