### ISSUE TITLE
🚀 Feature: support blink(1) as notification device

### ISSUE THREAD

**Issue by hinolulu** [novuhq/novu#4203]
### 🔖 Feature description

https://blink1.thingm.com/

### 🎤 Why is this feature needed ?

https://blink1.thingm.com/

### ✌️ How do you aim to achieve this?

https://blink1.thingm.com/

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by AlexVCS** [comment]
Hi there, are we able to integrate with this device? If so I'm willing to work on it. Thanks
