### ISSUE TITLE
[NV-2927] 📚 Docs Feedback: 404 on Kubernetes ReadMe

### ISSUE THREAD

**Issue by pascal-mueller** [novuhq/novu#4221]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/novuhq/novu/blob/next/docker/Readme.md

### Kind of issue

Other

### Issue description

The first sentence in the docker readme: https://github.com/novuhq/novu/blob/next/docker/Readme.md
contains a hyperlink to the kubernetes readme but there is no such readme, the link results in a 404.

### Context 🔦

I just try to figure out how to deploy it with Kubernetes

<sub>[NV-2927](https://linear.app/novu/issue/NV-2927/📚-docs-feedback-404-on-kubernetes-readme)</sub>

**Comment by michaldziuba03** [comment]
hello @pascal-mueller 

There are two readme files regarding Kubernetes: for [Helm](https://github.com/novuhq/novu/blob/19bf4f1b3abfc079be6591a690af06cf1ab2162f/docker/kubernetes/helm/README.md) and [Kustomize](https://github.com/novuhq/novu/blob/19bf4f1b3abfc079be6591a690af06cf1ab2162f/docker/kubernetes/kustomize/README.md)

**Comment by Shiva1406** [comment]
Can I fix the hyperlinks in the documentation?
