### ISSUE TITLE
[NV-2128] Add unmask button for API keys

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4231]
## What?

Implement an unmask button for the API key field..

## Why?

The user has the option to copy the API key and application identifier. Sometimes in the case of self-hosting, the browser blocks the copy action on http.

## Definition of done

* the unmask button is added to the API key field on the left to the copy button
* when the unmask button is clicked the API key value is shown to the user

[Worflows / New workflow - Crafting updates (Figma)](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=874%3A29001&mode=design&t=wL6gkqUIVAqvkksm-1)

[Worflows / New workflow - Crafting updates (Figma)](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=874%3A28854&mode=design&t=wL6gkqUIVAqvkksm-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2128](https://linear.app/novu/issue/NV-2128/add-unmask-button-for-api-keys)</sub>

**Comment by varaprasadh** [comment]
I will raise a PR in a couple of hours.

**Comment by pedrobruneli** [comment]
Can i contrib to this one?

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by LetItRock** [comment]
@pedrobruneli assigning this one to you ;)
