### ISSUE TITLE
📚 Docs Feedback: clarify how to run novu with Docker for development

### ISSUE THREAD

**Issue by collimarco** [novuhq/novu#4236]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/self-hosting-novu/deploy-with-docker

### Kind of issue

Missing information

### Issue description

I would like to start a dev environment for novu without having to configure everything as described here:

https://docs.novu.co/community/run-in-local-machine 

The above guide does not use Docker compose and requires a local installation of all the dependencies (including the databases, services, etc)...

So I went here:

https://docs.novu.co/self-hosting-novu/deploy-with-docker

However this seems for production, it uses the novu images from the online container registry, not the local code.

Can you please provide a clear explanation about starting novu locally for **development** using **Docker / Docker compose** or similar?

**Comment by RahulMishra0722** [comment]
The changes are not being propagated when you make changes and shut down the containers and re build it right? @https://github.com/collimarco

**Comment by collimarco** [comment]
I don't understand your question... I mean, the problem is that the guide is using the remote images and it's for deployment. I was looking for a solution that is local, for development, and can possibly read the new code without building everything for each small change (e.g. a docker image linked to the code in a local directory).

**Comment by RahulMishra0722** [comment]
This is what I did , I cloned the repo and the code ran just fine but when i made any changes it did not get updated and nothing changed even if you re build the containers i tried to re build it multiple times the changes just doesn't get propagated @collimarco

**Comment by jainpawan21** [comment]
@RahulMishra0722 

our docker images are for deployment
Please use nom run setup:project and then run individual services to run novu in local machine
