### ISSUE TITLE
[NV-1152] Make the entire error rectangle clickable raher than the arrow only

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4245]
## What?

Provider missing error in the:
- Workflow settings/providers tab
- All channels that have missing providers display this error panel

![image](https://github.com/novuhq/novu/assets/2607232/395163da-7528-4b25-875b-888c461acc73)

## Why?

Currently, a user needs to click on the arrow icon only to open the integration store to specify a provider. We want to simplify the UX of the interaction with the error panel

## Definition of done
- The cursor is displaying the hand with the finger hovering over the red panel (see screenshot below)
- The entire panel is clickable

![image](https://github.com/novuhq/novu/assets/2607232/e5aba755-fb7b-4cc9-9d6d-75ecb8338447)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by LetItRock** [comment]
> pls assign me this issue

sure ;)

**Comment by bellatrix01** [comment]
Can I work on this issue?

**Comment by utsavbhattarai007** [comment]
Hi, Can it can assign to me??

**Comment by trdxlucifer** [comment]
Working on it

**Comment by AnshuPathak-88825** [comment]
I'm working on it

**Comment by harshbsharma** [comment]
Hey @LetItRock Can multiple people be assigned this issue ? Please assign if that's the case.

**Comment by trdxlucifer** [comment]
CAN U CHECK MY PR IF THE GUY DIDN'T SOLVE THE ISSUE

**Comment by AnshuPathak-88825** [comment]
I'm working on it I've raise query in discord related to this issue and when my query resolved I'll raise pr asap
