### ISSUE TITLE
[NV-2439] [BUG] 👀 Improve visual BUG in WF editor, "+" freeze while hovering

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4246]
## Reproduction Steps
1. Hover between nodes
2. "+" icon appears and stuck on the screen
3. In some time it disappears

![image](https://github.com/novuhq/novu/assets/2607232/95da0279-f227-4c7b-b08a-5de67ec29eb8)

## Expected Behaviour
- "+" icon display only while hovering a dotted line between the nodes
- Display all "+" buttons background with colour B15 (1E1E26)

**Comment by shoaib-31** [comment]
@LetItRock Hi, I would like to contribute on this. Can you please give a screenshot or specify which plus but has this issue?

**Comment by Akhilbisht798** [comment]
@LetItRock, I would like to work on this issue.

**Comment by LetItRock** [comment]
hey @shoaib-31, thank you for your willingness to help, but please complete the other issue you are assigned to ;)

@Akhilbisht798 assigning this one to you ;)

**Comment by Akhilbisht798** [comment]
Hey thanks @LetItRock, I would love to work on this one.

**Comment by Akhilbisht798** [comment]
@LetItRock, Hey working on it. It will be up by tommorow.

**Comment by Debashis-11101-srijib** [comment]
Hey,  @LetItRock, Please allow me to assign myself to this issue. This will be my first.

**Comment by 07tAnYa** [comment]
If no PR has submitted for this, then I would like to work on this
