### ISSUE TITLE
[NV-2033] 🔧 [Quick start guide][Digest WF] Display hits on hover over card step

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4249]
## What?
Hints in the second step of getting started and on the Digest playground

## Why?
Currently, hints are active when the user hovers over it, but it's not highlighting when the user hovers over a step.

https://github.com/novuhq/novu/assets/2607232/2f386fb7-29db-4acd-b877-37cbce3f9744

https://github.com/novuhq/novu/assets/2607232/dc06e88d-540c-4e6b-82ff-076c95553e4e

## Definition of done
Highlight hints in both cases: 
• When user hover over a hint
• When user hover over a step

**Comment by AnshuPathak-88825** [comment]
assign me this issue I can resolve it easily

**Comment by LetItRock** [comment]
> assign me this issue I can resolve it easily

I've assigned you to another ticket, please complete that one first. Thanks! 🙌

**Comment by foolhardys** [comment]
Kindly assign me the issue , I already set up the project locally.
Thanks!!

**Comment by adityaK87** [comment]
Hey!! I would also like to contribute to this issue. Can u assign me this??

**Comment by Akshat2403** [comment]
Please assign me this issue

**Comment by LetItRock** [comment]
hey @foolhardys 👋 sure, assigning this one to you ;)

@adityaK87 @Akshat2403 thanks for your willingness to help 🙌 you can take a look into other tickets or make some small improvements in the project yourself, for example extracting some code into separate react components ;)

**Comment by LetItRock** [comment]
assigning this ticket to @SarmadKhoja95, as he has provided the working PR: #4292

**Comment by Naushadansarinitw** [comment]
Hey @LetItRock  could u assign this to me..
