### ISSUE TITLE
[NV-2443] 🤌 [WE canvas] Improve navigation across WE canvas for the touchpad

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4250]
## What?
Navigation across WE canvas using a touchpad

## Why?
Modern products with the canvas (Figma. Miro) offer 2 finger drag navigation for touchpads

## How?
Drag canvas if the user using 2 fingers on his touchpad
The expected mouse behavior:

https://github.com/novuhq/novu/assets/2607232/8f89276e-00c8-4673-9112-7d757565c915

**Comment by Shubham1450** [comment]
Please assign this issue to me @LetItRock

**Comment by LetItRock** [comment]
> Please assign this issue to me @LetItRock

thanks, assigning this one to you ;)

**Comment by AnshShah77** [comment]
@LetItRock can u please assign this to me?
