### ISSUE TITLE
[NV-2040] 👁️ [Visual fix] Fix cut shadow

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4251]
## What?
On the Get Started page in the second step, the shadow is cut at the bottom of the Email node.

![image](https://github.com/novuhq/novu/assets/2607232/f6bc9f9e-e517-4a39-8d2b-547b75b6bf67)

## Why?
Visually it doesn't look good :)

## Definition of done
- make the react flow container height or min-height a little bigger
- on the 1280x720 there should be no scrollbar

**Comment by vibh1103** [comment]
Hi @LetItRock can i pick this task ?

**Comment by LetItRock** [comment]
> Hi @LetItRock can i pick this task ?

of course, assigned it to you 🤝

**Comment by jatinder14** [comment]
@LetItRock  only the email shadow should be removed or the digest and trigger button should also be removed ?

**Comment by LetItRock** [comment]
> @LetItRock only the email shadow should be removed or the digest and trigger button should also be removed ?

hey @jatinder14 👋 We didn't want to remove the shadow, but rather increase the container height so it will be better visible. Btw the ticket is already assigned to another person ;) but if you would like to contribute, please take a look into some other not assigned tickets ;)

**Comment by jatinder14** [comment]
hi @LetItRock @vibh1103   sorry for the inconvenience but I started working on this task when no one was assigned to it.
if you guys don't mind  then I have solved this task ,
may I make a Pull Request for it?
![image](https://github.com/novuhq/novu/assets/89455433/6ad7f3b5-90b4-4ca6-8294-6e5c1d019096)

**Comment by vibh1103** [comment]
Ok @jatinder14 you can work on it then 
@LetItRock is there any other task I can pick please assign it to me

**Comment by PankajKumarAgrawal1729** [comment]
Hi @LetItRock,
Can you please assign this for me?

**Comment by LetItRock** [comment]
hey @Rajaa786 @PankajKumarAgrawal1729 👋 
Is anyone available to take a look here?

**Comment by anirudhp26** [comment]
Hey, Is this issue still relevant?

**Comment by LetItRock** [comment]
> Hey, Is this issue still relevant?

yes, it is :) @anirudhp26 do you want to give it a try?

**Comment by ebraj** [comment]
Hi @LetItRock sir, I wanna give it a try can you assign me please 🤗, but before that I wanna confirm myself if I actually understood the issue or not.

### These are the tasks right?
1. To fix the alignment of the `React Flow` tag whatever be the screen sizes.
2. Fixing the shadow being little below on the `Email Node` by following the instruction as per the `Definition of done` on issue

If I am wrong, can you correct me an assign it to me 🤗

**Comment by anirudhp26** [comment]
@LetItRock , Please assign it to @ebraj, he has a better understanding of this issue tbh, I'll look for another one

**Comment by LetItRock** [comment]
> Hi @LetItRock sir, I wanna give it a try can you assign me please 🤗, but before that I wanna confirm myself if I actually understood the issue or not.
> 
> ### These are the tasks right? (As per the issue & the comments on the PRs created for this issue)
> 1. To fix the alignment of the `React Flow` tag whatever be the screen sizes.
> 2. Fixing the shadow being little below on the `Email Node` by following the instruction as per the `Definition of done` on issue
> 
> If I am wrong, can you correct me an assign it to me 🤗

yes, that's correct! :) assigning it to you @ebraj :)

**Comment by ebraj** [comment]
Hi @LetItRock sir,
## Updates :
- I fix the Flow alignment part(center alignment for screens) , but regarding the Shadow cut portion, I didn't notice anything, I tried giving the darker border to see if there is anything like shadow cut, please check this screenshot please.
<img width="671" alt="Screenshot 2023-10-19 at 7 30 47 PM" src="https://github.com/novuhq/novu/assets/61580196/b28f77c7-eeb6-4f84-9d29-829c66c98d1e">

Can you please, tell me where I went wrong @LetItRock sir?

**Comment by LetItRock** [comment]
> Hi @LetItRock sir,
> 
> ## Updates :
> * I fix the Flow alignment part(center alignment for screens) , but regarding the Shadow cut portion, I didn't notice anything, I tried giving the darker border to see if there is anything like shadow cut, please check this screenshot please.
> 
> <img alt="Screenshot 2023-10-19 at 7 30 47 PM" width="671" src="https://user-images.githubusercontent.com/61580196/276636895-b28f77c7-eeb6-4f84-9d29-829c66c98d1e.png">
> Can you please, tell me where I went wrong @LetItRock sir?

can you please create a PR and I'll take a look? 🙏

**Comment by ebraj** [comment]
Sure @LetItRock sir, creating a PR 🤗

**Comment by ebraj** [comment]
Hi @LetItRock sir, did you have a look at my PR?
