### ISSUE TITLE
[NV-2031] 🏗️ [WF editor] Update icon and hint for Fit to screen control

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4252]
## What?
The fit-to-screen function has the wrong icon.

## Why?
The current icon refers to the full-screen button instead. So it's not working as expected. It's confusing and influences the product's credibility.

## Definition of done
- The Fit-to-screen control has an updated icon 
- On hover over an icon UI displays a background under all the buttons (+,–,fit)
- On hover over an icon UI display a hint

**Designs:**
[The zoom-in/zoom-out/fit to screen](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=737%3A6592&mode=design&t=4OHL1ZPbgvy9Y4Tz-1)
[The zoom-in/zoom-out/fit to screen](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=737%3A6647&mode=design&t=3dpKOjcaMqQwJr1k-1)

**Comment by JanetEne** [comment]
@LetItRock , i would like to work on this.

**Comment by TheNatkat** [comment]
hii i love to work on this one can please assign it to me

**Comment by parag477** [comment]
Hey I want to work on this can you please assign this issue to me?

**Comment by 3xp10it3r** [comment]
Hi @LetItRock 
Hope you are doing good,
I have started working on this, Please assign this to me.

**Comment by SPARSH1608** [comment]
@LetItRock Please assign this issue to me under @hacktoberfest'23

**Comment by LetItRock** [comment]
> @LetItRock , i would like to work on this. can you assign this to me?

yes, sure :) thanks! 🙌

**Comment by LetItRock** [comment]
hey friends 👋 @TheNatkat @parag477 @3xp10it3r @SPARSH1608 
thanks for your willingness to help 🤝 we have many more tickets, please take a look at some others that are not assigned or you can also contribute to the project without the ticket, for example, improve typescript types, or extract the code to components, move something to hooks, add tests ;) we would really appreciate your help :)

**Comment by Vishalk91-4** [comment]
@LetItRock , could you please assign this issue to me if it's inactive

**Comment by TheNatkat** [comment]
i also love to work on this one

**Comment by JanetEne** [comment]
@Vishalk91-4 , @TheNatkat  it isn't inactive as I am wrapping up working on it.

**Comment by TheNatkat** [comment]
@JanetEne Ok if you need any help just let me know

**Comment by anmol-matharu-100** [comment]
@LetItRock Please review my pull request & if it is correct please merge it.

**Comment by scopsy** [comment]
@anmol-matharu-100 Currently @JanetEne is working on the issue 🙏
