### ISSUE TITLE
[NV-2396] Link variable in button not shown to user

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4253]
## Reproduction Steps
Variables in buttons are not shown in the variables manager. 
If added to payload works as expected. Does show in the trigger snippet.

1. Create a workflow.
2. Add the Email step to the workflow.
3. Open the editor.
4. Click "Plus" button and choose "Add button".
5. Add any new variable to the button link.

![image](https://github.com/novuhq/novu/assets/2607232/742ba793-a298-48b3-b0a5-3286db8e892f)

## Definition of Done
- The variables from the button link should be visible in the Step Variables

**Comment by rockingrohit9639** [comment]
@LetItRock Can I work on this issue ?

**Comment by Akhilbisht798** [comment]
@LetItRock, can i work on this issue?

**Comment by ainouzgali** [comment]
@rockingrohit9639 assigning you :)

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 assigning you :)

Thanks @ainouzgali

**Comment by lazyMonk1010** [comment]
i want to work on this issue .please assign me this

**Comment by AyushDhimanIITR** [comment]
Can I work on this issue?

**Comment by LetItRock** [comment]
@lazyMonk1010 @AyushDhimanIITR this ticket has a person assigned ;) thanks for your interest to help, but please take a look into other tickets we have ;)

**Comment by LetItRock** [comment]
hey @rockingrohit9639 👋, how it's going? 
any progress with this one? any issues?

**Comment by rockingrohit9639** [comment]
Hey @LetItRock Thanks for asking. 
I am at a point where I know how the variables are being managed and displayed, i.e. `useVariableManager` hook, but kinda stuck with the issue while using this hook in Email component

**Comment by Rajaa786** [comment]
Is this issue solved? Can I take it?
