### ISSUE TITLE
[NV-2350] Should show filter modal in production

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4254]
## Reproduction steps
In production the filters button is disabled. A user can not view the filters applied for him. 

1. Promote the workflow with any steps that have filters applied to the production environment.
2. Change the environment to production.
3. Navigate to the promoted workflow and open the step that has filters applied.
4. The filters button is disabled

![image](https://github.com/novuhq/novu/assets/2607232/64aafbf3-5f51-47e5-b957-66acbb54ff59)

## Definition of Done
- The filters button should be enabled but when clicked all the Filter Modal fields should be disabled

**Comment by rs545837** [comment]
Hey, can you assign me this issue? I am willing to work on this.

**Comment by Akhilbisht798** [comment]
Hey can i work on this issue

**Comment by sjcode99** [comment]
Hey @LetItRock, fixed the add filter button. Please check it and let me know if anything else is required.

**Comment by harshhere905** [comment]
hey please assign me this task. I am willing to work on this

**Comment by LetItRock** [comment]
thanks @sjcode99! 🙌  you did almost everything correctly, but you forgot to do this part: 

> all the Filter Modal fields should be disabled

The only action possible from the modal should be the "Cancel" and "X".

![Screenshot 2023-10-01 at 21 02 14](https://github.com/novuhq/novu/assets/2607232/27161b3a-368e-475f-b3ff-1574f950e7f7)

**Comment by LetItRock** [comment]
hey! 👋 @rs545837 @Akhilbisht798 @harshhere905 
friends thanks a lot for your desire to make the Novu app better, really appreciate that :) we have many more tickets that are not assigned, or you can improve the code yourself for example extracting some code to separate components, adding some missing tests for web or api code :)

**Comment by sjcode99** [comment]
hey @LetItRock, I have updated the changes, please verify it.
