### ISSUE TITLE
[NV-2657] Add icons to the alerts component

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4255]
## What?
Update the Workflow Settings component with the error and warning icons.

![image](https://github.com/novuhq/novu/assets/2607232/1163d5ae-8e36-4b93-9a26-265da563fd76)

## Why?
Improve the UX of this component.

## Definition of done
- Add the warning and error icons according to [the designs](https://www.figma.com/file/72BWZJMFf9aikgI7CPpohp/Workflow-create%2Fedit?type=design&node-id=104%3A6260&mode=design&t=KtgqZOBnwFgnleCb-1)
- show the yellow warning banner only for the SMS or Email channels if there is only one Novu SMS/Email integration

**Comment by rayyyyofsunshine** [comment]
Hey, can you assign me this issue? I am willing to work on this.

**Comment by LetItRock** [comment]
> Hey, can you assign me this issue? I am willing to work on this.

sure, you are assigned! 🤝

**Comment by Mrityunjay1** [comment]
is this done

**Comment by rayyyyofsunshine** [comment]
@Mrityunjay1 I am working on it.

**Comment by Chandan-Singh10** [comment]
I want to work on this issues please assign me this issues as soon as possible.

**Comment by Ashutosh0602** [comment]
Hey @LetItRock I tried to fix the issue and made a PR request you can check and verify it.

**Comment by LetItRock** [comment]
hey @Mrityunjay1 @Chandan-Singh10! 👋 
friends, please take a look into some other tickets we have ;)

**Comment by SahilAli8808** [comment]
@rayy40 is it done?

**Comment by LetItRock** [comment]
@rayy40 we are looking forward to the PR from you ;)

**Comment by sohan01fw** [comment]
@LetItRock  Iam new to this contribution thing how should I know which issue is already done fixing or which one is not cause everyone is working on it and I don't have an idea of what should I pick first from good first issue.

**Comment by LetItRock** [comment]
> @LetItRock Iam new to this contribution thing how should I know which issue is already done fixing or which one is not cause everyone is working on it and I don't have an idea of what should I pick first from good first issue.

hey @sohan01fw! there is only one person assigned to the ticket, you can see that under the `Assignees` ;) the rules are described here: https://github.com/novuhq/novu/issues/4315

I would suggest you also read a few contribution guidelines on the internet and learn how GitHub works ;) for example these two: https://opensource.guide/how-to-contribute/, https://digital.gov/resources/an-introduction-github/

**Comment by rayy40** [comment]
@LetItRock hey, I was having setting it up locally, so I asked in the discord and someone said that they are working on this #4318 and it will be updated soon, so I am unable to set it up till it's fixed. 
Checked the discord now, they fixed it so I'd start working on it.

**Comment by rayy40** [comment]
@LetItRock The workflow setting component already have a MissingIcon, so I was wondering whether I should replace that with error and warning icon depending on the alertType.

![Screenshot 2023-10-04 025707](https://github.com/novuhq/novu/assets/128903323/79a0f5d2-0f6f-41f8-bc2a-54126fe4023f)

And one more thing, should I create two different components each for Warning Icon and Error Icon, or should I just use one component with conditional rendering based on the alertType.

**Comment by LetItRock** [comment]
> @LetItRock The workflow setting component already has a MissingIcon, so I was wondering whether I should replace that with error and warning icon depending on the alertType.

yes, please replace that icon with an error icon

> And one more thing, should I create two different components each for Warning Icon and Error Icon, or should I just use one component with conditional rendering based on the alertType.

good question, I think it's better to use the conditional rendering ;)

---

one additional ask, could you please show that yellow warning banner for the SMS or Email channels if there is only Novu SMS/Email integration? I'll update it in the description too ;) thanks a lot! 🙌

**Comment by rayy40** [comment]
> one additional ask, could you please show that yellow warning banner for the SMS or Email channels if there is only Novu SMS/Email integration? I'll update it in the description too ;) thanks a lot! 🙌

Yeah sure thing, I'll update that.

**Comment by rayy40** [comment]
Hey @LetItRock I submitted a PR with the changes, please take a look at it and let me know if any changes are required.

**Comment by MohdHasan2502** [comment]
Can You Assign me this task?

**Comment by Akash-9794** [comment]
Hey, can you assign me this issue? I am excited to work on this.

**Comment by muzzammilHub** [comment]
hey, can you assign me this issue? I am willing to work on this....
