### ISSUE TITLE
[NV-2825] Templates Store should have Blank Workflow in the List so users do not have to pop out to reselect it

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4258]
## What?
Currently, the blank workflow is not listed in the template store.

https://github.com/novuhq/novu/assets/2607232/712b41e9-32e9-46f1-a610-bab8878e17c4

## Why? (Context)
Because the blank workflow is not listed, a user has to restart the full process to select a blank workflow.

## Definition of Done
- The user should be able to select a blank workflow from the Template Store

**Comment by rohitkbc** [comment]
Hi @LetItRock 👋, Can you assign this task to me?

**Comment by LetItRock** [comment]
> Hi @LetItRock 👋, Can you assign this task to me?

yes, good luck! 🤞

**Comment by Chandan-Singh10** [comment]
Hey, can you assign me this issue? I am willing to work on this.

**Comment by RajAditya01** [comment]
Hello, I'd like to express my interest in taking on this issue. Please consider assigning it to me as I'm eager to work on it

**Comment by rohitkbc** [comment]
Hi @LetItRock, I have setup environment locally but while running project locally after clicking on **Add a workflow,** dropdown list is not appearing, instead it is going towards untitled workflow.

![image](https://github.com/novuhq/novu/assets/100275369/1b057583-76f0-48a9-91c8-ecdf379f3645)

**Comment by LetItRock** [comment]
hey @rohitkbc! 👋 yes, sorry for not mentioning that, we are using the feature flag mechanism, you have to return the temporarily the "true" value from the `useIsTemplateStoreEnabled` hook defined in the `apps/web/src/hooks/useFeatureFlags.ts` file ;) but please do not commit that change ;)

**Comment by LetItRock** [comment]
hey @Chandan-Singh10 @RajAditya01! 👋 
thanks for your willingness to contribute :) please take a look into some other tickets that are not taken, we have many more ;)

**Comment by capGoblin** [comment]
hey hi, i made the necessary changes kindly review.

**Comment by rohitkbc** [comment]
Hi @capGoblin, this task is assigned to me and I am working on it.

**Comment by LetItRock** [comment]
> Hi @capGoblin, this task is assigned to me and I am working on it.

hey @rohitkbc 👋 we are looking forward for the PR from you ;)

**Comment by rohitkbc** [comment]
Hey @LetItRock 👋, I have made necessary changes. Please review it. 😊

**Comment by LetItRock** [comment]
> Hey @LetItRock 👋, I have made necessary changes. Please review it. 😊

thanks @rohitkbc! you rock! 🚀 we will review it soon ;)

**Comment by rohitkbc** [comment]
@LetItRock hey 👋, Its been long time. Can you please review 🙂.
