### ISSUE TITLE
[NV-2792] Add request header to node sdk

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4259]
## What?
Add request header to node sdk.
Example:

```
headers: {
   Authorization: `Bearer ${ApiKey}`,
   "User-Agent": `novu/node@${version}`,
},
```

## Why? (Context)
Having request headers in the SDKs will help us in monitoring which SDK is mostly used by the community and customers. It will help us make the decision to officially maintain that SDK in the future. We will be able to filter out requests on our API by that header.

## Definition of Done
- include the "User-Agent": "novu/node@${version}" header in all requests from node sdk

**Comment by aybeedee** [comment]
@LetItRock could you kindly point me to the commit where this was added? Would just like to see how it was done.
