### ISSUE TITLE
[NV-2841] Workflow Editor - channels icons are white in light theme

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4260]
## Reproduction steps
Light theme - channels icon over provider image are always white.
![image](https://github.com/novuhq/novu/assets/2607232/d5cf51eb-f6b7-42ce-8dfc-fee9e342746d)

Also on hover on the sidebar:
![image](https://github.com/novuhq/novu/assets/2607232/9ad91b7f-a557-4415-a8c2-4bb478dba77b)

Dark theme for reference: 
![image](https://github.com/novuhq/novu/assets/2607232/07f682a4-433c-487a-99c0-becd72bb029a)

## Definition of done
- RIGHT TOOLBAR. When a user hover over the icons for Email and SMS in light theme it should behaves same way as other channels
- NODE. The channel icons (small icon on the right bottom corner near the provider icon) on the step node should be the following:
  - Dark theme: #BEBECC (B80)
  - Light theme: #828299 (B60)

**Comment by sarthak-kumar-shailendra** [comment]
pls assign this to me

**Comment by rituraj12797** [comment]
working!

**Comment by rituraj12797** [comment]
@LetItRock  do you want the icon color over provider image to be black in case of white theme and white in case of black?

**Comment by mokshith-moksh** [comment]
working on it

**Comment by Vidip-Ghosh** [comment]
Please assign this to me

**Comment by Drizer909** [comment]
Can i have this issues, if someone is not working on this

**Comment by chcg823** [comment]
Working on it

**Comment by rjangid9080** [comment]
Hey @LetItRock ,
I am unable to run the repo locally.
Getting Error 
![image](https://github.com/novuhq/novu/assets/43642227/97d9e456-fd9f-4556-ab58-a898fa96b466)

Could you please help me out ?

**Comment by wAsI7** [comment]
Working on it

**Comment by LetItRock** [comment]
hey friends! 👋 @sarthak-kumar-shailendra @rituraj12797 @mokshith-moksh @Vidip-Ghosh @Drizer909 @wAsI7 
it looks like @Aniketsahu28 has already created a PR with a fix :) thanks for your willingness to make the Novu better, please take a look into some other tickets we have there ;) and we will create a few more I promise ;)

**Comment by LetItRock** [comment]
> Hey @LetItRock , I am unable to run the repo locally. Getting Error ![image](https://user-images.githubusercontent.com/43642227/271833758-97d9e456-fd9f-4556-ab58-a898fa96b466.png)
> 
> Could you please help me out ?

Hey, it looks like the amount of memory allocated by the system to run the project is not enough. Please take a look into this article of how to fix this: https://www.makeuseof.com/javascript-heap-out-of-memory-error-fix/

**Comment by rjangid9080** [comment]
Thank You @LetItRock .  It works 
![image](https://github.com/novuhq/novu/assets/43642227/05294406-12c0-4ea8-847c-8bb7cf639d4c)

**Comment by snehpr966** [comment]
Please assign

**Comment by scopsy** [comment]
@sarthak-kumar-shailendra assigned you on the issue, please let me know if won't have the time for it as some people already submitted a PR for it 🙏

**Comment by rjangid9080** [comment]
Hey @LetItRock, Please assign to me

**Comment by LetItRock** [comment]
> Hey @LetItRock, Please assign to me

hey @rjangid9080! we have the assignee for this ticket if that person won't be able to submit the PR, we will take a look at the PRs submitted in the order ;)
