### ISSUE TITLE
[NV-2837] 💔 👀 Update UX/UI of the scroll

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4261]
## What?
Scroll component look and feel

## Why? (Context)
It does not look like a part of the application with borders and creates visual clutter.
It also behaves strangely for some pages. Like in the WF editor, it shouldn't appear at all, because there is not so much content. It also does not allow you to scroll down, feels like Novu is frozen :-0

## Definition of Done
- The scroll displays only when the content of a page(section) is bigger than a container of the content (so in the WE it shouldn't appear when the content is fit into the container
- The scroll uses the same scroll component everywhere
- The component with 8px height max (see the component in Figma)
- The visible scroll body is 4px and it's 40% transparent (see the component in Figma) 
- The component background is 100% transparent
- The scroll should perfectly fit into the container with the scrolling content
- The scroll sick to the right side of the container

**Design:** 
[Workflows / New workflow](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=730%3A5240&mode=design&t=Xs7u6G979yV7n8RA-1)

**Comment by 0xprathamesh** [comment]
Hi @LetItRock 👋, Can you assign this task to me?

**Comment by Nitesh123-Nits** [comment]
I want to work on this

**Comment by roniskywalker** [comment]
Hello [LetItRock](https://github.com/LetItRock), I want to work with this issue. Can you kindly provide a small video about this issue?

**Comment by ainouzgali** [comment]
Thanks everyone!! @0xprathamesh assigning you

**Comment by Sahilll15** [comment]
assign this to me

**Comment by parag477** [comment]
Hey, Can you please assign this issue to me?

**Comment by harshhere905** [comment]
Hey please assign me this issue

**Comment by LetItRock** [comment]
> I want to work on this

hey, assigned this one to you ;)

**Comment by LetItRock** [comment]
hey @roniskywalker @Sahilll15 @parag477 @harshhere905! 👋 
we have many more tickets out here, please take a look at those that are not assigned to anyone :) or find yourself the parts in the code that can be improved :) or you can add some missing tests for api or web apps, we would be really thankful :)

**Comment by narendercoder** [comment]
Hey, can you please assign me this issue ?

**Comment by RSN601KRI** [comment]
Hey Can you assign me this issue?

**Comment by Vriddhi23** [comment]
Hey,I too wanna contibute to this.Can you also assign this to me.

**Comment by LetItRock** [comment]
friends! 👋 we have the assignee in this ticket, but we really appreciate your interest in contributing to the Novu repository :) please take a look at the other tickets we have here ;)

if the assigned person won't be able to publish the PR, we will assign this ticket to someone else in the order from the top ;)

**Comment by Isoumyajit** [comment]
Hi I want to work on this @LetItRock , Please assign this to me 
Thank you !!

**Comment by nick2432** [comment]
i wants to work on this please assign it to me
