### ISSUE TITLE
🐛 Bug Report: Extra space is showing in bottom looks weired

### ISSUE THREAD

**Issue by soubhik-111** [novuhq/novu#4264]
### 📜 Description

In Workflow page
for 1024px X 869px size
empty space in bottom.

### 👟 Reproduction steps

1. Go to workflow edits
2. Scroll 
Note: Even for empty space In bottom it gives user to scroll

### 👍 Expected behavior

Scroll only work when height is more than the screen

### 👎 Actual Behavior with Screenshots

look on the bottom
![image](https://github.com/novuhq/novu/assets/90599826/679dd3be-db1e-4206-949f-a4514122d363)

### Novu version

Novu SaaS

### 📃 Provide any additional context for the Bug.

If you want me to solve this Kindly assign me

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by LetItRock** [comment]
hey @soubhik-111! 👋 Unfortunately, we don't support this screen size. The smallest one we support currently is 1280x720. Closing this issue.
