### ISSUE TITLE
🐛 Bug Report: [Quick start guide] Getting started page : React flow button UI fixing.

### ISSUE THREAD

**Issue by foolhardys** [novuhq/novu#4266]
### 📜 Description

When we visit the getting started page , the React Flow anchor tag link is not clearly visible finds makes user experience unsatisfactory.
![Screenshot 2023-10-01 091452](https://github.com/novuhq/novu/assets/120255116/6302f571-ac15-4582-a6e9-afd81a88eae5)

Color overlaps with the element behind and two links are placed very close to each other which does not look good.

### 👟 Reproduction steps

1. Go to the Getting started page.
2. Look down for the Element having a title 'Channel' and description 'Build desired order of channels' .
3. In the same element there is a pink colored link which looks great .
4. Below that you will see the React Flow link which is not clearly visible.
![Screenshot 2023-10-01 091452](https://github.com/novuhq/novu/assets/120255116/c79648ab-01d4-4750-bedd-6b08f4e5dbc5)

### 👍 Expected behavior

The React Flow link which redirects to [https://reactflow.dev/](url) should have seperate position and should be highlighted either with a lighter shade or a different color. The link should appear distant from background element.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-01 091452](https://github.com/novuhq/novu/assets/120255116/05cabb70-d9bf-4cc0-8725-014326775880)

### Novu version

Novu Saas

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ainouzgali** [comment]
Would you like me to assign you @foolhardys ?

**Comment by TanmayDhobale** [comment]
hey can i work on this issue ?

**Comment by LetItRock** [comment]
@jatinder14 is working on this issue

**Comment by Shiva1406** [comment]
Is this issue resolved or currently assigned to anyone?

**Comment by chankruze** [comment]
@jatinder14 will never fix this simple issue. Retards just contributing for t-shirt. After October no one will be here except real devs.

**Comment by jatinder14** [comment]
@chankruze  please tell me what changes are exactly is required here ?

**Comment by foolhardys** [comment]
> @chankruze please tell me what changes are exactly required here ?

The React Flow button which is appearing behind the message should be seperately visible.

**Comment by govardhanshah456** [comment]
Hey, I would like to work on this issue.

**Comment by unicodeveloper** [comment]
Hello @chankruze, we value respectful communication in this community and believe in encouraging contributions from individuals regardless of their knowledge levels. 

Using derogatory language or engaging in any form of abuse towards contributors is unacceptable. As a result of this behavior, we've decided to remove you from this community.

**Comment by Anonymous961** [comment]
Hey @LetItRock, I think I can fix this issue by repositioning the React Flow beneath the Email block. Furthermore, the font size and color can be changed to a lighter color. React Flow is redirecting to https://reactflow.dev/. Is it fine to move React Flow below the Email block? Please assign me this issue.
