### ISSUE TITLE
🐛 Bug Report: Filter icon is white in light theme

### ISSUE THREAD

**Issue by shaikahmadnawaz** [novuhq/novu#4271]
### 📜 Description

In the light theme of our application, the filter icon is currently displayed in white color, which makes it difficult to distinguish from the background. This affects the visibility and usability of the filter icon, leading to a suboptimal user experience.

### 👟 Reproduction steps

Create a workflow.
Add the Email step to the workflow.

### 👍 Expected behavior

The filter icon's color in the light theme should be consistent with the color scheme and should be set to B60 to ensure better visibility and alignment with the design standards.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-01 130714](https://github.com/novuhq/novu/assets/96189881/3d03ca6e-912a-42b1-bee2-05d6898fcbbf)

Dark theme for reference:

![Screenshot 2023-10-01 130739](https://github.com/novuhq/novu/assets/96189881/7aeda810-f980-4d04-a1d6-bfe8933a1cdd)

### Novu version

0.19.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by haaarsh619** [comment]
Can i Work on this ?

**Comment by ainouzgali** [comment]
@shaikahmadnawaz @haaarsh619 thank you both! 
An [issue](https://github.com/novuhq/novu/issues/3313) an a [pr](https://github.com/novuhq/novu/pull/4151) already exists for this one :) 
Closing this as duplicate

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz @haaarsh619 thank you both! 
> An [issue](https://github.com/novuhq/novu/issues/3313) an a [pr](https://github.com/novuhq/novu/pull/4151) already exists for this one :) 
> Closing this as duplicate 

Sorry I didn't see, I just saw this problem and raised the issue.

**Comment by haaarsh619** [comment]
@ainouzgali can you suggest me any open issue for frontend ,  i checked but most of them are assigned.

**Comment by ainouzgali** [comment]
> @ainouzgali can you suggest me any open issue for frontend , i checked but most of them are assigned.

How about [this one](https://github.com/novuhq/novu/issues/4247#issuecomment-1742039386)? @haaarsh619
