### ISSUE TITLE
🐛 Bug Report: Unable to close the dashboard sidebar on resize of the window 

### ISSUE THREAD

**Issue by ratishjain12** [novuhq/novu#4285]
### 📜 Description

There is no option to close the sidebar for smaller screens and its needed to be fixed
@jainpawan21 please assign me this issue under hacktoberfest '23

### 👟 Reproduction steps

adding a button for smaller screen so they can access the content on resize of the window

### 👍 Expected behavior

There should be a close button or some sort of burger menu to close the sidebar for smaller screens

### 👎 Actual Behavior with Screenshots

Sidebar takes the whole screen and does not close
![image](https://github.com/novuhq/novu/assets/43003421/b7b35a12-bf4e-4fcd-a0cb-9fcd3f8454a1)

### Novu version

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by LetItRock** [comment]
hey @ratishjain12! 👋 thanks for raising this problem, we have a plan to change the sidebar in the near future and our Product Designer is working on improvements in this area. For now, we don't want to introduce this change.
