### ISSUE TITLE
[NV-2932] Fix the pseudo class ":first-child" warning shown in the console

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4293]
## Reproduction Steps
1. Navigate to the Workflows page
2. Open any workflow
3. The warning is shown: `The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type". is printed in the console.`

![image](https://github.com/novuhq/novu/assets/2607232/949bd3d4-61f7-4300-8a31-abfd1e10ee00)

## Expected Behaviour
- fix the issue and there should be no warnings printed

**Comment by Ryan-Maddock-96** [comment]
Can I take a look at this please? :)

**Comment by LetItRock** [comment]
> Can I take a look at this please? :)

thanks! 🤝 the ticket is yours ;)

**Comment by Ryan-Maddock-96** [comment]
Thank you! I'll get on it right away

**Comment by Ryan-Maddock-96** [comment]
Sorry struggling to get the project running locally I know what change needs to be made obviously just can't test it :(

**Comment by UzairNoman** [comment]
@Ryan-Maddock-96, try to follow this documentation:

 https://docs.novu.co/community/run-in-local-machine
 
This will help for sure.

**Comment by LetItRock** [comment]
@Ryan-Maddock-96 please take a look at the documentation listed above, in case you still having some problems please share them here or on our discord channel ;)

**Comment by Ryan-Maddock-96** [comment]
Okay I'll have a look at the documentation now sorry was at work :D

**Comment by Ryan-Maddock-96** [comment]
@LetItRock is there not a quick way of getting it up and running without downloading everything lol seems a long winded process when all I need to see is if changing :first-child to :first-of-type works :D

**Comment by Shivam-043** [comment]
@LetItRock i want to work over this , if it is not resolved still !

**Comment by UzairNoman** [comment]
@LetItRock, I have already submitted the PR some days ago. I'd be really happy if you could review my PR (https://github.com/novuhq/novu/pull/4298). As you mentioned in the PR, that if the original person couldn't finish the task, you will revisit my PR. Thanks in advance :)

**Comment by Ryan-Maddock-96** [comment]
Its a shame I was obviously going to do the same change as you but didn't want to presume it worked without testing it

**Comment by LetItRock** [comment]
hey @UzairNoman 👋 assigned the ticket to you, we will check your PR soon ;) thanks a lot! 🤝
