### ISSUE TITLE
[NV-2933] Fix the kebab-case for css properties warning

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4294]
## Reproduction Steps
1. Navigate to the Get Started page
2. Navigate to the Workflows page
3. The warning: `Using kebab-case for css properties in objects is not supported. Did you mean WebkitTextFillColor?` is shown in the console.

![image](https://github.com/novuhq/novu/assets/2607232/c1432f95-2709-4349-98a9-0e2d3c14c812)

## Expected Behaviour
- provide the fix so the warning is not printed in the console

**Comment by sagnik3788** [comment]
i want to work on this issue please assign me @LetItRock

**Comment by LetItRock** [comment]
> i want to work on this issue please assign me @LetItRock

@sagnik3788 sure! thanks and good luck 🤞

**Comment by gouravkundu7370** [comment]
i want to work on this issue please assign me @LetItRock

**Comment by LetItRock** [comment]
> i want to work on this issue please assign me @LetItRock

hey @gouravkundu7370! 👋 the issue is already assigned, please take a look into others we have :)

**Comment by shakthi2003-ice** [comment]
where is the get started page?

**Comment by Debangan202Ok** [comment]
I will work on it

**Comment by LetItRock** [comment]
hey @shakthi2003-ice @Debangan202Ok! 👋 
Thanks for your willingness to help us improve the Novu :) but we have an assigned person to this ticket and there is already an opened PR.

**Comment by pragyamishra56** [comment]
could you please assign me it would be my first contribution?

**Comment by soumik-saha** [comment]
Hey @LetItRock, I am not getting this error in my console. I think it is a system specific issue. Please tell me what I should do for resolving it?

**Comment by LetItRock** [comment]
> Hey @LetItRock, I am not getting this error in my console. I think it is a system specific issue. Please tell me what I should do for resolving it?

hey @soumik-saha! thanks for your willingness to help, but it's already assigned to @sagnik3788 who has already opened a PR with the fix :) please take a look into some other tickets we have ;)

**Comment by sagnik3788** [comment]
hey @LetItRock can you check my pr

**Comment by LetItRock** [comment]
> hey @LetItRock can you check my pr

sure, we will do that soon ;)

**Comment by shaurya-jain23** [comment]
can you please assign it to me, it would be my first contribution
