### ISSUE TITLE
[NV-2939] 🚀 Feature: Add Mailchain Email Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4336]
### 🔖 Feature description

Use the [mailchain Email SDK](https://docs.mailchain.com/developer/tutorials/send-via-api/#step-2---mailchain-sdk) and the Novu guide to build a [new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider) to add a new provider

### 🎤 Why is this feature needed ?

To allow the community to have more options in sending notifications.

### ✌️ How do you aim to achieve this?

Hactoberfest

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2939](https://linear.app/novu/issue/NV-2939/🚀-feature-add-mailchain-email-provider)</sub>

**Comment by ItIsOHM** [comment]
I'm interested in this, as a beginner looking to contribute to Novu :)

**Comment by jatingodnani** [comment]
Interested

**Comment by Ninad3721** [comment]
Please assign to me

**Comment by shakthi2003-ice** [comment]
Hey cliftonz
J would like to work on this issue. Will u please assign me this issue.

**Comment by pawelborkar** [comment]
Hi @Cliftonz 
IMHO it's better not to assign the issues and take it on first come first serve basis as there are so many people willing to contribute.

**Comment by unicodeveloper** [comment]
@ItIsOHM you have now been assigned to this issue. ⭐

**Comment by ItIsOHM** [comment]
> @ItIsOHM you have now been assigned to this issue. ⭐

Thanks @unicodeveloper, I'll get back to you once I encounter any difficulty :)

**Comment by Cliftonz** [comment]
@pawelborkar How would you recommend doing it then?

**Comment by ItIsOHM** [comment]
Hey there, i've opened a PR regarding this issue, and I'd appreciate it if @Cliftonz @unicodeveloper can take a look at it :)

**Comment by PSKK-Git** [comment]
Has the PR been approved, or can we still work on this?

**Comment by ItIsOHM** [comment]
> can i work on this issue?

Sorry @nick2432 i'm already working on this one. You can look into [these issues](https://github.com/novuhq/novu/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3A%22good+first+issue%22), i believe many of them are not yet being worked upon.

**Comment by Cliftonz** [comment]
@ItIsOHM Any updates?

**Comment by Naushadansarinitw** [comment]
Hey @Cliftonz  can u assign this to me..

**Comment by Naushadansarinitw** [comment]
Hey @Cliftonz  can u review this #4592
