### ISSUE TITLE
[NV-2941] 🚀 Feature: Add SMS.to Chat Provider for Viber

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4338]
### 🔖 Feature description

Use the [sms.to viber documentation](https://developers.sms.to/#6bdae9bd-b677-420f-b0d2-6e7e430c4bef) to create a new chat provider with the help of the [novu new provider guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To add more variety for our community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2941](https://linear.app/novu/issue/NV-2941/🚀-feature-add-smsto-chat-provider-for-viber)</sub>

**Comment by bibaswan7** [comment]
please assign it to me

**Comment by rvikunwar** [comment]
Please assign this to me, I would love to work on this

**Comment by Ninad3721** [comment]
Interested to work please  assign it to me

**Comment by unicodeveloper** [comment]
@rvikunwar this has now been assigned to you. ⭐

**Comment by weedertree** [comment]
hey, could you please assign me this issue

**Comment by rvikunwar** [comment]
@unicodeveloper can you check this PR, and let me know what can I change here
