### ISSUE TITLE
[NV-2942] 🚀 Feature: Add SMS.to sms provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4339]
### 🔖 Feature description

Use the [sms.to sms documentation](https://developers.sms.to/#3a12f9ae-8afa-4d15-a3c5-4895c3a14778) to add a new sms provider by following [Novu's new provider guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To add more providers to the community

### ✌️ How do you aim to achieve this?

Community contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2942](https://linear.app/novu/issue/NV-2942/🚀-feature-add-smsto-sms-provider)</sub>

**Comment by rvikunwar** [comment]
Please assign this to me.

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me under Hacktoberfest.

**Comment by fadkeabhi** [comment]
As this issue is still unassigned, I would like to work on it. I possess prior experience with API's and have already read the documentation of SMS.to. I will be glad to work with it.

**Comment by unicodeveloper** [comment]
@rvikunwar You have now been assigned to this issue.

**Comment by Kanav-Arora** [comment]
@unicodeveloper I have already worked on this issue. Please assign me this issue

**Comment by rvikunwar** [comment]
@Cliftonz why this was closed ?

**Comment by 07tAnYa** [comment]
kindly assign this to me also, I have worked earlier also in this . So I have knowledge regarding this.
