### ISSUE TITLE
[NV-2943] 🚀 Feature: Add Viber Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4340]
### 🔖 Feature description

Use the [Viber api documentation](https://developers.viber.com/docs/api/rest-bot-api/#resource-url-2) to create a new chat provider by following the [Novu guide to adding a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To add more providers for the community

### ✌️ How do you aim to achieve this?

Community Contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2943](https://linear.app/novu/issue/NV-2943/🚀-feature-add-viber-chat-provider)</sub>

**Comment by pedrobruneli** [comment]
Hey! I wanna work on this one

**Comment by jatingodnani** [comment]
Intersted

**Comment by Ninad3721** [comment]
Interested to work please  assign it to me

**Comment by unicodeveloper** [comment]
@pedrobruneli You have now been assigned to this issue.

**Comment by ddevilz** [comment]
i want to work on this feature

**Comment by insanemindsk** [comment]
i wants to work on thi splease assign it to me

**Comment by pedrobruneli** [comment]
Hey @Cliftonz, do you think i put this in the CHAT category? Since it doesn't have channels or webhooks to send messages. It's a one-a-one bot-user messages.
Chat category has to contains the WEBHOOK URL and other fields that this API doesn't works on

**Comment by Cliftonz** [comment]
@davidsoderberg could you give your input on this?

**Comment by davidsoderberg** [comment]
Sure @Cliftonz :)
I am not sure we should not put it in the CHAT category on the other hand I think it requires a bunch of changes to make it possible to use with Vibers api for example. @LetItRock do you have thoughts on this?

**Comment by nick2432** [comment]
i wants to work on this please assign it to me?

**Comment by Cliftonz** [comment]
closing this issue for now as we do not support bots in Novu
