### ISSUE TITLE
🚀 Feature: Elixir client SDK

### ISSUE THREAD

**Issue by zoedsoupe** [novuhq/novu#4341]
### 🔖 Feature description

I would like to implement a client SDK for the [Elixir](https://elixir-lang.org) programming language. It’s most used for resilient, fault tolerant and low-latency responses apps, which includes an awesome web framework called [Phoenix](https://phoenixframework.org) that also includes a SSR/SPA like framework called [Phoenix Live View](https://hexdocs.pm/phoenix_live_view). The last one is also being tested to build native apps ala Flutter with [Phoenix Live View Native](https://github.com/liveview-native).

In conclusion, the Novu API SDK would be a great addition to the Elixir community deps, which always prefer and colaborate with OSS projects.

### 🎤 Why is this feature needed ?

Of course one could implement a interface handcrafted for Novu in Elixir! There are tons of HTTP clients, parsers and so on to do so, but it would be cool to have an official SDK for Elixir that already leverages and abstract some features into a well documented and standardized features implemented with good practices and leveraging the Erlang/OTP benefits!

### ✌️ How do you aim to achieve this?

I’ll take your API documentation but also will take a look into another SDKs to check a possible pattern. Specially the ruby one as Elixir syntax is very similar.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Cliftonz** [comment]
@zoedsoupe Hey, we already have a Elixir sdk started here.
https://github.com/novuhq/novu-elixir 

Feel free to talk to me on discord or @unicodeveloper  if you have more questions.

**Comment by Cliftonz** [comment]
I am going to close this issue as it already exists.

**Comment by zoedsoupe** [comment]
> @zoedsoupe Hey, we already have a Elixir sdk started here. https://github.com/novuhq/novu-elixir
> 
> Feel free to talk to me on discord or @unicodeveloper if you have more questions.

Oh, thanks to show it to me! I really tried to search but didn’t find this repo! Good to know that already exists! I’ll try to contribute to it then
