### ISSUE TITLE
[NV-2946] 🚀 Feature: Add WhatsApp Chat Provider 

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4344]
### 🔖 Feature description

Use the [WhatsApp docs](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#text-messages) and the archived [nodjs sdk](https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/blob/main/src/api/messages.ts#L205) to create a Chat provider for whatsapp while following [Novu's add a new provider Guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider) 

### 🎤 Why is this feature needed ?

To add more providers to the community

### ✌️ How do you aim to achieve this?

Community Contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2946](https://linear.app/novu/issue/NV-2946/🚀-feature-add-whatsapp-chat-provider)</sub>

**Comment by michaldziuba03** [comment]
I would like to work on this provider

**Comment by jatingodnani** [comment]
Interested

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me under Hacktoberfest.

**Comment by unicodeveloper** [comment]
There's an open issue here #1019 about Whatsapp. And it currently has a PR #4128
