### ISSUE TITLE
[NV-2946]🐛 Bug Report: Workflow Editor-Filter Icon is not visible in the light mode

### ISSUE THREAD

**Issue by rjangid9080** [novuhq/novu#4348]
### 📜 Description

Filter icon (in the Add Filter Button) is not visible in the light mode.
![image](https://github.com/novuhq/novu/assets/43642227/471c3dab-bc7c-4a77-adbe-e143531b0277)

### 👟 Reproduction steps

1. Go To the Workflows Editor.
2. Click on the + button
![image](https://github.com/novuhq/novu/assets/43642227/df560fff-f2bc-4392-9224-2a446e4c0e36)
3. Select the Channels from the dropdown
![image](https://github.com/novuhq/novu/assets/43642227/c0598cdb-d610-4dbb-a653-624fc457b017)
4. Click on the channel card to provide connection 
![image](https://github.com/novuhq/novu/assets/43642227/e9c28b0a-a4b5-4c3d-a1fd-66c3c2dc6f2d)
5. Then you will see the add filter button 
![image](https://github.com/novuhq/novu/assets/43642227/560ca231-9f9d-4b1c-88b1-4bea68115582)

### 👍 Expected behavior

Filter Icon should the same color as the "Add Filter" text in the light mode for better visibility.  

### 👎 Actual Behavior with Screenshots

Light Mode:
![image](https://github.com/novuhq/novu/assets/43642227/6f829987-11db-419a-abcc-6078f46ffcbe)

Dark Mode:
![image](https://github.com/novuhq/novu/assets/43642227/476321b2-f390-42a1-815b-fb8f5e369485)

### Novu version

0.19.0

### npm version

8.19.4

### node version

16.20.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vishalkhoje** [comment]
Please assign this issue to me

**Comment by rjangid9080** [comment]
Hey @LetItRock , Please assign to me

**Comment by michaldziuba03** [comment]
Duplicate of issue: #3313
There is also already PR for it: #4151

**Comment by ankitkr190** [comment]
@LetItRock  I believe I can make a valuable contribution to resolving this issue and, by extension, to the overall progress of the Novu project.I kindly request that you assign this issue to me, and I am committed to working diligently to address it in a timely manner.

**Comment by rjangid9080** [comment]
duplicate issue #3313

**Comment by vishalkhoje** [comment]
Fix PR: https://github.com/novuhq/novu/pull/4356
