### ISSUE TITLE
🐛 Bug Report: Link in Readme.md redirecting to undesired page

### ISSUE THREAD

**Issue by bibaswan7** [novuhq/novu#4354]
### 📜 Description

In the README.md file located in the root directory, at the bottom of the page, there is a link "_**Run Novu Locally**_" under **Links** section. Clicking on the link actually takes us to "Introduction" page instead of "Run Novu in local machine" page.

### 👟 Reproduction steps

1. Go to README.md
2. Click on **_Run Novu Locally_** near the bottom of page

### 👍 Expected behavior

It should be redirecting user to this [page](https://docs.novu.co/community/run-in-local-machine)

### 👎 Actual Behavior with Screenshots

It redirects the user to [Introduction page](https://docs.novu.co/getting-started/introduction)

### Novu version

0.19.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by bibaswan7** [comment]
Please assign it to me. I will solve this issue

**Comment by lazyMonk1010** [comment]
hey @bibaswan7  i would like to work on this issue , please assign me this .
