### ISSUE TITLE
[NV-2949] 🚀 Feature: Add Line Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4365]
### 🔖 Feature description

Use the [Line](https://developers.line.biz/en/reference/messaging-api/#send-push-message) send message documentation and the [Novu's add a provider guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider) to create it.

This integration may require some back and forth as it functions like an sms provider but is more along the lines of a chat provider.

### 🎤 Why is this feature needed ?

To support more integrations for the community

### ✌️ How do you aim to achieve this?

Community Contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2949](https://linear.app/novu/issue/NV-2949/🚀-feature-add-line-chat-provider)</sub>

**Comment by PalaniappanC** [comment]
Hi @Cliftonz I would like to work on this issue as a part of Hacktoberfest. Can you assign the hacktoberfest label and assign it to me
