### ISSUE TITLE
[NV-2950] 🚀 Feature: Add D7Networks SMS Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4366]
### 🔖 Feature description

Use the [d7 sms docs](https://d7networks.com/docs/SMS/Send-SMS/) to create a sms provider while following the [Novu's guide to building a provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To give the community more providers

### ✌️ How do you aim to achieve this?

community contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2950](https://linear.app/novu/issue/NV-2950/🚀-feature-add-d7networks-sms-provider)</sub>

**Comment by nilanjan2002** [comment]
I want to work on this

**Comment by Cliftonz** [comment]
@nilanjan2002 I have already assigned you to one, once you finish that one I would be happy to put you on this one if no one else has claimed it.

**Comment by skoriop** [comment]
Hi, I'd like to work on this if it's still up :)

**Comment by davidsoderberg** [comment]
@skoriop I have now assigned you :)
