### ISSUE TITLE
[NV-2952] 🚀 Feature: Add D7 network Slack Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4368]
### 🔖 Feature description

Use the [d7 Viber docs](https://d7networks.com/docs/Slack/Send-Message/) to create a Chat provider while following the [Novu's guide to building a provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

Note: This provider should not be a blank D7 provider, this provider should be a unique chat provider in the fact it only talks to Slack through D7 Network.

### 🎤 Why is this feature needed ?

to have more providers for the community

### ✌️ How do you aim to achieve this?

community contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2952](https://linear.app/novu/issue/NV-2952/🚀-feature-add-d7network-slack-chat-provider)</sub>

**Comment by nilanjan2002** [comment]
I would like to work on this.. please assignit to me

**Comment by bharathkumar01-k** [comment]
hi @Cliftonz please assign the task to me if possible

**Comment by Cliftonz** [comment]
@nilanjan2002 Reassigning due to inactivity.

**Comment by Mattiullah134** [comment]
@Cliftonz thanks for assigning

**Comment by REVERB283** [comment]
@Cliftonz 
I wanted to know if no one is working on this issue, can this be assigned it to me?
Also I found that we are using Slack as a chat provider already so why is there any need to add it again or am I missing something?

**Comment by Cliftonz** [comment]
@REVERB283 Yeas you can take this over

**Comment by REVERB283** [comment]
@Cliftonz thanks for assigning.

Can you please answer my above question regarding Slack already present as a chat provider; so that I can proceed with my approach?!

**Comment by Cliftonz** [comment]
> @Cliftonz I wanted to know if no one is working on this issue, can this be assigned it to me? Also I found that we are using Slack as a chat provider already so why is there any need to add it again or am I missing something?

This is not a need to do this. By supporting D7 slack provider we allow users of Novu to choice the way and the provider on which to send messages. 

This gives our user the most amount of flexibility to sent the messages they need no matter the provider.

**Comment by HarshJainofficial** [comment]
@Cliftonz  could you assign me this one
