### ISSUE TITLE
[NV-2953] 🚀 Feature: Add D7 Network Whatsapp Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4369]
### 🔖 Feature description

Use the [d7 Viber docs](https://d7networks.com/docs/Whatsapp/Send-Whatsapp-Message/) to create a Chat provider while following the [Novu's guide to building a provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

Note: This provider should not be a blank D7 provider, this provider should be a unique chat provider in the fact it only talks to Whatsapp through D7 Network.

### 🎤 Why is this feature needed ?

give more provider to the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2953](https://linear.app/novu/issue/NV-2953/🚀-feature-add-d7-network-whatsapp-chat-provider)</sub>

**Comment by Cliftonz** [comment]
done

**Comment by Yash-sudo-web** [comment]
hey @harshit-senpai, are you still working on this?

**Comment by harshit-senpai** [comment]
> hey @harshit-senpai, are you still working on this?
> 

Yeah

**Comment by Cliftonz** [comment]
@harshit-senpai  would you be able to push a draft pr so we can see your work?

**Comment by harshit-senpai** [comment]
yes, sure 

> @harshit-senpai would you be able to push a draft pr so we can see your work?

**Comment by Mattiullah134** [comment]
@harshit-senpai are you still working on this????

**Comment by harshit-senpai** [comment]
> @harshit-senpai are you still working on this????

Yeah I was facing some issue that I am getting resolved on discord.

**Comment by Mattiullah134** [comment]
@harshit-senpai okay

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by Cliftonz** [comment]
@harshit-senpai any progress on this?

**Comment by harshit-senpai** [comment]
> @harshit-senpai any progress on this?

Yeah I have made the basic structure of Chat Provider using Documentation and using other Providers as an Example Such as Discord, now i am wrapping my head around D7 to Setup Whatsapp, If there are any Resources for D7 Network that would really helpful

**Comment by Cliftonz** [comment]
> > @harshit-senpai any progress on this?
> 
> Yeah I have made the basic structure of Chat Provider using Documentation and using other Providers as an Example Such as Discord, now i am wrapping my head around D7 to Setup Whatsapp, If there are any Resources for D7 Network that would really helpful

Could you push a draft pr? we would be better able to assist with the code.
Also you can look at https://d7networks.com/docs/Viber/Send-Viber-Message/ to assist you.

**Comment by harshit-senpai** [comment]
@Cliftonz I have drafted an initial PR where i have set the Provider without D7, I am still learning about D7
