### ISSUE TITLE
[NV-2954] 🚀 Feature: Add Ryver Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4370]
### 🔖 Feature description

Use the [Ryver api docs](https://api.ryver.com/ryvrest_api_examples.html#create-chat-message) to create a chat provider while following the [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

Should be able to select if the provider is for workrooms or forums in the integration store.

### 🎤 Why is this feature needed ?

give more providers to the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2954](https://linear.app/novu/issue/NV-2954/🚀-feature-add-ryver-chat-provider)</sub>

**Comment by vishalkhoje** [comment]
I would like to work on this. Can you please assign to me

**Comment by Ayush-Vish** [comment]
@Cliftonz, I would like to work on this feature.  Can you assign it to me  ?

**Comment by davidsoderberg** [comment]
@Ayush-Vish I will assign you :) As @vishalkhoje is already assigned to another issue.

**Comment by vishalkhoje** [comment]
Hi @davidsoderberg 

I would like to bring to your attention that there was an issue previously assigned to me, which I have successfully completed and submitted a pull request for two days ago. Kindly consider reassigning this particular issue to me.

**Comment by Ayush-Vish** [comment]
> @Ayush-Vish I will assign you :) As @vishalkhoje is already assigned to another issue.

Thankyou for assigning me this issue.

**Comment by manoj8861** [comment]
Hi, I would like to work on this please assign me this issue. Thanks

**Comment by davidsoderberg** [comment]
Hi @vishalkhoje I have assigned you now :)

**Comment by vishalkhoje** [comment]
Thank you for assigning me

**Comment by davidsoderberg** [comment]
Ping @unicodeveloper or @scopsy

**Comment by vishalkhoje** [comment]
Hi @unicodeveloper ,
I would like to confirm whether this feature will not be taken into consideration for the label "Hacktoberfest."

Thank you

**Comment by Cliftonz** [comment]
@vishalkhoje everything in our repository will count for hacktoberfest, the issues with hacktoberfest are just to help foster engagement.

**Comment by vishalkhoje** [comment]
Thanks for update

**Comment by vishalkhoje** [comment]
Hi @Cliftonz 
Can you please review PR https://github.com/novuhq/novu/pull/4470
