### ISSUE TITLE
[NV-2955] 🚀 Feature: Add Signal SMS Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4372]
### 🔖 Feature description

Use the documentation for the [Unoffical Signal Rest api](https://bbernhard.github.io/signal-cli-rest-api/#/) from [Github](https://github.com/bbernhard/signal-cli-rest-api) to create an SMS provider for Signal while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider).

This is not a beginner friendly issue as it require some setup to run and test.

Once accepted, the PR's MUST have a gif or pictures of the full process working.

DO NOT INCLUDE PERSONAL INFO!

### 🎤 Why is this feature needed ?

add more providers for the community

### ✌️ How do you aim to achieve this?

community contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2955](https://linear.app/novu/issue/NV-2955/🚀-feature-add-signal-sms-provider)</sub>

**Comment by Kanav-Arora** [comment]
Please assign me this issue.

**Comment by AnuMessi10** [comment]
Hi, let me know if you can assign this issue to me, thanks.

**Comment by davidsoderberg** [comment]
@AnuMessi10 will assign you because @Kanav-Arora already is assigned to an issu :)

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by Cliftonz** [comment]
@nick2432 yes

**Comment by utkarsh2310** [comment]
can I work on this issue @Cliftonz

**Comment by utkarsh2310** [comment]
@Cliftonz To add this provider, we need a container setup. Do I need to do that as well or just have to write code for provider assuming all the container setup will be there?

**Comment by Cliftonz** [comment]
@utkarsh2310 You would create a docker compose file and add it to the package under a docker folder. Within the compose file you will have the container definition to set up the signal container. This way we can test in the future if need be.
