### ISSUE TITLE
[NV-2956] 🚀 Feature: Add Novu Rust Repository to the Readme for Hacktoberfest

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4373]
### 🔖 Feature description

Add [Rust SDK](https://github.com/novuhq/novu-rust/issues) to the Novu readme just like we recently did for [Elixer](https://github.com/novuhq/novu/pull/4360)

### 🎤 Why is this feature needed ?

Ensure the community knows that we have other sdks to support

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2956](https://linear.app/novu/issue/NV-2956/🚀-feature-add-novu-rust-repository-to-the-readme-for-hacktoberfest)</sub>

**Comment by michaldziuba03** [comment]
@Cliftonz I think Rust SDK needs some attention as Novu changed since November 2022 and most important - it should be easily downloadable from [crates.io](https://crates.io/) registry. Right now it's not possible.

Someone should push that SDK to crates.io registry.

**Comment by Cliftonz** [comment]
@michaldziuba03 Your absolutely correct! and since it is community managed other than the deployment credentials We want it to have visibility where the community can help us get it to today's standards.

**Comment by deanurag** [comment]
I would like to work on this issue. Please Assign me this.

**Comment by fadkeabhi** [comment]
I would like to work on this issue. Can you assign it to me.

**Comment by deanurag** [comment]
I have submitted a PR for this issue, please review it.

**Comment by dhruvgupta0503** [comment]
I would like to work on this issue can you please assign it to me
