### ISSUE TITLE
🐛 Bug Report:  In the press kit file  space img not responsive

### ISSUE THREAD

**Issue by gautammanak1** [novuhq/novu#4374]
### 📜 Description

In the Press Kit file, there is an issue with non-responsive images. When viewing the Press Kit on various screen sizes and devices, the images do not adapt or scale appropriately, causing them to appear distorted or cut off.

### 👟 Reproduction steps

Open the Press Kit file on a computer or mobile device.
Resize the window or view the Press Kit on different devices with varying screen sizes.

### 👍 Expected behavior

The images in the Press Kit should automatically adjust their size and proportions to fit the available screen space, maintaining their aspect ratio and ensuring they are fully visible and legible.

### 👎 Actual Behavior with Screenshots

The images in the Press Kit do not respond to changes in screen size or device, leading to issues like:

Images being cropped or partially hidden.
Images appearing stretched or distorted.
Difficulty in viewing the complete content of the images.
<img width="1680" alt="Screenshot 2023-10-04 at 3 18 33 AM" src="https://github.com/novuhq/novu/assets/106014185/eedcd572-d6d9-495b-bc8c-bca5459251b4">
<img width="541" alt="Screenshot 2023-10-04 at 3 19 06 AM" src="https://github.com/novuhq/novu/assets/106014185/44d37cc2-2aea-457d-923a-2b310658aaa5">
<img width="376" alt="Screenshot 2023-10-04 at 3 19 44 AM" src="https://github.com/novuhq/novu/assets/106014185/fdfa56d5-f7d4-4e76-99e0-6b1a8af1ecb4">

### Novu version

na

### 📃 Provide any additional context for the Bug.

Additional Information:

It is important to ensure that all images included in the Press Kit are responsive to provide a consistent and user-friendly experience for all viewers, regardless of their device or screen size.
Consider using responsive image techniques, such as using CSS properties like max-width: 100% and height: auto, or utilizing responsive image libraries like srcset and sizes attributes for <img> tags.
Test the Press Kit on various devices and screen sizes to verify that the images adapt correctly.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by theavitw** [comment]
Hey @GAUTAMMANAK1 
provide some direct link for this issue

**Comment by GAUTAMMANAK1** [comment]
https://handbook.novu.co/logos-assets

**Comment by theavitw** [comment]
Ok I understood this issue
Basically setting up the image size as per screen
ok you can assign to me.

**Comment by techmannih** [comment]
Hello @davidsoderberg ,
I want to work on this issue please assign ms
