### ISSUE TITLE
[NV-2957] 🚀 Feature: Add MagicBell In-app Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4375]
### 🔖 Feature description

Use the [Magicbell docs](https://www.magicbell.com/docs/rest-api/reference#notifications-create) to create an In-app Provider for MagicBell while following [Novu's Guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

give the community more options

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2957](https://linear.app/novu/issue/NV-2957/🚀-feature-add-magicbell-in-app-provider)</sub>

**Comment by Kanav-Arora** [comment]
Please assign me this

**Comment by unicodeveloper** [comment]
I'm going to go ahead and close this now. We currently don't have a flow that supports adding another in-app provider. @Kanav-Arora please can you take a look at the other issues. Thanks.
