### ISSUE TITLE
[NV-2959] 🚀 Feature: Add Webex Chat Provider 

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4379]
### 🔖 Feature description

Use the [Webex Docs](https://developer.webex.com/docs/api/v1/messages/create-a-message) to create a Chat Provider while following the [Novu's guide to new providers](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider).

Note: This provider may not have free access to attempts for integration.

### 🎤 Why is this feature needed ?

provide the community with more providers

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2959](https://linear.app/novu/issue/NV-2959/🚀-feature-add-webex-chat-provider)</sub>

**Comment by Yllet77** [comment]
ckages:%0A%20%20%23%20all%20packages%20in%20subdirs%20of%20packages/%20and%20components/%0A%20%20-%20'providers/*'%0A%20%20-%20'packages/*'%0A%20%20-%20'enterprise/packages/*'%0A%20%20-%20'apps/*'%0A%20%20-%20'libs/*'%0A%20%20%23%20exclude%20packages%20that%20are%20inside%20test%20directories%0A%20%20-%20'!**/test/**'

**Comment by TheOjasSingh** [comment]
Hi @Cliftonz I want to work on this issue can you assign me this issue and help me setup novu on my local machine

**Comment by davidsoderberg** [comment]
I have assignd you now on this issue @TheOjasSingh

**Comment by TheOjasSingh** [comment]
Can you assist me with setting up and running Novu on my local machine, @davidsoderberg?

**Comment by Cliftonz** [comment]
@TheOjasSingh Unfortunately, due to the strain of hacktoberfest, we are not. We recommend going to the discord and talking with the community members there to help assist you.

**Comment by Technmad** [comment]
@Cliftonz Can you assign me this task

**Comment by TheOjasSingh** [comment]
@Technmad I am already working on this issue  but if you want we both can work on it.

**Comment by parveshsaini** [comment]
Hey @TheOjasSingh . Are you still working on this?

**Comment by TheOjasSingh** [comment]
yes

**Comment by Cliftonz** [comment]
@TheOjasSingh Do you have a draft PR we can look at?

**Comment by TheOjasSingh** [comment]
Sure you can check the PR#4484

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by TheOjasSingh** [comment]
I have already raised a PR#4484 for this issue.

**Comment by Cliftonz** [comment]
@TheOjasSingh the PR that you mentioned is closed, do you have another PR that you are trying to get merged in for this?

**Comment by TheOjasSingh** [comment]
Hi @Cliftonz, I'm having trouble committing to the repository. Could you help me?
![Screenshot 2023-10-18 051249](https://github.com/novuhq/novu/assets/55990400/4fd0ea0a-e230-4c9c-a3e8-2c37bd2725a7)
