### ISSUE TITLE
[NV-2960] 🚀 Feature: Add Zulip Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4380]
### 🔖 Feature description

Use the [Zulip docs](https://zulip.com/api/send-message) and the [zulip js package](https://github.com/zulip/zulip-js) to create a chat provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

give more providers to the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2960](https://linear.app/novu/issue/NV-2960/🚀-feature-add-zulip-chat-provider)</sub>

**Comment by michaldziuba03** [comment]
I would like to implement this

**Comment by Yash-sudo-web** [comment]
@michaldziuba03 are you working on this issue?, if not @Cliftonz can i work on this?

**Comment by Ank61** [comment]
Hey @michaldziuba03 , @Cliftonz! I would like to contribute to this issue.
Thanks

**Comment by michaldziuba03** [comment]
@Yash-sudo-web @Ank61 

relax, I work on this

**Comment by Yash-sudo-web** [comment]
@Cliftonz if this issue is not being worked upon, i already have a PR that adds this feature, let me know if we can reopen that PR

**Comment by Cliftonz** [comment]
@michaldziuba03 have you completed this PR?
I know that I assigned other items to you.

If you have not then I will reassign and reopen @Yash-sudo-web  PR for this.

**Comment by michaldziuba03** [comment]
@Cliftonz 
today or tomorrow you can expect PR for this issue

**Comment by Cliftonz** [comment]
@michaldziuba03 Sounds good, I do not like to push but our policy is a draft PR/ PR needs have progress within three days or we will need to reassign.
