### ISSUE TITLE
[NV-2961] 🚀 Feature: Add Google Chat Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4381]
### 🔖 Feature description

Use the [Google Chat docs](https://developers.google.com/chat/api/guides/v1/messages/create) and the [SDK](https://github.com/google/google-api-javascript-client) to create a new chat provider while following [Novu's guide to a new provider](https://github.com/novuhq/novu/issues/new?assignees=&labels=feature&projects=&template=feature_request.yml&title=%F0%9F%9A%80+Feature%3A+)

### 🎤 Why is this feature needed ?

provide more options to the community

### ✌️ How do you aim to achieve this?

community Contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2961](https://linear.app/novu/issue/NV-2961/🚀-feature-add-google-chat-chat-provider)</sub>

**Comment by Sushmitha-93** [comment]
Hi @Cliftonz, I would like to work on this, could you please assign this to me?

**Comment by AnuMessi10** [comment]
Hi @Cliftonz , I have gone through your codebase and also have prior experience in integrating providers in Node + TypeScript for production apps, let me know if you can assign this to me. Cheers!

**Comment by manish7017** [comment]
Hi @Cliftonz, Could you please assign this issue to me? I would like to work on it.

**Comment by davidsoderberg** [comment]
@Sushmitha-93 you are now assigned to this issue :)

**Comment by Sushmitha-93** [comment]
Hi @Cliftonz, @davidsoderberg, I submitted a PR for the issue. Could you please review and let me know if any change is needed?

**Comment by Sushmitha-93** [comment]
Hi @Cliftonz , I closed the old PR #4453 and opened a new one #4381 because I made some changes while playing around and wanted to start with clean forked repo.
Could you please review when you get a chance?

**Comment by kuncevic** [comment]
It looks like a [generic webhook](https://github.com/novuhq/novu/blob/233aa8ef10cc808dd9fb517772d11876b2b65bbe/packages/providers/src/lib/chat/chat-webhook/chat-webhook.provider.ts) provider can serve the purpose tho haven't tried it yet.
