### ISSUE TITLE
[NV-2962] 🚀 Feature: Add Guilded Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4382]
### 🔖 Feature description

Use the [Guilded docs](https://www.guilded.gg/docs/api/chat/ChatMessage) to create a new Chat provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

provide the community with more providers

### ✌️ How do you aim to achieve this?

community contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2962](https://linear.app/novu/issue/NV-2962/🚀-feature-add-guilded-chat-provider)</sub>

**Comment by Kanav-Arora** [comment]
Please assign me this issue

**Comment by Abizrh** [comment]
can u please assigned this issue to me

**Comment by davidsoderberg** [comment]
@Kanav-Arora you are now assigned to this issue.

**Comment by Kanav-Arora** [comment]
I am working on it. Will submit soon

**Comment by Kanav-Arora** [comment]
Hi @Cliftonz 
I have created a PR
Kindly update me with any changes if required

**Comment by Kanav-Arora** [comment]
Hi @Cliftonz 
The conflict were rectified
I have created a new PR #4494 
You can close old PR #4416

**Comment by Kanav-Arora** [comment]
Looping @davidsoderberg 
The conflict were rectified
I have created a new PR https://github.com/novuhq/novu/pull/4494
You can close old PR https://github.com/novuhq/novu/pull/4416

Kindly review new PR
