### ISSUE TITLE
[NV-2963] 🚀 Feature: Add Pushed Push Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4383]
### 🔖 Feature description

Use the [Pushed Docs](https://about.pushed.co/docs/api#api-method-push) to create a new Push provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

give more providers to the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2963](https://linear.app/novu/issue/NV-2963/🚀-feature-add-pushed-push-provider)</sub>

**Comment by vishalkhoje** [comment]
I would like to work on this. please assign it to me

**Comment by Vishalk91-4** [comment]
@Cliftonz, could you please assign this issue to me

**Comment by shohan2001** [comment]
I you assign this me to?

**Comment by davidsoderberg** [comment]
@Vishalk91-4 I see you are already assigned to an issue so will assign @Vishalk91-4

**Comment by davidsoderberg** [comment]
@Vishalk91-4 you are now assigned

**Comment by vishalkhoje** [comment]
Hi @davidsoderberg,

I would like to bring to your attention that there was an issue previously assigned to me, which I have successfully completed and submitted a pull request for two days ago. Kindly consider reassigning this particular issue to me.

**Comment by davidsoderberg** [comment]
Yes sorry @vishalkhoje next issue I see you asked to be assigned first for I will assign you to 😄

**Comment by CodeGovindz** [comment]
could you please assign this issue to me

**Comment by Cliftonz** [comment]
@Vishalk91-4 Do you have a draft PR/ PR for this issue?

**Comment by Vishalk91-4** [comment]
@Cliftonz, I'm working on it, I'll submit the PR by tomorrow

**Comment by CodeGovindz** [comment]
@Cliftonz 
could you please assign this issue to me

**Comment by vishalkhoje** [comment]
@Cliftonz 
I kindly request that you assign this ticket to me. I have already raised the PR for the Ryver Provider and have been assigned another ticket related to it. Could you please reassign this particular ticket to me?

**Comment by Vishalk91-4** [comment]
@Cliftonz, it is taking a little time, but I'm working, if you want i can share the code too, I'm trying to complete it early

**Comment by Vishalk91-4** [comment]
@Cliftonz, I'm adding a draft PR now, will be adding the complete one also

**Comment by Cliftonz** [comment]
@Vishalk91-4 Please link this issue when you raise the pr

**Comment by HarshJainofficial** [comment]
@Vishalk91-4 could you please assign me this issue so that I can try my best

**Comment by Cliftonz** [comment]
@dhruvgupta0503 are you still interested?

**Comment by dhruvgupta0503** [comment]
yes I m interested

**Comment by jainpawan21** [comment]
@ayo6706 Assigning this issue to you.

**Comment by ayo6706** [comment]
> @ayo6706 Assigning this issue to you.

Thanks
