### ISSUE TITLE
[NV-2964] 🚀 Feature: Add X (formerly Twitter) Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4384]
### 🔖 Feature description

Use the [X dev docs](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets) to create a new chat provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider).

Note: you may run into issues due to this api requiring oauth 2.0

### 🎤 Why is this feature needed ?

provide more provider for the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2964](https://linear.app/novu/issue/NV-2964/🚀-feature-add-x-formerly-twitter-chat-provider)</sub>

**Comment by cu8code** [comment]
please assign me this one
