### ISSUE TITLE
[NV-2967] 🚀 Feature: Add Rocket.chat Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4387]
### 🔖 Feature description

Use the [Rocket.chat docs](https://developer.rocket.chat/reference/api/rest-api/endpoints#chat) to create a new chat provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

more options for the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2967](https://linear.app/novu/issue/NV-2967/🚀-feature-add-rocketchat-chat-provider)</sub>

**Comment by Deveesh-Shetty** [comment]
I would like to give it a try! Can I get it assigned, I will discuss about it in discord

**Comment by Sayan-dev** [comment]
Can I give it a try?

**Comment by nick2432** [comment]
can i work on this?

**Comment by manish7017** [comment]
Could you please assign this issue to me? I would like to work on it

**Comment by manish7017** [comment]
Could you please assign this issue to me? I would like to work on it.

**Comment by Cliftonz** [comment]
@Deveesh-Shetty Are you still working on this?

**Comment by Deveesh-Shetty** [comment]
Yes, sorry for the delay I got held up with some college work 😅

**Comment by kunalvirk** [comment]
Hi,
I can work on this if Deveesh Shetty is occupied with something else.
thanks,

**Comment by Cliftonz** [comment]
https://docs.rocket.chat/use-rocket.chat/workspace-administration/integrations#incoming-webhook-script

**Comment by Mattiullah134** [comment]
@jainpawan21 @Cliftonz  hi if no one work on this issue can i you please assign it to me

**Comment by Cliftonz** [comment]
@jainpawan21 Is there a PR for this or are we expecting the community to finish this?

**Comment by divyaannsh** [comment]
assign to me

**Comment by Mattiullah134** [comment]
> @Mattiullah134 In today's office hours, we used rocket chat for demonstration purposes. https://www.youtube.com/watch?v=Y_2fBwFpOps

okay

**Comment by Cliftonz** [comment]
@Deveesh-Shetty Are you still working on this?

**Comment by jainpawan21** [comment]
> @jainpawan21 Is there a PR for this or are we expecting the community to finish this?

I will raise PR for this

**Comment by Deveesh-Shetty** [comment]
> @Deveesh-Shetty Are you still working on this?

Yeah, I was working but then @jainpawan21 mentioned that they used it for office hours...
It was great, though I learned quite a few things. I will try to contribute to some other issues. Also, Thanks for the help on Discord @Cliftonz  ✨

**Comment by Cliftonz** [comment]
@jainpawan21 Would you have the ability to raise the PR soon?

**Comment by jainpawan21** [comment]
Removing my assignment. Happy to help if someone from community adds this.

**Comment by varsubham** [comment]
@jainpawan21 if no one is working on this, can you please assign it to me ?

**Comment by varsubham** [comment]
@Cliftonz @jainpawan21 if no one is working, can you assign me ?

**Comment by KaoutharAsma** [comment]
Hi is this issue still open , can I take it ?

**Comment by michaldziuba03** [comment]
@KaoutharAsma there is already open approved PR.

**Comment by DenisBessa** [comment]
Is it possible to configure the notification to a Self-Hosted instance of Rocket.Chat? Because I can't find any field to informe the server's URL.

**Comment by scopsy** [comment]
@DenisBessa not at the moment, feel free to submit an issue 🙏
