### ISSUE TITLE
[NV-2968] 🚀 Feature: Add Clicksend SMS Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4388]
### 🔖 Feature description

Use the [Clicksend Docs](https://developers.clicksend.com/docs/rest/v3/?javascript--nodejs#ClickSend-v3-API-SMS) to create a new SMS Provider while following [Novu's guide to new providers](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

add providers for the community

### ✌️ How do you aim to achieve this?

community contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2968](https://linear.app/novu/issue/NV-2968/🚀-feature-add-clicksend-sms-provider)</sub>

**Comment by rvikunwar** [comment]
Please assign this to me

**Comment by Prajwal0225** [comment]
I would like to work on this issue. Can you please assign this issue to me?

**Comment by unicodeveloper** [comment]
@rvikunwar You have been assigned different issues. Please can you work on that and submit a PR before you are assigned another issue?

**Comment by unicodeveloper** [comment]
@Prajwal0225 Assigning this to you.

**Comment by unicodeveloper** [comment]
Assigned @Prajwal0225 ⭐

**Comment by 07tAnYa** [comment]
kindly assign this to me, or let me know where I can work. Because of exams, I can not spend time on these, and the time I get for this I don't have the issue only to solve, as most of them are being assigned to someone else already.

**Comment by manish7017** [comment]
Could you please assign this issue to me? I would like to work on it.

**Comment by Sa2003hil** [comment]
I hope this message finds you well. I am writing to express my interest in taking ownership of issue #4388, which is related to the "**Add Clicksend SMS Provider**" feature.

I have been following the progress of this feature closely and believe I have the necessary skills and experience to contribute effectively to its resolution. In the past, I have [mention any relevant contributions or experience related to the project or feature].

I kindly request that you assign issue #4388 to me so that I can start working on it. 
Thank you for considering my request, and I look forward to the opportunity to contribute to the project.

**Comment by parveshsaini** [comment]
Hey Team! If the current assignee is unable to proceed with this issue, can you please assign it to me? I'd love to take this forward.

**Comment by 07tAnYa** [comment]
No , kindly refer some other issues. I am working on this. Due to exams I am not able to give required time on this. But will definitely fix this very soon.

**Comment by Cliftonz** [comment]
@Prajwal0225 do you have a draft pr for this issue?
If we do not see a PR by tomorrow we will re-assign the issue.

**Comment by Prajwal0225** [comment]
I'm not very familiar with TypeScript, and I've tried to understand it by reading the guide, but I'm still having trouble, so could you please reassign this task to someone else? I'll find another task that I can work on.

**Comment by parveshsaini** [comment]
I'd love to work upon this :)

**Comment by parveshsaini** [comment]
Hey @Cliftonz 👋
Any updates on reassigning this issue??
It'll be much appreciated if you could consider me.

**Comment by Cliftonz** [comment]
@parveshsaini reassigning to you

**Comment by parveshsaini** [comment]
Thanks! I'll be submitting the PR soon

**Comment by parveshsaini** [comment]
Quick update:
I'm almost done with the PR. Most probably you'll see it today :)

**Comment by parveshsaini** [comment]
Hey @Cliftonz ! I've raised the PR. Please review it.
