### ISSUE TITLE
🐛 Bug Report: Navbar is not responsive for small device 

### ISSUE THREAD

**Issue by techmannih** [novuhq/novu#4398]
### 📜 Description

Hello @unicodeveloper ,
I found an issue in your website in which navbar is not responsive for small device or at a fixed pixels **1024px to 1066px**  "GET STARTED" Button is out of div for a  given pixels. So I want to work on this issue ...please assign me 
![2023-10-04_16-39](https://github.com/novuhq/novu/assets/125847751/cc78a3e6-75a3-4ca2-b831-269e7c22b708)
 

### 👟 Reproduction steps

1. go to the Navbar file
2. change the pixels from 1022px to 1068px for a navbar menu
3. do same for toggle menu

### 👍 Expected behavior

This UI also for the 1024px to 1066px
![2023-10-04_16-57](https://github.com/novuhq/novu/assets/125847751/2ee0f85b-6ac1-47fd-9a6a-4e59c94a6c74)

### 👎 Actual Behavior with Screenshots

![2023-10-04_16-39](https://github.com/novuhq/novu/assets/125847751/7aea28a2-e2aa-49cf-9b05-3b7fd35a1a15)

### Novu version

0.19.0

### npm version

10.1.0

### node version

20v.6.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ShatilKhan** [comment]
I'd like to work on this

**Comment by davidsoderberg** [comment]
Hi @ShatilKhan I see you are already assigned to an issue, please complete that one first.

**Comment by CiaoRaviRaj** [comment]
@ShatilKhan  can i work on this issue?

**Comment by davidsoderberg** [comment]
@CiaoRaviRaj I have assigned you to this now.

**Comment by techmannih** [comment]
Hello @davidsoderberg ,
I want to work on this issue ....I create this issue .please assign me this isue.

**Comment by davidsoderberg** [comment]
Sorry I missed that, if not @CiaoRaviRaj have started I can assign you :)

**Comment by CiaoRaviRaj** [comment]
Sorry to say @davidsoderberg , i have started this task since you assign me sir.

**Comment by CiaoRaviRaj** [comment]
@davidsoderberg Tomorrow evening i will make push request.

**Comment by davidsoderberg** [comment]
No worries, looking forward to your PR :)

**Comment by CiaoRaviRaj** [comment]
Thank you so much @davidsoderberg

**Comment by CiaoRaviRaj** [comment]
@davidsoderberg can you help me to find the code files related to this website `https://novu.co/`? I have tried and searched a lot to find these code files in this repo. but it has code files related to this website `https://web.novu.co/auth/login`.

**Comment by davidsoderberg** [comment]
Ah yes the code is located in https://github.com/novuhq/website

**Comment by CiaoRaviRaj** [comment]
Thank you @davidsoderberg

**Comment by CiaoRaviRaj** [comment]
Hello @davidsoderberg ,
I am facing issue on setup this project https://github.com/novuhq/website.

I am facing this issue while run `npm run start` :
`info [sanity] Fetching remote GraphQL schema

 ERROR #gatsby-source-sanity_drafts.10001  UNKNOWN

GraphQL API not deployed - see https://github.com/sanity-io/gatsby-source-sanity#graphql-api
for more info`

i have setup these value in .env

`GATSBY_DEFAULT_SITE_URL=http://localhost:8000
GATSBY_DEV_SSR=false

WP_GRAPHQL_URL=localWordPressGraphQL-url
WP_HTACCESS_USERNAME=myWordPressUsername
WP_HTACCESS_PASSWORD=password
WP_HARD_CACHE_MEDIA=true
WP_HARD_CACHE_DATA=true
WP_NODE_UPDATE_INTERVAL=10000

GATSBY_STRAPI_API_URL=
GATSBY_CONTRIBUTORS_API_URL=

GITHUB_TOKEN=

GATSBY_SANITY_PROJECT_ID=myTestProducId
GATSBY_SANITY_DATASET=production

GATSBY_NOVU_API_KEY=
GATSBY_NOTIFICATIONS_API_URL=

GITHUB_README_TOKEN=
`

is this project need Deployed GraphQL APi ?

is these any why to bypass this setup?

**Comment by techmannih** [comment]
Hello @davidsoderberg ,
I created this issue...can you please assign me

**Comment by davidsoderberg** [comment]
@techmannih why did you close this one?

**Comment by techmannih** [comment]
@davidsoderberg 
I create this issue and also another 
I m working  on this issue right now 
Assign me #4458

**Comment by davidsoderberg** [comment]
Yes but @CiaoRaviRaj  is working on this one now... @CiaoRaviRaj are you still working on this one? 
@techmannih I think there is other issues you could work on :)

**Comment by CiaoRaviRaj** [comment]
@davidsoderberg as we discussed, i am facing a issue on setting up project regarding graphql api. I have fixed and test it one live website by using chrome dev tool. But not able to test on local. If i fixed my issue then i will push my change. If this issue is not argent then i want to fix my issue then push it and it argent rhen you can assign to @techmannih . No issues ☺️

**Comment by davidsoderberg** [comment]
Okay I the fix in discord did not work for you in that case please raise it again in discord.
