### ISSUE TITLE
🚀 Feature: display count of stars of repo dynamically

### ISSUE THREAD

**Issue by noobtuber20103152** [novuhq/novu#4412]
### 🔖 Feature description

Create a logic to display stars of github repo dynamically.

![image](https://github.com/novuhq/novu/assets/81584747/ea8aa643-a26a-47b6-abad-655e3c40055a)

Here counting stars are not dynamically

### 🎤 Why is this feature needed ?

Latest count of stars of repo.

### ✌️ How do you aim to achieve this?

We can use github api to fetch no of stars of a repo dynamically. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
*my opinion*: I don't think it's good idea - I think Novu does it on purpose to avoid hitting rate limit for GitHub's API :)

It's not big deal to show most recent number of stars on GitHub.

**Comment by SAGARSINGH-1** [comment]
We can achieve it using an API call.

**Comment by manmohanhunjan** [comment]
assign this to me

**Comment by scopsy** [comment]
This is intentional as @michaldziuba03 mentioned, we can't have it realtime, and we are ok of it to be cached and delayed a bit :) Closing for now.
