### ISSUE TITLE
[NV-2972] 🚀 Feature: Iframe Embed In App Widget - option to hide settings icon

### ISSUE THREAD

**Issue by ankit-sisodia** [novuhq/novu#4422]
### 🔖 Feature description

Ability to remove settings icon from header and logo in footer in Iframe embed UI widget,
React version has showUserPreferences prop.
Iframe version need to have same.

<img width="656" alt="Screenshot 2023-10-05 at 1 06 10 PM" src="https://github.com/novuhq/novu/assets/8232246/f56bc37f-22fb-4c4c-bb4b-8a21ff5537bf">

<img width="420" alt="Screenshot 2023-10-05 at 4 28 26 PM" src="https://github.com/novuhq/novu/assets/8232246/ab4ca67f-3d38-4156-9127-7b5a890e53e5">

### 🎤 Why is this feature needed ?

Need to hide settings icon for end users.

### ✌️ How do you aim to achieve this?

Enable Iframe to handle **showUserPreferences** when passed to novu init.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2972](https://linear.app/novu/issue/NV-2972/🚀-feature-iframe-embed-in-app-widget-option-to-hide-settings-icon)</sub>

**Comment by nirjann** [comment]
Let me try to implement the feature.. please can someone assign this to me?

**Comment by nirjann** [comment]
Skimming through the code.. tweaking and getting errors... will let
you know if i need any help.

**Comment by nirjann** [comment]
> @nirjann after working on this issue, please update the iframe docs in our docs repo as well 

sure.. will do that

**Comment by Vishalk91-4** [comment]
@jainpawan21 , could you please assign this issue to me if it's inactive

**Comment by jainpawan21** [comment]
Sure @nirjann 

@Vishalk91-4 
Are you still interested to work on this?

**Comment by ruhani2** [comment]
@jainpawan21 I would like to work on this, Can you please assign this to me?

**Comment by jainpawan21** [comment]
Sure @ruhani2 
Assigning to you!
