### ISSUE TITLE
🐛 Bug Report:  LogRocket is being loaded twice in your application, leading to a session quota exceeded error.

### ISSUE THREAD

**Issue by Nadiya-Shaikh** [novuhq/novu#4424]
### 📜 Description

LogRocket is being loaded twice in your application, leading to a session quota exceeded error.

### 👟 Reproduction steps

1. Navigate to the Get Started page
2. Navigate to the Workflows page
3. The bug: `build.umd.js:3103 LogRocket has already been loaded, loading a second instance is not supported. This is often caused by loading LogRocket as a package in your application and as a script tag.`

### 👍 Expected behavior

provide the fix so the warning is not printed in the console

### 👎 Actual Behavior with Screenshots

![Screenshot (111)](https://github.com/novuhq/novu/assets/142484981/987b6d57-e46d-42f1-ac00-d002cfb86f4e)   is shown in the console.

### Novu version

novu Saas

### 📃 Provide any additional context for the Bug.

The exact problem is that LogRocket is being loaded and initialized twice in your application, which is not supported, and the session quota for LogRocket has been exceeded.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by marcelorafaelfeil** [comment]
Hi,

I would like to work on this...

Thanks

**Comment by davidsoderberg** [comment]
@Nadiya-Shaikh I assigned you because you answered that you are willing to submit a PR.

**Comment by Nadiya-Shaikh** [comment]
Please check the PR & tell what further changes will I have to do?
