### ISSUE TITLE
[NV-2989] Upgrade cypress to latest version

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#4426]
### What?
Upgrade cypress for the following project:
- apps/web
- apps/widget

### Definition of Done
- Test suite is passing on those projects

<sub>[NV-2989](https://linear.app/novu/issue/NV-2989/upgrade-cypress-to-latest-version)</sub>

**Comment by scopsy** [comment]
@FroostyCodes assigned you 👌

**Comment by madtitan02** [comment]
@scopsy i would like to work on this issue, also can you eloborate more about the issue

**Comment by SauravKesari** [comment]
@scopsy Could you assign me this ticket? One more thing we just have to update the cypress version to latest, Right?

**Comment by AnshShah77** [comment]
@scopsy can u please assign this to me?

**Comment by AliYar-Khan** [comment]
Is this fixed ?

**Comment by utkarshtenguriya** [comment]
@scopsy can you assign this issue to me

**Comment by Isoumyajit** [comment]
Hey can you assign this issue to me !

**Comment by 07tAnYa** [comment]
if the current assignee is not able to make any required changes , then you can give this to me .

**Comment by FroostyCodes** [comment]
@scopsy Please assign the issue to someone else.
Following the cypress upgrade guide, there was no breaking change required so updating just the package version would be enough.
However I wanted to run the commands and verify everything would work locally as expected, however my laptop is not able to run the project properly. I tried to get some support over discord as well but no luck.

With everyone else wanting to pick up the issue and work on it, please do assign it to someone else 🙏

**Comment by AnshShah77** [comment]
@scopsy can u please assign it to me? i wont disappoint you.

**Comment by scopsy** [comment]
Sure @FroostyCodes thank you so much for giving it a look!

**Comment by 07tAnYa** [comment]
kindly, assign this to me also. The one who submits the PR first, will be fortunate enough

**Comment by AnshShah77** [comment]
I have Started Working.

**Comment by AnshShah77** [comment]
@scopsy please consider my PR as i was assigned with this issue.

**Comment by AnshShah77** [comment]
@scopsy can u please review this and merge?
 https://github.com/novuhq/novu/pull/4483

**Comment by ayushshukla7777** [comment]
Hey, I am working on this issue.
