### ISSUE TITLE
🚀 Feature: Support Dingtalks

### ISSUE THREAD

**Issue by Justice-23** [novuhq/novu#4431]
### 🔖 Feature description

Delivery notifications to Dingtalk

### 🎤 Why is this feature needed ?

Ding talk is a very popular DevOps tool in East Asia

### ✌️ How do you aim to achieve this?

As endpoint

### 🔄️ Additional Information

To enable an alert contact to receive alert notifications in a DingTalk.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by BiswaViraj** [comment]
Hello @Justice-23, Thank you for creating this issue.
I will close this one as we have a duplicate issue #4430 to tackle.
