### ISSUE TITLE
🚀 Feature: Activity feeds are failing to save

### ISSUE THREAD

**Issue by billyurs** [novuhq/novu#4435]
### 🔖 Feature description

I am manually triggered the event and even with API too, 

it is not showing the activity feed, But I am able to see the transaction id

And it is in self hosted Novu

### 🎤 Why is this feature needed ?

I need to get the inapp feeds for it

### ✌️ How do you aim to achieve this?

Through web novu of my self hosted I have tried it

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by shakthi2003-ice** [comment]
Can you please me this issue?

**Comment by davidsoderberg** [comment]
@shakthi2003-ice you are now assignde

**Comment by shakthi2003-ice** [comment]
how do we achieve this issue?

**Comment by mahimairaja** [comment]
Are you new here @shakthi2003-ice ?

**Comment by shakthi2003-ice** [comment]
> Are you new here @shakthi2003-ice ?

Yes i am new here

**Comment by billyurs** [comment]
Can we connect ? on google meet , I can explain the issue

**Comment by billyurs** [comment]
I have trigger the worflow from web and with the help of APIs too.

I am sucess fully getting the transaction id

{
    "data": {
        "acknowledged": true,
        "status": "processed",
        "transactionId": "5a140c2d-be32-4111-b689-f33bd1c6cf0d"
    }
}

But later If I check in activity feed it is showing as empty both dev and prod

**Comment by shakthi2003-ice** [comment]
> Can we connect ? on google meet , I can explain the issue

Sure through google meet. I am free right now

**Comment by billyurs** [comment]
https://meet.google.com/vvs-ynno-dqu

**Comment by billyurs** [comment]
It is not the issue with front end

**Comment by billyurs** [comment]
Till transaction id it is working fine, but the transactions are failing to save in db

**Comment by billyurs** [comment]
@davidsoderberg  Please help me to resolve this issue?

**Comment by davidsoderberg** [comment]
Please update with next and see if it helps. Please ask further questions in discord :)

**Comment by billyurs** [comment]
I've set up my own Novu hosting and attempted to create an in-app notification. However, I'm retrieving the transaction ID but the feeds aren't appearing in Novu's system's feeds tab."

**Comment by billyurs** [comment]
Can we connect @davidsoderberg

**Comment by davidsoderberg** [comment]
As I said please use Discord to ask questions :) I or my colleagues will be there to help you out.

**Comment by lucaspereirasouzat** [comment]
same problem here, I'm using the comunity edition
