### ISSUE TITLE
🚀 Feature: Support Grafana Oncall

### ISSUE THREAD

**Issue by Igorgro** [novuhq/novu#4438]
### 🔖 Feature description

Add support for [Grafana Oncall](https://grafana.com/oss/oncall/) notification provider

### 🎤 Why is this feature needed ?

Grafana Oncall is an actively developing incident management system

### ✌️ How do you aim to achieve this?

Community contributions 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Siddharth9890** [comment]
can i work on this please @unicodeveloper ?

**Comment by davidsoderberg** [comment]
I assigned you now @Siddharth9890 :)

**Comment by Cliftonz** [comment]
@Igorgro Can you explain your use-case for this?

**Comment by Cliftonz** [comment]
#4759
