### ISSUE TITLE
[NV-3009] 🚀 Feature: Typescript SDK - Add Exponential Retry Mechanism with Idempotency Headers

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4452]
In order to enhance the resilience and reliability of our SDK, we would like to introduce an Exponential Retry mechanism for retrying failed requests. Additionally, to ensure the idempotent processing of requests, it's vital to incorporate support for providing an Idempotency Key as per the draft specified in the [HTTP Idempotency Key Header Field](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/).

The key requirements for this implementation include:

1. **Exponential Retry Mechanism**:
   * The SDK should retry failed requests following an exponential backoff strategy to minimize the contention and impact on the systems involved.
   * The SDK should ensure that the retry mechanism is configurable (e.g., max retries, initial delay, maximum delay).
2. **Idempotency Key Provisioning**:
   * The SDK should allow for either automatic or manual provisioning of an Idempotency Key for each request.
   * The Idempotency Key should conform to either CUID, ULID, or UUID formats as specified in the draft.
   * The Idempotency Key should be included in the HTTP Header as `Idempotency-Key` and following the standards outlined in the draft.
3. **Configuration and Documentation**:
   * The SDK should provide configuration options for enabling/disabling the Exponential Retry mechanism and Idempotency Key provisioning.
   * Comprehensive documentation should be provided explaining the configuration options, operational behavior, and the benefits of using the Exponential Retry mechanism along with Idempotency Keys.

Acceptance Criteria:

* [ ] Implementation of the Exponential Retry mechanism with configurable parameters.
* [ ] Provisioning of Idempotency Keys, either automatically or manually, conforming to specified formats (CUID, ULID, or UUID).
* [ ] Adequate unit and integration testing to ensure the robustness and reliability of the implemented features.
* [ ] Comprehensive documentation on the usage and configuration of the Exponential Retry mechanism and Idempotency Key provisioning.
* [ ] Adherence to the specifications outlined in the [HTTP Idempotency Key Header Field draft](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/).

Please refer to the draft for further details on the HTTP Idempotency Key Header Field and ensure adherence to the specified standards while implementing this feature in the SDK.

**Update**: You can reference the go-lang library to keep the method signature and configuration the same.
[https://github.com/novuhq/go-novu/pull/62](https://github.com/novuhq/go-novu/pull/62)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3009](https://linear.app/novu/issue/NV-3009/🚀-feature-typescript-sdk-add-exponential-retry-mechanism-with)</sub>

**Comment by michaldziuba03** [comment]
1. There is popular extension for underlying http library used by SDK: [axios-retry](https://www.npmjs.com/package/axios-retry)
2. I'm little bit confused - does server reads `Idempotency-Key` header and implement any idempotency mechanism?

**Comment by Cliftonz** [comment]
@michaldziuba03 Thanks for adding that library.

As to number 2, not yet but we are looking to add it soon. 

I wanted to get this out during hacktoberfest if anyone was brave enough.

**Comment by michaldziuba03** [comment]
@Cliftonz ok, I think I'm brave enough :)

**Comment by Cliftonz** [comment]
@michaldziuba03 I would be happy to assign this to you, feel free to reach out if you have any questions or need to talk through anything.

**Comment by Marrwan** [comment]
Is this assigned already

**Comment by Cliftonz** [comment]
> Is this assigned already

Yes

**Comment by mahendraHegde** [comment]
@michaldziuba03 i have added the same for golan sdk, may be we should keep the signature same
https://github.com/novuhq/docs/pull/187
https://github.com/novuhq/go-novu/pull/62
@Cliftonz

**Comment by Cliftonz** [comment]
I agree, you made a very good implementation out of these requirements.

> @michaldziuba03 i have added the same for golang sdk, may be we should keep the signature same [novuhq/docs#187](https://github.com/novuhq/docs/pull/187) [novuhq/go-novu#62](https://github.com/novuhq/go-novu/pull/62) @Cliftonz
