### ISSUE TITLE
🐛 Bug Report: Sendchamp missing square logo variant

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/novu#4455]
### 📜 Description

**Sendchamp** provider is missing square logo variant.

### 👟 Reproduction steps

1. Go to Integrations Store (make sure `IS_MULTI_PROVIDER_CONFIGURATION_ENABLED` flag is `true`)
2. Click Add a provider button
3. In Select a provider window you can see that logo for **Sendchamp** provider is missing

### 👍 Expected behavior

We should see 32x32 svg **Sendchamp** logo

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/43048524/c4821560-b1c3-4444-b68d-90e75e084e3e)

### Novu version

every since sendchamp provider was implemented I guess

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Min2who** [comment]
can you please assign me this issue

**Comment by Suraj-kumar00** [comment]
Hi @michaldziuba03, How are you doing?
My name is Suraj, Can I know like you have raised this issue for this repository and are you also a maintainer or kind of something are handling this project? Can I fix this bug?

**Comment by michaldziuba03** [comment]
@Min2who 
@Suraj-kumar00 

I made this issue just for my PR. This is actually already solved by me, you can see reference to PR - waits for review.

This is my personal practice to create pair: issue + PR. Why? Because I want to make it searchable among issues. I also prefer to explain problem inside issue. In PR I describe only changes.
