### ISSUE TITLE
[NV-3015] Idempotent API Requests Implementation

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4469]
Enhance API reliability by introducing Idempotency headers, especially for `POST` and possibly `PATCH` HTTP methods. This will ensure requests are processed only once, even in scenarios of resubmissions due to perceived failures. 

#### **Benefits**
- Improves API reliability and trustworthiness.
- Acts as a precursor to broader system resilience.
- Reduces potential conflicts, data inconsistencies, and duplicate messages.

### 🚀 **Implementation Steps**

1. **Leveraging Redis for Caching**
   - Store idempotency keys, prefixed with organization Id and Environment Id.
   - Set TTL for keys to 24 hours.
   
2. **Interceptor Logic**
   - Check if request is of type POST or PATCH.
   - Inspect for Idempotency Header.
   - Interact with Redis cache.
   - Handle potential Redis errors.
   - On return, cache responce.
   
3. **Documentation and Developer Guidelines Update**
   - Update API documentation regarding idempotency headers.
   - Provide guidelines on key generation mechanisms.

4. **Testing**

   1. **Idempotency Key Absence**:
      - Submit a POST or PATCH request without an Idempotency header.
      - Ensure the request is processed normally without any idempotency guarantees.

   2. **Idempotency Key Presence & Cache Miss**:
      - Submit a POST request with a unique Idempotency header that hasn't been used.
      - Ensure the request is processed, and the response is cached with the correct TTL in Redis.

   3. **Idempotency Key Presence & Cache Hit**:
      - Resubmit the POST request from the previous scenario using the same Idempotency header.
      - Confirm the Interceptor fetches the response directly from Redis, bypassing any further processing or database interactions.

   4. **Redis Error Handling**:
      - Simulate a Redis outage or error.
      - Submit a POST request with an Idempotency header.
      - Ensure the request is processed normally without any idempotency guarantees, and appropriate error handling is in place.

   5. **Non-POST Request Processing**:
      - Submit a non-POST request (e.g., GET) with an Idempotency header.
      - Confirm the Interceptor does not enforce idempotency and the request is processed as usual.

   6. **Testing Specific Endpoints**:
      - For all mentioned PATCH endpoints, test the behavior with and without the Idempotency header.
      - Ensure the system behaves correctly, either processing normally or fetching from cache as expected.

<sub>[NV-3015](https://linear.app/novu/issue/NV-3015/idempotent-api-requests-implementation)</sub>

**Comment by mahendraHegde** [comment]
@Cliftonz  plz assign this to me
