### ISSUE TITLE
Describe and enforce patterns in our providers better (with TypeScript)

### ISSUE THREAD

**Issue by artfuldev** [novuhq/novu#45]
- **I'm submitting a ...**
 [ ] bug report
 [x] feature request
 [x] question about the decisions made in the repository
 [ ] question about how to use this project

- **Summary**
While using the project, I noticed that there are a few places where the typing information could be better. Enforcing some patterns is also possible by providing an abstract class to derive from, for example. Just wanted to bring these ideas up for discussion.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I want to talk about a few things, so let me add numbers as a way to refer to the ideas:

I'm providing code context here so people can contribute to this issue/discussion without having to go through source.
```typescript
export interface IProvider {
  id: string;
  channelType: ChannelTypeEnum;
}

export interface IEmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  from?: string;
  text?: string;
}

export interface ISmsOptions {
  to: string;
  content: string;
  from?: string;
}

export interface IEmailProvider extends IProvider {
  channelType: ChannelTypeEnum.EMAIL;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  sendMessage(options: IEmailOptions): Promise<any>;
}

export interface ISmsProvider extends IProvider {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  sendMessage(options: ISmsOptions): Promise<any>;

  channelType: ChannelTypeEnum.SMS;
}
```
1. Our `Provider`s are always tied to the `ChannelTypeEnum`. We could write the definition as:
```typescript
export interface IProvider<C extends ChannelTypeEnum> {
  channelType: C;
}
export interface IEmailProvider extends IProvider<ChannelTypeEnum.EMAIL> {
  sendMessage(options: IEmailOptions): Promise<any>;
}
```

2. In general, none of the properties of the provider and even options are supposed to be writable. so we could add [`readonly`](https://basarat.gitbook.io/typescript/type-system/readonly#readonly) attributes to all properties so that it's clear and consumers of the API (at least in TypeScript) can't make mistakes like changing the channel type of a provider or the to address of an `IEmailOptions`.
```typescript
export interface IProvider {
  readonly channelType: ChannelTypeEnum;
}
export interface ISmsOptions {
  readonly to: string;
  readonly content: string;
  readonly from?: string;
}
```
Another way to use records like `ISmsOptions` is to [control consumers](https://basarat.gitbook.io/typescript/type-system/readonly#readonly-1) from not being able to edit them:
```typescript
export interface ISmsProvider extends IProvider {
  sendMessage(options: Readonly<ISmsOptions>): Promise<any>;
}
```

3. Provide a standard interface for configurations. As an example, in the PR #44 we have an `EmailJsConfig` interface:
```typescript
export interface EmailJsConfig {
  from: string;
  host: string;
  port: number;
  secure: boolean;
  user: string;
  password: string;
}
```
We could provide an interface for API-based and SMTP-based email providers so that the shape of the configuration is consistent.
```typescript
export interface EmailProviderConfig {
}
export interface SmtpBasedEmailProviderConfig extends EmailProviderConfig {
  from: string;
  host: string;
  port: number;
  secure: boolean;
  user: string;
  password: string;
}
export interface EmailJsConfig extends SmtpBasedEmailProviderConfig {
}
export interface NodeMailerConfig extends SmtpBasedEmailProviderConfig {
}
export interface ApiBasedEmailProviderConfig extends EmailProviderConfig {
  api_key: string;
}
export interface SendgridConfig extends ApiBasedEmailProviderConfig {
}
```
4. Provide easy ways to enforce patterns with `IProvider` implementations.

For example, if we want to enforce usage of EmailProviderConfig, we can expose an abstract class for the same:
```typescript
public abstract class ConfigBasedEmailProvider<E extends EmailProviderConfig> {
  constructor(protected config: E) {
  }
}
```
That would enable writing new config based providers easily. For example, the EmailJsProvider could've been written as:
```typescript
public class EmailJsProvider extends ConfigBasedEmailProvider<EmailJsConfig> implements IEmailProvider {
  ..
}
```

5. ~I would discourage returning `Promise<any>` - but I'd like to first understand why it's used. I think in most instances of current usage it can safely be `Promise<void>` if we don't care about the result but want to signal an `async` operation. Returning an any is pretty useless as the result always needs to be casted. Converting a result this way can be done by something like `promise().then(() => {})`. Combining this with idea 4 would mean we don't even need individual providers to write this code. They can return `Promise<T>` and we can always ensure the final return is a `Promise<void>`.~ Already taken care of in #41 

6. Some interfaces which are closed, could just be [type aliases](https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases). Example:
```typescript
type SmsOptions = {
  to: string;
  content: string;
  from?: string;
}
```
because we don't expect the options to be extended, whereas `EmailProviderConfig` in idea 3 is expected to be extended.

These ideas are composable. For example, combining the ideas 1, 3, and 4, we can write the EmailJsProvider as
```typescript
public abstract class ConfigBasedEmailProvider<E extends EmailProviderConfig> implements IProvider<ChannelTypeEnum.EMAIL> {
  channelType: ChannelTypeEnum.EMail;
  constructor(protected config: E) {
 }
  abstract sendMessage(options: IEmailOptions): Promise<any>;
}
public class EmailJsProvider extends ConfigBasedEmailProvider<EmailJsConfig> {
  ..
}
```
Notice the lack of `readonly` since we didn't use idea 2.

These were my initial thoughts. Please let me know what you think.

**Comment by artfuldev** [comment]
I would like to understand what we think of this so we can decide if it can be picked up.

**Comment by artfuldev** [comment]
@scopsy @ComBarnea What are the issues we want to create out of this? We can probably just edit the issue to be simpler and convert this into a tracker issue of sorts. What do you think?

**Comment by artfuldev** [comment]
Also @scopsy point 3 is meant to be extensible, we're not getting locked into anything. We kind of have an empty `EmailProviderConfig` interface 😅

**Comment by scopsy** [comment]
@artfuldev Yeah we definitely can use this issue to be a tracker. I'll try to review this tomorrow and write the action items to develop from it. Thanks!

**Comment by scopsy** [comment]
A lot has changed since :) Closing this one as we have moved more toward an HTTP API approach. Thanks everyone involved here
