### ISSUE TITLE
🚀 Feature: Support Bark

### ISSUE THREAD

**Issue by eightwomen** [novuhq/novu#4500]
### 🔖 Feature description

Bark

### 🎤 Why is this feature needed ?

Bark

### ✌️ How do you aim to achieve this?

Bark

### 🔄️ Additional Information

Bark

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by p-fernandez** [comment]
Could you provide more context on what is Bark and how it should be implemented?

**Comment by Cliftonz** [comment]
Just to update, I believe bark is a OS notification app that while it is not a blocker itself not not have great documentation or movement to support on our side.
Thank you for your request!
