### ISSUE TITLE
🚀 Feature: Bump pnpm version to latest

### ISSUE THREAD

**Issue by dammy001** [novuhq/novu#4501]
### 🔖 Feature description

This feature is to bump pnpm version requirement of the project to the latest. The project currently makes use of `7.33` which is outdated.

### 🎤 Why is this feature needed ?

Devs with the latest pnpm version can't install the project due to the strict engine check in the `package.json` file and there have been a lot of performance improvements.

### ✌️ How do you aim to achieve this?

update the engine and package manager section in the package JSON file.
- make the lockfile up-to-date.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by BiswaViraj** [comment]
@dammy001 I've assigned you, Let me know if you need any help 🙏🏼

**Comment by p-fernandez** [comment]
pnpm upgrade has been tackled here: https://github.com/novuhq/novu/pull/4528
