### ISSUE TITLE
[NV-2860] Fix the dropdown z-index issue in the Email Editor

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4506]
## Reproduction Steps
- Create the workflow and add the Email node
- Click on the Email node
- In the Email Editor create multiple new lines by clicking on the "+" button
- The dropdown will be cut down at the bottom

## Definition of done
- The dropdown actions/contents should be visible

![image](https://github.com/novuhq/novu/assets/2607232/a6991033-0be7-42a7-98f8-017bb5665220)

**Comment by AmreetKumarkhuntia** [comment]
Hello, I can work on this !!!

**Comment by LetItRock** [comment]
> Hello, I can work on this !!!

hey @AmreetKumarkhuntia 👋 of course, thank you!

**Comment by deep-yad** [comment]
hello, can i work on this?

**Comment by AmreetKumarkhuntia** [comment]
sorry brother already working on this.

**Comment by sudhanshugautam2911** [comment]
@LetItRock Can you assign me this issue? I think current assignee is unable to solve this issue

**Comment by deanurag** [comment]
I would like to work on this issue.

**Comment by ainouzgali** [comment]
@sudhanshugautam2911 @deanurag thank you for the interest!Tthere is already someone assigned for this one. Please take a look at any of the other unassigned issues :)

**Comment by Bilal-Gujjar** [comment]
@LetItRock I would really love to work on this, I am ready to make PR issue is fix. Can I get assigned to it? (check screenshot)
<img width="1666" alt="Screen Shot 2023-10-16 at 10 33 01 AM" src="https://github.com/novuhq/novu/assets/64352435/c2df5095-5cdd-4cb7-94fe-2770a5dfc5cc">

**Comment by ainouzgali** [comment]
Hi @Bilal-Gujjar, as I mentioned, there is already someone assigned. If it frees up, we will let you know.

**Comment by Bilal-Gujjar** [comment]
> Hi @Bilal-Gujjar, as I mentioned, there is already someone assigned. If it frees up, we will let you know.

ok

**Comment by Bilal-Gujjar** [comment]
Hi @LetItRock @ainouzgali Now it is more than a week Please check if the current assignee is unable to fix. Please assign me.I want to work in it.

**Comment by muzzammilHub** [comment]
hey! can you assign me this issue if no one is working on this..

**Comment by sudhanshugautam2911** [comment]
@LetItRock @ainouzgali  I think its time to re-assign this issue as current assignee is inactive.

**Comment by anmol-matharu-100** [comment]
@LetItRock I have made a pull request fixing the issue. Please review it as soon as possible.

**Comment by djabarovgeorge** [comment]
Before we reassign the issue @AmreetKumarkhuntia do you have an existing solution??

**Comment by anmol-matharu-100** [comment]
@djabarovgeorge @LetItRock  I have already submitted the solution via PR. Please assign it to me or directly review it.

**Comment by sudhanshugautam2911** [comment]
@djabarovgeorge If we go with first come first serve than this issue should be assigned to me & solution is also ready.

**Comment by AmreetKumarkhuntia** [comment]
Since I didn't get the time to work on the solution I am unassigning myself anyone with a solution please take it up. Sorry for the inconvenience.

**Comment by ainouzgali** [comment]
OK. @sudhanshugautam2911 assigning you.

**Comment by sudhanshugautam2911** [comment]
@djabarovgeorge @ainouzgali @LetItRock please checkout my PR, if possible please review changes today because today is the last date of hacktoberfest and I really want this contribution to be included as my PR in hacktoberfest.

**Comment by sudhanshugautam2911** [comment]
@ainouzgali Please checkout the PR
