### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Anjali-Git-Hub** [novuhq/novu#4516]
### 📜 Description

Need to add a full stop.

### 👟 Reproduction steps

I'm just reading the lines and found that it doesn't end with a full stop.

### 👍 Expected behavior

The line should be end with a full stop.

### 👎 Actual Behavior with Screenshots

![Capture](https://github.com/novuhq/novu/assets/122084921/ee8efc05-17b1-4626-9821-58aa2ab0218d)

### Novu version

0.17.0.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Ank61** [comment]
Hey! assign this task to me!

**Comment by priyankarpal** [comment]
@Anjali-Git-Hub it is not required

**Comment by p-fernandez** [comment]
Thanks for creating an issue.
Unfortunately we do not consider it as such.
Feel free to find other things in Novu to contribute with. 🙌🏻
