### ISSUE TITLE
🐛 Bug Report: Not able setup the project

### ISSUE THREAD

**Issue by Praveen03AJJARAPU** [novuhq/novu#4521]
### 📜 Description

I am running the script npm "npm run setup:project" but I got this log.
npm: 8.11.0
pnpm: 7.33.4
node: v16.15.1
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> setup:project
> npx --yes pnpm@7.33.4 i && node scripts/setup-env-files.js && pnpm build

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Scope: all 65 workspace projects
apps/inbound-mail                        |  WARN  deprecated mailparser@0.6.2
apps/web                                 |  WARN  deprecated @babel/polyfill@7.12.1
apps/web                                 |  WARN  deprecated react-flow-renderer@10.3.17
apps/ws                                  |  WARN  deprecated @types/socket.io@3.0.2
libs/embed                               |  WARN  deprecated rollup-plugin-json@4.0.0
libs/embed                               |  WARN  deprecated rollup-plugin-commonjs@10.1.0
libs/embed                               |  WARN  deprecated rollup-plugin-terser@7.0.2
packages/application-generic             |  WARN  deprecated codecov@3.8.3

 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@novu%2Fdal: Not Found - 404

This error happened while installing the dependencies of @novu/application-generic@0.20.0-alpha.1

@novu/dal is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
apps/api                                 |  WARN  deprecated @types/ioredis@5.0.0
Progress: resolved 526, reused 523, downloaded 0, added 0

### 👟 Reproduction steps

Run through the above versions.

### 👍 Expected behavior

Project should start running.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-14 211342](https://github.com/novuhq/novu/assets/97183004/5a352f5a-68c8-487c-966a-ea379001909d)

### Novu version

0.17.0

### npm version

 8.11.0

### node version

16.15.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by BrijeshPatra** [comment]
Hey @Praveen03AJJARAPU 
To resolve this issue, you can try the following steps:

 Check the Package Name: Make sure that you're using the correct package name for "@novu/dal" in your project's dependencies. Double-check the package name in your project's configuration files (e.g., package.json) to ensure it's spelled correctly.

 Verify Package Existence: Search for the package on the npm registry to confirm its availability. You can do this by visiting 
the package's npm page in your web browser or by using the npm search command:

// command
npm search @novu/dal
 If the package doesn't exist or is not available, you may need to check if there's an alternative package or source that you should be using instead.

Check Your Configuration Files: Review your project's npm or pnpm configuration files (e.g., .npmrc or .pnpmrc) to ensure that there are no custom registry settings or configurations that could be causing the issue.

 Update Dependencies: Ensure that you are using compatible versions of all dependencies in your project. You can try updating the versions of your dependencies to see if that resolves the issue.

 Alternative Package or Source: If the package is indeed not available in the public registry, consider whether there's an alternative package or source you can use for your project. You may need to consult the package's documentation or the maintainers for guidance.

 Check Network and Proxy Settings: Sometimes network issues or proxy settings can affect package installation. Ensure that your network connection is stable and that any proxy settings are correctly configured.

Registry Cache: Clear the npm or pnpm registry cache, as sometimes issues can be related to cached data. You can do this with the following command:

For npm:

//command
npm cache clean --force

For pnpm:

//command
pnpm cache clear --force

 After trying these steps, attempt to run the setup script again. If the issue persists, you may need to seek further assistance from the maintainers of the project or package in question, as it could be a specific issue related to that package.

**Comment by itsmemittal** [comment]
The issue is with version "0.20.0-alpha.1" of "@novu/application-generic," but after switching to version "0.20.0-alpha.0," the "setup:project" operation completed without any problems.
