### ISSUE TITLE
[NV-3028] Upgrade mocha to latest versions on all app packages

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#4527]
### What?
Upgrade mocha to latest version `10.2.0` on all apps packages

### Definition of Done
- Tests in all affected packages are passing
- pnpm lock file is updated
- package.json in all relevant packages is updated

<sub>[NV-3028](https://linear.app/novu/issue/NV-3028/upgrade-mocha-to-latest-versions-on-all-app-packages)</sub>

**Comment by ayushshukla7777** [comment]
Hey @scopsy . I am starting to work on this.
