### ISSUE TITLE
🐛 Bug Report: Inconsistent Use of Markdown Image Tags

### ISSUE THREAD

**Issue by biplobsd** [novuhq/novu#4541]
### 📜 Description

Some of the images are using the markdown image tag. Images appear rounded while others do not.

![image](https://github.com/novuhq/novu/assets/43641536/a7565b24-2190-4ad9-8016-8ae1043ef08c)

Here I find some of them:
![image](https://github.com/novuhq/novu/assets/43641536/792180cf-1337-41d6-a184-34cc07d77c9f)

In the some of tag I mean "Open in Gitpod" they are good.

### 👟 Reproduction steps

Visit : https://docs.novu.co/community/machine-setup#aws-cli

### 👍 Expected behavior

https://docs.novu.co/getting-started/how-novu-works

![image](https://github.com/novuhq/novu/assets/43641536/1030a7f2-ddc8-487a-80f8-535561864587)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/43641536/1030a7f2-ddc8-487a-80f8-535561864587)

### Novu version

0.19.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by krishanu7** [comment]
please assign it to me
