### ISSUE TITLE
Update the new Twitter logo to X

### ISSUE THREAD

**Issue by Shreyas0410** [novuhq/novu#4545]
- In the current version of the website the logo of Twitter is not updated.

-**To Reproduce** 
Go to https://novu.co/ and go to built by community section 

![novu_issue](https://github.com/novuhq/novu/assets/70795867/52280cd7-b71c-444b-b615-970024bb8224)

**Comment by ainouzgali** [comment]
@Shreyas0410 please re-open this in our [website repository](https://github.com/novuhq/website/issues) :)

**Comment by krishanu7** [comment]
please assign it to me
