### ISSUE TITLE
🐛 Bug Report: Missing Sender Name in Mandrill (Email) Provider

### ISSUE THREAD

**Issue by emersonliuuu** [novuhq/novu#4558]
### 📜 Description

`Sender Name` doesn't work in Mandrill Provider, as the [current implementation](https://github.com/novuhq/novu/blob/next/providers/mandrill/src/lib/mandrill.provider.ts#L46-L58) is missing the `from_name` parameter [required by Mandrill](https://mailchimp.com/developer/transactional/api/messages/send-new-message/) to set up the sender's name in the email.

### 👟 Reproduction steps

1.  Setup Mandrill provider in Novu Cloud
2. Create a workflow and implement a email template with Mandrill provider
3. Send a test email and check it in your inbox.
4. You might find there's no sender name.

### 👍 Expected behavior

`SenderName <email@domain.com>` is the expected value in the `from` field in received email

### 👎 Actual Behavior with Screenshots

Actually will only receive `email@domain.com`, although you have set up the `Sender Name` in Novu.

### Novu version

0.20.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by krishanu7** [comment]
please assign me

**Comment by saikiran76** [comment]
Please assign me this issue.
