### ISSUE TITLE
🐛 Bug Report:  LogRocket has already been loaded, loading a second instance is not supported.

### ISSUE THREAD

**Issue by saikiran76** [novuhq/novu#4562]
### 📜 Description

When navigating to the workspace, there is an issue with loading _LogRocket_, which is a tool used for logging and monitoring web applications. The error message suggests that there is already an instance of _LogRocket_ loaded, and attempting to load a second instance is not supported. This issue is commonly caused by loading _LogRocket_ both as a package in the application and as a script tag.

ERROR:
<img width="625" alt="image" src="https://github.com/novuhq/novu/assets/80874246/687c7df2-be63-45e4-aea0-54425a2d7582">

### 👟 Reproduction steps

1. Go to the Novu website and click **Get Started**.
2. Navigate towards _Workspace_ and open up the console by bringing in your browser's development tools.
3. Now, Filter out the errors by searching for the above issue or search sequentially in the errors that are in the console.

### 👍 Expected behavior

Ideally, when loading _LogRocket_, there should be only one instance of it in the application. Loading multiple instances can lead to conflicts and errors, as indicated by the error message in the image. To resolve the issue, it is recommended to identify and remove any duplicate instances of _LogRocket_.

### 👎 Actual Behavior with Screenshots

The message reads, "This is off of a script and as a script." Additionally, the image contains some detected text which says, "(\otimes \boldsymbol{\nabla}) LogRocket has already been loaded, loading a main.313dce4e.js:sourcemap:2 second instance is not supported. This is often caused by loading LogRocket as a package in your application and as a script tag."

<img width="820" alt="image" src="https://github.com/novuhq/novu/assets/80874246/f86cb875-d5d0-42a1-aeee-c28865e65e82">

### Novu version

Novu SaaS

### npm version

9.6.7

### node version

v18.17.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by p-fernandez** [comment]
Thank you for reporting it.
We have been already notified about it here: https://github.com/novuhq/novu/issues/4424
We will keep the evolution in that other issue. Please follow up there.
Closing as duplicate.
