### ISSUE TITLE
📚 Docs Feedback: Changed the emojis in the readme file to more relatable ones

### ISSUE THREAD

**Issue by abhi-vardhan** [novuhq/novu#4564]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/novuhq/novu/blob/next/README.md

### Kind of issue

Other

### Issue description

Few emojis were there which r not related to the text written. Tried to change it to better and more reliable ones

**Comment by abhi-vardhan** [comment]
![image](https://github.com/novuhq/novu/assets/112716983/6727fa16-62a7-48b1-bc3b-ec3af53a879c)
 This is the previous emojis

![image](https://github.com/novuhq/novu/assets/112716983/47982406-87ba-455c-addb-fbe33ac86fc2)
This is the after 

pls assign it to me, have the code ready and also few grammatical mistakes fixed.

**Comment by krishanu7** [comment]
Please assing me.

**Comment by p-fernandez** [comment]
Thanks for opening this issue. 🙏🏻 
We have a Design Team that takes care of this kind of things. We will provide the feedback to them to manage internally.
