### ISSUE TITLE
🚀 Feature: make expireAt configurable

### ISSUE THREAD

**Issue by Khongchai** [novuhq/novu#4570]
### 🔖 Feature description

Hi, Novu team! 

Do you have any plans on making the `expireAt` property configurable?  I have looked at [this release note ](https://github.com/novuhq/novu/releases/tag/v0.14.0) + the source code but didn't manage to find any information on how to configure ttl or `expireAt`.

### 🎤 Why is this feature needed ?

 We have a usecase where we want to broadcast some announcements for events, but depending on the types of the events, the expiry date might wary. 

For example, if the event is participatory by nature, i.e.  only lasts for 3 days, then the users that login after that 3-day-period should not be notified of the event. 

Of course, we can work around this by subscribing all users that come online during the active period to that event, but I think that is less convenient that just setting the event to expire after some time.

### ✌️ How do you aim to achieve this?

I want to be able to do something like this

```ts
await novu.trigger('<WORKFLOW_TRIGGER_ID>',
  {
    to: {
      // ...
    },
    payload: {
       // ...
    },
  },
  overrides: {
    // set ttl to 3 days here. Maybe override the ttl config from the env var as well if it's disabled.
  } 
);
```

Basically all users that are logged in within the 3-day period gets this notification, but those that login after, do not. 

If there is already a way to achieve this. Please let me know, I might have missed something. I talked to Novu AI and it was hallucinating wildly, so I assumed it's because this is not really talked about that much.

We'd also be happy to contribute back to Novu if this is already something that's been sitting in your backlog!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by michaldziuba03** [comment]
I believe there is env variable to configure TTL - as far I remember expiration is based on MongoDB TTL index so you cannot set it dynamically for example inside trigger.

**Comment by Khongchai** [comment]
Hello! Appreciate the response.

> I believe there is env variable to configure TTL

There is, but that's only for enabling or disabling TTL. On or off only.

> as far I remember expiration is based on MongoDB TTL index so you cannot set it dynamically for example inside trigger.

How so? **Maybe I'm missing something** crucial here, but from the source code, I see some dynamic `expireAt` calculations. For example, [here](https://github.com/novuhq/novu/blob/7f369353b9efa7d330187cca228d61b5115d7d2f/packages/application-generic/src/usecases/create-notification-jobs/create-notification-jobs.usecase.ts#L54)

```ts 
    const notification = await this.notificationRepository.create({
      _environmentId: command.environmentId,
      _organizationId: command.organizationId,
      _subscriberId: command.subscriber._id,
      _templateId: command.template._id,
      transactionId: command.transactionId,
      to: command.to,
      payload: command.payload,
      expireAt: this.calculateExpireAt(command), // this
      channels,
    });
```

**Comment by michaldziuba03** [comment]
Sorry I think I missed the point.

I think TTL in the release note is just about storage, messages will be deleted after some time to save space.

But for your use case where you need to expire notification messages because some event became not relevant, I'm not sure if it's possible.

**Comment by Khongchai** [comment]
@scopsy 

Oh. I see. Well, if there's anything we can do to help, we'd be happy to contribute! Thank you @michaldziuba03 and @scopsy  for the swift replies.

**Comment by katyaterletskaya** [comment]
Hey @scopsy 😊 any updates on this? I would like to contribute to make expiredAt configurable

**Comment by scopsy** [comment]
@katyaterletskaya we can defiently make it configurable, the only thing is that the definition of the TTL indexes will need to happen on mongodb directly and not via the Novu code base. Will that help?

**Comment by katyaterletskaya** [comment]
@scopsy I would like to customize the retention period of in-app messages to 1 month. This should only require code changes, right?

**Comment by scopsy** [comment]
So just updating the env variable, and making sure you have a TTL index set up in mongodb yes.
