### ISSUE TITLE
[NV-3037] 🐛 Bug Report: Wrong Socket Close in useUnreadCount.ts

### ISSUE THREAD

**Issue by Khongchai** [novuhq/novu#4582]
### 📜 Description

In[ this hook](https://github.com/novuhq/novu/blob/e332a6c8b46aef1e886330d5560c4ec705afdb78/packages/notification-center/src/hooks/useUnreadCount.ts#L43), you're doing `socket.on(WebSocketEventEnum.UNREAD)` but you're doing `socket.off(WebSocketEventEnum.UNSEEN)`.

### 👟 Reproduction steps

None

### 👍 Expected behavior

It should closes the correct socket channel.

### 👎 Actual Behavior with Screenshots

```ts
    socket.on(
      WebSocketEventEnum.UNREAD, // <<<<<<<<<<<<< here
      debounce((data?: { unreadCount: number }) => {
        if (Number.isInteger(data?.unreadCount)) {
          queryClient.setQueryData<{ count: number }>(queryKeysRef.current.unreadCountQueryKey, (oldData) => ({
            count: data?.unreadCount ?? oldData.count,
          }));

          // when unread count changes, we need to refetch unseen count
          queryClient.refetchQueries(queryKeysRef.current.unseenCountQueryKey, {
            exact: false,
          });
          queryClient.refetchQueries(queryKeysRef.current.fetchNotificationsQueryKey, {
            exact: false,
          });
          // refetch all feeds unseen count that is shown on the tabs
          queryClient.refetchQueries([...FEED_UNSEEN_COUNT_QUERY_KEY], {
            exact: false,
          });

          dispatchUnreadCountEvent(data.unreadCount);
        }
      }, DEBOUNCE_TIME)
    );

    return () => {
      socket.off(WebSocketEventEnum.UNSEEN); // <<<<<<<<<<<<< here
    };
  }, [socket, queryClient, setQueryKey]);
```

### Novu version

0.17.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes

<sub>[NV-3037](https://linear.app/novu/issue/NV-3037/🐛-bug-report-wrong-socket-close-in-useunreadcountts)</sub>

**Comment by Khongchai** [comment]
Just noticed that the query being refetched is also the wrong one.

<img width="730" alt="image" src="https://github.com/novuhq/novu/assets/56601823/317fa401-5698-43d9-a5d8-c8b54240445d">

**Comment by p-fernandez** [comment]
Thank you for raising this bug. Indeed you are right.
I am assigning the issue to you as you mention you are happy to raise a PR to fix it.

**Comment by p-fernandez** [comment]
> @p-fernandez I'll open a PR for the socket one.
> 
> Perhaps @krishanu7 can have this other one?
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/56601823/276676836-22576f59-dc0b-49e2-8fb6-cbf1821d3830.png">
> These still references unseen count when they should probably be unread.

I think it is better if you can fix both issues in the same PR as you identified them. 🙂

**Comment by Khongchai** [comment]
@p-fernandez  just checked the code. It seems the other parts I mentioned were actually already correct, no?

<img width="651" alt="image" src="https://github.com/novuhq/novu/assets/56601823/80b1549a-8904-4ef3-9fbe-6ab0e9a7de23">

It's just reflecting the change after having updated unread to unseen. Please let me know if my assumption is correct. If not, I'll add more changes.

Here's the PR https://github.com/novuhq/novu/pull/4590
