### ISSUE TITLE
[NV-3041] Migrate from clicksend SDK to direct API calls with Axios

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4586]
## What?

In the `@novu/clicksend` package we would like to migrate from using the `clicksend` SDK to having a code that directly calls to the provider APIs. Check the documentation about the API here: https://developers.clicksend.com/docs/rest/v3/#ClickSend-v3-API-Transactional-Email

## Why? (Context)

Due to an un-maintained SDK, we should move from the official SDK' to working directly with the provider's API spec.

## Definition of Done
- the SDK package has been removed from the package.json file
- the current provider functionality works with the calls to their APIs using Axios
  - attachments
  - email delivery with all fields

**Comment by nick2432** [comment]
can i work on this?

**Comment by sikehish** [comment]
Hey. Im working on this. Can you assign it to me?

**Comment by Prathamesh625** [comment]
Please , Assign this issue to me , I will work on it

**Comment by djabarovgeorge** [comment]
Thanks to everyone for taking the initiative to help 🙏, I will assign @[his-maj-esty](https://github.com/his-maj-esty) his-maj-esty for now as no one was assigned yet and he raised a PR already.

**Comment by djabarovgeorge** [comment]
I am not able to assign, maybe some bug in Github 😕
