### ISSUE TITLE
[NV-3040] Migrate from pepipost SDK to direct API calls with Axios

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4587]
## What?
In the `@novu/netcore` package we would like to migrate from using the `pepipost` SDK to having a code that directly calls to the provider APIs. Check the documentation about the API here: https://cpaasdocs.netcorecloud.com/docs/pepipost-api/c2d895762f832-send-an-email

## Why? (Context)
Due to an un-maintained SDK, we should move from the official SDK' to working directly with the provider's API spec.

## Definition of Done
- the SDK package has been removed from the package.json file
- the current provider functionality works with the calls to their APIs using Axios
  - attachments
  - email delivery with all fields

**Comment by Junko-Takeguchi** [comment]
Can I work on this issue?
