### ISSUE TITLE
[NV-3039] Migrate from sparkpost SDK to direct API calls with Axios

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4588]
## What?
In the `@novu/sparkpost` package we would like to migrate from using the `sparkpost` SDK to have a code that directly calls to the provider APIs. Check the documentation about the API here: https://developers.sparkpost.com/api/

## Why? (Context)
Due to an un-maintained SDK, we should move from the official SDK' to working directly with the provider's API spec.

## Definition of Done
- the SDK package has been removed from the package.json file
- the current provider functionality works with the calls to their APIs using Axios
  - attachments
  - email delivery with all fields

**Comment by michaldziuba03** [comment]
@LetItRock can you assign me, I'm currently working on other issue regarding Sparkpost and I want to avoid git conflicts

**Comment by harshit-senpai** [comment]
Hey I would like to work on it

**Comment by djabarovgeorge** [comment]
Hey @michaldziuba03, 
We assigned you please let us know if you won't have the time to work on this issue so we can assign it if needed.

**Comment by ayushshukla7777** [comment]
Hey @LetItRock @djabarovgeorge , Since no one is activly working on this issue, I would like to raise a PR.

**Comment by michaldziuba03** [comment]
@ayushshukla7777 it's active

I'm waiting for merge: https://github.com/novuhq/novu/pull/3736
