### ISSUE TITLE
[NV-3038] Migrate from @sendinblue/client SDK to direct API calls with Axios

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4589]
## What?
In the `@novu/sendinblue` package we would like to migrate from using the `@sendinblue/client` SDK to having a code that directly calls to the provider APIs. Check the documentation about the API here: https://developers.brevo.com/

## Why? (Context)
Due to an un-maintained SDK, we should move from the official SDK' to working directly with the provider's API spec.

## Definition of Done
- the SDK package has been removed from the package.json file
- the current provider functionality works with the calls to their APIs using Axios
  - attachments
  - email delivery with all fields

**Comment by Vidip-Ghosh** [comment]
Which tech is used in this case?

**Comment by nick2432** [comment]
can i work on this?

**Comment by SpeedReach** [comment]
@LetItRock May I work on this? I'd be happy to help.

**Comment by Dhoni77** [comment]
I would like to work on this

**Comment by ayushshukla7777** [comment]
hey, I'm free too. Can I work on this or any of the new tasks?

**Comment by djabarovgeorge** [comment]
Thanks to everyone for taking the initiative to help 🙏, I will assign @Dhoni77 for now as no one was assigned yet and he raised a PR already.
