### ISSUE TITLE
📚 Docs Feedback: Change Twitter name to X (Twitter) in apps/Api/README.md

### ISSUE THREAD

**Issue by BandhiyaHardik** [novuhq/novu#4606]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/novuhq/novu/blob/next/apps/api/README.md

### Kind of issue

Unclear explanations

### Issue description

I was looking into apps/api/README.md and i noticed that twitter is now known as x but it is not changed in documentation.

![image](https://github.com/novuhq/novu/assets/110784317/e305d0af-d09b-4506-a7e2-587bddf0dfcd)

**Comment by michaldziuba03** [comment]
spammy/low effort issue and PR .

No one cares about readme of API - it's generated by CLI anyway.
Seriously, there are important issues to choose from.
