### ISSUE TITLE
📚 Docs Feedback: Addressing various grammatical errors in the README.md 

### ISSUE THREAD

**Issue by alienishi** [novuhq/novu#4612]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/novuhq/novu#readme

### Kind of issue

Other

### Issue description

The README.md file has various grammatical errors.

### Context 🔦

The README.md file has various grammatical errors which I am addressing and would like to correct.

**Comment by alienishi** [comment]
@scopsy 
I have created an issue, as you mentioned in my previous PR
please review it 
and if you'll allow, I would love to work on it :)

**Comment by djabarovgeorge** [comment]
Hello @alienishi 
Thanks for creating an issue in order to improve the README file.

The issue you've opened is quite general. I'll assign it to you, but could you please refine it and submit a relevant Pull Request to address this issue?

**Comment by alienishi** [comment]
@djabarovgeorge will start working right away :)
