### ISSUE TITLE
Anki Algorithm

### ISSUE THREAD

**Issue by vasnt** [novuhq/novu#4618]
I am just wondering is Anki/related SRS Algorithm integrated in Novu?

**Comment by jainpawan21** [comment]
Hi @vasnt 

Could you please share the use of this algorithm and how it can be useful in Novu?

**Comment by vasnt** [comment]
Since Novu is all about notification, SRS algo (more details: https://www.juliensobczak.com/inspect/2022/05/30/anki-srs.html or https://github.com/open-spaced-repetition/fsrs4anki) can help to remain on top of (non-critical/time-sensitive) tasks/things by regularly reminding about it.  Isnt it?

**Comment by Cliftonz** [comment]
@vasnt We do not, we use bullmq repeatable jobs or delayed jobs as our schedules are very deterministic this way.

If we do need something that is higher scale and in house, I will take a look at this recommendation
