### ISSUE TITLE
[NV-3052] 🚀 Feature: Add Pusher Beam as a Push Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4634]
### 🔖 Feature description

Use the [pusher beam docs](https://pusher.com/docs/beams/reference/server-sdk-node/) to create a new push provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

more options for the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-3052](https://linear.app/novu/issue/NV-3052/🚀-feature-add-pusher-beam-as-a-push-provider)</sub>

**Comment by im-perativa** [comment]
Can i work on this?

**Comment by im-perativa** [comment]
@Cliftonz sorry i messed up the previous PR, will submit a cleaner PR later today
