### ISSUE TITLE
[NV-3053] Migrate from onesignal-node SDK to the official @onesignal/node-onesignal

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4635]
## What?
In the @novu/one-signal package we would like to migrate from using the onesignal-node SDK to the official @onesignal/node-onesignal SDK. Check the documentation about the it here: https://github.com/OneSignal/onesignal-node-api#readme

## Why? (Context)
Due to vulnerabilities and un-maintained SDK, we should move from using unofficial onesignal-node SDK.

## Definition of Done
- the onesignal-node SDK package has been replaced with @onesignal/node-onesignal
- the current provider functionality works with the calls to the new @onesignal/node-onesignal SDK:
  - attachments
  - email delivery with all fields

**Comment by Dhoni77** [comment]
HI @LetItRock I would like to work on this.

**Comment by djabarovgeorge** [comment]
Hey @Dhoni77 you are already assigned to an open issue. Let's see if someone is willing to help here, if not we will assign you.

**Comment by anshikavashistha** [comment]
@LetItRock Can I work in this issue?

**Comment by djabarovgeorge** [comment]
Hey @anshikavashistha, 
This issue has already been assigned.
@sakshivbp1812 how is your progress, are you managing to create migration for onesignal?

**Comment by scopsy** [comment]
@sakshivbp1812 how things are going? Please let me know if you would love to be un-assigned so we can let someone else to work on this in case you are not able to do so 🙏

**Comment by Dhoni77** [comment]
Hi @scopsy If there is no progress I can take this issue

**Comment by scopsy** [comment]
@Dhoni77 have assigned you 🙏
