### ISSUE TITLE
🐛 Bug Report: Suggestion to Enhance User-Friendliness through Social Media Handle Logos #638

### ISSUE THREAD

**Issue by moheyt** [novuhq/novu#4636]
### 📜 Description

Currently, you're using text-based links for your social media handles on your website, emails, and other digital communication channels. While this practice effectively conveys the information, it might not be the most user-friendly approach. Users often process visual information more quickly and accurately than text, and the use of logos or icons alongside your social media links can significantly improve user engagement and recognition.

Integrating logos or icons representing each of your social media platforms alongside the corresponding links. This would not only make it easier for users to identify and connect with us on their preferred social media channels but also contribute to a more cohesive and visually appealing brand image.

I would like to fix this. Please assign me. #Hacktoberfest

### 👟 Reproduction steps

1. Go to Homepage
2. Scroll down the bottom

### 👍 Expected behavior

The expected behavior involves the integration of logos or icons that represent each of your social media platforms next to the corresponding links. This not only simplifies the process for users to identify and connect with you on their preferred social media channels but also contributes to a more cohesive and visually appealing brand image. This approach enhances the overall user experience and reinforces your brand identity, making it easier for users to interact with your social media presence.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-24 115735](https://github.com/novuhq/novu/assets/85775976/2e633c59-7d95-47d0-9bde-86ca8e8be946)

### Novu version

0.15.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by djabarovgeorge** [comment]
@LetItRock Do you think we could benefit from this change?

**Comment by scopsy** [comment]
For now we will have this as-is. Thank you @moheyt
