### ISSUE TITLE
🐛 Bug Report: Overlapping Icons in Integration Store

### ISSUE THREAD

**Issue by moheyt** [novuhq/novu#4637]
### 📜 Description

I encountered in the Integration Store window of our application. It appears that two icons are overlapping, which is causing a visual problem and may lead to user confusion.

#hacktoberfest

### 👟 Reproduction steps

1. Launch the application.
2. Click on Get Started 
3. Navigate to the "Integration Store" window.
4. Observe the icons within this window.

### 👍 Expected behavior

The icons in the Integration Store window should be clearly displayed without any overlapping.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-10-24 121437](https://github.com/novuhq/novu/assets/85775976/505a5453-f852-4f56-8952-47ebeebda818)

### Novu version

0.15.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sudhanshugautam2911** [comment]
hey @moheyt, This issue is already solved here #4574

**Comment by moheyt** [comment]
oh My bad @sudhanshugautam2911
