### ISSUE TITLE
🐛 Bug Report: Blog Section Scrolling Issue

### ISSUE THREAD

**Issue by moheyt** [novuhq/novu#4638]
### 📜 Description

Upon entering the website's "Blog" section, users encounter a scrolling issue that disrupts their ability to smoothly navigate and read the blog content. When attempting to scroll down the page, several problematic behaviors manifest, negatively affecting the overall user experience.

### 👟 Reproduction steps

1. Open the website.
2. Navigate to the "Blog" section.
3. Attempt to scroll down the blog page.

### 👍 Expected behavior

When scrolling in the "Blog" section, the content should smoothly move down, allowing the user to access all the blog posts.

### 👎 Actual Behavior with Screenshots

https://github.com/novuhq/novu/assets/85775976/20a7a4a7-aaf0-41d8-8184-3e70b24cbe2f

### Novu version

0.15.0

### 📃 Provide any additional context for the Bug.

1. This issue occurs consistently and has been observed on multiple devices and browsers.
2. Other sections of the website do not seem to exhibit this scrolling problem, suggesting that it might be specific to the "Blog" section.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kevaldev** [comment]
Hey moheyt, could you please share details of browser?
Currently its working fine in the browser.

**Comment by moheyt** [comment]
I have tried it in Chrome. First, click on 'Announcement,' and then switch to another options. Please check the attached video. I have also tried it in other browsers."

**Comment by kevaldev** [comment]
I repeated same steps as per the video but its working fine with the Chrome

**Comment by moheyt** [comment]
idk but i've tried it several time then i created this issue.

**Comment by kevaldev** [comment]
Could you please check this video am i following right steps?

https://github.com/novuhq/novu/assets/112800764/a07b7f32-3ad0-4c4b-b0fd-49e4f8fbe127

**Comment by moheyt** [comment]
Uploading Recording 2023-10-24 132056.mp4…

**Comment by moheyt** [comment]
https://github.com/novuhq/novu/assets/85775976/260ae37d-9c34-43ea-ae87-23d2ab78c6fd

**Comment by moheyt** [comment]
just do it slowly.

**Comment by kevaldev** [comment]
I have tried it several times but working fine

**Comment by moheyt** [comment]
idk then let wait for someone else to be verify this issue.

**Comment by djabarovgeorge** [comment]
Works fine for me in Chrome, as you said let's see if someone else can verify, maybe then we can locate the issue.

**Comment by JeevaRamanathan** [comment]
Hi @moheyt @djabarovgeorge, am facing the same issue as well by recreating the steps in video.
Also I don't see that website as a part of this novu repo also not under hacktoberfest?

**Comment by ayush02dev** [comment]
hii i am facing same issue can i work on it @kevaldev
