### ISSUE TITLE
[NV-3073] [NV-2902] bug: new workflow is critical by default

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4646]
### What?

Critical workflow overrides above the workflow and subscriber preference

### Why? (Context)

Steps to reproduce:-

1. Create a new workflow
2. Add any channel / action step
3. update the workflow
4. go to settings, workflow is critical by default.
5. **Users will be able to manage subscriptions** toggle button is off

Definition of Done

It should not be critical by default as a new user is not aware of the critical concept. Users get confused as to why subscriber preference is not working.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2902](https://linear.app/novu/issue/NV-2902/bug-new-workflow-is-critical-by-default)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3073](https://linear.app/novu/issue/NV-3073/[nv-2902]-bug-new-workflow-is-critical-by-default)</sub>

**Comment by Atharva1723** [comment]
@jainpawan21 Is this issue and the NV-2902 i.e issue #4647 the same ..If not please assign me

**Comment by jainpawan21** [comment]
Duplicate of #4647
