### ISSUE TITLE
[NV-2902] bug: new workflow is critical by default

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4647]
### What?

Critical workflow overrides above the workflow and subscriber preference

### Why? (Context)

Steps to reproduce:-

1. Create a new workflow
2. Add any channel / action step
3. update the workflow
4. go to settings, workflow is critical by default.
5. **Users will be able to manage subscriptions** toggle button is off

Definition of Done

It should not be critical by default as a new user is not aware about critical concept. User get confused why subscriber preference is not working?

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2902](https://linear.app/novu/issue/NV-2902/bug-new-workflow-is-critical-by-default)</sub>

**Comment by lalitkumawat1m** [comment]
Hey Team, I want to work on this issue please assign to me
