### ISSUE TITLE
🚀 Feature: The Buttons in the Header Section Lacks Transition

### ISSUE THREAD

**Issue by DeepRahangdale** [novuhq/novu#4658]
### 🔖 Feature description

When hovering over an element, apply a smooth transition effect with a scale change from 95% to 105% to create a subtle zoom-in and out effect, enhancing the user interaction and visual feedback.

### 🎤 Why is this feature needed ?

enhancing the user interaction

### ✌️ How do you aim to achieve this?

apply a smooth transition effect with a scale change from 95% to 105%.

similar to this site.
https://drive.google.com/file/d/1Gm2KpWL_40dTaTYSwiTKyI3HPI0nPcQw/view?usp=sharing

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Harikrishna3** [comment]
are you working on it?
I would like to work on it
