### ISSUE TITLE
📚 Docs Feedback: Update the spanish language typescript file in notification center 

### ISSUE THREAD

**Issue by Atharva1723** [novuhq/novu#4659]
### Duplicates

- [X] I have searched the existing issues

### Related page

packages/notification-center/src/i18n/languages/es.ts

### Kind of issue

Broken demonstration

### Issue description

I was looking for a proper Spanish translation and it appears that some of the words are not properly translated :
1) poweredBy: 'Con tecnología de'  - The correct translation should be 'Energizado por'
2) settings: 'Configuración' - The correct translation should be 'Ajustes'
3) noNewNotification: 'Nada nuevo por aquí' - The correct translation should be 'noNuevaNotificación'

**Comment by Harikrishna3** [comment]
I would like to work on it
