### ISSUE TITLE
🐛 Bug Report: CSS bug , Question Mark Icon overlapping

### ISSUE THREAD

**Issue by Atharva1723** [novuhq/novu#4678]
### 📜 Description

![image](https://github.com/novuhq/novu/assets/87201444/7c2a799d-1d79-4bdd-836f-123b831d05cd)
![image](https://github.com/novuhq/novu/assets/87201444/9b611d29-5afa-4688-a157-c25331b82bcc)

 The question mark icon overlaps with the text "Channels" in the screenshot. This is a bug because it makes the text difficult to read and can be confusing for users. 

### 👟 Reproduction steps

1. Goto Workflow -> Workflow Settings -> Channels 
2. Click on the Profile tab in the top right corner 

### 👍 Expected behavior

The profile tab should overlap the question mark icon 

### 👎 Actual Behavior with Screenshots

The question mark icon is overlapping the profile tab

### Novu version

Novu

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Atharva1723** [comment]
@Cliftonz Please review my raised issue. If it is accepted then please assign me

**Comment by jainpawan21** [comment]
@Atharva1723 Closing this issue as this is not reproducible anymore 

Thanks for creating big report for this 🙂
