### ISSUE TITLE
🚀 Feature: Add GetStream as a Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4679]
### 🔖 Feature description

Use the [GetStream docs](https://getstream.io/chat/docs/node/?language=javascript)  to create a new chat provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

more options for the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by ayushshukla7777** [comment]
hey @Cliftonz , I would love to work on this issue. Can you please also add  hacktoberfest badge

**Comment by Cliftonz** [comment]
@ayushshukla7777 I have already assign you the braze provider. If no one else has taken this and you get that one done, I would be happy to assign it to you.

**Comment by vikaspatil0021** [comment]
@Cliftonz I would like to work on this issue

**Comment by vikaspatil0021** [comment]
Hey @Cliftonz ,Please review the PR

**Comment by lillheaton** [comment]
Hey @vikaspatil0021 I'm very interested in the GetStream provider. Have a hard time understanding the connection however? Would you be able to share the intended workflow and how to get going? Would be greatly appreciated

**Comment by Cliftonz** [comment]
@lillheaton Are you able to put this in the support channel in our discord?
