### ISSUE TITLE
🚀 Feature: Add Azure SMS as an SMS Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4681]
### 🔖 Feature description

Use the [Azure SMS docs](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/sms/send?tabs=windows&pivots=programming-language-javascript#authenticate-the-client) to create a new push provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

more options for the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by parveshsaini** [comment]
I'd like to work on this. Please assign it to me
