### ISSUE TITLE
🚀 Feature: Add Grafana On-call as a Incident Management Provider 

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4682]
### 🔖 Feature description

Use the [Grafana On-call docs](https://grafana.com/docs/oncall/latest/integrations/webhook/) to create a new push provider while following [Novu's guide to a new provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

This provider should act functionally similar to chat provider in that the credentials will be passed by a subscriber (alert_uid, state, etc) except for the message and title.

### 🎤 Why is this feature needed ?

more options for the community

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by mahendraHegde** [comment]
@Cliftonz I'd like to pick this up.

**Comment by mahendraHegde** [comment]
@Cliftonz  i have raised the PR

**Comment by Cliftonz** [comment]
Awesome, I will check it out.
