### ISSUE TITLE
📚 Docs Feedback: Space missing 

### ISSUE THREAD

**Issue by ayushshukla7777** [novuhq/novu#4685]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider

### Kind of issue

Broken demonstration

### Issue description

I was looking for the docs on adding new providers  and it appears that a space is missing which is making it look bad.

### Context 🔦

Add the space between 'infobipsupports'  to make it 'infobi supports' .
![image](https://github.com/novuhq/novu/assets/53791140/80350ad0-0383-4a01-8106-3c956cc56699)

**I can raise pull request for this.

**Comment by Nitinshukla88** [comment]
Please assign this issue to me. @Cliftonz

**Comment by shawakash** [comment]
@Cliftonz Please Review it

**Comment by SSukhvant** [comment]
@Cliftonz I'm interested in contributing to this issue and would like to create a pull request to address it.

**Comment by Nitinshukla88** [comment]
@SSukhvant @shawakash Guys I'm being assigned this issue and im working on it.In case I'm not able to resolve it I will directly ask maintainer to assign it to any of you.Thanks.

**Comment by Nitinshukla88** [comment]
@Cliftonz 
Actually this issue is of the the repository novuhq/docs.
Since the doc file is not present in this repository so there is no sense of raising or contributing this issue here.
I would like to propose to close/drop this issue from this repository.
Thank you.
