### ISSUE TITLE
[NV-3072] Workflow update button should show loading state when clicked

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4703]
### What?

Whenever we add new step or change anything in any of the workflow step, update button becomes active

### Why? (Context)

After updating the step or workflow settings, when user clicks on the update button. it gets freezes for few seconds. User may click multiple times.

https://github.com/novuhq/novu/assets/39362422/cdc93613-e1c6-4085-b0ce-5f92de5ded6b

### Definition of Done

Update button should show loading state

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3072](https://linear.app/novu/issue/NV-3072/workflow-update-button-should-show-loading-state-when-clicked)</sub>

**Comment by TheNatkat** [comment]
hii team, i would like to work on this issue but i am not able to open this recorded video can you help me with that.

**Comment by sudhanshugautam2911** [comment]
yes...Unable to play video.

**Comment by jainpawan21** [comment]
Updated description with correct video link

**Comment by iknlaxmi** [comment]
hi,I would like to contribute to this issue.

**Comment by jainpawan21** [comment]
Assigned to you @iknlaxmi

**Comment by jainpawan21** [comment]
@iknlaxmi how is it going?

**Comment by iknlaxmi** [comment]
@jainpawan21 Almost done today or tomorrow I will submit PR.

**Comment by iknlaxmi** [comment]
@jainpawan21 I have submitted PR. Please review.
