### ISSUE TITLE
Storybook of web is crashing on-load

### ISSUE THREAD

**Issue by ninjadev101** [novuhq/novu#472]
**Describe the bug**
storybook of web is crashing...

**To Reproduce**
1. `git pull origin main`
2. `cd apps/web`
3. `pnpm storybook`

**Expected behavior**
Working properly....

**Screenshots**
![image](https://user-images.githubusercontent.com/52289096/163091806-989549e0-e9e5-4651-b7bc-3a16512f5fdb.png)

**Comment by scopsy** [comment]
Might be caused from the latest PasswordInput addition. I think we should also add a storybook github action to validate it builds and runs on web project changes.

Thanks for the quick fix!
