### ISSUE TITLE
🐛 Bug Report: Helm chart not working

### ISSUE THREAD

**Issue by aayushave** [novuhq/novu#4726]
### 📜 Description

D:\novu-next\docker\kubernetes\helm>helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

D:\novu-next\docker\kubernetes\helm>kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2

when i tried to buid helm chart it throws error as below
D:\novu-next\docker\kubernetes\helm>helm install my-release ./
Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: redis, mongodb, common, localstack

### 👟 Reproduction steps

Run helm install my-release ./
error: Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: redis, mongodb, common, localstack

then as comment i tried the below command
helm dependency build
Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies

then tried  the below command
helm dependency update

Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://localstack.github.io/helm-charts" chart repository
Error: could not retrieve list of tags for repository oci://registry-1.docker.io/bitnamicharts: GET "https://registry-1.docker.io/v2/bitnamicharts/redis/tags/list": unable to retrieve credentials

### 👍 Expected behavior

novu should be up and running

### 👎 Actual Behavior with Screenshots

Novu doesnt run and is not working with helm charts

Steps below 

Run helm install my-release ./
error: Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: redis, mongodb, common, localstack

then as comment i tried the below command
helm dependency build
Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies

then tried  the below command
helm dependency update

Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://localstack.github.io/helm-charts" chart repository
Error: could not retrieve list of tags for repository oci://registry-1.docker.io/bitnamicharts: GET "https://registry-1.docker.io/v2/bitnamicharts/redis/tags/list": unable to retrieve credentials

### Novu version

0.15.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Cliftonz** [comment]
@aayushave We are working on fixing this within the next few months and the current one is community supported.
