### ISSUE TITLE
🐛 Bug Report: Bulk Apply Changes in @node/novu wrong property name

### ISSUE THREAD

**Issue by Khongchai** [novuhq/novu#4736]
### 📜 Description

For `POST v1/changes/bulk/apply`, the name of the required property `changeIds` in the body of the request is wrong when using @novu/node typescript sdk.

The endpoint expects `changeIds`, but the sdk passes `ChangeIDs`

[sdk](https://github.com/novuhq/novu/blob/a063e8ed4e135899438bbc4e03910b386c72e722/packages/node/src/lib/changes/changes.ts#L33)

novu backend[
](https://github.com/novuhq/novu/blob/a063e8ed4e135899438bbc4e03910b386c72e722/apps/api/src/app/change/changes.controller.ts#L93)

### 👟 Reproduction steps

Call `novu.changes.bulkApply(["someId"]);`

The endpoint will throw an error. The screenshot is attached below.

### 👍 Expected behavior

The Id should match. Either both use `ChangeIDs` or `changeIds`

### 👎 Actual Behavior with Screenshots

I had another request with a bunch of ids, but the one in the screenshot is an empty array. Both throw the same error.

<img width="461" alt="image" src="https://github.com/novuhq/novu/assets/56601823/dcafc247-3435-446e-b1a8-30eeef48c415">

### Novu version

0.17.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nick2432** [comment]
can i work on this issue?
