### ISSUE TITLE
[NV-3126] Novu should fail delay error gracefully

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4748]
### What?

The delay step accepts the scheduled time variable

### Why? (Context)

If the user sets this variable a past date time, then novu fails the step and stop the execution. This error is not logged in activity feed logs.

### Definition of Done

Delay errors should fail gracefully with logs in activity feed

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3126](https://linear.app/novu/issue/NV-3126/novu-should-fail-delay-error-gracefully)</sub>

**Comment by Cliftonz** [comment]
Sounds like we should set up a verification in the trigger engine and the UI

**Comment by jainpawan21** [comment]
@Cliftonz Yes we should handle this from backend, because as well as from UI

**Comment by Khongchai** [comment]
Would it be possible for us to have a query parameter like `failOnInvalidDelay` that would cause this

```ts
  const delay = differenceInMilliseconds(new Date(delayDate), new Date());

      if (delay < 0) {
        throw new ApiException(
          `Delay date at path ${delayPath} must be a future date`
        );
      }

   return delay;
```

to behave like this?

```ts
  const delay = Math.max(0, differenceInMilliseconds(new Date(delayDate), new Date()));

  return delay;
```

For short delay interval (< 5 minutes) and large amount of subscribers, there is a chance that the time it takes to schedule is longer than the provided delay time, we sometimes want the jobs to just fire if it finds that the delay job is in the past.

**Comment by jainpawan21** [comment]
> Would it be possible for us to have a query parameter like `failOnInvalidDelay`(bad name, I know) that when set to false, would cause this
> 
> ```ts
>   const delay = differenceInMilliseconds(new Date(delayDate), new Date());
> 
>       if (delay < 0) {
>         throw new ApiException(
>           `Delay date at path ${delayPath} must be a future date`
>         );
>       }
> 
>    return delay;
> ```
> 
> to behave like this?
> 
> ```ts
>   const delay = Math.max(0, differenceInMilliseconds(new Date(delayDate), new Date()));
> 
>   return delay;
> ```
> 
> For short delay interval (< 5 minutes) and large amount of subscribers, there is a chance that the time it takes to schedule is longer than the provided delay time, we sometimes want the jobs to just fire if it finds that the delay job is in the past.

@djabarovgeorge WDYT?

**Comment by djabarovgeorge** [comment]
@Khongchai Good idea, 
The main reason for the un gracefully failure was that in the trigger flow, an unexpected exception while creating a notification. 

This will be resolved at https://github.com/novuhq/novu/pull/4946

Your idea about enabling immediate firing at 5-minute intervals sounds interesting and potentially useful. However, I believe it might be better to open a distinct ticket for this task. 
Implementing it could be complex and might lead to additional difficulties and confusion in the production process, in order to avoid potential errors, it should also be configurable.
