### ISSUE TITLE
[NV-3056] Enable to copy transactionId from the activity feed

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4757]
### What?

The user is unable to copy transactionId from the activity feed. In the activity feed page, we show notification items with `transactionId` and `suscriberId`.

![image.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/34ca7e52-10f6-4678-8c4f-bde5dd05488d/c5c9d8fa-69a1-4888-b87e-0c1322115531?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YxM2YxOTk2LWM5YjAtNGZlYS04ZWU3LTJjM2ZhZjZhODMyZC8zNGNhN2U1Mi0xMGY2LTQ2NzgtOGM0Zi1iZGU1ZGQwNTQ4OGQvYzVjOWQ4ZmEtNjlhMS00ODg4LWI4N2UtMGMxMzIyMTE1NTMxIiwiaWF0IjoxNjk5MDEzNzkxLCJleHAiOjE2OTkxMDAxOTF9._Kd02SKe8GN8NPft5i8i875HcaUkQeI469R5MSanGhY)

### Why? (Context)

When a user shares any issue with us, we need to check transactionId. But It is not an easy task from user's point of view to copy transactionId. When the user clicks on the item card. A modal is opened with job logs. So the only way is to copy from the developer console.
In my opinion, we can add a transaction ID copy option in the modal like this 

### Definition of Done

* Normal state: display Subscriber ID and Transaction ID without control "Copy"
* When a user hovers over a card in the activity feed the control "Copy" appears on the right side of the transaction ID and a Subscriber ID
* By clicking on the control "CopY" a user copies the Subscriber ID and Transaction ID to the clipboard

[Hover state - Crafting updates (Figma)](https://www.figma.com/file/mxViLXxtC0PnB0ehXDcafw/Crafting-updates?type=design&node-id=1561%3A7947&mode=dev&t=QfQgdk3zFB0BnfjC-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3056](https://linear.app/novu/issue/NV-3056/enable-to-copy-transactionid-from-the-activity-feed)</sub>

**Comment by jainpawan21** [comment]
Sure, @jainpawan21 although I think we have some issue with the issue syncing engine 😟

**Comment by jainpawan21** [comment]
Thanks Nikolay It will work for sure

**Comment by jainpawan21** [comment]
Hey @jainpawan21, I simplified the UI that you proposed a little bit. I think for now we need to display copy control on the hover over a card, please see the attached picture. This should help you to copy the IDs for now.

**Comment by jainpawan21** [comment]
@nikolay 
Reference:- [Discord Conversation](https://discord.com/channels/895029566685462578/1088881338192498748/1166333962113789962)

loom:- [https://www.loom.com/share/efdeebe8a6af4186918198bd332c726b](https://www.loom.com/share/efdeebe8a6af4186918198bd332c726b)

**Comment by michaldziuba03** [comment]
You can assign me @jainpawan21

**Comment by tquocanvn** [comment]
@jainpawan21 

Please help to review PR: https://github.com/novuhq/novu/pull/4761

**Comment by michaldziuba03** [comment]
@tquocanvn raising PR without being assigned especially when someone before is willing to handle issue is a bit asshole move.

**Comment by jainpawan21** [comment]
@tquocanvn 
Please wait for assignment before creating PR
if some has already commented before.
We appreciate your interest in contribution but please make sure you are following our code of conduct.

**Comment by Cliftonz** [comment]
@michaldziuba03 any update here?

**Comment by michaldziuba03** [comment]
@Cliftonz recently im busy with exams, so reassign this is issue to @tquocanvn and review their PR.
