### ISSUE TITLE
🐛 Bug Report: Node SDK ITopicPayload Has Wrong Type

### ISSUE THREAD

**Issue by Khongchai** [novuhq/novu#4770]
### 📜 Description

When calling `novu.topics.create(...)`, the documentation and the backend code says all parameters are required, but the types in the typescript sdk is saying everything is optional

<img width="639" alt="image" src="https://github.com/novuhq/novu/assets/56601823/56abb1da-ff9e-49d4-ae71-488e4a07c16f">

https://github.com/novuhq/novu/blob/c40182938a1b2d0e62ecee9acce7e32863370f8b/packages/node/src/lib/topics/topic.interface.ts#L21

### 👟 Reproduction steps

<img width="1009" alt="image" src="https://github.com/novuhq/novu/assets/56601823/93f6e54c-d94e-4765-b64a-c95a0f637be4">

Use this curl command, replace the apikey and remove either `key` or `name`. You will get an error like the attached screenshot. If this is correct, then the node sdk should change its type to match.

```curl
curl --location 'http://localhost:5001/v1/topics' \
--header 'Authorization: ApiKey 4775389efc0ef5e2362774efc7938b80' \
--header 'Content-Type: application/json' \
--data '{
  "name": "something sdfsd",
  "key": "something sdfsd"
}'
```

### 👍 Expected behavior

Either backend and documentation update `key` and `name` to be optional, or the node sdk change its typescript type to be mandatory.

### 👎 Actual Behavior with Screenshots

<img width="1009" alt="image" src="https://github.com/novuhq/novu/assets/56601823/93f6e54c-d94e-4765-b64a-c95a0f637be4">

### Novu version

0.17.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by peoray** [comment]
picking this up :)

**Comment by nick2432** [comment]
can i work on this?
