### ISSUE TITLE
🚀 Feature: add nodejs sdk methods for organization apis

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4775]
### 🔖 Feature description

We recently made organizations apis public and accessible using API keys and nodejs methods are missing for these apis

https://api.novu.co/api#/Organizations/OrganizationController_createOrganization

### 🎤 Why is this feature needed ?

So that these apis can be accessed using nodejs SDK methods

### ✌️ How do you aim to achieve this?

By adding organization methods in sdk

### 🔄️ Additional Information

1. Crete required DTOs and interfaces
2. Add required tests
3. Document in readme.md

Take subscriber methods as reference
https://github.com/novuhq/novu/blob/next/packages/node/src/lib/subscribers/subscribers.ts

Take documentation for subscriber as reference
https://github.com/novuhq/novu/blob/next/packages/node/README.md#subscribers

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
you can assign me

**Comment by jainpawan21** [comment]
> you can assign me

Assigned this to you!
