### ISSUE TITLE
🐛 Bug Report: We can have different color picker instead of this

### ISSUE THREAD

**Issue by sumitappinfoinc** [novuhq/novu#4778]
### 📜 Description

When we select color from color control

### 👟 Reproduction steps

Click on brand tab on the side bar
pick color from font color field

### 👍 Expected behavior

![image](https://github.com/novuhq/novu/assets/148742229/e29fd3c6-545e-4805-a458-f57252b00a06)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/148742229/e0011556-01dd-4d55-9704-552ef9711d78)

### Novu version

Novu Saas

### npm version

2.0

### node version

21.1.0

### 📃 Provide any additional context for the Bug.

--

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by michaldziuba03** [comment]
ok, but what is wrong with current color picker? For me it does its job.
