### ISSUE TITLE
[NV-3054] feature: add number format handlebar helper

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4821]
### What?

Novu supports handlebar in step editors

### Why? (Context)

Add a new handlebar helper to transform numbers
This handlebar helper should have these customizations:-

1. Choosing the separator
2. Customizing the no. of digits after which the separator should be added
3. Have customization for the decimal point and separator

Example: 

Code:- 

```
{{numberFormat number decimalSep="," decimalLength="2" thousandsSep="|"}}
```

Input:- 

```
{"number": 1000000000}
```

Output:-

```
1|000|000|000,00
```

### Definition of Done

1. Add `numberFormat` handlebar helper
2. Add test cases for this helper
3. Add in [this](https://docs.novu.co/content-creation-design/handlebars-helpers) docs similar to [groupBy](https://docs.novu.co/content-creation-design/handlebars-helpers#groupby) helper

Checkout this gist for Idea
[https://gist.github.com/DennyLoko/61882bc72176ca74a0f2](https://gist.github.com/DennyLoko/61882bc72176ca74a0f2)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3054](https://linear.app/novu/issue/NV-3054/feature-add-number-format-handlebar-helper)</sub>

**Comment by michaldziuba03** [comment]
You can assign me
