### ISSUE TITLE
📚 Docs Feedback: typo in react-quickstart backend

### ISSUE THREAD

**Issue by kunalznk** [novuhq/novu#4822]
### Duplicates

- [x] I have searched the existing issues

### Related page

https://github.com/novuhq/react-quickstart/blob/main/Back-end/index.js

### Kind of issue

Unclear explanations

### Issue description

- **I'm submitting a...**
   - [x] bug report
   - [ ] feature request
   - [ ] question about the decisions made in the repository
   - [ ] question about how to use this project

- **Summary**
- I had trouble setting up the example. The server port in the example is not the same as the actual port when I tried it.

- **Other information** 
- I tried adding Novu notifications using the React guide, but there's a problem. The server logging says the server is on one 3000, but it's actually running on a different 3001. 

### Context 🔦

Took me a while to set up the react-quickstart example

**Comment by michaldziuba03** [comment]
I think this issue should be moved to react quickstart guide repo.

**Comment by sumitsaurabh927** [comment]
> I think this issue should be moved to react quickstart guide repo.

I agree, can you create an issue on the [react quickstart guide repo](https://github.com/novuhq/react-quickstart), please @kunalznk ?

**Comment by kunalznk** [comment]
Sure
