### ISSUE TITLE
Upgrade @vonage/server-sdk to latest version 

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#4828]
## Why?
Version 2 of `@vonage/server-sdk` is using the vulnerable `request` package.

## What?
Updating the `@vonage/server-sdk` and modifying the code to meet the breaking changes in version 3.

## Definition of Done
- Verifying that all tests pass for the nexmo provider
- SMS delivery verification with Vonage is working (opening test account)

**Comment by michaldziuba03** [comment]
you can assign me

**Comment by michaldziuba03** [comment]
@Mutai-Gilbert it's already assigned

**Comment by scopsy** [comment]
Hi @michaldziuba03 let me know if you would love to be un-assigned from this 🙏

**Comment by scopsy** [comment]
@Mutai-Gilbert would you still love to pick this up?

**Comment by scopsy** [comment]
@sr-26 thank you!
