### ISSUE TITLE
📚 Docs Feedback: Correction of a spelling mistake.

### ISSUE THREAD

**Issue by Mutai-Gilbert** [novuhq/novu#4847]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/getting-started/concepts

### Kind of issue

Other

### Issue description

I was reading the documentation and I encountered a spelling mistake.

### Context 🔦

I'll love to help in correcting the documentation.

**Comment by Mutai-Gilbert** [comment]
Hello, Kindly assign me the issue. 

Thank you in advance.

**Comment by Atharva1723** [comment]
> Hello, Kindly assign me the issue.
> 
> Thank you in advance.

You should open this issue in this repo https://github.com/novuhq/docs as it is correct repository for the documentation

**Comment by Mutai-Gilbert** [comment]
Thank you. Let men do that.
