### ISSUE TITLE
🐛 Bug Report: Email Override is not working when using topics

### ISSUE THREAD

**Issue by vichustephen** [novuhq/novu#4856]
### 📜 Description

There is an issue when you try to **override** the **email channel** while triggering topics. The email text , sender name is not getting overridden. Instead it is still sending email using the **template** provided in the workflow 

### 👟 Reproduction steps

1. Create a workflow with one more steps. Then create one step for email. (configure the email provider before this step).
2. Configure the email with default template and provide the necessary details.
3. Now create a topic and some users
4. Now trigger the workflow with the created topic and add override for email. You can add **'from'** and **'text'** parameter (we don't need '**to**' parameter since we are triggering a topic).

### 👍 Expected behavior

The email must be delivered to the users who are in that topic with the **overridden text data**.  

### 👎 Actual Behavior with Screenshots

The email is delivered to the users in that topic but the content is from the **workflow template** and is not overridden.

Here is the workflow template:
<img width="623" alt="image" src="https://github.com/novuhq/novu/assets/22585439/02f9349e-d6ae-4bd4-8c1b-ba5ee6bfb925">

Here is the API trigger:

<img width="553" alt="image" src="https://github.com/novuhq/novu/assets/22585439/c00b083c-3f6a-4312-b5fa-25e17a75b8e1">

Here is the email I got:
<img width="515" alt="image" src="https://github.com/novuhq/novu/assets/22585439/9bb6fee5-c182-4c7c-961c-cf004afb1ce7">

### Novu version

0.19.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vichustephen** [comment]
Hi @jainpawan21. It seems like this bug is not exactly a bug. To put it simply,  the context of the issue i had was "not able to override the email content". My usecase is like this:

I have a **workflow with one email channel step**. I have a set of processes say 100 processes for which I need to send email to my clients. But ofcourse I cannot create **100s of workflow email templates**. I would like to use one workflow and I will override the content based on the process. Am I missing something here ?. 
I have gone through the code. The bug mentioned above is not a bug. Simple because the text override does not override the content for all email clients. There is supposed to be an **override option for HTML**. Because text content is only used for email clients that does not support html content.

I also would like to work on this feature or discuss about how to proceed and approach this. Please let me know I'm wrong or missing something here

**Comment by jainpawan21** [comment]
Hi @vichustephen 

Yeah you are correct. html property should also be there in overrides.
I see you are interested to contribute. Feel free to create a PR
