### ISSUE TITLE
[NV-3199] feature: add integrationIdentifier field in node sdk

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4874]
### What?

As per this [API](https://docs.novu.co/api-reference/subscribers/update-subscriber-credentials), While updating credentials of provider for subscriber, `integrationIdentifier` filed can be send to select integration.
This field enables to choose for which integration, credentials can be updated

### Why? (Context)

Add this new field in nodejs SDK method `setCredentials`

### Definition of Done

1. Add `integrationIdentifier` optional field in nodejs SDK
2. Update `setCredentials` documentation in nodejs readme 
3. Update this in API reference and corresponding places at documentation

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3199](https://linear.app/novu/issue/NV-3199/feature-add-integrationidentifier-field-in-node-sdk)</sub>

**Comment by AlexVCS** [comment]
hi, I'd like to work on this issue. can you assign it to me please?

**Comment by namrata18s** [comment]
Hey @jainpawan21  ,can I work on this issue. Will do a PR soon. Thankyou!

**Comment by jainpawan21** [comment]
Sure @AlexVCS I am assigning this to you

**Comment by jainpawan21** [comment]
> Hey @jainpawan21 ,can I work on this issue. Will do a PR soon. Thankyou!

Thanks for your interest. Let me know If you want to work on any other issue

**Comment by dhruvgupta0503** [comment]
hey can i work on this issue

**Comment by Prashant-dot1** [comment]
Hi @jainpawan21 , I have raised a PR for this feature. Please look into it and let me know if I missed something

**Comment by jainpawan21** [comment]
@Prashant-dot1 
I merged your above PR.
Kindly follow our guidelines. Please ask for issue assignment and wait before starting to work on it if multiple people are interested. 
One person was already assigned to this issue and have raised a draft PR

**Comment by AlexVCS** [comment]
Why did you let that get merged in then? Aren't you allowing the behavior that's not written out in the guidelines?
