### ISSUE TITLE
🐛 Bug Report: tenant add button is not always in the same location

### ISSUE THREAD

**Issue by SebastianStehle** [novuhq/novu#4886]
### 📜 Description

Very small design issue. The add button is not always add the same location:

![Untitled](https://github.com/novuhq/novu/assets/1236435/5e61aaef-16e9-4840-a074-b8f5c03e1ada)

In general the left padding of the elements within a page are not consistent. I have seen 24px, 25px, 30px...

### 👟 Reproduction steps

Just go to the pages.

### 👍 Expected behavior

Should be aligned.

### 👎 Actual Behavior with Screenshots

See above

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by nick2432** [comment]
can i work on this?

**Comment by sumitsaurabh927** [comment]
sure @nick2432 assigning this to you

**Comment by nick2432** [comment]
i can not able to locate tenants when i run novu locally
![Screenshot from 2023-12-03 16-54-15](https://github.com/novuhq/novu/assets/77477551/024cb994-b45d-4704-bb38-f86987adc367)

**Comment by michaldziuba03** [comment]
@nick2432 there is feature flag: `IS_MULTI_TENANCY_ENABLED `.

Set this to "true" in env files for API and WEB.

https://docs.novu.co/community/feature-flags
