### ISSUE TITLE
🐛 Bug Report: Triggering an Event might lead to an outdated Error Messages (when using outdated request)

### ISSUE THREAD

**Issue by JonasDoe** [novuhq/novu#4891]
### 📜 Description

When triggering an Event with an outdated request structure, I get an error suggesting the outdates request structure is still expected. Here's a sketch:
```JSON
{
    "name": "{{workflow}}",
    "to": [{
        "type": "Topic",
        "topicKey": "{{topicKey}}"    
    }],
    "payload": {
      "customVariables": "Hello World",
      "from": "Trigger event"
    },
    "transactionId": "{{triggerEventTransactionId}}",
    "actor": {
        "subscriberId:": "{{subscriberIdTest}}",
    }
  }
```
The `actor` is invalid, according to the [documentation](https://docs.novu.co/api-reference/events/trigger-event) it should be a `string`, not an `object`. The error response still suggests otherwise, though:
```json
{
    "message": [
        "actor.subscriberId should not be null or undefined",
        "actor.subscriberId must be a string"
    ],
    "error": "Bad Request",
    "statusCode": 400
}
```

### 👟 Reproduction steps

Just run a `POST` request against `/events/trigger` which is valid except for the `actor`.

### 👍 Expected behavior

I'ld expect an error response like
```JSON
{
    "message": [
        "actor must be a string"
    ],
    "error": "Bad Request",
    "statusCode": 400
}
```

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/10669876/a2c0f651-03c8-496d-809b-0a982f3988a0)

### Novu version

NOVU self-hosted `v0.21.0`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
Hi @JonasDoe 
I see you are using postman variables as value in `actor.subscriberId`. Could you double check if `jwt_test` is a valid string or not. You can check postman console of request and response.

**Comment by JonasDoe** [comment]
> Hi @JonasDoe I see you are using postman variables as value in `actor.subscriberId`. Could you double check if `jwt_test` is a valid string or not. You can check postman console of request and response.

Hey, you're right that the screenshot contained with `jwt_test` was the wrong variable, I didn't want to send the JWT. That said, it's just faulty in the screenshot, and the error isn't affected by that: Here's a request body from the console (after I fixed that variable in Postman):
```
{
    "name": "my-workflow",
    "to": [
        {
            "type": "Topic",
            "topicKey": "U:950273ef-da09-4ba0-9066-07343916e874:ChatChannel2"
        }
    ],
    "payload": {
        "customVariables": "Hello World",
        "from": "Trigger event"
    },
    "transactionId": "0b540cf-7fa5-11ee-bf40-b42e99f4bbda",
    "actor": {
        "subscriberID": "70fe98bd-7145-4ad3-aba3-b9095fcf82ce"
    }
}
```

**Comment by JonasDoe** [comment]
Hey, you're right, and when playing around with it just now, I introduced another error. Now, it's actually working. What I don't get is why the [documentation](https://docs.novu.co/api-reference/events/trigger-event) claims it must be a `String`. Are both approaches supported, and one of them is a deprecated variant?

**Comment by JonasDoe** [comment]
Well, either I was blind before, or it was fixed. But I see that the documenation now reflects both cases - `subscriberId` being a `string` or an `object`. :)
