### ISSUE TITLE
🚀 Feature: Expose Public API to Invalidate Cache

### ISSUE THREAD

**Issue by Khongchai** [novuhq/novu#4907]
### 🔖 Feature description

Every time I make changes to notification templates, I have to manually invalidate the entity cache in redis in order for the next queries to receive fresh template data. It'd be nice to have a public API that allows us to invalidate specific caches.

For now, I think this is the part that intercepts my get template detail call and return cached data 

https://github.com/novuhq/novu/blob/next/apps/worker/src/app/workflow/usecases/send-message/send-message.usecase.ts#L314

### 🎤 Why is this feature needed ?

My use case is that we want the data to reflect immediately every time we edit a template. Right now, we have to go into redis and delete these manually:

<img width="425" alt="image" src="https://github.com/novuhq/novu/assets/56601823/c5958718-1b9d-4653-b057-ccff4e5ebb6e">

### ✌️ How do you aim to achieve this?

PUT notification-templates/{template-id} should invalidate the entity cache.

We could, of course, invalidate the keys by interacting with redis API directly, but we don't want to shoot ourselves in the foot later when the implementation details  -- the keys -- change.

**_Edit: I noticed that I said `PUT` endpoint here. That's not the case. I forgot that we were actually promoting the changes not calling the put endpoint directly because we had problems with the production, not development environment._**

### 🔄️ Additional Information

I'm referring to the production environment. We are self-hosting. We have no use of the development environment; all of our environments, dev, staging, and prod use different databases.

Found a similar issue, but it was closed already due to inactivity.

https://github.com/novuhq/novu/issues/3520

Please let me know if there already is an existing solution or if I have missed something.

Appreciate the work y'all are doing. Thanks!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
@djabarovgeorge

**Comment by djabarovgeorge** [comment]
Hi @Khongchai, appreciate you flagging this. From what I've observed, we invalidate during a [PUT request](https://github.com/novuhq/novu/blob/a00974bd85ac6fbd3bfc1d57917df3c981ef78f4/apps/api/src/app/workflows/usecases/update-notification-template/update-notification-template.usecase.ts#L147). Could you provide the specific steps you take to replicate the issue, requiring the need for manual invalidation?

**Comment by Khongchai** [comment]
Hi @djabarovgeorge, thank you for the reply.

 I will try to reproduce this sometime tomorrow if I am able and will get back to you. If I remember correctly, it happened to us in the `production` environment. We made some changes to one of the in app notification templates a development workflow and then applied the changes to prod env. I just quickly browsed the changes controller and related files and didn't see any cache invalidation there. Could it be because of this? I could be totally wrong though.

**Comment by Cliftonz** [comment]
@Khongchai Where you able to validate this?

**Comment by Khongchai** [comment]
@Cliftonz Hey, sorry for the long delay. I haven't had time to go over this yet. I'll close this issue for now to unclutter your issues tab.
