### ISSUE TITLE
[NV-3237] Intercom chat bubble shouldn't be visible

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4912]
### Reproduction Steps
1. Navigate to the Integrations page.
2. Click on the existing integration from the list to edit.
3. Close the Integration Sidebar.
4. The Intercom chat bubble will appear after.

### Expected Behaviour
- the Intercom chat bubble won't show
- the Intercom popover should be only controlled by the help button "?" from the header navigation

### Additional info
For the local development, you would need to update the INTERCOM_APP_ID.
https://github.com/novuhq/novu/blob/ccd52a27f1914f04577b998b9afc84da8a8e8133/apps/web/src/config/index.ts#L45

### Screenshots
![image](https://github.com/novuhq/novu/assets/2607232/3cce5153-9ad0-4bbd-98e3-19abbccda0e6)

https://github.com/novuhq/novu/assets/2607232/caeca8c7-ea0a-42d9-a880-ca4cba7d01be

**Comment by zt4ff** [comment]
@LetItRock This is my time contributing to the project. Can you assign me to this please?

**Comment by LetItRock** [comment]
> @LetItRock This is my time contributing to the project. Can you assign me to this please?

of course @zt4ff! if anything needed let me know ;)

**Comment by learner-mohit** [comment]
@LetItRock I had been working on this issue. Kindly, assign to me. 

https://github.com/novuhq/novu/assets/151846514/693ff0ed-aa8b-4f16-b115-ffc6656bb14e
