### ISSUE TITLE
📚 Docs Feedback: Trying to go through docs and Something is not clear on subscriber id.

### ISSUE THREAD

**Issue by Qodestackr** [novuhq/novu#4927]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://web.novu.co/settings, https://web.novu.co/subscribers

### Kind of issue

Unclear explanations

### Issue description

I was looking for subscriber id but I only have(API Key, Application ID, and Environment ID) ... and it appears that going to subscribers tab on dashboard does not create Subscriber ID automatically

Which values do I need work on?

### Context 🔦

Expected Behavior:

I expected to find clear documentation or a specific API endpoint for obtaining or generating the subscriber ID.

**Comment by jainpawan21** [comment]
@Qodestackr 

Checkout this documentation to learn the concept of subscribers and subscriberId
https://docs.novu.co/subscribers/subscribers
