### ISSUE TITLE
🐛 Bug Report: Digests with filter behave improperly

### ISSUE THREAD

**Issue by MasonD** [novuhq/novu#4957]
### 📜 Description

When a digest has a filter attached and that filter succeeds, messages are sent immediately, resulting in one message per trigger with each message having a digest of the triggers leading up to it.

### 👟 Reproduction steps

This branch https://github.com/MasonD/novu/tree/digest-filter-failing-test has a failing test "should digest events within time interval with filter".

### 👍 Expected behavior

Digests behave identically to when they have no filter attached when they have a filter that passes. The test I wrote passes.

### 👎 Actual Behavior with Screenshots

The test I wrote fails. Digests send one message per trigger when they have a filter even when the filter passes.

### Novu version

next (commit cf7ec7d1d327d82ac24d81444015d3c94dcd8a8b)

### npm version

8.11.0

### node version

v16.15.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
@davidsoderberg

**Comment by ainouzgali** [comment]
Hi @MasonD , thanks for reporting!! I pushed a fix into next, let me know if you still encounter problems :)
