### ISSUE TITLE
🚀 Feature: Support One-way Voice Channel

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4973]
### 🔖 Feature description

Novu is a great system for centralized notification and messaging all in one place.

We are interested in extending our platform to support more types of channels.

Some of the Voice providers would include
- https://www.telesign.com/products/voice-api
- https://www.twilio.com/en-us/voice/api
- etc

### 🎤 Why is this feature needed ?

We would like to have this feature to support more one way messaging channels in Novu

### ✌️ How do you aim to achieve this?

Community Contributions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by learner-mohit** [comment]
@Cliftonz This seems a great step for a11y, could you assign me this one 😇

**Comment by jainpawan21** [comment]
@Cliftonz I see this issue is for adding a new channel requiring some brainstorming.

@learner-mohit would you like to share your ideas on how you want to tackle this issue

**Comment by learner-mohit** [comment]
@jainpawan21 Right now, I am adding a new channel type called VOICE which will have Twilio and Telesign as two options.

Currently, I am working on Twilio's Voice API, it is very similar to Twilio's SMS API. It takes three fields: 
twiML url: this is the url where TwiML(twilio markup language) is hosted. it will have an xml file telling what to do like [here](https://demo.twilio.com/docs/voice.xml), the xml file reads a line "Thanks for trying our documentation. Enjoy!" and then plays the classic.mp3 file after calling the recipient. Developers can create new TwiML files using Twilio's TwiML bin feature provided on their console.
to: it will be receiver's mobile number
from: it will be twilio's rented mobile number

further, a new icon for VOICE channel needs to be put @novu/design-systems and VOICE needs to be added prompt.js of hygen generator, also docs need to be updated.  I'll do that.

I haven't checked Telesign yet. If you have any suggestion, we can discuss and get to a better solution.

**Comment by learner-mohit** [comment]
@jainpawan21 @Cliftonz this will take a lot of refactoring if we introduce new IVoiceProvider. for eg, if we just find "IEmailProvider | ISmsProvider | IChatProvider | IPushProvider" in code, then it is present in lots of places. Is there any other way to go round this. Is there a better way to onboard a new channel?

**Comment by mahendraHegde** [comment]
@Cliftonz  i will add a new voice channel, can you assign this to me please?

**Comment by mahendraHegde** [comment]
@Cliftonz  i'm thinking to add only twillio voice as part of this PR, would like to do telesign as separate PR/issue, because I was checking telesign api, and its not a straightforward flow(verify(with voice) api is, but not the voice api), it requires us to setup a webhook to handle the call accepted action to play messages, so i feel its better to separate out that implementation. lmk what do you think?

**Comment by Cliftonz** [comment]
> @Cliftonz i'm thinking to add only twillio voice as part of this PR, would like to do telesign as separate PR/issue, because I was checking telesign api, and its not a straightforward flow(verify(with voice) api is, but not the voice api), it requires us to setup a webhook to handle the call accepted action to play messages, so i feel its better to separate out that implementation. lmk what do you think?

I agree, I think twillio voice would be enough for the initial version. 

Just to quickly list, here is the general steps to do.
- Add a new type in the channel enum
- Add a integration section for that type in the fronted
- Add a workflow node for that channel type.
- Create a editor page for that channel type.
- Create a send message usecase in the backend for that channel type.

In addition, I also want to add that each voice system has its own data format (xml, json, etc) and when building the data representation for the phone call, we would need to build some intermediary data representation(idr) so it can be converted in each provider by passing the idr in the parms for the functions call. Inside the provider it would then convert it to the representation for that provider. 

Let us know if you need any assistance.

**Comment by alexkreidler** [comment]
Any updates on this? There a lot of AI voice calling providers like [Retell](https://www.retellai.com/) that can do outbound calling + intelligently handle a conversation - would be useful to have option to integrate them.
