### ISSUE TITLE
[NV-3300] most recent change should be on the top in changes page

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#5006]
steps to reproduce:-

1. Create a new workflow or update an existing workflow
2. Check if there is new pending change in changes page
3. update few more workflows
4. Now on changes page, changes are list in order of last updated date having last updated change at the top

Most recently updated change should be on the top. As a user I want to promote the most recent change only. To get to that change, I have to use pagination and go till the last item.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3300](https://linear.app/novu/issue/NV-3300/most-recent-change-should-be-on-the-top-in-changes-page)</sub>

**Comment by Ujjwal55** [comment]
@jainpawan21 can I take this issue? Please assign it to me

**Comment by sudhanshugautam2911** [comment]
@jainpawan21 I would like to work on this issue. Please assign me

**Comment by jainpawan21** [comment]
> @jainpawan21 can I take this issue? Please assign it to me

@Ujjwal55 Assigning this to you 🙂

**Comment by m-Chetan** [comment]
Hello @jainpawan21 I have already worked on this issue. Could you please merge it if everything is fine?

**Comment by Ujjwal55** [comment]
> > @jainpawan21 can I take this issue? Please assign it to me
> 
> @Ujjwal55 Assigning this to you 🙂

Please review this pr https://github.com/novuhq/novu/pull/5010 @jainpawan21

**Comment by mahendraHegde** [comment]
@Ujjwal55  @m-Chetan  you both followed the same approach of sorting in mem in the UI, but i believe it should be done on `/changes` api side while querying DB.
@jainpawan21  correct me if i'm wrong.

**Comment by Ujjwal55** [comment]
> @Ujjwal55 @m-Chetan you both followed the same approach of sorting in mem in the UI, but i believe it should be done on `/changes` api side while querying DB. @jainpawan21 correct me if i'm wrong.

Okk, I'll do it

**Comment by m-Chetan** [comment]
@mahendraHegde sure we can fetch it from DB in descending order from api side

**Comment by m-Chetan** [comment]
@jainpawan21 I have made changes in the PR to fetch the changes from api side while querying DB.
If all fine could you please merge it

**Comment by scopsy** [comment]
@Ujjwal55 are you still on it? Or shouldIassign @m-Chetan for this issue?

**Comment by Ujjwal55** [comment]
> @mahendraHegde sure we can fetch it from DB in descending order from api side

@m-Chetan this issue has been assigned to me, so you can work on other open issues.

**Comment by Ujjwal55** [comment]
> @Ujjwal55 are you still on it? Or shouldIassign @m-Chetan for this issue?

Yes I am working on this

**Comment by Ujjwal55** [comment]
@scopsy I have done the change, you can review it. But I wanted to ask one thing whenever I did any change to the change.repository.ts file, the server the change didn't reflected even if I empty the whole file but this was not the case with files inside app directory. Can you help why it maybe the issue?

**Comment by scopsy** [comment]
@Ujjwal55 dal is a separate package that you need to build. Have you run a build in its package folder?

**Comment by Ujjwal55** [comment]
> @Ujjwal55 dal is a separate package that you need to build. Have you run a build in its package folder?

Not yet, now I know why it wasn't running
