### ISSUE TITLE
Change Providers Constructor Into An Interface

### ISSUE THREAD

**Issue by nevo-david** [novuhq/novu#501]
**Describe the bug**
Today except for SES and EmailJS, providers don't have an interface.
You can import the interface in different libraries, and you need to copy the object that might change in the future.

**To Reproduce**
Try to import any provider config interface

**Expected behavior**
Convert the provider's object type into an interface

**Comment by carlaulloa** [comment]
Can I work on this?

**Comment by carlaulloa** [comment]
Hi. Can I work on this?
