### ISSUE TITLE
🐛 Bug Report: Unable to increase widget height

### ISSUE THREAD

**Issue by katyaterletskaya** [novuhq/novu#5013]
### 📜 Description

While trying to adjust the widget's height using CSS styles, I faced an issue where the expected increase in height did not occur as intended

### 👟 Reproduction steps

```
<NovuProvider
   subscriberId={SUBSCRIBER_ID}
   applicationIdentifier={APPLICATION_IDENTIFIER}
    styles={{
       notifications: {
          root: { height: "500px" },
       },
    }}
>
   <PopoverNotificationCenter>
       {({ unseenCount }) => <NotificationBell unseenCount={unseenCount} />}
   </PopoverNotificationCenter>
</NovuProvider>
```

### 👍 Expected behavior

The widget's height should increase according to the specified CSS styles

### 👎 Actual Behavior with Screenshots

The scrollable area is limited to 400px due to the specified height in the InfiniteScroll component

<img width="591" alt="Screenshot 2023-12-21 at 15 48 26" src="https://github.com/novuhq/novu/assets/58933206/e8332179-de93-4519-9a56-7d12f812c1d3">

### Novu version

0.22.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
@katyaterletskaya do you think we can some how restructure this so that updating this Div, affects also the outer layer?

**Comment by katyaterletskaya** [comment]
@scopsy it would be possible to override the height value in styles by using a [scrollable target approach](https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/src/stories/ScrollableTargetInfScroll.tsx)
