### ISSUE TITLE
🐛 Bug Report: translations are missing in the notification centre

### ISSUE THREAD

**Issue by parsch** [novuhq/novu#5015]
### 📜 Description

While https://github.com/novuhq/novu/blob/main/packages/notification-center/src/i18n/languages/en.ts contains 8 strings, most other languages contain 5 strings only. The missing strings are `removeMessage`, `markAsRead` and `markAsUnRead`.

This leads to language confusions in the notification centre, for example with `i18n="de"` showing a mixture of German and English strings.

I could provide following translations: `da, de, fr, it`

### 👟 Reproduction steps

Add a different language than English to the `NovuProvider`:

```
<NovuProvider i18n="de">
  <PopoverNotificationCenter>
    {({ unseenCount }) => <NotificationBell unseenCount={unseenCount} />}
  </PopoverNotificationCenter>
</NovuProvider>
```

### 👍 Expected behavior

All translations within the notification centre should be in German.

### 👎 Actual Behavior with Screenshots

Translations for `removeMessage`, `markAsRead` and `markAsUnRead` are missing and the English strings are being displayed instead.

<img width="438" alt="Bildschirmfoto 2023-12-21 um 14 52 39" src="https://github.com/novuhq/novu/assets/206830/d41e54fc-a173-42f1-be59-eb3f3ab4cbde">

### Novu version

Novu SaaS

### npm version

NA

### node version

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
@parsch if I understand correctly you are willing to help with those languages? Assigning you 🙏

**Comment by parsch** [comment]
@scopsy I'll start with an overview of the languages for which the strings mentioned are missing or present (all respective files are located at `/packages/notification-center/src/i18n/languages`):

- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`
- [ ] `af`

**Comment by parsch** [comment]
@scopsy out of curiosity: how did you come up with all existing translations? I'm happy to help with this issue, just wondering how I could support this beyond updating languages I'm somehow familiar with.

**Comment by scopsy** [comment]
All translations are contributed by community members, so it might take a while to get to full availability on all languages 😃

**Comment by sieratwb** [comment]
I can provide a translation in Simplified Chinese but I'm not a developer and don't know how to contribute, maybe someone can do it?

{
  notifications: '通知中心',
  markAllAsRead: '将所有设为已读',
  poweredBy: '由{Novu}作为技术支持',
  settings: '设置',
  removeMessage: '移除消息',
  markAsRead: '设为已读',
  markAsUnRead: '设为未读',
  noNewNotification: '目前没有新消息',
}

**Comment by parsch** [comment]
Thanks @sieratwb, I'll integrate that.
