### ISSUE TITLE
Widget cypress test fail

### ISSUE THREAD

**Issue by djabarovgeorge** [novuhq/novu#503]
**Describe the bug**
Whenever you run 'notifications-list.spec' on widget with 'cypress:run' the test fails while on 'cypress:open' they succeed.

**To Reproduce**
1. Go to widget pakage.json 
2. Click on Run 'cypress:run' script command.
3. Scroll down to console
4. See the error.

**Expected behavior**
The tests pass successfully.

**Screenshots**
Screenshot of the error:

![image](https://user-images.githubusercontent.com/39195835/165136960-b00c2342-3547-4dc2-a1ee-e92c598d871f.png)

Screenshot from cypress:

![Notifications List -- should lazy-load notifications on scroll (failed)](https://user-images.githubusercontent.com/39195835/165137052-9476c0a7-9745-4d82-b65d-d383e7922329.png)

**Details (please complete the following information):**
 - OS: [e.g. Mac]
 - Node Version [e.g. v14.18.3]
 - Cypress Version [e.g. v7.7.0]
 
**Additional context**
LOCAL RUN
If we compare the cypress run types we can see the difference between 'cypress:run'(on the left) and  'cypress:open'(on the right)
Looks like on the cypress:run are multiple requests for page 0, and on the cypress:open there aren't.

![image](https://user-images.githubusercontent.com/39195835/165137678-8df3a65e-7fd0-4e75-8c5e-6c48e0c89751.png)

**Comment by ninjadev101** [comment]
A question! Why still use cypress v7.7.0???

**Comment by scopsy** [comment]
@ninjadev101 haha good question. We only updated the web project once you upgraded it :)

**Comment by ninjadev101** [comment]
Damn. I will upgrade it then.

**Comment by djabarovgeorge** [comment]
Hey @ninjadev101, It is strange on my machine they passed successfully.
Could you share the errors you get?

**Comment by ninjadev101** [comment]
@djabarovgeorge 
![image](https://user-images.githubusercontent.com/52289096/166235029-46347b09-36c4-4fd8-a3ef-7bc9397f3f02.png)

**Comment by ninjadev101** [comment]
@djabarovgeorge @scopsy 
I think time out happens because of too many requests from `packages/notification-center`

![image](https://user-images.githubusercontent.com/52289096/166237180-009513ea-0a33-425f-8a74-585c52ff4030.png)

**Comment by djabarovgeorge** [comment]
Hey @ninjadev101, I tend to agree the strange thing is that I could not reproduce the issue on development or cypress:open, the only time it failed for me was on cypress:run

**Comment by ninjadev101** [comment]
Sometimes it works but it fails often... I console logged at that case, and in the notification list component, the `hasNextPage` prop was false...

**Comment by scopsy** [comment]
Closing this as it looks like for now it passes with latest cypress version
