### ISSUE TITLE
🐛 Bug Report: When using react-query yourself you cant use NovuProvider because it overrrides the queryclient

### ISSUE THREAD

**Issue by TNAJanssen** [novuhq/novu#5030]
### 📜 Description

When using react-query yourself you cant use NovuProvider because it overrrides the queryclient

### 👟 Reproduction steps

1. install react-query and novu
2. create a query client and add query client provider
3. render novu provider
4. add child component and use react query
5. it uses the wrong query client

### 👍 Expected behavior

It should not override the query client, or allow to set a flag that a query client is already present.

### 👎 Actual Behavior with Screenshots

It overrides the query client

### Novu version

Novu SaaS

### npm version

NA

### node version

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by FinnWoelm** [comment]
We just ran into the same issue. Ideally, novu should be creating the query client with a custom context, so that it does not "pollute" the default react query context: https://tanstack.com/query/v4/docs/framework/react/reference/useQueryClient
