### ISSUE TITLE
🚀 Feature: Add the ability to specify SNS origination number when publishing

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu#5033]
### 🔖 Feature description

Currently, the publish command for SNS looks like the following:
(https://github.com/novuhq/novu/blob/next/providers/sns/src/lib/sns.provider.ts#L31)

```js
  const publish = new PublishCommand({
    PhoneNumber: to,
    Message: content,
  });
```
It is my recommendation that a new field be added in the configuration: `Origination Number`.

This will allow users to assign a particular integration in Novu with a specified number from AWS SNS.

Potential code solution:

```js

...
let publishCommand: PublishCommand;

if (this.config.originationNumber) {
      publishCommand = new PublishCommand({
      PhoneNumber: to,
      Message: content,
      MessageAttributes: {
          'AWS.SNS.SMS.SenderID': {
            DataType: 'String',
            StringValue: this.config.originationNumber // Specify your origination number here
          }
        }
    });
} else {
// existing publish command
      publishCommand = new PublishCommand({
        PhoneNumber: to,
        Message: content,
      });
}

const snsResponse = await this.client.send(publishCommand);
...

```

Research:
https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sns/command/PublishCommand/

### 🎤 Why is this feature needed ?

In my use-case, we use 1 number to send out general ambulance assignments and communications. We use another number to send out emergency communications.

### ✌️ How do you aim to achieve this?

Add a new option in the UI/API that will allow users to input their origination number. If set, it will add that number to the configuration. This would be optional so there would be no downtime on upgrades for existing implementations.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Thank you @wh1337 🙏
