### ISSUE TITLE
🐛 Bug Report: why can I add the same exact subscriber?

### ISSUE THREAD

**Issue by uzbekbear** [novuhq/novu#5036]
### 📜 Description

.

### 👟 Reproduction steps

.

### 👍 Expected behavior

I used the documentation and created a subscriber like so
```
subscriber = SubscriberDto(
   subscriber_id=your_subscriber_id,
   email="a@b.com",
   first_name="John",
   last_name="Doe"
)

SubscriberApi().create(subscriber)
```

the sucscriber was created successfully in the dashboard but I was then able to run the same code and it seems the subscriber was created successfully again. I would expect to get a conflict error considering the subscriber ID is the same and it's unique

### 👎 Actual Behavior with Screenshots

created the subscriber with no issue

### Novu version

1.11.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
as far as I remember Novu updates subscriber if already exists, so I would say it's performing upsert.

Do you have two subscribers with same id in the Novu dasboard or one?

**Comment by uzbekbear** [comment]
> @uzbekbear as far as I remember Novu updates subscriber if already exists, so I would say it's performing upsert.
> 
> Do you have two subscribers with same id in the Novu dasboard or one?

I have one
