### ISSUE TITLE
🐛 Bug Report: Docker containers always try to build enterprise version

### ISSUE THREAD

**Issue by MasonD** [novuhq/novu#5052]
### 📜 Description

The dockerfiles use the syntax:

```
RUN if [ -n '${BULL_MQ_PRO_NPM_TOKEN}' ] ; then echo 'Building with Enterprise Edition of Novu'; rm -f .npmrc ; cp .npmrc-cloud .npmrc ; fi
```

But since single quotes are used in the if, string interpolation isn't performed, and the literal string '${BULL_MQ_PRO_NPM_TOKEN}' is always non-null. Thus the npmrc swap is always performed.

### 👟 Reproduction steps

`pnpm docker:build` without BULL_MQ_PRO_NPM_TOKEN set. Observe the build output echo "Building with Enterprise Edition of Novu"

### 👍 Expected behavior

~It should use double quotes instead of single so it actually works as intended.~

It should securely leverage the Bullmq pro token to correctly identify if we are building the community or enterprise edition.

### Novu version

0\.23.0

### npm version

n/a

### node version

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR! Ping me if it's more convenient for me to make those couple quote changes and submit a PR :)

**Comment by scopsy** [comment]
@MasonD just to make sure that you are willing to help with this? Let me know if otherwise, I can un-assign and we will handle it internally 🙏

**Comment by MasonD** [comment]
I'm happy to do this, yeah. I'll have time to tackle it tomorrow if it's not something you're trying to push through asap.
