### ISSUE TITLE
🚀 Feature(self-hosting): AWS SES without access key when running in environment that assumes an IAM role

### ISSUE THREAD

**Issue by MasonD** [novuhq/novu#5054]
### 🔖 Feature description

When self-hosting in AWS, it's likely that the environment that is running the api and worker code are running somewhere that automatically assumes an IAM role. If this role has the correct (`ses:SendEmail` and `ses:SendRawEmail`) permissions, then creating an SESClient and providing *no* credentials results in the client picking up the role from its environment and not needing an access key. It'd be nice if we could opt in to using this method instead of providing an access key that Novu then stores in its database (even encrypted).

### 🎤 Why is this feature needed ?

Authenticating in this manner is more secure than creating an IAM user and managing an access key, and is generally the suggested method when operating inside the AWS ecosystem nowadays.

### ✌️ How do you aim to achieve this?

I've already tested it by modifying SESEmailProvider to check for a specific value of accessKeyId and secretAccessKey and omit the credentials key when instantiating the SESClient, and that's the minimal change required to get it to work (and it does work!). That's probably good enough, since this feature is pretty poweruser anyway and including an extra checkbox in the SES provider's settings seems like it'd worsen regular users' experience. 

The complication that needs to be solved is that this feature would likely need to be opt-in via env var and *also* only work if DISABLE_USER_REGISTRATION is enabled.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by bharathkumar01-k** [comment]
Willing to work on this feature can you assign this to me?

**Comment by scopsy** [comment]
@MasonD added you as an assignee 🙏

**Comment by dverzolla** [comment]
upvoting.
It could be implemented for all aws pieces that connect to aws services. Just remembering that `aws-sdk` has already implemented the control of this access to their services. The sdk understand the access fallbacks for several situations.

**Comment by MasonD** [comment]
Indeed, however care has to be taken to only enable this in certain circumstances, because having this be possible on a self-hosted novu instance accessible from the internet and forgetting to turn on DISABLE_USER_REGISTRATION means that anyone would be able to create a new account, add an SES provider and then send emails using your SES. I'll create a PR to allow interacting with Amazon services as I described, but we should probably have someone with security experience to double-check my work. I'll make sure it's opt-in, too.

**Comment by MasonD** [comment]
I'm not familiar with IRSA specifically, but a read of the documentation seems to suggest it's pretty similar to task roles in ECS? If so, then the issue would be that since the provider inherits the IAM role from the execution environment/container, if DISABLE_USER_REGISTRATION is not enabled and the API is open to the internet, anyone can create a new account, create a new SES integration and set it to using the container's IAM role. Therefore, anyone would be able to send messages using the permissions granted to the container. 

I'm assuming that this feature would be used exclusively in self-hosted novu instances intended to be used solely by the entity hosting the instance. They would want their Novu instance to be able to have SES/SNS providers authenticate using the IAM role granted to the containers running Novu, but don't intend for other entities to be able to create their own accounts and use the role. I'd rather preempt the foot-gun that would be and prevent this feature from being used without DISABLE_USER_REGISTRATION also enabled.

**Comment by dverzolla** [comment]
> I'm not familiar with IRSA specifically, but a read of the documentation seems to suggest it's pretty similar to task roles in ECS? If so, then the issue would be that since the provider would use the inherited IAM role from the execution environment/container, if DISABLE_USER_REGISTRATION is not enabled and the API is open to the internet, anyone could create a new account, create a new SES integration and set it to using the container's IAM role. Therefore, anyone would be able to send messages using the permissions granted to the container.


Yes, IRSA and Task Roles are similar in the context of `assume role`. 


> I'm assuming that this feature would be used exclusively in self-hosted novu instances intended to be used solely by the entity hosting the instance. They would want their Novu instance to be able to have SES/SNS providers authenticate using the IAM role granted to the containers running Novu, but don't intend for other entities to be able to create their own accounts and use the role. I'd rather preempt the foot-gun that would be and prevent this feature from being used without DISABLE_USER_REGISTRATION also enabled.

I understand what you explained, and these precautions measures sound really solid.

**Comment by MasonD** [comment]
In the interest of getting this flowing again since it seems at least one person would benefit from me pushing this upstream in a production-ready manner, I'll repeat a question here that I asked on Discord in hopes of reaching an answer. The logic to generate a config object for the aws sdks would be identical between all of the aws providers, so ideally all of the providers would share the same code there. I'd like some input on how to structure that. Should that just be a function exported from `@novu/stateless`, since that appears to be the package that providers put shared functionality in?

**Comment by liuwei2957** [comment]
@MasonD need your help， can you show me how you change the code？
