### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by Veeraops** [novuhq/novu#5074]
### 📜 Description

websocket is not failing. Due to this, new notification “In Application“ bell icon alert is not working.
Only After reloading the complete page from browser, these notifications work.

### 👟 Reproduction steps

WS docker process is running and new notification “In Application“ bell icon alert is not working.
Only After reloading the complete page from browser, these notifications work.

### 👍 Expected behavior

Without r reloading the complete page from browser need to be notifications worked

### 👎 Actual Behavior with Screenshots

New notification “In Application“ bell icon alert is not working.
Only After reloading the complete page from browser, these notifications work.

### Novu version

0.21

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by scopsy** [comment]
Hi [**Veeraops**](https://github.com/Veeraops)** **are you running this in self-hosting? If yes can you confirm that WS service is properly running in your environment?
