### ISSUE TITLE
Docker images require authorization.

### ISSUE THREAD

**Issue by isikhi** [novuhq/novu#512]
```
> docker-compose up
Pulling embed (ghcr.io/novuhq/novu/embed:latest)...
ERROR: Head "https://ghcr.io/v2/novuhq/novu/embed/manifests/latest": unauthorized
```

**Expected behavior**
I need to fetch the repo for development. So maybe we can release images to a public repo

**Comment by scopsy** [comment]
Thanks for the report @isikhi , looks like a config was missed. Made it public now, can you refetch?
Please note the docker-compose setup is still a work-in-progress if you will encounter any issues please let us know 🙏

**Comment by scopsy** [comment]
@marsouin could you please retry again, images should be published now
