### ISSUE TITLE
🐛 Bug Report: Styling Issue

### ISSUE THREAD

**Issue by pranshugupta54** [novuhq/novu#5150]
### 📜 Description

Cross button overlaps for integration 

### 👟 Reproduction steps

1) Goto https://web.novu.co/integrations
2) Click any Novu related (Email, chat) etc
![image](https://github.com/novuhq/novu/assets/76090263/5c0afc7c-bec9-4ae0-b6f0-9f8f4a6843cd)

### 👍 Expected behavior

proper spacing

### 👎 Actual Behavior with Screenshots

NA

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by gMabdullah** [comment]
@pranshugupta54 can you provide more details on which browser/screen size you are facing this issue.
