### ISSUE TITLE
🐛 Bug Report: Auto scroll to provider

### ISSUE THREAD

**Issue by pranshugupta54** [novuhq/novu#5151]
### 📜 Description

Automatically scrolling from Get-Started page to providers

### 👟 Reproduction steps

1) On clicking "change provider" for any of them
![image](https://github.com/novuhq/novu/assets/76090263/481f73e3-26a9-499e-a651-199aca3b79fc)

2) It takes to the top:
![image](https://github.com/novuhq/novu/assets/76090263/5859198e-3561-41ca-a74e-d4fb847d148c)

### 👍 Expected behavior

It should automatically scroll to the section example:
clicking on "Change provider" under "Email" should automatically scroll to that section

### 👎 Actual Behavior with Screenshots

NA

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by AdityaGos** [comment]
Willing to work on this issue can you assign this to me?
