### ISSUE TITLE
🚀 Feature: Add a new provider for sms (Eazy)

### ISSUE THREAD

**Issue by sumitsaurabh927** [novuhq/novu#5195]
### 🔖 Feature description

Add a new provider for SMS called 'Eazy'. You can find more [here](https://www.eazy.im/)

### 🎤 Why is this feature needed ?

requested by a [community member](https://discord.com/channels/895029566685462578/937309213036785744/1207334363444805674)

### ✌️ How do you aim to achieve this?

The outcome from this would be Novu supporting Eazy for SMS notifications

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by groom115** [comment]
Hii Can you assign me this issue?
I am open to contribute to your project.

**Comment by sumitsaurabh927** [comment]
Hey @groom115 @last-developer are you still looking to contribute to this?

**Comment by sumitsaurabh927** [comment]
Sure @sr-26 

Assigning it to you!

**Comment by RonnieRocket147** [comment]
Eazy developer here. You can find the API specs at https://developers.eazy.im/

Let me know if there are any questions. Looking forward to the end result, thanks!

**Comment by RonnieRocket147** [comment]
Sure. Can you send a message via WhatsApp to https://wa.me/31302106499

Then I will set it up for you.

**Comment by RonnieRocket147** [comment]
I created a test account for you. Good luck!

**Comment by shashankdaima** [comment]
If @sr-26 is unable to resolve this issue, please assign it to me. I would be happy to work on it.
