### ISSUE TITLE
📚 Docs Feedback: Roadmap up to date?

### ISSUE THREAD

**Issue by gemueselasagne** [novuhq/novu#5240]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://roadmap.novu.co/roadmap

### Kind of issue

Other

### Issue description

Judging by the latest release notes, the roadmap seems out of date. Would love to see where you are heading and what to expect in the near future.

**Comment by scopsy** [comment]
@gemueselasagne do you refer to the translation management released? Or something else there?

**Comment by gemueselasagne** [comment]
> @gemueselasagne do you refer to the translation management released? Or something else there?

yes.

**Comment by scopsy** [comment]
Updated :)
