### ISSUE TITLE
🚀 Feature: Support Data Integration Channel

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#5256]
### 🔖 Feature description

Novu is a great system for centralized notification and messaging all in one place.

We are interested in extending our platform to support more types of channels that allow users to do what they need.

We are looking to add a new channel to support data integrations to allow data of the Notification to be streamed to some other system through a queuing system. This would allow users to create there own processing engine or ingest the events into a identity platform for there system.

A list of systems would be:
1. amqp
2. mqtt
3. Webhook
4. Kafka
5. Pulsar
6. Prometheus

This data provider would just send the full event data of the trigger to some other platform.

NOTE: this is not a feature for advanced integrations, this feature is solely so we can support users doing other things with Novu. The Novu team may choose to create more in-depth integrations in the future that are not covered by the basic data sent here. 

### 🎤 Why is this feature needed ?

This feature would allow users to send data to other internal systems for integration or coloration within there system.

### ✌️ How do you aim to achieve this?

We plan to create a new channel and add providers like we do for any other provider.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by svyatoslavratov** [comment]
Any news?
