### ISSUE TITLE
[NV-375] - Direct Channel Support

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#526]

**Comment by ysaakpr** [comment]
Would be interested to contribute here.. Are there any regular calls/meets happening.. I can spend few hours daily on this.

If we can sort out the interface design for push provider .. it will be great to start with FCM for push.

**Comment by scopsy** [comment]
Hi @ysaakpr ! @djabarovgeorge is currently working on the Direct channel this is mainly for things like Discord, Slack and etc... Push channels are next on the line and would love to chat with you about some of your ideas on this topic since we haven't started implementing the interface yet for push. Feel free to send me a Discord DM and we can schedule a quick call.

And we will share the results here for everybody to see :)

**Comment by davidsoderberg** [comment]
@scopsy will close this now, will be a part of the 0.7.0 release.
