### ISSUE TITLE
🚀 Feature: support of Comparison operators handler helpers

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#5263]
### 🔖 Feature description

Comparison operators — operators that compare values and return true or false. 
The operators include: >, <, >=, <=, ===, and !==.

Example:- 
`{{#gt step.total_count 5}}`

### 🎤 Why is this feature needed ?

To compare two variable values and change content dynamically in step content editor

### ✌️ How do you aim to achieve this?

New handlebar helper implementation can be added here
https://github.com/novuhq/novu/blob/next/packages/application-generic/src/usecases/compile-template/compile-template.usecase.ts#L9

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
@jainpawan21 you can assign me
