### ISSUE TITLE
🚀 Feature: launchUrl override field for onesignal provider

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#5265]
### 🔖 Feature description

Onesignal provider is missing launchUrl field in [implementation](https://github.com/novuhq/novu/blob/next/providers/one-signal/src/lib/one-signal.provider.ts#L32)

### 🎤 Why is this feature needed ?

1. To redirect the user to a specific screen on the app on clicking the push notification
2. Deeplinking

### ✌️ How do you aim to achieve this?

1. Adding this in one signal implementation
2. adding in types and nodejs SDK type

### 🔄️ Additional Information

https://documentation.onesignal.com/docs/links#launch-url

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Aditya-A-G** [comment]
Hi, I would like to work on this issue. Thanks!

**Comment by SafaLabash** [comment]
Do you plan this feature because it is needed?
