### ISSUE TITLE
[NV-300] - [Tracking] - HMAC support

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#527]
## Why?

Currently, when Novu's user adds the notification center to his application he is required to pass a `$user_id` which identifies the user end-customer identifier and the application Identifier which is acted as a public key. 

A malicious actor can access the user feed by accessing the API and passing another `$user_id` using the public application identifier. 

HMAC will make sure that a $user_id is encrypted using the secret API key, and those will prevent malicious actors from impersonating users.

## What?  

By default, the HMAC should not be enabled to make easier onboarding for our users and testing.  But for production purposes, we should add the ability in the configuration to Enable HMAC encryption using a toggle. 

When enabled at the application level, all requests using the application identifier will be rejected unless it successfully decrypted and exists in the request.

### Web Settings Screen 

* application identifier added

[API - Ready for Dev (Figma)](https://www.figma.com/file/IpAw7sGWYZ8DHTem0tSM8r/Ready-for-Dev?node-id=28%3A7574)

### HMAC Setting screen

[In app center - Ready for Dev (Figma)](https://www.figma.com/file/IpAw7sGWYZ8DHTem0tSM8r/Ready-for-Dev?node-id=28%3A7501)

### API Header

A new header should be added and passed along to the client requests. It should contain the signature generated by our customer. 

## Done definition

* E2E tests for web && widget behavior
* Settings configured by web project
* Documentation on how to implement HMAC (in [notion](https://www.notion.so/novuhq/4f08169c94e044079283783293082ae5?v=ee0f6dd079cc4bacbb37ffd7f42e091f&p=04e76403f4344071b6f45db1d31d3a2d)) 
* Updated WIDGET + SDK/EMBED project that received the HMAC as a config (sync with @george and his @novu/bell work)
* API rejects mandatory requests without HMAC when enabled.

**Comment by djabarovgeorge** [comment]
Closed by #539
