### ISSUE TITLE
🚀 Feature: Support Struct as a Chat Provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#5274]
### 🔖 Feature description

We want to add https://struct.ai/ as a chat provider.

### 🎤 Why is this feature needed ?

This will allow users to be able to send messages to new systems.

### ✌️ How do you aim to achieve this?

community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Aditya-A-G** [comment]
Hi, I would like to work on this issue. Thanks!

**Comment by Aditya-A-G** [comment]
Update: I found the Struct API documentation, but I'm having trouble locating where users can obtain the authorization token.

I've reached out to Struct support for assistance and will update once I have more information.
