### ISSUE TITLE
🚀 Feature: Allow img tags and attributes in the In-App & Email Editor

### ISSUE THREAD

**Issue by efaraz27** [novuhq/novu#5310]
### 🔖 Feature description

To allow images to be send in emails and in-app notification.

### 🎤 Why is this feature needed ?

Right now it is not possible to add images to emails and in-app notification, this PR aims to solve that.

### ✌️ How do you aim to achieve this?

Novu used an npm packaged called [sanitize-html](https://www.npmjs.com/package/sanitize-html), [the default allowed tags](https://www.npmjs.com/package/sanitize-html#default-options), doesnt include img tags, this PRs aims to include it as it was done for the style tag in this [PR](https://github.com/novuhq/novu/pull/4841).

### 🔄️ Additional Information

[Original discussion for discord.](https://discord.com/channels/895029566685462578/1212043950039240744/1212043950039240744)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment]
@efaraz27 

Assigned to you 🙂
