### ISSUE TITLE
🚀 Feature: Add DLT supoport for infobip sms provider

### ISSUE THREAD

**Issue by annoyPR** [novuhq/novu#5311]
### 🔖 Feature description

The feature should handle principalEntityId and templateId if passed and send it to infobip request while triggering SMS communication. For businesses that have registered communications with TRAI, DLT support is mandatory

### 🎤 Why is this feature needed ?

DLT support is needed for regulating sms communications which is mandatory by TRAI([Telecom Regulatory Authority of India](https://trai.gov.in/)). Without this feature, cannot send SMS to any user.

### ✌️ How do you aim to achieve this?

Need to add support for DLT template and principal ids in infobip provider (Already supported by infobip APIs)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by joy12999** [comment]
- Maderchod 🗿### [`_****_`]([url](url))
