### ISSUE TITLE
🐛 Bug Report: save id from resend response

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#5337]
### 📜 Description

When resend email provider is used, As per resend [API](https://resend.com/docs/api-reference/emails/send-email) and [SDK method ](https://github.com/resend/resend-node/blob/canary/src/emails/interfaces/create-email-options.interface.ts#L89), id is returned in response, but novu is not storing this `Id` in execution details

### 👟 Reproduction steps

1. Make resend as primary email integration with valid resend credentials
2. Add email step in workflow
3. Trigger the workflow 
4. Check activity feed 
5. Click on the `show details` button on the message sent log of email step

### 👍 Expected behavior

Novu should show resend response id in the execution details

### 👎 Actual Behavior with Screenshots

Id not stored and not showing in execution details

### Novu version

Novu Saas

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
you can assign me

**Comment by michaldziuba03** [comment]
@jainpawan21 unable to reproduce the issue

![image](https://github.com/novuhq/novu/assets/43048524/82f65287-ba48-4433-83a4-368ff80faead)

![image](https://github.com/novuhq/novu/assets/43048524/02d6bbb8-ac75-4323-8d7b-dd33124c4ddc)

**Comment by jainpawan21** [comment]
@michaldziuba03 

Thanks for help. I see it is not reproducible 🙂

Closing this issue
