### ISSUE TITLE
🚀 Feature: current date handlebar helper

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#5376]
### 🔖 Feature description

Add current date handlebar helper to add full date time customization option

### 🎤 Why is this feature needed ?

Currently, Novu has a date handlebar helper that can customize the format of the date value. But the actual value should be sent via the payload variable.

### ✌️ How do you aim to achieve this?

Similar to this

{{curDate 'EEEE, MMMM DO yyyy'}}

curDate is helper and later part is for custmization.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Meyazhagan** [comment]
@jainpawan21 I would like to work on this, can you assign it to me?
