### ISSUE TITLE
🚀 Feature: Support SendGrid ASM parameters

### ISSUE THREAD

**Issue by dmgarland** [novuhq/novu#5402]
### 🔖 Feature description

[ASM groups ](https://docs.sendgrid.com/ui/sending-email/unsubscribe-groups)are a SendGrid feature designed to allow e-mail suppressions short of stopping all mail. 

The [SendGrid API ](https://docs.sendgrid.com/api-reference/mail-send/mail-send) supports `asm` as an option, where the group id is matched against the recipient to see whether they should be sent mail or not.

Currently the Novu SendGrid provider doesn't support `asm` parameters passed via `customData`. This patches that to allow an asm group id to be passed directly through to SendGrid

### 🎤 Why is this feature needed ?

We have a use case where an ASM group is shared with other parts of our platform that require to send mail, so we need to suppress mail being sent to members of that group.

### ✌️ How do you aim to achieve this?

I will change the SendGrid provider to allow the passing of this option

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Abobos** [comment]
Can I work on this issue?
