### ISSUE TITLE
🚀 Feature: Slack personal multi channel support

### ISSUE THREAD

**Issue by kallepronk** [novuhq/novu#5430]
### 🔖 Feature description

Slackbot integrations can be done in two ways: Websockets and channel permissions. Websockets only allow one channel to be added at a time. But this doesn't work when a message needs to be send to a specific user. 
This feature should allow Novu to send a notification to a personal channel in slack, using either the channelID, or the subscribers email.

### 🎤 Why is this feature needed ?

Our system will send notifications to users who have a guest at the front of an office. They need to be send a personal message on slack. We want to use Novu because the system should be able to be hosted on location for security reasons. 
We will know the emails of all users, but not automatically their slack personal ID, therefore we need to be able to reach their personal channel via email.

### ✌️ How do you aim to achieve this?

The slack API has two endpoints that are relevant for this issue, the postmessage endpoint and the endpoint for getting a user by email. When only a email is given, the integration should first get the id of the user, then afterwards it should use that ID in the post message endpoint to actually send the message. The should be a new integration.

### 🔄️ Additional Information

We've tried implementing this ourselves first, but got stuck on the integration structure, this integration needs information that the websocket type doesn't give. We've also tried other services and found that [Knock](https://docs.knock.app/integrations/chat/slack/overview) and [courier](https://www.courier.com/docs/platform/channels/direct-message/slack/) both support this type of advanced slack integration

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by kallepronk** [comment]
I would be willing to pick this up myself once we allocate time for it. However we will need some support to solve some of the issues that have stopped us before.

**Comment by shashankdaima** [comment]
Can I do it? Assign me this?
