### ISSUE TITLE
🐛 Bug Report: Message content could not be generated

### ISSUE THREAD

**Issue by SafaLabash** [novuhq/novu#5465]
### 📜 Description

I use SendGrid for emails and in-app notifications. I have several workflows, but sometimes when I send notifications, I encounter an error: "Message content could not be generated." When I check the details, I find that the "error" field is empty. When I try triggering the email again using a curl request, I see that the email is sent successfully. This error occurs intermittently, at different times of the day and with different emails.
![Screenshot 2024-04-26 at 18 01 07](https://github.com/novuhq/novu/assets/70747544/4cdfbc25-4af7-4c56-86a6-217c2bbedf99)

### 👟 Reproduction steps

1. Trigger an email notification with SendGrid.

### 👍 Expected behavior

Receive email.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-04-26 at 18 01 07](https://github.com/novuhq/novu/assets/70747544/39f3fa70-ced9-46fb-a773-b00807236577)
Error

### Novu version

SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by k0m09dx** [comment]
any updates on this ?

**Comment by shashankdaima** [comment]
I want to take this issue. will do it over night.

**Comment by Samaresh-Das** [comment]
May  I get this issue to work on?

**Comment by Jsdhujw** [comment]
updates on this ?
