### ISSUE TITLE
🐛 Bug Report: Layouts not loaded on web admin client

### ISSUE THREAD

**Issue by Abobos** [novuhq/novu#5483]
### 📜 Description

The layout code template is not loading. The code template field just displays a `loading...` indicator.

### 👟 Reproduction steps

- Go to web `https://web.novu.co/` and login to your web account.
- Go to brand, 
- Click on layout tabs
- When the layout page loads, observe the code template field

### 👍 Expected behavior

It should load the layout code template

### 👎 Actual Behavior with Screenshots

The layout code template is not loaded

<img width="1658" alt="Screenshot 2024-05-02 at 08 24 32" src="https://github.com/novuhq/novu/assets/39123908/4b51658a-c783-4e6f-a4bd-80a04c5a6f7b">
 

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by racky7** [comment]
Not able to reproduce the issue.

<img width="716" alt="Screenshot 2024-05-03 at 12 59 15 PM" src="https://github.com/novuhq/novu/assets/74532684/69062103-0bc0-4812-bbae-70a1cba612f7">

**Comment by Abobos** [comment]
It works now 😄
