### ISSUE TITLE
🐛 Bug Report: Message dropdown menu is hidden by below the notifications center header

### ISSUE THREAD

**Issue by lucafaggianelli** [novuhq/novu#5490]
### 📜 Description

When you open the first message menu (three horizontal dots) in the notifications center (React in my case) the menu is hidden below the notifications center header

### 👟 Reproduction steps

1. Send an in-app notification
2. Open the Notifications Center
3. Click on the 3 dots button on the right of the **first** notification

### 👍 Expected behavior

The dropdown menu should be visible

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/4471043/40610497-1765-4882-902c-ada4495ab1d4)

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by racky7** [comment]
Can I work on this issue?
