### ISSUE TITLE
🐛Cannot find module react-scanner.config.js

### ISSUE THREAD

**Issue by sschwenker** [novuhq/novu#5492]
### 📜 Description

When I run the `pnpm run setup:project` command to setup the project, I get the following error.

✔️ `styled-system/jsx`: styled jsx elements for react
│ > @novu/design-system@0.24.1 prepare:audit C:\Development\git\novu\libs\design-system
│ > pnpm audit-components
│ > @novu/design-system@0.24.1 audit-components C:\Development\git\novu\libs\design-system
│ > pnpm react-scanner -c './react-scanner.config.js'
│ node:internal/modules/cjs/loader:1147
│   throw err;
│   ^
│ Error: Cannot find module 'C:\Development\git\novu\libs\design-system\'.\react-scanner.config.js''
│ Require stack:
│ - C:\Development\git\novu\node_modules\.pnpm\react-scanner@1.1.0\node_modules\react-scanner\src\index.js
│ - C:\Development\git\novu\node_modules\.pnpm\react-scanner@1.1.0\node_modules\react-scanner\bin\react-scanner
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
│     at Module._load (node:internal/modules/cjs/loader:985:27)
│     at Module.require (node:internal/modules/cjs/loader:1235:19)
│     at require (node:internal/modules/helpers:176:18)
│     at C:\Development\git\novu\node_modules\.pnpm\react-scanner@1.1.0\node_modules\react-scanner\src\index.js:14:20
│     at o.parse (C:\Development\git\novu\node_modules\.pnpm\sade@1.8.1\node_modules\sade\lib\index.js:1:3402)
│     at Object.<anonymous> (C:\Development\git\novu\node_modules\.pnpm\react-scanner@1.1.0\node_modules\react-scanner\src\index.js:17:4)   
│     at Module._compile (node:internal/modules/cjs/loader:1376:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
│     at Module.load (node:internal/modules/cjs/loader:1207:32) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\Development\\git\\novu\\node_modules\\.pnpm\\react-scanner@1.1.0\\node_modules\\react-scanner\\src\\index.js',
│     'C:\\Development\\git\\novu\\node_modules\\.pnpm\\react-scanner@1.1.0\\node_modules\\react-scanner\\bin\\react-scanner'
│   ]
│ }
│ Node.js v20.11.1
│  ELIFECYCLE  Command failed with exit code 1.
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 8.9s at C:\Development\git\novu\libs\design-system
 ELIFECYCLE  Command failed with exit code 1.

### 👟 Reproduction steps

Check out the codebase and run pnpm run setup:project

### 👍 Expected behavior

It should install the projects required dependencies.

### 👎 Actual Behavior with Screenshots

It's throwing the error above.

### Novu version

the current next branch

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by itsmemittal** [comment]
I tried clone fresh repo but i am not getting any such error can you try with fresh clone ?

**Comment by ayo6706** [comment]
I had the same issue, and I think it was because my internet went off during the setup, but I am not certain about it, and I was also using Windows. I then decided to use Ubuntu WSL with Windows, and it works now.

**Comment by chaunm182** [comment]
Use linux environment to resolve problem
If using Windows, you can remove the apostrophe for react-scanner.config.js in libs\design-system\package.json
`"audit-components": "pnpm react-scanner -c ./react-scanner.config.js"`

**Comment by ayo6706** [comment]
> Use linux environment to resolve problem If using Windows, you can remove the parentheses for react-scanner.config.js in libs\design-system\package.json `"audit-components": "pnpm react-scanner -c ./react-scanner.config.js"`

I will just advise to switch to a Linux environment or better still make use of Ubuntu WSL on your windows machine because when I faced this issues I had to clone this repo afresh three times and it was resolved when I used a Linux environment.

**Comment by sschwenker** [comment]
Hey.  I re-checked out the code and opened the project using wsl and things got much better, but it still has errors.  I'm now seeing this.

`> @novu/ee-dal@0.24.1 build /mnt/c/Development/git/novu/enterprise/packages/libs/dal
> node ./check-ee.mjs


node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
> @novu/ee-dal@0.24.1 build:esm /mnt/c/Development/git/novu/enterprise/packages/libs/dal
> cross-env node_modules/.bin/tsc -p tsconfig.build.json
error TS18003: No inputs were found in config file '/mnt/c/Development/git/novu/enterprise/packages/libs/dal/tsconfig.build.json'. Specified 'include' paths were '["src/**/*"]' and 'exclude' paths were '["./dist"]'.
 ELIFECYCLE  Command failed with exit code 2.
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.13.0
 ELIFECYCLE  Command failed with exit code 1`

**Comment by ayo6706** [comment]
from what i can see here, firstly, you're not using the required node version, v20.8.1, as stated in https://docs.novu.co/community/run-in-local-machine?utm_campaign=github-contrib .  Also, make sure you cloned the repo in the WSL environment, which you can also use vscode with the WSL extension to do that easily.

**Comment by sschwenker** [comment]
I re-cloned the repo into a folder in my home directory in my wsl instance and that worked.  Thank you.
