### ISSUE TITLE
🚀 Feature: Specify data for each step using Expo provider

### ISSUE THREAD

**Issue by GEphrau** [novuhq/novu#5510]
### 🔖 Feature description

You should add the possibility to specify some additionnal data for a workflow step that use expo

### 🎤 Why is this feature needed ?

Currently i can only specify additionnal data in the payload while triggerring  a workflow.
In my case i would like to send some specific data per worflow step that use expo. The value for data could be different from a step to another one.

### ✌️ How do you aim to achieve this?

I would like to have an additional input on the workflow step edit page, to add the data field for expo notification. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by shashankdaima** [comment]
If this PR get verified by maintainers, I want to work on this.
