### ISSUE TITLE
Notification Center doesn't work with Next.js

### ISSUE THREAD

**Issue by aaron5670** [novuhq/novu#560]
## Notification Center doesn't work with Next.js

**To Reproduce**
1. Installed on latest Next.js 12.1.6
2. Followed this instructions: https://docs.novu.co/docs/notification-center/getting-started
3. See error:
![image](https://user-images.githubusercontent.com/17295145/168160080-bd597c4b-f89d-496a-b14f-9c79ef77387c.png)
4. See code:
![image](https://user-images.githubusercontent.com/17295145/168160798-b1bc22c7-89f1-4cf2-85fd-9bd56d16e5f8.png)

**Details (please complete the following information):**
 - OS: Windows
 - Node 16.14.2
 - NPM 8.5.5

**Comment by scopsy** [comment]
@djabarovgeorge Looks like this is happening during SSR loading on the server and window.localstorage is not accessible.

One thing we can do is we can skip the initialization of the session on the server and only do this on the client side. we might have some other things to adjust so maybe we can test this using Next.js and @davidsoderberg can help with testing on Remix as well :)

**Comment by davidsoderberg** [comment]
@scopsy a rule of mine is if it works with Next.js SSR it works with Remix :) But yeah if we have an example with Next.js it will be easy to port to Remix 😄

**Comment by 13colours** [comment]
Hi! I have made a draft PR to fix this issue here https://github.com/novuhq/novu/pull/561
I would appreciate some help to test this implementation before I make it a proper PR.
Thanks!

**Comment by nevo-david** [comment]
As a temporary solution, you can make your component dynamic.
https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by scopsy** [comment]
@aaron5670 just merged @13colours fix to main, will also push a new package version soon 🙏

**Comment by scopsy** [comment]
This was fixed an 0.4.1 let me know if someone still experience this 🙏
