### ISSUE TITLE
Can't checkout repository on Windows

### ISSUE THREAD

**Issue by proDOOMman** [novuhq/novu#567]
**To Reproduce**
1. Try to checkout repo on Windows:
D:\>git clone https://github.com/novuhq/novu
2. Catch error:
Cloning into 'novu'...
remote: Enumerating objects: 21945, done.
remote: Counting objects: 100% (1493/1493), done.
remote: Compressing objects: 100% (633/633), done.
remote: Total 21945 (delta 857), reused 1414 (delta 836), pack-reused 20452
Receiving objects: 100% (21945/21945), 19.01 MiB | 2.31 MiB/s, done.
Resolving deltas: 100% (13594/13594), done.
error: invalid path 'apps/api/src/app/change/usecases/promote-notification-group-change /promote-notification-group-change.ts'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Details:**
 - OS: Windows

**Comment by ainouzgali** [comment]
Hi @proDOOMman Thank you for reporting! @BiswaViraj  just merged a fix. Please let us know if all is well :) And if you have any more issues.
