### ISSUE TITLE
TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_9__.__spreadArray) is not a function

### ISSUE THREAD

**Issue by singhgulshan** [novuhq/novu#569]
**To Reproduce**
1. Create new Next JS App 'yarn create next-app --typescript'
2. Setup novu notification center using following instructions https://docs.novu.co/docs/notification-center/react-components.
3. Add `typeof window !== 'undefined'` to avoid localstorage undefined issue.
4. Start dev server
5. Trigger one or multiple notifications from backend
6. Click on notification bell icon

**Expected behavior**
It should show the notification triggered

**Screenshots**
<img width="958" alt="Screenshot 2022-05-17 at 3 44 06 PM" src="https://user-images.githubusercontent.com/36273489/168790001-b6833f86-add9-4174-89c8-d6fd9bed9715.png">

**Details (please complete the following information):**
 - OS: Mac, M1 Chip
 - Node Version: v14.18.3
 - NPM Version: 6.14.15
 - React Version: 17.0.2
 - next: 12.0.2
 - @novu/notification-center: 0.4.0-alpha.12

**Comment by davidsoderberg** [comment]
@singhgulshan is this the same problem as https://github.com/novuhq/novu/issues/560 ?

**Comment by singhgulshan** [comment]
@davidsoderberg no its not the same as #560. You can see in step 3 i'm using `typeof window !== 'undefined'`.  So, rendering of notification center is on client side only.

**Comment by singhgulshan** [comment]
@BiswaViraj Output of command `npm list tslib`
<img width="470" alt="Screenshot 2022-05-17 at 11 04 36 PM" src="https://user-images.githubusercontent.com/36273489/168876677-b16f9f6e-794c-439f-983a-c694a2764b5d.png">

Code snippet:
![carbon](https://user-images.githubusercontent.com/36273489/168876770-1d5f49b8-b126-4c4b-afff-7ed47b207e7e.png)

**Comment by BiswaViraj** [comment]
@singhgulshan 
I was able to reproduce the error
![image](https://user-images.githubusercontent.com/29251776/168967202-db9e2d60-1617-4203-80ca-d5ef9828d22c.png)

The issue is due to the outdated version of `tslib` used by the dependencies of `next` as listed in the hierarchy `npm list tslib`.
So, it is more of an issue regarding **Next**. nonetheless, I was able to fix it with a workaround.

1. By explicitly installing latest tslib version: Run `npm install tslib`
2. By using [npm force resolutions](https://www.npmjs.com/package/npm-force-resolutions):
    -  Add this in the scripts section of package.json
    `"preinstall": "npx npm-force-resolutions"`
    - Add resolutions in the package.json
    ` "resolutions": {
    "tslib": "^2.4.0"
  }`

**Comment by singhgulshan** [comment]
This worked!! thanks.
@BiswaViraj thanks for quick resolution and @davidsoderberg for fast response. 
Closing the issue.

**Comment by scopsy** [comment]
Reopening this so we can fix this without the workaround since we seen that a couple of more users experienced this.

**Comment by scopsy** [comment]
Looks like the error was reseolved in latest `0.4.1-alpha.0` release! Amazing Work @singhgulshan @BiswaViraj and all the others <3
