### ISSUE TITLE
Is there a documentation page for the http apis

### ISSUE THREAD

**Issue by aravindarc** [novuhq/novu#570]
## What?
I need http api documentation

## Why?
I don't want to use the nodejs sdk, I want to trigger, create subscribers from golang.

## How?
We can use swagger for documentation, sdk generation and more

**Comment by davidsoderberg** [comment]
@aravindarc, right now we do not have one... I suggest that you check out the nodejs sdk to figure out how you can use the endpoints from golang 😄

**Comment by aravindarc** [comment]
Thanks

**Comment by ainouzgali** [comment]
Hi @aravindarc , its in the works. An issue was opened about this. Thank you for bringing it up!
