### ISSUE TITLE
Swagger json for api documentation

### ISSUE THREAD

**Issue by davidsoderberg** [novuhq/novu#571]
## What?
Swagger json to be able to create an api documentation

## Why?
So the community can create sdks in other lang then NodeJs and also using our api without any sdk if they like...

## How?
Using the express alternative here: https://docs.nestjs.com/openapi/introduction

**Comment by vickywane** [comment]
Hi David 👋 , 

I'd like to work on this.

**Comment by Ekman** [comment]
Novu seems like a cool project and we're investigating if we should use it or not.

I'd say this is extremely important for Novu as you market yourself as "one unified API" but without API documentation you defeat your own purpose. Unfortunately, our back end does not run JS.

Looking forward to this.

**Comment by ComBarnea** [comment]
Hey @Ekman, I think you are very right,  thank you for taking the time to write this down, super appreciated. Would love to get your help about the API once the first version of the interactive API is up and running as @vickywane is working on this, thanks to you two!

**Comment by vickywane** [comment]
@davidsoderberg Going through the [bootstrap.js](https://github.com/novuhq/novu/blob/main/apps/api/src/bootstrap.ts) file for the API, I can see that [Nest.js swagger documentation](https://docs.nestjs.com/openapi/introduction) has already been implemented. 

A user using the service can view the entire swagger docs at `http://localhost:3000/api` (see screenshot). 

Is this issue here having an official copy of the docs hosted for everyone to view without running the services locally?

Cc: @ComBarnea 

<img width="1552" alt="Screen Shot 2022-05-19 at 7 07 35 AM" src="https://user-images.githubusercontent.com/29664439/169222512-6848ce76-a237-4587-af34-56eddb70b7bc.png">

**Comment by davidsoderberg** [comment]
Okay lets start adding docs for /v1/subscribers in this issue :)

**Comment by vickywane** [comment]
I'm back on this :) @davidsoderberg . 

I have added some swagger decorators to the `/subscribers` endpoint.

**Comment by davidsoderberg** [comment]
@scopsy I will close this now because this is included in next weeks release 😄

**Comment by chihabhajji** [comment]
```
i'm getting an error Cannot read properties of undefined (reading '0') at /home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/services/parameter-metadata-accessor.js:14:24
    at /home/black/work/finvo/back/node_modules/lodash/lodash.js:13469:38
    at /home/black/work/finvo/back/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/black/work/finvo/back/node_modules/lodash/lodash.js:3032:24)
    at mapValues (/home/black/work/finvo/back/node_modules/lodash/lodash.js:13468:7)
    at ParameterMetadataAccessor.explore (/home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/services/parameter-metadata-accessor.js:13:59)
    at exploreApiParametersMetadata (/home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js:20:58)
    at /home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/swagger-explorer.js:73:45
    at Array.reduce (<anonymous>)
    at /home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/swagger-explorer.js:72:104
```

using nestjs and the new @novu/framework/nest

**Comment by chihabhajji** [comment]
i dont know how to use the registerApiPath provider

**Comment by IgnacioNavarro** [comment]
> ```
> i'm getting an error Cannot read properties of undefined (reading '0') at /home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/services/parameter-metadata-accessor.js:14:24
>     at /home/black/work/finvo/back/node_modules/lodash/lodash.js:13469:38
>     at /home/black/work/finvo/back/node_modules/lodash/lodash.js:4967:15
>     at baseForOwn (/home/black/work/finvo/back/node_modules/lodash/lodash.js:3032:24)
>     at mapValues (/home/black/work/finvo/back/node_modules/lodash/lodash.js:13468:7)
>     at ParameterMetadataAccessor.explore (/home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/services/parameter-metadata-accessor.js:13:59)
>     at exploreApiParametersMetadata (/home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js:20:58)
>     at /home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/swagger-explorer.js:73:45
>     at Array.reduce (<anonymous>)
>     at /home/black/work/finvo/back/node_modules/@nestjs/swagger/dist/swagger-explorer.js:72:104
> ```
> 
> using nestjs and the new @novu/framework/nest

Did you fix it?
