### ISSUE TITLE
Page crash on CRA React 18

### ISSUE THREAD

**Issue by BiswaViraj** [novuhq/novu#594]
**Describe the bug**
The page crashes when importing the Novu react component.

**To Reproduce**
1. Create a new react app using `npx create-react-app <project-name>`
2. install `npm install @novu/notification-center`
3. use the code snippet provided on [https://docs.novu.co/docs/notification-center/react-components](url)

**Expected behavior**
Should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/29251776/170071718-72136900-a6ab-472b-ae6f-e7585a95aa55.png)

**Details (please complete the following information):**
 - OS: Windows 11
 - Node Version: v16.15.0

**Additional context**

**Comment by davidsoderberg** [comment]
@BiswaViraj, yes this is known to us, right now the notification-center do not work with React 18...
Is this something you like to investigate?
