### ISSUE TITLE
When editing the message name, the code snippet is not updated

### ISSUE THREAD

**Issue by abrl91** [novuhq/novu#602]
**Describe the bug**
When editing the message name, the code snippet is not updated.

**To Reproduce**
1. Go to 'Notification'
2. Click on 'the edit button of the notification you want to edit'
3. Edit the name
4. Click on Trigger Snippet
5. See that the notification name on `novu.trigger` was not updated

**Expected behavior**
The notification name string on `novu.trigger` should be updated when renaming the notification name

**Screenshots**
![image](https://user-images.githubusercontent.com/39680385/170463801-c3c5e9a3-977a-4812-a8c5-e82183bc4f12.png)

![image](https://user-images.githubusercontent.com/39680385/170463843-627a2f6e-6e01-4a7c-af5f-9ba7a77aa4ac.png)

**Details (please complete the following information):**
 - OS: Mac
 - Node Version v16.3.0

**Additional context**

**Comment by scopsy** [comment]
@abrl91 Thanks for reporting, we currently do not allow updating the trigger identifier after initial creation from the UI. We had some blocking issues we needed to update, and we just can add a field for this. I'm creating a detailed issue right now and will update you once it's released.

**Comment by rizdev99** [comment]
Hi, @scopsy  is the detailed issue ready for this to look into?

**Comment by scopsy** [comment]
Hi @rizdev99! Yes,we can work on this one :)

We can add a new input on the workflow editor settings page that will be automatically generated on input change of the name field (Only in new creation mode)

In Editor mode, this will not be automatically updated but must be updated by the user. 

Let me know if that makes sense, and let me know if you will have any further questions :)

**Comment by rizdev99** [comment]
Okay. I'll look into this issue
Thanks :)

**Comment by Nike682631** [comment]
@scopsy  Is this issue available to work on?

**Comment by jainpawan21** [comment]
This is fixed and can be closed
