### ISSUE TITLE
Add Clickatell SMS provider

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#604]
### What?
New [Clickatell](https://github.com/clickatell/clickatell-node) SMS Provider.

### Why?
To have the ability to use Clickatell as a provider.

### How?
Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### Usage
Example for Clickatell SMS provider registration needs to be finalized. 

```ts
  new ClickatellSmsProvider({
    // API is missing
  })

```

**Comment by Abobos** [comment]
@scopsy I think I can look into this.

**Comment by djabarovgeorge** [comment]
Sure, so the new provider handlers currently serve as data mappers. and are located at 
https://github.com/novuhq/novu/tree/main/apps/api/src/app/events/services/sms-service/handlers
where you can see all the current SMS handlers.

**Comment by Abobos** [comment]
@djabarovgeorge got you.

**Comment by AakashRaj20** [comment]
@scopsy if this issue is not resolved I would like to try it

**Comment by AakashRaj20** [comment]
> @AakashRaj20 I am working on this issue

Oh ok no problem

**Comment by Abobos** [comment]
@scopsy @djabarovgeorge 

Context

1. Clickatell platform package does not return the messageId it logs internally. Hence after the message is been submitted to Clickatell ends, We don't have the messageId.

2. Clickatell platform also sends a delivery notification that contains nitty-gritty details about the SMS. 


Questions.

1. Should I amend the Clickatell platform package to return the messageId it logs internally to consumers of its APIs and open a PR for it on the Clickatell platform so we can use that amended package

2. How do we handle Clickatell delivery notifications for users of our providers?
