### ISSUE TITLE
Socket Api Breaking on Safari Browser: Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by singhgulshan** [novuhq/novu#616]
**Describe the bug**
Socket.io api for novu is responding with 
```
{
    "code": 1,
    "message": "Session ID unknown"
}
```
Same is working on chrome.

Also Socket api keeps on triggering in a loop.
<img width="1440" alt="Screenshot 2022-06-01 at 4 31 41 PM" src="https://user-images.githubusercontent.com/36273489/171391101-e8b5c6fa-9761-4a66-a681-6e752a2c22a8.png">

**Expected behavior**
Socket connection should establish a connection for real time update

**Details:**
 - OS: Mac
 - Node Version: v14.18.3
 - NPM Version: 8.10.0
 - @novu/notification-center: 0.4.2
 - react: 17.0.2
 - next: 12.0.2
 - Browser: Safari 15.4

**Comment by scopsy** [comment]
@singhgulshan I think the approach would be to add to the socket client of the `@novu/notification-center` library since looks like this issue is caused by sticky session behavior on other transport methodologies. 

```
   "transports": ['websocket']
```
