### ISSUE TITLE
Activity Feed breaks down and can't resubscribe a user with same phone and different id

### ISSUE THREAD

**Issue by narzaut** [novuhq/novu#619]
**Describe the bug**
After subscribing and unsubscribing a user, the Activity Feed breaks down and I cannot subscribe another user with different id and same phone number as the previously unsubscribed user

**To Reproduce**
1. Using '@novu/node' module
2. Connected to Novu Cloud account and using its API and Web Dashboard
3. Set up an active notification template with sms channel
4. Set up a Twilio Integration
6. Subscribe an user only with an ID and a phone number 
7. Up until this point the trigger is working
8. Unsubscribe previously subscribed user
9. Dashboard's Activity Feed now shows TypeError: Cannot read properties of null (reading 'firstName')
10. Can't seem to be able to subscribe another user with the same phone number and different id.

**I MIGHT HAVE SUBSCRIBED A USER, THEN UNSUBSCRIBED, THEN TRIGGERED**

**Expected behavior**
I expected to be able to unsubscribe the user and just subscribe another one with a different id and the same phone number as the previously unsubscribed one
Now I can't get the trigger working with the same number as before

**Screenshots**
This is the Activity Feed after unsubscribing a user
![Screenshot from 2022-06-01 20-01-39](https://user-images.githubusercontent.com/63589213/171515501-52d884cf-cfee-400d-b153-3e0a4fcbe538.png)

This is the small node implementation I got the bug with
![Screenshot from 2022-06-01 20-14-07](https://user-images.githubusercontent.com/63589213/171516633-03a07e31-07d9-4134-9755-8ccb2ef92803.png)

**Details (please complete the following information):**
 - OS: Ubuntu 22.04
 - Node version: 16.13.0
- @novu/node version: 0.4.1

**Additional context**
I recreated the same error both in Development and Production enviroments
There's also the possibility that I'm doing something wrong. If that's the case, I'm sorry for opening an issue. If not, then I hope this feedback helps.

**Comment by scopsy** [comment]
@narzaut Thanks for reporting this! We are looking at it ASAP. Will reproduce and create a test to verify this won't happen again. 

On another note, you can keep the subscriber entity alive without removing it, and just don't trigger events to it. Could you elaborate on your need to remove the subscriber? (This is nothing to do with the issue you encountered, will fix it regardless.)

**Comment by narzaut** [comment]
Hi George,

I initially thought that both problems were linked (client failure and my
subscription problem), but now I see that's not the case. I'm embarrased to
say that maybe the latter is product of my own incompetence.

I haven't tried further yet, but I will keep working on my implementation
and will update if I fix it, and report any other problems that I might
encounter

**Comment by djabarovgeorge** [comment]
I am not saying there is no issue on creation on the second subscriber (just that i could not reproduce it), please note that without your contribution we would  not be aware about of the client bug. 
Please do not hesitate to contact us at any point, and you are more then welcome to join our discord if you did not yet, in order to chat with me or the rest of our community, i will try to reproduce this issue once again tomorrow :)
