### ISSUE TITLE
Unseen Count for Custom UI Component

### ISSUE THREAD

**Issue by singhgulshan** [novuhq/novu#620]
**Describe the bug**
Not able to get unseen count for custom component using `useNotifications` hook. I used useSocket to get unseen count on real time, which is working fine. But on page reload unseen count state is reset to 0.

**Expected behavior**
There should be a new hook or new entity in `useNotifications` to get the unseen count.

**Details:**
 - OS: Mac
 - Node Version: v14.18.3
 - NPM Version: 8.10.0
 - @novu/notification-center: 0.4.2
 - react: 17.0.2
 - next: 12.0.2
 - Browser: Safari 15.4

**Comment by scopsy** [comment]
@singhgulshan thanks for mentioning this! We added this to our upcoming release. I will keep you up to date around this Sunday on update for it.

**Comment by djabarovgeorge** [comment]
Hey @singhgulshan 
Actually, we do have useUnseenController hook you can use please let us know if it answers your need, the missing part is a mention of the hook in the documentation that we should add.

**Comment by djabarovgeorge** [comment]
@singhgulshan Yes you are right you can use the socket `unseen_count_changed` message in order to update the count on setUnseenCount.

**Comment by djabarovgeorge** [comment]
@singhgulshan Awesome i glad we could help :)
