### ISSUE TITLE
Add Twitter and Support on readme

### ISSUE THREAD

**Issue by souravjain540** [novuhq/novu#635]
## What?
1. There should be a link to the Twitter page of the project in the starting on readme where discord is mentioned. Twitter is a tech community.
2. There should be a separate section for support on the readme where it should be mentioned clearly where one should go to get priority support(most probably discord or whatever maintainers want)

## Why?
1.) Twitter should be mentioned to show the visibility and show this is the authentic account of the project. Also, there are updates on the Twitter account of a project, so users will get to know what's going on.

2.) To let users know where to go when support is needed.

## How?

I can make a PR and we can review it together.

**Comment by AakashRaj20** [comment]
@souravjain540  is this still open I would like to try it?

**Comment by ainouzgali** [comment]
Thank you both! I am closing this as this was merged
