### ISSUE TITLE
start script fails on windows

### ISSUE THREAD

**Issue by BiswaViraj** [novuhq/novu#643]
**Describe the bug**
when running npm start:dev on windows it throws an error and upon investigating it seems to be an issue with the 
scripts having PORT=4200,  PORT=3000 in the package.json.
This can be confirmed by running apps/web individually using `npm run start:web` as it throws the error
`PORT is not recognized as an internal or external command`

**To Reproduce**
Steps to reproduce the behaviour:
1. clone and set up the project on a windows machine.
2. run npm run start:dev
3. It will throw the error

**Expected behavior**

**Screenshots**
<img width="470" alt="image" src="https://user-images.githubusercontent.com/29251776/172891579-c5b80803-040f-4ae3-bb42-5068f5ce76b3.png">

**Details (please complete the following information):**
 - OS: Windows
 - Node Version: v16.15.0

I would like to fix this.

**Comment by scopsy** [comment]
Hi @BiswaViraj I think it's because the way windows sets env params right? Do you know a better way to handle this in order to support both mac, linux and windows?

**Comment by BiswaViraj** [comment]
@scopsy, I moved the params to the `.env` file and it seems to work on all OS.
I will update the scripts of other packages and create a PR.

**Comment by scopsy** [comment]
@BiswaViraj for default params that might be totally fine, but in some case we modify params for testing purposes and etc... 
So for those cases this might not work. Are you familiar with https://www.npmjs.com/package/cross-env ? Maybe better adding it?

**Comment by BiswaViraj** [comment]
@scopsy, I saw now that we are already using cross-env for a few scripts and will update the broken scripts with cross-env then.

**Comment by scopsy** [comment]
@BiswaViraj good to know aswell :P

**Comment by BiswaViraj** [comment]
@scopsy, while building the project, 
`rm -rf dist` command inside `cli` package is throwing the error of `rm is not recognized as an internal or external command`
and `cross-env` or `cross-env-shell` doesn't solve that.
we need [rimraf](https://www.npmjs.com/package/rimraf) to solve that.

Please note that this error only occurs while using `Command Prompt` on windows, it works fine on `Powershell` and `git bash`.
So do you think it would be a good idea to add `rimraf` package and update the `rm` scripts or just let it be?
