### ISSUE TITLE
Widget auth token clashing with gateway auth token

### ISSUE THREAD

**Issue by rashi-jaiswal-007** [novuhq/novu#645]
## What?
Have a setting to use react component widget without auth (bearer) token being appended to it.

## Why?

We're facing this scenario where  on trying to use the react component for in-app notifications, the component internally takes care of the auth and applies a bearer token for the same. Now this token is actually clashing with our API gateway's auth token. I don't see a way to disable this auth currently. So widget skipping to add this token should help this.

## How?
Perhaps have an environment variable for this setting. Keeping in mind there could be some structure change required in API too (apart from removing auth guards over widget APIs).

**Comment by djabarovgeorge** [comment]
@scopsy How about using another custom header on the notification-center authentication and creating auth guards with the same logic that uses the new custom header?
Will such an approach will be proper in order to address our issue of the shared use of the authentication header?

**Comment by scopsy** [comment]
Regardless of the way we solve this we need to add the new custom header on the API authorized headers on the CORS plugin. 

We can either modify this at the @novu/notification-center component by changing the `Authorization` header to something custom like "X-Novu-Authorization". @rashi-jaiswal-007 will this help? 

We can also allow the user to select his own header name, but this will require to also add this to the API Cors config, something that might be problematic.

@rashi-jaiswal-007 Are you using the Cloud or self-hosted version of Novu?

**Comment by rashi-jaiswal-007** [comment]
@scopsy 
1. Yes novu having header `X-Novu-Authorization` sounds good. 
2. Can't we set the `Authorization` header additionally? (So in any case authorization is still being performed)
3. We're using self-hosted version

**Comment by rashi-jaiswal-007** [comment]
Hey sure @scopsy. There are some other minor changes too, for which I'd wish to create a PR. I'll discuss with you soon.

Thanks @djabarovgeorge for taking this up

**Comment by scopsy** [comment]
Sure thing! @rashi-jaiswal-007 Im available here or on Discord :)

**Comment by scopsy** [comment]
Will be closing this for now, we can revisit it later 🙏
