### ISSUE TITLE
Rust server SDK

### ISSUE THREAD

**Issue by kymppi** [novuhq/novu#654]
## What?
A Rust server SDK

## Why?
Probably a lot of people will write their APIs in Rust or have already wrote.

## How?
You could follow [doc.rust-lang.org](https://doc.rust-lang.org/cargo/guide/creating-a-new-project.html)

**Comment by kymppi** [comment]
Ive been learning Rust for the last month or so, so i think I could do it :+1: And that link i sent has a section for publishing.

**Comment by kymppi** [comment]
Hey just wondering where i should store the source code, probably a new repo? Since it's rust and not javascript so it cant use the multirepo that well.

**Comment by scopsy** [comment]
Totally aggree, I think it's best to have a separate repo for this. Created https://github.com/novuhq/rust/ 🚀

**Comment by aggmoulik** [comment]
Hey, @kymppi Can we pair on the SDK for rust? I am also learning Rust and I am a TypeScript Developer maybe I can bring something to the table.

**Comment by kymppi** [comment]
Sure, wanna work on my fork? Then we can make a single PR

**Comment by lawweiliang** [comment]
This is what I am looking at.  @kymppi @aggmoulik. Mind to share with me the github link. We might work together to turn the underground into rust as well. What do you think?

I had put a discussion over this section. Let discuss. 😃 
https://github.com/novuhq/novu/discussions/1181

**Comment by kymppi** [comment]
Heyy, you can find the repo at https://github.com/novuhq/rust

**Comment by lawweiliang** [comment]
The beauty of Rust is it is a memory-safe and high-performance bottom layer(system) language. Adding a layer of Rust on top of NodeJs would not bring any beauty of Rust to the surface. 

Hmm, but since the project had been started with node. Then, we follow yeah. 😄

**Comment by kymppi** [comment]
Yea, rust doesnt bring any performance, this is just an sdk for the rust server applications

**Comment by kymppi** [comment]
Any performance in this case*

**Comment by lawweiliang** [comment]
Alright, noted. Thanks @kymppi.

**Comment by kymppi** [comment]
Yea, i see i didnt mention it in the issue :D

**Comment by Cliftonz** [comment]
@scopsy I think this issue can be closed now the repo is created.
