### ISSUE TITLE
Team invite is not working when already logged in

### ISSUE THREAD

**Issue by ComBarnea** [novuhq/novu#656]
**Describe the bug**
When inviting some to my team on the Cloud version of Novu, and opening the link on the same browser, the invite link page isn't working. 
![Screen_Shot_2022-06-13_at_3 06 02_PM](https://user-images.githubusercontent.com/8877285/173488588-9a47125f-0438-4bda-97de-81119aa31edb.png)

**To Reproduce**
1. Go to https://web.novu.co/team
2. Invite another email
3. Open the invite link, on the same browser, or any browser with an active session, already logged in to web.novu.co
4. See the error

**Expected behavior**
A clear message about why it's not working and an option to log out.

**Screenshots**
See above

**Additional context**
Using another browser, or incognito mode is working as a workaround.

**Comment by samsoft00** [comment]
@scopsy can I jump on this?

**Comment by davidsoderberg** [comment]
@samsoft00 I have assigned you :)

**Comment by samsoft00** [comment]
Awesome, thank you.

**Comment by samsoft00** [comment]
@davidsoderberg check your Discord DM for, quick clarification.

**Comment by scopsy** [comment]
Looks like this was merged, thanks @samsoft00 !
