### ISSUE TITLE
Documentation update: "PopoverNotificationCenter", colorScheme

### ISSUE THREAD

**Issue by Lorakus** [novuhq/novu#697]
**To Reproduce**
1. Go to 'https://docs.novu.co/docs/notification-center/react-components#dark-mode-support'
2. Try to add colorScheme into NovuProvider 
3. PopoverNotificationCenter does not change color, it stays in "light" mode

or

1. open novu documentation
2. go to notification-center
3. Click on 'react-components'
4. Scroll down to 'dark-mode-support'
5. Try to add colorScheme into NovuProvider 
6. PopoverNotificationCenter does not change color, it stays in "light" mode
 
**Expected behavior**
PopoverNotificationCenter  component changes color when colorScheme={'dark'} to dark mode.

Solution: 
The colorSchema prop should be passed in "PopoverNotificationCenter" component.

```
import { NovuProvider, PopoverNotificationCenter, NotificationBell } from '@novu/notification-center';

function Header() {
  function onNotificationClick(notification: IMessage) {
    navigate(notification.cta.data.url);
  }
  
  return (
    <NovuProvider subscriberId={'USER_ID'} applicationIdentifier={'APP_ID_FROM_ADMIN_PANEL'}>
      <PopoverNotificationCenter onNotificationClick={onNotificationClick} colorScheme={'dark' || 'light'}>
        {({ unseenCount }) => <NotificationBell unseenCount={unseenCount} />}
      </PopoverNotificationCenter>
    </NovuProvider>
  );
}
```

**Comment by ainouzgali** [comment]
Thank you @Lorakus !🚀
