### ISSUE TITLE
Update favicon url and remove unused default images from `apps/web`

### ISSUE THREAD

**Issue by devblin** [novuhq/novu#715]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  - Updating href for below mentioned favicon-link with novu's favicon.
   https://github.com/novuhq/novu/blob/963b3c9f594b368b5b9725624943a1da8160a21e/apps/web/public/index.html#L9
  - Removing default unused-react images from **apps/web/public**.
  https://github.com/novuhq/novu/tree/main/apps/web/public

Willing to submit PR 👍🏽

**Comment by scopsy** [comment]
Good idea to fix this! @devblin 🚀
