### ISSUE TITLE
Make Nodemailer options optional

### ISSUE THREAD

**Issue by Keyruu** [novuhq/novu#739]
## What?
I have a local novu running inside docker. In my network is a plain SMTP server without authentication. With the current Nodemailer in novu I can't use it without specifying username and password. I also would have to specify "Secure" which I also don't use. Please make these properties optional instead of mandatory.

## Why?
For a test setup or a setup where the SMTP server authenticates through network username, password and secure shouldn't be mandatory.

## How?
Dima Grossman#8096 in the novu discord already pointed this out:
```
so looks like it happens here https://github.com/novuhq/novu/blob/4b1103fdd806abbc461d8c2d90eddb64f2d2dc54/apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx#L120
We actually can just specify in the config array that those 2 fields can be not mandatory
We can add an optional field of "required" on this interface https://github.com/novuhq/novu/blob/b093fe5c2d1619df0ce0cc963b3a5ef86f54df4e/libs/shared/src/consts/providers/provider-credentials.ts#L96
```

**Comment by shreyazz** [comment]
I'd like to look into it...

**Comment by scopsy** [comment]
Hi @shreyazz sure! Let me know if you will need any help or direction

**Comment by scopsy** [comment]
Thanks @WinterCore closing this one 🚀
