### ISSUE TITLE
[NV-182] - Add Bandwidth sms provider

### ISSUE THREAD

**Issue by ComBarnea** [novuhq/novu#76]
### **What?**

New [Bandwidth](https://github.com/Bandwidth/node-messaging) SMS Provider.

### **Why?**

To have the ability to use [Bandwidth](https://github.com/Bandwidth/node-messaging) as a provider.

### **How?**

Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### **Usage**

Example for Bandwidth SMS provider registration needs to be finalized.

```
await notifire.registerProvider(
  new Bandwidth SmsProvider({
    username: process.env. BANDWIDTH_USERNAME,
    password: process.env.BANDWIDTH_PASSWORD,
    apiKey: process.env.BANDWIDTH_API_KEY
  })
);
```

**Comment by kishorliv** [comment]
@ComBarnea Can i work on adding this new provider?

**Comment by ComBarnea** [comment]
Hey @kishorliv sure thing :) Just assigned you, good luck!

Let us know if we can assist you in any way.

**Comment by kishorliv** [comment]
@ComBarnea I worked on it but to get the api keys, they need organisation email and phone numbers for the trial. So, I am kinda stuck here...

**Comment by scopsy** [comment]
Hey @kishorliv missed this message between all the notifications on GH. If this is still relevant could you jump on our discord server so I can send you a test credentials to use ?

**Comment by Antonio-Riccelli** [comment]
Hi all, 
Is this still required and unassigned? It seems to be a beginner-friendly issue and I would like to help 👍🏻

**Comment by davidsoderberg** [comment]
@Antonio-Riccelli it is, should I assign you to it?

**Comment by Antonio-Riccelli** [comment]
Hey @davidsoderberg, please do. I'd like to give it a go :)

**Comment by davidsoderberg** [comment]
@Antonio-Riccelli Assigned you now 😄

**Comment by AakashRaj20** [comment]
> Hey @davidsoderberg, please do. I'd like to give it a go :)


Hey are still working on this issue or can I give it a try

**Comment by Antonio-Riccelli** [comment]
Hey @AakashRaj20 , please feel free to have a go. I've got kind of busy with work in the meantime. 

Apologies, @davidsoderberg, could you kindly reassign it to Aakash?

**Comment by AakashRaj20** [comment]
> Hey @AakashRaj20 , please feel free to have a go. I've got kind of busy with work in the meantime.
> 
> Apologies, @davidsoderberg, could you kindly reassign it to Aakash?

Hey actually right now I am working on another issue, so when I will be done with it, I will give this issue a try 😅

**Comment by AakashRaj20** [comment]
@davidsoderberg I would like to try this issue please assign it to me 😀

**Comment by davidsoderberg** [comment]
@AakashRaj20 assigned :)

**Comment by iampearceman** [comment]
Hey @AakashRaj20, I will unassign you so others can try and help with that issue.

Ping me if you would wish to work on it again :)

**Comment by peoray** [comment]
@scopsy @iampearceman I'm working on this and would love the test credentials

**Comment by jainpawan21** [comment]
> @scopsy @iampearceman I'm working on this and would love the test credentials

Thanks for your interest. You can signup and use your own credentials.

**Comment by unicodeveloper** [comment]
@peoray Is this something you are still working on?

**Comment by peoray** [comment]
yes @unicodeveloper

**Comment by 07tAnYa** [comment]
hey! can you assign this to me? I want to work on it.

**Comment by 07tAnYa** [comment]
> @07tAnYa I just assigned you to this one
okay sir, I have started working on this. If found any difficulty then how may I contact you?

**Comment by davidsoderberg** [comment]
Use our discord and someone will help you :)

**Comment by 07tAnYa** [comment]
ok sir

**Comment by 07tAnYa** [comment]
sir I am almost done with the work , hopefully if everything goes well . You will recieve the PR by the end of this day. Due to my college exams I was not getting enough time. But from today I will completely focus over here.

**Comment by CodeGovindz** [comment]
@davidsoderberg could you please assign this issue to me

**Comment by parveshsaini** [comment]
Hello @davidsoderberg! I'd like to take this forward. It'll be much appreciated if you could assign it to me.

**Comment by parveshsaini** [comment]
Hey @Cliftonz 👋
Is this issue still open? If so, I'd like to contribute to it. Kindly assign it to me.

**Comment by parveshsaini** [comment]
Hey @Cliftonz 👋
I've raised the draft PR. Please ping me on Discord whenever you receive the test credentials for Bandwidth SMS provider.
I'll test the provider and finalize the PR once I get the credentials.
Thanks!
