### ISSUE TITLE
Allow regenerating API keys

### ISSUE THREAD

**Issue by raikasdev** [novuhq/novu#768]
## What?
Users should be able to regenerate their API keys

## Why?
For example if they get leaked, you can just regenerate new ones and they cannot get abused.

## How?
Add a button that refreshes the app secret and api key.

**Comment by samsoft00** [comment]
@scopsy kindly assigned to me.

**Comment by ainouzgali** [comment]
Sure @samsoft00 :) I assigned you

**Comment by scopsy** [comment]
Hi @samsoft00 just wanted to ask if you need some help or guidance. Or otherwise if you want me to un-assign you 🙏

**Comment by abayomii** [comment]
Hi @scopsy, yes, I'll reach out to you, apologies for the delay.

**Comment by samsoft00** [comment]
Hi @scopsy, yes, I'll reach out to you, apologies for the delay.

**Comment by florian-lefebvre** [comment]
Hi, I'm interested in this. Any news ?

**Comment by scopsy** [comment]
Hi @samsoft00 I'll un-assign you for the time being, perhaps someone can help with this aswell. Since it's quite an asked functionality just as @florian-lefebvre mentioned.

**Comment by florian-lefebvre** [comment]
I could try I guess @scopsy, just need a few infos:
- Is there an existing endpoint for this already? And if it's not the case, where should it be created?
- Do we want to regenerate all tokens at once or per environment?

Just for references:
- https://github.com/novuhq/novu/blob/main/apps/web/src/pages/settings/tabs/ApiKeysCard.tsx

**Comment by scopsy** [comment]
Sure! 
- There is no endpoint for this yet. You can look at the fetch existing API keys endpoint and locate the use case and endpoint close to there.
- Only for the existing environment

You could add an integration test on the API for this (you can look at the get API keys as a starting point). And ofcourse feel free to reach out here or on Discord if you will need any help.

**Comment by florian-lefebvre** [comment]
Hey @scopsy, I just made a PR (#1292)

**Comment by florian-lefebvre** [comment]
Hey @scopsy can be closed now. Thanks for your help (and the rest of the team) on the PR!

**Comment by scopsy** [comment]
Amazing work @florian-lefebvre thanks for you contribution!
