### ISSUE TITLE
Vercel Redirection not working for docs.

### ISSUE THREAD

**Issue by dcbartlett** [novuhq/novu#788]
**Describe the bug**
Vercel Redirection not working for docs.

https://github.com/novuhq/novu/blob/main/docs/vercel.json

**To Reproduce**
1. Go to 'https://docs.novu.co/docs/overview/introduction'
4. See Page not Found

**Expected behavior**
Redirection will happen and send to correct documentation page.

**Screenshots**
https://cdn.discordapp.com/attachments/943775848509620234/993936839406792896/unknown.png

**Details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by raikasdev** [comment]
Fixed by #806
