### ISSUE TITLE
[NV-180] - Add new SparkPost provider

### ISSUE THREAD

**Issue by ComBarnea** [novuhq/novu#80]
### **What?**

New [SparkPost](https://github.com/SparkPost/node-sparkpost) Email Provider

### **Why?**

To have the ability to use [SparkPost](https://github.com/SparkPost/node-sparkpost) as a provider.

### **How?**

Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### **Usage**

Example for SparkPost provider registration needs to be finalized.

```
await notifire.registerProvider(
  new SparkPostProvider({
    apiKey: process.env.SPARKPOST_API_KEY
  })
);
```

**Comment by alceil** [comment]
I would like to work on this issue. Can anyone assign me this issue?

**Comment by scopsy** [comment]
@alceil Amazing! You kick off the needed code by running `yarn run generate:provider` from the root directory.

Feel free to reach us on Discord for any help 🚀

**Comment by alceil** [comment]
Thanks @scopsy

**Comment by aggmoulik** [comment]
Hey @scopsy What was the issue with the previous PR? I am looking to work on this.

**Comment by scopsy** [comment]
So I think it was closed automatically when the target branch was deployed for some reason, just now noticed that :( @alceil deeply apologize I missed it, if you can maybe reopen it and @aggmoulik can contribute to it to finalize everything so we can merge this.

**Comment by alceil** [comment]
Sure

**Comment by aggmoulik** [comment]
@alceil @scopsy Update on PR.

**Comment by scopsy** [comment]
@oba2311 it was actually closed without every being merged :( And some much have changed since then that we will have to re-do a lot of the integration parts based on the guide here: https://docs.novu.co/community/create-provider

**Comment by Nike682631** [comment]
@scopsy  Is this issue available to work on?

**Comment by peoray** [comment]
Is this still a valid issue?

**Comment by scopsy** [comment]
Looks like already merged @peoray thank you for mentioning.

**Comment by peoray** [comment]
I can't find a page for the documentation though. Can I make a pr?

**Comment by scopsy** [comment]
@peoray would really appreciate this! Thank you

**Comment by peoray** [comment]
@scopsy Sparkpost is also not under Novu integrationns page
