### ISSUE TITLE
Allow deleting notifications

### ISSUE THREAD

**Issue by raikasdev** [novuhq/novu#807]
## What?
Allow users to remove notifications.

## Why?
Disabling isn't enough, I want the notifications I don't need removed. Also someone can typo the notification name.

## How?
If you have an idea of how this can be implemented write your solution here

**Comment by scopsy** [comment]
Also add a comment for Shlomy our designer to where this can fit in the UI. https://www.figma.com/file/9jalQvImfHtbbExZPLW3XO?node-id=1451:23817#224130926

**Comment by FidalMathew** [comment]
@scopsy I would like to work on this issue. It might take some time for me to get started cause I have to set up novu locally in my system. I had also been pondering over this issue for some time 😄.

**Comment by raikasdev** [comment]
> @scopsy I would like to work on this issue. It might take some time for me to get started cause I have to set up novu locally in my system. I had also been pondering over this issue for some time smile.

This has already been done, forgot to close, sorry!
Resolved by #809
