### ISSUE TITLE
Allow users to belong to multiple organizations

### ISSUE THREAD

**Issue by raikasdev** [novuhq/novu#811]
## What?
Users should be able to be in multiple organizations, create new ones and switch between them.

## Why?
If user wants to host different projects on same instance or cloud version, it is not possible.

## How?
If you have an idea of how this can be implemented write your solution here

**Comment by scopsy** [comment]
That is a good one, we actually already support this in the backend data structure, just need to add a UI part for switching and generating organization specific tokens. 

From my memory there is an organizations/switch endpoint for it

**Comment by oba2311** [comment]
@raikasdev  is this something you want to work on?

**Comment by scopsy** [comment]
@oba2311 can we create a UI design for this? of where we can have it in the UI maybe? I think it will help with working on this

**Comment by Anishpras** [comment]
@scopsy @oba2311  May I work on this? If yes, how would you like me to proceed?

**Comment by scopsy** [comment]
Sure @Anishpras ! We would only need a design from @oba2311 for the switcher of the organizations and how a user will be able to switch between them.

**Comment by scopsy** [comment]
@oba2311 did you have a chance to chat with Shlomi about this one?
