### ISSUE TITLE
Allow nested access to payload with handlebars

### ISSUE THREAD

**Issue by raikasdev** [novuhq/novu#823]
## What?
Users cannot access data in payload, if it is nested.

## Why?
Users might want to use nested objects instead of long variable names to make payloads more clear.
Discord [thread](https://discord.com/channels/895029566685462578/895029567125872653)

## How?
Currently [customly made](https://github.com/novuhq/novu/blob/main/apps/api/src/app/shared/helpers/content.service.ts#L4-L14), but a library like [handlebars.js](https://handlebarsjs.com/) could be utilized, or a add a nested feature to the custom functionality ([example](https://stackoverflow.com/a/38640223))

![image](https://user-images.githubusercontent.com/29684625/178312228-5b652aa9-be3b-443c-ade5-d00771241398.png)

**Comment by scopsy** [comment]
This is already fixed by @davidsoderberg as part of #771 and will be merged in v0.6.0 release 🙏

Thanks for reporting!

**Comment by oba2311** [comment]
@raikasdev  - sounds like a quick fix, WDYT?
