### ISSUE TITLE
[NV-2436] Add NTFY provider

### ISSUE THREAD

**Issue by raikasdev** [novuhq/novu#836]
## What?
Add support for https://ntfy.sh/

## Why?
For more providers. This was requested on [Reddit](https://www.reddit.com/r/selfhosted/comments/vxywzx/comment/ifz575j/?utm_source=share&utm_medium=web2x&context=3)

## How?
If you have an idea of how this can be implemented write your solution here

## Other information

<sub>[NV-2436](https://linear.app/novu/issue/NV-2436/ntfy-support)</sub>

**Comment by jgoerner** [comment]
@raikasdev would you mind if I tackle this one? 😊

**Comment by jgoerner** [comment]
@raikasdev is this Issue still relevant and up for grabs?

**Comment by iampearceman** [comment]
Hey @jgoerner, any updates on this issue?

**Comment by iampearceman** [comment]
Hey @jgoerner, any updates on this issue?
