### ISSUE TITLE
UI issues in Settings menu, Branding Tab

### ISSUE THREAD

**Issue by amirhmoradi** [novuhq/novu#840]
**Describe the bug**
In "Settings" Menu, "Branding" tab:
* Logo is streched and not showing properly ( rendered size 80x100, original logo size: 512x512)
* I cannot input HEX code in the Brand color input field, quite impossible to get my brand color if not a standard one.
* The Font Family seems to be from Google Fonts, maybe better if we have a full list (or a search box) to choose the our own, the current selection is very limited.

**To Reproduce**
1. Go to 'Settings' menu from your account
2. Click on 'Branding' tab
3. Try to upload a square logo, change your brand color, choose a Font.

**Expected behavior**
Logo should be square (or with the same aspect ratio as uploaded)
Brand color input shall accept custom hex color code
Font family shall show a full Google Fonts list or provide a search box for search and select.

**Screenshots**
<img width="1124" alt="Screenshot 2022-07-13 at 20 37 14" src="https://user-images.githubusercontent.com/1281163/178812601-af500776-800d-44c3-a2ef-144f0345947e.png">

**Details (please complete the following information):**
 - OS: Mac
- Live Novu platform

**Additional context**
None

**Comment by muhammadawais-rogers** [comment]
i have tested and did it in my local. assign this to me, i have already did this in Novu by inspecting it. thanks

**Comment by scopsy** [comment]
@muhammadawais-rogers Thanks! :)

**Comment by nawed2611** [comment]
Hey, is this issue open to work on?

**Comment by scopsy** [comment]
@nawed2611 really up to @muhammadawais-rogers not sure if he got the time to go over it yet :)

**Comment by nawed2611** [comment]
Sure!

**Comment by oba2311** [comment]
Hi guys, how's it going? @nawed2611  @muhammadawais-rogers

**Comment by TheLearneer** [comment]
Hi @scopsy I can work on solving this issue if this is something that is still in the todo list.

And just let me know if the following are the things I need to do:
1. Maintain the aspect ratio of 1:1 for image container, and put `justify-content: contain` if the image has different aspect ratio
2. Make the color picker to have text based users input (can be easily done by modifying props of mantine component)
3. Make the select component searchable (can be easily done with mantine as well)

**Comment by scopsy** [comment]
@TheLearneer sounds like a plan!

**Comment by TheLearneer** [comment]
Hi @scopsy 👋 

So, point `1.` and `2.` are done with ease.
But for `3.` I need to discuss something with you.

It seems the current `Select` component in the design-system has a custom filter function which removes all the items which are not selected.
So when I make the Select component searchable as discussed in this issue, we will see only the selected element.

We can fix it by adding an optional prop to the Select component in the design system.
However if you know any better idea, do let me know.

**Comment by scopsy** [comment]
So to make sure I got it right, what prop are you suggesting to add for the component?
