### ISSUE TITLE
Team Members management

### ISSUE THREAD

**Issue by amirhmoradi** [novuhq/novu#841]
**Describe the bug**
As a team admin, I need to be able to remove/re-invite/change role for team members.
(bonus) When I am not an admin, there is no need to see full email addresses of my team colleagues.

**To Reproduce**
1. Go to 'Team Members' menu
2. Add a team member by inviting via email
3. Try to remove the newly invited team member -> no way
4. Try to resent the invite for the pending new team member -> no way

**Expected behavior**
As admin, we should be able to remove team members, change their roles (admin / member), and re-send invite for pending members.
As member (not admin), do not reveal other user emails. (in my case I work with multiple freelancers that do not want their emails exposed)

**Screenshots**
<img width="1107" alt="Screenshot 2022-07-13 at 20 34 00" src="https://user-images.githubusercontent.com/1281163/178814285-25356c7f-2005-4082-ad00-0e0e089ca30a.png">

**Details (please complete the following information):**
 - OS: Mac
 - Chrome browser, latest
 - Hosted Novu platform (https://web.novu.co/team)

**Additional context**
None

**Comment by Nike682631** [comment]
@scopsy  Is this issue available to work on?

**Comment by scopsy** [comment]
Hi @Nike682631 looks like this was already implemented and merged 🙏
