### ISSUE TITLE
Clarify API Keys vs Application Identifier

### ISSUE THREAD

**Issue by amirhmoradi** [novuhq/novu#842]
## What?
In 'Settings' menu, 'Api Keys' tab, I am not expecting to have my 'Application identifier', it is confusing.

On the other hand, to enable HMAC for subscriberId encryption, the documentation does not make it clear enough and I got confused between API key and Application identifier to use for hashing.

## Why?
To make it easier for developers to understand the mechanism and have a better integration experience.

## How?
Either the tab name may be changed from 'Api Keys' to something more generic, or the application identifier can be moved somewhere else like below the "Development / Production" switch thingy.

Also the documentation shall be updated to make it clear that the API key is used to create the HMAC and not the APP ID.

## Other information
None

**Comment by Anishpras** [comment]
@scopsy May I work on this? If yes, how would you like me to proceed?

**Comment by Nike682631** [comment]
@scopsy  Is this issue available to work on?

**Comment by scopsy** [comment]
Sure @Nike682631 do you have some ideas on how this can be solved and be more clear? Maybe see how other applications treat those situations?

**Comment by Susmita-Dey** [comment]
I want to take this up but not sure how to solve it. Maybe I can try it out after my exams(20th Jan)

**Comment by Vrishabhsk** [comment]
Hi can i pick this up?

**Comment by p-fernandez** [comment]
@nknyshov what do you think about this suggestion and the current state of our Settings menu and the API keys tab? Do you think there is room to improve?

**Comment by mpatwa98** [comment]
I would like to work on this. Can you assign it to me?

**Comment by davidsoderberg** [comment]
@mpatwa98 you are now assigned :)

**Comment by mpatwa98** [comment]
Can you help me with where to start and how to implement it? @davidsoderberg

**Comment by davidsoderberg** [comment]
Please ask in discord and we will help you out :)

**Comment by Naushadansarinitw** [comment]
hey @amirhmoradi or @davidsoderberg  can i do something "Use this API key to interact with the Novu API and create the HMAC encryption"  or Moved the Application identifier below development/production>..

Reference:
![Screenshot 2023-10-17 230920](https://github.com/novuhq/novu/assets/113180514/6a794c09-c338-419c-8053-1e3bbb54b27b)
