### ISSUE TITLE
UI Bug in Settings menu, In App Center tab

### ISSUE THREAD

**Issue by amirhmoradi** [novuhq/novu#843]
**Describe the bug**
When in settings page, if I switch from Development to Production (from top left menu), the content of the 'In App Center' tab, in the 'Security' section does not refresh.

**To Reproduce**

1. In 'Development' environment, in 'Settings' menu, 'In App Center' tab, **disable** HMAC
2. In 'Production' environment, in 'Settings' menu, 'In App Center' tab, **enable** HMAC
3. Go to any other page (ex 'Notifications')
4. Select 'Development' environment
5. Go back to 'Settings' menu, 'In App Center' tab => HMAC is disabled
6. Switch the environment to 'Production' (do not change page)
7. See the error: HMAC shows as 'disabled' but should be enabled.
8. In the same 'Production' environment, refresh the page or change tabs and come back, HMAC shows as **enabled**.

**Expected behavior**
Page contents shall be fully updated when we switch environments. There should be some kind of guarantee for that as it is supposed to behave as 2 distinct environments.

**Screenshots**
<img width="471" alt="Screenshot 2022-07-13 at 21 41 03" src="https://user-images.githubusercontent.com/1281163/178819192-c9003361-6483-4a55-ac13-29fb7e5f39c0.png">
<img width="453" alt="Screenshot 2022-07-13 at 21 40 46" src="https://user-images.githubusercontent.com/1281163/178819195-d9126dda-756e-4b0d-9b4f-7b9fe839ea99.png">

**Details (please complete the following information):**
 - OS: Mac
 - Hosted Novu live platform (https://web.novu.co/settings)

**Additional context**
None

**Comment by muhammadawais-rogers** [comment]
assign this to me please. thanks

**Comment by scopsy** [comment]
Thank you @muhammadawais-rogers, just did

**Comment by scopsy** [comment]
@muhammadawais-rogers how are you? Do you need any help with this? Let me know if I can be of any help here

**Comment by aggmoulik** [comment]
@scopsy Can I pick this up ?

**Comment by scopsy** [comment]
Sure thing, @muhammadawais-rogers I will un-assign you now. If you did start to work on it please let me know 🙏

**Comment by aggmoulik** [comment]
@scopsy Can you help me with setting up the different environment for development and production.
