### ISSUE TITLE
Disable 'delete template' on production

### ISSUE THREAD

**Issue by djabarovgeorge** [novuhq/novu#846]
**Describe the bug**
You can see that the button of the 'delete template' is clickable.

**To Reproduce**
1. Go to https://web.novu.co/templates/edit/

**Expected behavior**
The production environment should be only read-only.

**Screenshots**
![image](https://user-images.githubusercontent.com/39195835/178928494-bbe6a158-1c34-4e7a-a4c5-ff7e20dd26ff.png)

**Comment by WinterCore** [comment]
Hey. Can I take this?
Also do we wanna remove the button completely, or just disable it and show a tooltip?

**Comment by scopsy** [comment]
@WinterCore i think we can just remove it, wdyt?

**Comment by davidsoderberg** [comment]
@scopsy disable everything else today maybe we should follow that pattern?

**Comment by djabarovgeorge** [comment]
I tend to agree with David following the same pattern will be more intuitive, won't it?

**Comment by scopsy** [comment]
Let's do it :)
