### ISSUE TITLE
Validate the the existence of a template on activity page render

### ISSUE THREAD

**Issue by djabarovgeorge** [novuhq/novu#847]
**Describe the bug**
If the user deleted a template, we need to make sure we validate the check if the template exists or not, because if we do not the page will crash.

**To Reproduce**
1. Go to Activity Page 

**Expected behavior**
The page should not crash if a template was deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/39195835/178931862-1e293e3d-8d15-45a7-8402-6afedec59dd8.png)

**Additional context**
In order to approach this issue you will need to go to the component: 
https://github.com/novuhq/novu/blob/main/apps/web/src/pages/activities/ActivitiesPage.tsx

see the subscriber handle on the same issue:
https://github.com/novuhq/novu/blob/3fa67b1eac9fe4b40c93ca7b506173260bd5d003/apps/web/src/pages/activities/ActivitiesPage.tsx#L95

**Comment by scopsy** [comment]
Closed in #913
