### ISSUE TITLE
Allow non AWS infrastructure setups NV-681

### ISSUE THREAD

**Issue by alaboudi** [novuhq/novu#865]
## What?
Currently, Novu is coupled to AWS through its .env config. It would be nice to allow a developer to setup with an alternative infrastructure provider, such as Google Cloud Platform (a.k.a GCP), instead.

## Why?
Some company's are known to be a complete AWS, GCP, or Azure shop. They wouldn't be able to adopt this repo on-prem if they were not on AWS. The only way about this is to fork this repo, update the AWS logic, and replace it with a GCP one. Adding logic to a forked repo just makes it a little harder to keep it up to date with the upstream source. It would be best if we can avoid that and make the adoption to this repo a little easier.

## How?
A potentially better experience might be to allow a developer to either specify the minimum GCP, AWS, or Azure configurations to get the application running with their chosen infrastructure provider. Since I'm only writing because I'm interested in GCP, I'll list out the items that should be done for that.

1. .env.example. : demonstrate the GCP related configs that can be potentially placed there (i.e `GCP_SECRETY_ACCESS_KEY`, `GCS_REGION`, etc). I'm not fully sure what minimum information is required to store items in Google Cloud Storage, but those would have to be laid out in this file. 
2. env-validator.ts : Update to see if either S3 or GCS (Google Cloud Storage) information has been provided. If not, an error can be thrown.
3. storage.service.ts: Update this file to provide to determine whether to store items in GCP or in AWS. To make this scalable, beyond the GCP scope,  it may make sense to create 1 file per provider (i.e. S3StorageService and a GCSStorageService) with a common interface. Then, storage.service.ts, can be used to simply select between the different tech depending on the env configs.

More work may be required, but I think this is all that's necessary.

**Comment by oba2311** [comment]
Sounds like a good request to me  - @scopsy  WDYT?  Can this be communitized?

**Comment by scopsy** [comment]
Thanks for the suggestion @alaboudi !

I definitely thinks it's ok to introduce another `StorageService` to interact with GCP depending on the actually provided keys. We can use the existence of `S3_BUCKET_NAME` or `GCP_BUCKET_NAME` to identify which storage service to actually use. 

Same methodology might be relevant when using other cloud-related services in the future.

**Comment by alaboudi** [comment]
Yes, exactly what I was thinking. We can let the `StorageService`, or any other service concerned with infrastructure, to abstract away any cloud-service providers. And ya, I like the idea of using something like the key used for the bucket name as the discriminator to decide between cloud storage providers

**Comment by oba2311** [comment]
Cool, then @alaboudi  are you going to take this one?
No pressure, but if you need this little fix fast, then that would be the fastest way :)

**Comment by alaboudi** [comment]
I can take this on. First Novu contribution 🙌

**Comment by davidsoderberg** [comment]
@alaboudi I have assigned you now :)

**Comment by alaboudi** [comment]
I'm unassigning myself in favor of @Lian1230. He just put up a PR for this https://github.com/novuhq/novu/pull/934

**Comment by scopsy** [comment]
Merged at #934 🥳
