### ISSUE TITLE
Clicking on a menu item in the workflow editor submits the form

### ISSUE THREAD

**Issue by nevo-david** [novuhq/novu#891]
**Describe the bug**
When creating a new workflow, if you click on the menu item without dragging them, it submits the form.
Need to add type="button" on the buttons

**To Reproduce**
1. Create a new workflow
2. Click on a menu item

**Expected behavior**
Nothing happens if you just click

**Comment by scopsy** [comment]
Thanks for the report, uploading a fix at #894
