### ISSUE TITLE
Add tabs style for notification center to theme

### ISSUE THREAD

**Issue by davidsoderberg** [novuhq/novu#896]
## What?
Would like to be able to at least change color on tab border

## Why?
I can customize all other colors in notification center but not the tab borders color

## How?
Add it to the theme

## Other information
<img width="377" alt="Skärmavbild 2022-07-25 kl  07 11 53" src="https://user-images.githubusercontent.com/2233092/180703250-a0f05bc0-f1f8-49a1-9707-c08020ef020d.png">

**Comment by aggmoulik** [comment]
@scopsy I can pick it up.

**Comment by scopsy** [comment]
Sure thing @aggmoulik assigning you!

**Comment by oba2311** [comment]
@aggmoulik good luck! Let us know if you need any help.

**Comment by aggmoulik** [comment]
Hey @oba2311 If you can, I just need a help with notifications, as I am not able to render any notifications.

**Comment by ainouzgali** [comment]
@aggmoulik sure, how can I help?

**Comment by aggmoulik** [comment]
Need some help in triggering notifications to show in my notifications panel for some testing and also not able to run cypress tests.

**Comment by MohammedBajuaifer** [comment]
I can work on this if its available

**Comment by davidsoderberg** [comment]
@MohammedBajuaifer someone is already working on this

**Comment by scopsy** [comment]
@aggmoulik did you managed to figure the sending notification part? I can jump on a call if needed 🙏

**Comment by davidsoderberg** [comment]
Hey @aggmoulik I will unassign you now but if you still like to work on it am happy to help you and assign you again :)

**Comment by jainpawan21** [comment]
I would like to work on this @davidsoderberg !

**Comment by davidsoderberg** [comment]
I have now assigned you now @jainpawan21
