### ISSUE TITLE
Replace moment.js with something lighter in the React notification center component

### ISSUE THREAD

**Issue by WinterCore** [novuhq/novu#898]
More info: https://github.com/novuhq/novu/pull/854#issuecomment-1192069233

**Comment by BiswaViraj** [comment]
@scopsy, @davidsoderberg

So will `date-fns` work or any other library needs to be used?
Also, assign this to me.

**Comment by scopsy** [comment]
@BiswaViraj I think `date-fns` will be great, assigning 🙏

**Comment by aggmoulik** [comment]
@BiswaViraj dayjs would be more good choice vs date-fns.

**Comment by crismxiex** [comment]
Is this issue still open?

**Comment by scopsy** [comment]
@BiswaViraj did you had a chance to start working on this? If not, let me know and I can assign @crismxiex for this one 🙏

**Comment by BiswaViraj** [comment]
@scopsy , I've just done the bare minimum setup for it, been traveling this week, so I'm not able to get back to it till Saturday or Sunday when I reach home.
I'm fine with @crismxiex working on this, if he is interested.

**Comment by crismxiex** [comment]
@BiswaViraj Apologize I was checking on the phone and I missed this issue was already assigned.

**Comment by scopsy** [comment]
No worries @crismxiex just assigned you for this one 🚀

**Comment by scopsy** [comment]
Yes 🙏

**Comment by scopsy** [comment]
Sorry @crismxiex looks like it was already implemented at #1032

**Comment by crismxiex** [comment]
All good glad it was fixed
