### ISSUE TITLE
Intercom Implementation (Ways to submit feedback)

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#911]
### Discussed in https://github.com/orgs/novuhq/discussions/632

Intercom will be used to collect feedback as well as send emails to new users.

<div type='discussions-op-text'>

<sup>Originally posted by **oba2311** June  8, 2022</sup>
**How would you want to submit your feedback? Intercom? Email? Discord bots?**

We would love your feedback on how to gather feedback (see what we did here 🤯 ). We are always looking to improve the ways we work and it is time that we make it easier for our community to submit feedback.

Comment with your take - what would work best for you?

**Context:**

As a community-first company, it is most important for us to be able to capture valuable feedback so we can build the things our community wants. 

**DoD / Acceptance Criteria:**

The solution would have to allow a streamlined feedback pipeline that will allow us to consolidate feedback into a roadmap.

**Localization:** 

At the moment we are looking to gather feedback in English.</div>

**Comment by scopsy** [comment]
Working on a PR to add support for this, will be merged to day 🥳
