### ISSUE TITLE
User should be logged out when API sends 401 Unauthorized error

### ISSUE THREAD

**Issue by chavda-bhavik** [novuhq/novu#918]
**Describe the bug**
The user should be logged out when API sends **401 Unauthorized** error

**To Reproduce**
1. Login with credentials
2. Wait for **1 day** till the token expires or modify the `auth_token` manually in localstorage.
3. Refresh the page
4. See API throwing **401** errors but user stay signed in.

**Expected behavior**
The user should be logged out when API throws a 401 error.

**Screenshots**
![image](https://user-images.githubusercontent.com/50201755/181683639-18299d6c-ebbe-4006-8c1c-ab989b5fcb6c.png)

**Details (please complete the following information):**
 - OS: [e.g. Linux]
 - Node Version [e.g. v16.15.1]

**Comment by davidsoderberg** [comment]
@chavda-bhavik did you like to work on this?

**Comment by chavda-bhavik** [comment]
Yes, @davidsoderberg I would like to work on it.
