### ISSUE TITLE
Failing e2e test in the notifications-editor.spec.ts file

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#948]
## What?
The e2e test `should edit notification` in the `notifications-editor.spec.ts` file is failing.
In the PR: #937 I've marked it with `it.skip` so it will be skipped by now. 
We should verify the cause and fix it.

## How?
Remove the `.skip` from the test, then run the e2e tests by `pnpm run cypress:open` in the `web` app folder.
Choose the browser and select the `notifications-editor.spec.ts` file.

**Comment by scopsy** [comment]
This was fixed on #949 and should be ok now 🥳
