### ISSUE TITLE
[FEATURE REQUEST] Add button to go from docs.novu.co to novu.co

### ISSUE THREAD

**Issue by PritamSarbajna** [novuhq/novu#978]
### describe the issue :

In _docs.novu.co_ there isn't anything which redirect user from `docs.novu.co` to `novu.co`

### suggestive solution:

-  We can add a button at navbar to `novu.co`
or
-  adding `novu.co` to the novu logo also solves the problem
or
-  We can add something on footer which will redirect user to `novu.co`

**Comment by PritamSarbajna** [comment]
Hey @ComBarnea I'd love to do it so yeah assign this to me

**Comment by PritamSarbajna** [comment]
also I have a question so you're saying that I should change the link of the logo to `docs.novu.co` to `novu.co` as per [docusaurus.io](https:///docs/api/themes/configuration) ??

**Comment by PritamSarbajna** [comment]
@ComBarnea  also I have a question so you're saying that I should change the link of the logo to `docs.novu.co` to `novu.co` as per [docusaurus.io](https:///docs/api/themes/configuration) ??

**Comment by ComBarnea** [comment]
@PritamSarbajna the question is, should we navigate to Novu's docs, or to the main website when clicking on the logo on the top. Originally I thought it should be to Novu's main website, but after looking into other implementations I think we should **keep** it the way it is.

But add on the footer another link for Home.
<img width="1574" alt="Screen Shot 2022-08-14 at 21 54 04" src="https://user-images.githubusercontent.com/8877285/184551002-83de37d2-3784-4698-84f0-9fdadf29defb.png">

What do you think @PritamSarbajna ?

**Comment by PritamSarbajna** [comment]
Hey @ComBarnea when we click on the logo it takes us to `docs.novu.co` which I think is correct so let it as it is. We can also add HOME as shown above but wouldn't it be odd like `4 : 3`. I'm thinking to add `novu.co` in the footer's novu logo but the question is how will users know that if we click on that it'll take me to `novu.co`

Also I've an idea we can add `novu.co` in footer's logo as well add the link in the footer where copyrights reserved written

**Comment by ComBarnea** [comment]
I think we can navigate the bottom logo to nove.co as a new tab. And for now we can skip the additional link as you suggested. @scopsy any thoughts here?

**Comment by PritamSarbajna** [comment]
Hey @ComBarnea I was not asking for adding a extra link with extra area. I was just asking if we click on this copyright area's words we can also add a link to `novu.co`

**Comment by ComBarnea** [comment]
@PritamSarbajna our docs are managed in our main repo, and not on the website repo. And while we were discussing our design team updated the logo to include documentation. 
![Screen Shot 2022-08-15 at 13 37 26](https://user-images.githubusercontent.com/8877285/184621137-58567f03-a75d-4adf-986d-bfb0280b14c7.png)

I think that adding another column with a Home link would be the best option, as clicking on the copyright area is very unusual.

**Comment by PritamSarbajna** [comment]
Yeah sure @ComBarnea. Now we can't add `novu.co` into the logo. Okay so you're saying make another column not another row ?

**Comment by scopsy** [comment]
I think just adding another row on the existing columng with work there :)

**Comment by scopsy** [comment]
Hi @PritamSarbajna did you had a chance to look at it?

**Comment by PritamSarbajna** [comment]
> Hi @PritamSarbajna did you had a chance to look at it?

Sorry @scopsy I tried but I couldn't run this locally probably I should learn more.

**Comment by vishnu-kyatannawar** [comment]
Hi @scopsy and @ComBarnea 

I would like to work on this feature. Can you please assign this to me?

Here is my understanding regarding about this feature

- We need a way to redirect from `docs.novu.co` to `novu.co`
- Proposed solution is to add a new row as `Home` which can redirect to `novu.co`
- This link will open `novu.co` in a new tab
- This row will be add to the first column as the first link i.e. above documentation

![image](https://user-images.githubusercontent.com/22377238/213285574-054c44f0-5a96-44df-885d-1f5b2764ba1e.png)

**Comment by vishnu-kyatannawar** [comment]
Thanks @jainpawan21 

I have opened a PR https://github.com/novuhq/novu/pull/2528 to address this this.
