### ISSUE TITLE
Wrong response status on missing template

### ISSUE THREAD

**Issue by atompie** [novuhq/novu#986]
**Describe the bug**
Wrong response status on missing template

**To Reproduce**
I have sent na API request with the wrong template name and got this response: 
status: 201
content: {
  data: {
    acknowledged: true
    status: "template_not_found"
  }
}

**Expected behavior**
Some other status 422 maybe

**Comment by Rutam21** [comment]
@scopsy I would love to take this up. Kindly confirm the correct status code and point me to the file that needs to be changed.

**Comment by scopsy** [comment]
Sure @Rutam21, this is handled in the `trigger-event.usecase.ts` file. Nestjs has a NotFoundException you can throw there. Regarding the status I think 404 should be appropriate here @atompie what do you think ?

**Comment by atompie** [comment]
@scopsy well 404 means that there is no endpoint or data. This is not true as the endpoint exists.  422 is en error that indicates that the sent data is incorrect. If you would like a proper rest api then this is the correct status.

**Comment by scopsy** [comment]
Do you think that an entity doesn't exist here? Since the template with the provided identifier doesn't exist. This is why I was thinking about the 404 here. But I think 422 fits here too @Rutam21 🚀

**Comment by dcbartlett** [comment]
I agree with @atompie  here.  404 is SUPPOSED to be used by REST APIs to give feedback that a route does not exist at the given URI.  In this case, the route does exist, thus it is invalid input data that caused the error.  Status code 422 should be the correct code to use here.

**Comment by oba2311** [comment]
😎 
@Rutam21 ping us if you need any help with this :)

**Comment by jainpawan21** [comment]
@Rutam21 Any update on this?

**Comment by scopsy** [comment]
I think that @asedmammad worked on this, but can't find the PR Associated to the fix.

**Comment by asedmammad** [comment]
> I think that @asedmammad worked on this, but can't find the PR Associated to the fix.

Yes, but I did not create the PR since I've noticed that this issue has already been assigned to @Rutam21.

**Comment by scopsy** [comment]
@Rutam21 if you hadn't a chance yet to take a look, please let me know because looks like @asedmammad already implemented this :)

**Comment by Rutam21** [comment]
@scopsy It would be great then if @asedmammad submits the PR as he is already done with that. You can assign it to him.

**Comment by Rutam21** [comment]
@scopsy It would be great then if @asedmammad submits the PR as he is already done with that. You can assign it to him.
